'use strict';
(function(){
  if(window.__partyQuestActiveViewV4)return;
  window.__partyQuestActiveViewV4=true;
  var active=[],seenEvents={},openTaskId=null,reopenQueue=false;
  function currentUid(){try{var u=window.fbUser||(window.fbAuth&&window.fbAuth.currentUser)||firebase.auth().currentUser;return u&&u.uid||null;}catch(e){return null;}}
  function familyId(){return window.fbFamilyId||null;}
  function invitees(q){return q&&q.invitees&&typeof q.invitees==='object'?q.invitees:{};}
  function relevant(q){var me=currentUid(),mine=invitees(q)[me];return q&&q.status==='active'&&(q.inviterUid===me||(mine&&mine.status==='active'));}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function toast(m){if(typeof window.showToast==='function')window.showToast(m);}
  function members(){try{return window.TaskSharedData&&TaskSharedData.members?TaskSharedData.members()||[]:[];}catch(e){return[];}}
  function member(id){return members().find(function(m){return String(m.uid||m.id)===String(id);})||null;}
  function nameOf(id,fallback){var m=member(id);return (m&&(m.displayName||m.name))||fallback||'Gezinslid';}
  function avatarOf(id){var m=member(id);if(!m)return'';try{return m.avatarUrl||m.photoURL||m.profilePhoto||m.avatar||localStorage.getItem('fam_avatar_'+String(m.displayName||m.name||'').toLowerCase())||'';}catch(e){return m.avatarUrl||m.photoURL||m.profilePhoto||m.avatar||'';}}
  function initials(v){return String(v||'G').trim().split(/\s+/).map(function(x){return x.charAt(0);}).join('').slice(0,2).toUpperCase()||'G';}
  function participantRows(q){var out=[];if(q.inviterUid)out.push({uid:q.inviterUid,name:q.inviterName||nameOf(q.inviterUid)});Object.keys(invitees(q)).forEach(function(k){var x=invitees(q)[k];if(x&&x.status==='active'&&!out.some(function(p){return String(p.uid)===String(k);})){out.push({uid:k,name:x.name||nameOf(k)});}});return out;}
  function participantNames(q){return participantRows(q).map(function(p){return p.name;});}
  function avatarStack(q,cls){return participantRows(q).map(function(p){var u=avatarOf(p.uid),n=p.name||nameOf(p.uid);return u?'<img class="'+cls+'" src="'+esc(u)+'" alt="'+esc(n)+'">':'<span class="'+cls+'" title="'+esc(n)+'">'+esc(initials(n))+'</span>';}).join('');}
  function refresh(rows){
    var all=Object.keys(rows||{}).map(function(k){var q=rows[k];if(q&&!q.id)q.id=k;return q;});
    all.forEach(function(q){var ev=q&&q.lastEvent;if(!ev||!ev.id)return;if(!seenEvents[q.id]){seenEvents[q.id]=ev.id;return;}if(seenEvents[q.id]===ev.id)return;seenEvents[q.id]=ev.id;if(ev.actorUid!==currentUid()&&relevant(q))toast(ev.message||'Party Quest bijgewerkt');});
    active=all.filter(relevant).sort(function(a,b){return Number(b.updatedAt||b.createdAt||0)-Number(a.updatedAt||a.createdAt||0);});decorate();decorateDetail();
    var openEl=document.getElementById('party-quest-active-view');
    if(openEl){if(active.length)open();else openEl.remove();}
  }
  function decorate(){var b=document.getElementById('tch-party-quest');if(!b||!active.length)return;var h=b.querySelector('b'),s=b.querySelector('small');if(h)h.textContent=active.length===1?'1 actieve Party Quest':active.length+' actieve Party Quests';if(s)s.textContent='Tik voor overzicht en beheer';}
  function eventPayload(message){return {id:String(Date.now())+'-'+currentUid(),actorUid:currentUid(),message:message,time:firebase.database.ServerValue.TIMESTAMP};}
  function leave(q){var me=currentUid(),mine=invitees(q)[me];if(!mine)return;var message=(mine.name||'Een gezinslid')+' heeft “'+(q.questTitle||'Party Quest')+'” verlaten';var updates={};updates['invitees/'+me+'/status']='declined';updates['invitees/'+me+'/respondedAt']=firebase.database.ServerValue.TIMESTAMP;updates.updatedAt=firebase.database.ServerValue.TIMESTAMP;updates.lastEvent=eventPayload(message);firebase.database().ref('families/'+familyId()+'/partyQuests/'+q.id).update(updates).then(function(){toast('Je hebt “'+(q.questTitle||'Party Quest')+'” verlaten');});}
  function end(q){var message=(q.inviterName||'De maker')+' heeft “'+(q.questTitle||'Party Quest')+'” beëindigd';firebase.database().ref('families/'+familyId()+'/partyQuests/'+q.id).update({status:'completed',endedAt:firebase.database.ServerValue.TIMESTAMP,updatedAt:firebase.database.ServerValue.TIMESTAMP,lastEvent:eventPayload(message)}).then(function(){toast('Party Quest beëindigd');});}
  function open(){
    if(!active.length){var stale=document.getElementById('party-quest-active-view');if(stale)stale.remove();return false;}
    var old=document.getElementById('party-quest-active-view');if(old)old.remove();var me=currentUid();var e=document.createElement('div');e.id='party-quest-active-view';e.style.cssText='position:fixed;inset:0;z-index:10120;background:rgba(8,7,15,.68);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:16px';
    e.innerHTML='<div style="width:min(440px,100%);max-height:82vh;overflow:auto;border-radius:24px;background:linear-gradient(180deg,#171126,#0f0d18);border:1px solid rgba(216,181,82,.48);padding:20px;color:#fff"><style>.pqav-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.pqav-avatars{display:flex;align-items:center;padding-left:8px}.pqav-avatar{width:31px;height:31px;border-radius:50%;margin-left:-8px;display:grid;place-items:center;object-fit:cover;overflow:hidden;background:linear-gradient(135deg,#6d28d9,#a855f7);color:#fff;border:2px solid #1b1726;box-shadow:0 0 0 1px rgba(216,181,82,.65);font-size:9px;font-weight:900}.pqav-avatar:first-child{margin-left:0}</style><h3 style="margin:0;font:800 20px Georgia,serif">Actieve Party Quests</h3><p style="color:#aaa1b4;font-size:12px">'+active.length+' actieve groepsquest'+(active.length===1?'':'s')+'</p>'+active.map(function(q){var names=participantNames(q),owner=q.inviterUid===me;return '<div style="border:1px solid rgba(255,255,255,.1);background:#1b1726;border-radius:15px;padding:12px;margin-top:10px"><div class="pqav-head"><div style="min-width:0"><b style="display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+esc(q.questTitle||'Party Quest')+'</b><small style="display:block;color:#a9a0b3;margin-top:4px">'+(names.length?'Party: '+esc(names.join(', ')):'Geen andere actieve deelnemers')+'</small></div><div class="pqav-avatars">'+avatarStack(q,'pqav-avatar')+'</div></div><button data-action="'+(owner?'end':'leave')+'" data-id="'+esc(q.id)+'" style="width:100%;margin-top:10px;border:0;border-radius:12px;padding:10px;background:#3a1720;color:#ffb3c0;font-weight:800">'+(owner?'Beëindigen':'Verlaten')+'</button></div>';}).join('')+'<button data-close style="width:100%;margin-top:16px;border:0;border-radius:14px;padding:12px;background:#262130;color:#c9c0d1;font-weight:800">Sluiten</button></div>';
    document.body.appendChild(e);e.onclick=function(ev){if(ev.target===e)e.remove();};e.querySelector('[data-close]').onclick=function(){e.remove();};e.querySelectorAll('[data-action]').forEach(function(b){b.onclick=function(){var q=active.find(function(x){return String(x.id)===String(b.getAttribute('data-id'));});if(!q)return;if(b.getAttribute('data-action')==='end')end(q);else leave(q);};});return true;
  }
  function ensureDetailCss(){if(document.getElementById('party-quest-detail-css'))return;var s=document.createElement('style');s.id='party-quest-detail-css';s.textContent='.tdp-party-strip{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:0 0 9px;padding:8px 10px;border-radius:13px;border:1px solid rgba(164,120,36,.32);background:linear-gradient(135deg,rgba(109,40,217,.10),rgba(202,161,83,.10))}.tdp-party-copy{min-width:0}.tdp-party-label{font-family:"Cinzel",Georgia,serif;font-size:9px;font-weight:800;letter-spacing:1px;text-transform:uppercase;color:var(--tdp-gold)}.tdp-party-sub{font-size:10.5px;color:var(--tdp-text2);margin-top:2px}.tdp-party-avatars{display:flex;align-items:center;flex:0 0 auto;padding-left:8px}.tdp-party-avatar{width:29px;height:29px;border-radius:50%;margin-left:-8px;display:grid;place-items:center;overflow:hidden;object-fit:cover;background:linear-gradient(135deg,#6d28d9,#a855f7);color:#fff;border:2px solid var(--tdp-surface);box-shadow:0 0 0 1px rgba(202,161,83,.65);font-size:9px;font-weight:900}.tdp-party-avatar:first-child{margin-left:0}';document.head.appendChild(s);}
  function decorateDetail(){if(!openTaskId)return;var body=document.querySelector('#tdp-overlay .tdp-body');if(!body)return;var old=body.querySelector('.tdp-party-strip');if(old)old.remove();var q=active.find(function(x){return String(x.questId)===String(openTaskId);});if(!q)return;var people=participantRows(q);if(people.length<2)return;ensureDetailCss();var anchor=body.querySelector('.tdp-person');if(!anchor)return;var strip=document.createElement('div');strip.className='tdp-party-strip';strip.innerHTML='<div class="tdp-party-copy"><div class="tdp-party-label">⚔ Groepsquest</div><div class="tdp-party-sub">'+esc(people.map(function(p){return p.name;}).join(' & '))+'</div></div><div class="tdp-party-avatars">'+avatarStack(q,'tdp-party-avatar')+'</div>';anchor.parentNode.insertBefore(strip,anchor.nextSibling);}
  function hookDetail(){var tries=0,t=setInterval(function(){tries++;if(window.TaskDetailPopup&&typeof window.TaskDetailPopup.open==='function'&&!window.TaskDetailPopup.__partyActiveWrapped){var orig=window.TaskDetailPopup.open;window.TaskDetailPopup.open=function(id){openTaskId=id;var r=orig.apply(this,arguments);setTimeout(decorateDetail,0);setTimeout(decorateDetail,100);return r;};window.TaskDetailPopup.__partyActiveWrapped=true;clearInterval(t);}else if(tries>80)clearInterval(t);},100);var mo=new MutationObserver(function(){if(openTaskId)setTimeout(decorateDetail,0);});if(document.body)mo.observe(document.body,{childList:true,subtree:true});else window.addEventListener('load',function(){mo.observe(document.body,{childList:true,subtree:true});});}
  function hookQueue(){document.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('#party-quest-invite-modal [data-yes],#party-quest-invite-modal [data-no]');if(!b||!window.PartyQuestInvites||typeof window.PartyQuestInvites.pending!=='function')return;if(window.PartyQuestInvites.pending().length>1)reopenQueue=true;},true);setInterval(function(){if(!reopenQueue)return;var p=window.PartyQuestInvites&&window.PartyQuestInvites.pending?window.PartyQuestInvites.pending():[];if(p.length&&!document.getElementById('party-quest-invite-modal')){reopenQueue=false;setTimeout(function(){if(window.PartyQuestInvites)window.PartyQuestInvites.open();},40);}else if(!p.length)reopenQueue=false;},120);}
  function start(){try{if(!familyId()||!currentUid())return false;firebase.database().ref('families/'+familyId()+'/partyQuests').on('value',function(s){refresh(s.val()||{});});return true;}catch(e){return false;}}
  document.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('#tch-party-quest');if(!b||!active.length)return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();open();},true);
  hookDetail();hookQueue();
  window.PartyQuestActiveView={open:open,list:function(){return active.slice();},start:start};
  var tries=0,t=setInterval(function(){tries++;if(start()||tries>80)clearInterval(t);},250);
})();
