'use strict';
// ============================================================
// PARTY QUEST CONTEXT UI v1.0
// Compatibility UI facade backed only by PartyQuestContextService.
// ============================================================
(function(){
  if(window.__partyQuestContextUiV1)return;
  window.__partyQuestContextUiV1=true;

  var modalId='party-quest-invite-modal';
  function svc(){return window.PartyQuestContextService||null;}
  function ctx(){return window.HouseholdContext||null;}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function toast(m){if(typeof window.showToast==='function')window.showToast(m);}
  function close(){var e=document.getElementById(modalId);if(e)e.remove();}
  function ensureCss(){if(document.getElementById('party-quest-context-css'))return;var s=document.createElement('style');s.id='party-quest-context-css';s.textContent='.pqc-overlay{position:fixed;inset:0;z-index:10090;background:rgba(8,7,15,.66);backdrop-filter:blur(8px);display:flex;align-items:flex-end;justify-content:center;padding:16px}.pqc-card{width:min(440px,100%);max-height:82vh;overflow:auto;border-radius:24px;background:linear-gradient(180deg,#171126,#0f0d18);border:1px solid rgba(216,181,82,.48);box-shadow:0 24px 70px rgba(0,0,0,.5);padding:20px;color:#fff}.pqc-head{display:flex;gap:12px;align-items:center;margin-bottom:14px}.pqc-crest{width:46px;height:50px;display:grid;place-items:center;clip-path:polygon(50% 0,92% 14%,86% 70%,50% 100%,14% 70%,8% 14%);background:linear-gradient(160deg,#cfa94d,#8f6923);font-size:20px}.pqc-head h3{margin:0;font:800 20px/1.1 Georgia,serif}.pqc-head p{margin:4px 0 0;color:#bdb4c8;font-size:12px;line-height:1.4}.pqc-list{display:grid;gap:9px;margin:12px 0}.pqc-row{width:100%;display:flex;align-items:center;gap:10px;border:1px solid rgba(255,255,255,.1);background:#1b1726;color:#fff;border-radius:15px;padding:11px;text-align:left}.pqc-row.is-selected{border-color:#d8b552;background:#2a2038}.pqc-row b{display:block;font-size:13px}.pqc-row small{display:block;color:#9f96aa;font-size:10px;margin-top:2px}.pqc-actions{display:flex;gap:9px;margin-top:15px}.pqc-btn{flex:1;border:0;border-radius:14px;padding:12px 14px;font-weight:800}.pqc-gold{background:linear-gradient(135deg,#d1ac55,#9e7425);color:#21160a}.pqc-muted{background:#262130;color:#c9c0d1}.pqc-danger{background:#3a1720;color:#ffb3c0}.pqc-focus{font:800 17px/1.25 Georgia,serif;color:#f0d78c;margin:10px 0 4px}';document.head.appendChild(s);}
  function modal(html){ensureCss();close();var e=document.createElement('div');e.id=modalId;e.className='pqc-overlay';e.innerHTML='<div class="pqc-card">'+html+'</div>';document.body.appendChild(e);e.onclick=function(ev){if(ev.target===e)close();};return e;}
  function me(){try{return ctx().requireUser();}catch(e){return null;}}
  function members(){try{return window.TaskSharedData&&TaskSharedData.members?TaskSharedData.members()||[]:[];}catch(e){return[];}}
  function memberId(m){return m&&(m.uid||m.id)||null;}
  function taskById(id){return (window.taskData||[]).find(function(t){return String(t&&t.id)===String(id);})||null;}
  function isCreator(t,uid){return !!(t&&uid&&String(t.createdByUid||t.ownerUid||'')===String(uid));}
  function openTasks(){var uid=me();return (window.taskData||[]).filter(function(t){var st=String(t&&t.status||'').toLowerCase();return t&&t.id&&!t.done&&!t.completed&&st!=='done'&&st!=='completed'&&isCreator(t,uid);});}
  function current(){var list;try{list=svc().relevant();}catch(e){return null;}list=list.filter(function(q){return q&&q.status!=='cancelled'&&q.status!=='completed';}).sort(function(a,b){return Number(b.updatedAt||b.createdAt||0)-Number(a.updatedAt||a.createdAt||0);});return list[0]||null;}
  function pending(){try{return svc().pending();}catch(e){return[];}}
  function chooseQuest(){var tasks=openTasks();if(!tasks.length){toast('Je hebt geen zelf gestarte open quests om te delen');return;}var selected=null,e=modal('<div class="pqc-head"><div class="pqc-crest">⚔</div><div><h3>Start een Party Quest</h3><p>Kies een quest die jij zelf hebt gestart.</p></div></div><div class="pqc-list">'+tasks.map(function(t){return '<button class="pqc-row" data-q="'+esc(t.id)+'"><span><b>'+esc(t.title||'Naamloze quest')+'</b><small>'+esc(t.xp||t.xpReward||'Quest')+'</small></span></button>';}).join('')+'</div><div class="pqc-actions"><button class="pqc-btn pqc-muted" data-close>Annuleren</button><button class="pqc-btn pqc-gold" data-next>Deelnemers kiezen</button></div>');e.querySelector('[data-close]').onclick=close;e.querySelectorAll('[data-q]').forEach(function(b){b.onclick=function(){selected=b.getAttribute('data-q');e.querySelectorAll('[data-q]').forEach(function(x){x.classList.toggle('is-selected',x===b);});};});e.querySelector('[data-next]').onclick=function(){if(!selected){toast('Kies een quest');return;}choosePeople(selected);};}
  function choosePeople(taskId){var uid=me(),task=taskById(taskId);if(!isCreator(task,uid)){toast('Alleen de maker kan deelnemers uitnodigen');return;}var blocked={};if(task.assignedToUids)Object.keys(task.assignedToUids).forEach(function(id){if(task.assignedToUids[id])blocked[String(id)]=true;});if(task.assignedToUid)blocked[String(task.assignedToUid)]=true;blocked[String(uid)]=true;try{svc().list().forEach(function(q){if(!q||String(q.questId)!==String(taskId)||q.status==='cancelled'||q.status==='completed')return;if(q.inviterUid)blocked[String(q.inviterUid)]=true;Object.keys(q.invitees||{}).forEach(function(id){var x=q.invitees[id];if(x&&(x.status==='pending'||x.status==='active'))blocked[String(id)]=true;});});}catch(e){}var list=members().filter(function(m){var id=memberId(m);return id&&!blocked[String(id)];});if(!list.length){toast('Alle gezinsleden doen al mee of hebben een uitnodiging');return;}var chosen={},e=modal('<div class="pqc-head"><div class="pqc-crest">⚔</div><div><h3>Deelnemers kiezen</h3><p>Alleen beschikbare gezinsleden worden getoond.</p></div></div><div class="pqc-list">'+list.map(function(m){var id=memberId(m),name=m.displayName||m.name||'Gezinslid';return '<button class="pqc-row" data-p="'+esc(id)+'"><span><b>'+esc(name)+'</b><small>Gezinslid uitnodigen</small></span></button>';}).join('')+'</div><div class="pqc-actions"><button class="pqc-btn pqc-muted" data-back>Terug</button><button class="pqc-btn pqc-gold" data-send>Uitnodigen</button></div>');e.querySelector('[data-back]').onclick=chooseQuest;e.querySelectorAll('[data-p]').forEach(function(b){b.onclick=function(){var id=b.getAttribute('data-p');chosen[id]=!chosen[id];b.classList.toggle('is-selected',!!chosen[id]);};});e.querySelector('[data-send]').onclick=function(){var ids=Object.keys(chosen).filter(function(k){return chosen[k];});if(!ids.length){toast('Kies minstens één gezinslid');return;}svc().createInvites(taskId,ids).then(function(){close();toast('Party Quest-uitnodiging verstuurd');}).catch(function(err){toast((err&&err.message)||'Uitnodigen mislukt');});};}
  function incoming(q){var e=modal('<div class="pqc-head"><div class="pqc-crest">⚔</div><div><h3>Party Quest-uitnodiging</h3><p><b>'+esc(q.inviterName||'Gezinslid')+'</b> nodigt je uit voor:</p></div></div><div class="pqc-focus">'+esc(q.questTitle||'Party Quest')+'</div><div class="pqc-actions"><button class="pqc-btn pqc-muted" data-no>Weigeren</button><button class="pqc-btn pqc-gold" data-yes>Accepteren</button></div>');e.querySelector('[data-no]').onclick=function(){respond(q,'declined');};e.querySelector('[data-yes]').onclick=function(){respond(q,'active');};}
  function showStatus(q){if(!q){chooseQuest();return;}var uid=me(),mine=q.invitees&&q.invitees[uid];if(mine&&mine.status==='pending'){incoming(q);return;}var e=modal('<div class="pqc-head"><div class="pqc-crest">⚔</div><div><h3>'+(q.status==='active'?'Party Quest actief':'Uitnodiging verstuurd')+'</h3><p>'+esc(q.questTitle||'Party Quest')+'</p></div></div><div class="pqc-focus">'+esc(q.questTitle||'Party Quest')+'</div><div class="pqc-actions"><button class="pqc-btn pqc-muted" data-close>Sluiten</button>'+(String(q.inviterUid)===String(uid)?'<button class="pqc-btn pqc-danger" data-end>Beëindigen</button>':'')+'</div>');e.querySelector('[data-close]').onclick=close;var end=e.querySelector('[data-end]');if(end)end.onclick=function(){svc().end(q.id,q.status==='active'?'completed':'cancelled').then(function(){close();toast('Party Quest beëindigd');}).catch(function(err){toast((err&&err.message)||'Actie mislukt');});};}
  function open(){var p=pending();if(p.length){incoming(p[0]);return;}var q=current();if(q)showStatus(q);else chooseQuest();}
  function respond(q,status){if(!q)return Promise.resolve(false);return svc().respond(q.id,status).then(function(){close();toast(status==='active'?'Party Quest geaccepteerd':'Party Quest geweigerd');return true;}).catch(function(err){toast((err&&err.message)||'Actie mislukt');return false;});}
  function revokeInvite(qid,targetUid){return svc().revokeInvite(qid,targetUid).then(function(){toast('Uitnodiging ingetrokken');return true;});}
  function decorate(){var b=document.getElementById('tch-party-quest');if(!b)return;var h=b.querySelector('b'),s=b.querySelector('small'),p=pending(),q=current();if(p.length){if(h)h.textContent=p.length===1?'Party Quest-uitnodiging':p.length+' Party Quest-uitnodigingen';if(s)s.textContent=p[0].questTitle||'Tik om te bekijken';return;}if(!q){if(h)h.textContent='Party Quest starten';if(s)s.textContent='Nodig beschikbare gezinsleden uit';return;}if(h)h.textContent=q.status==='active'?'Party Quest actief':'Uitnodiging verstuurd';if(s)s.textContent=q.questTitle||'Party Quest';}

  window.addEventListener('click',function(e){var b=e.target&&e.target.closest&&e.target.closest('#tch-party-quest');if(!b)return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();open();},true);
  window.addEventListener('familyapp:party-quests-updated',function(){decorate();if(pending().length&&!document.getElementById(modalId))decorate();});
  window.addEventListener('familyapp:tasks-updated',decorate);
  window.addEventListener('familyapp:household-context-changed',function(){close();decorate();});
  window.PartyQuestInvites={version:'6.0-context',start:function(){return svc()&&svc().start();},open:open,current:current,pending:pending,getById:function(id){return svc()&&svc().get(id);},revokeInvite:revokeInvite,respond:respond};
  Promise.resolve().then(function(){if(svc())svc().start();decorate();});
})();
