'use strict';
// ============================================================
// PERSOON TAB PREMIUM v4.4
// UID-first renderer over PersonDashboardService.
// Visual language follows the premium Taken overview.
// ============================================================
(function(){
  if(window.__personTabPremiumV44)return;
  window.__personTabPremiumV44=true;

  var VERSION='4.4.0';
  var selectedUid=null,currentTarget=null,unsubscribe=null,serviceLoading=false;
  var PALETTES=[
    {accent:'#a78bfa',glow:'rgba(124,58,237,.42)',hero:'linear-gradient(135deg,#211744,#4b2c7e 55%,#101426)'},
    {accent:'#f0abfc',glow:'rgba(217,70,239,.34)',hero:'linear-gradient(135deg,#35152f,#783866 55%,#151020)'},
    {accent:'#fbbf24',glow:'rgba(245,158,11,.30)',hero:'linear-gradient(135deg,#31230d,#715522 55%,#17130d)'},
    {accent:'#5eead4',glow:'rgba(20,184,166,.30)',hero:'linear-gradient(135deg,#102e2b,#236c63 55%,#0d1718)'}
  ];
  var AREA={home:'Home',tasks:'Taken',shop:'Boodschappen',recipes:'Recepten',notes:'Notities',cal:'Agenda',calendar:'Agenda',finance:'Financiën',achievements:'Achievements',skills:'Skills',meals:'Maaltijden',profile:'Profiel',feed:'Feed'};

  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function clamp(v){return Math.max(0,Math.min(100,Math.round(Number(v)||0)));}
  function palette(i){return PALETTES[i%PALETTES.length];}
  function initials(m){if(m&&m.initials)return m.initials;return String(m&&m.displayName||'?').split(/\s+/).filter(Boolean).map(function(x){return x.charAt(0);}).join('').slice(0,2).toUpperCase()||'?';}
  function areaLabel(area){var k=String(area||'').toLowerCase();return AREA[k]||(area?String(area).charAt(0).toUpperCase()+String(area).slice(1):'de app');}
  function relative(ts){var n=Number(ts||0);if(!n)return'Offline';var mins=Math.floor(Math.max(0,Date.now()-n)/60000);if(mins<1)return'Zojuist actief';if(mins<60)return mins+' min geleden actief';var h=Math.floor(mins/60);if(h<24)return h+' uur geleden actief';var d=Math.floor(h/24);return d<7?d+(d===1?' dag':' dagen')+' geleden actief':'Offline';}
  function presenceClass(m){return'is-'+((m.presence&&m.presence.state)||'offline');}
  function presenceLabel(m){var p=m.presence||{};if(p.state==='online')return'Online · '+areaLabel(p.area);if(p.state==='recent')return relative(p.lastSeen)+(p.area?' · '+areaLabel(p.area):'');if(p.state==='today')return relative(p.lastSeen);return'Offline';}

  function injectStyles(){
    ['person-tab-premium-style-v4','person-tab-premium-style-v43'].forEach(function(id){var old=document.getElementById(id);if(old)old.remove();});
    if(document.getElementById('person-tab-premium-style-v44'))return;
    var s=document.createElement('style');s.id='person-tab-premium-style-v44';s.textContent=[
      '.task-person-page{--pp-bg:#080a14;--pp-card:rgba(18,19,35,.88);--pp-card2:rgba(29,23,52,.86);--pp-line:rgba(255,255,255,.085);--pp-muted:rgba(237,235,250,.57);background:radial-gradient(90% 42% at 50% 0%,rgba(95,46,164,.28),transparent 72%),linear-gradient(180deg,#0c0e1a 0%,#080912 72%,#070810 100%);margin:0 -16px;padding:46px 16px 112px;min-height:calc(100vh - 120px);color:#f7f5ff;overflow-x:hidden}.task-person-page *{box-sizing:border-box}',
      '#screen-tasks:has(.task-person-page){background:#080912}#screen-tasks:has(.task-person-page) #task-content{position:relative;overflow:visible}#screen-tasks:has(.task-person-page) .task-tabs{background:#0b0d18;border-bottom-color:rgba(255,255,255,.08);z-index:20}#screen-tasks:has(.task-person-page) .ttab{padding:10px 4px;font-size:12px;font-weight:700;color:rgba(244,246,255,.52);border-bottom:2px solid transparent;border-radius:0}#screen-tasks:has(.task-person-page) .ttab.active{color:#d8c8ff;border-bottom-color:#8b5cf6;background:linear-gradient(180deg,rgba(124,58,237,.10),rgba(124,58,237,.02));box-shadow:none}#screen-tasks:has(.task-person-page) .ttab-trade{background:#111322;color:#e8d9ff;border-left-color:rgba(255,255,255,.08)}',
      '.pp-members{display:flex;gap:15px;overflow-x:auto;padding:8px 3px 12px;margin:-24px 0 14px;scrollbar-width:none;min-height:91px;position:relative;z-index:2}.pp-members::-webkit-scrollbar{display:none}.pp-member{flex:0 0 68px;border:0;background:none;color:inherit;padding:0;text-align:center}.pp-avatar-wrap{position:relative;width:58px;height:58px;margin:0 auto 7px}.pp-avatar,.pp-avatar-fallback{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;object-fit:cover;border:2px solid rgba(255,255,255,.16);background:#252338;color:#fff;font-size:14px;font-weight:900}.pp-member.active .pp-avatar,.pp-member.active .pp-avatar-fallback{border-color:var(--accent);box-shadow:0 0 0 2px #0a0c16,0 0 18px var(--glow)}.pp-member-name{font-size:11px;font-weight:850;color:rgba(255,255,255,.66);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pp-member.active .pp-member-name{color:#fff}.pp-member-state{font-size:8.5px;color:rgba(255,255,255,.34);margin-top:2px}.pp-dot{position:absolute;right:-1px;bottom:1px;width:14px;height:14px;border-radius:50%;border:3px solid #0a0c16;background:#59606c}.pp-dot.is-online{background:#22c55e;box-shadow:0 0 9px rgba(34,197,94,.55)}.pp-dot.is-recent{background:#84cc16}.pp-dot.is-today{background:#eab308}',
      '.pp-hero{position:relative;min-height:220px;border-radius:25px;overflow:hidden;padding:19px;display:flex;align-items:flex-end;border:1px solid rgba(150,92,255,.30);background:var(--hero);box-shadow:0 18px 42px rgba(0,0,0,.36),0 0 32px var(--glow);margin-bottom:21px}.pp-hero-bg{position:absolute;inset:0;background-size:cover;background-position:center 25%;opacity:.58;transform:scale(1.02)}.pp-hero:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(8,8,16,.95) 0%,rgba(8,8,16,.72) 46%,rgba(8,8,16,.20) 80%),linear-gradient(180deg,rgba(8,8,16,.08),rgba(8,8,16,.90))}.pp-hero-content{position:relative;z-index:2;width:min(74%,290px)}.pp-name{font-size:25px;font-weight:950;letter-spacing:-.04em;line-height:1}.pp-titleline{font-size:12px;font-weight:850;color:#d8c8ff;margin-top:6px}.pp-presence{display:flex;align-items:center;gap:7px;font-size:10.5px;font-weight:800;color:rgba(255,255,255,.62);margin-top:7px}.pp-presence i{width:7px;height:7px;border-radius:50%;background:#5f6672}.pp-presence.is-online{color:#bbf7d0}.pp-presence.is-online i{background:#22c55e;box-shadow:0 0 8px rgba(34,197,94,.55)}.pp-presence.is-recent i{background:#84cc16}.pp-presence.is-today i{background:#eab308}.pp-level{position:absolute;right:16px;top:16px;z-index:3;width:59px;height:66px;clip-path:polygon(50% 0,94% 18%,94% 72%,50% 100%,6% 72%,6% 18%);display:grid;place-items:center;align-content:center;background:linear-gradient(180deg,#5b21b6,#27104e);filter:drop-shadow(0 7px 12px rgba(0,0,0,.42))}.pp-level:before{content:"";position:absolute;inset:3px;clip-path:inherit;border:1px solid rgba(246,203,103,.82)}.pp-level small{font-size:7px;text-transform:uppercase;font-weight:950;color:#f4d37e}.pp-level strong{font-size:20px;line-height:1;color:#fff4ca}.pp-xp{margin-top:15px}.pp-xp-meta{display:flex;justify-content:space-between;font-size:9px;color:rgba(255,255,255,.53);margin-bottom:5px}.pp-track{height:8px;border-radius:999px;background:rgba(255,255,255,.13);overflow:hidden}.pp-fill{height:100%;border-radius:inherit;background:linear-gradient(90deg,#7c3aed,#c084fc,#e9d5ff);box-shadow:0 0 11px rgba(192,132,252,.52)}',
      '.pp-section{margin-bottom:22px}.pp-head{display:flex;align-items:center;justify-content:space-between;margin:0 2px 11px}.pp-head h3{font-size:12px;font-weight:950;letter-spacing:.085em;text-transform:uppercase;color:rgba(247,245,255,.78)}.pp-link{border:0;background:none;color:#c4b5fd;font-size:11px;font-weight:900;padding:4px 0}',
      '.pp-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.pp-stat{min-width:0;background:linear-gradient(180deg,rgba(40,30,72,.74),rgba(18,19,34,.90));border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:12px 5px 11px;text-align:center;box-shadow:inset 0 1px 0 rgba(255,255,255,.025)}.pp-stat-icon{font-size:18px;line-height:1;margin-bottom:7px}.pp-stat-value{font-size:18px;font-weight:950;line-height:1}.pp-stat-label{font-size:8.5px;color:var(--pp-muted);margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
      '.pp-quests{display:grid;gap:9px}.pp-quest{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:11px;align-items:center;padding:11px 12px;border-radius:16px;background:linear-gradient(180deg,rgba(25,22,43,.96),rgba(16,17,30,.96));border:1px solid rgba(255,255,255,.085);box-shadow:0 8px 18px rgba(0,0,0,.16)}.pp-quest-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(145deg,#57268c,#28163d);font-size:19px}.pp-quest-title{font-size:12.5px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pp-quest-sub{font-size:9.5px;color:var(--pp-muted);margin-top:3px}.pp-xp-pill{font-size:10px;font-weight:900;color:#e1c5ff;background:#381660;border:1px solid rgba(216,180,254,.20);padding:5px 8px;border-radius:999px;white-space:nowrap}',
      '.pp-progress{position:relative;overflow:hidden;border-radius:18px;padding:15px;background:linear-gradient(115deg,rgba(63,31,103,.88),rgba(22,20,38,.96));border:1px solid rgba(196,181,253,.18);box-shadow:0 10px 25px rgba(0,0,0,.18)}.pp-progress:after{content:"";position:absolute;right:-20px;bottom:-36px;width:135px;height:135px;border-radius:50%;background:radial-gradient(circle,rgba(124,58,237,.22),transparent 70%)}.pp-progress-row{display:flex;gap:12px;align-items:center;position:relative;z-index:1}.pp-crest{width:50px;height:58px;flex:0 0 50px;clip-path:polygon(50% 0,94% 16%,94% 70%,50% 100%,6% 70%,6% 16%);display:grid;place-items:center;background:linear-gradient(160deg,#6d28d9,#281249);font-size:23px;filter:drop-shadow(0 6px 10px rgba(0,0,0,.3))}.pp-progress-body{flex:1;min-width:0}.pp-progress-name{font-size:13px;font-weight:950}.pp-progress-sub{font-size:9.5px;color:var(--pp-muted);margin-top:2px}.pp-progress-percent{font-size:12px;font-weight:950;color:#f0e5ff}.pp-progress-foot{font-size:9px;color:var(--pp-muted);margin-top:7px}',
      '.pp-achievements{display:flex;gap:9px;overflow-x:auto;padding:1px 1px 4px;scrollbar-width:none}.pp-achievements::-webkit-scrollbar{display:none}.pp-ach{flex:0 0 80px;min-height:91px;padding:10px 6px;border-radius:15px;text-align:center;background:linear-gradient(180deg,rgba(31,25,51,.96),rgba(16,17,30,.96));border:1px solid rgba(255,255,255,.08)}.pp-ach-icon{width:37px;height:37px;border-radius:11px;display:grid;place-items:center;margin:0 auto 7px;background:linear-gradient(145deg,#6726a0,#2b1745);font-size:18px}.pp-ach-name{font-size:8.5px;font-weight:850;line-height:1.15;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pp-ach-sub{font-size:7.5px;color:var(--pp-muted);margin-top:3px}.pp-ach.locked{opacity:.43}',
      '.pp-empty{padding:17px 12px;text-align:center;border:1px dashed rgba(255,255,255,.12);border-radius:15px;color:rgba(255,255,255,.43);font-size:10.5px;background:rgba(255,255,255,.015)}.pp-loading{padding:40px 14px;text-align:center;color:rgba(255,255,255,.54)}',
      '@media(max-width:370px){.task-person-page{padding-left:12px;padding-right:12px}.pp-stats{gap:6px}.pp-stat{padding-left:3px;padding-right:3px}.pp-member{flex-basis:64px}}@media(min-width:480px){.task-person-page{margin:0}.pp-hero{min-height:230px}}'
    ].join('\n');document.head.appendChild(s);
  }

  function ensureService(done){
    if(window.PersonDashboardService){done();return;}
    if(serviceLoading)return;
    serviceLoading=true;
    var script=document.createElement('script');script.src='src/modules/tasks/personDashboardService.js?v=2';
    script.onload=function(){serviceLoading=false;done();};
    script.onerror=function(){serviceLoading=false;if(currentTarget)currentTarget.innerHTML='<div class="pp-loading">Persoonsgegevens konden niet worden geladen.</div>';};
    document.head.appendChild(script);
  }
  function decorate(models){return(models||[]).map(function(m,i){m._palette=palette(i);return m;});}
  function choose(models){if(!models.length)return null;var current=selectedUid&&models.find(function(m){return m.uid===selectedUid;});if(current)return current;current=models.find(function(m){return m.member&&m.member.isCurrent;})||models[0];selectedUid=current.uid;return current;}

  function membersHtml(models){return'<div class="pp-members">'+models.map(function(m){var p=m._palette,mem=m.member||{},pr=m.presence||{},active=m.uid===selectedUid;return'<button type="button" class="pp-member'+(active?' active':'')+'" data-pp-member="'+esc(m.uid)+'" style="--accent:'+p.accent+';--glow:'+p.glow+'"><div class="pp-avatar-wrap">'+(mem.avatar?'<img class="pp-avatar" src="'+esc(mem.avatar)+'" alt="'+esc(mem.displayName)+'">':'<div class="pp-avatar-fallback">'+esc(initials(mem))+'</div>')+'<i class="pp-dot '+presenceClass(m)+'"></i></div><div class="pp-member-name">'+esc(mem.displayName||'Gezinslid')+'</div><div class="pp-member-state">'+(pr.state==='online'?'Online':pr.state==='recent'?'Recent':pr.state==='today'?'Vandaag':'Offline')+'</div></button>';}).join('')+'</div>';}
  function heroHtml(m){var p=m._palette,mem=m.member||{},g=m.progression||{},prev=Number(g.previousLevelXp||0),next=Number(g.nextLevelXp||prev+1),xp=Number(g.xp||0),progress=next>prev?clamp((xp-prev)/(next-prev)*100):0;return'<div class="pp-hero" style="--hero:'+p.hero+';--glow:'+p.glow+'">'+(mem.avatar?'<div class="pp-hero-bg" style="background-image:url(&quot;'+esc(mem.avatar)+'&quot;)"></div>':'')+'<div class="pp-level"><small>Level</small><strong>'+esc(g.level||1)+'</strong></div><div class="pp-hero-content"><div class="pp-name">'+esc(mem.displayName||'Gezinslid')+'</div><div class="pp-titleline">⚔ '+esc(g.title||'Avonturier')+'</div><div class="pp-presence '+presenceClass(m)+'"><i></i>'+esc(presenceLabel(m))+'</div><div class="pp-xp"><div class="pp-xp-meta"><span>'+xp.toLocaleString('nl-NL')+' XP</span><span>'+next.toLocaleString('nl-NL')+' XP</span></div><div class="pp-track"><div class="pp-fill" style="width:'+progress+'%"></div></div></div></div></div>';}
  function statsHtml(m){var q=m.quests||{},g=m.progression||{},cap=m.capabilities||{},streak=cap.streak&&g.streak!=null?g.streak:'—',rows=[['⬡',g.level||1,'Level'],['🔥',streak,'Streak'],['⚔️',q.completedCount||0,'Quests'],['✦',q.earnedXpThisWeek||0,'XP/week']];return'<section class="pp-section"><div class="pp-head"><h3>Jouw avontuur</h3></div><div class="pp-stats">'+rows.map(function(x){return'<div class="pp-stat"><div class="pp-stat-icon">'+x[0]+'</div><div class="pp-stat-value">'+esc(x[1])+'</div><div class="pp-stat-label">'+esc(x[2])+'</div></div>';}).join('')+'</div></section>';}
  function questIcon(t){var type=String(t.type||'').toUpperCase();if(type.indexOf('RAID')>-1)return'⚔️';if(type.indexOf('DUNGEON')>-1)return'🏰';return'✦';}
  function questsHtml(m){var list=((m.quests&&m.quests.active)||[]).slice(0,3);return'<section class="pp-section"><div class="pp-head"><h3>Actieve quests</h3><button type="button" class="pp-link" data-pp-tasks>Alles bekijken ›</button></div>'+(list.length?'<div class="pp-quests">'+list.map(function(t){var roles=t.roles||[],role=roles.indexOf('helper')>-1?'Helpt mee':roles.indexOf('creator')>-1?'Maker':'Toegewezen';return'<div class="pp-quest"><div class="pp-quest-icon">'+questIcon(t)+'</div><div><div class="pp-quest-title">'+esc(t.title)+'</div><div class="pp-quest-sub">'+esc(role+(t.dueDate?' · '+t.dueDate:''))+'</div></div><div class="pp-xp-pill">+'+esc(t.xp||0)+' XP</div></div>';}).join('')+'</div>':'<div class="pp-empty">Geen actieve quests voor dit gezinslid.</div>')+'</section>';}
  function progressHtml(m){var g=m.progression||{},prev=Number(g.previousLevelXp||0),next=Number(g.nextLevelXp||prev+1),xp=Number(g.xp||0),progress=next>prev?clamp((xp-prev)/(next-prev)*100):0;return'<section class="pp-section"><div class="pp-head"><h3>Progressie</h3></div><div class="pp-progress"><div class="pp-progress-row"><div class="pp-crest">⚔</div><div class="pp-progress-body"><div class="pp-progress-name">'+esc(g.title||'Avonturier')+'</div><div class="pp-progress-sub">Level '+esc(g.level||1)+'</div><div class="pp-track" style="margin-top:9px"><div class="pp-fill" style="width:'+progress+'%"></div></div><div class="pp-progress-foot">Nog '+Math.max(0,next-xp).toLocaleString('nl-NL')+' XP tot het volgende level</div></div><div class="pp-progress-percent">'+progress+'%</div></div></div></section>';}
  function achHtml(m){var list=((m.achievements&&m.achievements.recent)||[]).slice(0,5),cards=list.map(function(a){return'<div class="pp-ach"><div class="pp-ach-icon">🏆</div><div class="pp-ach-name">'+esc(a.id)+'</div><div class="pp-ach-sub">Ontgrendeld</div></div>';});while(cards.length<5)cards.push('<div class="pp-ach locked"><div class="pp-ach-icon">🔒</div><div class="pp-ach-name">Nog te ontdekken</div><div class="pp-ach-sub">Locked</div></div>');return'<section class="pp-section"><div class="pp-head"><h3>Achievements</h3><button type="button" class="pp-link" data-pp-ach>Alles bekijken ›</button></div><div class="pp-achievements">'+cards.join('')+'</div></section>';}
  function activityHtml(m){var cap=m.capabilities||{},list=(m.activity&&m.activity.recent)||[];return'<section class="pp-section"><div class="pp-head"><h3>Recente activiteit</h3></div>'+(!cap.activity||!list.length?'<div class="pp-empty">Nog geen recente activiteit.</div>':'<div class="pp-quests">'+list.map(function(a){return'<div class="pp-quest"><div class="pp-quest-icon">'+esc(a.icon||'✦')+'</div><div><div class="pp-quest-title">'+esc(a.title||a.text||'Activiteit')+'</div><div class="pp-quest-sub">'+esc(a.timeLabel||'')+'</div></div></div>';}).join('')+'</div>')+'</section>';}

  function bind(el){
    el.querySelectorAll('[data-pp-member]').forEach(function(btn){btn.addEventListener('click',function(){selectedUid=btn.getAttribute('data-pp-member');renderFromService();});});
    var tasks=el.querySelector('[data-pp-tasks]');if(tasks)tasks.addEventListener('click',function(){try{var btn=Array.prototype.find.call(document.querySelectorAll('#screen-tasks .ttab'),function(b){return(b.textContent||'').trim()==='Overzicht';});if(window.setTaskTab)window.setTaskTab('compact',btn||null);}catch(e){}});
    var ach=el.querySelector('[data-pp-ach]');if(ach)ach.addEventListener('click',function(){try{if(window.showScreen)window.showScreen('achievements');}catch(e){}});
  }
  function draw(models){if(!currentTarget)return;var data=decorate(models||[]),chosen=choose(data);if(!chosen){currentTarget.innerHTML='<div class="task-person-page"><div class="pp-loading">Gezinsleden worden geladen…</div></div>';return;}currentTarget.innerHTML='<div class="task-person-page">'+membersHtml(data)+heroHtml(chosen)+statsHtml(chosen)+questsHtml(chosen)+progressHtml(chosen)+achHtml(chosen)+activityHtml(chosen)+'</div>';bind(currentTarget);}
  function renderFromService(){if(!window.PersonDashboardService){ensureService(renderFromService);return;}draw(window.PersonDashboardService.getMembers());}
  function connect(){if(!window.PersonDashboardService||unsubscribe)return;unsubscribe=window.PersonDashboardService.subscribe(function(models){if(currentTarget&&document.documentElement.contains(currentTarget))draw(models);});}

  window.renderTasksPersoon=function(el){injectStyles();currentTarget=el||document.getElementById('task-content');if(!currentTarget)return;currentTarget.innerHTML='<div class="task-person-page"><div class="pp-loading">Persoonsdashboard laden…</div></div>';ensureService(function(){connect();renderFromService();});};
  window.PersonTabPremium={version:VERSION,render:window.renderTasksPersoon,refresh:function(){if(window.PersonDashboardService)window.PersonDashboardService.refresh();else renderFromService();},selectedUid:function(){return selectedUid;}};
  window.addEventListener('familyapp:person-dashboard-updated',function(){if(currentTarget&&document.documentElement.contains(currentTarget))renderFromService();});
})();
