'use strict';
// FamilyApp Person tab premium geometry v3.0
(function(){
  if(window.PersonHeroFantasyPolish)return;
  var VERSION='3.0.0',busy=false;
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function txt(root,sel,fallback){var n=root&&root.querySelector(sel);return n&&n.textContent?n.textContent.trim():(fallback||'');}
  function avatar(){try{var active=document.querySelector('.member-card-active');if(active){var img=active.querySelector('img');if(img&&img.getAttribute('src'))return img.getAttribute('src');}}catch(e){}try{var hdr=document.querySelector('#hdr-avatar img');if(hdr&&hdr.getAttribute('src'))return hdr.getAttribute('src');}catch(e){}try{if(window.HouseholdIdentity&&HouseholdIdentity.getActiveAvatar)return HouseholdIdentity.getActiveAvatar()||'';}catch(e){}try{return localStorage.getItem('familyapp-current-user-avatar-v1')||'';}catch(e){return '';}}
  function css(){var old=document.getElementById('person-hero-fantasy-polish-css');if(old)old.remove();var s=document.createElement('style');s.id='person-hero-fantasy-polish-css';s.textContent=`
.task-person-page{padding:14px 18px 118px!important;background:radial-gradient(115% 90% at 50% -12%,#21154a 0%,#0b0e1a 50%,#07080f 100%)!important;color:#f6f3ff!important}
.member-selector{gap:18px!important;margin:0 0 18px!important;padding:2px 0 7px!important}.member-card{width:76px!important}.member-card-avatar,.member-card-avatar-fallback,.member-card-add-icon{width:62px!important;height:62px!important}.member-card-name{font-size:12.5px!important}.member-card-level{font-size:10.5px!important}
.member-hero-card.ptp3-hero{display:block!important;position:relative!important;min-height:0!important;height:auto!important;padding:0!important;margin:0 0 14px!important;border-radius:28px!important;overflow:hidden!important;background:none!important;background-image:none!important;border:1px solid rgba(178,138,255,.20)!important;box-shadow:0 22px 60px rgba(17,8,48,.55)!important}
.member-hero-card.ptp3-hero::before,.member-hero-card.ptp3-hero::after{display:none!important;content:none!important}
.ptp3-visual{position:relative;min-height:265px;padding:22px 20px 20px;display:flex;align-items:flex-end;overflow:hidden;background:radial-gradient(circle at 52% 24%,rgba(255,190,100,.30),transparent 17%),radial-gradient(circle at 82% 38%,rgba(126,69,196,.24),transparent 30%),linear-gradient(165deg,#17192e 0%,#232443 38%,#151729 66%,#080a13 100%)}
.ptp3-visual::before{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(7,9,18,.02) 0%,rgba(7,8,16,.05) 36%,rgba(5,6,12,.55) 69%,rgba(5,6,12,.94) 100%)}
.ptp3-visual::after{content:"";position:absolute;left:-10%;right:-10%;bottom:22%;height:42%;background:linear-gradient(160deg,transparent 0 37%,rgba(19,24,42,.85) 38% 45%,transparent 46%),linear-gradient(200deg,transparent 0 42%,rgba(11,16,31,.92) 43% 54%,transparent 55%);opacity:.9}
.ptp3-profile{position:relative;z-index:2;display:grid;grid-template-columns:118px minmax(0,1fr);gap:18px;width:100%;align-items:end}.ptp3-avatar{width:118px;height:118px;border-radius:50%;object-fit:cover;background:#171528;border:4px solid #cdbdff;box-shadow:0 0 0 4px rgba(124,58,237,.22),0 16px 38px rgba(0,0,0,.46)}.ptp3-avatar-fallback{display:grid;place-items:center;font-size:27px;font-weight:950;color:#fff}.ptp3-copy{min-width:0;padding-bottom:5px}.ptp3-name{font-size:31px;font-weight:950;letter-spacing:-.55px;line-height:1;color:#fff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-shadow:0 2px 16px rgba(0,0,0,.55)}.ptp3-title{margin-top:7px;color:#d9ccff;font-size:14px;font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ptp3-meta{display:flex;align-items:center;gap:10px;margin-top:14px;min-width:0}.ptp3-level{flex:0 0 50px;height:58px;clip-path:polygon(50% 0%,100% 25%,100% 75%,50% 100%,0% 75%,0% 25%);background:linear-gradient(160deg,#35195e,#6c38b6);display:flex;flex-direction:column;align-items:center;justify-content:center;box-shadow:inset 0 0 0 2px rgba(253,230,138,.55)}.ptp3-level span{font-size:7px;font-weight:950;letter-spacing:.12em;color:#fde68a}.ptp3-level strong{font-size:19px;line-height:1;color:#fde68a}.ptp3-xpblock{min-width:0;flex:1}.ptp3-xplabel{font-size:9px;font-weight:850;color:rgba(255,255,255,.55);text-transform:uppercase;letter-spacing:.06em}.ptp3-xptext{font-size:14px;font-weight:900;color:#fff;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ptp3-bar{height:8px;border-radius:999px;background:rgba(255,255,255,.18);overflow:hidden;margin-top:7px}.ptp3-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,#7c3aed,#d8b4fe);box-shadow:0 0 12px rgba(168,85,247,.45)}
.ptp3-statbar{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;background:linear-gradient(180deg,#0d101b,#090b13);border-top:1px solid rgba(255,255,255,.075)}.ptp3-statcell{min-width:0;padding:14px 7px 15px;text-align:center}.ptp3-statcell+.ptp3-statcell{border-left:1px solid rgba(255,255,255,.07)}.ptp3-staticon{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;margin:0 auto 7px;background:radial-gradient(circle at 35% 30%,rgba(255,255,255,.13),rgba(255,255,255,.04));font-size:17px}.ptp3-statlabel{font-size:8px;color:rgba(255,255,255,.50);font-weight:800;text-transform:uppercase;letter-spacing:.05em}.ptp3-statvalue{font-size:16px;font-weight:950;color:#fff;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.person-stat-grid{display:none!important}
.ptp3-skills{margin:14px 0 20px;background:linear-gradient(180deg,rgba(18,20,33,.96),rgba(10,12,21,.98));border:1px solid rgba(255,255,255,.08);border-radius:22px;padding:16px 16px 10px;box-shadow:0 14px 34px rgba(0,0,0,.18)}.ptp3-skills-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:9px}.ptp3-skills-title{font-size:16px;font-weight:900;color:#fff}.ptp3-skills-link{font-size:12.5px;font-weight:850;color:#b56cff}.ptp3-skillrow{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 0}.ptp3-skillrow+.ptp3-skillrow{border-top:1px solid rgba(255,255,255,.055)}.ptp3-skillicon{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#111523;border:1px solid rgba(255,255,255,.09);font-size:17px}.ptp3-skillmain{min-width:0}.ptp3-skilltop{display:flex;align-items:center;gap:7px;min-width:0}.ptp3-skillname{font-size:13.5px;font-weight:850;color:#fff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ptp3-skilllvl{font-size:9px;font-weight:850;color:#d8b4fe;background:rgba(124,58,237,.18);border:1px solid rgba(168,85,247,.22);border-radius:7px;padding:2px 5px;white-space:nowrap}.ptp3-skillbar{height:6px;border-radius:999px;background:rgba(255,255,255,.10);overflow:hidden;margin-top:6px}.ptp3-skillfill{height:100%;border-radius:999px;background:linear-gradient(90deg,#7c3aed,#c084fc)}.ptp3-skillxp{font-size:10.5px;font-weight:750;color:rgba(255,255,255,.68);white-space:nowrap}
.ptp-row-header{margin:0 2px 10px!important}.ptp-label{font-size:16px!important;font-weight:900!important}.ptp-see-all{font-size:12.5px!important;color:#b56cff!important}.person-task-list{gap:10px!important}.person-task-card{min-height:76px!important;border-radius:18px!important;padding:13px!important;background:rgba(255,255,255,.035)!important;border:1px solid rgba(255,255,255,.075)!important}.ptc-icon-sq{width:46px!important;height:46px!important;border-radius:14px!important}.ptc-title{font-size:14.5px!important}.ptc-cat{font-size:11px!important}.ptc-check{width:27px!important;height:27px!important}.ptp-empty{border-radius:18px!important;background:rgba(255,255,255,.03)!important;border:1px solid rgba(255,255,255,.07)!important}
@media(max-width:390px){.task-person-page{padding-left:14px!important;padding-right:14px!important}.ptp3-visual{min-height:248px;padding:19px 17px 17px}.ptp3-profile{grid-template-columns:102px minmax(0,1fr);gap:14px}.ptp3-avatar{width:102px;height:102px}.ptp3-name{font-size:27px}.ptp3-title{font-size:12.5px}.ptp3-level{flex-basis:46px;height:52px}.ptp3-level strong{font-size:17px}.ptp3-xptext{font-size:12.5px}.ptp3-statcell{padding:12px 4px 13px}.ptp3-staticon{width:32px;height:32px;font-size:15px}.ptp3-statvalue{font-size:14.5px}.ptp3-statlabel{font-size:7.5px}}
`;
    document.head.appendChild(s);
  }
  function skillLevel(xp){try{return typeof window.skillLevelFromXp==='function'?skillLevelFromXp(xp):1;}catch(e){return 1;}}
  function skillNeed(level){try{return typeof window.skillXpNeeded==='function'?skillXpNeeded(level):Math.max(36,level*34);}catch(e){return Math.max(36,level*34);}}
  function skillsData(){var st=null;try{st=window.FamilyProgression&&FamilyProgression.getState?FamilyProgression.getState():null;}catch(e){}var defs=window.SKILL_DEFS||[];if(!st||!st.skills||!defs.length)return[];return defs.map(function(d){var sk=st.skills[d.id]||{xp:0};var xp=Number(sk.xp)||0;return{def:d,xp:xp,level:skillLevel(xp)};}).sort(function(a,b){return b.xp-a.xp;}).slice(0,4);}
  function injectSkills(page){var old=page.querySelector('.ptp3-skills');if(old)old.remove();var anchor=page.querySelector('.person-stat-grid');if(!anchor)return;var items=skillsData();if(!items.length)return;var panel=document.createElement('section');panel.className='ptp3-skills';var rows=items.map(function(it){var need=skillNeed(it.level),pct=Math.max(0,Math.min(100,Math.round((it.xp/need)*100)));return '<div class="ptp3-skillrow"><div class="ptp3-skillicon">'+esc(it.def.icon||'⭐')+'</div><div class="ptp3-skillmain"><div class="ptp3-skilltop"><div class="ptp3-skillname">'+esc(it.def.name||it.def.id)+'</div><div class="ptp3-skilllvl">Lv '+it.level+'</div></div><div class="ptp3-skillbar"><div class="ptp3-skillfill" style="width:'+pct+'%"></div></div></div><div class="ptp3-skillxp">'+it.xp+' / '+need+' XP</div></div>';}).join('');panel.innerHTML='<div class="ptp3-skills-head"><div class="ptp3-skills-title">Mijn vaardigheden</div><div class="ptp3-skills-link">Bekijk alle ›</div></div>'+rows;anchor.insertAdjacentElement('afterend',panel);}
  function avatarHtml(name){var av=avatar();return av?'<img class="ptp3-avatar" src="'+esc(av)+'" alt="">':'<div class="ptp3-avatar ptp3-avatar-fallback">'+esc(name.slice(0,2).toUpperCase())+'</div>';}
  function rebuild(hero,page){if(!hero)return;var name=txt(hero,'.member-hero-name',window.myName||'Jij'),title=txt(hero,'.member-hero-title','Avonturier'),level=txt(hero,'.member-hero-lvl-num','1'),caption=txt(hero,'.member-hero-progress-caption',''),oldFill=hero.querySelector('.member-hero-progress-fill'),pct=(oldFill&&oldFill.style&&oldFill.style.width)||'0%';var cols=[].slice.call(hero.querySelectorAll('.mh-stat-col')).map(function(col){return{label:txt(col,'.mh-stat-lbl',''),value:txt(col,'.mh-stat-val','')}});while(cols.length<3)cols.push({label:'',value:''});var external=[].slice.call(page.querySelectorAll('.person-stat-card')).map(function(card){return{icon:txt(card,'.psc-icon-wrap','⭐'),label:txt(card,'.psc-lbl',''),value:txt(card,'.psc-val','0')};});var totalXp='';try{var st=window.FamilyProgression&&FamilyProgression.getState?FamilyProgression.getState():null;if(st)totalXp=String(st.totalXp||0);}catch(e){}var statItems=[{icon:'✦',label:'Totale XP',value:totalXp||cols[0].value||'0'},{icon:'🏆',label:'Prestaties',value:(external[1]&&external[1].value)||'0'},{icon:'🔥',label:'Streak',value:cols[1].value||((external[3]&&external[3].value)||'0')},{icon:'👥',label:'Huishoud',value:'Gezin'}];var stats=statItems.map(function(x){return '<div class="ptp3-statcell"><div class="ptp3-staticon">'+esc(x.icon)+'</div><div class="ptp3-statlabel">'+esc(x.label)+'</div><div class="ptp3-statvalue">'+esc(x.value)+'</div></div>';}).join('');hero.className='member-hero-card ptp3-hero';hero.removeAttribute('style');hero.innerHTML='<div class="ptp3-visual"><div class="ptp3-profile">'+avatarHtml(name)+'<div class="ptp3-copy"><div class="ptp3-name">'+esc(name)+'</div><div class="ptp3-title">'+title+'</div><div class="ptp3-meta"><div class="ptp3-level"><span>LEVEL</span><strong>'+esc(level)+'</strong></div><div class="ptp3-xpblock"><div class="ptp3-xplabel">Voortgang</div><div class="ptp3-xptext">'+esc(caption||'Level '+level)+'</div><div class="ptp3-bar"><div class="ptp3-fill" style="width:'+esc(pct)+'"></div></div></div></div></div></div></div><div class="ptp3-statbar">'+stats+'</div>';injectSkills(page);}
  function refreshAvatar(hero){var av=avatar(),current=hero&&hero.querySelector('.ptp3-avatar');if(!hero||!av||!current)return;if(current.tagName==='IMG'){if(current.getAttribute('src')!==av)current.setAttribute('src',av);return;}var img=document.createElement('img');img.className='ptp3-avatar';img.alt='';img.src=av;current.replaceWith(img);}
  function enhance(){if(busy)return;busy=true;try{css();var page=document.querySelector('.task-person-page');if(!page)return;var hero=page.querySelector('.member-hero-card');if(hero&&!hero.classList.contains('ptp3-hero'))rebuild(hero,page);else if(hero){refreshAvatar(hero);if(!page.querySelector('.ptp3-skills'))injectSkills(page);}}finally{busy=false;}}
  function boot(){css();enhance();var root=document.getElementById('task-content')||document.body;new MutationObserver(function(){requestAnimationFrame(enhance);}).observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:['class','src']});window.addEventListener('familyapp:avatar-updated',enhance);window.addEventListener('familyapp:progression:skill',enhance);window.addEventListener('familyapp:progression:xp',enhance);}
  window.PersonHeroFantasyPolish={version:VERSION,refresh:enhance};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
