'use strict';
// PERSOON TAB v3 — Firebase UID identity + presence. Progression remains legacy.
(function(){
  var VERSION='3.0', cachedMembers=[], lastTarget=null;
  var PALETTES=[
    {bg:'linear-gradient(150deg,#241455,#6d3fc9)',glow:'rgba(124,58,237,.45)',accent:'#a78bfa'},
    {bg:'linear-gradient(150deg,#4a0f38,#c9439f)',glow:'rgba(236,72,153,.4)',accent:'#ff9fd6'},
    {bg:'linear-gradient(150deg,#3a2408,#d9a441)',glow:'rgba(217,119,6,.4)',accent:'#fbbf6a'},
    {bg:'linear-gradient(150deg,#0a3324,#3fd9a8)',glow:'rgba(13,148,103,.4)',accent:'#5eead4'}
  ];
  var CATS={Keuken:{bg:'#b9713d',icon:'🍽️'},Wassen:{bg:'#5b6fd8',icon:'🧺'},Organisatie:{bg:'#7a8c4a',icon:'📋'},Boodschappen:{bg:'#3d95c2',icon:'🛒'},RAID:{bg:'#b91c4c',icon:'⚔️'},DUNGEON:{bg:'#6d28d9',icon:'🏰'}};
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function catStyle(cat){if(CATS[cat])return CATS[cat];if(String(cat).indexOf('RAID')>-1)return CATS.RAID;if(String(cat).indexOf('DUNGEON')>-1)return CATS.DUNGEON;return{bg:'#5b6472',icon:'⭐'};}
  function injectStyles(){
    if(document.getElementById('person-tab-premium-style'))return;
    var s=document.createElement('style');s.id='person-tab-premium-style';s.textContent=[
      '.task-person-page{background:radial-gradient(120% 140% at 20% -10%,#1a1440 0%,#0b0e1a 55%,#07080f 100%);margin:0 -16px;padding:14px 16px 110px;min-height:100%;color:#f4f6ff;overflow-x:hidden}.task-person-page *{box-sizing:border-box}',
      '.ptp-label{font-size:14.5px;font-weight:800;color:rgba(244,246,255,.82);margin:2px 2px 12px}.ptp-row-header{display:flex;justify-content:space-between;margin:4px 2px 10px}.ptp-row-header .ptp-label{margin:0}.ptp-see-all{font-size:12.5px;font-weight:800;color:#fbbf24}.ptp-section{margin-bottom:20px}',
      '#screen-tasks:has(.task-person-page) .task-tabs{background:#0b0e1a;display:flex;gap:4px;padding:10px 12px 6px;overflow-x:auto}#screen-tasks:has(.task-person-page) .ttab{background:transparent;border:0;color:rgba(244,246,255,.5);font-size:13px;font-weight:800;padding:9px 14px;border-radius:999px;white-space:nowrap}#screen-tasks:has(.task-person-page) .ttab.active{background:linear-gradient(135deg,#6d28d9,#8b5cf6);color:#fff}',
      '.member-selector{display:flex;gap:14px;overflow-x:auto;padding:2px 2px 6px;margin-bottom:16px}.member-card{flex:0 0 auto;width:76px;text-align:center;cursor:pointer;background:transparent;border:0}.member-card-avatar-wrap{position:relative;width:58px;height:58px;margin:0 auto 6px}.member-card-avatar,.member-card-avatar-fallback{width:56px;height:56px;border-radius:50%;object-fit:cover;display:block;border:2.5px solid rgba(255,255,255,.16)}.member-card-avatar-fallback{display:flex;align-items:center;justify-content:center;font-size:16px;font-weight:900}.member-card-name{font-size:12.5px;font-weight:800;color:rgba(244,246,255,.75);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.member-card-level{font-size:10.5px;color:rgba(244,246,255,.45)}.member-card-active .member-card-avatar,.member-card-active .member-card-avatar-fallback{border-color:var(--ptp-accent);box-shadow:0 0 0 2px #0b0e1a,0 0 16px var(--ptp-glow)}.member-card-active .member-card-name{color:#fff}',
      '.ptp-presence-dot{position:absolute;right:0;bottom:2px;width:13px;height:13px;border-radius:50%;background:#6b7280;border:2.5px solid #0b0e1a}.ptp-presence-dot.is-online{background:#22c55e;box-shadow:0 0 10px rgba(34,197,94,.55)}.member-card-add-icon{width:56px;height:56px;border-radius:50%;border:1.5px dashed rgba(255,255,255,.28);display:flex;align-items:center;justify-content:center;font-size:19px;margin:0 auto 6px}',
      '.member-hero-card{position:relative;border-radius:28px;overflow:hidden;min-height:290px;display:flex;flex-direction:column;justify-content:flex-end;padding:20px 18px 18px;margin-bottom:16px;background-size:cover;background-position:center 22%;box-shadow:0 20px 46px var(--ptp-glow)}.member-hero-card::after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 0%,rgba(7,8,15,.12) 30%,rgba(9,7,20,.94) 100%)}.member-hero-lvl-badge{position:absolute;top:16px;right:16px;z-index:2;width:56px;height:56px;clip-path:polygon(50% 0%,100% 25%,100% 75%,50% 100%,0 75%,0 25%);background:#3d276c;display:flex;flex-direction:column;align-items:center;justify-content:center}.member-hero-lvl-eyebrow{font-size:7px;font-weight:900;color:#fde68a}.member-hero-lvl-num{font-size:17px;font-weight:950;color:#fde68a}.member-hero-content{position:relative;z-index:1}.member-hero-name{font-size:23px;font-weight:950}.member-hero-title{font-size:13px;font-weight:800;color:#c9b8ff;margin-top:2px}',
      '.ptp-presence-status{display:flex;align-items:center;gap:7px;margin-top:7px;font-size:11.5px;font-weight:750;color:rgba(244,246,255,.62)}.ptp-presence-mini{width:8px;height:8px;border-radius:50%;background:#6b7280}.ptp-presence-status.is-online{color:#bbf7d0}.ptp-presence-status.is-online .ptp-presence-mini{background:#22c55e}',
      '.member-hero-stats-row{display:flex;margin-top:16px}.mh-stat-col{flex:1;padding:0 10px;min-width:0}.mh-stat-col:first-child{padding-left:0}.mh-stat-col+.mh-stat-col{border-left:1px solid rgba(255,255,255,.16)}.mh-stat-lbl{font-size:11px;color:rgba(255,255,255,.65)}.mh-stat-val{font-size:15px;font-weight:950}.mh-stat-sub{font-size:9.5px;color:rgba(255,255,255,.5)}.member-hero-progress-bar{margin-top:16px;height:9px;border-radius:999px;background:rgba(255,255,255,.18);overflow:hidden}.member-hero-progress-fill{height:100%;background:linear-gradient(90deg,#7c3aed,#c4b5fd)}.member-hero-progress-caption{margin-top:7px;font-size:11px;color:rgba(255,255,255,.55);text-align:center}',
      '.person-stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:20px}.person-stat-card{background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:12px 6px;text-align:center}.psc-icon-wrap{width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 6px}.psc-val{font-size:17px;font-weight:950}.psc-lbl{font-size:9.5px;color:rgba(244,246,255,.5)}',
      '.person-task-list{display:flex;flex-direction:column;gap:9px}.person-task-card{display:flex;align-items:center;gap:12px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.08);border-radius:18px;padding:12px 13px}.ptc-icon-sq{width:44px;height:44px;border-radius:13px;display:flex;align-items:center;justify-content:center}.ptc-body{flex:1;min-width:0}.ptc-title{font-size:14.5px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ptc-cat{font-size:11.5px;color:rgba(244,246,255,.5)}.ptc-side{text-align:right}.ptc-xp{font-size:13px;font-weight:900;color:#fbbf24}.ptc-day{font-size:10.5px;color:rgba(251,191,36,.6)}.ptc-check{width:24px;height:24px;border-radius:50%;border:2px solid rgba(255,255,255,.3)}.ptp-empty,.ptp-loading{text-align:center;padding:22px 10px;color:rgba(244,246,255,.55);background:rgba(255,255,255,.03);border-radius:16px}',
      '@media(min-width:480px){.task-person-page{margin:0}}'
    ].join('\n');document.head.appendChild(s);
  }
  function xpFromString(v){var m=String(v||'').match(/(\d+)/);return m?parseInt(m[1],10):0;}
  function recent(v){if(!v)return false;var d=new Date(String(v).replace(/^(\d{1,2})[\/\-](\d{1,2})/,'$1-$2'));return !isNaN(d.getTime())&&((new Date()-d)/86400000)>=-1&&((new Date()-d)/86400000)<=7;}
  // Legacy task/progression lookup only; household identity never depends on names.
  function questStats(name){var raw=localStorage.getItem('fam_tasks_v023')||localStorage.getItem('fam_tasks_v022')||'[]',all=[];try{all=JSON.parse(raw)||[];}catch(e){}var tasks=all.filter(function(x){return x[5]&&(x[5]==='Beiden'||x[5].indexOf(name)>-1);}),done=tasks.filter(function(x){return x[9]&&recent(x[11]||x[4]);});return{open:tasks.filter(function(x){return !x[9];}),done:done,weekXP:done.reduce(function(s,x){return s+xpFromString(x[6]);},0)};}
  function streak(name){if(typeof recurData==='undefined')return 0;return recurData.reduce(function(m,r){return r.who&&r.who.indexOf(name)>-1?Math.max(m,r.streak||0):m;},0);}
  function currentUid(){try{if(window.HouseholdIdentityFirebaseBridge&&HouseholdIdentityFirebaseBridge.getCurrentUid)return HouseholdIdentityFirebaseBridge.getCurrentUid();var u=window.fbUser||(firebase.auth&&firebase.auth().currentUser);return u?u.uid:null;}catch(e){return null;}}
  function sourceMembers(){try{var b=window.HouseholdIdentityFirebaseBridge;if(b&&b.getMembers){var live=b.getMembers();if(live&&live.length)cachedMembers=live;}}catch(e){}return cachedMembers.slice();}
  function buildMembers(){var me=currentUid();return sourceMembers().map(function(raw,i){var name=raw.displayName||raw.name||'Gezinslid',isMe=raw.uid===me,xp=isMe&&typeof myXP!=='undefined'?Number(myXP||0):0,level=typeof getLevel==='function'?getLevel(xp):Math.max(1,Math.floor(xp/100)+1),titleData=typeof LEVEL_TITLES!=='undefined'?LEVEL_TITLES[Math.min(level-1,LEVEL_TITLES.length-1)]:null,prev=typeof LEVEL_XP!=='undefined'?(LEVEL_XP[level-1]||0):0,next=typeof LEVEL_XP!=='undefined'?(LEVEL_XP[Math.min(level,LEVEL_XP.length-1)]||(prev+200)):(prev+200),qs=questStats(name);return{id:raw.uid,uid:raw.uid,name:name,isMe:isMe,avatar:raw.avatar||'',initials:raw.initials||name.slice(0,2).toUpperCase(),palette:PALETTES[i%PALETTES.length],online:raw.online===true||raw.onlineStatus==='online',lastSeen:raw.lastSeen||null,area:raw.area||'',role:raw.role||'member',level:level,title:titleData?titleData.title:'⚔️ Avonturier',xp:xp,prevXP:prev,nextXP:next,openCount:qs.open.length,doneCount:qs.done.length,weekXP:qs.weekXP,streak:streak(name),openTasks:qs.open};});}
  function areaLabel(a){var m={home:'Home',tasks:'Taken',shop:'Winkelen',recipes:'Recepten',notes:'Notities',cal:'Agenda',calendar:'Agenda',finance:'Financiën',achievements:'Prestaties',skills:'Vaardigheden',meals:'Maaltijden',profile:'Profiel',feed:'Feed'},k=String(a||'').toLowerCase();return m[k]||(a?String(a).charAt(0).toUpperCase()+String(a).slice(1):'in de app');}
  function presence(m){if(m.online)return'Actief · '+areaLabel(m.area);var ts=Number(m.lastSeen||0);if(!ts)return'Offline';var min=Math.floor(Math.max(0,Date.now()-ts)/60000);if(min<1)return'Zojuist actief';if(min<60)return min+' min geleden actief';var h=Math.floor(min/60);if(h<24)return h+' uur geleden actief';var d=Math.floor(h/24);return d<7?d+(d===1?' dag':' dagen')+' geleden actief':'Offline';}
  function selector(ms,selected){var h='<div class="ptp-label">Gezinsleden</div><div class="member-selector">';ms.forEach(function(m){var a=m.uid===selected;h+='<div class="member-card'+(a?' member-card-active':'')+'" data-person="'+esc(m.uid)+'" style="'+(a?'--ptp-accent:'+m.palette.accent+';--ptp-glow:'+m.palette.glow+';':'')+'"><div class="member-card-avatar-wrap">'+(m.avatar?'<img class="member-card-avatar" src="'+esc(m.avatar)+'" alt="'+esc(m.name)+'">':'<div class="member-card-avatar-fallback" style="background:'+m.palette.accent+'">'+esc(m.initials)+'</div>')+'<span class="ptp-presence-dot'+(m.online?' is-online':'')+'" title="'+esc(presence(m))+'"></span></div><div class="member-card-name">'+esc(m.name)+'</div><div class="member-card-level">'+(m.online?'Online':'Offline')+'</div></div>';});return h+'<div class="member-card" onclick="if(window.FamilyHousehold&&FamilyHousehold.showInviteManager)FamilyHousehold.showInviteManager()"><div class="member-card-add-icon">+</div><div class="member-card-name">Toevoegen</div></div></div>';}
  function hero(m){var pct=m.nextXP>m.prevXP?Math.max(0,Math.min(100,Math.round((m.xp-m.prevXP)/(m.nextXP-m.prevXP)*100))):0,bg=m.avatar?'background-image:url(&quot;'+esc(m.avatar)+'&quot;);':'background:'+m.palette.bg+';';return'<div class="member-hero-card" style="'+bg+'--ptp-glow:'+m.palette.glow+'"><div class="member-hero-lvl-badge"><div class="member-hero-lvl-eyebrow">Level</div><div class="member-hero-lvl-num">'+m.level+'</div></div><div class="member-hero-content"><div class="member-hero-name">'+esc(m.name)+'</div><div class="member-hero-title">'+esc(m.title)+'</div><div class="ptp-presence-status'+(m.online?' is-online':'')+'"><span class="ptp-presence-mini"></span><span>'+esc(presence(m))+'</span></div><div class="member-hero-stats-row"><div class="mh-stat-col"><div class="mh-stat-lbl">XP deze week</div><div class="mh-stat-val">'+m.weekXP+' XP</div></div><div class="mh-stat-col"><div class="mh-stat-lbl">Streak</div><div class="mh-stat-val">🔥 '+m.streak+' dagen</div></div><div class="mh-stat-col"><div class="mh-stat-lbl">Rol</div><div class="mh-stat-val">'+esc(m.role)+'</div><div class="mh-stat-sub">Firebase member</div></div></div><div class="member-hero-progress-bar"><div class="member-hero-progress-fill" style="width:'+pct+'%"></div></div><div class="member-hero-progress-caption">'+(m.isMe?m.xp+' / '+m.nextXP+' XP tot level '+(m.level+1):'Progression van dit lid wordt later UID-gebaseerd gemigreerd')+'</div></div></div>';}
  function stats(m){var cs=[['📋','#3b6fe0',m.openCount,'Open taken'],['✔','#22c55e',m.doneCount,'Voltooid'],['⭐','#d69f1c',m.weekXP,'XP verdiend'],['🔥','#f97316',m.streak,'Streak']];return'<div class="person-stat-grid">'+cs.map(function(c){return'<div class="person-stat-card"><div class="psc-icon-wrap" style="background:'+c[1]+'">'+c[0]+'</div><div class="psc-val">'+c[2]+'</div><div class="psc-lbl">'+c[3]+'</div></div>';}).join('')+'</div>';}
  function tasks(m){var h='<div class="ptp-section"><div class="ptp-row-header"><div class="ptp-label">Open taken</div><div class="ptp-see-all">Bekijk alle ›</div></div>';if(!m.openTasks.length)return h+'<div class="ptp-empty">🎉 Geen open taken voor '+esc(m.name)+'</div></div>';h+='<div class="person-task-list">';m.openTasks.forEach(function(x){var cat=x[1]||'Quest',cs=catStyle(cat);h+='<div class="person-task-card" onclick="if(window.famDetail)famDetail(\''+esc(x[0])+'\')"><div class="ptc-icon-sq" style="background:'+cs.bg+'">'+cs.icon+'</div><div class="ptc-body"><div class="ptc-title">'+esc(x[2])+'</div><div class="ptc-cat">'+esc(cat)+'</div></div><div class="ptc-side"><div class="ptc-xp">'+esc(x[6]||'')+'</div><div class="ptc-day">'+esc(x[11]||x[4]||'Binnenkort')+'</div></div><div class="ptc-check"></div></div>';});return h+'</div></div>';}
  function render(el){if(!el)return;lastTarget=el;injectStyles();var ms=buildMembers();if(!ms.length){el.innerHTML='<div class="task-person-page"><div class="ptp-loading">Gezinsleden uit Firebase laden…</div></div>';try{if(window.HouseholdIdentityFirebaseBridge)HouseholdIdentityFirebaseBridge.sync();}catch(e){}return;}var me=currentUid();if(!window.__personTabSelected||!ms.some(function(m){return m.uid===window.__personTabSelected;}))window.__personTabSelected=ms.some(function(m){return m.uid===me;})?me:ms[0].uid;var selected=ms.find(function(m){return m.uid===window.__personTabSelected;})||ms[0];el.innerHTML='<div class="task-person-page">'+selector(ms,selected.uid)+hero(selected)+stats(selected)+tasks(selected)+'</div>';el.querySelectorAll('.member-card[data-person]').forEach(function(card){card.addEventListener('click',function(){window.__personTabSelected=card.getAttribute('data-person');render(el);});});}
  function refresh(e){if(e&&e.detail&&Array.isArray(e.detail.members))cachedMembers=e.detail.members.slice();if(lastTarget&&document.body.contains(lastTarget)&&typeof taskTab!=='undefined'&&taskTab==='persoon')render(lastTarget);}
  window.addEventListener('familyapp:household-identity-synced',refresh);window.renderTasksPersoon=render;window.PersonTabPremium={version:VERSION,render:render,buildMembers:buildMembers};
  try{if(window.HouseholdIdentityFirebaseBridge&&HouseholdIdentityFirebaseBridge.subscribe)HouseholdIdentityFirebaseBridge.subscribe(function(ms){cachedMembers=ms.slice();refresh({detail:{members:ms}});});}catch(e){}
  if(typeof taskTab!=='undefined'&&taskTab==='persoon'){var target=document.getElementById('task-content');if(target)render(target);}
})();
