'use strict';
(function(){
  if(window.PersonTabV2)return;
  var VERSION='2.7.0',target=null,selectedUid=null,unsubscribe=null,lastModels=[],railSignature='';
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function clamp(value){return Math.max(0,Math.min(100,Math.round(Number(value)||0)));}
  function icon(key,opts){try{return window.FamilyAppIconRenderer&&FamilyAppIconRenderer.render?FamilyAppIconRenderer.render(key,opts||{}):'';}catch(e){return'';}}
  function initials(member){if(member&&member.initials)return member.initials;return String(member&&member.displayName||'?').split(/\s+/).filter(Boolean).map(function(part){return part.charAt(0);}).join('').slice(0,2).toUpperCase()||'?';}
  function currentModel(models){if(!models.length)return null;var chosen=selectedUid&&models.find(function(model){return model.uid===selectedUid;});if(!chosen)chosen=models.find(function(model){return model.member&&model.member.isCurrent;})||models[0];selectedUid=chosen.uid;return chosen;}
  function presenceState(model){return String(model&&model.presence&&model.presence.state||'offline');}
  function presenceText(model){var p=model&&model.presence||{};if(p.state==='online')return p.area?'Online · '+String(p.area):'Online';if(p.state==='recent')return'Recent actief';if(p.state==='today')return'Vandaag actief';return'Offline';}
  function avatarHtml(model){var member=model.member||{},src=member.avatar||'';if(src)return'<img class="pt2-avatar" src="'+esc(src)+'" alt="'+esc(member.displayName||'Gezinslid')+'" decoding="async">';return'<div class="pt2-avatar pt2-avatar-fallback">'+esc(initials(member))+'</div>';}
  function railKey(models){return models.map(function(model){var m=model.member||{};return [model.uid,m.displayName||'',m.avatar||''].join('|');}).join('||');}
  function memberRail(models){return'<div class="pt2-members" role="list">'+models.map(function(model){var member=model.member||{},active=model.uid===selectedUid,state=presenceState(model);return'<button type="button" class="pt2-member'+(active?' is-active':'')+'" data-pt2-member="'+esc(model.uid)+'" role="listitem"><span class="pt2-avatar-shell">'+avatarHtml(model)+'<i class="pt2-status-dot is-'+esc(state)+'"></i></span><span class="pt2-member-name">'+esc(member.displayName||'Gezinslid')+'</span><span class="pt2-member-state">'+esc(state==='online'?'Online':state==='recent'?'Recent':state==='today'?'Vandaag':'Offline')+'</span></button>';}).join('')+'</div>';}
  function resolvedBackdrop(member){try{if(window.HeroBackdropResolver&&typeof HeroBackdropResolver.resolve==='function')return HeroBackdropResolver.resolve(member&&member.heroBackground||null);}catch(e){}return{imageUrl:'src/assets/hero-backdrops/fantasy-castle-night.webp',focalX:.60,focalY:.47,overlayStyle:'violet-night',sceneExposure:1.04,sceneSaturation:1.04,sceneContrast:1.03,overlayStrength:.34};}
  function heroBackdropHtml(member){var backdrop=resolvedBackdrop(member||{}),url=backdrop&&backdrop.imageUrl||'';if(!url)return'';var x=Math.max(0,Math.min(1,Number(backdrop.focalX)));if(!isFinite(x))x=.5;var y=Math.max(0,Math.min(1,Number(backdrop.focalY)));if(!isFinite(y))y=.5;var exposure=Number(backdrop.sceneExposure);if(!isFinite(exposure))exposure=1;var saturation=Number(backdrop.sceneSaturation);if(!isFinite(saturation))saturation=1;var contrast=Number(backdrop.sceneContrast);if(!isFinite(contrast))contrast=1;var overlay=Number(backdrop.overlayStrength);if(!isFinite(overlay))overlay=.5;var style='--pt2-focal-x:'+(x*100).toFixed(2)+'%;--pt2-focal-y:'+(y*100).toFixed(2)+'%;--pt2-scene-exposure:'+exposure.toFixed(3)+';--pt2-scene-saturation:'+saturation.toFixed(3)+';--pt2-scene-contrast:'+contrast.toFixed(3)+';--pt2-overlay-strength:'+overlay.toFixed(3)+';';return'<div class="pt2-hero-backdrop-layer" data-overlay="'+esc(backdrop.overlayStyle||'violet-night')+'" style="'+style+'"><img src="'+esc(url)+'" alt="" decoding="async"></div>';}
  function characterPortraitHtml(member){if(member.avatar)return'<div class="pt2-hero-character"><img src="'+esc(member.avatar)+'" alt="'+esc(member.displayName||'Gezinslid')+'" decoding="async"></div>';return'<div class="pt2-hero-character pt2-hero-character-fallback">'+esc(initials(member))+'</div>';}
  function editButton(member){if(!member||!member.isCurrent)return'';return'<button type="button" class="pt2-hero-edit" data-pt2-edit-backdrop aria-label="Hero-achtergrond aanpassen">'+icon('edit',{size:'sm',label:false})+'</button>';}
  function hero(model){var member=model.member||{},progress=model.progression||{},prev=Number(progress.previousLevelXp||0),next=Number(progress.nextLevelXp||prev+1),xp=Number(progress.xp||0),pct=next>prev?clamp(((xp-prev)/(next-prev))*100):0;return'<section class="pt2-hero">'+heroBackdropHtml(member)+'<div class="pt2-hero-shade"></div>'+characterPortraitHtml(member)+editButton(member)+'<div class="pt2-level"><span>LEVEL</span><strong>'+esc(progress.level||1)+'</strong></div><div class="pt2-hero-body"><div class="pt2-hero-name"><h2>'+esc(member.displayName||'Gezinslid')+'</h2><p><span class="fa-icon-slot fa-icon-slot-muted">'+icon('title',{size:'sm',label:false})+'</span>'+esc(progress.title||'Avonturier')+'</p></div><div class="pt2-presence is-'+esc(presenceState(model))+'"><i></i>'+esc(presenceText(model))+'</div><div class="pt2-xp-meta"><span>'+xp.toLocaleString('nl-NL')+' XP</span><span>'+next.toLocaleString('nl-NL')+' XP</span></div><div class="pt2-progress"><i style="width:'+pct+'%"></i></div></div></section>';}
  function statCard(key,value,label){return'<div class="pt2-stat"><span class="pt2-stat-icon fa-icon-slot">'+icon(key,{size:'lg',label:false})+'</span><strong>'+esc(value)+'</strong><small>'+esc(label)+'</small></div>';}
  function stats(model){var q=model.quests||{},g=model.progression||{};return'<section class="pt2-section"><h3>Jouw avontuur</h3><div class="pt2-stats">'+statCard('level',g.level||1,'Level')+statCard('streak',g.streak==null?'—':g.streak,'Streak')+statCard('quest',q.completedCount||0,'Quests')+statCard('xpWeekly',q.earnedXpThisWeek||0,'XP/week')+'</div></section>';}
  function questIconKey(task){var type=String(task&&task.type||'').toUpperCase();if(type.indexOf('RAID')>-1)return'raid';if(type.indexOf('DUNGEON')>-1)return'dungeon';return'quest';}
  function quests(model){var list=((model.quests&&model.quests.active)||[]).slice(0,3),body=list.length?'<div class="pt2-quest-list">'+list.map(function(task){return'<article class="pt2-quest"><span class="pt2-quest-icon fa-icon-slot">'+icon(questIconKey(task),{size:'lg',label:false})+'</span><div class="pt2-quest-copy"><strong>'+esc(task.title||'Taak')+'</strong><small>'+esc(task.dueDate||'Actieve quest')+'</small></div><b>+'+esc(task.xp||0)+' XP</b></article>';}).join('')+'</div>':'<div class="pt2-empty">Geen actieve quests voor dit gezinslid.</div>';return'<section class="pt2-section"><div class="pt2-section-head"><h3>Actieve quests</h3><button type="button" data-pt2-tasks>Alles bekijken</button></div>'+body+'</section>';}
  function achievements(model){var list=((model.achievements&&model.achievements.recent)||[]).slice(0,4);if(!list.length)return'<section class="pt2-section"><h3>Achievements</h3><div class="pt2-empty">Nog geen achievements ontgrendeld.</div></section>';return'<section class="pt2-section"><h3>Achievements</h3><div class="pt2-achievements">'+list.map(function(item){return'<div class="pt2-achievement"><span class="fa-icon-slot">'+icon('achievement',{size:'lg',label:false})+'</span><strong>'+esc(item.id||'Achievement')+'</strong></div>';}).join('')+'</div></section>';}
  function dynamicHtml(model){return hero(model)+stats(model)+quests(model)+achievements(model);}
  function updateRail(models){if(!target)return;models.forEach(function(model){var button=target.querySelector('[data-pt2-member="'+CSS.escape(String(model.uid))+'"]');if(!button)return;var state=presenceState(model);button.classList.toggle('is-active',model.uid===selectedUid);var dot=button.querySelector('.pt2-status-dot');if(dot)dot.className='pt2-status-dot is-'+state;var label=button.querySelector('.pt2-member-state');if(label)label.textContent=state==='online'?'Online':state==='recent'?'Recent':state==='today'?'Vandaag':'Offline';});}
  function bindRail(){if(!target)return;target.querySelectorAll('[data-pt2-member]').forEach(function(button){if(button.dataset.pt2Bound==='1')return;button.dataset.pt2Bound='1';button.addEventListener('click',function(){selectedUid=button.getAttribute('data-pt2-member');var selected=currentModel(lastModels);updateRail(lastModels);var dynamic=target.querySelector('.pt2-dynamic');if(dynamic&&selected)dynamic.innerHTML=dynamicHtml(selected);bindDynamic();});});}
  function bindDynamic(){if(!target)return;var tasks=target.querySelector('[data-pt2-tasks]');if(tasks&&tasks.dataset.pt2Bound!=='1'){tasks.dataset.pt2Bound='1';tasks.addEventListener('click',function(){if(typeof window.setTaskTab==='function')window.setTaskTab('compact',document.querySelector('#screen-tasks .task-tabs .ttab'));});}var edit=target.querySelector('[data-pt2-edit-backdrop]');if(edit&&edit.dataset.pt2Bound!=='1'){edit.dataset.pt2Bound='1';edit.addEventListener('click',function(){var selected=currentModel(lastModels);if(selected&&window.PersonHeroBackgroundPicker&&typeof PersonHeroBackgroundPicker.open==='function')PersonHeroBackgroundPicker.open(selected.uid,selected.member&&selected.member.heroBackground||null);});}}
  function renderModels(models){if(!target)return;lastModels=Array.isArray(models)?models.slice():[];var selected=currentModel(lastModels);if(!selected){target.innerHTML='<div class="person-tab-v2"><div class="pt2-empty pt2-empty-main">Geen gezinsleden beschikbaar.</div></div>';railSignature='';return;}var nextSignature=railKey(lastModels),root=target.querySelector('.person-tab-v2'),dynamic=target.querySelector('.pt2-dynamic');if(!root||!dynamic||railSignature!==nextSignature){target.innerHTML='<div class="person-tab-v2">'+memberRail(lastModels)+'<div class="pt2-dynamic">'+dynamicHtml(selected)+'</div></div>';railSignature=nextSignature;bindRail();bindDynamic();return;}updateRail(lastModels);dynamic.innerHTML=dynamicHtml(selected);bindDynamic();}
  function connectService(){if(!window.PersonDashboardService)return false;if(unsubscribe){try{unsubscribe();}catch(e){}unsubscribe=null;}unsubscribe=window.PersonDashboardService.subscribe(function(models){renderModels(models);});return true;}
  function render(el){target=el||document.getElementById('task-content');if(!target)return;target.innerHTML='<div class="person-tab-v2"><div class="pt2-loading">Persoonsdashboard laden…</div></div>';railSignature='';if(connectService())return;var tries=0,timer=setInterval(function(){tries++;if(connectService()||tries>=20)clearInterval(timer);},100);}
  function destroy(){if(unsubscribe){try{unsubscribe();}catch(e){}unsubscribe=null;}target=null;lastModels=[];railSignature='';}
  window.PersonTabV2={version:VERSION,render:render,destroy:destroy,selectedUid:function(){return selectedUid;}};
})();
