'use strict';
// ============================================================
// TASK DETAIL POPUP v3.0 — "Warm Minimal" redesign
// Role-aware collaboration is projected from TaskSharedData.
// Visual language matches TaskCompactHome: warm cream / deep green /
// soft gold, editorial, photographic hero, thin borders, minimal shadows.
// All data/collaboration logic below is unchanged from the previous
// version — only markup (render/renderCreate) and styling (injectStyles)
// were redesigned, plus two small additive features (Uitstellen,
// Benodigdheden) that read existing task fields without introducing a
// second task store or changing the Firebase schema.
// ============================================================
(function(){
  if(window.__taskDetailPopupV1) return;
  window.__taskDetailPopupV1 = true;

  var openId = null;
  var helpPickerOpen = false;
  var detailsOpen = false;
  var closeTimer = null;
  var prevBodyOverflow = null;
  var scrollLockActive = false;
  var mode = null;
  var draftTask = null;
  var assigneePickerOpen = false;
  var catPickerOpen = false;
  var iconPickerForId = null; // subtask id whose icon picker is currently expanded (null = none open)

  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function currentUid(){try{return (window.fbUser||(window.firebase&&firebase.auth&&firebase.auth().currentUser)||{}).uid||null;}catch(e){return null;}}
  function currentName(){return localStorage.getItem('familyapp-profile-name-v1')||'Ik';}
  function members(){try{if(window.TaskSharedData&&typeof window.TaskSharedData.members==='function')return window.TaskSharedData.members()||[];}catch(e){}return[];}
  function memberByUid(uidVal){var list=members();for(var i=0;i<list.length;i++){var m=list[i];if(String(m.uid||m.id)===String(uidVal))return m;}return null;}
  function memberName(uidVal){var m=memberByUid(uidVal);if(m)return m.displayName||m.name||'Gezinslid';if(String(uidVal)===String(currentUid()))return currentName();return 'Gezinslid';}
  function initials(name){return String(name||'G').trim().split(/\s+/).map(function(p){return p.charAt(0);}).join('').slice(0,2).toUpperCase()||'G';}
  function avatarUrlFor(m){if(!m)return'';var direct=m.avatar||m.avatarUrl||m.photoURL||m.profilePhoto||'';if(direct)return direct;var name=(m.displayName||m.name||'').toLowerCase();try{return localStorage.getItem('fam_avatar_'+name)||'';}catch(e){return'';}}
  function findTask(id){return (window.taskData||[]).find(function(t){return String(t.id)===String(id);})||null;}
  function subtasks(task){var s=task&&task.subtasks;return Array.isArray(s)?s.filter(function(x){return x&&typeof x==='object';}):[];}
  function assignees(task){var out=[];if(task.assignedToUids&&typeof task.assignedToUids==='object')Object.keys(task.assignedToUids).forEach(function(uidVal){if(task.assignedToUids[uidVal])out.push({uid:String(uidVal),name:memberName(uidVal),member:memberByUid(uidVal)});});if(!out.length&&Array.isArray(task.who))task.who.forEach(function(n){out.push({uid:null,name:n,member:null});});return out;}
  function helperUid(h){return String(h&&(h.uid||h.memberId||h.id)||'');}
  function helpers(task){return Array.isArray(task&&task.helpers)?task.helpers:[];}
  function isHelper(task,uidVal){return helpers(task).some(function(h){return helperUid(h)===String(uidVal);});}
  function isOwner(task,uidVal){return !!(window.TaskSharedData&&TaskSharedData.isTaskOwner&&TaskSharedData.isTaskOwner(task,uidVal));}
  function participants(task){var out=assignees(task).slice();helpers(task).forEach(function(h){var id=helperUid(h);if(!id||out.some(function(p){return String(p.uid)===id;}))return;var m=memberByUid(id);out.push({uid:id,name:(m&&(m.displayName||m.name))||h.name||'Helper',member:m});});return out;}
  function participantAvatars(task){return participants(task).map(function(p){var u=p.member&&avatarUrlFor(p.member);return u?'<img class="tdp-party-avatar" src="'+esc(u)+'" alt="'+esc(p.name)+'">':'<span class="tdp-party-avatar">'+esc(initials(p.name))+'</span>';}).join('');}
  function xpLabel(task){if(task.xp)return task.xp;if(task.xpReward)return task.xpReward;var n=task.xpAmount||20;return '+'+n+' XP';}
  function xpNumber(task){var m=String(xpLabel(task)).match(/(\d+)/);return m?parseInt(m[1],10):20;}
  function prioLabel(p){var m={hoog:'Hoge prioriteit',high:'Hoge prioriteit',normaal:'Normale prioriteit',medium:'Normale prioriteit',laag:'Lage prioriteit',low:'Lage prioriteit'};return m[String(p||'laag').toLowerCase()]||'Normale prioriteit';}
  function frequencyLabel(task){var r=String(task.recurrence||'once').toLowerCase();var m={once:'Eenmalige taak',daily:'Dagelijkse taak',weekly:'Wekelijkse taak',monthly:'Maandelijkse taak'};return m[r]||'Eenmalige taak';}
  function dateTimeLabel(task){if(!task.date)return'Geen datum';var d=new Date(task.date+'T00:00:00'),today=new Date();today.setHours(0,0,0,0);var diff=Math.round((d-today)/86400000),label;if(diff===0)label='Vandaag';else if(diff===1)label='Morgen';else if(diff===-1)label='Gisteren';else label=d.toLocaleDateString('nl-NL',{day:'numeric',month:'short'});return label+(task.time?' '+task.time:'');}

  function iconCategory(task){var raw=String(task.category||task.type||task.title||'').toLowerCase();if(/was|laundry|kleding/.test(raw))return'laundry';if(/stof|schoon|clean|dweil|badkamer|toilet/.test(raw))return'cleaning';if(/vaat|keuken|kitchen|koken/.test(raw))return'kitchen';if(/bood|supermarkt|grocer/.test(raw))return'groceries';if(/admin|contract|rekening|factuur|bank/.test(raw))return'admin';if(/kind|speel|family|gezin/.test(raw))return'family';if(/tuin|garden|plant/.test(raw))return'garden';return'quest';}
  // Warm/earthy accent palette — matches TaskCompactHome, no purple/fantasy hues.
  var CATEGORY_ACCENT={laundry:'#4A6A82',cleaning:'#6E8B5E',kitchen:'#9C6B3C',groceries:'#4F7A52',admin:'#7A7060',family:'#A15D68',garden:'#5C7A45',quest:'#2F5233'};
  var CATEGORY_ICON_PATH={laundry:'<path d="M6 3.5h12a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-13a2 2 0 0 1 2-2Z"/><circle cx="12" cy="13" r="4.2"/><path d="M7 7h2m2 0h1"/>',cleaning:'<path d="m8 3 8 18M5 18l12-5 2 5H5Z"/><path d="M7 6h5"/>',kitchen:'<path d="M7 3v7m-3-7v5a3 3 0 0 0 6 0V3M7 10v11M16 3v18M16 3c3 2 3 7 0 9"/>',groceries:'<path d="M3 5h2l2 10h9.5l2-7H6"/><circle cx="9" cy="19" r="1.2"/><circle cx="16" cy="19" r="1.2"/>',admin:'<rect x="5" y="3.5" width="14" height="17" rx="2.5"/><path d="M8 8h8M8 12h8M8 16h5"/>',family:'<circle cx="9" cy="8" r="3"/><circle cx="16.5" cy="9" r="2.2"/><path d="M3.5 20a5.5 5.5 0 0 1 11 0M13 20a4 4 0 0 1 7.5-1.8"/>',garden:'<path d="M12 21V10M12 13c-5 0-7-3-7-7 5 0 7 3 7 7Zm0 2c5 0 7-3 7-7-5 0-7 3-7 7Z"/>',quest:'<path d="M8 4v5.2c0 1 .4 2 1.1 2.7L12 14.6l2.9-2.7A3.8 3.8 0 0 0 16 9.2V4M8 4h8M8 20h8M12 14.6V20"/>'};
  function categorySvg(cat,size){return '<svg viewBox="0 0 24 24" width="'+(size||26)+'" height="'+(size||26)+'" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(CATEGORY_ICON_PATH[cat]||CATEGORY_ICON_PATH.quest)+'</svg>';}
  // Single canonical source for the popup's category badge: a plain
  // monoline icon in the warm accent color. Deliberately not routed
  // through the richer FamilyApp icon registry here, so this screen's
  // look stays fully controlled by the warm-minimal palette below.
  function categoryBadgeHtml(cat,size){return categorySvg(cat,size||20);}
  var CATEGORY_ORDER=['quest','laundry','cleaning','kitchen','groceries','admin','family','garden'];
  var CATEGORY_LABEL={laundry:'Wasgoed',cleaning:'Schoonmaak',kitchen:'Keuken',groceries:'Boodschappen',admin:'Administratie',family:'Gezin',garden:'Tuin',quest:'Quest'};
  // ------------------------------------------------------------
  // Subtask icons: user-chosen emoji only. There is no automatic
  // keyword/content classification -- a subtask has an icon only
  // if someone explicitly picked one via SubtaskIconPicker below.
  // undefined, missing, and null all mean "no icon" everywhere a
  // subtask icon is read; never assume icon:null must be present
  // on the record (Firebase may drop null fields on write).
  // ------------------------------------------------------------
  function getSubIcon(s){var v=s&&s.icon;return (typeof v==='string'&&v)?v:null;}
  var SUBTASK_ICON_CATEGORIES=[
    {label:'Favorieten',icons:['⭐','✅','📌','✨','🔥','⏰']},
    {label:'Huis',icons:['🏠','🛏️','🚪','🪑','🪟','🗑️']},
    {label:'Schoonmaken',icons:['🧹','🧽','🧴','🧼','🪣','🚿']},
    {label:'Boodschappen',icons:['🛒','🛍️','🥦','🍎','🥛','🍞']},
    {label:'Eten',icons:['🍳','🍽️','☕','🍲','🥗','🍕']},
    {label:'Werk / school',icons:['💼','📚','🖊️','📅','🎒','📞']},
    {label:'Buiten',icons:['🌱','🌳','🚲','🏡','🌤️','🐝']},
    {label:'Verzorging',icons:['🪥','🛁','💊','🧑‍⚕️','🐾','🧴']},
    {label:'Tech',icons:['💻','📱','🔌','🖨️','⌨️','🔋']},
    {label:'Vervoer',icons:['🚗','🚌','✈️','⛽','🅿️','🚆']},
    {label:'Overig',icons:['🎯','📦','🎁','🧩','❓','✏️']}
  ];
  // SubtaskIconPicker: one small shared helper used by both the detail
  // view (bind) and the create-task view (bindCreate) so there is a
  // single picker implementation, not two parallel ones.
  function subtaskIconPickerHtml(subId,currentIcon){
    var groups=SUBTASK_ICON_CATEGORIES.map(function(cat){
      return '<div class="tdp-icon-picker-cat">'+esc(cat.label)+'</div><div class="tdp-icon-picker-grid">'+cat.icons.map(function(ic){
        return '<button type="button" class="tdp-icon-chip'+(currentIcon===ic?' selected':'')+'" data-icon-pick="'+esc(subId)+'" data-icon-value="'+esc(ic)+'">'+esc(ic)+'</button>';
      }).join('')+'</div>';
    }).join('');
    return '<div class="tdp-icon-picker">'+groups+'<button type="button" class="tdp-icon-clear-btn" data-icon-pick="'+esc(subId)+'" data-icon-value="">Geen icoon</button></div>';
  }
  function subtaskIconButtonHtml(s,accent,interactive){
    var icon=getSubIcon(s),body=icon?esc(icon):'<span class="tdp-sub-icon-empty">+</span>';
    if(!interactive)return '<span class="tdp-sub-icon" style="background:'+accent+'1f;color:'+accent+'">'+body+'</span>';
    return '<button type="button" class="tdp-sub-icon-btn" data-sub-icon-toggle="'+esc(s.id)+'" style="background:'+accent+'1f;color:'+accent+'">'+body+'</button>';
  }
  var UI_ICON_PATHS={close:'<path d="M6 6l12 12M18 6 6 18"/>',check:'<path d="M5 13l4 4L19 7"/>',lock:'<rect x="5" y="10.5" width="14" height="9" rx="2.2"/><path d="M8 10.5V8a4 4 0 0 1 8 0v2.5"/>',reopen:'<path d="M4 4.5V9h4.5"/><path d="M4.7 9A7.5 7.5 0 1 1 6 15"/>',calendar:'<rect x="4" y="5.5" width="16" height="15" rx="2.3"/><path d="M4 10h16M8 3.3v4M16 3.3v4"/>',repeat:'<path d="M4 4.5V9h4.5"/><path d="M20 19.5V15h-4.5"/><path d="M4.7 9A7.5 7.5 0 0 1 19 8M19.3 15a7.5 7.5 0 0 1-14.3 1"/>',users:'<circle cx="9" cy="8.2" r="3"/><circle cx="16.2" cy="9.3" r="2.1"/><path d="M3.3 19.2a5.7 5.7 0 0 1 11.4 0M13.6 19.2a4.1 4.1 0 0 1 7.1-2"/>',edit:'<path d="M4 20h4.2L19 9.2a2 2 0 0 0 0-2.8l-1.4-1.4a2 2 0 0 0-2.8 0L4 15.8V20Z"/>',snooze:'<circle cx="12" cy="13" r="8"/><path d="M9 2h6M12 9v4l2.5 1.5"/>',bookmark:'<path d="M7 4.2h10a1 1 0 0 1 1 1V20l-6-4-6 4V5.2a1 1 0 0 1 1-1Z"/>',trash:'<path d="M5 7h14M10 7V5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2M7 7l1 12a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2l1-12"/>',drop:'<path d="M12 3s6 6.5 6 11a6 6 0 0 1-12 0c0-4.5 6-11 6-11Z"/>'};
  function uiIcon(name,size){return '<svg viewBox="0 0 24 24" width="'+(size||14)+'" height="'+(size||14)+'" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="flex-shrink:0">'+(UI_ICON_PATHS[name]||'')+'</svg>';}
  function heroImageUrl(task){try{if(window.TaskModel&&typeof window.TaskModel.getImage==='function'){var v=window.TaskModel.getImage(task);if(v)return v;}}catch(e){}return task.heroImage||task.img||task.imageUrl||task.image||task.photo||task.cover||'';}
  function heroFallbackStyle(task){var cat=iconCategory(task),accent=CATEGORY_ACCENT[cat]||CATEGORY_ACCENT.quest;return 'background-image:linear-gradient(150deg,'+accent+'cc,'+accent+'55 85%)';}
  function ready(){return !!(window.TaskSharedData&&typeof window.TaskSharedData.update==='function'&&window.TaskSharedData.status&&window.TaskSharedData.status().ready);}
  function persistLocal(task){try{var idx=(window.taskData||[]).findIndex(function(t){return String(t.id)===String(task.id);});if(idx>-1)window.taskData[idx]=task;if(window.AppState&&typeof window.AppState.save==='function')window.AppState.save();}catch(e){}}
  function patch(id,patchObj,cb){var task=findTask(id);if(ready()){window.TaskSharedData.update(id,patchObj).then(function(saved){persistLocal(saved);if(typeof window.renderTasks==='function')window.renderTasks();if(typeof window.updateStats==='function')window.updateStats();if(cb)cb(saved);}).catch(function(err){console.warn('[TaskDetailPopup] shared update failed',err);if(typeof window.showToast==='function')window.showToast((err&&err.message)||'Kon niet opslaan — probeer opnieuw');});return;}if(!task)return;Object.keys(patchObj).forEach(function(k){task[k]=patchObj[k];});task.updatedAt=Date.now();persistLocal(task);if(typeof window.renderTasks==='function')window.renderTasks();if(typeof window.updateStats==='function')window.updateStats();if(cb)cb(task);}
  function todayIso(){var d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10);}
  function makeDraftTask(){var assigned={},me=currentUid();if(me)assigned[me]=true;return {title:'',desc:'',category:null,date:todayIso(),time:'',prio:'laag',recurrence:'once',assignedToUids:assigned,subtasks:[]};}

  // Benodigdheden (supplies): reads an existing array field if the task
  // already has one (several naming conventions are tolerated since this
  // is not yet a single canonical field elsewhere in the codebase). This
  // is read-only display for now -- no new Firebase field is written from
  // here, so there is no second data authority for supplies.
  function supplyItems(task){
    var raw=task&&(task.supplies||task.benodigdheden||task.materials||task.suppliesList);
    if(!Array.isArray(raw))return[];
    return raw.map(function(x){return typeof x==='string'?x:(x&&(x.name||x.title))||'';}).filter(Boolean);
  }

  function injectStyles(){
    if(document.getElementById('task-detail-popup-style'))return;
    var s=document.createElement('style');s.id='task-detail-popup-style';
    s.textContent=
      '.tdp-overlay{position:fixed;inset:0;background:rgba(30,26,18,.55);z-index:9500;display:flex;align-items:center;justify-content:center;padding:14px;opacity:0;pointer-events:none;transition:opacity .22s;box-sizing:border-box}.tdp-overlay.open{opacity:1;pointer-events:auto}'+
      '.tdp-card{--tdp-bg:#faf6ee;--tdp-surface:#fff;--tdp-surface-2:#f3ecdc;--tdp-border:#e7dcc4;--tdp-border-soft:#efe8d8;--tdp-text:#2b2a22;--tdp-text2:#8b8270;--tdp-green:#2f5233;--tdp-green-2:#254226;--tdp-gold:#b08c4c;--tdp-danger:#a4433a;width:100%;max-width:400px;max-height:calc(100dvh - 28px);overflow-y:auto;-webkit-overflow-scrolling:touch;background:var(--tdp-bg);color:var(--tdp-text);border-radius:20px;border:1px solid var(--tdp-border-soft);transform:translateY(18px) scale(.98);transition:transform .25s;box-shadow:0 20px 48px rgba(30,26,18,.22);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.tdp-overlay.open .tdp-card{transform:translateY(0) scale(1)}[data-theme*="dark"] .tdp-card{--tdp-bg:#161c17;--tdp-surface:#1e261f;--tdp-surface-2:#212a22;--tdp-border:#38442f;--tdp-border-soft:#2c3729;--tdp-text:#f1ead9;--tdp-text2:#a6ad9b;--tdp-green:#6fa377;--tdp-green-2:#5c8d66;--tdp-gold:#d7b978;--tdp-danger:#e08a7f;box-shadow:0 24px 64px rgba(0,0,0,.5)}'+
      '.tdp-hero{position:relative;height:140px;border-radius:20px 20px 0 0;background-size:cover;background-position:center;overflow:hidden;background-color:var(--tdp-surface-2)}.tdp-hero:after{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(0deg,var(--tdp-bg) 0%,transparent 32%)}.tdp-close{position:absolute;top:10px;right:10px;width:28px;height:28px;border-radius:50%;background:rgba(255,255,255,.94);border:none;color:#2b2a22;cursor:pointer;display:flex;align-items:center;justify-content:center;z-index:3;padding:0;box-shadow:0 2px 8px rgba(0,0,0,.15)}.tdp-xp-pill{position:absolute;top:10px;left:10px;z-index:3;background:rgba(255,255,255,.94);border-radius:9px;padding:4px 9px;font-size:11px;font-weight:800;color:var(--tdp-gold)}.tdp-xp-pill small{font-weight:700;opacity:.85;margin-left:2px}'+
      '.tdp-body{padding:14px 16px 14px}.tdp-title{font-family:Georgia,"Times New Roman",serif;font-weight:700;font-size:19px;margin:0 0 8px;line-height:1.2}.tdp-person{display:flex;align-items:center;gap:8px;margin-bottom:11px}.tdp-person-avatar,.tdp-party-avatar{width:26px;height:26px;border-radius:50%;background:var(--tdp-green);color:#fff;font-size:9.5px;font-weight:800;display:inline-flex;align-items:center;justify-content:center;object-fit:cover;border:1.5px solid var(--tdp-bg)}.tdp-party-stack{display:flex;align-items:center}.tdp-party-avatar{margin-left:-6px}.tdp-party-avatar:first-child{margin-left:0}.tdp-person-name{font-size:13px;font-weight:700}'+
      '.tdp-pillrow{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:11px}.tdp-pill{display:inline-flex;align-items:center;gap:5px;background:var(--tdp-surface-2);border:1px solid var(--tdp-border-soft);border-radius:9px;padding:5px 9px;font-size:11px;font-weight:700;color:var(--tdp-text2)}'+
      '.tdp-desc{font-size:12.5px;line-height:1.55;color:var(--tdp-text2);margin-bottom:14px}'+
      '.tdp-section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:7px}.tdp-section-label{font-size:12.5px;font-weight:700;color:var(--tdp-text)}.tdp-section-value{font-size:11px;font-weight:700;color:var(--tdp-text2)}'+
      '.tdp-box{background:var(--tdp-surface);border:1px solid var(--tdp-border-soft);border-radius:14px;padding:2px 12px;margin-bottom:12px}.tdp-sub-row{border-bottom:1px solid var(--tdp-border-soft)}.tdp-sub-row:last-child{border-bottom:none}.tdp-sub{display:flex;align-items:center;gap:9px;padding:8px 2px}.tdp-sub-chk{appearance:none;-webkit-appearance:none;width:19px;height:19px;min-width:19px;border-radius:50%;border:1.6px solid var(--tdp-border);background:transparent;display:flex;align-items:center;justify-content:center;padding:0;color:#fff}.tdp-sub-chk.done{background:var(--tdp-green);border-color:var(--tdp-green)}.tdp-sub-icon,.tdp-sub-icon-btn{width:21px;height:21px;min-width:21px;max-width:21px;box-sizing:border-box;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;font-size:12px;line-height:1;flex-shrink:0}.tdp-sub-icon-btn{appearance:none;-webkit-appearance:none;border:none;margin:0;padding:0;cursor:pointer}.tdp-sub-icon-empty{color:var(--tdp-text2);opacity:.55;font-weight:800;font-size:13px;line-height:1}.tdp-sub-text{flex:1;font-size:12.5px;font-weight:600;color:var(--tdp-text)}.tdp-sub.done .tdp-sub-text{text-decoration:line-through;color:var(--tdp-text2)}.tdp-sub-accent{background:none;border:none;color:var(--tdp-text2);font-size:11px;cursor:pointer}.tdp-sub-add,.tdp-empty-add{background:none;border:1.5px dashed var(--tdp-border);border-radius:10px;padding:7px;font-size:11px;font-weight:700;color:var(--tdp-green);cursor:pointer}.tdp-sub-add{width:100%;margin:6px 0 8px}.tdp-empty-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 2px;font-size:12px;color:var(--tdp-text2)}.tdp-icon-picker{padding:5px 2px 9px;max-height:190px;overflow-y:auto;-webkit-overflow-scrolling:touch}.tdp-icon-picker-cat{font-size:8.5px;font-weight:900;color:var(--tdp-text2);text-transform:uppercase;letter-spacing:.7px;margin:6px 1px 3px}.tdp-icon-picker-grid{display:flex;flex-wrap:wrap;gap:5px}.tdp-icon-chip{width:29px;height:29px;border-radius:9px;border:1.5px solid var(--tdp-border-soft);background:var(--tdp-surface-2);font-size:15px;display:flex;align-items:center;justify-content:center;cursor:pointer;padding:0}.tdp-icon-chip.selected{border-color:var(--tdp-green);background:rgba(47,82,51,.14)}.tdp-icon-clear-btn{width:100%;margin-top:7px;background:none;border:1.5px dashed var(--tdp-border);border-radius:10px;padding:6px;font-size:10.5px;font-weight:700;color:var(--tdp-text2);cursor:pointer}'+
      '.tdp-supplies{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:14px}.tdp-supply-pill{display:inline-flex;align-items:center;gap:6px;background:var(--tdp-surface);border:1px solid var(--tdp-border-soft);border-radius:10px;padding:7px 10px;font-size:11.5px;font-weight:600;color:var(--tdp-text)}.tdp-supply-pill svg{color:var(--tdp-text2)}'+
      '.tdp-help-box{position:relative;background:var(--tdp-surface);border:1px solid var(--tdp-border-soft);border-radius:14px;padding:9px 11px;margin-bottom:12px}.tdp-help-row{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.tdp-help-crest{flex-shrink:0;width:32px;height:32px;border-radius:50%;background:var(--tdp-surface-2);color:var(--tdp-green);display:flex;align-items:center;justify-content:center}.tdp-help-text{flex:1;min-width:0}.tdp-help-title{font-size:12px;font-weight:700;color:var(--tdp-text)}.tdp-help-sub{font-size:10.5px;color:var(--tdp-text2);line-height:1.3}#tdp-overlay .tdp-help-btn{flex:0 0 auto;width:auto;border:1.4px solid var(--tdp-green);border-radius:9px;padding:6px 10px;font-size:10.5px;font-weight:700;background:transparent;color:var(--tdp-green);cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:4px;white-space:nowrap}.tdp-help-btn.is-leave{color:var(--tdp-danger);border-color:var(--tdp-danger)}.tdp-member-pick{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px;width:100%}.tdp-member-chip{border:1.5px solid var(--tdp-border-soft);background:var(--tdp-surface-2);border-radius:99px;padding:5px 10px;font-size:11px;font-weight:700;color:var(--tdp-text);cursor:pointer}.tdp-help-status{margin-top:7px;font-size:10.5px;font-weight:700;color:var(--tdp-green);width:100%}'+
      '.tdp-cta{width:100%;border:none;border-radius:12px;padding:13px 10px;font-size:13.5px;font-weight:700;background:var(--tdp-surface-2);color:var(--tdp-text2);display:flex;align-items:center;justify-content:center;gap:7px;margin-bottom:8px}.tdp-cta.active{background:var(--tdp-green);color:#fff}.tdp-cta.done-state{background:var(--tdp-surface);color:var(--tdp-green);border:1.5px solid var(--tdp-green)}.tdp-footer-row{display:flex;gap:8px}.tdp-btn-secondary{flex:1;border:1px solid var(--tdp-border);background:var(--tdp-surface);color:var(--tdp-text);border-radius:11px;padding:11px 8px;font-size:12.5px;font-weight:700;display:flex;align-items:center;justify-content:center;gap:6px}'+
      '.tdp-edit-field{margin-bottom:7px}.tdp-edit-label{font-size:9px;font-weight:900;color:var(--tdp-text2);text-transform:uppercase}.tdp-edit-input,.tdp-edit-select,.tdp-edit-textarea{width:100%;box-sizing:border-box;border:1.5px solid var(--tdp-border-soft);border-radius:10px;padding:6px 9px;font-size:12.5px;background:var(--tdp-surface-2);color:var(--tdp-text)}.tdp-note{padding:6px 0;border-bottom:1px solid var(--tdp-border-soft)}.tdp-note-head{display:flex;justify-content:space-between;font-size:10px;font-weight:900;color:var(--tdp-text2)}.tdp-note-text{font-size:12.5px}.tdp-note-form{display:flex;gap:6px;margin-top:7px}.tdp-note-input{flex:1;border:1.5px solid var(--tdp-border-soft);border-radius:10px;padding:7px 9px}.tdp-note-send{border:none;background:var(--tdp-green);color:#fff;border-radius:10px;padding:0 12px}.tdp-del-btn{width:100%;background:none;border:none;color:var(--tdp-danger);font-size:11.5px;font-weight:700;padding:10px 0 3px}'+
      '.tdp-title-input{width:100%;border:none;border-bottom:1.5px dashed var(--tdp-border);background:transparent;font-family:Georgia,"Times New Roman",serif;font-weight:700;font-size:18px;color:var(--tdp-text);margin:0 0 8px;padding:2px 0 4px}.tdp-icon-ring{width:44px;height:44px;border-radius:50%;background:var(--tdp-surface);border:1px solid var(--tdp-border-soft);margin-top:-32px;position:relative;z-index:2;display:flex;align-items:center;justify-content:center;margin-bottom:8px}.tdp-assignee-row{display:flex;gap:5px;flex-wrap:wrap;align-items:center}.tdp-inline-date,.tdp-inline-select{border:1.5px solid var(--tdp-border-soft);border-radius:8px;padding:2px 6px;font-size:10.5px;background:var(--tdp-surface-2);color:var(--tdp-text);max-width:120px}';
    document.head.appendChild(s);
  }

  function overlayEl(){var el=document.getElementById('tdp-overlay');if(!el){el=document.createElement('div');el.id='tdp-overlay';el.className='tdp-overlay';document.body.appendChild(el);}return el;}
  function finalizeCleanup(){if(closeTimer){clearTimeout(closeTimer);closeTimer=null;}var ov=document.getElementById('tdp-overlay');if(ov&&ov.parentNode)ov.parentNode.removeChild(ov);document.body.style.overflow=prevBodyOverflow===null?'':prevBodyOverflow;prevBodyOverflow=null;scrollLockActive=false;openId=null;helpPickerOpen=false;detailsOpen=false;mode=null;draftTask=null;assigneePickerOpen=false;catPickerOpen=false;iconPickerForId=null;}
  function close(){var ov=document.getElementById('tdp-overlay');if(!ov){finalizeCleanup();return;}ov.classList.remove('open');ov.style.pointerEvents='none';if(closeTimer)clearTimeout(closeTimer);closeTimer=setTimeout(finalizeCleanup,220);}
  function toast(m){if(typeof window.showToast==='function')window.showToast(m);}

  function collaborationState(task){var me=currentUid();if(!me)return{role:'none'};if(isHelper(task,me))return{role:'helper',button:'Quest verlaten',subtitle:'Je helpt mee aan deze taak. Tik om te stoppen met helpen.'};if(isOwner(task,me)){if(task.helpRequested)return{role:'owner-pending',button:'Hulpvraag intrekken',subtitle:'Uitnodiging staat open voor '+memberName(task.helpRequestedForUid)+'.'};return{role:'owner',button:'Hulp vragen',subtitle:'Vraag iemand in huis om te helpen en deel de taak samen.'};}if(task.helpRequested&&String(task.helpRequestedForUid||'')===String(me))return{role:'invitee',button:'Hulp geven',subtitle:memberName(task.helpRequestedByUid||task.createdByUid)+' vraagt jouw hulp bij deze taak.'};return{role:'viewer',button:null,subtitle:'Deze taak is van '+memberName(task.createdByUid||task.ownerUid)+'.'};}

  function render(){
    if(mode==='create'){renderCreate();return;}var task=findTask(openId);if(!task){close();return;}injectStyles();var ov=overlayEl(),subs=subtasks(task),subDone=subs.filter(function(s){return s.done;}).length,totalXp=xpNumber(task),allSubsDone=!subs.length||subDone===subs.length,people=participants(task),mainPerson=people[0],mainAvatar=mainPerson&&mainPerson.member,mainAvatarUrl=mainAvatar?avatarUrlFor(mainAvatar):'',cat=iconCategory(task),accent=CATEGORY_ACCENT[cat]||CATEGORY_ACCENT.quest,heroImg=heroImageUrl(task),collab=collaborationState(task),isDone=!!task.done,supplies=supplyItems(task);
    var subsHtml=subs.map(function(s){var iconInteractive=!isDone;return '<div class="tdp-sub-row"><div class="tdp-sub'+(s.done?' done':'')+(isDone?' readonly':'')+'"><button class="tdp-sub-chk'+(s.done?' done':'')+'"'+(isDone?'':' data-sub-toggle="'+esc(s.id)+'"')+(isDone?' disabled':'')+'>'+(s.done?uiIcon('check',11):'')+'</button>'+subtaskIconButtonHtml(s,accent,iconInteractive)+'<span class="tdp-sub-text">'+esc(s.title)+'</span>'+(isDone?'':'<button class="tdp-sub-accent" data-sub-del="'+esc(s.id)+'">✕</button>')+'</div>'+(iconInteractive&&iconPickerForId===s.id?subtaskIconPickerHtml(s.id,getSubIcon(s)):'')+'</div>';}).join('');
    var notes=Array.isArray(task.notes)?task.notes.slice().reverse():[];var notesHtml=notes.length?notes.map(function(n){var when='';try{when=new Date(n.createdAt).toLocaleString('nl-NL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}catch(e){}return '<div class="tdp-note"><div class="tdp-note-head"><span>'+esc(memberName(n.createdByUid))+'</span><span>'+esc(when)+'</span></div><div class="tdp-note-text">'+esc(n.text)+'</div></div>';}).join(''):'<div style="font-size:11.5px;color:var(--tdp-text2);padding:4px 0">Nog geen opmerkingen.</div>';
    var helpableMembers=members().filter(function(m){var id=String(m.uid||m.id||'');return id&&id!==String(currentUid())&&!isOwner(task,id)&&!isHelper(task,id);});
    var helpChips=helpableMembers.length?helpableMembers.map(function(m){var id=m.uid||m.id;return '<button class="tdp-member-chip" data-help-pick="'+esc(id)+'">'+esc(m.displayName||m.name||'Gezinslid')+'</button>';}).join(''):'<div style="font-size:12px;color:var(--tdp-text2)">Geen andere gezinsleden beschikbaar.</div>';
    var ctaState=allSubsDone?(task.done?'active done-state':'active'):'',ctaIcon=allSubsDone?uiIcon(task.done?'reopen':'check',13):uiIcon('lock',13),ctaText=allSubsDone?(task.done?'Heropenen':'Markeer als klaar'):'Voltooi eerst alle stappen';
    var detailsHtml=detailsOpen?'<div class="tdp-box" style="padding-top:10px"><div class="tdp-edit-field"><label class="tdp-edit-label">Beschrijving</label><textarea class="tdp-edit-textarea" id="tdp-edit-desc" rows="2">'+esc(task.desc||task.description||'')+'</textarea></div><div style="display:flex;gap:8px"><div class="tdp-edit-field" style="flex:1"><label class="tdp-edit-label">Datum</label><input class="tdp-edit-input" type="date" id="tdp-edit-date" value="'+esc(task.date||'')+'"></div><div class="tdp-edit-field" style="flex:1"><label class="tdp-edit-label">Tijd</label><input class="tdp-edit-input" type="time" id="tdp-edit-time" value="'+esc(task.time||'')+'"></div></div><div class="tdp-edit-field"><label class="tdp-edit-label">Prioriteit</label><select class="tdp-edit-select" id="tdp-edit-prio">'+['laag','normaal','hoog'].map(function(p){return '<option value="'+p+'"'+((task.prio||'laag')===p?' selected':'')+'>'+prioLabel(p)+'</option>';}).join('')+'</select></div><div id="tdp-notes-list">'+notesHtml+'</div><div class="tdp-note-form"><input class="tdp-note-input" id="tdp-note-input" placeholder="Laat een opmerking achter…"><button class="tdp-note-send" id="tdp-note-send">Plaats</button></div><button class="tdp-cta active" id="tdp-save-edit" style="margin-top:8px">Wijzigingen opslaan</button><button class="tdp-del-btn" id="tdp-delete-btn">'+uiIcon('trash',13)+' Taak verwijderen</button></div>':'';
    var helpButton=collab.button?'<button class="tdp-help-btn'+(collab.role==='helper'?' is-leave':'')+'" id="tdp-help-btn" data-help-role="'+esc(collab.role)+'">'+uiIcon('users',12)+esc(collab.button)+'</button>':'';
    var suppliesHtml=supplies.length?'<div class="tdp-section-head"><span class="tdp-section-label">Benodigdheden</span></div><div class="tdp-supplies">'+supplies.map(function(item){return '<span class="tdp-supply-pill">'+uiIcon('drop',12)+esc(item)+'</span>';}).join('')+'</div>':'';
    var html='<div class="tdp-card" role="dialog" aria-modal="true"><div class="tdp-hero" style="'+(heroImg?('background-image:url('+esc(heroImg)+')'):heroFallbackStyle(task))+'"><div class="tdp-xp-pill">+'+totalXp+' <small>XP</small></div><button class="tdp-close" id="tdp-close-btn">'+uiIcon('close',13)+'</button></div><div class="tdp-body"><div class="tdp-icon-ring" style="color:'+accent+'">'+categoryBadgeHtml(cat,20)+'</div><div class="tdp-title">'+esc(task.title||'Taak')+'</div><div class="tdp-person">'+(mainAvatarUrl?'<img class="tdp-person-avatar" src="'+esc(mainAvatarUrl)+'">':'<div class="tdp-person-avatar">'+esc(initials(mainPerson?mainPerson.name:'?'))+'</div>')+'<div class="tdp-person-name">'+esc(people.map(function(p){return p.name;}).join(', ')||'Niet toegewezen')+'</div>'+(people.length>1?'<div class="tdp-party-stack">'+participantAvatars(task)+'</div>':'')+'</div><div class="tdp-pillrow"><span class="tdp-pill">'+uiIcon('calendar',12)+esc(dateTimeLabel(task))+'</span><span class="tdp-pill">'+uiIcon('repeat',12)+esc(frequencyLabel(task))+'</span><span class="tdp-pill">'+esc(prioLabel(task.prio))+'</span></div>'+(task.desc||task.description?'<div class="tdp-desc">'+esc(task.desc||task.description)+'</div>':'')+(subs.length?'<div class="tdp-section-head"><span class="tdp-section-label">Subtaken</span><span class="tdp-section-value">'+subDone+' van '+subs.length+' voltooid</span></div><div class="tdp-box"><div style="padding-top:4px">'+subsHtml+'</div>'+(isDone?'':'<button class="tdp-sub-add" id="tdp-sub-add-btn">+ Subtaak toevoegen</button></div>'):'<div class="tdp-box"><div class="tdp-empty-row"><span>Geen subtaken</span>'+(isDone?'':'<button class="tdp-empty-add" id="tdp-sub-add-btn">+ Subtaak</button>')+'</div></div>')+suppliesHtml+'<div class="tdp-help-box"><div class="tdp-help-row"><span class="tdp-help-crest">'+uiIcon('users',15)+'</span><div class="tdp-help-text"><div class="tdp-help-title">'+(collab.role==='invitee'?'Hulp gevraagd':collab.role==='helper'?'Samen aan deze taak':'Hulp nodig?')+'</div><div class="tdp-help-sub">'+esc(collab.subtitle||'')+'</div></div>'+helpButton+(helpPickerOpen&&collab.role==='owner'?'<div class="tdp-member-pick">'+helpChips+'</div>':'')+(task.helpRequested&&collab.role==='owner-pending'?'<div class="tdp-help-status">Wacht op '+esc(memberName(task.helpRequestedForUid))+'</div>':'')+'</div></div>'+detailsHtml+'<button class="tdp-cta '+ctaState+'" id="tdp-complete-btn" '+(allSubsDone?'':'disabled')+'>'+ctaIcon+ctaText+'</button><div class="tdp-footer-row"><button class="tdp-btn-secondary" id="tdp-more-btn">'+uiIcon('edit',13)+'Bewerken</button><button class="tdp-btn-secondary" id="tdp-postpone-btn">'+uiIcon('snooze',13)+'Uitstellen</button></div></div></div>';
    ov.innerHTML=html;ov.style.pointerEvents='';requestAnimationFrame(function(){ov.classList.add('open');});document.body.style.overflow='hidden';bind(ov,task,subs,collab);
  }

  function bind(ov,task,subs,collab){
    ov.onclick=function(e){if(e.target===ov)close();};var closeBtn=document.getElementById('tdp-close-btn');if(closeBtn)closeBtn.onclick=close;var moreBtn=document.getElementById('tdp-more-btn');if(moreBtn)moreBtn.onclick=function(){detailsOpen=!detailsOpen;render();};
    document.querySelectorAll('[data-sub-toggle]').forEach(function(btn){btn.onclick=function(){var id=btn.getAttribute('data-sub-toggle'),next=subs.map(function(s){return s.id===id?Object.assign({},s,{done:!s.done}):s;});patch(task.id,{subtasks:next},render);};});
    document.querySelectorAll('[data-sub-del]').forEach(function(btn){btn.onclick=function(){var id=btn.getAttribute('data-sub-del');patch(task.id,{subtasks:subs.filter(function(s){return s.id!==id;})},render);};});
    document.querySelectorAll('[data-sub-icon-toggle]').forEach(function(btn){btn.onclick=function(e){e.stopPropagation();var id=btn.getAttribute('data-sub-icon-toggle');iconPickerForId=(iconPickerForId===id)?null:id;render();};});
    document.querySelectorAll('[data-icon-pick]').forEach(function(btn){btn.onclick=function(e){e.stopPropagation();var id=btn.getAttribute('data-icon-pick'),val=btn.getAttribute('data-icon-value')||'',next=subs.map(function(s){return s.id===id?Object.assign({},s,{icon:val||null}):s;});iconPickerForId=null;patch(task.id,{subtasks:next},render);};});
    var addBtn=document.getElementById('tdp-sub-add-btn');if(addBtn)addBtn.onclick=function(){var title=(prompt('Naam van de subtaak?')||'').trim();if(!title)return;patch(task.id,{subtasks:subs.concat([{id:'sub_'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),title:title,done:false}])},render);};
    var completeBtn=document.getElementById('tdp-complete-btn');if(completeBtn)completeBtn.onclick=function(){if(!completeBtn.disabled)patch(task.id,{done:!task.done},render);};
    var helpBtn=document.getElementById('tdp-help-btn');if(helpBtn)helpBtn.onclick=function(){var service=window.TaskSharedData;if(!service)return;helpBtn.disabled=true;if(collab.role==='owner'){helpPickerOpen=!helpPickerOpen;helpBtn.disabled=false;render();return;}var p;if(collab.role==='owner-pending')p=service.retractHelp(task.id);else if(collab.role==='invitee')p=service.joinHelp(task.id);else if(collab.role==='helper')p=service.leaveHelp(task.id);Promise.resolve(p).then(function(saved){if(collab.role==='invitee'&&window.NotificationEvents&&NotificationEvents.taskHelpJoined)NotificationEvents.taskHelpJoined(saved||task,task.helpRequestedByUid||task.createdByUid||null).catch(function(){});toast(collab.role==='invitee'?'Je helpt nu mee 🤝':collab.role==='helper'?'Je hebt de taak verlaten':'Hulpvraag ingetrokken');render();}).catch(function(err){helpBtn.disabled=false;toast((err&&err.message)||'Actie mislukt');});};
    document.querySelectorAll('[data-help-pick]').forEach(function(btn){btn.onclick=function(){var targetUid=btn.getAttribute('data-help-pick');if(!window.TaskSharedData||!TaskSharedData.requestHelp)return;btn.disabled=true;TaskSharedData.requestHelp(task.id,targetUid).then(function(){helpPickerOpen=false;toast('Hulp gevraagd aan '+memberName(targetUid));render();}).catch(function(err){btn.disabled=false;toast((err&&err.message)||'Hulp vragen mislukt');});};});
    var noteSend=document.getElementById('tdp-note-send'),noteInput=document.getElementById('tdp-note-input');function submitNote(){var text=(noteInput&&noteInput.value||'').trim();if(!text)return;patch(task.id,{notes:(Array.isArray(task.notes)?task.notes:[]).concat([{id:'note_'+Date.now().toString(36),text:text,createdByUid:currentUid(),createdAt:Date.now()}])},render);}if(noteSend)noteSend.onclick=submitNote;if(noteInput)noteInput.addEventListener('keydown',function(e){if(e.key==='Enter')submitNote();});
    if(detailsOpen){var saveEdit=document.getElementById('tdp-save-edit');if(saveEdit)saveEdit.onclick=function(){patch(task.id,{desc:(document.getElementById('tdp-edit-desc')||{}).value||'',date:(document.getElementById('tdp-edit-date')||{}).value||'',time:(document.getElementById('tdp-edit-time')||{}).value||'',prio:(document.getElementById('tdp-edit-prio')||{}).value||'laag'},function(){detailsOpen=false;render();});};var delBtn=document.getElementById('tdp-delete-btn');if(delBtn)delBtn.onclick=function(){if(!confirm('Deze taak verwijderen?'))return;if(ready())TaskSharedData.remove(task.id).then(function(){close();});else if(typeof window.deleteTask==='function'){window.deleteTask(task.id);close();}};}
    // Uitstellen: shifts the task one day later using the same date field
    // and patch() path already used by the edit form -- no new Firebase
    // field, no second write path.
    var postponeBtn=document.getElementById('tdp-postpone-btn');if(postponeBtn)postponeBtn.onclick=function(){var base=task.date?new Date(task.date+'T00:00:00'):new Date();base.setDate(base.getDate()+1);var iso=base.getFullYear()+'-'+String(base.getMonth()+1).padStart(2,'0')+'-'+String(base.getDate()).padStart(2,'0');patch(task.id,{date:iso},function(){toast('Taak verzet naar morgen');render();});};
  }

  function renderCreate(){
    injectStyles();var ov=overlayEl(),draft=draftTask||(draftTask=makeDraftTask()),cat=draft.category||iconCategory(draft),accent=CATEGORY_ACCENT[cat]||CATEGORY_ACCENT.quest,totalXp=xpNumber(draft),mList=members(),chosen=mList.filter(function(m){var id=m.uid||m.id;return id&&draft.assignedToUids[id];});
    var chosenNames=chosen.map(function(m){return m.displayName||m.name||'Gezinslid';}).join(', '),avatarsHtml=chosen.length?chosen.map(function(m){var u=avatarUrlFor(m);return u?'<img class="tdp-person-avatar" src="'+esc(u)+'">':'<div class="tdp-person-avatar">'+esc(initials(m.displayName||m.name))+'</div>';}).join(''):'<div class="tdp-person-avatar">?</div>';
    var assigneePickHtml=assigneePickerOpen?'<div class="tdp-member-pick">'+mList.map(function(m){var id=m.uid||m.id;return '<button class="tdp-member-chip" data-assignee-toggle="'+esc(id)+'">'+esc(m.displayName||m.name||'Gezinslid')+'</button>';}).join('')+'</div>':'',catPickHtml=catPickerOpen?'<div class="tdp-member-pick">'+CATEGORY_ORDER.map(function(c){return '<button class="tdp-member-chip" data-cat-pick="'+c+'">'+esc(CATEGORY_LABEL[c])+'</button>';}).join('')+'</div>':'';
    var subs=draft.subtasks||[],subsHtml=subs.map(function(s){return '<div class="tdp-sub-row"><div class="tdp-sub"><button class="tdp-sub-chk" disabled></button>'+subtaskIconButtonHtml(s,accent,true)+'<span class="tdp-sub-text" data-sub-edit="'+esc(s.id)+'">'+esc(s.title)+'</span><button class="tdp-sub-accent" data-sub-del="'+esc(s.id)+'">✕</button></div>'+(iconPickerForId===s.id?subtaskIconPickerHtml(s.id,getSubIcon(s)):'')+'</div>';}).join('');
    var html='<div class="tdp-card"><div class="tdp-hero" style="'+heroFallbackStyle(draft)+'"><div class="tdp-xp-pill">+'+totalXp+' <small>XP</small></div><button class="tdp-close" id="tdp-close-btn">'+uiIcon('close',13)+'</button></div><div class="tdp-body"><div class="tdp-icon-ring" id="tdp-cat-trigger" style="color:'+accent+';cursor:pointer">'+categoryBadgeHtml(cat,20)+'</div><input class="tdp-title-input" id="tdp-create-title" placeholder="Taaknaam…" value="'+esc(draft.title)+'">'+catPickHtml+'<div class="tdp-person"><div class="tdp-assignee-row" id="tdp-assignee-trigger" style="cursor:pointer">'+avatarsHtml+'</div><div class="tdp-person-name">'+(chosenNames?esc(chosenNames):'Kies gezinslid(en)')+'</div></div>'+assigneePickHtml+'<div class="tdp-pillrow"><span class="tdp-pill"><input type="date" class="tdp-inline-date" id="tdp-create-date" value="'+esc(draft.date||'')+'"></span><span class="tdp-pill"><select class="tdp-inline-select" id="tdp-create-recurrence">'+['once','daily','weekly','monthly'].map(function(r){return '<option value="'+r+'"'+(draft.recurrence===r?' selected':'')+'>'+frequencyLabel({recurrence:r})+'</option>';}).join('')+'</select></span></div><div class="tdp-section-head"><span class="tdp-section-label">Subtaken</span></div><div class="tdp-box">'+(subsHtml||'<div class="tdp-empty-row"><span>Geen subtaken</span></div>')+'<button class="tdp-sub-add" id="tdp-sub-add-btn">+ Subtaak toevoegen</button></div><button class="tdp-cta active" id="tdp-create-save-btn">'+uiIcon('check',13)+'Taak aanmaken</button><button class="tdp-cta" id="tdp-cancel-btn" style="margin-bottom:0">Annuleren</button></div></div>';
    ov.innerHTML=html;ov.style.pointerEvents='';requestAnimationFrame(function(){ov.classList.add('open');});document.body.style.overflow='hidden';bindCreate(ov,draft);
  }
  function syncCreateFields(){if(!draftTask)return;var t=document.getElementById('tdp-create-title');if(t)draftTask.title=t.value;var d=document.getElementById('tdp-create-date');if(d)draftTask.date=d.value;var r=document.getElementById('tdp-create-recurrence');if(r)draftTask.recurrence=r.value;}
  function bindCreate(ov,draft){ov.onclick=function(e){if(e.target===ov)close();};var closeBtn=document.getElementById('tdp-close-btn');if(closeBtn)closeBtn.onclick=close;var cancelBtn=document.getElementById('tdp-cancel-btn');if(cancelBtn)cancelBtn.onclick=close;var titleInput=document.getElementById('tdp-create-title');if(titleInput)titleInput.oninput=function(){draft.title=titleInput.value;};var dateInput=document.getElementById('tdp-create-date');if(dateInput)dateInput.onchange=function(){draft.date=dateInput.value;};var rec=document.getElementById('tdp-create-recurrence');if(rec)rec.onchange=function(){draft.recurrence=rec.value;};var cat=document.getElementById('tdp-cat-trigger');if(cat)cat.onclick=function(){syncCreateFields();catPickerOpen=!catPickerOpen;renderCreate();};document.querySelectorAll('[data-cat-pick]').forEach(function(btn){btn.onclick=function(){syncCreateFields();draft.category=btn.getAttribute('data-cat-pick');catPickerOpen=false;renderCreate();};});var ass=document.getElementById('tdp-assignee-trigger');if(ass)ass.onclick=function(){syncCreateFields();assigneePickerOpen=!assigneePickerOpen;renderCreate();};document.querySelectorAll('[data-assignee-toggle]').forEach(function(btn){btn.onclick=function(){syncCreateFields();var id=btn.getAttribute('data-assignee-toggle');if(draft.assignedToUids[id])delete draft.assignedToUids[id];else draft.assignedToUids[id]=true;renderCreate();};});document.querySelectorAll('[data-sub-del]').forEach(function(btn){btn.onclick=function(){draft.subtasks=draft.subtasks.filter(function(s){return s.id!==btn.getAttribute('data-sub-del');});renderCreate();};});document.querySelectorAll('[data-sub-icon-toggle]').forEach(function(btn){btn.onclick=function(e){e.stopPropagation();syncCreateFields();var id=btn.getAttribute('data-sub-icon-toggle');iconPickerForId=(iconPickerForId===id)?null:id;renderCreate();};});document.querySelectorAll('[data-icon-pick]').forEach(function(btn){btn.onclick=function(e){e.stopPropagation();syncCreateFields();var id=btn.getAttribute('data-icon-pick'),val=btn.getAttribute('data-icon-value')||'';draft.subtasks=draft.subtasks.map(function(s){return s.id===id?Object.assign({},s,{icon:val||null}):s;});iconPickerForId=null;renderCreate();};});var add=document.getElementById('tdp-sub-add-btn');if(add)add.onclick=function(){var title=(prompt('Naam van de subtaak?')||'').trim();if(!title)return;syncCreateFields();draft.subtasks.push({id:'sub_'+Date.now().toString(36),title:title,done:false});renderCreate();};var save=document.getElementById('tdp-create-save-btn');if(save)save.onclick=function(){syncCreateFields();saveCreate(draft,save);};}
  function saveCreate(draft,btnEl){var title=String(draft.title||'').trim();if(!title){toast('Geef de taak een naam');return;}if(!Object.keys(draft.assignedToUids||{}).length){var me=currentUid();if(me)draft.assignedToUids[me]=true;}if(!window.TaskSharedData||typeof TaskSharedData.create!=='function'){toast('Taak kon niet worden opgeslagen');return;}var names=[];members().forEach(function(m){var id=m.uid||m.id;if(id&&draft.assignedToUids[id])names.push(m.displayName||m.name||'Gezinslid');});if(btnEl)btnEl.disabled=true;TaskSharedData.create({title:title,desc:draft.desc||'',description:draft.desc||'',category:draft.category||null,who:names,assignedToUids:draft.assignedToUids,createdByUid:currentUid(),date:draft.date||'',time:draft.time||'',prio:draft.prio||'laag',recurrence:draft.recurrence||'once',subtasks:draft.subtasks||[],done:false}).then(function(){toast('Taak aangemaakt ✓');close();}).catch(function(err){if(btnEl)btnEl.disabled=false;toast((err&&err.message)||'Taak kon niet worden opgeslagen');});}
  function open(id){if(closeTimer){clearTimeout(closeTimer);closeTimer=null;}var stale=document.getElementById('tdp-overlay');if(stale&&stale.parentNode)stale.parentNode.removeChild(stale);if(!scrollLockActive){prevBodyOverflow=document.body.style.overflow||'';scrollLockActive=true;}mode='detail';openId=id;helpPickerOpen=false;detailsOpen=false;assigneePickerOpen=false;catPickerOpen=false;iconPickerForId=null;render();}
  function openCreate(){if(closeTimer){clearTimeout(closeTimer);closeTimer=null;}var stale=document.getElementById('tdp-overlay');if(stale&&stale.parentNode)stale.parentNode.removeChild(stale);if(!scrollLockActive){prevBodyOverflow=document.body.style.overflow||'';scrollLockActive=true;}mode='create';openId=null;helpPickerOpen=false;detailsOpen=false;assigneePickerOpen=false;catPickerOpen=false;iconPickerForId=null;draftTask=makeDraftTask();render();}
  window.TaskDetailPopup={open:open,close:close,openCreate:openCreate,isOpen:function(){return !!openId||!!mode;}};
})();
