'use strict';
// ============================================================
// TASK COMPACT HOME v2
// Dense RPG task overview. Shared taskData remains authoritative.
// ============================================================
(function(){
  if(window.__taskCompactHomeV2)return;
  window.__taskCompactHomeV2=true;
  var state={range:'today',personUid:'all',sortDesc:false,expanded:{Vandaag:true,Morgen:true,Later:false},picker:false};

  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function members(){try{return window.TaskSharedData&&TaskSharedData.members?TaskSharedData.members()||[]:[];}catch(e){return[];}}
  function member(uid){return members().find(function(m){return (m.uid||m.id)===uid;})||null;}
  function initials(n){return String(n||'G').trim().split(/\s+/).map(function(x){return x[0]||'';}).join('').slice(0,2).toUpperCase()||'G';}
  function avatar(m){if(!m)return'';try{return m.avatarUrl||m.photoURL||localStorage.getItem('fam_avatar_'+String(m.displayName||m.name||'').toLowerCase())||'';}catch(e){return'';}}
  function tasks(){return Array.isArray(window.taskData)?window.taskData:[];}
  function assignees(t){var out=[];if(t.assignedToUids&&typeof t.assignedToUids==='object')Object.keys(t.assignedToUids).forEach(function(uid){if(t.assignedToUids[uid]){var m=member(uid);out.push({uid:uid,name:m&&(m.displayName||m.name)||'Gezinslid',member:m});}});if(!out.length&&Array.isArray(t.who))t.who.forEach(function(n){out.push({uid:null,name:n,member:null});});return out;}
  function group(t){if(!t.date)return'Later';var d=new Date(t.date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var diff=Math.round((d-now)/86400000);if(diff<=0)return'Vandaag';if(diff===1)return'Morgen';return'Later';}
  function withinRange(t){if(state.range==='all')return true;if(!t.date)return state.range==='all';var d=new Date(t.date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var diff=Math.round((d-now)/86400000);if(state.range==='today')return diff<=0;return diff>=0&&diff<=7;}
  function xp(t){var m=String(t.xp||t.xpReward||('+'+(t.xpAmount||20)+' XP')).match(/(\d+)/);return m?parseInt(m[1],10):20;}
  function levelInfo(){var total=(Number(window.myXP)||0)+(Number(window.partnerXP)||0),need=200;return{level:Math.max(1,Math.floor(total/need)+1),into:total%need,need:need,streak:Number(window.currentStreak||window.streakCount||0)||0};}
  function taskIcon(t){return t.icon||({high:'⚔️',hoog:'⚔️',low:'🪶',laag:'🪶'}[String(t.prio||t.priority||'').toLowerCase()]||'✦');}
  function dateMeta(t){if(!t.date)return'Geen datum';var d=new Date(t.date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var diff=Math.round((d-now)/86400000);return diff<=0?'Vandaag':diff===1?'Morgen':d.toLocaleDateString('nl-NL',{day:'numeric',month:'short'});}

  function ensurePolish(){if(window.__taskVisualPolishLoader)return;window.__taskVisualPolishLoader=true;var s=document.createElement('script');s.src='src/modules/tasks/taskVisualPolish.js?v=1';s.defer=true;document.head.appendChild(s);}

  function header(){var lv=levelInfo(),pct=Math.round(lv.into/lv.need*100),ms=members();var av=ms.slice(0,4).map(function(m){var u=avatar(m),n=m.displayName||m.name||'Gezinslid';return u?'<img class="tch-party-avatar" src="'+esc(u)+'" alt="'+esc(n)+'">':'<span class="tch-party-avatar">'+esc(initials(n))+'</span>';}).join('');return '<section class="tch-header"><div class="tch-shield"><span class="tch-crown">✦</span><b>'+lv.level+'</b><small>LEVEL</small></div><div class="tch-header-mid"><div class="tch-kicker">JOUW AVONTUUR</div><div class="tch-xp-row"><b>'+lv.into+'</b> / '+lv.need+' XP</div><div class="tch-xp-bar"><i class="tch-xp-fill" style="width:'+pct+'%"></i></div><div class="tch-streak">🔥 '+lv.streak+' dagen streak</div></div><div class="tch-party"><div class="tch-party-avatars">'+av+'</div><div class="tch-party-label">PARTY · '+ms.length+'</div></div></section>';}

  function filterBar(){var ms=members(),selected=state.personUid==='all'?null:member(state.personUid);var picker=state.picker?'<div class="tch-person-menu"><button data-person="all" class="'+(state.personUid==='all'?'active':'')+'">Alle personen</button>'+ms.map(function(m){var id=m.uid||m.id;return '<button data-person="'+esc(id)+'" class="'+(state.personUid===id?'active':'')+'">'+esc(m.displayName||m.name||'Gezinslid')+'</button>';}).join('')+'</div>':'';return '<div class="tch-filter-wrap"><div class="tch-filters">'+[['today','Vandaag'],['week','Deze week'],['all','Alles']].map(function(x){return '<button class="tch-chip '+(state.range===x[0]?'active':'')+'" data-range="'+x[0]+'">'+x[1]+'</button>';}).join('')+'<button class="tch-chip tch-person-trigger" id="tch-person-btn">👤 '+esc(selected?(selected.displayName||selected.name):'Alle personen')+'⌄</button><button class="tch-sort-btn" id="tch-sort-btn">'+(state.sortDesc?'↓':'↑')+'</button></div>'+picker+'</div>';}

  function row(t){var people=assignees(t),subs=Array.isArray(t.subtasks)?t.subtasks:[],done=subs.filter(function(s){return s&&s.done;}).length;var avatars=people.slice(0,3).map(function(p){var u=p.member&&avatar(p.member);return u?'<img class="tch-avatar" src="'+esc(u)+'" alt="'+esc(p.name)+'">':'<span class="tch-avatar">'+esc(initials(p.name))+'</span>';}).join('');var meta=[dateMeta(t),people.map(function(p){return p.name;}).join(', ')||'Niet toegewezen'];if(subs.length)meta.push(done+'/'+subs.length+' stappen');return '<article class="tch-row '+(t.done?'is-done':'')+'" data-task-id="'+esc(t.id)+'"><button class="tch-check '+(t.done?'done':'')+'" data-quick-toggle="'+esc(t.id)+'">'+(t.done?'✓':'')+'</button><div class="tch-icon">'+taskIcon(t)+'</div><div class="tch-main"><div class="tch-name">'+esc(t.title||'Taak')+'</div><div class="tch-meta">'+meta.map(function(x){return '<span>'+esc(x)+'</span>';}).join('<i>•</i>')+'</div></div><div class="tch-avatars">'+avatars+'</div><div class="tch-reward">+'+xp(t)+'<small>XP</small></div><div class="tch-chevron">›</div></article>';}

  function section(name,list){var open=!!state.expanded[name];return '<section class="tch-group"><button class="tch-group-head" data-group-toggle="'+name+'"><span><b>'+name+'</b><em>'+list.length+' '+(list.length===1?'taak':'taken')+'</em></span><span class="tch-group-right"><span class="tch-group-add" data-quick-add="1">+ Taak</span><i>'+ (open?'⌃':'⌄') +'</i></span></button>'+(open?(list.length?'<div class="tch-list">'+list.map(row).join('')+'</div>':'<div class="tch-empty">Geen quests in deze categorie.</div>'):'')+'</section>';}

  function render(el){if(!el)el=document.getElementById('task-content');if(!el)return;ensurePolish();var all=tasks().filter(withinRange);if(state.personUid!=='all')all=all.filter(function(t){return t.assignedToUids&&t.assignedToUids[state.personUid];});all.sort(function(a,b){var x=String(a.date||'9999'),y=String(b.date||'9999'),c=x.localeCompare(y);return state.sortDesc?-c:c;});var g={Vandaag:[],Morgen:[],Later:[]};all.forEach(function(t){g[group(t)].push(t);});el.innerHTML='<div class="tch-page"><div class="tch-page-title"><div><span>QUEST LOG</span><h2>Taken</h2></div><button class="tch-add-top" data-quick-add="1">＋</button></div>'+header()+filterBar()+section('Vandaag',g.Vandaag)+section('Morgen',g.Morgen)+section('Later',g.Later)+'<button class="tch-party-card" id="tch-party-quest"><span class="tch-party-icon">⚔️</span><span><b>Party Quest actief</b><small>Werk samen en verdien bonus XP</small></span><i>›</i></button></div>';bind(el);}

  function bind(el){el.querySelectorAll('[data-range]').forEach(function(b){b.onclick=function(){state.range=b.dataset.range;state.expanded.Vandaag=true;state.expanded.Morgen=state.range!=='today';state.expanded.Later=state.range==='all';render(el);};});var p=document.getElementById('tch-person-btn');if(p)p.onclick=function(){state.picker=!state.picker;render(el);};el.querySelectorAll('[data-person]').forEach(function(b){b.onclick=function(){state.personUid=b.dataset.person;state.picker=false;render(el);};});var sort=document.getElementById('tch-sort-btn');if(sort)sort.onclick=function(){state.sortDesc=!state.sortDesc;render(el);};el.querySelectorAll('[data-group-toggle]').forEach(function(h){h.onclick=function(e){if(e.target.closest('[data-quick-add]'))return;var n=h.dataset.groupToggle;state.expanded[n]=!state.expanded[n];render(el);};});el.querySelectorAll('[data-quick-add]').forEach(function(b){b.onclick=function(e){e.stopPropagation();if(typeof window.openAdd==='function')window.openAdd('task');};});el.querySelectorAll('[data-quick-toggle]').forEach(function(b){b.onclick=function(e){e.stopPropagation();var id=b.dataset.quickToggle,t=tasks().find(function(x){return String(x.id)===String(id);}),subs=t&&Array.isArray(t.subtasks)?t.subtasks:[];if(subs.length&&!t.done&&!subs.every(function(s){return s.done;})){if(window.TaskDetailPopup)TaskDetailPopup.open(id);if(typeof window.showToast==='function')showToast('Voltooi eerst alle stappen');return;}if(typeof window.toggleTask==='function')window.toggleTask(id);};});el.querySelectorAll('[data-task-id]').forEach(function(r){r.onclick=function(e){if(e.target.closest('[data-quick-toggle]'))return;if(window.TaskDetailPopup)TaskDetailPopup.open(r.dataset.taskId);};});var party=document.getElementById('tch-party-quest');if(party)party.onclick=function(){if(typeof window.showGQPopup==='function')showGQPopup('Groepsquest');};}

  window.TaskCompactHome={render:render,state:state};
  window.addEventListener('familyapp:tasks-updated',function(){if(window.taskTab==='compact')render();});
})();
