'use strict';
// ============================================================
// TASK COMPACT HOME v2.1
// Dense RPG task overview. Shared taskData remains authoritative.
// When the real list is empty, local render-only preview tasks are shown.
// Preview data is NEVER persisted or written to Firebase.
// ============================================================
(function(){
  if(window.__taskCompactHomeV21)return;
  window.__taskCompactHomeV21=true;
  var state={range:'today',personUid:'all',sortDesc:false,expanded:{Vandaag:true,Morgen:true,Later:true},picker:false};

  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function members(){try{return window.TaskSharedData&&TaskSharedData.members?TaskSharedData.members()||[]:[];}catch(e){return[];}}
  function member(uid){return members().find(function(m){return (m.uid||m.id)===uid;})||null;}
  function initials(n){return String(n||'G').trim().split(/\s+/).map(function(x){return x[0]||'';}).join('').slice(0,2).toUpperCase()||'G';}
  function avatar(m){if(!m)return'';try{return m.avatarUrl||m.photoURL||localStorage.getItem('fam_avatar_'+String(m.displayName||m.name||'').toLowerCase())||'';}catch(e){return'';}}
  function isoOffset(days){var d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);}
  function previewAssignees(){var list=members(),a=list[0],b=list[1]||list[0];return{a:a?{[(a.uid||a.id)]:true}:null,b:b?{[(b.uid||b.id)]:true}:null,both:(a&&b)?{[(a.uid||a.id)]:true,[(b.uid||b.id)]:true}:null,aName:a?(a.displayName||a.name):'Jij',bName:b?(b.displayName||b.name):'Gezinslid'};}
  function previewTasks(){var p=previewAssignees();return[
    {_preview:true,id:'preview_laundry',title:'Was draaien',category:'laundry',date:isoOffset(0),prio:'hoog',xpAmount:35,assignedToUids:p.a,who:[p.aName],subtasks:[{id:'p1',title:'Was sorteren',done:true},{id:'p2',title:'Machine aanzetten',done:true},{id:'p3',title:'Was ophangen',done:false},{id:'p4',title:'Opvouwen',done:false}]},
    {_preview:true,id:'preview_clean',title:'Woonkamer stofzuigen',category:'cleaning',date:isoOffset(0),prio:'normaal',xpAmount:20,assignedToUids:p.b,who:[p.bName],subtasks:[]},
    {_preview:true,id:'preview_kitchen',title:'Vaatwasser uitruimen',category:'kitchen',date:isoOffset(1),prio:'normaal',xpAmount:15,assignedToUids:p.a,who:[p.aName],subtasks:[{id:'p5',title:'Glazen en bekers',done:false},{id:'p6',title:'Borden en bestek',done:false}]},
    {_preview:true,id:'preview_grocery',title:'Boodschappen halen',category:'groceries',date:isoOffset(1),prio:'hoog',xpAmount:30,assignedToUids:p.both,who:[p.aName,p.bName],subtasks:[{id:'p7',title:'Supermarkt',done:true},{id:'p8',title:'Drogist',done:false}]},
    {_preview:true,id:'preview_admin',title:'Energiecontract controleren',category:'admin',date:isoOffset(3),prio:'laag',xpAmount:40,assignedToUids:p.a,who:[p.aName],subtasks:[]},
    {_preview:true,id:'preview_family',title:'Speelgoed opruimen',category:'family',date:isoOffset(5),prio:'laag',xpAmount:20,assignedToUids:p.both,who:[p.aName,p.bName],subtasks:[{id:'p9',title:'Woonkamer',done:false},{id:'p10',title:'Kinderkamer',done:false}]}
  ];}
  function realTasks(){return Array.isArray(window.taskData)?window.taskData:[];}
  function tasks(){var real=realTasks();return real.length?real:previewTasks();}
  function usingPreview(){return realTasks().length===0;}
  function assignees(t){var out=[];if(t.assignedToUids&&typeof t.assignedToUids==='object')Object.keys(t.assignedToUids).forEach(function(uid){if(t.assignedToUids[uid]){var m=member(uid);out.push({uid:uid,name:m&&(m.displayName||m.name)||'Gezinslid',member:m});}});if(!out.length&&Array.isArray(t.who))t.who.forEach(function(n){out.push({uid:null,name:n,member:null});});return out;}
  function group(t){if(!t.date)return'Later';var d=new Date(t.date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var diff=Math.round((d-now)/86400000);if(diff<=0)return'Vandaag';if(diff===1)return'Morgen';return'Later';}
  function withinRange(t){if(t._preview)return true;if(state.range==='all')return true;if(!t.date)return state.range==='all';var d=new Date(t.date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var diff=Math.round((d-now)/86400000);if(state.range==='today')return diff<=0;return diff>=0&&diff<=7;}
  function xp(t){var m=String(t.xp||t.xpReward||('+'+(t.xpAmount||20)+' XP')).match(/(\d+)/);return m?parseInt(m[1],10):20;}
  function levelInfo(){var total=(Number(window.myXP)||0)+(Number(window.partnerXP)||0),need=200;return{level:Math.max(1,Math.floor(total/need)+1),into:total%need,need:need,streak:Number(window.currentStreak||window.streakCount||0)||0};}
  function iconCategory(t){var raw=String(t.category||t.type||t.title||'').toLowerCase();if(/was|laundry|kleding/.test(raw))return'laundry';if(/stof|schoon|clean|dweil|badkamer|toilet/.test(raw))return'cleaning';if(/vaat|keuken|kitchen|koken/.test(raw))return'kitchen';if(/bood|supermarkt|grocer/.test(raw))return'groceries';if(/admin|contract|rekening|factuur|bank/.test(raw))return'admin';if(/kind|speel|family|gezin/.test(raw))return'family';if(/tuin|garden|plant/.test(raw))return'garden';return'quest';}
  function iconSvg(cat){var icons={laundry:'<path d="M6 3.5h12a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-13a2 2 0 0 1 2-2Z"/><circle cx="12" cy="13" r="4.2"/><path d="M7 7h2m2 0h1"/>',cleaning:'<path d="m8 3 8 18M5 18l12-5 2 5H5Z"/><path d="M7 6h5"/>',kitchen:'<path d="M7 3v7m-3-7v5a3 3 0 0 0 6 0V3M7 10v11M16 3v18M16 3c3 2 3 7 0 9"/>',groceries:'<path d="M3 5h2l2 10h9.5l2-7H6"/><circle cx="9" cy="19" r="1.2"/><circle cx="16" cy="19" r="1.2"/>',admin:'<rect x="5" y="3.5" width="14" height="17" rx="2.5"/><path d="M8 8h8M8 12h8M8 16h5"/>',family:'<circle cx="9" cy="8" r="3"/><circle cx="16.5" cy="9" r="2.2"/><path d="M3.5 20a5.5 5.5 0 0 1 11 0M13 20a4 4 0 0 1 7.5-1.8"/>',garden:'<path d="M12 21V10M12 13c-5 0-7-3-7-7 5 0 7 3 7 7Zm0 2c5 0 7-3 7-7-5 0-7 3-7 7Z"/>',quest:'<path d="m13 2-7 11h6l-1 9 7-12h-6Z"/>'};return'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[cat]||icons.quest)+'</svg>';}
  function dateMeta(t){if(!t.date)return'Geen datum';var d=new Date(t.date+'T00:00:00'),now=new Date();now.setHours(0,0,0,0);var diff=Math.round((d-now)/86400000);return diff<=0?'Vandaag':diff===1?'Morgen':d.toLocaleDateString('nl-NL',{day:'numeric',month:'short'});}
  function ensurePolish(){if(window.__taskVisualPolishLoader)return;window.__taskVisualPolishLoader=true;var s=document.createElement('script');s.src='src/modules/tasks/taskVisualPolish.js?v=2';s.defer=true;document.head.appendChild(s);}
  function header(){var lv=levelInfo(),pct=Math.round(lv.into/lv.need*100),ms=members();var av=ms.slice(0,4).map(function(m){var u=avatar(m),n=m.displayName||m.name||'Gezinslid';return u?'<img class="tch-party-avatar" src="'+esc(u)+'" alt="'+esc(n)+'">':'<span class="tch-party-avatar">'+esc(initials(n))+'</span>';}).join('');return'<section class="tch-header"><div class="tch-shield"><span style="position:absolute;left:50%;top:48%;transform:translate(-50%,-50%);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;white-space:nowrap"><b style="margin:0;font-size:26px;line-height:1">'+lv.level+'</b><small style="margin:0;font-size:7px;line-height:1;letter-spacing:.7px">LEVEL</small></span></div><div class="tch-header-mid"><div class="tch-kicker">JOUW AVONTUUR</div><div class="tch-xp-row"><b>'+lv.into+'</b> / '+lv.need+' XP</div><div class="tch-xp-bar"><i class="tch-xp-fill" style="width:'+pct+'%"></i></div><div class="tch-streak">🔥 '+lv.streak+' dagen streak</div></div><div class="tch-party"><div class="tch-party-avatars">'+av+'</div><div class="tch-party-label">PARTY · '+ms.length+'</div></div></section>';}
  function filterBar(){var ms=members(),selected=state.personUid==='all'?null:member(state.personUid);var picker=state.picker?'<div class="tch-person-menu"><button data-person="all" class="'+(state.personUid==='all'?'active':'')+'">Alle personen</button>'+ms.map(function(m){var id=m.uid||m.id;return'<button data-person="'+esc(id)+'" class="'+(state.personUid===id?'active':'')+'">'+esc(m.displayName||m.name||'Gezinslid')+'</button>';}).join('')+'</div>':'';return'<div class="tch-filter-wrap"><div class="tch-filters">'+[['today','Vandaag'],['week','Deze week'],['all','Alles']].map(function(x){return'<button class="tch-chip '+(state.range===x[0]?'active':'')+'" data-range="'+x[0]+'">'+x[1]+'</button>';}).join('')+'<button class="tch-chip tch-person-trigger" id="tch-person-btn">👤 '+esc(selected?(selected.displayName||selected.name):'Alle personen')+'⌄</button><button class="tch-sort-btn" id="tch-sort-btn">'+(state.sortDesc?'↓':'↑')+'</button></div>'+picker+'</div>';}
  function row(t){var people=assignees(t),subs=Array.isArray(t.subtasks)?t.subtasks:[],done=subs.filter(function(s){return s&&s.done;}).length,cat=iconCategory(t);var avatars=people.slice(0,3).map(function(p){var u=p.member&&avatar(p.member);return u?'<img class="tch-avatar" src="'+esc(u)+'" alt="'+esc(p.name)+'">':'<span class="tch-avatar">'+esc(initials(p.name))+'</span>';}).join('');var meta=[dateMeta(t),people.map(function(p){return p.name;}).join(', ')||'Niet toegewezen'];if(subs.length)meta.push(done+'/'+subs.length+' stappen');return'<article class="tch-row '+(t.done?'is-done ':'')+(t._preview?'is-preview':'')+'" data-task-id="'+esc(t.id)+'" data-preview="'+(t._preview?'1':'0')+'"><button class="tch-check '+(t.done?'done':'')+'" data-quick-toggle="'+esc(t.id)+'">'+(t.done?'✓':'')+'</button><div class="tch-icon tch-icon--'+cat+'">'+iconSvg(cat)+'</div><div class="tch-main"><div class="tch-name">'+esc(t.title||'Taak')+(t._preview?'<span class="tch-preview-tag">VOORBEELD</span>':'')+'</div><div class="tch-meta">'+meta.map(function(x){return'<span>'+esc(x)+'</span>';}).join('<i>•</i>')+'</div></div><div class="tch-avatars">'+avatars+'</div><div class="tch-reward">+'+xp(t)+'<small>XP</small></div><div class="tch-chevron">›</div></article>';}
  function section(name,list){var open=!!state.expanded[name];return'<section class="tch-group"><button class="tch-group-head" data-group-toggle="'+name+'"><span><b>'+name+'</b><em>'+list.length+' '+(list.length===1?'taak':'taken')+'</em></span><span class="tch-group-right"><span class="tch-group-add" data-quick-add="1">+ Taak</span><i>'+(open?'⌃':'⌄')+'</i></span></button>'+(open?(list.length?'<div class="tch-list">'+list.map(row).join('')+'</div>':'<div class="tch-empty">Geen quests in deze categorie.</div>'):'')+'</section>';}
  function previewNotice(){return usingPreview()?'<div class="tch-preview-note"><span>✦</span><div><b>Design preview</b><small>Deze voorbeeldtaken bestaan alleen op dit scherm en worden niet opgeslagen.</small></div></div>':'';}
  function render(el){if(!el)el=document.getElementById('task-content');if(!el)return;ensurePolish();var all=tasks().filter(withinRange);if(state.personUid!=='all'&&!usingPreview())all=all.filter(function(t){return t.assignedToUids&&t.assignedToUids[state.personUid];});all.sort(function(a,b){var x=String(a.date||'9999'),y=String(b.date||'9999'),c=x.localeCompare(y);return state.sortDesc?-c:c;});var g={Vandaag:[],Morgen:[],Later:[]};all.forEach(function(t){g[group(t)].push(t);});el.innerHTML='<div class="tch-page"'+(window.__taskVisualPolishV11?'':' style="visibility:hidden"')+'><div class="tch-page-title"><div><span>QUEST LOG</span><h2>Taken</h2></div><button class="tch-add-top" data-quick-add="1">＋</button></div>'+header()+previewNotice()+filterBar()+section('Vandaag',g.Vandaag)+section('Morgen',g.Morgen)+section('Later',g.Later)+'<button class="tch-party-card" id="tch-party-quest"><span class="tch-party-icon">⚔️</span><span><b>Party Quest actief</b><small>Werk samen en verdien bonus XP</small></span><i>›</i></button></div>';bind(el);}
  function bind(el){el.querySelectorAll('[data-range]').forEach(function(b){b.onclick=function(){state.range=b.dataset.range;state.expanded.Vandaag=true;state.expanded.Morgen=state.range!=='today';state.expanded.Later=state.range==='all'||usingPreview();render(el);};});var p=document.getElementById('tch-person-btn');if(p)p.onclick=function(){state.picker=!state.picker;render(el);};el.querySelectorAll('[data-person]').forEach(function(b){b.onclick=function(){state.personUid=b.dataset.person;state.picker=false;render(el);};});var sort=document.getElementById('tch-sort-btn');if(sort)sort.onclick=function(){state.sortDesc=!state.sortDesc;render(el);};el.querySelectorAll('[data-group-toggle]').forEach(function(h){h.onclick=function(e){if(e.target.closest('[data-quick-add]'))return;var n=h.dataset.groupToggle;state.expanded[n]=!state.expanded[n];render(el);};});el.querySelectorAll('[data-quick-add]').forEach(function(b){b.onclick=function(e){e.stopPropagation();if(window.TaskDetailPopup&&typeof window.TaskDetailPopup.openCreate==='function')window.TaskDetailPopup.openCreate();};});el.querySelectorAll('[data-quick-toggle]').forEach(function(b){b.onclick=function(e){e.stopPropagation();var row=b.closest('[data-preview]');if(row&&row.dataset.preview==='1'){if(typeof window.showToast==='function')showToast('Voorbeeldtaak — voeg een echte taak toe om te testen');return;}var id=b.dataset.quickToggle,t=realTasks().find(function(x){return String(x.id)===String(id);}),subs=t&&Array.isArray(t.subtasks)?t.subtasks:[];if(subs.length&&!t.done&&!subs.every(function(s){return s.done;})){if(window.TaskDetailPopup)TaskDetailPopup.open(id);if(typeof window.showToast==='function')showToast('Voltooi eerst alle stappen');return;}if(typeof window.toggleTask==='function')window.toggleTask(id);};});el.querySelectorAll('[data-task-id]').forEach(function(r){r.onclick=function(e){if(e.target.closest('[data-quick-toggle]'))return;if(r.dataset.preview==='1'){if(typeof window.showToast==='function')showToast('Dit is alleen een visuele voorbeeldtaak');return;}if(window.TaskDetailPopup)TaskDetailPopup.open(r.dataset.taskId);};});var party=document.getElementById('tch-party-quest');if(party)party.onclick=function(){if(typeof window.showGQPopup==='function')showGQPopup('Groepsquest');};}
  window.TaskCompactHome={render:render,state:state,isPreview:usingPreview};
  window.addEventListener('familyapp:tasks-updated',function(){if(window.taskTab==='compact')render();});
})();