'use strict';
// ============================================================
// TASK UID CREATE BRIDGE v1.2
// UID assignment + shared create. Recurring tasks remain legacy.
// ============================================================
(function(){
  if(window.__taskUidCreateBridgeV1)return;window.__taskUidCreateBridgeV1=true;
  var selected={},installed=false,originalTaskBuild=null,originalSaveItem=null;
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function currentUid(){try{return (window.fbUser||(window.firebase&&firebase.auth&&firebase.auth().currentUser)||{}).uid||null;}catch(e){return null;}}
  function members(){try{if(window.HouseholdIdentityFirebaseBridge&&typeof HouseholdIdentityFirebaseBridge.getMembers==='function'){var x=HouseholdIdentityFirebaseBridge.getMembers();if(x&&x.length)return x;}if(window.TaskSharedData&&TaskSharedData.members)return TaskSharedData.members()||[];}catch(e){}return[];}
  function reset(){selected={};var me=currentUid();if(me)selected[me]=true;window.taskSelectedAssigneeUids=selected;}
  function selectedMembers(){return members().filter(function(m){var id=m.uid||m.id;return id&&selected[id];});}
  function assigneeHtml(){var list=members();if(!list.length)return'<div style="font-size:12px;color:var(--c-text2);padding:8px 0">Gezinsleden worden geladen…</div>';var me=currentUid();if(!Object.keys(selected).length&&me)selected[me]=true;return'<div class="assignee-row task-uid-assignees" style="flex-wrap:wrap">'+list.map(function(m){var id=m.uid||m.id,n=m.displayName||m.name||'Gezinslid';return'<button type="button" class="assignee-chip'+(selected[id]?' active':'')+'" data-task-assignee-uid="'+esc(id)+'" onclick="taskUidToggleAssignee(this)">'+esc(n)+'</button>';}).join('')+'</div>';}
  function enhance(html){var start=html.indexOf('<div id="fields-eenmalig">'),rec=html.indexOf('<div id="fields-herhalend"');if(start<0||rec<0)return html;var part=html.slice(start,rec),who=part.indexOf('<div class="field"><label>Wie</label>'),date=part.indexOf('<div class="field"><label>Datum</label>');if(who<0||date<0)return html;var note='<div class="field task-create-note"><label>Notitie / omschrijving <span style="opacity:.55;font-weight:600">optioneel</span></label><textarea id="task-create-description" rows="3" placeholder="Bijv. witte was apart, gebruik fijnwasprogramma…" style="box-sizing:border-box;width:100%;resize:none;border:1px solid var(--c-border,#e5e7eb);border-radius:14px;padding:12px;font:inherit;background:var(--c-card,#fff);color:var(--c-text,#111827)"></textarea></div>';var rebuilt=part.slice(0,who)+'<div class="field"><label>Wie</label>'+assigneeHtml()+'</div>'+note+part.slice(date);return html.slice(0,start)+rebuilt+html.slice(rec);}
  window.taskUidToggleAssignee=function(btn){var id=btn&&btn.getAttribute('data-task-assignee-uid');if(!id)return;if(selected[id])delete selected[id];else selected[id]=true;if(!Object.keys(selected).length)selected[id]=true;window.taskSelectedAssigneeUids=selected;document.querySelectorAll('[data-task-assignee-uid]').forEach(function(b){b.classList.toggle('active',!!selected[b.getAttribute('data-task-assignee-uid')]);});};
  function nextId(){return window.TaskSharedData&&TaskSharedData.newLegacyId?TaskSharedData.newLegacyId():(Date.now()*1000)+Math.floor(Math.random()*1000);}
  function build(title){var date=(document.getElementById('f3')||{}).value||null,prio=(document.getElementById('f4')||{}).value||'med',desc=((document.getElementById('task-create-description')||{}).value||'').trim(),chosen=selectedMembers();if(!chosen.length){var me=currentUid(),mine=members().find(function(m){return(m.uid||m.id)===me;});if(mine)chosen=[mine];}var assigned={},names=[];chosen.forEach(function(m){var id=m.uid||m.id;if(id)assigned[id]=true;names.push(m.displayName||m.name||'Gezinslid');});return{id:nextId(),title:title,description:desc,desc:desc,who:names,assignedToUids:assigned,createdByUid:currentUid(),date:date,done:false,prio:prio,createdAt:Date.now(),updatedAt:Date.now()};}
  function create(title){if(!window.TaskSharedData||!TaskSharedData.create)return false;var task=build(title);if(!Object.keys(task.assignedToUids).length){if(window.showToast)showToast('Kies minimaal één gezinslid');return true;}TaskSharedData.create(task).then(function(saved){if(!Array.isArray(window.taskData))window.taskData=[];if(!window.taskData.some(function(t){return String(t.id)===String(saved.id);}))window.taskData.unshift(saved);try{if(window.AppState&&AppState.save)AppState.save();if(window.renderTasks)renderTasks();if(window.updateStats)updateStats();}catch(e){}}).catch(function(e){if(window.showToast)showToast('Taak kon niet worden opgeslagen');console.warn('[TaskUidCreateBridge]',e);});try{if(window.addActivity)addActivity('📋','#f0ede8',(window.myName||'Gezinslid')+' maakte taak "'+title+'" aan');if(window.addNotif)addNotif('📋','#f0ede8','Nieuwe taak',title);if(window.closeAdd)closeAdd();}catch(e){}window.taskTypeMode='eenmalig';reset();return true;}
  function install(){if(typeof window.SHEETS==='undefined'||!SHEETS.task||typeof SHEETS.task.build!=='function'||typeof window.saveItem!=='function')return false;if(installed&&saveItem.__taskUidCreateBridgeV1)return true;if(!originalTaskBuild)originalTaskBuild=SHEETS.task.build;SHEETS.task.build=function(){reset();return enhance(originalTaskBuild.apply(this,arguments));};originalSaveItem=window.saveItem;window.saveItem=function(){if(window.currentAddType==='task'&&window.taskTypeMode!=='herhalend'){var input=document.getElementById('f1'),title=input?input.value.trim():'';if(!title){if(window.closeAdd)closeAdd();return;}if(create(title))return;}return originalSaveItem.apply(this,arguments);};window.saveItem.__taskUidCreateBridgeV1=true;installed=true;return true;}
  function ensure(){if(install())return;var tries=0,timer=setInterval(function(){tries++;if(install()||tries>120)clearInterval(timer);},100);}
  reset();window.addEventListener('load',function(){setTimeout(ensure,0);});window.addEventListener('familyapp:household-identity-synced',function(){if(window.currentAddType==='task'&&window.taskTypeMode!=='herhalend'){var row=document.querySelector('.task-uid-assignees');if(row)row.outerHTML=assigneeHtml();}});setTimeout(ensure,0);
})();

// Normalize TaskSharedData.update() for UI consumers and preserve the existing
// completion XP/activity side effects when completion starts from the shared popup.
(function(){
  if(window.__taskSharedUpdateContractV1)return;window.__taskSharedUpdateContractV1=true;
  function rewardFor(task){var raw=task&&(task.xpAmount||task.xpReward||task.xp)||20,m=String(raw).match(/(\d+)/);return m?parseInt(m[1],10):20;}
  function install(){var api=window.TaskSharedData;if(!api||typeof api.update!=='function')return false;if(api.update.__returnsSavedTask)return true;var raw=api.update;api.update=function(id,patch){var before=(window.taskData||[]).find(function(t){return String(t.id)===String(id);}),wasDone=before?!!before.done:false;return raw.apply(api,arguments).then(function(result){var saved=result&&result.value&&typeof result.value==='object'?result.value:result,isDone=saved&&typeof saved==='object'?!!saved.done:!!(patch&&patch.done);if(!wasDone&&isDone){try{if(window.awardXP)awardXP(rewardFor(saved||before),'Taak');}catch(e){}try{if(window.addActivity)addActivity('✅','#e8f5e3',(window.myName||'Gezinslid')+' voltooide "'+((saved&&saved.title)||(before&&before.title)||'Taak')+'"');}catch(e){}}return saved;});};api.update.__returnsSavedTask=true;return true;}
  if(!install()){var tries=0,timer=setInterval(function(){tries++;if(install()||tries>80)clearInterval(timer);},50);}
})();
