'use strict';
// TASK MUTATION REPOSITORY BRIDGE v0.336 - persistence + idempotent progression.
(function(){
  var VERSION='0.336',wrapped=false,pendingRewards={};
  function findTask(id){return(window.taskData||[]).find(function(t){return String(t.id)===String(id);})||null;}function persist(operation,id){if(window.TaskRepositoryAdapter&&typeof TaskRepositoryAdapter.persistGlobals==='function')TaskRepositoryAdapter.persistGlobals({operation:operation||'taskMutation',id:id||null,source:'taskMutationRepositoryBridge',version:VERSION});}
  function rewardNow(task){if(!task||!task.done)return false;if(window.FamilyProgression&&typeof FamilyProgression.awardTaskCompletion==='function'&&FamilyProgression.isReady&&FamilyProgression.isReady()){FamilyProgression.awardTaskCompletion(task,{xp:4,source:'toggleTask'});return true;}return false;}
  function rewardIfCompleted(task,wasDone){if(!task||wasDone||!task.done)return;if(rewardNow(task))return;pendingRewards[String(task.id)]=JSON.parse(JSON.stringify(task));}function flushPending(){Object.keys(pendingRewards).forEach(function(key){var task=findTask(key)||pendingRewards[key];if(task&&task.done&&rewardNow(task))delete pendingRewards[key];else if(!task||!task.done)delete pendingRewards[key];});}
  function wrap(){if(wrapped||typeof window.toggleTask!=='function'||typeof window.deleteTask!=='function')return false;var originalToggle=window.toggleTask,originalDelete=window.deleteTask;window.toggleTask=function(id){var before=findTask(id),wasDone=!!(before&&before.done),result=originalToggle.apply(this,arguments),after=findTask(id);rewardIfCompleted(after,wasDone);persist('toggleTask',id);return result;};window.deleteTask=function(id){var result=originalDelete.apply(this,arguments);delete pendingRewards[String(id)];persist('deleteTask',id);return result;};wrapped=true;try{window.dispatchEvent(new CustomEvent('familyapp:tasks-mutation-bridge-ready',{detail:{version:VERSION}}));}catch(e){}return true;}
  function boot(){wrap();[100,300,800,1500,3000].forEach(function(d){setTimeout(function(){wrap();flushPending();},d);});window.addEventListener('familyapp:progression:ready',flushPending);}window.TaskMutationRepositoryBridge={version:VERSION,boot:boot,persist:persist,flushPending:flushPending};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
