'use strict';
(function(){
  if(window.__taskCompactLifecyclePolishV1)return;
  window.__taskCompactLifecyclePolishV1=true;
  function tasks(){return Array.isArray(window.taskData)?window.taskData:[];}
  function diff(t){if(!t||!t.date)return null;var d=new Date(t.date+'T00:00:00'),n=new Date();n.setHours(0,0,0,0);return Math.round((d-n)/86400000);}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function ensureCss(){if(document.getElementById('tch-life-css'))return;var s=document.createElement('style');s.id='tch-life-css';s.textContent='.tch-overdue-badge{display:inline-flex;margin-left:6px;padding:2px 6px;border-radius:99px;background:#fee2e2;color:#b91c1c;font-size:8px;font-weight:900;letter-spacing:.5px}.tch-completed-group .tch-row{opacity:.72}';document.head.appendChild(s);}
  function makeGroup(name,cls){var x=document.createElement('section');x.className='tch-group '+cls;x.dataset.lifeGroup=name;x.innerHTML='<button class="tch-group-head" type="button"><span><b>'+name+'</b><em>0 taken</em></span><span class="tch-group-right"><i>⌃</i></span></button><div class="tch-list"></div>';x.querySelector('.tch-group-head').onclick=function(){var l=x.querySelector('.tch-list'),i=x.querySelector('i'),hide=l.style.display!=='none';l.style.display=hide?'none':'';i.textContent=hide?'⌄':'⌃';};return x;}
  function count(g){var n=g.querySelectorAll('.tch-list>.tch-row').length,em=g.querySelector('em');if(em)em.textContent=n+' '+(n===1?'taak':'taken');g.style.display=n?'':'none';}
  function polish(){var page=document.querySelector('.tch-page');if(!page)return false;ensureCss();page.querySelectorAll('.tch-reward').forEach(function(r){r.innerHTML='+4<small>XP</small>';});var party=page.querySelector('#tch-party-quest small');if(party&&/XP/i.test(party.textContent))party.textContent='Werk samen en verdien 4 XP';var first=page.querySelector('.tch-group'),partyCard=page.querySelector('#tch-party-quest');var overdue=page.querySelector('[data-life-group="Verlopen"]');if(!overdue){overdue=makeGroup('Verlopen','tch-overdue-group');if(first)page.insertBefore(overdue,first);else page.appendChild(overdue);}var completed=page.querySelector('[data-life-group="Voltooid"]');if(!completed){completed=makeGroup('Voltooid','tch-completed-group');if(partyCard)page.insertBefore(completed,partyCard);else page.appendChild(completed);}var ol=overdue.querySelector('.tch-list'),cl=completed.querySelector('.tch-list');tasks().forEach(function(t){var row=page.querySelector('.tch-row[data-task-id="'+esc(t.id)+'"]');if(!row)return;var meta=row.querySelector('.tch-meta span');if(t.done){if(meta)meta.textContent='Voltooid';cl.appendChild(row);return;}var d=diff(t);if(d<0){if(meta){var n=Math.abs(d);meta.textContent='Verlopen · '+n+' '+(n===1?'dag':'dagen');}var name=row.querySelector('.tch-name');if(name&&!name.querySelector('.tch-overdue-badge'))name.insertAdjacentHTML('beforeend','<span class="tch-overdue-badge">VERLOPEN</span>');ol.appendChild(row);}else if(meta&&d===0)meta.textContent='Vandaag';else if(meta&&d===1)meta.textContent='Morgen';});count(overdue);count(completed);return true;}
  function run(){setTimeout(polish,0);setTimeout(polish,120);}
  window.addEventListener('familyapp:tasks-updated',run);document.addEventListener('click',function(){setTimeout(polish,100);},true);var n=0,t=setInterval(function(){n++;if(polish()||n>60)clearInterval(t);},250);window.TaskCompactLifecyclePolish={apply:polish};
})();
