'use strict';
// ============================================================
// FINANCE ANALYSIS UI v1.0.0
// Premium period dashboard backed exclusively by FinanceAnalysisEngine.
// ============================================================
(function(){
  var VERSION='1.0.0';
  if(window.FinanceAnalysisUI&&window.FinanceAnalysisUI.version===VERSION)return;
  var prefs=null,lastModel=null,STYLE_ID='finance-analysis-v1-style';

  function E(){return window.FinanceAnalysisEngine;}
  function S(){return window.FinanceStore;}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function euro(v){return '€ '+Math.abs(Number(v)||0).toLocaleString('nl-NL',{maximumFractionDigits:0});}
  function signedEuro(v){v=Number(v)||0;return(v>0?'+ ':v<0?'− ':'')+euro(v);}
  function percent(v){return v==null||!Number.isFinite(Number(v))?'—':(Math.round(Number(v)*10)/10).toLocaleString('nl-NL')+'%';}
  function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function pretty(v){if(!v)return'';var p=v.split('-').map(Number);try{return new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',year:p[0]===new Date().getFullYear()?undefined:'numeric'}).format(new Date(p[0],p[1]-1,p[2]));}catch(e){return v;}}
  function rangeText(r){return pretty(r.start)+' – '+pretty(r.end);}
  function scopeKey(){try{var c=window.HouseholdContext&&HouseholdContext.snapshot?HouseholdContext.snapshot():null;return c&&c.uid&&c.householdId?c.uid+'_'+c.householdId:'anonymous';}catch(e){return'anonymous';}}
  function key(){return'familyapp_finance_analysis_v1_'+scopeKey();}
  function defaults(){var r=E().calendarMonthRange(today());return{mode:'calendar',cycleStartDay:1,start:r.start,end:r.end,compareMode:'previous',compareStart:'',compareEnd:''};}
  function loadPrefs(){var p=defaults(),saved={};try{saved=JSON.parse(localStorage.getItem(key())||'{}')||{};}catch(e){}p=Object.assign(p,saved);p.cycleStartDay=Math.min(31,Math.max(1,Number(p.cycleStartDay)||1));try{var r=E().normalizeRange({start:p.start,end:p.end});p.start=r.start;p.end=r.end;}catch(e){var d=defaults();p.start=d.start;p.end=d.end;}if(p.compareMode!=='custom')p.compareMode='previous';return p;}
  function savePrefs(){try{localStorage.setItem(key(),JSON.stringify(prefs));}catch(e){}}
  function cmpRange(){if(prefs.compareMode==='custom'&&prefs.compareStart&&prefs.compareEnd)return{start:prefs.compareStart,end:prefs.compareEnd};return E().previousEqualRange({start:prefs.start,end:prefs.end});}
  function compute(){return E().comparePeriods(S().get(),{range:{start:prefs.start,end:prefs.end},compareRange:cmpRange(),cycleStartDay:prefs.cycleStartDay});}
  function delta(d,inverse){var n=Number(d&&d.absolute)||0,cls=!n?'neutral':(inverse?n<0:n>0)?'good':'bad',arrow=!n?'→':n>0?'↑':'↓';return'<span class="fa-delta '+cls+'">'+arrow+' '+esc(percent(d&&d.percent))+'</span>';}

  function styles(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent=[
    '#fin-analyse.finance-analysis-owned{padding:0 0 120px!important}.fa-wrap{max-width:760px;margin:0 auto;display:flex;flex-direction:column;gap:12px}',
    '.fa-card{background:var(--c-surface);border:1px solid var(--c-border);border-radius:22px;box-shadow:0 7px 22px rgba(17,24,39,.055);overflow:hidden}.fa-pad{padding:16px}',
    '.fa-period{background:linear-gradient(145deg,var(--c-surface),var(--c-surface2))}.fa-eyebrow{font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:var(--c-text3,var(--c-text2))}.fa-title{font-size:21px;font-weight:950;color:var(--c-text);margin-top:4px}.fa-sub{font-size:10.5px;line-height:1.4;color:var(--c-text2);margin-top:4px}',
    '.fa-chips{display:flex;gap:7px;overflow:auto;margin-top:13px}.fa-chip{border:1px solid var(--c-border);border-radius:999px;background:var(--c-surface);color:var(--c-text2);padding:8px 11px;font-size:11px;font-weight:900;white-space:nowrap}.fa-chip.active{background:var(--c-primary);border-color:var(--c-primary);color:#fff}',
    '.fa-grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.fa-field label{display:block;font-size:9.5px;font-weight:850;color:var(--c-text2);margin-bottom:5px}.fa-field input,.fa-field select,.fa-cycle select{width:100%;box-sizing:border-box;border:1px solid var(--c-border);border-radius:12px;background:var(--c-surface);color:var(--c-text);padding:9px 10px;font-size:12px;font-weight:750}',
    '.fa-cycle{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:9px;padding:10px 11px;border:1px solid var(--c-border);border-radius:14px;background:var(--c-surface)}.fa-cycle-copy{font-size:10.5px;line-height:1.35;color:var(--c-text2)}.fa-cycle-copy b{color:var(--c-text)}.fa-cycle select{width:auto;min-width:66px}',
    '.fa-hero{padding:20px 18px;background:linear-gradient(145deg,#183e34,#2d7057);color:#fff}.fa-hero .fa-eyebrow{color:rgba(255,255,255,.72)}.fa-hero-value{font-size:36px;font-weight:950;letter-spacing:-.04em;margin:7px 0 8px}.fa-hero-row{display:flex;align-items:center;gap:8px;flex-wrap:wrap;font-size:10.5px;opacity:.9}',
    '.fa-kpis{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fa-kpi{padding:13px}.fa-kpi-label{font-size:10px;font-weight:850;color:var(--c-text2)}.fa-kpi-value{font-size:20px;font-weight:950;color:var(--c-text);margin:4px 0 6px}',
    '.fa-delta{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:10px;font-weight:900;background:var(--c-surface2);color:var(--c-text2)}.fa-delta.good{background:#dcfce7;color:#15803d}.fa-delta.bad{background:#fee2e2;color:#b91c1c}.fa-hero .fa-delta{background:rgba(255,255,255,.16);color:#fff}',
    '.fa-section-title{font-size:16px;font-weight:950;color:var(--c-text)}.fa-section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:12px}.fa-legend{display:flex;gap:8px;flex-wrap:wrap;font-size:9px;font-weight:800;color:var(--c-text2)}.fa-dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:3px}',
    '.fa-chart{width:100%;height:auto;display:block}.fa-chart text{fill:var(--c-text2);font-size:8px}.fa-cat{margin-bottom:12px}.fa-cat:last-child{margin-bottom:0}.fa-cat-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.fa-cat-name,.fa-cat-amount{font-size:12px;font-weight:900;color:var(--c-text)}.fa-cat-right{display:flex;align-items:center;gap:6px}.fa-bar{height:7px;background:var(--c-surface2);border-radius:99px;overflow:hidden;margin-top:6px}.fa-bar span{display:block;height:100%;background:var(--c-primary);border-radius:99px}',
    '.fa-split{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fa-mini{padding:12px;border-radius:16px;background:var(--c-surface2)}.fa-mini-label{font-size:9.5px;font-weight:850;color:var(--c-text2)}.fa-mini-value{font-size:18px;font-weight:950;color:var(--c-text);margin-top:3px}',
    '.fa-insight{display:flex;align-items:center;gap:10px;padding:10px;border-radius:14px;background:var(--c-surface2);margin-top:8px}.fa-insight:first-of-type{margin-top:0}.fa-insight-icon{width:32px;height:32px;border-radius:10px;display:grid;place-items:center;background:var(--c-surface)}.fa-insight-title{font-size:11px;font-weight:900;color:var(--c-text)}.fa-insight-sub{font-size:9.5px;color:var(--c-text2);margin-top:2px}',
    '.fa-note{font-size:9px;line-height:1.45;color:var(--c-text3,var(--c-text2));padding:0 2px}@media(min-width:620px){.fa-kpis{grid-template-columns:repeat(4,1fr)}}'
  ].join('\n');document.head.appendChild(s);}

  function lineChart(m){var rows=m.primary.trend.rows||[];if(!rows.length)return'<div class="fa-sub">Nog geen datapunten in deze periode.</div>';var run=[],inc=0,exp=0,sav=0;rows.forEach(function(r){inc+=Number(r.income)||0;exp+=Number(r.expenses)||0;sav+=Number(r.savings)||0;run.push({date:r.date,income:inc,expenses:exp,savings:sav});});var W=330,H=130,L=8,R=8,T=8,B=22,iw=W-L-R,ih=H-T-B,max=1;run.forEach(function(r){max=Math.max(max,r.income,r.expenses,Math.max(0,r.savings));});function pts(k){return run.map(function(r,i){var x=L+(run.length===1?iw/2:i/(run.length-1)*iw),y=T+ih-Math.max(0,r[k])/max*ih;return x.toFixed(1)+','+y.toFixed(1);}).join(' ');}return'<svg class="fa-chart" viewBox="0 0 '+W+' '+H+'">'+[0,.5,1].map(function(q){var y=T+ih-q*ih;return'<line x1="'+L+'" y1="'+y+'" x2="'+(W-R)+'" y2="'+y+'" stroke="var(--c-border)" stroke-dasharray="3 4"/>';}).join('')+'<polyline points="'+pts('income')+'" fill="none" stroke="#16a34a" stroke-width="2.4"/><polyline points="'+pts('expenses')+'" fill="none" stroke="#dc2626" stroke-width="2.4"/><polyline points="'+pts('savings')+'" fill="none" stroke="var(--c-primary)" stroke-width="2.4"/><text x="'+L+'" y="'+(H-4)+'">'+esc(pretty(run[0].date))+'</text><text x="'+(W-R)+'" y="'+(H-4)+'" text-anchor="end">'+esc(pretty(run[run.length-1].date))+'</text></svg>';}

  function periodControls(m){var p=prefs;return'<section class="fa-card fa-pad fa-period"><div class="fa-eyebrow">Analyseperiode</div><div class="fa-title">'+esc(rangeText(m.primary.range))+'</div><div class="fa-sub">Vergelijking: '+esc(rangeText(m.comparison.range))+'</div><div class="fa-chips"><button class="fa-chip '+(p.mode==='calendar'?'active':'')+'" data-fa-mode="calendar">Kalendermaand</button><button class="fa-chip '+(p.mode==='salary'?'active':'')+'" data-fa-mode="salary">Salariscyclus</button><button class="fa-chip '+(p.mode==='custom'?'active':'')+'" data-fa-mode="custom">Eigen bereik</button></div><div class="fa-grid2"><div class="fa-field"><label>Van</label><input type="date" data-fa-start value="'+esc(p.start)+'"></div><div class="fa-field"><label>Tot en met</label><input type="date" data-fa-end value="'+esc(p.end)+'"></div></div><div class="fa-cycle"><div class="fa-cycle-copy"><b>Financiële cyclus</b><br>Startdag voor salaris en vaste lasten.</div><select data-fa-cycle>'+Array.from({length:31},function(_,i){var d=i+1;return'<option value="'+d+'" '+(d===p.cycleStartDay?'selected':'')+'>'+d+'</option>';}).join('')+'</select></div><div class="fa-grid2"><div class="fa-field" style="grid-column:1/-1"><label>Vergelijken met</label><select data-fa-compare><option value="previous" '+(p.compareMode==='previous'?'selected':'')+'>Vorige even lange periode</option><option value="custom" '+(p.compareMode==='custom'?'selected':'')+'>Andere periode</option></select></div></div>'+(p.compareMode==='custom'?'<div class="fa-grid2"><div class="fa-field"><label>Vergelijk vanaf</label><input type="date" data-fa-cstart value="'+esc(p.compareStart||m.comparison.range.start)+'"></div><div class="fa-field"><label>Vergelijk t/m</label><input type="date" data-fa-cend value="'+esc(p.compareEnd||m.comparison.range.end)+'"></div></div>':'')+'</section>';}
  function hero(m){var x=m.primary.metrics;return'<section class="fa-card fa-hero"><div class="fa-eyebrow">'+(x.result>=0?'Over na uitgaven & sparen':'Tekort na uitgaven & sparen')+'</div><div class="fa-hero-value">'+(x.result<0?'− ':'')+euro(x.result)+'</div><div class="fa-hero-row">'+delta(m.deltas.result,false)+'<span>'+m.primary.range.days+' dagen · '+m.primary.cycleDates.length+' cyclusmoment'+(m.primary.cycleDates.length===1?'':'en')+'</span></div></section>';}
  function kpi(label,value,d,inverse,sub){return'<div class="fa-card fa-kpi"><div class="fa-kpi-label">'+esc(label)+'</div><div class="fa-kpi-value">'+esc(value)+'</div>'+delta(d,inverse)+(sub?'<div class="fa-sub">'+esc(sub)+'</div>':'')+'</div>';}
  function kpis(m){var x=m.primary.metrics;return'<div class="fa-kpis">'+kpi('Inkomsten',euro(x.income),m.deltas.income,false)+kpi('Uitgaven',euro(x.expenses),m.deltas.expenses,true)+kpi('Netto gespaard',signedEuro(x.netSavings),m.deltas.netSavings,false,'Spaarquote '+percent(x.savingsRate))+kpi('Vaste lasten',euro(x.fixedExpenses),m.deltas.fixedExpenses,true)+'</div>';}
  function trend(m){return'<section class="fa-card fa-pad"><div class="fa-section-head"><div><div class="fa-section-title">Geldstroom</div><div class="fa-sub">Cumulatief verloop in de geselecteerde periode.</div></div><div class="fa-legend"><span><i class="fa-dot" style="background:#16a34a"></i>Inkomen</span><span><i class="fa-dot" style="background:#dc2626"></i>Uitgaven</span><span><i class="fa-dot" style="background:var(--c-primary)"></i>Sparen</span></div></div>'+lineChart(m)+'</section>';}
  function categories(m){var rows=m.primary.categories||[],cmp={};m.categories.forEach(function(r){cmp[r.category]=r;});if(!rows.length)return'<section class="fa-card fa-pad"><div class="fa-section-title">Waar ging het geld heen?</div><div class="fa-sub">Nog geen uitgaven in deze periode.</div></section>';var top=rows.slice(0,8),max=top[0].amount||1;return'<section class="fa-card fa-pad"><div class="fa-section-head"><div><div class="fa-section-title">Waar ging het geld heen?</div><div class="fa-sub">Sparen staat bewust apart van gewone uitgaven.</div></div></div>'+top.map(function(r){var c=cmp[r.category]||{delta:0,deltaPercent:0};return'<div class="fa-cat"><div class="fa-cat-row"><span class="fa-cat-name">'+esc(r.category)+'</span><div class="fa-cat-right">'+delta({absolute:c.delta,percent:c.deltaPercent},true)+'<span class="fa-cat-amount">'+euro(r.amount)+'</span><span class="fa-sub">'+percent(r.share)+'</span></div></div><div class="fa-bar"><span style="width:'+Math.max(2,Math.round(r.amount/max*100))+'%"></span></div></div>';}).join('')+'</section>';}
  function split(m){var x=m.primary.metrics,total=x.expenses||1;return'<section class="fa-card fa-pad"><div class="fa-section-title">Vast versus variabel</div><div class="fa-sub">Welk deel van de uitgaven ligt structureel vast?</div><div class="fa-split" style="margin-top:12px"><div class="fa-mini"><div class="fa-mini-label">Vaste lasten</div><div class="fa-mini-value">'+euro(x.fixedExpenses)+'</div><div class="fa-sub">'+percent(x.fixedExpenses/total*100)+' van uitgaven</div></div><div class="fa-mini"><div class="fa-mini-label">Variabel</div><div class="fa-mini-value">'+euro(x.variableExpenses)+'</div><div class="fa-sub">'+percent(x.variableExpenses/total*100)+' van uitgaven</div></div></div></section>';}
  function savings(m){var s=m.primary.savings;return'<section class="fa-card fa-pad"><div class="fa-section-title">Sparen</div><div class="fa-sub">Stortingen en opnames worden niet dubbel als uitgave geteld.</div><div class="fa-split" style="margin-top:12px"><div class="fa-mini"><div class="fa-mini-label">Gestort</div><div class="fa-mini-value">'+euro(s.deposits)+'</div></div><div class="fa-mini"><div class="fa-mini-label">Opgenomen</div><div class="fa-mini-value">'+euro(s.withdrawals)+'</div></div></div><div class="fa-cat" style="margin-top:13px"><div class="fa-cat-row"><span class="fa-cat-name">Alle spaardoelen</span><span class="fa-cat-amount">'+euro(s.currentSaved)+' / '+euro(s.target)+'</span></div><div class="fa-bar"><span style="width:'+Math.min(100,Math.max(0,s.goalProgress))+'%"></span></div></div></section>';}
  function receipts(m){var r=m.primary.receipts;if(!r.count)return'';return'<section class="fa-card fa-pad"><div class="fa-section-title">Boodschappenbonnen</div><div class="fa-sub">Historische receipt-data uit Finance.</div><div class="fa-split" style="margin-top:12px"><div class="fa-mini"><div class="fa-mini-label">Bonnen</div><div class="fa-mini-value">'+r.count+'</div><div class="fa-sub">'+r.itemCount+' items</div></div><div class="fa-mini"><div class="fa-mini-label">Gemiddeld</div><div class="fa-mini-value">'+euro(r.average)+'</div><div class="fa-sub">Totaal '+euro(r.total)+'</div></div></div></section>';}
  function insights(m){if(!m.insights.length)return'';function text(i){if(i.type==='increase')return['📈',i.title,i.category+' · '+euro(i.amount)+' meer'];if(i.type==='decrease')return['📉',i.title,i.category+' · '+euro(i.amount)+' minder'];if(i.type==='savings')return['🎯',i.title,euro(i.amount)+' · '+percent(i.rate)+' van inkomen'];return['🛒',i.title,i.count+' bon'+(i.count===1?'':'nen')+' · '+euro(i.amount)];}return'<section class="fa-card fa-pad"><div class="fa-section-title">Wat valt op?</div><div class="fa-sub">Automatisch afgeleid uit dezelfde analyse-data.</div>'+m.insights.map(function(i){var t=text(i);return'<div class="fa-insight"><div class="fa-insight-icon">'+t[0]+'</div><div><div class="fa-insight-title">'+esc(t[1])+'</div><div class="fa-insight-sub">'+esc(t[2])+'</div></div></div>';}).join('')+'</section>';}

  function bind(el){
    el.querySelectorAll('[data-fa-mode]').forEach(function(b){b.onclick=function(){var mode=b.getAttribute('data-fa-mode'),r=null;if(mode==='calendar')r=E().calendarMonthRange(today());if(mode==='salary')r=E().salaryCycleRange(today(),prefs.cycleStartDay);prefs.mode=mode;if(r){prefs.start=r.start;prefs.end=r.end;}savePrefs();render();};});
    var a=el.querySelector('[data-fa-start]'),z=el.querySelector('[data-fa-end]');if(a)a.onchange=function(){prefs.start=a.value;prefs.mode='custom';savePrefs();render();};if(z)z.onchange=function(){prefs.end=z.value;prefs.mode='custom';savePrefs();render();};
    var cyc=el.querySelector('[data-fa-cycle]');if(cyc)cyc.onchange=function(){prefs.cycleStartDay=Number(cyc.value)||1;if(prefs.mode==='salary'){var r=E().salaryCycleRange(today(),prefs.cycleStartDay);prefs.start=r.start;prefs.end=r.end;}savePrefs();render();};
    var c=el.querySelector('[data-fa-compare]');if(c)c.onchange=function(){prefs.compareMode=c.value==='custom'?'custom':'previous';if(prefs.compareMode==='custom'&&(!prefs.compareStart||!prefs.compareEnd)){var r=E().previousEqualRange({start:prefs.start,end:prefs.end});prefs.compareStart=r.start;prefs.compareEnd=r.end;}savePrefs();render();};
    var cs=el.querySelector('[data-fa-cstart]'),ce=el.querySelector('[data-fa-cend]');if(cs)cs.onchange=function(){prefs.compareStart=cs.value;savePrefs();render();};if(ce)ce.onchange=function(){prefs.compareEnd=ce.value;savePrefs();render();};
  }
  function render(){var el=document.getElementById('fin-analyse');if(!el||!E()||!S())return false;styles();if(!prefs)prefs=loadPrefs();var m;try{m=compute();}catch(e){prefs=defaults();savePrefs();m=compute();}lastModel=m;el.classList.add('finance-analysis-owned');el.innerHTML='<div class="fa-wrap">'+periodControls(m)+hero(m)+kpis(m)+trend(m)+categories(m)+split(m)+savings(m)+receipts(m)+insights(m)+'<div class="fa-note">Salaris en vaste lasten volgen de ingestelde financiële cyclus. Werkelijke transacties, bonnen en spaarbewegingen volgen hun eigen datum.</div></div>';bind(el);return true;}
  function renderIfActive(){var p=document.getElementById('fin-analyse');if(p&&p.classList.contains('active'))render();}
  function install(){document.addEventListener('click',function(e){if(e.target&&e.target.closest&&e.target.closest('[data-fin-tab="analyse"]'))setTimeout(renderIfActive,0);});var screen=document.getElementById('screen-finance');if(screen&&window.MutationObserver){var ob=new MutationObserver(renderIfActive);ob.observe(screen,{subtree:true,attributes:true,attributeFilter:['class']});}[0,100,300,800,1500].forEach(function(d){setTimeout(renderIfActive,d);});}
  window.addEventListener('familyapp:finance:changed',renderIfActive);window.addEventListener('familyapp:household-members-updated',function(){prefs=null;lastModel=null;renderIfActive();});
  window.FinanceAnalysisUI={version:VERSION,render:render,getModel:function(){return lastModel;},install:install};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
