'use strict';
// ============================================================
// FINANCE ANALYSIS UI v2.0.0
// Premium STEP 8 analysis presentation backed only by FinanceAnalysisEngine.
// Light/dark share one data contract. No MutationObserver / no persistence.
// ============================================================
(function(){
  var VERSION='2.0.0';
  if(window.FinanceAnalysisUI&&window.FinanceAnalysisUI.version===VERSION)return;

  var prefs=null,lastModel=null,rendering=false,pending=false,installed=false,requestTimer=null;
  var periodOpen=false,selectedCategory=null,selectedTrendIndex=null;
  var STYLE_ID='finance-analysis-v2-style';
  var PALETTE=['#ef6685','#9b7bf5','#4ca9df','#47b985','#e8a33b','#f08358','#75a65c','#c06ac7','#8a97aa'];

  function E(){return window.FinanceAnalysisEngine;}
  function S(){return window.FinanceStore;}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function euro(v,decimals){var n=Math.abs(Number(v)||0);return '€ '+n.toLocaleString('nl-NL',{minimumFractionDigits:decimals?2:0,maximumFractionDigits:decimals?2:0});}
  function signedEuro(v){v=Number(v)||0;return(v>0?'+ ':v<0?'− ':'')+euro(v);}
  function percent(v){return v==null||!Number.isFinite(Number(v))?'—':(Math.round(Number(v)*10)/10).toLocaleString('nl-NL')+'%';}
  function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function parseLocal(v){var p=String(v||'').split('-').map(Number);return p.length===3?new Date(p[0],p[1]-1,p[2]):null;}
  function pretty(v,withYear){var d=parseLocal(v);if(!d)return String(v||'');try{return new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',year:withYear?'numeric':undefined}).format(d);}catch(e){return v;}}
  function rangeText(r){if(!r)return'';var sy=String(r.start||'').slice(0,4),ey=String(r.end||'').slice(0,4),showYear=sy!==String(new Date().getFullYear())||ey!==sy;return pretty(r.start,showYear)+' – '+pretty(r.end,showYear);}
  function scopeKey(){try{var c=window.HouseholdContext&&HouseholdContext.snapshot?HouseholdContext.snapshot():null;return c&&c.uid&&c.householdId?c.uid+'_'+c.householdId:'anonymous';}catch(e){return'anonymous';}}
  function storageKey(){return'familyapp_finance_analysis_v2_'+scopeKey();}
  function defaults(){var r=E().calendarMonthRange(today());return{mode:'calendar',cycleStartDay:1,start:r.start,end:r.end,compareMode:'previous',compareStart:'',compareEnd:''};}
  function loadPrefs(){var p=defaults(),saved={};try{saved=JSON.parse(localStorage.getItem(storageKey())||'{}')||{};}catch(e){}p=Object.assign(p,saved);p.cycleStartDay=Math.min(31,Math.max(1,Number(p.cycleStartDay)||1));try{var r=E().normalizeRange({start:p.start,end:p.end});p.start=r.start;p.end=r.end;}catch(e){var d=defaults();p.start=d.start;p.end=d.end;}if(p.compareMode!=='custom')p.compareMode='previous';return p;}
  function savePrefs(){try{localStorage.setItem(storageKey(),JSON.stringify(prefs));}catch(e){}}
  function compareRange(){if(prefs.compareMode==='custom'&&prefs.compareStart&&prefs.compareEnd)return{start:prefs.compareStart,end:prefs.compareEnd};return E().previousEqualRange({start:prefs.start,end:prefs.end});}
  function compute(){return E().comparePeriods(S().get(),{range:{start:prefs.start,end:prefs.end},compareRange:compareRange(),cycleStartDay:prefs.cycleStartDay});}
  function active(){var el=document.getElementById('fin-analyse');return !!(el&&el.classList.contains('active'));}
  function categoryColor(index){return PALETTE[index%PALETTE.length];}
  function categoryGlyph(name){var n=String(name||'').toLowerCase();if(/bood|super|eten|voeding/.test(n))return'⌁';if(/woon|huur|huis|energie/.test(n))return'⌂';if(/vervoer|auto|transport|brandstof/.test(n))return'◇';if(/vrij|uitje|hobby|horeca/.test(n))return'✦';if(/kind/.test(n))return'☆';if(/gezond|zorg/.test(n))return'+';if(/abonn/.test(n))return'↻';return'•';}
  function deltaBadge(d,inverse){var n=Number(d&&d.absolute)||0,good=inverse?n<0:n>0,cls=!n?'neutral':good?'good':'bad',arrow=!n?'→':n>0?'↑':'↓';return'<span class="fa2-delta '+cls+'">'+arrow+' '+esc(percent(d&&d.percent))+'</span>';}
  function deltaSentence(d,label){var n=Number(d&&d.absolute)||0;if(!n)return'Gelijk aan de vergelijkingsperiode';return signedEuro(n)+' '+(n>0?'meer':'minder')+' '+esc(label||'')+' dan vorige periode';}

  function ensureStyles(){
    if(document.getElementById(STYLE_ID))return;
    var s=document.createElement('style');s.id=STYLE_ID;s.textContent=[
      '#fin-analyse.finance-analysis-owned{--fa2-page:#fbfaf7;--fa2-card:rgba(255,255,255,.96);--fa2-card2:#f8f5fb;--fa2-line:#ebe5f1;--fa2-text:#262330;--fa2-muted:#777184;--fa2-faint:#a7a0af;--fa2-purple:#8b5cf6;--fa2-purple2:#a78bfa;--fa2-purpleSoft:#f1ebff;--fa2-gold:#d4a64a;--fa2-green:#45a66b;--fa2-red:#dc6677;--fa2-shadow:0 10px 28px rgba(72,55,91,.08);padding:12px 12px 120px!important;background:radial-gradient(circle at 92% 1%,rgba(167,139,250,.12),transparent 34%),var(--fa2-page)!important;color:var(--fa2-text)}',
      'html[data-theme="dark"] #fin-analyse.finance-analysis-owned,html[data-theme$="-dark"] #fin-analyse.finance-analysis-owned{--fa2-page:#090a17;--fa2-card:rgba(18,18,39,.97);--fa2-card2:#15152f;--fa2-line:#2f2951;--fa2-text:#f5f2ff;--fa2-muted:#aaa2c0;--fa2-faint:#6d6781;--fa2-purple:#9b6df2;--fa2-purple2:#c4a5ff;--fa2-purpleSoft:#2b1b50;--fa2-gold:#e0ad4f;--fa2-green:#5ed180;--fa2-red:#f06b78;--fa2-shadow:0 16px 38px rgba(0,0,0,.28);background:radial-gradient(circle at 88% 2%,rgba(122,76,214,.20),transparent 32%),linear-gradient(180deg,#090a17,#0d0c20 70%,#090a17)!important}',
      '#screen-finance.finance-analysis-active #finance-native-tabs .finance-native-tab[data-fin-tab="analyse"].active{background:#8251dd!important;box-shadow:0 7px 18px rgba(130,81,221,.28)!important}',
      '.fa2-wrap{max-width:760px;margin:0 auto;display:flex;flex-direction:column;gap:12px}.fa2-card{background:var(--fa2-card);border:1px solid var(--fa2-line);border-radius:20px;box-shadow:var(--fa2-shadow);overflow:hidden}.fa2-pad{padding:15px}',
      '.fa2-overview{position:relative;isolation:isolate}.fa2-periodbar{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 14px;border-bottom:1px solid var(--fa2-line)}.fa2-period-label{font-size:10px;font-weight:900;color:var(--fa2-muted);text-transform:uppercase;letter-spacing:.08em}.fa2-period-btn{border:1px solid var(--fa2-line);background:var(--fa2-card2);color:var(--fa2-text);border-radius:11px;padding:7px 9px;display:flex;align-items:center;gap:6px;font-size:11px;font-weight:850;max-width:70%;text-align:right}.fa2-period-btn span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
      '.fa2-period-panel{display:none;padding:12px 14px;border-bottom:1px solid var(--fa2-line);background:var(--fa2-card2)}.fa2-period-panel.open{display:block}.fa2-chips{display:flex;gap:6px;overflow:auto;padding-bottom:2px}.fa2-chip{border:1px solid var(--fa2-line);border-radius:999px;background:var(--fa2-card);color:var(--fa2-muted);padding:7px 10px;font-size:10px;font-weight:900;white-space:nowrap}.fa2-chip.active{background:var(--fa2-purple);border-color:var(--fa2-purple);color:#fff}.fa2-grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.fa2-field label{display:block;font-size:9px;font-weight:850;color:var(--fa2-muted);margin-bottom:4px}.fa2-field input,.fa2-field select{width:100%;min-width:0;border:1px solid var(--fa2-line);border-radius:10px;background:var(--fa2-card);color:var(--fa2-text);padding:8px 9px;font-size:11px;font-weight:750}.fa2-cycle{margin-top:8px;display:flex;gap:8px;align-items:center;justify-content:space-between}.fa2-cycle-copy{font-size:9.5px;line-height:1.35;color:var(--fa2-muted)}.fa2-cycle select{width:70px}',
      '.fa2-hero{position:relative;padding:17px 16px 15px;min-height:144px;background:linear-gradient(135deg,rgba(142,87,240,.12),rgba(241,235,255,.32) 50%,transparent)}html[data-theme="dark"] .fa2-hero,html[data-theme$="-dark"] .fa2-hero{background:radial-gradient(circle at 82% 36%,rgba(121,70,206,.28),transparent 28%),linear-gradient(135deg,rgba(65,38,112,.65),rgba(20,18,47,.2) 56%,transparent)}.fa2-eyebrow{font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:var(--fa2-muted)}.fa2-hero-title{font-size:13px;font-weight:900;color:var(--fa2-muted);margin-top:10px}.fa2-hero-value{font-size:32px;font-weight:950;letter-spacing:-.035em;color:var(--fa2-text);margin-top:2px}.fa2-hero-compare{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:7px;font-size:10px;color:var(--fa2-muted);max-width:72%}',
      '.fa2-art{position:absolute;right:12px;bottom:11px;width:92px;height:92px;pointer-events:none}.fa2-art-glow{position:absolute;inset:18px;border-radius:50%;background:radial-gradient(circle,rgba(155,109,242,.42),rgba(155,109,242,0));filter:blur(7px)}.fa2-crystal{position:absolute;left:28px;top:10px;width:42px;height:58px;clip-path:polygon(50% 0,90% 30%,76% 90%,50% 100%,23% 90%,9% 30%);background:linear-gradient(135deg,#eadcff 3%,#a779ff 45%,#6f41cd 76%,#d8c2ff);border:1px solid rgba(255,255,255,.65);box-shadow:0 0 24px rgba(145,91,238,.42)}.fa2-crystal:after{content:"";position:absolute;left:18px;top:5px;width:2px;height:42px;background:rgba(255,255,255,.7);transform:rotate(20deg)}.fa2-art-base{position:absolute;left:19px;bottom:8px;width:62px;height:16px;border-radius:50%;background:linear-gradient(180deg,#dbb566,#9a6b2a);box-shadow:0 4px 12px rgba(111,71,23,.22)}',
      '.fa2-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:0 12px 12px}.fa2-kpi{min-width:0;padding:11px 8px;border:1px solid var(--fa2-line);border-radius:14px;background:var(--fa2-card2);text-align:center}.fa2-kpi-label{font-size:9px;font-weight:850;color:var(--fa2-muted)}.fa2-kpi-value{font-size:15px;font-weight:950;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fa2-kpi.income .fa2-kpi-value{color:var(--fa2-green)}.fa2-kpi.expenses .fa2-kpi-value{color:var(--fa2-red)}.fa2-kpi.savings .fa2-kpi-value{color:var(--fa2-purple)}.fa2-kpi-sub{font-size:8px;color:var(--fa2-faint);margin-top:3px}',
      '.fa2-delta{display:inline-flex;align-items:center;border-radius:999px;padding:3px 6px;font-size:9px;font-weight:900;background:var(--fa2-card2);color:var(--fa2-muted)}.fa2-delta.good{background:rgba(69,166,107,.13);color:var(--fa2-green)}.fa2-delta.bad{background:rgba(220,102,119,.13);color:var(--fa2-red)}',
      '.fa2-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:12px}.fa2-section-title{font-size:15px;font-weight:950;color:var(--fa2-text)}.fa2-sub{font-size:9.5px;line-height:1.45;color:var(--fa2-muted);margin-top:2px}.fa2-ghost-btn{border:1px solid var(--fa2-line);background:var(--fa2-card2);color:var(--fa2-muted);border-radius:10px;padding:6px 8px;font-size:9px;font-weight:850}',
      '.fa2-category-layout{display:grid;grid-template-columns:128px 1fr;gap:10px;align-items:center}.fa2-donut{width:128px;height:128px}.fa2-donut text{fill:var(--fa2-muted);font-size:7px}.fa2-donut .total{fill:var(--fa2-text);font-size:11px;font-weight:900}.fa2-legend{display:flex;flex-direction:column;gap:7px;min-width:0}.fa2-cat-btn{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:7px;align-items:center;border:0;background:none;color:var(--fa2-text);padding:0;text-align:left}.fa2-cat-dot{width:9px;height:9px;border-radius:50%}.fa2-cat-name{font-size:9.5px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fa2-cat-meta{font-size:9px;color:var(--fa2-muted);white-space:nowrap}.fa2-drill{margin-top:12px;border-top:1px solid var(--fa2-line);padding-top:10px}.fa2-drill-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.fa2-flow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:8px 0;border-bottom:1px solid var(--fa2-line)}.fa2-flow:last-child{border-bottom:0}.fa2-flow-name{font-size:10px;font-weight:850;color:var(--fa2-text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fa2-flow-date{font-size:8.5px;color:var(--fa2-muted);margin-top:2px}.fa2-flow-amount{font-size:10px;font-weight:900;color:var(--fa2-text)}',
      '.fa2-chart{width:100%;height:auto;display:block;overflow:visible}.fa2-chart text{fill:var(--fa2-muted);font-size:7px}.fa2-chart-grid{stroke:var(--fa2-line);stroke-width:1;stroke-dasharray:3 4}.fa2-chart-point{cursor:pointer}.fa2-chart-tip{fill:var(--fa2-card);stroke:var(--fa2-line);stroke-width:1}.fa2-chart-tiptext{fill:var(--fa2-text)!important;font-size:7px!important;font-weight:850}.fa2-chart-date{fill:var(--fa2-muted)!important;font-size:6.7px!important}.fa2-chart-legend{display:flex;align-items:center;gap:13px;justify-content:center;margin-top:5px;font-size:9px;font-weight:850;color:var(--fa2-muted)}.fa2-legend-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:4px}',
      '.fa2-trends{display:flex;flex-direction:column;gap:11px}.fa2-trend-row{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:8px;align-items:center}.fa2-icon{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;font-size:13px;font-weight:950;background:var(--fa2-card2)}.fa2-trend-main{min-width:0}.fa2-trend-top{display:flex;align-items:center;justify-content:space-between;gap:6px}.fa2-trend-name{font-size:10.5px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fa2-trend-bar{height:4px;border-radius:99px;background:var(--fa2-card2);overflow:hidden;margin-top:5px}.fa2-trend-bar span{display:block;height:100%;border-radius:99px}.fa2-trend-amount{font-size:9.5px;font-weight:850;color:var(--fa2-muted);white-space:nowrap}',
      '.fa2-insights{display:flex;flex-direction:column;gap:8px}.fa2-insight{display:grid;grid-template-columns:36px minmax(0,1fr);gap:10px;align-items:center;border:1px solid var(--fa2-line);border-radius:14px;padding:10px;background:var(--fa2-card2)}.fa2-insight-icon{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;font-size:16px;font-weight:950}.fa2-insight-title{font-size:10.5px;font-weight:900;color:var(--fa2-text)}.fa2-insight-copy{font-size:9.5px;line-height:1.42;color:var(--fa2-muted);margin-top:2px}.fa2-assistant{margin-top:10px;display:grid;grid-template-columns:42px minmax(0,1fr);gap:10px;align-items:center;padding:10px;border-radius:15px;background:linear-gradient(135deg,var(--fa2-purpleSoft),var(--fa2-card2));border:1px solid var(--fa2-line)}.fa2-assistant-face{width:42px;height:42px;border-radius:50% 50% 44% 44%;display:grid;place-items:center;background:linear-gradient(145deg,#f7f3ff,#d7c4ff);box-shadow:inset 0 0 0 3px rgba(212,166,74,.45),0 5px 15px rgba(139,92,246,.16)}html[data-theme="dark"] .fa2-assistant-face,html[data-theme$="-dark"] .fa2-assistant-face{background:linear-gradient(145deg,#27274c,#111126)}.fa2-face-screen{width:28px;height:22px;border-radius:10px;background:#111627;color:#72d7ff;display:flex;align-items:center;justify-content:center;font-size:12px;letter-spacing:3px;padding-left:3px}.fa2-assistant-copy b{font-size:10.5px;color:var(--fa2-text)}.fa2-assistant-copy div{font-size:9px;line-height:1.4;color:var(--fa2-muted);margin-top:2px}',
      '.fa2-goals{display:flex;flex-direction:column;gap:9px}.fa2-goal{border:1px solid var(--fa2-line);border-radius:15px;padding:11px;background:linear-gradient(135deg,var(--fa2-card2),var(--fa2-card));cursor:pointer}.fa2-goal-top{display:grid;grid-template-columns:36px minmax(0,1fr) auto;gap:9px;align-items:center}.fa2-goal-icon{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;background:var(--fa2-purpleSoft);font-size:18px}.fa2-goal-name{font-size:10.5px;font-weight:900;color:var(--fa2-text)}.fa2-goal-money{font-size:8.8px;color:var(--fa2-muted);margin-top:2px}.fa2-goal-pct{font-size:11px;font-weight:950;color:var(--fa2-text)}.fa2-progress{height:6px;border-radius:99px;background:var(--fa2-line);overflow:hidden;margin-top:9px}.fa2-progress span{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,var(--fa2-purple),var(--fa2-purple2))}',
      '.fa2-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.fa2-mini{padding:11px;border-radius:14px;background:var(--fa2-card2);border:1px solid var(--fa2-line)}.fa2-mini-label{font-size:9px;font-weight:850;color:var(--fa2-muted)}.fa2-mini-value{font-size:16px;font-weight:950;color:var(--fa2-text);margin-top:3px}.fa2-note{font-size:8.5px;line-height:1.45;color:var(--fa2-faint);padding:0 3px 8px}',
      '@media(max-width:360px){.fa2-category-layout{grid-template-columns:112px 1fr}.fa2-donut{width:112px;height:112px}.fa2-kpi-value{font-size:13px}.fa2-period-btn{max-width:74%}}@media(min-width:620px){.fa2-wrap{display:grid;grid-template-columns:1fr 1fr}.fa2-overview,.fa2-category-card,.fa2-trend-card{grid-column:1/-1}.fa2-note{grid-column:1/-1}}'
    ].join('\n');document.head.appendChild(s);
  }

  function periodPanel(m){var p=prefs;return'<div class="fa2-period-panel '+(periodOpen?'open':'')+'"><div class="fa2-chips"><button class="fa2-chip '+(p.mode==='calendar'?'active':'')+'" data-fa-mode="calendar">Kalendermaand</button><button class="fa2-chip '+(p.mode==='salary'?'active':'')+'" data-fa-mode="salary">Salariscyclus</button><button class="fa2-chip '+(p.mode==='custom'?'active':'')+'" data-fa-mode="custom">Eigen bereik</button></div><div class="fa2-grid2"><div class="fa2-field"><label>Van</label><input type="date" data-fa-start value="'+esc(p.start)+'"></div><div class="fa2-field"><label>Tot en met</label><input type="date" data-fa-end value="'+esc(p.end)+'"></div></div><div class="fa2-cycle"><div class="fa2-cycle-copy"><b>Salariscyclus</b><br>Startdag van je financiële maand.</div><div class="fa2-field"><select data-fa-cycle>'+Array.from({length:31},function(_,i){var d=i+1;return'<option value="'+d+'" '+(d===p.cycleStartDay?'selected':'')+'>'+d+'</option>';}).join('')+'</select></div></div><div class="fa2-grid2"><div class="fa2-field" style="grid-column:1/-1"><label>Vergelijken met</label><select data-fa-compare><option value="previous" '+(p.compareMode==='previous'?'selected':'')+'>Vorige even lange periode</option><option value="custom" '+(p.compareMode==='custom'?'selected':'')+'>Andere periode</option></select></div></div>'+(p.compareMode==='custom'?'<div class="fa2-grid2"><div class="fa2-field"><label>Vergelijk vanaf</label><input type="date" data-fa-cstart value="'+esc(p.compareStart||m.comparison.range.start)+'"></div><div class="fa2-field"><label>Vergelijk t/m</label><input type="date" data-fa-cend value="'+esc(p.compareEnd||m.comparison.range.end)+'"></div></div>':'')+'</div>';}
  function overview(m){var x=m.primary.metrics,positive=x.result>=0;return'<section class="fa2-card fa2-overview"><div class="fa2-periodbar"><div><div class="fa2-period-label">Periode</div></div><button class="fa2-period-btn" type="button" data-fa-period-toggle aria-expanded="'+(periodOpen?'true':'false')+'"><span>'+esc(rangeText(m.primary.range))+'</span><b>⌄</b></button></div>'+periodPanel(m)+'<div class="fa2-hero"><div class="fa2-eyebrow">Periodeoverzicht</div><div class="fa2-hero-title">'+(positive?'Resultaat':'Tekort')+'</div><div class="fa2-hero-value">'+(positive?'':'− ')+euro(x.result)+'</div><div class="fa2-hero-compare">'+deltaBadge(m.deltas.result,false)+'<span>'+esc(deltaSentence(m.deltas.result,'resultaat'))+'</span></div><div class="fa2-art" aria-hidden="true"><div class="fa2-art-glow"></div><div class="fa2-crystal"></div><div class="fa2-art-base"></div></div></div><div class="fa2-kpis"><div class="fa2-kpi income"><div class="fa2-kpi-label">Inkomsten</div><div class="fa2-kpi-value">'+euro(x.income)+'</div><div class="fa2-kpi-sub">'+percent(m.deltas.income.percent)+' vs vorige</div></div><div class="fa2-kpi expenses"><div class="fa2-kpi-label">Uitgaven</div><div class="fa2-kpi-value">'+euro(x.expenses)+'</div><div class="fa2-kpi-sub">'+percent(m.deltas.expenses.percent)+' vs vorige</div></div><div class="fa2-kpi savings"><div class="fa2-kpi-label">Sparen</div><div class="fa2-kpi-value">'+signedEuro(x.netSavings)+'</div><div class="fa2-kpi-sub">Spaarquote '+percent(x.savingsRate)+'</div></div></div></section>';}
  function donutSvg(rows,total){var r=44,c=2*Math.PI*r,offset=0,segments='';rows.slice(0,8).forEach(function(row,i){var share=total?row.amount/total:0,len=Math.max(0,Math.min(c,c*share));segments+='<circle cx="64" cy="64" r="'+r+'" fill="none" stroke="'+categoryColor(i)+'" stroke-width="20" stroke-dasharray="'+len.toFixed(2)+' '+(c-len).toFixed(2)+'" stroke-dashoffset="'+(-offset).toFixed(2)+'" transform="rotate(-90 64 64)"/>';offset+=len;});return'<svg class="fa2-donut" viewBox="0 0 128 128" role="img" aria-label="Uitgaven per categorie"><circle cx="64" cy="64" r="44" fill="none" stroke="var(--fa2-line)" stroke-width="20"/>'+segments+'<text x="64" y="59" text-anchor="middle">Totaal</text><text class="total" x="64" y="74" text-anchor="middle">'+esc(euro(total))+'</text></svg>';}
  function categoryDrill(m){if(!selectedCategory)return'';var flows=(m.primary.flows||[]).filter(function(f){return f.type==='expense'&&String(f.category||'Overig')===selectedCategory;});var total=flows.reduce(function(sum,f){return sum+Number(f.amount||0);},0);return'<div class="fa2-drill"><div class="fa2-drill-head"><div><div class="fa2-section-title">'+esc(selectedCategory)+'</div><div class="fa2-sub">'+flows.length+' post'+(flows.length===1?'':'en')+' · '+euro(total)+'</div></div><button class="fa2-ghost-btn" type="button" data-fa-category-close>Sluiten</button></div>'+flows.slice().reverse().slice(0,8).map(function(f){return'<div class="fa2-flow"><div><div class="fa2-flow-name">'+esc(f.name||f.category||'Uitgave')+'</div><div class="fa2-flow-date">'+esc(pretty(f.date,true))+(f.fixed?' · vaste last':'')+'</div></div><div class="fa2-flow-amount">− '+euro(f.amount)+'</div></div>';}).join('')+'</div>';}
  function categories(m){var rows=m.primary.categories||[],total=m.primary.metrics.expenses||0;if(!rows.length)return'<section class="fa2-card fa2-pad fa2-category-card"><div class="fa2-section-title">Uitgaven per categorie</div><div class="fa2-sub">Nog geen uitgaven in deze periode.</div></section>';return'<section class="fa2-card fa2-pad fa2-category-card"><div class="fa2-head"><div><div class="fa2-section-title">Uitgaven per categorie</div><div class="fa2-sub">Waar ging het geld heen? Tik op een categorie voor details.</div></div></div><div class="fa2-category-layout">'+donutSvg(rows,total)+'<div class="fa2-legend">'+rows.slice(0,7).map(function(r,i){return'<button type="button" class="fa2-cat-btn" data-fa-category="'+esc(r.category)+'"><span class="fa2-cat-dot" style="background:'+categoryColor(i)+'"></span><span class="fa2-cat-name">'+esc(r.category)+'</span><span class="fa2-cat-meta">'+percent(r.share)+' · '+euro(r.amount)+'</span></button>';}).join('')+'</div></div>'+categoryDrill(m)+'</section>';}
  function cumulativeTrend(m){var rows=m.primary.trend.rows||[],out=[],income=0,expenses=0;rows.forEach(function(r){income+=Number(r.income)||0;expenses+=Number(r.expenses)||0;out.push({date:r.date,income:income,expenses:expenses});});return out;}
  function chartValue(n){n=Math.abs(Number(n)||0);if(n>=1000)return'€'+(Math.round(n/100)/10).toLocaleString('nl-NL')+'k';return'€'+Math.round(n);}
  function lineChart(m){var rows=cumulativeTrend(m);if(!rows.length)return'<div class="fa2-sub">Nog geen datapunten in deze periode.</div>';var W=340,H=170,L=30,R=10,T=18,B=28,iw=W-L-R,ih=H-T-B,max=1;rows.forEach(function(r){max=Math.max(max,r.income,r.expenses);});function x(i){return L+(rows.length===1?iw/2:i/(rows.length-1)*iw);}function y(v){return T+ih-(Math.max(0,v)/max*ih);}function pts(k){return rows.map(function(r,i){return x(i).toFixed(1)+','+y(r[k]).toFixed(1);}).join(' ');}var grids=[0,.5,1].map(function(q){var yy=T+ih-q*ih;return'<line class="fa2-chart-grid" x1="'+L+'" y1="'+yy+'" x2="'+(W-R)+'" y2="'+yy+'"/><text x="2" y="'+(yy+3)+'">'+esc(chartValue(max*q))+'</text>';}).join('');var selected=selectedTrendIndex==null?rows.length-1:Math.max(0,Math.min(rows.length-1,selectedTrendIndex));var points=rows.map(function(r,i){return'<g class="fa2-chart-point" data-fa-point="'+i+'"><circle cx="'+x(i)+'" cy="'+y(r.income)+'" r="'+(i===selected?4.2:3)+'" fill="var(--fa2-green)" stroke="var(--fa2-card)" stroke-width="1.5"/><circle cx="'+x(i)+'" cy="'+y(r.expenses)+'" r="'+(i===selected?4.2:3)+'" fill="var(--fa2-red)" stroke="var(--fa2-card)" stroke-width="1.5"/></g>';}).join('');var sr=rows[selected],tipW=91,tipH=45,tipX=Math.min(W-tipW-5,Math.max(L+2,x(selected)-tipW/2)),tipY=Math.max(3,Math.min(y(Math.max(sr.income,sr.expenses))-tipH-8,H-tipH-5));var tooltip='<g pointer-events="none"><rect class="fa2-chart-tip" x="'+tipX+'" y="'+tipY+'" width="'+tipW+'" height="'+tipH+'" rx="8"/><text class="fa2-chart-tiptext" x="'+(tipX+7)+'" y="'+(tipY+12)+'">'+esc(pretty(sr.date,true))+'</text><circle cx="'+(tipX+9)+'" cy="'+(tipY+24)+'" r="3" fill="var(--fa2-green)"/><text class="fa2-chart-tiptext" x="'+(tipX+16)+'" y="'+(tipY+27)+'">In '+esc(euro(sr.income))+'</text><circle cx="'+(tipX+9)+'" cy="'+(tipY+36)+'" r="3" fill="var(--fa2-red)"/><text class="fa2-chart-tiptext" x="'+(tipX+16)+'" y="'+(tipY+39)+'">Uit '+esc(euro(sr.expenses))+'</text></g>';return'<svg class="fa2-chart" viewBox="0 0 '+W+' '+H+'" aria-label="Inkomsten versus uitgaven">'+grids+'<polyline points="'+pts('income')+'" fill="none" stroke="var(--fa2-green)" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/><polyline points="'+pts('expenses')+'" fill="none" stroke="var(--fa2-red)" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>'+points+tooltip+'<text class="fa2-chart-date" x="'+L+'" y="'+(H-5)+'">'+esc(pretty(rows[0].date,false))+'</text><text class="fa2-chart-date" x="'+(W-R)+'" y="'+(H-5)+'" text-anchor="end">'+esc(pretty(rows[rows.length-1].date,false))+'</text></svg><div class="fa2-chart-legend"><span><i class="fa2-legend-dot" style="background:var(--fa2-green)"></i>Inkomsten</span><span><i class="fa2-legend-dot" style="background:var(--fa2-red)"></i>Uitgaven</span></div>';}
  function trend(m){return'<section class="fa2-card fa2-pad fa2-trend-card"><div class="fa2-head"><div><div class="fa2-section-title">Trend overzicht</div><div class="fa2-sub">Geldstroom over de geselecteerde periode. Tik op een punt voor bedragen.</div></div><span class="fa2-ghost-btn">'+m.primary.range.days+' dagen</span></div>'+lineChart(m)+'</section>';}
  function categoryTrends(m){var map={};(m.categories||[]).forEach(function(r){map[r.category]=r;});var rows=(m.primary.categories||[]).slice(0,6),max=rows.length?rows[0].amount:1;if(!rows.length)return'';return'<section class="fa2-card fa2-pad"><div class="fa2-head"><div><div class="fa2-section-title">Categorie trends</div><div class="fa2-sub">Vergelijking met de vorige geselecteerde periode.</div></div></div><div class="fa2-trends">'+rows.map(function(r,i){var c=map[r.category]||{delta:0,deltaPercent:0},delta=Number(c.delta)||0,color=categoryColor(i);return'<div class="fa2-trend-row"><div class="fa2-icon" style="color:'+color+'">'+esc(categoryGlyph(r.category))+'</div><div class="fa2-trend-main"><div class="fa2-trend-top"><span class="fa2-trend-name">'+esc(r.category)+'</span>'+deltaBadge({absolute:delta,percent:c.deltaPercent},true)+'</div><div class="fa2-trend-bar"><span style="width:'+Math.max(4,Math.min(100,r.amount/max*100))+'%;background:'+color+'"></span></div></div><span class="fa2-trend-amount">'+euro(r.amount)+'</span></div>';}).join('')+'</div></section>';}
  function insightCard(icon,color,title,copy){return'<div class="fa2-insight"><div class="fa2-insight-icon" style="color:'+color+'">'+esc(icon)+'</div><div><div class="fa2-insight-title">'+esc(title)+'</div><div class="fa2-insight-copy">'+esc(copy)+'</div></div></div>';}
  function insights(m){var rows=(m.insights||[]).slice(0,3),html='';rows.forEach(function(i){if(i.type==='increase')html+=insightCard('↑','#dc6677',i.title,i.category+' kostte '+euro(i.amount)+' meer dan vorige periode.');else if(i.type==='decrease')html+=insightCard('↓','#45a66b',i.title,'Je gaf '+euro(i.amount)+' minder uit aan '+i.category+'.');else if(i.type==='savings')html+=insightCard('◆','#8b5cf6','Netto gespaard',euro(i.amount)+' in deze periode · spaarquote '+percent(i.rate)+'.');else html+=insightCard('⌁','#d4a64a','Boodschappenbonnen',i.count+' bon'+(i.count===1?'':'nen')+' · '+euro(i.amount)+' totaal.');});if(!html){var x=m.primary.metrics;if(x.result>=0)html+=insightCard('✓','#45a66b','Positief resultaat','Je houdt in deze periode '+euro(x.result)+' over na uitgaven en sparen.');else html+=insightCard('!','#dc6677','Negatief resultaat','De uitgaven en spaarbewegingen liggen '+euro(Math.abs(x.result))+' boven de inkomsten.');}return'<section class="fa2-card fa2-pad"><div class="fa2-head"><div><div class="fa2-section-title">Inzichten voor jou</div><div class="fa2-sub">Automatisch berekend uit je eigen Finance-data.</div></div></div><div class="fa2-insights">'+html+'</div><div class="fa2-assistant"><div class="fa2-assistant-face"><div class="fa2-face-screen">••</div></div><div class="fa2-assistant-copy"><b>FamilyApp Assistent</b><div>Ik gebruik alleen de analyse hierboven om opvallende veranderingen zichtbaar te maken.</div></div></div></section>';}
  function goals(){var state=S().get(),rows=Array.isArray(state.savingsGoals)?state.savingsGoals.slice():[];if(!rows.length)return'<section class="fa2-card fa2-pad"><div class="fa2-head"><div><div class="fa2-section-title">Spaardoelen</div><div class="fa2-sub">Nog geen spaardoelen ingesteld.</div></div><button class="fa2-ghost-btn" type="button" data-fa-new-goal>+ Nieuw doel</button></div></section>';rows.sort(function(a,b){var ap=Number(a.target)?Number(a.saved||0)/Number(a.target):0,bp=Number(b.target)?Number(b.saved||0)/Number(b.target):0;return bp-ap;});return'<section class="fa2-card fa2-pad"><div class="fa2-head"><div><div class="fa2-section-title">Spaardoelen</div><div class="fa2-sub">Voortgang op de doelen van jullie gezin.</div></div><button class="fa2-ghost-btn" type="button" data-fa-new-goal>+ Nieuw doel</button></div><div class="fa2-goals">'+rows.slice(0,3).map(function(g){var target=Math.max(0,Number(g.target)||0),saved=Math.max(0,Number(g.saved)||0),pct=target?Math.min(100,saved/target*100):0;return'<button class="fa2-goal" type="button" data-fa-goal="'+esc(g.id)+'"><div class="fa2-goal-top"><div class="fa2-goal-icon">'+esc(g.icon||'◆')+'</div><div><div class="fa2-goal-name">'+esc(g.name||'Spaardoel')+'</div><div class="fa2-goal-money">'+euro(saved)+' / '+euro(target)+'</div></div><div class="fa2-goal-pct">'+Math.round(pct)+'%</div></div><div class="fa2-progress"><span style="width:'+pct+'%"></span></div></button>';}).join('')+'</div></section>';}
  function details(m){var x=m.primary.metrics,s=m.primary.savings,r=m.primary.receipts,total=x.expenses||1;return'<section class="fa2-card fa2-pad"><div class="fa2-head"><div><div class="fa2-section-title">Financiële details</div><div class="fa2-sub">Vast versus variabel, sparen en Boodschappenbonnen.</div></div></div><div class="fa2-detail-grid"><div class="fa2-mini"><div class="fa2-mini-label">Vaste lasten</div><div class="fa2-mini-value">'+euro(x.fixedExpenses)+'</div><div class="fa2-sub">'+percent(x.fixedExpenses/total*100)+' van uitgaven</div></div><div class="fa2-mini"><div class="fa2-mini-label">Variabel</div><div class="fa2-mini-value">'+euro(x.variableExpenses)+'</div><div class="fa2-sub">'+percent(x.variableExpenses/total*100)+' van uitgaven</div></div><div class="fa2-mini"><div class="fa2-mini-label">Netto sparen</div><div class="fa2-mini-value">'+signedEuro(s.net)+'</div><div class="fa2-sub">Gestort '+euro(s.deposits)+' · opname '+euro(s.withdrawals)+'</div></div><div class="fa2-mini"><div class="fa2-mini-label">Boodschappenbonnen</div><div class="fa2-mini-value">'+r.count+'</div><div class="fa2-sub">'+r.itemCount+' items · '+euro(r.total)+'</div></div></div></section>';}
  function bind(el){var toggle=el.querySelector('[data-fa-period-toggle]');if(toggle)toggle.onclick=function(){periodOpen=!periodOpen;requestRender(true);};el.querySelectorAll('[data-fa-mode]').forEach(function(btn){btn.onclick=function(){var mode=btn.getAttribute('data-fa-mode');prefs.mode=mode;if(mode==='calendar'){var r=E().calendarMonthRange(today());prefs.start=r.start;prefs.end=r.end;}else if(mode==='salary'){var sr=E().salaryCycleRange(today(),prefs.cycleStartDay);prefs.start=sr.start;prefs.end=sr.end;}periodOpen=true;selectedTrendIndex=null;savePrefs();requestRender(true);};});var st=el.querySelector('[data-fa-start]'),en=el.querySelector('[data-fa-end]');if(st)st.onchange=function(){prefs.start=st.value;prefs.mode='custom';savePrefs();requestRender(true);};if(en)en.onchange=function(){prefs.end=en.value;prefs.mode='custom';savePrefs();requestRender(true);};var cyc=el.querySelector('[data-fa-cycle]');if(cyc)cyc.onchange=function(){prefs.cycleStartDay=Number(cyc.value)||1;if(prefs.mode==='salary'){var r=E().salaryCycleRange(today(),prefs.cycleStartDay);prefs.start=r.start;prefs.end=r.end;}savePrefs();requestRender(true);};var cmp=el.querySelector('[data-fa-compare]');if(cmp)cmp.onchange=function(){prefs.compareMode=cmp.value==='custom'?'custom':'previous';if(prefs.compareMode==='custom'&&(!prefs.compareStart||!prefs.compareEnd)){var r=E().previousEqualRange({start:prefs.start,end:prefs.end});prefs.compareStart=r.start;prefs.compareEnd=r.end;}savePrefs();requestRender(true);};var cs=el.querySelector('[data-fa-cstart]'),ce=el.querySelector('[data-fa-cend]');if(cs)cs.onchange=function(){prefs.compareStart=cs.value;savePrefs();requestRender(true);};if(ce)ce.onchange=function(){prefs.compareEnd=ce.value;savePrefs();requestRender(true);};el.querySelectorAll('[data-fa-category]').forEach(function(btn){btn.onclick=function(){selectedCategory=btn.getAttribute('data-fa-category');requestRender(true);};});var close=el.querySelector('[data-fa-category-close]');if(close)close.onclick=function(){selectedCategory=null;requestRender(true);};el.querySelectorAll('[data-fa-point]').forEach(function(point){point.onclick=function(){selectedTrendIndex=Number(point.getAttribute('data-fa-point'));requestRender(true);};});var ng=el.querySelector('[data-fa-new-goal]');if(ng)ng.onclick=function(){if(typeof window.openSavingsGoalSheet==='function')window.openSavingsGoalSheet(null);else if(window.FinanceNativeTabs)FinanceNativeTabs.activate('sparen');};el.querySelectorAll('[data-fa-goal]').forEach(function(btn){btn.onclick=function(){window.savingsViewGoal=btn.getAttribute('data-fa-goal');if(window.FinanceNativeTabs&&FinanceNativeTabs.activate)FinanceNativeTabs.activate('sparen');if(typeof window.renderSparen==='function')setTimeout(window.renderSparen,0);};});}
  function render(){var el=document.getElementById('fin-analyse');if(!el||!E()||!S())return false;if(rendering){pending=true;return false;}rendering=true;pending=false;var started=Date.now();try{ensureStyles();if(!prefs)prefs=loadPrefs();var m;try{m=compute();}catch(e){prefs=defaults();savePrefs();m=compute();}lastModel=m;el.classList.add('finance-analysis-owned');var screen=document.getElementById('screen-finance');if(screen)screen.classList.add('finance-analysis-active');el.innerHTML='<div class="fa2-wrap">'+overview(m)+categories(m)+trend(m)+categoryTrends(m)+insights(m)+goals()+details(m)+'<div class="fa2-note">Analyse gebruikt dezelfde genormaliseerde Finance-data als toekomstige rapportage. Salaris en vaste lasten volgen de ingestelde cyclus; transacties, bonnen en spaarbewegingen volgen hun eigen datum.</div></div>';bind(el);var elapsed=Date.now()-started;if(elapsed>120)console.warn('[FinanceAnalysisUI] slow render',{ms:elapsed,range:m.primary.range,flows:m.primary.flows&&m.primary.flows.length});return true;}catch(error){console.error('[FinanceAnalysisUI] render failed',error);el.innerHTML='<div class="fa2-card fa2-pad" style="color:var(--fa2-red)"><b>Analyse kon niet laden.</b><div class="fa2-sub">'+esc(error&&error.message||'Onbekende fout')+'</div></div>';return false;}finally{rendering=false;if(pending&&active()){pending=false;setTimeout(render,0);}}}
  function requestRender(force){if(!force&&!active())return false;if(requestTimer)clearTimeout(requestTimer);requestTimer=setTimeout(function(){requestTimer=null;if(force||active())render();},force?0:50);return true;}
  function resetScope(){prefs=null;lastModel=null;selectedCategory=null;selectedTrendIndex=null;periodOpen=false;requestRender(false);}
  function install(){if(installed)return;installed=true;ensureStyles();window.addEventListener('familyapp:finance:changed',function(){requestRender(false);});window.addEventListener('familyapp:household-members-updated',resetScope);document.addEventListener('click',function(event){var btn=event.target&&event.target.closest?event.target.closest('#finance-native-tabs [data-fin-tab]'):null;if(!btn)return;var screen=document.getElementById('screen-finance');if(screen&&btn.getAttribute('data-fin-tab')!=='analyse')screen.classList.remove('finance-analysis-active');});requestRender(false);}
  window.FinanceAnalysisUI={version:VERSION,render:render,requestRender:requestRender,getModel:function(){return lastModel;},install:install};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
