'use strict';
// ============================================================
// FINANCE STORE v4.0.0
// Canonical household-scoped finance source of truth.
// ============================================================
(function(){
  var VERSION='4.0.0',COLLECTION='finance';
  if(window.FinanceStore&&window.FinanceStore.version===VERSION)return;
  var state=null,sub=null,boundToken=null,readyPromise=null,booted=false;
  function store(){return window.FamilyDataStore||null;}function hc(){return window.HouseholdContext||null;}function now(){return Date.now();}
  function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}function arr(v){return Array.isArray(v)?clone(v):[];}
  function capture(){var c=hc();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function same(t){return!!(t&&hc()&&hc().isCurrent(t));}function assertToken(t){if(!same(t)){var e=new Error('FINANCE_CONTEXT_CHANGED');e.code='FINANCE_CONTEXT_CHANGED';throw e;}return t;}
  function todayStr(){var d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return d.getFullYear()+'-'+m+'-'+day;}
  function makeId(prefix){var s=store();return s&&s.makeId?s.makeId(prefix):(prefix+'_'+now().toString(36)+'_'+Math.random().toString(36).slice(2,8));}
  function emptyState(token){token=token||boundToken||{uid:null,householdId:null};return{schemaVersion:3,initialized:true,householdId:token.householdId||null,income:{primary:{label:'Salaris',amount:0},partner:{label:'Salaris',amount:0}},samenBetaler:'Beiden',vasteLasten:[],transactions:[],extraIncome:[],savingsGoals:[],meta:{resetAt:null,updatedAt:now(),updatedBy:token.uid||null}};}
  function fromLegacyGlobals(token){return{schemaVersion:3,initialized:true,householdId:token.householdId,income:{primary:clone(window.inkomenShane||{label:'Salaris',amount:0}),partner:clone(window.inkomenEsra||{label:'Salaris',amount:0})},samenBetaler:window.samenBetaler||'Beiden',vasteLasten:arr(window.vasteLasten),transactions:arr(window.transData),extraIncome:arr(window.extraIncome),savingsGoals:arr(window.savingsGoals),meta:{migratedAt:now(),updatedAt:now(),updatedBy:token.uid}};}
  function normalize(v,token){token=token||boundToken||{uid:null,householdId:null};v=v&&typeof v==='object'?clone(v):emptyState(token);v.schemaVersion=3;v.initialized=true;v.householdId=token.householdId||v.householdId||null;v.income=v.income||{};v.income.primary=v.income.primary||{label:'Salaris',amount:0};v.income.partner=v.income.partner||{label:'Salaris',amount:0};v.samenBetaler=v.samenBetaler||'Beiden';v.vasteLasten=arr(v.vasteLasten);v.transactions=arr(v.transactions);v.extraIncome=arr(v.extraIncome);v.savingsGoals=arr(v.savingsGoals).map(function(g){g=g||{};g.log=arr(g.log);return g;});v.meta=v.meta||{};return v;}
  function sortByDateThenStamp(list){return(list||[]).slice().sort(function(a,b){var ad=a&&a.date||'',bd=b&&b.date||'';if(ad!==bd)return ad<bd?1:-1;return Number(b&&b.updatedAt||b&&b.createdAt||0)-Number(a&&a.updatedAt||a&&a.createdAt||0);});}
  function render(){try{if(typeof window.renderFinance==='function')window.renderFinance();}catch(e){}}
  function apply(v,token){if(token&&!same(token))return;state=normalize(v,token||boundToken);window.inkomenShane=clone(state.income.primary);window.inkomenEsra=clone(state.income.partner);window.samenBetaler=state.samenBetaler;window.vasteLasten=arr(state.vasteLasten);window.transData=sortByDateThenStamp(state.transactions);window.extraIncome=sortByDateThenStamp(state.extraIncome);window.savingsGoals=arr(state.savingsGoals).map(function(g){g=clone(g);g.log=sortByDateThenStamp(g.log);return g;});render();try{window.dispatchEvent(new CustomEvent('familyapp:finance:changed',{detail:{state:clone(state),householdId:boundToken&&boundToken.householdId||null}}));}catch(e){}}
  function stop(){if(sub)try{sub();}catch(e){}sub=null;boundToken=null;readyPromise=null;state=null;window.transData=[];window.extraIncome=[];window.vasteLasten=[];window.savingsGoals=[];}
  function subscribe(token){if(sub)try{sub();}catch(e){}sub=store().subscribeShared(COLLECTION,function(v){if(!same(token))return;if(v&&v.initialized)apply(v,token);},emptyState(token));}
  function initialize(token){var s=store();return s.readShared(COLLECTION,null).then(function(existing){assertToken(token);if(existing&&existing.initialized===true)return normalize(existing,token);if(existing&&typeof existing==='object'&&Object.keys(existing).length){var adopted=normalize(existing,token);adopted.meta.adoptedAt=now();adopted.meta.updatedBy=token.uid;return s.writeShared(COLLECTION,adopted).then(function(){assertToken(token);return adopted;});}var seed=fromLegacyGlobals(token);return s.writeShared(COLLECTION,seed).then(function(){assertToken(token);return seed;});}).then(function(initial){assertToken(token);apply(initial,token);subscribe(token);return true;});}
  function ready(){if(boundToken&&same(boundToken)&&sub)return Promise.resolve(true);if(readyPromise)return readyPromise;var token;try{token=capture();}catch(e){return Promise.resolve(false);}boundToken=token;readyPromise=initialize(token).catch(function(e){if(e&&e.code!=='FINANCE_CONTEXT_CHANGED')console.warn('[FinanceStore]',e);return false;}).then(function(v){readyPromise=null;return v;});return readyPromise;}
  function rebind(){stop();return ready();}function boot(){if(booted)return;booted=true;ready();}
  function mutateList(field,updater){var token=capture();assertToken(token);return ready().then(function(){assertToken(token);var fallback=(state&&state[field])||[];return store().transactSharedPath(COLLECTION,[field],function(list){return updater(Array.isArray(list)?list:[]);},fallback);}).then(function(result){assertToken(token);return result&&Array.isArray(result.value)?result.value:[];});}
  function mutateField(path,updater){var token=capture();assertToken(token);return ready().then(function(){assertToken(token);var cur=state||emptyState(token),fallback=cur;for(var i=0;i<path.length;i++)fallback=fallback==null?undefined:fallback[path[i]];return store().transactSharedPath(COLLECTION,path,updater,fallback);}).then(function(result){assertToken(token);return result?result.value:undefined;});}
  function stampNew(rec,token,ts){rec.id=rec.id||makeId('fin');rec.householdId=token.householdId;rec.createdAt=rec.createdAt||ts;rec.createdBy=rec.createdBy||token.uid;rec.updatedAt=ts;rec.updatedBy=token.uid;if(!rec.date)rec.date=todayStr();return rec;}
  function monthKey(year,month){if(typeof year==='string'&&/^\d{4}-\d{2}$/.test(year))return year;var d=new Date(),y=Number.isFinite(Number(year))?Number(year):d.getFullYear(),m=Number.isFinite(Number(month))?Number(month):d.getMonth();return y+'-'+String(m+1).padStart(2,'0');}
  function monthlySummary(year,month){var s=normalize(state||emptyState(boundToken),boundToken),key=monthKey(year,month);var tx=s.transactions.filter(function(t){return String(t&&t.date||'').slice(0,7)===key;});var extra=s.extraIncome.filter(function(t){return String(t&&t.date||'').slice(0,7)===key;});var transactionIncome=tx.filter(function(t){return Number(t&&t.amount)>0;}).reduce(function(sum,t){return sum+Number(t.amount||0);},0);var transactionExpenses=tx.filter(function(t){return Number(t&&t.amount)<0;}).reduce(function(sum,t){return sum+Math.abs(Number(t.amount||0));},0);var extraIncomeTotal=extra.filter(function(t){return Number(t&&t.amount)>0;}).reduce(function(sum,t){return sum+Number(t.amount||0);},0);var extraExpenses=extra.filter(function(t){return Number(t&&t.amount)<0;}).reduce(function(sum,t){return sum+Math.abs(Number(t.amount||0));},0);var fixedExpenses=s.vasteLasten.reduce(function(sum,t){return sum+Math.abs(Number(t&&t.amount)||0);},0);var savingsDeposits=s.savingsGoals.reduce(function(sum,g){return sum+(g.log||[]).filter(function(l){return String(l&&l.date||'').slice(0,7)===key&&l.type==='deposit';}).reduce(function(x,l){return x+Math.abs(Number(l.amount)||0);},0);},0);var salaryIncome=Number(s.income.primary&&s.income.primary.amount||0)+Number(s.income.partner&&s.income.partner.amount||0);var totalIncome=salaryIncome+extraIncomeTotal+transactionIncome,totalExpenses=fixedExpenses+extraExpenses+transactionExpenses+savingsDeposits;return{month:key,salaryIncome:salaryIncome,extraIncome:extraIncomeTotal,transactionIncome:transactionIncome,fixedExpenses:fixedExpenses,extraExpenses:extraExpenses,transactionExpenses:transactionExpenses,savingsDeposits:savingsDeposits,totalIncome:totalIncome,totalExpenses:totalExpenses,disposable:totalIncome-totalExpenses,transactionCount:tx.length,transactions:clone(tx)};}
  function addTransaction(data){var t=capture(),ts=now(),rec=stampNew(Object.assign({},data),t,ts);rec.sourceType=rec.sourceType||'manual';return mutateList('transactions',function(list){list=list.slice();list.unshift(rec);return list;}).then(function(){assertToken(t);return rec;});}
  function updateTransaction(id,patch){var t=capture(),ts=now();return mutateList('transactions',function(list){return list.map(function(x){return x&&x.id===id?Object.assign({},x,patch,{householdId:t.householdId,updatedAt:ts,updatedBy:t.uid}):x;});});}
  function deleteTransaction(id){return mutateList('transactions',function(list){return list.filter(function(x){return!x||x.id!==id;});});}
  function transactionKey(sourceType,sourceId){return String(sourceType||'manual')+':'+String(sourceId||'');}
  function upsertSourceTransaction(o){o=o||{};if(!o.sourceType||!o.sourceId)return Promise.reject(new Error('source required'));var t=capture(),key=transactionKey(o.sourceType,o.sourceId),incoming=clone(o.transaction||{}),ts=now();return mutateList('transactions',function(list){list=list.slice();var idx=list.findIndex(function(x){return x&&x.sourceKey===key;}),old=idx>=0?list[idx]:null;var record=Object.assign({},old||{},incoming,{id:old&&old.id||makeId('fin'),householdId:t.householdId,sourceType:o.sourceType,sourceId:String(o.sourceId),sourceKey:key,createdAt:old&&old.createdAt||ts,createdBy:old&&old.createdBy||t.uid,updatedAt:ts,updatedBy:t.uid});if(!record.date)record.date=todayStr();if(idx>=0)list[idx]=record;else list.unshift(record);return list;}).then(function(list){assertToken(t);var record=list.find(function(x){return x&&x.sourceKey===key;})||null;return record?clone(record):null;});}
  function addExtraIncome(data){var t=capture(),ts=now(),rec=stampNew(Object.assign({},data),t,ts);return mutateList('extraIncome',function(list){list=list.slice();list.unshift(rec);return list;}).then(function(){return rec;});}
  function deleteExtraIncome(id){var removed=null;return mutateList('extraIncome',function(list){removed=list.find(function(x){return x&&x.id===id;})||null;return list.filter(function(x){return!x||x.id!==id;});}).then(function(){return removed;});}
  function addVasteLast(data){var t=capture(),ts=now(),rec=Object.assign({paid:{}},data,{householdId:t.householdId});rec.id=rec.id||makeId('vl');rec.createdAt=ts;rec.createdBy=t.uid;rec.updatedAt=ts;rec.updatedBy=t.uid;return mutateList('vasteLasten',function(list){list=list.slice();list.push(rec);return list;}).then(function(){return rec;});}
  function deleteVasteLast(id){return mutateList('vasteLasten',function(list){return list.filter(function(x){return!x||x.id!==id;});});}
  function toggleVasteLastPaid(id,ym){var t=capture(),ts=now();return mutateList('vasteLasten',function(list){return list.map(function(x){if(!x||x.id!==id)return x;var n=Object.assign({},x,{paid:Object.assign({},x.paid||{}),householdId:t.householdId,updatedAt:ts,updatedBy:t.uid});if(n.paid[ym])delete n.paid[ym];else n.paid[ym]=true;return n;});});}
  function setIncome(person,patch){var t=capture(),ts=now();return mutateField(['income',person],function(cur){return Object.assign({},cur||{label:'Salaris',amount:0},patch,{updatedAt:ts,updatedBy:t.uid});});}
  function setSamenBetaler(v){return mutateField(['samenBetaler'],function(){return v;});}
  function addSavingsGoal(data){var t=capture(),ts=now(),rec=Object.assign({saved:0,log:[]},data,{householdId:t.householdId});rec.id=rec.id||makeId('goal');rec.createdAt=ts;rec.createdBy=t.uid;rec.updatedAt=ts;rec.updatedBy=t.uid;return mutateList('savingsGoals',function(list){list=list.slice();list.push(rec);return list;}).then(function(){return rec;});}
  function updateSavingsGoal(id,patch){var t=capture(),ts=now();return mutateList('savingsGoals',function(list){return list.map(function(g){return g&&g.id===id?Object.assign({},g,patch,{householdId:t.householdId,updatedAt:ts,updatedBy:t.uid}):g;});});}
  function deleteSavingsGoal(id){return mutateList('savingsGoals',function(list){return list.filter(function(g){return!g||g.id!==id;});});}
  function addSavingsTransaction(goalId,entry){var t=capture(),ts=now(),logEntry=Object.assign({id:makeId('savingslog'),householdId:t.householdId,createdAt:ts,createdBy:t.uid,updatedAt:ts,updatedBy:t.uid},entry);if(!logEntry.date)logEntry.date=todayStr();return mutateList('savingsGoals',function(list){return list.map(function(g){if(!g||g.id!==goalId)return g;var log=(g.log||[]).slice();log.push(logEntry);var delta=logEntry.type==='deposit'?Number(logEntry.amount||0):-Number(logEntry.amount||0);return Object.assign({},g,{log:log,saved:Math.max(0,Number(g.saved||0)+delta),updatedAt:ts,updatedBy:t.uid});});}).then(function(){return logEntry;});}
  function deleteSavingsLogEntry(goalId,logId){var t=capture(),ts=now();return mutateList('savingsGoals',function(list){return list.map(function(g){if(!g||g.id!==goalId)return g;var entry=(g.log||[]).find(function(l){return l.id===logId;});if(!entry)return g;var log=(g.log||[]).filter(function(l){return l.id!==logId;});var delta=entry.type==='deposit'?-Number(entry.amount||0):Number(entry.amount||0);return Object.assign({},g,{log:log,saved:Math.max(0,Number(g.saved||0)+delta),updatedAt:ts,updatedBy:t.uid});});});}
  function resetAll(){var t=capture(),ts=now(),next=emptyState(t);next.meta.resetAt=ts;next.meta.resetBy=t.uid;return ready().then(function(){assertToken(t);return store().writeShared(COLLECTION,next);}).then(function(){assertToken(t);apply(next,t);return true;});}
  window.FinanceStore={version:VERSION,ready:ready,boot:boot,stop:stop,rebind:rebind,status:function(){return{version:VERSION,context:boundToken?clone(boundToken):null,ready:!!(boundToken&&same(boundToken)&&sub)};},get:function(){return clone(state||emptyState(boundToken));},sortTransactions:sortByDateThenStamp,monthlySummary:monthlySummary,addTransaction:addTransaction,updateTransaction:updateTransaction,deleteTransaction:deleteTransaction,upsertSourceTransaction:upsertSourceTransaction,addExtraIncome:addExtraIncome,deleteExtraIncome:deleteExtraIncome,addVasteLast:addVasteLast,deleteVasteLast:deleteVasteLast,toggleVasteLastPaid:toggleVasteLastPaid,setIncome:setIncome,setSamenBetaler:setSamenBetaler,addSavingsGoal:addSavingsGoal,updateSavingsGoal:updateSavingsGoal,deleteSavingsGoal:deleteSavingsGoal,addSavingsTransaction:addSavingsTransaction,deleteSavingsLogEntry:deleteSavingsLogEntry,resetAll:resetAll};
  window.addEventListener('familyapp:household-context-changed',rebind);window.addEventListener('familyapp:session:cleared',stop);window.addEventListener('online',ready);window.addEventListener('focus',ready);boot();
})();
