(function(){
try{
if(window.__famV022){return;} window.__famV022=1;
var A=function(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));};
var T=function(e){return (e&&e.textContent||'').toLowerCase();};
var lang=localStorage.getItem('fam_lang')||'en';
var tr={en:{add:'+ Add Quest',today:'Today',tomorrow:'Tomorrow',overmorrow:'Day after tomorrow',week:'Next week',later:'Later',done:'completed',level:'Level',streak:'Streak',newq:'New Quest',complete:'Mark as completed',reopen:'Reopen quest'},nl:{add:'+ Quest toevoegen',today:'Vandaag',tomorrow:'Morgen',overmorrow:'Overmorgen',week:'Volgende week',later:'Later',done:'voltooid',level:'Level',streak:'Streak',newq:'Nieuwe Quest',complete:'Markeer als voltooid',reopen:'Quest opnieuw openen'}};
var L=function(k){return (tr[lang]&&tr[lang][k])||k;};
var H={tasks:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=95&fm=webp',shop:'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=95&fm=webp',posts:'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=1200&q=95&fm=webp',recipes:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1600&q=95&fm=webp'};
var I={today:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=95&fm=webp',level:'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=95&fm=webp',streak:'https://images.unsplash.com/photo-1476231682828-37e571bc172f?auto=format&fit=crop&w=900&q=95&fm=webp',home:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=700&q=90&fm=webp',plant:'https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&w=700&q=90&fm=webp',car:'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=700&q=90&fm=webp',dent:'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=700&q=90&fm=webp',kids:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=700&q=90&fm=webp',food:'https://images.unsplash.com/photo-1543353071-10c8ba85a904?auto=format&fit=crop&w=700&q=90&fm=webp',work:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=700&q=90&fm=webp'};
function pick(s){s=(s||'').toLowerCase();if(s.indexOf('kind')>-1||s.indexOf('school')>-1){return I.kids;}if(s.indexOf('auto')>-1||s.indexOf('car')>-1){return I.car;}if(s.indexOf('plant')>-1){return I.plant;}if(s.indexOf('eten')>-1||s.indexOf('kook')>-1||s.indexOf('boodschap')>-1){return I.food;}if(s.indexOf('tand')>-1||s.indexOf('dokter')>-1){return I.dent;}if(s.indexOf('kamer')>-1||s.indexOf('huis')>-1){return I.home;}return I.work;}
var data=JSON.parse(localStorage.getItem('fam_tasks_v022')||localStorage.getItem('fam_tasks_v021')||'null')||[
['living','SIDE QUEST','Stofzuigen woonkamer','Maak de woonkamer weer fris.','2026-05-13','Esra','+20 XP',I.home,['Kussens opruimen','Vloer stofzuigen','Kleed schoonmaken'],1,'once','2026-05-13'],
['plant','SIDE QUEST','Planten water geven','Zorg dat alle planten genoeg water krijgen.','2026-05-14','Esra','+10 XP',I.plant,['Gieter vullen','Alle planten nalopen'],0,'once','2026-05-14'],
['car','SIDE QUEST','Auto wassen','Maak de auto van buiten en binnen schoon.','2026-05-20','Shane','+40 XP',I.car,['Buitenkant wassen','Interieur opruimen'],0,'once','2026-05-20']
];
function save(){localStorage.setItem('fam_tasks_v022',JSON.stringify(data));}
function bg(el,url){if(!el){return;}el.style.setProperty('background-image','url('+url+')','important');el.style.setProperty('background-size','cover','important');el.style.setProperty('background-position','center','important');var im=el.querySelector('img');if(im){im.src=url;im.style.opacity=1;im.style.objectFit='cover';}}
function home(){if(!T(A('.header-title')[0]).match(/familie|family/)){return;}var c=A('.home-epic-cards .epic-card,.home-pills .home-pill,.home-card,.home-pills>*,.home-epic-cards>*');bg(c[0],H.tasks);bg(c[1],H.shop);bg(c[2],H.posts);var s=A('.home-carousel .home-slide,.home-slide,.recipes-slide,.agenda-slide,.meals-slide');bg(s[0],H.recipes);}
function task(){return A('.task-tabs,.ttab').length||T(A('.header-title')[0]).match(/taken|tasks/);}
function overview(){var a=A('.ttab.active,.task-tabs .active')[0];return !a||T(a).match(/overzicht|overview/);}
function root(){return document.getElementById('task-content')||A('.task-content')[0];}
function group(x){var d=new Date(x[11]||x[4]);var now=new Date('2026-05-13T00:00:00');var diff=Math.round((new Date(d.toDateString())-now)/86400000);if(isNaN(diff)){return L('later');}if(diff===0){return L('today');}if(diff===1){return L('tomorrow');}if(diff===2){return L('overmorrow');}if(diff>2&&diff<8){return L('week');}return L('later');}
function card(x){var c=x[1].indexOf('RAID')>-1?'raid':(x[1].indexOf('DUNGEON')>-1?'dungeon':'');return '<div class="fqCard '+(x[9]?'done ':'')+c+'" data-id="'+x[0]+'"><button class="fqDel" data-del="'+x[0]+'">x</button><div class="fqImg" style="background-image:url('+x[7]+')"><div class="fqChk">'+(x[9]?'✓':'')+'</div></div><div class="fqBody"><div class="fqType">'+x[1]+'</div><div class="fqTitle">'+x[2]+'</div><div class="fqDesc">'+x[3]+'</div><div class="fqMeta"><span>'+String.fromCharCode(128197)+' '+(x[11]||x[4])+'</span><span>'+x[5]+'</span><span class="xp">'+x[6]+'</span></div></div><div class="fqArrow">›</div></div>';}
function stats(done,total){return '<div class="fqStats"><div class="fqStat" data-stat="today" style="background-image:url('+I.today+')"><div class="fqIcon">✓</div><h4>'+L('today')+'</h4><b>'+done+'/'+total+'</b><p>quests '+L('done')+'</p><div class="fqBar"><i style="width:'+Math.round(done/Math.max(total,1)*100)+'%"></i></div><div class="fqNext">›</div></div><div class="fqStat" data-stat="level" style="background-image:url('+I.level+')"><div class="fqIcon">12</div><h4>'+L('level')+'</h4><b>12</b><p>450 / 800 XP</p><div class="fqBar p"><i style="width:56%"></i></div><div class="fqNext">›</div></div><div class="fqStat" data-stat="streak" style="background-image:url('+I.streak+')"><div class="fqIcon">'+String.fromCharCode(128293)+'</div><h4>'+L('streak')+'</h4><b>7</b><p>days</p><div class="fqNext">›</div></div></div>';}
function ensure(){if(!document.getElementById('famBg')){var d=document.createElement('div');d.id='famBg';document.body.prepend(d);}}
function render(force){ensure();document.body.classList.toggle('famTask',!!task());var r=root();if(!r||!task()){return;}if(!overview()){r.dataset.v022='';return;}if(!force&&r.dataset.v022==='1'){return;}r.dataset.v022='1';var done=data.filter(function(x){return x[9];}).length;var groups={};data.forEach(function(x){var g=group(x);(groups[g]||(groups[g]=[])).push(x);});var order=[L('today'),L('tomorrow'),L('overmorrow'),L('week'),L('later')];r.innerHTML='<div class="fq"><div class="fqTop"><button class="fqAdd">'+L('add')+'</button></div>'+stats(done,data.length)+order.filter(function(g){return groups[g];}).map(function(g){return '<div class="fqHead" id="grp-'+g.replace(/\s+/g,'-')+'"><h3>'+g+'</h3><span>'+groups[g].filter(function(x){return x[9];}).length+' / '+groups[g].length+' '+L('done')+'</span></div>'+groups[g].map(card).join('');}).join('')+'</div>';A('.fqCard',r).forEach(function(e){e.onclick=function(ev){if(ev.target.dataset.del){ev.stopPropagation();data=data.filter(function(x){return x[0]!==ev.target.dataset.del;});save();r.dataset.v022='';render(true);return;}detail(e.dataset.id);};});A('.fqAdd',r)[0].onclick=create;A('.fqStat',r).forEach(function(s){s.onclick=function(){var t=s.dataset.stat;if(t==='today'){var el=document.getElementById('grp-'+L('today'));if(el){el.scrollIntoView({behavior:'smooth'});}else{simple('Today','No quests for today.',I.today);}}if(t==='level'){level();}if(t==='streak'){streak();}};});}
function modal(html){var m=document.getElementById('fqModal');if(!m){m=document.createElement('div');m.id='fqModal';m.className='fqModal';document.body.appendChild(m);}m.innerHTML=html;m.classList.add('open');document.body.style.overflow='hidden';A('.fqClose',m).forEach(function(b){b.onclick=function(){m.classList.remove('open');document.body.style.overflow='';};});return m;}
function hero(img,small,title,body){return '<div class="fqPage"><button class="fqClose">x</button><div class="fqHero" style="background-image:url('+img+')"><div class="fqHeroT"><small>'+small+'</small><h2>'+title+'</h2>'+(body?'<p>'+body+'</p>':'')+'</div></div><div class="fqContent">';}
function simple(t,b,img){modal(hero(img,'FamilyApp',t,'')+'<div class="fqBox"><p>'+b+'</p></div></div></div>');}
function level(){var ups=[['Quest completed','Stofzuigen woonkamer','+20 XP'],['Help given to Jamie','Group quest assist','+15 XP'],['Weekly goal reached','Family productivity streak','+50 XP'],['Ability progress','Planning Boost unlocks soon','72%']];var leaders=[['1','Esra','950 XP'],['2','Jamie','720 XP'],['3','Shane','450 XP'],['4','Liam','380 XP']];var u=ups.map(function(x){return '<div class="fqUpdate"><div><b>'+x[0]+'</b><br><small>'+x[1]+'</small></div><b>'+x[2]+'</b></div>';}).join('');var l=leaders.map(function(x){return '<div class="fqLeader"><b>'+x[0]+'</b><span>'+x[1]+'<br><small>Family rank</small></span><b>'+x[2]+'</b></div>';}).join('');var m=modal(hero(I.level,'Level Progress','Level 12','450 / 800 XP richting je volgende ability.')+'<div class="fqBox"><b>Context updates</b>'+u+'</div><div class="fqBox"><b>Compare with others</b><div class="fqFilter"><button class="on">Family</button><button>Household</button><button>Friends</button></div>'+l+'</div></div></div>');A('.fqFilter button',m).forEach(function(btn){btn.onclick=function(){A('.fqFilter button',m).forEach(function(b){b.classList.remove('on');});btn.classList.add('on');};});}
function streak(){var rs=[['3 days','+10 XP','done'],['7 days','+25 XP','done'],['14 days','+50 XP','locked'],['30 days','+100 XP','locked']].map(function(x){return '<div class="fqUpdate"><div><b>'+x[0]+'</b><br><small>Streak reward</small></div><b>'+x[1]+' '+x[2]+'</b></div>';}).join('');modal(hero(I.streak,'Streak','7 days','Je hebt 7 dagen achter elkaar minimaal een quest voltooid.')+'<div class="fqBox"><b>Waarom dit telt</b><p>Je streak laat zien dat het huishouden ritme krijgt. Houd hem vast om extra XP en family abilities sneller vrij te spelen.</p></div><div class="fqBox"><b>Volgende mijlpaal</b><p>14 dagen streak. Nog 7 dagen te gaan.</p><div class="fqBar p"><i style="width:50%"></i></div></div><div class="fqBox"><b>Rewards</b>'+rs+'</div></div></div>');}
function get(id){return data.find(function(x){return x[0]===id;})||data[0];}
function sub(x){return JSON.parse(localStorage.getItem('fqsub_'+x[0])||'null')||x[8].map(function(){return !!x[9];});}
function setsub(x,s){localStorage.setItem('fqsub_'+x[0],JSON.stringify(s));}
function detail(id){var x=get(id),st=sub(x);var m=modal(hero(x[7],x[1],x[2],'')+'<p>'+x[3]+'</p><div class="fqBox"><b class="subc"></b><div class="fqBar subbar"><i style="width:0%"></i></div>'+x[8].map(function(s,i){return '<div class="fqSub '+(st[i]?'done':'')+'"><span><i>'+(st[i]?'✓':'')+'</i>'+s+'</span><button class="fqSubDel">x</button></div>';}).join('')+'<button class="fqSubAdd">+ Add subquest</button></div><div class="fqBox"><b>Co-op</b><p>Invite someone and turn this into a Group Quest.</p><button class="fqHelp">Ask for help</button></div></div><div class="fqDoneWrap"><button class="fqDone">'+L('complete')+'</button></div></div>');function upd(){var rows=A('.fqSub',m),state=rows.map(function(r){return r.classList.contains('done');}),d=state.filter(Boolean).length,t=rows.length,b=A('.subbar i',m)[0],l=A('.subc',m)[0],btn=A('.fqDone',m)[0];setsub(x,state);if(b){b.style.width=(t?Math.round(d/t*100):0)+'%';}if(l){l.textContent=d+' / '+t+' '+L('done');}if(t&&d===t){btn.textContent=L('reopen');btn.classList.add('reopen');x[9]=1;}else{btn.textContent=L('complete');btn.classList.remove('reopen');x[9]=0;}save();var r=root();if(r){r.dataset.v022='';render(true);}}A('.fqSub',m).forEach(function(row){row.onclick=function(ev){if(ev.target.className==='fqSubDel'){ev.stopPropagation();var i=A('.fqSub',m).indexOf(row);x[8].splice(i,1);var ss=sub(x);ss.splice(i,1);setsub(x,ss);save();detail(x[0]);return;}row.classList.toggle('done');A('i',row)[0].textContent=row.classList.contains('done')?'✓':'';upd();};});A('.fqSubAdd',m)[0].onclick=function(){var s=prompt('Subquest?');if(!s){return;}x[8].push(s);var ss=sub(x);ss.push(false);setsub(x,ss);save();detail(x[0]);};A('.fqDone',m)[0].onclick=function(){A('.fqSub',m).forEach(function(row){row.classList.toggle('done',!x[9]);A('i',row)[0].textContent=!x[9]?'✓':'';});upd();};upd();}
function create(){var m=modal('<div class="fqPage"><button class="fqClose">x</button><div class="fqContent fqForm"><h2>'+L('newq')+'</h2><label>Name</label><input id="qn"><label>Description</label><textarea id="qd" rows="3"></textarea><label>Quest type</label><div class="fqSeg"><button id="side" class="on">Side</button><button id="dun">Dungeon</button><button id="raid">Raid</button></div><label>When</label><input id="qdate" type="date"><label>Assigned to</label><select id="qw"><option>Shane</option><option>Esra</option><option>Both</option></select><button class="fqSave">Save quest</button></div></div>');var type='SIDE QUEST';function on(id){['side','dun','raid'].forEach(function(i){A('#'+i,m)[0].classList.remove('on');});A('#'+id,m)[0].classList.add('on');}A('#side',m)[0].onclick=function(){type='SIDE QUEST';on('side');};A('#dun',m)[0].onclick=function(){type='DUNGEON';on('dun');};A('#raid',m)[0].onclick=function(){type='RAID';on('raid');};A('.fqSave',m)[0].onclick=function(){var n=A('#qn',m)[0].value.trim();if(!n){return;}var d=A('#qd',m)[0].value.trim()||'New quest.';var date=A('#qdate',m)[0].value||new Date().toISOString().slice(0,10);data.push(['q'+Date.now(),type,n,d,date,A('#qw',m)[0].value,type==='RAID'?'+120 XP':type==='DUNGEON'?'+60 XP':'+10 XP',pick(n+' '+d),['First step'],0,'once',date]);save();m.classList.remove('open');document.body.style.overflow='';var r=root();if(r){r.dataset.v022='';render(true);}};}
function langBtn(){if(document.getElementById('famLang')){return;}var b=document.createElement('button');b.id='famLang';b.className='famLang';b.textContent=lang==='en'?'NL':'EN';b.onclick=function(){lang=lang==='en'?'nl':'en';localStorage.setItem('fam_lang',lang);location.reload();};document.body.appendChild(b);}
function bind(){A('.ttab,.task-tabs button,.nav-btn').forEach(function(t){if(t.dataset.v022){return;}t.dataset.v022='1';t.addEventListener('click',function(){var r=root();if(r){r.dataset.v022='';}setTimeout(run,30);setTimeout(function(){render(true);},180);});});}
function run(){home();bind();render(false);langBtn();if(!task()){document.body.classList.remove('famTask');}}
document.addEventListener('DOMContentLoaded',function(){run();setTimeout(function(){render(true);},60);});window.addEventListener('load',function(){run();setTimeout(function(){render(true);},120);});for(var i=0;i<12;i++){setTimeout(run,i*150);}setInterval(run,900);new MutationObserver(run).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style']});
}catch(e){console.error('fam v0.22 failed',e);}
})();