'use strict';
// ============================================================
// CLEANING APPROVAL CLARITY v0.1.0
// Adds one explicit status banner and a safe "Planning vernieuwen" action to
// the canonical approval panel. It does NOT rewrite .cleaning-approval-copy or
// any occurrence-card content owned by CleaningPlanApprovalUi.
// ============================================================
(function(){
  if(window.CleaningApprovalClarity)return;

  var VERSION='0.1.0';
  var state={snapshot:null,unsubscribe:null,observer:null,queued:false,busy:false,notice:'',error:''};

  function text(value){return String(value==null?'':value).trim();}
  function escapeHtml(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function context(){try{return window.HouseholdContext&&window.HouseholdContext.snapshot?window.HouseholdContext.snapshot():null;}catch(error){return null;}}
  function memberName(uid){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[],row=Array.isArray(rows)?rows.find(function(item){return text(item&&(item.uid||item.id))===text(uid);}):null;return row?text(row.displayName||row.name)||'Gezinslid':'Gezinslid';}catch(error){return'Gezinslid';}}
  function currentPlan(){var snapshot=state.snapshot,persistence=window.CleaningPlanPersistenceContract,plans=snapshot&&snapshot.data&&snapshot.data.plans;if(!persistence||!persistence.planIdForWindow||!plans)return null;try{var start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-((start.getDay()+6)%7));var end=new Date(start.getTime());end.setDate(end.getDate()+7);var id=persistence.planIdForWindow({startAt:start.getTime(),endAt:end.getTime()}),row=plans[id];return row&&typeof row==='object'?Object.assign({id:id},row):null;}catch(error){return null;}}
  function approvalFor(uid,planId){var data=state.snapshot&&state.snapshot.data||{},map=data.approvals&&data.approvals[uid],row=map&&map[planId];return row&&typeof row==='object'?row:null;}
  function pendingUids(plan){var required=Array.isArray(plan&&plan.requiredApprovalUids)?plan.requiredApprovalUids.map(String):[];return required.filter(function(uid){var row=approvalFor(uid,plan.id);return !row||row.status!=='ACCEPTED';});}
  function bannerModel(plan){
    var ctx=context(),uid=text(ctx&&ctx.uid),mine=approvalFor(uid,plan.id),pending=pendingUids(plan);
    if(plan.status==='ACTIVE')return{tone:'active',title:'Plan is actief ✓',copy:'Iedereen die nodig was heeft geaccepteerd. Wijzigingen in kamers en routines worden weer met Taken en Agenda gesynchroniseerd.'};
    if(plan.status==='DRAFT')return{tone:'draft',title:'Nog niet actief',copy:'Dit is nog een concept. Eerst voorstellen aan het gezin; daarna wordt het pas actief wanneer alle benodigde personen akkoord zijn.'};
    if(plan.approvalState==='CHANGES_REQUESTED')return{tone:'danger',title:'Plan is niet actief',copy:'Er is een aanpassing gevraagd. Het plan moet eerst worden aangepast en opnieuw worden voorgesteld.'};
    if(mine&&mine.status==='PENDING')return{tone:'attention',title:'Jouw akkoord is nog nodig',copy:'Accepteer of wijs jouw deel af. Totdat alle benodigde gezinsleden akkoord zijn, wordt deze nieuwe verdeling niet actief.'};
    if(pending.length){var names=pending.map(memberName);return{tone:'attention',title:'Nog niet actief · wacht op '+names.join(', '),copy:'Jouw deel is geregeld, maar '+(pending.length===1?'deze persoon moet':'deze personen moeten')+' nog reageren voordat de nieuwe verdeling actief wordt.'};}
    return{tone:'attention',title:'Nog niet actief',copy:'Dit voorstel wacht nog op de benodigde goedkeuringen.'};
  }

  function ensureStyle(){if(document.getElementById('cleaning-approval-clarity-style'))return;var style=document.createElement('style');style.id='cleaning-approval-clarity-style';style.textContent='\n'
    +'#screen-cleaning .cleaning-approval-state-banner{display:grid;gap:3px;padding:11px 12px;border-radius:14px;border:1px solid var(--cleaning-border);background:color-mix(in srgb,var(--cleaning-accent) 7%,var(--cleaning-surface))}#screen-cleaning .cleaning-approval-state-banner strong{font-size:12px;color:var(--cleaning-text)}#screen-cleaning .cleaning-approval-state-banner span{font-size:10px;line-height:1.45;color:var(--cleaning-muted);font-weight:750}#screen-cleaning .cleaning-approval-state-banner[data-tone="attention"]{border-color:rgba(198,132,22,.3);background:rgba(198,132,22,.09)}#screen-cleaning .cleaning-approval-state-banner[data-tone="danger"]{border-color:rgba(188,54,66,.25);background:rgba(188,54,66,.08)}#screen-cleaning .cleaning-approval-state-banner[data-tone="active"]{border-color:rgba(46,139,87,.25);background:rgba(46,139,87,.08)}\n'
    +'#screen-cleaning .cleaning-approval-refresh{min-height:42px;width:100%;border:1px solid var(--cleaning-border);border-radius:12px;background:var(--cleaning-surface);color:var(--cleaning-text);font:inherit;font-size:10px;font-weight:900;cursor:pointer}#screen-cleaning .cleaning-approval-refresh:disabled{opacity:.5}#screen-cleaning .cleaning-approval-refresh-note{margin:0;font-size:9px;line-height:1.4;color:var(--cleaning-muted);font-weight:750;text-align:center}\n';document.head.appendChild(style);}

  function decorate(){
    state.queued=false;ensureStyle();var screen=document.getElementById('screen-cleaning'),panel=screen&&screen.querySelector('[data-cleaning-approval-panel]'),plan=currentPlan();if(!screen||!screen.classList.contains('active')||!panel||!plan)return;var model=bannerModel(plan),banner=panel.querySelector('[data-cleaning-approval-state-banner]'),signature=JSON.stringify({tone:model.tone,title:model.title,copy:model.copy});if(!banner){banner=document.createElement('div');banner.className='cleaning-approval-state-banner';banner.setAttribute('data-cleaning-approval-state-banner','1');var head=panel.querySelector('.cleaning-approval-head');if(head&&head.parentNode)head.parentNode.insertBefore(banner,head.nextSibling);else panel.insertBefore(banner,panel.firstChild);}if(banner.getAttribute('data-signature')!==signature){banner.setAttribute('data-signature',signature);banner.setAttribute('data-tone',model.tone);banner.innerHTML='<strong>'+escapeHtml(model.title)+'</strong><span>'+escapeHtml(model.copy)+'</span>';}
    var refresh=panel.querySelector('[data-cleaning-approval-refresh-wrap]');if(plan.status==='DRAFT'){if(refresh)refresh.remove();return;}if(!refresh){refresh=document.createElement('div');refresh.setAttribute('data-cleaning-approval-refresh-wrap','1');panel.appendChild(refresh);}var refreshSignature=[state.busy,state.notice,state.error,plan.updatedAt||0].join('|');if(refresh.getAttribute('data-signature')!==refreshSignature){refresh.setAttribute('data-signature',refreshSignature);refresh.innerHTML='<button type="button" class="cleaning-approval-refresh" data-cleaning-approval-refresh'+(state.busy?' disabled':'')+'>'+(state.busy?'Planning bijwerken…':'↻ Planning vernieuwen')+'</button><p class="cleaning-approval-refresh-note">Gebruik dit na het verwijderen, toevoegen of wijzigen van kamers/routines. De huidige goedkeuringen blijven waar mogelijk behouden.</p>'+(state.notice?'<p class="cleaning-approval-refresh-note" style="color:var(--cleaning-accent)">'+escapeHtml(state.notice)+'</p>':'')+(state.error?'<p class="cleaning-approval-refresh-note" style="color:#b32636">'+escapeHtml(state.error)+'</p>':'');}
  }
  function queue(){if(state.queued)return;state.queued=true;(window.requestAnimationFrame||function(callback){return window.setTimeout(callback,0);})(decorate);}
  function refresh(){var plan=currentPlan(),sanitizer=window.CleaningPlanSanitizer;if(!plan||state.busy)return;if(!sanitizer||typeof sanitizer.refreshPlan!=='function'){state.error='Planning vernieuwen is nog niet geladen.';queue();return;}state.busy=true;state.notice='';state.error='';queue();sanitizer.refreshPlan(plan.id).then(function(){state.busy=false;state.notice='Planning is bijgewerkt ✓';queue();window.setTimeout(function(){state.notice='';queue();},2200);}).catch(function(error){state.busy=false;state.error=(error&&error.message)||'Planning vernieuwen mislukt';queue();});}
  function onClick(event){var button=event.target&&event.target.closest?event.target.closest('[data-cleaning-approval-refresh]'):null;if(!button)return;event.preventDefault();event.stopPropagation();refresh();}
  function start(){if(window.__cleaningApprovalClarityStarted)return;window.__cleaningApprovalClarityStarted=true;ensureStyle();var r=window.CleaningHouseholdRepository;if(r&&typeof r.subscribe==='function')state.unsubscribe=r.subscribe(function(snapshot){state.snapshot=snapshot;queue();});else try{state.snapshot=r&&r.snapshot?r.snapshot():null;}catch(error){}document.addEventListener('click',onClick,true);var target=document.getElementById('screen-cleaning')||document.documentElement;if(typeof MutationObserver!=='undefined'&&target){state.observer=new MutationObserver(queue);state.observer.observe(target,{childList:true,subtree:true});}window.addEventListener('familyapp:household-identity-synced',queue);queue();}

  window.CleaningApprovalClarity={version:VERSION,start:start,_bannerModel:bannerModel,_pendingUids:pendingUids};start();
})();
