'use strict';
// ============================================================
// CLEANING V2.3 — OCCURRENCE COMMANDS
// Lightweight extension of the existing CleaningV2Repository object.
// CleaningOccurrence remains canonical. No listener, observer, popup owner,
// startup work or second public writer is introduced.
// ============================================================
(function(){
  var VERSION='2.3.0';
  var DAY_MS=86400000;
  var busy=new Set();

  function text(value){return String(value==null?'':value).trim();}
  function safeKey(value){return text(value).replace(/[.#$\[\]\/\u0000-\u001F\u007F]/g,'_');}
  function clone(value){if(value===undefined)return undefined;try{return JSON.parse(JSON.stringify(value));}catch(error){return value;}}
  function ctx(){try{return window.HouseholdContext&&window.HouseholdContext.snapshot?window.HouseholdContext.snapshot():null;}catch(error){return null;}}
  function capture(){try{return window.HouseholdContext&&window.HouseholdContext.capture?window.HouseholdContext.capture():null;}catch(error){return null;}}
  function current(token){try{return !!(window.HouseholdContext&&window.HouseholdContext.isCurrent&&window.HouseholdContext.isCurrent(token));}catch(error){return false;}}
  function db(){try{return window.fbDb||(window.firebase&&window.firebase.database&&window.firebase.database())||null;}catch(error){return null;}}
  function repo(){return window.CleaningHouseholdRepository||window.CleaningV2Repository||null;}
  function snapshot(){var r=repo();try{return r&&r.snapshot?r.snapshot():null;}catch(error){return null;}}
  function members(){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[];return(Array.isArray(rows)?rows:[]).filter(function(row){return row&&text(row.uid||row.id)&&text(row.status||'active').toLowerCase()==='active';});}catch(error){return[];}}
  function memberUid(row){return text(row&&(row.uid||row.id));}
  function memberName(uid){var row=members().find(function(item){return memberUid(item)===text(uid);});return text(row&&(row.displayName||row.name))||'Gezinslid';}
  function activeUids(){return members().map(memberUid).filter(Boolean);}
  function localDate(timestamp){var d=new Date(Number(timestamp)||Date.now());return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function parseDate(date,time){date=text(date);time=text(time);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error('CLEANING_V23_DATE_INVALID');if(time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw new Error('CLEANING_V23_TIME_INVALID');var p=date.split('-').map(Number),t=time?time.split(':').map(Number):[0,0],d=new Date(p[0],p[1]-1,p[2],t[0],t[1],0,0);if(d.getFullYear()!==p[0]||d.getMonth()!==p[1]-1||d.getDate()!==p[2])throw new Error('CLEANING_V23_DATE_INVALID');var start=new Date(p[0],p[1]-1,p[2],0,0,0,0).getTime();return{date:date,time:time,startAt:d.getTime(),dayStartAt:start,dayEndAt:start+DAY_MS};}
  function writeContext(){var c=ctx(),database=db(),token=capture();if(!c||c.ready!==true||!c.uid||!c.householdId)throw new Error('ACTIVE_HOUSEHOLD_REQUIRED');if(!database)throw new Error('FIREBASE_DATABASE_UNAVAILABLE');if(!token||!current(token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED');return{ctx:c,db:database,token:token,familyPath:'families/'+c.householdId,cleaningPath:'families/'+c.householdId+'/cleaning'};}
  function occurrence(id){var s=snapshot(),row=s&&s.data&&s.data.occurrences&&s.data.occurrences[id];return row?Object.assign({id:id},clone(row)):null;}
  function roomActive(roomId){var s=snapshot(),room=s&&s.data&&s.data.rooms&&s.data.rooms[roomId];return !!(room&&room.active!==false);}
  function isClosed(row){var a=text(row&&row.status).toUpperCase(),b=text(row&&row.assignmentStatus).toUpperCase();return a==='COMPLETED'||b==='COMPLETED'||a==='CANCELLED'||a==='SKIPPED'||b==='SKIPPED';}
  function hasPendingCollab(row){var transfer=text(row&&row.transferRequest&&row.transferRequest.status).toUpperCase(),help=text(row&&row.helpRequest&&row.helpRequest.status).toUpperCase();return transfer==='PENDING'||transfer==='COUNTER_PROPOSED'||help==='PENDING';}
  function withBusy(id,fn){id=text(id);if(!id)return Promise.reject(new Error('CLEANING_V23_OCCURRENCE_REQUIRED'));if(busy.has(id))return Promise.resolve({duplicateTap:true});busy.add(id);return Promise.resolve().then(fn).finally(function(){busy.delete(id);});}
  function recordOccurrenceIds(row){var ids=[];(Array.isArray(row&&row.cleaningOccurrenceIds)?row.cleaningOccurrenceIds:[]).forEach(function(v){v=text(v);if(v&&ids.indexOf(v)<0)ids.push(v);});[row&&row.cleaningOccurrenceId,row&&row.sourceId].forEach(function(v){v=text(v);if(v&&ids.indexOf(v)<0)ids.push(v);});return ids;}
  function projectionTask(id){var rows=Array.isArray(window.taskData)?window.taskData:[];return rows.find(function(row){return recordOccurrenceIds(row).indexOf(text(id))>=0;})||null;}
  function projectionEvent(id){var r=window.CalendarEventHouseholdRepository||window.CalendarEventRepository,rows=[];try{rows=r&&r.list?r.list():[];}catch(error){}return(Array.isArray(rows)?rows:[]).find(function(row){return recordOccurrenceIds(row).indexOf(text(id))>=0;})||null;}
  function syncProjection(row,write,mode){if(!row||!current(write.token))return Promise.reject(new Error('HOUSEHOLD_CONTEXT_CHANGED'));var updates={},stamp=Date.now(),assigned=text((row.assignmentUids||[])[0]),display=memberName(assigned),task=projectionTask(row.id),taskKey=task&&text(task._key||task.id);if(taskKey){updates['tasks/'+taskKey+'/assignedToUid']=assigned;updates['tasks/'+taskKey+'/assignedToUids']=assigned?Object.fromEntries([[assigned,true]]):{};updates['tasks/'+taskKey+'/who']=display?[display]:[];updates['tasks/'+taskKey+'/date']=text(row.scheduledDate);updates['tasks/'+taskKey+'/dueDate']=text(row.scheduledDate);updates['tasks/'+taskKey+'/time']=text(row.scheduledTime);updates['tasks/'+taskKey+'/updatedAt']=stamp;updates['tasks/'+taskKey+'/updatedByUid']=write.ctx.uid;if(mode==='SKIP'||mode==='CARRY_FORWARD'){updates['tasks/'+taskKey+'/status']='skipped';updates['tasks/'+taskKey+'/cleaningOutcome']=mode;updates['tasks/'+taskKey+'/done']=false;}}
    var event=projectionEvent(row.id),eventKey=event&&text(event._key||event.id);if(!eventKey&&row.projections&&row.projections.calendarEventId)eventKey='id_'+safeKey(row.projections.calendarEventId);if(eventKey){updates['calendarEvents/'+eventKey+'/assignedToUid']=assigned;updates['calendarEvents/'+eventKey+'/who']=display;updates['calendarEvents/'+eventKey+'/date']=text(row.scheduledDate);updates['calendarEvents/'+eventKey+'/time']=text(row.scheduledTime);updates['calendarEvents/'+eventKey+'/flexible']=!text(row.scheduledTime);updates['calendarEvents/'+eventKey+'/updatedAt']=stamp;updates['calendarEvents/'+eventKey+'/updatedByUid']=write.ctx.uid;if(mode==='SKIP'||mode==='CARRY_FORWARD'){updates['calendarEvents/'+eventKey+'/status']='cancelled';updates['calendarEvents/'+eventKey+'/cancelled']=true;updates['calendarEvents/'+eventKey+'/cleaningOutcome']=mode;}}
    if(!Object.keys(updates).length)return Promise.resolve();return write.db.ref(write.familyPath).update(updates);
  }
  function validateEditable(row,write){if(!row)throw new Error('CLEANING_V23_OCCURRENCE_NOT_FOUND');if(row.householdId&&text(row.householdId)!==text(write.ctx.householdId))throw new Error('CLEANING_V23_HOUSEHOLD_CONFLICT');if(isClosed(row))throw new Error('CLEANING_V23_OCCURRENCE_CLOSED');if(!roomActive(row.roomId))throw new Error('CLEANING_V23_ROOM_ARCHIVED');if(hasPendingCollab(row))throw new Error('CLEANING_V23_COLLAB_PENDING');}

  function adjustOccurrence(id,input){return withBusy(id,function(){var write=writeContext(),wantedAssignee=text(input&&input.assigneeUid),wantedDate=text(input&&input.date),wantedTime=text(input&&input.time),parts=parseDate(wantedDate,wantedTime),allowed=activeUids();if(wantedAssignee&&allowed.indexOf(wantedAssignee)<0)throw new Error('CLEANING_V23_ASSIGNEE_INVALID');var ref=write.db.ref(write.cleaningPath+'/occurrences/'+safeKey(id));return ref.transaction(function(server){if(!server||!current(write.token))return;var row=clone(server);validateEditable(row,write);row.scheduledDate=parts.date;row.scheduledTime=parts.time;row.scheduledStartAt=parts.time?parts.startAt:null;row.scheduledEndAt=parts.time?parts.startAt+Math.max(0,Number(row.estimatedMinutes)||0)*60000:null;row.scheduledWindow={startAt:parts.dayStartAt,endAt:parts.dayEndAt};row.flexibleWindow={startAt:parts.dayStartAt,endAt:parts.dayEndAt};row.status=parts.time?'SCHEDULED':'FLEXIBLE';row.assignmentStatus='ACTIVE';if(wantedAssignee)row.assignmentUids=[wantedAssignee];row.manuallyAdjustedAt=Date.now();row.manuallyAdjustedByUid=write.ctx.uid;row.updatedAt=Date.now();row.updatedByUid=write.ctx.uid;row.v23Revision=Math.max(0,Number(row.v23Revision)||0)+1;return row;}).then(function(result){if(!result||result.committed!==true||!result.snapshot)throw new Error('CLEANING_V23_WRITE_NOT_COMMITTED');if(!current(write.token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED');var row=Object.assign({id:id},result.snapshot.val());return syncProjection(row,write,'ADJUST').then(function(){return row;});});});}

  function laterThisWeek(id){var row=occurrence(id);if(!row)return Promise.reject(new Error('CLEANING_V23_OCCURRENCE_NOT_FOUND'));var base=text(row.scheduledDate)?new Date(text(row.scheduledDate)+'T12:00:00'):new Date(),candidate=new Date(Math.max(Date.now(),base.getTime())+DAY_MS),day=candidate.getDay();if(day===0)return Promise.reject(new Error('CLEANING_V23_NO_LATER_DAY_THIS_WEEK'));return adjustOccurrence(id,{date:localDate(candidate.getTime()),time:text(row.scheduledTime),assigneeUid:text((row.assignmentUids||[])[0])});}

  function finalizeIncomplete(id,mode){mode=text(mode).toUpperCase();if(mode!=='SKIP'&&mode!=='CARRY_FORWARD')return Promise.reject(new Error('CLEANING_V23_OUTCOME_INVALID'));return withBusy(id,function(){var write=writeContext(),logId='v23_'+safeKey(id)+'_'+mode.toLowerCase(),resultRow=null,remainingIds=[];var ref=write.db.ref(write.cleaningPath+'/occurrences/'+safeKey(id));return ref.transaction(function(server){if(!server||!current(write.token))return;var row=clone(server);if(isClosed(row)){if(text(row.exceptionOutcome).toUpperCase()===mode){resultRow=row;return;}throw new Error('CLEANING_V23_OCCURRENCE_CLOSED');}validateEditable(row,write);var unfinished=(Array.isArray(row.checklist)?row.checklist:[]).filter(function(item){return !item||item.completed!==true;});if(!unfinished.length)throw new Error('CLEANING_V23_NOTHING_REMAINING');remainingIds=unfinished.map(function(item){return text(item&&(item.routineItemId||item.id));}).filter(Boolean);var stamp=Date.now();row.status='SKIPPED';row.assignmentStatus='SKIPPED';row.skippedAt=stamp;row.skippedByUid=write.ctx.uid;row.skipReason=mode;row.exceptionOutcome=mode;row.exceptionLogId=logId;if(mode==='CARRY_FORWARD'){row.carriedForwardAt=stamp;row.carriedForwardByUid=write.ctx.uid;}row.updatedAt=stamp;row.updatedByUid=write.ctx.uid;row.v23Revision=Math.max(0,Number(row.v23Revision)||0)+1;resultRow=row;return row;}).then(function(result){if(resultRow&&(!result||result.committed!==true))return resultRow;if(!result||result.committed!==true||!result.snapshot)throw new Error('CLEANING_V23_WRITE_NOT_COMMITTED');resultRow=Object.assign({id:id},result.snapshot.val());var stamp=Date.now(),updates={};updates['cleaning/completionLogs/'+logId]={id:logId,householdId:write.ctx.householdId,occurrenceId:id,planId:resultRow.planId||null,roomId:resultRow.roomId||null,assignmentUids:Array.isArray(resultRow.assignmentUids)?resultRow.assignmentUids.slice():[],checklist:clone(resultRow.checklist||[]),remainingRoutineItemIds:remainingIds,estimatedMinutes:Number(resultRow.estimatedMinutes)||0,status:(resultRow.checklist||[]).some(function(x){return x&&x.completed===true;})?'PARTIAL':'SKIPPED',outcome:mode,source:'CLEANING_V23',finalizedAt:stamp,finalizedByUid:write.ctx.uid,createdAt:stamp,createdByUid:write.ctx.uid,schemaVersion:2};if(mode==='CARRY_FORWARD'){var s=snapshot(),routines=s&&s.data&&s.data.routines||{};remainingIds.forEach(function(rid){var routine=routines[rid];if(!routine||routine.active===false)return;var next=Math.max(Number(routine.nextDueAt)||stamp,stamp)+Math.max(1,parseInt(routine.intervalDays,10)||7)*DAY_MS;updates['cleaning/routines/'+safeKey(rid)+'/nextDueAt']=next;updates['cleaning/routines/'+safeKey(rid)+'/lastExceptionAt']=stamp;updates['cleaning/routines/'+safeKey(rid)+'/lastExceptionOutcome']=mode;updates['cleaning/routines/'+safeKey(rid)+'/updatedAt']=stamp;updates['cleaning/routines/'+safeKey(rid)+'/updatedByUid']=write.ctx.uid;});}
      if(!current(write.token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED');return write.db.ref(write.familyPath).update(updates).then(function(){return syncProjection(resultRow,write,mode);}).then(function(){return resultRow;});});});}

  function userMessage(error){var code=text(error&&error.message||error);if(code.indexOf('NO_LATER_DAY')>=0)return'Er is deze week geen latere dag meer. Kies handmatig een ander moment.';if(code.indexOf('COLLAB_PENDING')>=0)return'Rond eerst het openstaande overdracht- of hulpverzoek af.';if(code.indexOf('ROOM_ARCHIVED')>=0)return'De kamer van deze beurt is inmiddels verwijderd.';if(code.indexOf('ASSIGNEE_INVALID')>=0)return'Kies een actief gezinslid.';if(code.indexOf('DATE_INVALID')>=0)return'Kies een geldige datum.';if(code.indexOf('TIME_INVALID')>=0)return'Kies een geldige tijd.';if(code.indexOf('NOTHING_REMAINING')>=0)return'Alle onderdelen zijn al afgerond.';if(code.indexOf('OCCURRENCE_CLOSED')>=0)return'Deze schoonmaakbeurt is al afgesloten.';if(code.indexOf('HOUSEHOLD')>=0)return'Het actieve huishouden veranderde. Probeer opnieuw.';return code||'Deze wijziging kon niet worden opgeslagen.';}

  function install(){var r=repo();if(!r)return false;if(typeof r.adjustOccurrenceV23!=='function')r.adjustOccurrenceV23=adjustOccurrence;if(typeof r.laterThisWeekV23!=='function')r.laterThisWeekV23=laterThisWeek;if(typeof r.finalizeIncompleteV23!=='function')r.finalizeIncompleteV23=finalizeIncomplete;r.v23CommandsVersion=VERSION;return true;}
  window.CleaningOccurrenceCommandsV23=Object.freeze({version:VERSION,install:install,userMessage:userMessage});
  install();
})();

export const CLEANING_OCCURRENCE_COMMANDS_V23_VERSION='2.3.0';