'use strict';
// ============================================================
// CLEANING OVERVIEW EXPERIENCE v0.1.0
// Presentation-only live house status + recent canonical Cleaning history.
// Also fills the existing 'Gepland per kamer' shell without owning Planning.
// ============================================================
(function(){
  if(window.CleaningOverviewExperience)return;

  var VERSION='0.1.0';
  var state={observer:null,queued:false,repository:null};

  function text(value){return String(value==null?'':value).trim();}
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function pad(value){return value<10?'0'+value:String(value);}
  function todayIso(){var d=new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}
  function localIso(value){var d=new Date(Number(value)||0);if(!Number.isFinite(d.getTime())||!Number(value))return'';return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}
  function root(){var snap=state.repository;if(!snap){try{var repo=window.CleaningHouseholdRepository;snap=repo&&repo.snapshot?repo.snapshot():null;}catch(error){}}return snap&&snap.data||{};}
  function roomName(data,id){var room=data.rooms&&data.rooms[id];return text(room&&room.name)||'Ruimte';}
  function memberName(uid){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[],row=(Array.isArray(rows)?rows:[]).find(function(item){return text(item&&(item.uid||item.id))===text(uid);});return text(row&&(row.displayName||row.name))||'Gezinslid';}catch(error){return'Gezinslid';}}
  function occurrenceDate(row){var explicit=text(row&&row.scheduledDate);if(/^\d{4}-\d{2}-\d{2}$/.test(explicit))return explicit;return localIso(Number(row&&row.scheduledStartAt)||Number(row&&row.slotAt)||Number(row&&row.flexibleWindow&&row.flexibleWindow.startAt)||Number(row&&row.earliestDueAt));}
  function activeOccurrence(row){var status=text(row&&row.status).toUpperCase(),assignment=text(row&&row.assignmentStatus).toUpperCase();return !!row&&status!=='CANCELLED'&&status!=='SKIPPED'&&status!=='COMPLETED'&&assignment!=='COMPLETED'&&assignment!=='SKIPPED'&&['ACTIVE','ACCEPTED'].indexOf(assignment)>=0;}
  function activeOccurrences(data){var rows=data.occurrences||{};return Object.keys(rows).map(function(id){return Object.assign({id:id},rows[id]||{});}).filter(activeOccurrence);}
  function pausedRoutines(data){var rows=data.routines||{};return Object.keys(rows).map(function(id){return Object.assign({id:id},rows[id]||{});}).filter(function(row){return row&&row.active!==false&&row.paused===true;});}
  function recentLogs(data){var rows=data.completionLogs||{};return Object.keys(rows).map(function(id){var row=rows[id]||{};return Object.assign({id:id,_at:Number(row.completedAt)||Number(row.finalizedAt)||Number(row.reopenedAt)||Number(row.createdAt)||0},row);}).filter(function(row){return row._at>0;}).sort(function(a,b){return b._at-a._at;});}
  function relativeDate(value){var at=Number(value)||0;if(!at)return'';var d=new Date(at),today=new Date();today.setHours(0,0,0,0);var day=new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime(),diff=Math.round((day-today.getTime())/86400000);if(diff===0)return'Vandaag';if(diff===-1)return'Gisteren';if(diff===1)return'Morgen';try{return d.toLocaleDateString('nl-NL',{day:'numeric',month:'short'});}catch(error){return'';}}
  function dueLabel(date){var today=todayIso();if(!date)return'Flexibel';if(date<today)return'Achterstallig';if(date===today)return'Vandaag';try{return new Date(date+'T00:00:00').toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'});}catch(error){return date;}}

  function ensureStyle(){if(document.getElementById('cleaning-overview-experience-style'))return;var style=document.createElement('style');style.id='cleaning-overview-experience-style';style.textContent='\n'
    +'#screen-cleaning .cleaning-live-overview{display:grid;gap:12px}.cleaning-overview-hero{padding:17px;border:1px solid var(--cleaning-border);border-radius:20px;background:linear-gradient(145deg,color-mix(in srgb,var(--cleaning-accent) 10%,var(--cleaning-surface)),var(--cleaning-surface));box-shadow:var(--cleaning-shadow)}.cleaning-overview-hero p{margin:0 0 5px;font-size:10px;font-weight:900;color:var(--cleaning-accent);text-transform:uppercase;letter-spacing:.08em}.cleaning-overview-hero h2{margin:0;font-size:20px}.cleaning-overview-hero>span{display:block;margin-top:6px;color:var(--cleaning-muted);font-size:11px;line-height:1.45}\n'
    +'#screen-cleaning .cleaning-overview-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.cleaning-overview-stat{padding:12px 9px;border:1px solid var(--cleaning-border);border-radius:15px;background:var(--cleaning-surface);text-align:center}.cleaning-overview-stat strong{display:block;font-size:19px}.cleaning-overview-stat span{display:block;margin-top:2px;color:var(--cleaning-muted);font-size:9px;font-weight:850}.cleaning-overview-stat.is-attention strong{color:#b35c00}\n'
    +'#screen-cleaning .cleaning-overview-section{padding:14px;border:1px solid var(--cleaning-border);border-radius:18px;background:var(--cleaning-surface)}.cleaning-overview-section-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-end;margin-bottom:10px}.cleaning-overview-section-head strong{font-size:13px}.cleaning-overview-section-head span{font-size:9px;color:var(--cleaning-muted);font-weight:850}.cleaning-history-list{display:grid;gap:8px}.cleaning-history-row{display:flex;align-items:center;gap:10px;padding:9px;border-radius:13px;background:color-mix(in srgb,var(--cleaning-accent) 4%,var(--cleaning-surface));border:1px solid color-mix(in srgb,var(--cleaning-accent) 8%,var(--cleaning-border))}.cleaning-history-icon{width:34px;height:34px;flex:0 0 auto;display:grid;place-items:center;border-radius:11px;background:color-mix(in srgb,var(--cleaning-accent) 10%,var(--cleaning-surface));font-size:15px}.cleaning-history-copy{min-width:0;flex:1}.cleaning-history-copy strong{display:block;font-size:11px}.cleaning-history-copy span{display:block;margin-top:2px;color:var(--cleaning-muted);font-size:9px;line-height:1.35}.cleaning-history-date{font-size:9px!important;font-weight:900!important;white-space:nowrap}.cleaning-overview-empty{padding:13px;border:1px dashed var(--cleaning-border);border-radius:13px;color:var(--cleaning-muted);font-size:10px;line-height:1.45;text-align:center}\n'
    +'#screen-cleaning .cleaning-planned-room-list{display:grid;gap:10px}.cleaning-planned-room-card{padding:13px;border:1px solid var(--cleaning-border);border-radius:17px;background:var(--cleaning-surface)}.cleaning-planned-room-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.cleaning-planned-room-head strong{font-size:12px}.cleaning-planned-room-head span{font-size:9px;color:var(--cleaning-muted);font-weight:850}.cleaning-planned-room-items{display:grid;gap:6px;margin-top:9px}.cleaning-planned-room-item{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:8px 9px;border-radius:11px;background:color-mix(in srgb,var(--cleaning-accent) 4%,var(--cleaning-surface))}.cleaning-planned-room-item div{min-width:0}.cleaning-planned-room-item strong{display:block;font-size:10.5px}.cleaning-planned-room-item small{display:block;margin-top:2px;color:var(--cleaning-muted);font-size:8.5px}.cleaning-planned-room-item>span{font-size:8.5px;font-weight:900;color:var(--cleaning-accent);white-space:nowrap}.cleaning-planned-room-paused{display:inline-flex;margin-top:8px;padding:4px 8px;border-radius:999px;background:color-mix(in srgb,var(--cleaning-accent) 9%,var(--cleaning-surface));color:var(--cleaning-accent);font-size:8.5px;font-weight:900}\n';document.head.appendChild(style);}

  function historyMeta(log){var outcome=text(log.outcome).toUpperCase(),status=text(log.status).toUpperCase();if(outcome==='CARRY_FORWARD')return{icon:'→',title:'Deels gedaan · doorgeschoven'};if(outcome==='SKIP'||status==='SKIPPED')return{icon:'⏭',title:'Schoonmaakbeurt overgeslagen'};if(status==='PARTIAL')return{icon:'◐',title:'Schoonmaakbeurt deels gedaan'};if(status==='REOPENED')return{icon:'↻',title:'Schoonmaakbeurt heropend'};return{icon:'✓',title:'Schoonmaakbeurt afgerond'};}
  function historyMarkup(data){var logs=recentLogs(data).slice(0,8);if(!logs.length)return'<div class="cleaning-overview-empty">Nog geen schoonmaakgeschiedenis. Afgeronde, gedeeltelijke en overgeslagen beurten verschijnen hier automatisch.</div>';return'<div class="cleaning-history-list">'+logs.map(function(log){var meta=historyMeta(log),check=Array.isArray(log.checklist)?log.checklist:[],done=check.filter(function(item){return item&&item.completed===true;}).length,who=text(log.completedByUid||log.finalizedByUid||log.createdByUid),detail=done+' van '+check.length+' stappen';return'<div class="cleaning-history-row"><div class="cleaning-history-icon">'+meta.icon+'</div><div class="cleaning-history-copy"><strong>'+esc(roomName(data,log.roomId))+' · '+esc(meta.title)+'</strong><span>'+esc(detail+(who?' · '+memberName(who):''))+'</span></div><span class="cleaning-history-date">'+esc(relativeDate(log._at))+'</span></div>';}).join('')+'</div>';}
  function overviewMarkup(data){var occurrences=activeOccurrences(data),today=todayIso(),attention=occurrences.filter(function(row){var date=occurrenceDate(row);return date&&date<=today;}),paused=pausedRoutines(data),completedWeek=recentLogs(data).filter(function(row){return row._at>=Date.now()-7*86400000&&text(row.status).toUpperCase()==='COMPLETED';}).length;return'<section class="cleaning-live-overview" data-cleaning-live-overview><div class="cleaning-overview-hero"><p>Huisstatus</p><h2>'+(attention.length?'Er is '+attention.length+'× schoonmaakwerk dat aandacht vraagt':'Alles loopt volgens jullie planning')+'</h2><span>'+(paused.length?paused.length+' '+(paused.length===1?'routine staat':'routines staan')+' tijdelijk gepauzeerd. ':'')+'De status komt rechtstreeks uit jullie actuele schoonmaakplanning.</span></div><div class="cleaning-overview-stats"><div class="cleaning-overview-stat'+(attention.length?' is-attention':'')+'"><strong>'+attention.length+'</strong><span>vandaag / verlopen</span></div><div class="cleaning-overview-stat"><strong>'+occurrences.length+'</strong><span>open beurten</span></div><div class="cleaning-overview-stat"><strong>'+completedWeek+'</strong><span>afgerond 7 dagen</span></div></div><div class="cleaning-overview-section"><div class="cleaning-overview-section-head"><strong>Recente geschiedenis</strong><span>laatste 8 gebeurtenissen</span></div>'+historyMarkup(data)+'</div></section>';}

  function occurrenceChecklistTitle(row){var list=Array.isArray(row&&row.checklist)?row.checklist:[];if(!list.length)return'Schoonmaakbeurt';if(list.length===1)return text(list[0].title)||'Schoonmaakbeurt';return list.length+' routines';}
  function plannedRoomsMarkup(data){var rooms=data.rooms||{},routines=data.routines||{},occurrences=activeOccurrences(data),cards=Object.keys(rooms).map(function(id){return Object.assign({id:id},rooms[id]||{});}).filter(function(room){return room&&room.active!==false;}).sort(function(a,b){var ao=Number(a.sortOrder),bo=Number(b.sortOrder);if(Number.isFinite(ao)&&Number.isFinite(bo)&&ao!==bo)return ao-bo;return Number(a.createdAt||0)-Number(b.createdAt||0);}).map(function(room){var rows=occurrences.filter(function(row){return text(row.roomId)===text(room.id);}).sort(function(a,b){return occurrenceDate(a).localeCompare(occurrenceDate(b));}).slice(0,4),paused=Object.keys(routines).map(function(id){return routines[id];}).filter(function(routine){return routine&&routine.active!==false&&text(routine.roomId)===text(room.id)&&routine.paused===true;}).length;var body=rows.length?'<div class="cleaning-planned-room-items">'+rows.map(function(row){var uid=Array.isArray(row.assignmentUids)?row.assignmentUids[0]:null,date=occurrenceDate(row);return'<div class="cleaning-planned-room-item"><div><strong>'+esc(occurrenceChecklistTitle(row))+'</strong><small>'+esc(memberName(uid))+' · '+esc(Number(row.estimatedMinutes)||0)+' min</small></div><span>'+esc(dueLabel(date))+'</span></div>';}).join('')+'</div>':'<div class="cleaning-overview-empty" style="margin-top:9px">Geen actieve schoonmaakbeurten gepland.</div>';return'<article class="cleaning-planned-room-card"><div class="cleaning-planned-room-head"><strong>'+esc(room.name||'Ruimte')+'</strong><span>'+rows.length+' gepland</span></div>'+body+(paused?'<span class="cleaning-planned-room-paused">⏸ '+paused+' '+(paused===1?'routine gepauzeerd':'routines gepauzeerd')+'</span>':'')+'</article>';});return'<div class="cleaning-planned-room-list" data-cleaning-planned-room-list>'+cards.join('')+'</div>';}

  function decorate(){state.queued=false;ensureStyle();var screen=document.getElementById('screen-cleaning');if(!screen)return;var panel=screen.querySelector('.cleaning-panel');if(!panel)return;var data=root(),overview=screen.querySelector('[data-cleaning-tab="overview"].is-active'),rooms=screen.querySelector('[data-cleaning-tab="rooms"].is-active'),planned=screen.querySelector('[data-cleaning-room-view="planned"].is-active');if(overview){var empty=panel.querySelector('.cleaning-empty-card');if(empty&&/Huisoverzicht/.test(empty.textContent||'')){var wrap=document.createElement('div');wrap.innerHTML=overviewMarkup(data);empty.replaceWith(wrap.firstChild);}else{var existing=panel.querySelector('[data-cleaning-live-overview]');if(existing){var holder=document.createElement('div');holder.innerHTML=overviewMarkup(data);existing.replaceWith(holder.firstChild);}}return;}if(rooms&&planned){var emptyPlanned=panel.querySelector('.cleaning-empty-card');if(emptyPlanned&&/Gepland per kamer/.test(emptyPlanned.textContent||'')){var container=document.createElement('div');container.innerHTML=plannedRoomsMarkup(data);emptyPlanned.replaceWith(container.firstChild);}else{var existingPlanned=panel.querySelector('[data-cleaning-planned-room-list]');if(existingPlanned){var next=document.createElement('div');next.innerHTML=plannedRoomsMarkup(data);existingPlanned.replaceWith(next.firstChild);}}}}
  function queue(){if(state.queued)return;state.queued=true;(window.requestAnimationFrame||function(callback){return setTimeout(callback,0);})(decorate);}
  function relevant(records){for(var i=0;i<records.length;i++){var nodes=records[i].addedNodes||[];for(var j=0;j<nodes.length;j++){var node=nodes[j];if(!node||node.nodeType!==1)continue;if(node.matches&&node.matches('[data-cleaning-live-overview],[data-cleaning-planned-room-list]'))continue;if(node.closest&&node.closest('[data-cleaning-live-overview],[data-cleaning-planned-room-list]'))continue;return true;}}return false;}
  function onRepository(event){state.repository=event&&event.detail||null;queue();}
  function start(){if(window.__cleaningOverviewExperienceStarted)return;window.__cleaningOverviewExperienceStarted=true;ensureStyle();try{var repo=window.CleaningHouseholdRepository;state.repository=repo&&repo.snapshot?repo.snapshot():null;}catch(error){}var target=document.getElementById('screen-cleaning')||document.documentElement;if(typeof MutationObserver!=='undefined'&&target){state.observer=new MutationObserver(function(records){if(relevant(records))queue();});state.observer.observe(target,{childList:true,subtree:true});}window.addEventListener('familyapp:cleaning-repository',onRepository);queue();}

  window.CleaningOverviewExperience={version:VERSION,start:start,_activeOccurrences:activeOccurrences,_recentLogs:recentLogs,_occurrenceDate:occurrenceDate};start();
})();
