'use strict';
// CLEANING V2.3 — contextual controls inside the existing Cleaning turn sheet.
// This module does not create a popup, listener, observer or canonical writer.
(function(){
  var VERSION='2.3.0',bound=false,busy=false,screenBound=false;
  function text(v){return String(v==null?'':v).trim();}
  function esc(v){return text(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function repo(){return window.CleaningHouseholdRepository||window.CleaningV2Repository||null;}
  function snap(){var r=repo();try{return r&&r.snapshot?r.snapshot():null;}catch(e){return null;}}
  function occurrence(id){var s=snap(),row=s&&s.data&&s.data.occurrences&&s.data.occurrences[id];return row?Object.assign({id:id},row):null;}
  function members(){try{var b=window.HouseholdIdentityFirebaseBridge,rows=b&&b.getMembers?b.getMembers():[];return(Array.isArray(rows)?rows:[]).filter(function(x){return x&&text(x.uid||x.id)&&text(x.status||'active').toLowerCase()==='active';});}catch(e){return[];}}
  function memberUid(row){return text(row&&(row.uid||row.id));}
  function memberName(row){return text(row&&(row.displayName||row.name))||'Gezinslid';}
  function avatarUrl(row){var raw=text(row&&(row.avatar||row.avatarUrl||row.photoURL||row.photoUrl||row.profilePhoto||row.image));return /^(https?:\/\/|\/|data:image\/)/i.test(raw)?raw:'';}
  function initials(row){var parts=memberName(row).split(/\s+/).filter(Boolean);return((parts[0]||'G').charAt(0)+(parts.length>1?parts[parts.length-1].charAt(0):'')).toUpperCase();}
  function avatar(row){var url=avatarUrl(row);return url?'<img src="'+esc(url)+'" alt="">':'<span>'+esc(initials(row))+'</span>';}
  function toast(m){if(window.showToast)window.showToast(m);}
  function defer(fn){if(typeof queueMicrotask==='function')queueMicrotask(fn);else Promise.resolve().then(fn);}
  function turnId(sheet){var anchor=sheet&&sheet.querySelector('[data-cv2-complete-all]');return text(anchor&&anchor.dataset.cv2CompleteAll);}
  function closed(row){var a=text(row&&row.status).toUpperCase(),b=text(row&&row.assignmentStatus).toUpperCase();return a==='COMPLETED'||b==='COMPLETED'||a==='SKIPPED'||b==='SKIPPED'||a==='CANCELLED';}
  function pending(row){var t=text(row&&row.transferRequest&&row.transferRequest.status).toUpperCase(),h=text(row&&row.helpRequest&&row.helpRequest.status).toUpperCase();return t==='PENDING'||t==='COUNTER_PROPOSED'||h==='PENDING';}
  function selectedUids(row){return(Array.isArray(row&&row.assignmentUids)?row.assignmentUids:[]).map(text).filter(Boolean);}
  function ensureStyle(){if(document.getElementById('cleaning-v23-controls-style'))return;var s=document.createElement('style');s.id='cleaning-v23-controls-style';s.textContent=''
    +'#cleaning-v2-sheet .cv23-adjust{margin:18px 0 8px;padding:14px;border:1px solid var(--c-border);border-radius:18px;background:var(--c-bg,var(--c-bg2))}'
    +'#cleaning-v2-sheet .cv23-adjust-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}'
    +'#cleaning-v2-sheet .cv23-adjust-head span{display:block;font-size:10.5px;font-weight:800;letter-spacing:.35px;text-transform:uppercase;color:var(--c-text2)}'
    +'#cleaning-v2-sheet .cv23-adjust-head strong{display:block;font-size:14px;color:var(--c-text);margin-top:2px}'
    +'#cleaning-v2-sheet .cv23-quick{display:grid;grid-template-columns:1fr 1fr;gap:8px}'
    +'#cleaning-v2-sheet .cv23-btn{min-height:42px;border-radius:12px;border:1px solid var(--c-border);background:var(--c-bg2);color:var(--c-text);font:inherit;font-size:12px;font-weight:800;padding:0 10px}'
    +'#cleaning-v2-sheet .cv23-btn.primary{background:#7c3aed;color:white;border-color:transparent}'
    +'#cleaning-v2-sheet .cv23-btn.warn{color:#a16207}'
    +'#cleaning-v2-sheet .cv23-form{display:none;margin-top:10px;padding-top:10px;border-top:1px solid var(--c-border);gap:10px}'
    +'#cleaning-v2-sheet .cv23-form.is-open{display:grid}'
    +'#cleaning-v2-sheet .cv23-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}'
    +'#cleaning-v2-sheet .cv23-form>label{display:grid;gap:5px;font-size:11px;font-weight:800;color:var(--c-text2)}'
    +'#cleaning-v2-sheet .cv23-form input[type="date"],#cleaning-v2-sheet .cv23-form input[type="time"]{box-sizing:border-box;width:100%;min-height:44px;border-radius:11px;border:1px solid var(--c-border);background:var(--c-bg2);color:var(--c-text);padding:0 10px;font:inherit}'
    +'#cleaning-v2-sheet .cv23-assignee-label{font-size:11px;font-weight:800;color:var(--c-text2);margin-top:2px}'
    +'#cleaning-v2-sheet .cv23-assignees{display:grid;grid-template-columns:1fr 1fr;gap:8px}'
    +'#cleaning-v2-sheet .cv23-person{display:flex;align-items:center;gap:9px;min-height:50px;border:1px solid var(--c-border);border-radius:13px;background:var(--c-bg2);padding:7px 9px;cursor:pointer;user-select:none}'
    +'#cleaning-v2-sheet .cv23-person input{position:absolute;opacity:0;pointer-events:none}'
    +'#cleaning-v2-sheet .cv23-person-avatar{width:34px;height:34px;border-radius:50%;overflow:hidden;display:grid;place-items:center;flex:0 0 34px;background:rgba(124,58,237,.12);color:var(--c-accent,#7c3aed);font-size:11px;font-weight:900}'
    +'#cleaning-v2-sheet .cv23-person-avatar img{width:100%;height:100%;object-fit:cover}'
    +'#cleaning-v2-sheet .cv23-person-name{min-width:0;flex:1;color:var(--c-text);font-size:12px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}'
    +'#cleaning-v2-sheet .cv23-person-check{width:20px;height:20px;border-radius:50%;display:grid;place-items:center;border:1.5px solid var(--c-border);color:transparent;font-size:12px;font-weight:900}'
    +'#cleaning-v2-sheet .cv23-person:has(input:checked){border-color:#4d9a69;background:rgba(54,126,78,.09)}'
    +'#cleaning-v2-sheet .cv23-person:has(input:checked) .cv23-person-check{background:#357d4d;border-color:#357d4d;color:white}'
    +'#cleaning-v2-sheet .cv23-note{font-size:11px;line-height:1.4;color:var(--c-text2);margin:8px 0 0}'
    +'#cleaning-v2-sheet .cv23-adjust.is-busy{opacity:.65;pointer-events:none}'
    +'#cleaning-v2-sheet .fav-person-card[data-cv23-assignees-open]{cursor:pointer;position:relative;transition:transform .08s ease,box-shadow .12s ease}'
    +'#cleaning-v2-sheet .fav-person-card[data-cv23-assignees-open]:active{transform:scale(.99)}'
    +'#cleaning-v2-sheet .cv23-avatar-stack{display:flex;align-items:center;min-width:42px}'
    +'#cleaning-v2-sheet .cv23-avatar-stack .fav-avatar{width:38px;height:38px;flex:0 0 38px;border:2px solid var(--c-bg,var(--c-bg2));margin-left:-9px}'
    +'#cleaning-v2-sheet .cv23-avatar-stack .fav-avatar:first-child{margin-left:0}'
    +'#cleaning-v2-sheet .cv23-person-card-copy{min-width:0;flex:1}'
    +'#cleaning-v2-sheet .cv23-person-card-copy strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}'
    +'#cleaning-v2-sheet .cv23-person-card-edit{color:var(--c-text2);font-size:18px;font-weight:900}'
    +'[data-theme*="dark"] #cleaning-v2-sheet .cv23-btn.primary{background:#d8b552;color:#241608}'
    +'[data-theme*="dark"] #cleaning-v2-sheet .cv23-person:has(input:checked){border-color:#75ad84;background:rgba(77,141,94,.13)}'
    +'@media(max-width:390px){#cleaning-v2-sheet .cv23-quick,#cleaning-v2-sheet .cv23-grid,#cleaning-v2-sheet .cv23-assignees{grid-template-columns:1fr}}';document.head.appendChild(s);}
  function personOptions(row){var assigned=selectedUids(row);return members().map(function(m){var uid=memberUid(m),checked=assigned.indexOf(uid)>=0?' checked':'';return'<label class="cv23-person"><input type="checkbox" name="assigneeUids" value="'+esc(uid)+'"'+checked+'><span class="cv23-person-avatar">'+avatar(m)+'</span><span class="cv23-person-name">'+esc(memberName(m))+'</span><span class="cv23-person-check">✓</span></label>';}).join('');}
  function markup(row){if(closed(row))return'';var note=pending(row)?'<p class="cv23-note">Er staat een overdracht- of hulpverzoek open. Rond dat eerst af voordat je deze beurt wijzigt.</p>':'';return'<section class="cv23-adjust" data-cv23-root data-occurrence-id="'+esc(row.id)+'"><div class="cv23-adjust-head"><div><span>Deze schoonmaakbeurt</span><strong>Planning aanpassen</strong></div></div><div class="cv23-quick"><button type="button" class="cv23-btn" data-cv23-later'+(pending(row)?' disabled':'')+'>Later deze week</button><button type="button" class="cv23-btn" data-cv23-edit'+(pending(row)?' disabled':'')+'>Moment / personen</button><button type="button" class="cv23-btn" data-cv23-carry'+(pending(row)?' disabled':'')+'>Doorschuiven</button><button type="button" class="cv23-btn warn" data-cv23-skip'+(pending(row)?' disabled':'')+'>Deze keer overslaan</button></div>'+note+'<form class="cv23-form" data-cv23-form><div class="cv23-grid"><label>Dag<input type="date" name="date" value="'+esc(text(row.scheduledDate))+'" required></label><label>Tijd<input type="time" name="time" value="'+esc(text(row.scheduledTime))+'"></label></div><div class="cv23-assignee-label">Toegewezen personen</div><div class="cv23-assignees">'+personOptions(row)+'</div><button class="cv23-btn primary" type="submit">Wijziging opslaan</button></form></section>';}
  function enhancePersonCard(row){var sheet=document.getElementById('cleaning-v2-sheet'),card=sheet&&sheet.querySelector('.fav-person-card');if(!card||!row)return;var ids=selectedUids(row),lookup={};members().forEach(function(m){lookup[memberUid(m)]=m;});var selected=ids.map(function(id){return lookup[id];}).filter(Boolean),names=selected.map(memberName);card.setAttribute('data-cv23-assignees-open','1');card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label','Toegewezen personen wijzigen');card.innerHTML='<div class="cv23-avatar-stack">'+selected.slice(0,3).map(function(m){return'<div class="fav-avatar">'+avatar(m)+'</div>';}).join('')+'</div><div class="cv23-person-card-copy"><small>'+(ids.length===1?'Toegewezen persoon':'Toegewezen personen')+'</small><strong>'+esc(names.length?names.join(', '):'Kies gezinslid')+'</strong></div><span class="cv23-person-card-edit">›</span>';}
  function render(){var sheet=document.getElementById('cleaning-v2-sheet');if(!sheet||!sheet.classList.contains('is-open'))return;var id=turnId(sheet),existing=sheet.querySelector('[data-cv23-root]');if(!id){if(existing)existing.remove();return;}var row=occurrence(id);if(!row){if(existing)existing.remove();return;}enhancePersonCard(row);var host=sheet.querySelector('[data-cv2-sheet-body]'),collab=host&&host.querySelector('.cc21-turn'),anchor=host&&host.querySelector('.cv2-sheet-actions');if(!host||!anchor)return;var wasOpen=existing&&existing.querySelector('[data-cv23-form].is-open'),html=markup(row);if(!html){if(existing)existing.remove();return;}var holder=document.createElement('div');holder.innerHTML=html;var fresh=holder.firstElementChild;if(wasOpen){var form=fresh.querySelector('[data-cv23-form]');if(form)form.classList.add('is-open');}if(existing)existing.replaceWith(fresh);else if(collab)host.insertBefore(fresh,collab);else anchor.insertAdjacentElement('afterend',fresh);}
  function refreshDetail(id){var detail=window.CleaningDetailVisualV221;if(detail&&typeof detail.renderTurn==='function')detail.renderTurn(id);defer(render);}
  function run(root,id,promise,success){if(busy)return;busy=true;root.classList.add('is-busy');Promise.resolve(promise).then(function(){toast(success);refreshDetail(id);}).catch(function(error){var c=window.CleaningOccurrenceCommandsV23;toast(c&&c.userMessage?c.userMessage(error):text(error&&error.message));}).finally(function(){busy=false;if(root&&root.isConnected)root.classList.remove('is-busy');});}
  function openAssignmentForm(sheet){var root=sheet&&sheet.querySelector('[data-cv23-root]'),form=root&&root.querySelector('[data-cv23-form]');if(!form)return;form.classList.add('is-open');try{form.scrollIntoView({behavior:'smooth',block:'nearest'});}catch(e){form.scrollIntoView();}}
  function click(event){var sheet=document.getElementById('cleaning-v2-sheet'),personCard=event.target&&event.target.closest?event.target.closest('[data-cv23-assignees-open]'):null;if(personCard){openAssignmentForm(sheet);return;}var button=event.target&&event.target.closest?event.target.closest('[data-cv23-later],[data-cv23-edit],[data-cv23-carry],[data-cv23-skip]'):null;if(!button)return;var root=button.closest('[data-cv23-root]'),id=text(root&&root.dataset.occurrenceId),r=repo();if(!root||!id||!r)return;if(button.hasAttribute('data-cv23-edit')){var form=root.querySelector('[data-cv23-form]');if(form)form.classList.toggle('is-open');return;}if(button.hasAttribute('data-cv23-later')){run(root,id,r.laterThisWeekV23(id),'Beurt verplaatst ✓');return;}if(button.hasAttribute('data-cv23-carry')){if(!confirm('Niet-afgeronde onderdelen doorschuiven naar de volgende cyclus?'))return;run(root,id,r.finalizeIncompleteV23(id,'CARRY_FORWARD'),'Resterende onderdelen doorgeschoven ✓');return;}if(button.hasAttribute('data-cv23-skip')){if(!confirm('Deze schoonmaakbeurt deze keer overslaan?'))return;run(root,id,r.finalizeIncompleteV23(id,'SKIP'),'Beurt overgeslagen');}}
  function keydown(event){var card=event.target&&event.target.closest?event.target.closest('[data-cv23-assignees-open]'):null;if(!card||(event.key!=='Enter'&&event.key!==' '))return;event.preventDefault();openAssignmentForm(document.getElementById('cleaning-v2-sheet'));}
  function submit(event){var form=event.target&&event.target.closest?event.target.closest('[data-cv23-form]'):null;if(!form)return;event.preventDefault();var root=form.closest('[data-cv23-root]'),id=text(root&&root.dataset.occurrenceId),r=repo(),data=new FormData(form),assignees=data.getAll('assigneeUids').map(text).filter(Boolean);if(!root||!id||!r)return;if(!assignees.length){toast('Kies minimaal één gezinslid.');return;}run(root,id,r.adjustOccurrenceV23(id,{date:data.get('date'),time:data.get('time'),assigneeUids:assignees}),'Beurt bijgewerkt ✓');}
  function bind(){if(bound)return;var sheet=document.getElementById('cleaning-v2-sheet');if(!sheet)return;bound=true;ensureStyle();sheet.addEventListener('click',click);sheet.addEventListener('keydown',keydown);sheet.addEventListener('submit',submit);var original=window.CleaningOccurrenceCommandsV23;if(original&&original.install)original.install();var rerender=function(){defer(render);};sheet.addEventListener('click',rerender,true);var screen=document.getElementById('screen-cleaning');if(screen&&!screenBound){screenBound=true;screen.addEventListener('click',function(event){if(event.target&&event.target.closest&&event.target.closest('[data-cv2-turn]'))defer(render);});}render();}
  function boot(){bind();if(!bound&&document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});}
  window.CleaningOccurrenceControlsV23=Object.freeze({version:VERSION,render:render,bind:bind});boot();
})();
export const CLEANING_OCCURRENCE_CONTROLS_V23_VERSION='2.3.0';
