'use strict';
// ============================================================
// CLEANING ROOM WORKFLOW UX v0.2.0
// Presentation-only simplification around the canonical Cleaning screen.
// - room type comes first; standard room names are optional
// - an omitted standard name resolves to the room type label
// - duplicate unnamed standard rooms get a readable numeric suffix
// - routine actions collapse behind one compact overflow menu
// Existing edit/assign/pause/remove handlers stay canonical and are invoked
// through hidden proxy controls instead of being reimplemented here.
// ============================================================
(function(){
  if(window.CleaningRoomWorkflowUx)return;

  var VERSION='0.2.0';
  var LABELS={
    'living-room':'Woonkamer',kitchen:'Keuken',bathroom:'Badkamer',toilet:'Toilet',bedroom:'Slaapkamer',
    'kids-room':'Kinderkamer',hall:'Hal',laundry:'Wasruimte',outdoor:'Balkon / tuin',custom:'Eigen ruimte'
  };
  var state={observer:null,queued:false,openMenu:null,lastCreateForm:null};

  function text(value){return String(value==null?'':value).trim();}
  function canonical(value){return text(value).toLocaleLowerCase('nl-NL').replace(/\s+/g,' ');}
  function repositoryRoot(){try{var repo=window.CleaningHouseholdRepository,snap=repo&&repo.snapshot?repo.snapshot():null;return snap&&snap.data||{};}catch(error){return{};}}
  function activeRooms(){var raw=repositoryRoot().rooms||{};return Object.keys(raw).map(function(id){return Object.assign({id:id},raw[id]||{});}).filter(function(row){return row&&row.active!==false;});}
  function roomLabel(type){return LABELS[text(type)]||LABELS.custom;}
  function defaultRoomName(type,rooms){
    type=text(type)||'custom';if(type==='custom')return'';var base=roomLabel(type),taken={};(Array.isArray(rooms)?rooms:[]).forEach(function(row){if(row&&row.active!==false)taken[canonical(row.name)]=true;});if(!taken[canonical(base)])return base;var index=2;while(taken[canonical(base+' '+index)])index++;return base+' '+index;
  }

  function ensureStyle(){
    if(document.getElementById('cleaning-room-workflow-ux-style'))return;var style=document.createElement('style');style.id='cleaning-room-workflow-ux-style';style.textContent='\n'
      +'#screen-cleaning .cleaning-room-name-help{display:block;margin-top:5px;color:var(--cleaning-muted);font-size:9px;font-weight:750;line-height:1.4}\n'
      +'#screen-cleaning .cleaning-room-toggle{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:4px;padding:4px;border:1px solid var(--color-border,var(--cleaning-border));border-radius:16px;background:var(--surface-2,var(--cleaning-surface));box-shadow:var(--shadow-soft);backdrop-filter:blur(var(--surface-glass-blur,18px));-webkit-backdrop-filter:blur(var(--surface-glass-blur,18px))}#screen-cleaning .cleaning-room-toggle-btn{min-height:40px;border:0;border-radius:12px;background:transparent;color:var(--color-muted,var(--cleaning-muted));font:inherit;font-size:11px;font-weight:850;transition:background .18s ease,color .18s ease,box-shadow .18s ease}#screen-cleaning .cleaning-room-toggle-btn.is-active{background:var(--surface-1,var(--cleaning-surface));color:var(--cleaning-text);box-shadow:0 5px 18px rgba(19,27,38,.09)}\n'
      +'#screen-cleaning .cleaning-room-grid{display:grid;gap:14px;margin-top:12px}#screen-cleaning .cleaning-room-card{--room-accent:var(--color-primary,var(--cleaning-accent));position:relative;overflow:hidden;border:1px solid color-mix(in srgb,var(--room-accent) 17%,var(--color-border,var(--cleaning-border)));border-radius:var(--radius-lg,22px);background:linear-gradient(145deg,color-mix(in srgb,var(--room-accent) 7%,var(--surface-2,var(--cleaning-surface))),var(--surface-2,var(--cleaning-surface)) 48%);box-shadow:var(--shadow-card);backdrop-filter:blur(var(--surface-glass-blur,18px));-webkit-backdrop-filter:blur(var(--surface-glass-blur,18px));transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease}#screen-cleaning .cleaning-room-card:before{content:"";position:absolute;right:-56px;top:-72px;width:170px;height:170px;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--room-accent) 15%,transparent),transparent 67%);pointer-events:none}#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="kitchen"]{--room-accent:#d99436}#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="bathroom"],#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="toilet"]{--room-accent:#3a9cc7}#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="bedroom"],#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="kids-room"]{--room-accent:#8c70cf}#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="outdoor"]{--room-accent:#4a9b69}#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="laundry"]{--room-accent:#5d8fb8}#screen-cleaning .cleaning-room-card[data-cleaning-room-visual="hall"]{--room-accent:#9b765c}#screen-cleaning .cleaning-room-card.is-expanded{border-color:color-mix(in srgb,var(--room-accent) 28%,var(--color-border,var(--cleaning-border)));box-shadow:var(--shadow-float,var(--shadow-card))}\n'
      +'#screen-cleaning .cleaning-room-card-main{position:relative;z-index:1;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;min-height:82px;padding:14px 14px 13px}#screen-cleaning .cleaning-room-card-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:15px;background:linear-gradient(145deg,color-mix(in srgb,var(--room-accent) 18%,var(--surface-1,var(--cleaning-surface))),color-mix(in srgb,var(--room-accent) 7%,var(--surface-3,var(--cleaning-surface))));border:1px solid color-mix(in srgb,var(--room-accent) 20%,transparent);box-shadow:0 8px 20px color-mix(in srgb,var(--room-accent) 12%,transparent);font-size:22px}#screen-cleaning .cleaning-room-card-copy{min-width:0}#screen-cleaning .cleaning-room-card-copy h3{margin:0;font-size:15px;line-height:1.18;letter-spacing:-.02em;font-weight:900}#screen-cleaning .cleaning-room-card-copy p{margin:5px 0 0;color:var(--color-muted,var(--cleaning-muted));font-size:9.5px;line-height:1.3;font-weight:730}#screen-cleaning .cleaning-room-card-actions{display:flex;flex-direction:column;align-items:flex-end;gap:7px}#screen-cleaning .cleaning-room-card-status{display:inline-flex;align-items:center;gap:5px;min-height:24px;padding:0 8px;border-radius:999px;background:color-mix(in srgb,var(--status-planned,#36b76a) 10%,var(--surface-1,var(--cleaning-surface)));border:1px solid color-mix(in srgb,var(--status-planned,#36b76a) 18%,transparent);color:var(--status-planned,#2f995b);font-size:8px;font-weight:900;text-transform:uppercase;letter-spacing:.045em}#screen-cleaning .cleaning-room-card-status:before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor}#screen-cleaning .cleaning-room-edit-button{min-height:30px;padding:0 9px;border:1px solid var(--color-border,var(--cleaning-border));border-radius:10px;background:var(--surface-1,var(--cleaning-surface));color:var(--cleaning-text);font:inherit;font-size:9px;font-weight:850;box-shadow:var(--shadow-soft)}\n'
      +'#screen-cleaning .cleaning-room-card .cleaning-routine-section,#screen-cleaning .cleaning-room-card .cleaning-routine-empty{position:relative;z-index:1;margin:0 12px 12px;padding:11px;border:1px solid color-mix(in srgb,var(--room-accent) 9%,var(--color-border,var(--cleaning-border)));border-radius:15px;background:color-mix(in srgb,var(--surface-1,var(--cleaning-surface)) 94%,var(--room-accent) 6%)}#screen-cleaning .cleaning-routine-section-head{display:flex;align-items:center;justify-content:space-between;gap:9px;margin-bottom:8px;color:var(--color-muted,var(--cleaning-muted));font-size:9px;font-weight:850}#screen-cleaning .cleaning-routine-section-head>span:first-child{color:var(--cleaning-text);font-size:10px}#screen-cleaning .cleaning-routine-list{display:grid;gap:7px}#screen-cleaning .cleaning-routine-item{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:9px;min-height:54px;padding:9px;border:1px solid color-mix(in srgb,var(--room-accent) 8%,var(--color-border,var(--cleaning-border)));border-radius:13px;background:var(--surface-2,var(--cleaning-surface));box-shadow:0 4px 14px rgba(16,25,35,.045)}#screen-cleaning .cleaning-routine-dot{width:9px;height:9px;border-radius:50%;background:var(--room-accent);box-shadow:0 0 0 4px color-mix(in srgb,var(--room-accent) 10%,transparent)}#screen-cleaning .cleaning-routine-copy{min-width:0}#screen-cleaning .cleaning-routine-copy strong{display:block;font-size:10.5px;line-height:1.25;font-weight:850}#screen-cleaning .cleaning-routine-copy span{display:block;margin-top:3px;color:var(--color-muted,var(--cleaning-muted));font-size:8.5px;line-height:1.25}#screen-cleaning .cleaning-priority-badge{min-height:22px;display:inline-flex;align-items:center;padding:0 7px;border-radius:999px;background:color-mix(in srgb,var(--room-accent) 8%,var(--surface-1));border:1px solid color-mix(in srgb,var(--room-accent) 13%,transparent);color:var(--color-muted,var(--cleaning-muted));font-size:7.5px;font-weight:900;text-transform:uppercase;letter-spacing:.04em}#screen-cleaning .cleaning-add-routine-button{min-height:38px;border:1px solid color-mix(in srgb,var(--room-accent) 15%,var(--color-border,var(--cleaning-border)));border-radius:11px;padding:0 10px;background:color-mix(in srgb,var(--room-accent) 6%,var(--surface-1,var(--cleaning-surface)));color:var(--room-accent);font:inherit;font-size:9px;font-weight:850;text-align:left}#screen-cleaning .cleaning-routine-empty{display:flex;align-items:center;justify-content:space-between;gap:10px;color:var(--cleaning-muted);font-size:9px;font-weight:800}\n'
      +'#screen-cleaning .cleaning-room-form{position:relative;overflow:hidden;margin:12px 0 14px;padding:15px;border:1px solid color-mix(in srgb,var(--color-primary,var(--cleaning-accent)) 20%,var(--color-border,var(--cleaning-border)));border-radius:var(--radius-lg,22px);background:linear-gradient(145deg,color-mix(in srgb,var(--color-primary,var(--cleaning-accent)) 7%,var(--surface-2,var(--cleaning-surface))),var(--surface-2,var(--cleaning-surface)));box-shadow:var(--shadow-float,var(--shadow-card))}#screen-cleaning .cleaning-room-form:before{content:"";position:absolute;right:-45px;top:-60px;width:145px;height:145px;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--color-primary,var(--cleaning-accent)) 14%,transparent),transparent 67%);pointer-events:none}#screen-cleaning .cleaning-form-heading,#screen-cleaning .cleaning-field,#screen-cleaning .cleaning-routine-fields,#screen-cleaning .cleaning-form-actions,#screen-cleaning .cleaning-room-danger{position:relative;z-index:1}#screen-cleaning .cleaning-field input,#screen-cleaning .cleaning-field select{border-radius:12px!important;background:var(--surface-1,var(--cleaning-surface))!important;border-color:var(--color-border,var(--cleaning-border))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.06)}\n'
      +'#screen-cleaning .cleaning-routine-item-actions{position:relative;display:flex;align-items:center;gap:7px}\n'
      +'#screen-cleaning .cleaning-routine-item-actions>.cleaning-routine-edit-button,#screen-cleaning .cleaning-routine-item-actions>.cleaning-routine-assign-button,#screen-cleaning .cleaning-routine-item-actions>.cleaning-routine-remove-button,#screen-cleaning .cleaning-routine-item-actions>.cleaning-routine-pause-button{display:none!important}\n'
      +'#screen-cleaning .cleaning-routine-more{width:38px;height:38px;display:grid;place-items:center;border:1px solid var(--color-border,var(--cleaning-border));border-radius:11px;background:var(--surface-1,var(--cleaning-surface));color:var(--cleaning-text);font:inherit;font-size:18px;font-weight:950;line-height:1;cursor:pointer;touch-action:manipulation;box-shadow:var(--shadow-soft)}\n'
      +'#screen-cleaning .cleaning-routine-more[aria-expanded="true"]{background:color-mix(in srgb,var(--room-accent,var(--cleaning-accent)) 10%,var(--cleaning-surface));border-color:color-mix(in srgb,var(--room-accent,var(--cleaning-accent)) 35%,var(--cleaning-border));color:var(--room-accent,var(--cleaning-accent))}\n'
      +'#screen-cleaning .cleaning-routine-more-menu{position:absolute;right:0;top:44px;z-index:25;min-width:184px;padding:6px;border:1px solid var(--color-border,var(--cleaning-border));border-radius:14px;background:var(--surface-3,var(--cleaning-surface-strong,var(--cleaning-surface)));box-shadow:0 18px 42px rgba(20,24,32,.20);display:grid;gap:3px;backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}\n'
      +'#screen-cleaning .cleaning-routine-menu-action{min-height:42px;width:100%;border:0;border-radius:10px;padding:0 11px;background:transparent;color:var(--cleaning-text);font:inherit;font-size:11px;font-weight:850;text-align:left;cursor:pointer}\n'
      +'#screen-cleaning .cleaning-routine-menu-action:active{background:color-mix(in srgb,var(--cleaning-accent) 9%,var(--cleaning-surface))}\n'
      +'#screen-cleaning .cleaning-routine-menu-action.is-pause{color:var(--cleaning-accent)}\n'
      +'#screen-cleaning .cleaning-routine-menu-action.is-danger{color:#b32636}#screen-cleaning .cleaning-routine-menu-action.is-confirm{background:#b32636;color:#fff}\n'
      +'[data-theme*="dark"] #screen-cleaning .cleaning-routine-menu-action.is-danger:not(.is-confirm){color:#ff9ba6}[data-theme*="dark"] #screen-cleaning .cleaning-room-card{box-shadow:0 16px 42px rgba(0,0,0,.22)}[data-theme*="dark"] #screen-cleaning .cleaning-room-toggle-btn.is-active{box-shadow:0 6px 20px rgba(0,0,0,.24)}\n'
      +'@media(max-width:370px){#screen-cleaning .cleaning-room-card-main{grid-template-columns:auto minmax(0,1fr);gap:10px}#screen-cleaning .cleaning-room-card-actions{grid-column:1/-1;flex-direction:row;align-items:center;justify-content:space-between}#screen-cleaning .cleaning-room-card-icon{width:44px;height:44px}#screen-cleaning .cleaning-routine-item{grid-template-columns:auto minmax(0,1fr)}#screen-cleaning .cleaning-routine-item-actions{grid-column:2;justify-self:end}}@media(prefers-reduced-motion:reduce){#screen-cleaning .cleaning-room-card,#screen-cleaning .cleaning-room-toggle-btn{transition:none}}\n';document.head.appendChild(style);
  }

  function decorateRoomForm(){
    var form=document.querySelector('#screen-cleaning [data-cleaning-room-form]');if(!form)return;var select=form.querySelector('[data-cleaning-room-type]'),name=form.querySelector('[data-cleaning-room-name]');if(!select||!name)return;var typeField=select.closest('.cleaning-field'),nameField=name.closest('.cleaning-field');
    if(typeField&&nameField&&typeField.parentNode===form&&nameField.parentNode===form&&typeField.nextElementSibling!==nameField)form.insertBefore(typeField,nameField);
    var type=text(select.value)||'custom',label=nameField&&nameField.querySelector('span'),help=nameField&&nameField.querySelector('[data-cleaning-room-name-help]');
    if(label)label.textContent=type==='custom'?'Naam':'Naam (optioneel)';name.placeholder=type==='custom'?'Bijv. Kantoor of Hobbykamer':'Optioneel · bijv. '+roomLabel(type)+' boven';
    if(nameField&&!help){help=document.createElement('small');help.className='cleaning-room-name-help';help.setAttribute('data-cleaning-room-name-help','1');nameField.appendChild(help);}
    if(help)help.textContent=type==='custom'?'Bij een Eigen ruimte is een naam nodig.':'Laat leeg en we gebruiken automatisch “'+roomLabel(type)+'”.';
    var editing=!!form.querySelector('[data-cleaning-room-delete-open],[data-cleaning-room-delete-confirm]');
    if(!editing&&state.lastCreateForm!==form){state.lastCreateForm=form;window.setTimeout(function(){try{if(document.activeElement===name||!document.activeElement||document.activeElement===document.body)select.focus();}catch(error){}},0);}
  }

  function decorateRoomCards(){
    var rooms=activeRooms(),byId={};rooms.forEach(function(room){byId[text(room.id)]=room;});
    var cards=document.querySelectorAll('#screen-cleaning .cleaning-room-card[data-cleaning-room-id]');
    for(var i=0;i<cards.length;i++){
      var card=cards[i],id=text(card.getAttribute('data-cleaning-room-id')),room=byId[id];if(!room)continue;
      var type=text(room.type)||'custom';if(card.getAttribute('data-cleaning-room-visual')!==type)card.setAttribute('data-cleaning-room-visual',type);
    }
  }

  function originalAction(item,action){
    if(!item)return null;
    if(action==='edit')return item.querySelector('.cleaning-routine-item-actions>[data-cleaning-routine-edit]');
    if(action==='assign')return item.querySelector('.cleaning-routine-item-actions>[data-cleaning-routine-assign]');
    if(action==='pause')return item.querySelector('.cleaning-routine-item-actions>[data-cleaning-routine-pause]');
    if(action==='remove')return item.querySelector('.cleaning-routine-item-actions>[data-cleaning-routine-remove]');
    return null;
  }
  function menuMarkup(item,routineId){
    var assign=originalAction(item,'assign'),pause=originalAction(item,'pause'),remove=originalAction(item,'remove'),confirming=!!(remove&&remove.classList&&remove.classList.contains('is-confirm')),busy=!!(remove&&remove.disabled),parts=[];
    parts.push('<button type="button" class="cleaning-routine-menu-action" data-cleaning-routine-menu-action="edit" data-cleaning-routine-menu-id="'+routineId+'">Bewerken</button>');
    if(assign)parts.push('<button type="button" class="cleaning-routine-menu-action" data-cleaning-routine-menu-action="assign" data-cleaning-routine-menu-id="'+routineId+'">Toewijzen</button>');
    if(pause)parts.push('<button type="button" class="cleaning-routine-menu-action is-pause" data-cleaning-routine-menu-action="pause" data-cleaning-routine-menu-id="'+routineId+'">'+(text(pause.textContent)||'Pauzeren')+'</button>');
    if(remove)parts.push('<button type="button" class="cleaning-routine-menu-action is-danger'+(confirming?' is-confirm':'')+'" data-cleaning-routine-menu-action="remove" data-cleaning-routine-menu-id="'+routineId+'"'+(busy?' disabled':'')+'>'+(busy?'Verwijderen…':confirming?'Tik nogmaals om te verwijderen':'Verwijderen')+'</button>');
    return parts.join('');
  }
  function decorateRoutineActions(){
    var edits=document.querySelectorAll('#screen-cleaning .cleaning-routine-item [data-cleaning-routine-edit]');for(var i=0;i<edits.length;i++){var edit=edits[i],routineId=text(edit.getAttribute('data-cleaning-routine-edit')),item=edit.closest('.cleaning-routine-item'),actions=item&&item.querySelector('.cleaning-routine-item-actions');if(!routineId||!actions)continue;var more=actions.querySelector('[data-cleaning-routine-more="'+routineId+'"]');if(!more){more=document.createElement('button');more.type='button';more.className='cleaning-routine-more';more.setAttribute('data-cleaning-routine-more',routineId);more.setAttribute('aria-label','Routine-acties');actions.appendChild(more);}var open=state.openMenu===routineId;more.textContent='•••';more.setAttribute('aria-expanded',open?'true':'false');var menu=actions.querySelector('[data-cleaning-routine-more-menu="'+routineId+'"]');if(!open){if(menu)menu.remove();continue;}var markup=menuMarkup(item,routineId),signature=markup;if(!menu){menu=document.createElement('div');menu.className='cleaning-routine-more-menu';menu.setAttribute('data-cleaning-routine-more-menu',routineId);menu.setAttribute('role','menu');actions.appendChild(menu);}if(menu.getAttribute('data-signature')!==signature){menu.setAttribute('data-signature',signature);menu.innerHTML=markup;}}
  }

  function decorate(){state.queued=false;ensureStyle();decorateRoomForm();decorateRoomCards();decorateRoutineActions();}
  function queue(){if(state.queued)return;state.queued=true;(window.requestAnimationFrame||function(callback){return window.setTimeout(callback,0);})(decorate);}
  function prepareOptionalName(form){
    if(!form||!form.matches||!form.matches('[data-cleaning-room-form]'))return;var select=form.querySelector('[data-cleaning-room-type]'),name=form.querySelector('[data-cleaning-room-name]');if(!select||!name||text(name.value))return;var type=text(select.value)||'custom';if(type==='custom')return;var generated=defaultRoomName(type,activeRooms());name.value=generated;try{name.dispatchEvent(new Event('input',{bubbles:true}));}catch(error){var event=document.createEvent&&document.createEvent('Event');if(event){event.initEvent('input',true,true);name.dispatchEvent(event);}}
  }

  function onSubmit(event){var form=event.target;if(form&&form.matches&&form.matches('[data-cleaning-room-form]'))prepareOptionalName(form);}
  function onChange(event){var target=event.target;if(target&&target.matches&&target.matches('[data-cleaning-room-type]'))window.setTimeout(queue,0);}
  function onClick(event){
    var target=event.target,closest=target&&target.closest?target.closest.bind(target):null;if(!closest)return;var more=closest('[data-cleaning-routine-more]');if(more){event.preventDefault();event.stopPropagation();var id=text(more.getAttribute('data-cleaning-routine-more'));state.openMenu=state.openMenu===id?null:id;queue();return;}
    var proxy=closest('[data-cleaning-routine-menu-action][data-cleaning-routine-menu-id]');if(proxy){event.preventDefault();event.stopPropagation();var action=text(proxy.getAttribute('data-cleaning-routine-menu-action')),id=text(proxy.getAttribute('data-cleaning-routine-menu-id')),item=proxy.closest('.cleaning-routine-item'),original=originalAction(item,action);if(original&&!original.disabled){if(action!=='remove')state.openMenu=null;original.click();if(action==='remove'){state.openMenu=id;window.setTimeout(queue,0);}else queue();}return;}
    if(state.openMenu&&!closest('[data-cleaning-routine-more-menu]')){state.openMenu=null;queue();}
  }

  function start(){
    if(window.__cleaningRoomWorkflowUxStarted)return;window.__cleaningRoomWorkflowUxStarted=true;ensureStyle();document.addEventListener('submit',onSubmit,true);document.addEventListener('change',onChange,true);document.addEventListener('click',onClick,true);var target=document.getElementById('screen-cleaning')||document.documentElement;if(typeof MutationObserver!=='undefined'&&target){state.observer=new MutationObserver(queue);state.observer.observe(target,{childList:true,subtree:true});}window.addEventListener('familyapp:cleaning-repository',queue);queue();
  }

  window.CleaningRoomWorkflowUx={version:VERSION,start:start,_roomLabel:roomLabel,_defaultRoomName:defaultRoomName};start();
})();