'use strict';
import './cleaningHistoryContract.js?v=1';

// ============================================================
// CLEANING HISTORY V2.2
// Lightweight companion to the accepted Cleaning V2 screen.
// - same CleaningHouseholdRepository subscription (no second Firebase listener)
// - no MutationObserver, polling or separate popup owner
// - history is derived from canonical completionLogs
// - attention/reminder is in-module only; no notification/push loop
// - only newly observed completion logs are projected to HouseholdActivity
// ============================================================
const VERSION='2.2.0';
const state={repo:null,unsubscribe:null,snapshot:null,screen:null,historyActive:false,enhanceQueued:false,householdId:'',seen:new Set(),inFlight:new Set()};

function text(value){return String(value==null?'':value).trim();}
function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function contract(){return window.CleaningHistoryContract||null;}
function context(){try{return window.HouseholdContext&&typeof window.HouseholdContext.snapshot==='function'?window.HouseholdContext.snapshot():null;}catch(error){return null;}}
function memberName(uid){uid=text(uid);if(!uid)return'Gezinslid';try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&typeof bridge.getMembers==='function'?bridge.getMembers():[],row=(Array.isArray(rows)?rows:[]).find(function(item){return text(item&&(item.uid||item.id))===uid;});return text(row&&(row.displayName||row.name))||'Gezinslid';}catch(error){return'Gezinslid';}}
function formatWhen(value){var timestamp=Number(value)||0;if(!timestamp)return'Nog nooit';var date=new Date(timestamp),today=new Date();today.setHours(0,0,0,0);var day=new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime(),diff=Math.round((day-today.getTime())/86400000);if(diff===0)return'Vandaag, '+date.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});if(diff===-1)return'Gisteren, '+date.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});return date.toLocaleDateString('nl-NL',{day:'numeric',month:'short',year:date.getFullYear()!==today.getFullYear()?'numeric':undefined});}

function ensureStyle(){if(document.getElementById('cleaning-history-v22-style'))return;var style=document.createElement('style');style.id='cleaning-history-v22-style';style.textContent=''
  +'#screen-cleaning .ch22-hidden{display:none!important}\n'
  +'#screen-cleaning .ch22-attention{margin:12px 0 0;padding:12px 13px;border-radius:15px;border:1px solid var(--c-border);background:var(--c-bg2);display:flex;gap:11px;align-items:center}\n'
  +'#screen-cleaning .ch22-attention-icon{width:36px;height:36px;flex:0 0 36px;border-radius:12px;display:flex;align-items:center;justify-content:center;background:rgba(124,58,237,.10);font-size:17px}\n'
  +'#screen-cleaning .ch22-attention-copy{min-width:0;flex:1}#screen-cleaning .ch22-attention-copy strong{display:block;font-size:12.5px;color:var(--c-text)}#screen-cleaning .ch22-attention-copy span{display:block;margin-top:2px;font-size:10.5px;line-height:1.35;color:var(--c-text2)}\n'
  +'#screen-cleaning .ch22-history{display:grid;gap:12px;padding-bottom:22px}\n'
  +'#screen-cleaning .ch22-hero{padding:17px;border-radius:20px;border:1px solid var(--c-border);background:linear-gradient(145deg,rgba(124,58,237,.09),rgba(245,158,11,.06),var(--c-bg2));box-shadow:0 8px 26px rgba(15,23,42,.05)}\n'
  +'#screen-cleaning .ch22-kicker{font-size:9px;font-weight:900;letter-spacing:.8px;text-transform:uppercase;color:var(--c-text2)}#screen-cleaning .ch22-hero h2{font-size:20px;line-height:1.15;margin:5px 0 4px;color:var(--c-text)}#screen-cleaning .ch22-hero p{font-size:11px;line-height:1.45;margin:0;color:var(--c-text2)}\n'
  +'#screen-cleaning .ch22-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:13px}#screen-cleaning .ch22-stat{padding:10px 8px;border-radius:13px;background:rgba(255,255,255,.55);border:1px solid var(--c-border);text-align:center}#screen-cleaning .ch22-stat strong{display:block;font-size:16px;color:var(--c-text)}#screen-cleaning .ch22-stat span{display:block;font-size:8.5px;color:var(--c-text2);margin-top:2px}\n'
  +'#screen-cleaning .ch22-room{border:1px solid var(--c-border);border-radius:17px;background:var(--c-bg2);overflow:hidden}#screen-cleaning .ch22-room summary{list-style:none;display:flex;align-items:center;gap:10px;padding:13px;cursor:pointer}#screen-cleaning .ch22-room summary::-webkit-details-marker{display:none}\n'
  +'#screen-cleaning .ch22-room-icon{width:38px;height:38px;border-radius:12px;background:rgba(124,58,237,.08);display:flex;align-items:center;justify-content:center;font-size:17px;flex:0 0 auto}#screen-cleaning .ch22-room-copy{flex:1;min-width:0}#screen-cleaning .ch22-room-copy strong{display:block;font-size:12.5px;color:var(--c-text)}#screen-cleaning .ch22-room-copy span{display:block;font-size:9.5px;color:var(--c-text2);margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#screen-cleaning .ch22-room-count{font-size:9px;font-weight:900;color:#7c3aed;white-space:nowrap}\n'
  +'#screen-cleaning .ch22-routines{display:grid;gap:6px;padding:0 10px 11px}#screen-cleaning .ch22-routine{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:12px;background:var(--c-bg);border:1px solid var(--c-border)}#screen-cleaning .ch22-dot{width:7px;height:7px;border-radius:50%;background:#22c55e;flex:0 0 auto}#screen-cleaning .ch22-routine-copy{min-width:0;flex:1}#screen-cleaning .ch22-routine-copy strong{display:block;font-size:10.5px;color:var(--c-text)}#screen-cleaning .ch22-routine-copy small{display:block;margin-top:2px;font-size:8.8px;color:var(--c-text2)}#screen-cleaning .ch22-routine-meta{font-size:8.5px;font-weight:850;color:var(--c-text2);white-space:nowrap}\n'
  +'#screen-cleaning .ch22-empty{padding:24px 16px;border:1px dashed var(--c-border);border-radius:17px;text-align:center;background:var(--c-bg2)}#screen-cleaning .ch22-empty strong{display:block;color:var(--c-text);font-size:13px}#screen-cleaning .ch22-empty span{display:block;color:var(--c-text2);font-size:10.5px;line-height:1.45;margin-top:4px}\n'
  +'[data-theme*="dark"] #screen-cleaning .ch22-stat{background:rgba(255,255,255,.035)}[data-theme*="dark"] #screen-cleaning .ch22-room-count{color:#e0bf69}[data-theme*="dark"] #screen-cleaning .ch22-attention-icon{background:rgba(224,191,105,.12)}\n'
  +'@media(max-width:380px){#screen-cleaning .ch22-stats{gap:5px}#screen-cleaning .ch22-stat{padding:9px 4px}}\n';document.head.appendChild(style);}

function data(){return state.snapshot&&state.snapshot.data||{};}
function reminderMarkup(){var c=contract(),ctx=context();if(!c||!ctx||!ctx.uid)return'';var reminder=c.reminders(data(),ctx.uid,Date.now());if(!reminder||!reminder.hasReminder)return'';var parts=[];if(reminder.todayCount)parts.push(reminder.todayCount+' '+(reminder.todayCount===1?'beurt':'beurten')+' vandaag · '+reminder.todayMinutes+' min');if(reminder.overdueCount)parts.push(reminder.overdueCount+' achterstallig · '+reminder.overdueMinutes+' min');return'<section class="ch22-attention" data-ch22-attention><div class="ch22-attention-icon">'+(reminder.overdueCount?'⏳':'✨')+'</div><div class="ch22-attention-copy"><strong>'+(reminder.overdueCount?'Schoonmaken vraagt aandacht':'Voor vandaag')+'</strong><span>'+esc(parts.join(' · '))+'</span></div></section>';}
function historyMarkup(){var c=contract();if(!c)return'';var source=data(),summary=c.summary(source,Date.now()),rooms=c.roomRows(source,Date.now());var intro='<section class="ch22-hero"><span class="ch22-kicker">Historie</span><h2>Wat is er gedaan?</h2><p>Een rustig overzicht van afgeronde schoonmaakbeurten per kamer en routine.</p><div class="ch22-stats"><div class="ch22-stat"><strong>'+summary.weekCount+'</strong><span>deze week</span></div><div class="ch22-stat"><strong>'+summary.weekMinutes+'</strong><span>minuten</span></div><div class="ch22-stat"><strong>'+summary.peopleCount+'</strong><span>gezinsleden</span></div></div></section>';
  if(!rooms.length)return'<div class="ch22-history" data-ch22-history-root>'+intro+'<div class="ch22-empty"><strong>Nog geen historie</strong><span>Zodra een schoonmaakbeurt is afgerond verschijnt die hier automatisch.</span></div></div>';
  var rows=rooms.map(function(room,index){var routines=room.routines||[],body=routines.length?routines.slice(0,12).map(function(routine){return'<div class="ch22-routine"><span class="ch22-dot"></span><div class="ch22-routine-copy"><strong>'+esc(routine.title)+'</strong><small>'+esc(formatWhen(routine.lastAt))+' · '+esc(memberName(routine.lastByUid))+'</small></div><span class="ch22-routine-meta">'+routine.count30+'× / 30d</span></div>';}).join(''):'<div class="ch22-empty"><span>Geen routine-details beschikbaar voor deze oudere log.</span></div>';return'<details class="ch22-room"'+(index===0?' open':'')+'><summary><div class="ch22-room-icon">✓</div><div class="ch22-room-copy"><strong>'+esc(room.name)+'</strong><span>Laatst '+esc(formatWhen(room.lastAt))+' · '+esc(memberName(room.lastByUid))+'</span></div><span class="ch22-room-count">'+room.activity30+'× / 30d</span></summary><div class="ch22-routines">'+body+'</div></details>';}).join('');
  return'<div class="ch22-history" data-ch22-history-root>'+intro+rows+'</div>';}

function ensureHistoryTab(shell){var tabs=shell&&shell.querySelector('.cv2-tabs');if(!tabs)return null;var button=tabs.querySelector('[data-ch22-history]');if(!button){button=document.createElement('button');button.type='button';button.setAttribute('data-ch22-history','');button.textContent='Historie';tabs.appendChild(button);}button.classList.toggle('is-active',state.historyActive);return tabs;}
function showNative(shell){Array.from(shell.children).forEach(function(child){child.classList.remove('ch22-hidden');});var history=shell.querySelector('[data-ch22-history-root]');if(history)history.remove();}
function showHistory(shell,tabs){Array.from(shell.children).forEach(function(child){if(child!==tabs)child.classList.add('ch22-hidden');});var old=shell.querySelector('[data-ch22-history-root]');if(old)old.remove();var holder=document.createElement('div');holder.innerHTML=historyMarkup();var next=holder.firstElementChild;if(next)shell.appendChild(next);tabs.querySelectorAll('button').forEach(function(button){button.classList.toggle('is-active',button.hasAttribute('data-ch22-history'));});}
function enhance(){state.enhanceQueued=false;ensureStyle();var screen=document.getElementById('screen-cleaning'),root=document.getElementById('cleaning-content'),shell=root&&root.querySelector('.cv2-shell');if(!screen||!shell)return;attachScreen(screen);var tabs=ensureHistoryTab(shell);if(!tabs)return;if(state.historyActive){showHistory(shell,tabs);return;}showNative(shell);var nativeActive=tabs.querySelector('[data-cv2-tab].is-active'),old=root.querySelector('[data-ch22-attention]');if(old)old.remove();if(nativeActive&&nativeActive.dataset.cv2Tab==='today'){var markup=reminderMarkup();if(markup){var holder=document.createElement('div');holder.innerHTML=markup;var node=holder.firstElementChild;if(node)tabs.insertAdjacentElement('afterend',node);}}}
function scheduleEnhance(){if(state.enhanceQueued)return;state.enhanceQueued=true;(window.requestAnimationFrame||function(fn){Promise.resolve().then(fn);})(function(){(window.requestAnimationFrame||function(fn){Promise.resolve().then(fn);})(enhance);});}

function onScreenClick(event){var historyButton=event.target&&event.target.closest?event.target.closest('[data-ch22-history]'):null;if(historyButton){event.preventDefault();state.historyActive=true;enhance();return;}var nativeButton=event.target&&event.target.closest?event.target.closest('[data-cv2-tab]'):null;if(nativeButton){state.historyActive=false;scheduleEnhance();}}
function attachScreen(screen){if(state.screen===screen)return;if(state.screen)state.screen.removeEventListener('click',onScreenClick);state.screen=screen;screen.addEventListener('click',onScreenClick);}

function publishNewActivities(snapshot){var c=contract(),activity=window.HouseholdActivity;if(!c||!snapshot||snapshot.ready!==true)return;var householdId=text(snapshot.householdId),logs=snapshot.data&&snapshot.data.completionLogs||{};if(householdId!==state.householdId){state.householdId=householdId;state.seen=new Set(Object.keys(logs));state.inFlight.clear();return;}Object.keys(logs).forEach(function(id){if(state.seen.has(id)||state.inFlight.has(id))return;var event=c.activityEvent(snapshot.data,id,logs[id]);if(!event){state.seen.add(id);return;}if(!activity||typeof activity.publish!=='function')return;state.inFlight.add(id);Promise.resolve(activity.publish(event)).then(function(){state.seen.add(id);}).catch(function(error){try{console.warn('[CleaningHistoryV22] activity projection deferred',error&&error.message||error);}catch(e){}}).finally(function(){state.inFlight.delete(id);});});}
function bindRepository(){var repo=window.CleaningHouseholdRepository;if(!repo||typeof repo.subscribe!=='function'||state.unsubscribe)return false;state.repo=repo;ensureStyle();state.unsubscribe=repo.subscribe(function(snapshot){state.snapshot=snapshot;publishNewActivities(snapshot);scheduleEnhance();});scheduleEnhance();return true;}
function waitForRepository(attempt){if(bindRepository())return;attempt=Number(attempt)||0;if(attempt>=60)return;(window.requestAnimationFrame||function(fn){Promise.resolve().then(fn);})(function(){waitForRepository(attempt+1);});}

window.CleaningHistoryV22={version:VERSION,render:enhance,historyMarkup:historyMarkup,reminderMarkup:reminderMarkup,status:function(){return{version:VERSION,historyActive:state.historyActive,subscribed:!!state.unsubscribe,householdId:state.householdId,seen:state.seen.size,inFlight:state.inFlight.size};}};
waitForRepository(0);
export const CLEANING_HISTORY_V22_VERSION=VERSION;
