'use strict';
import './cleaningCollaborationContract.js?v=1';

// CLEANING COLLABORATION EXPERIENCE v2.1.1
// Collaboration is contextual to one CleaningOccurrence. The existing
// Cleaning V2 turn sheet remains the only popup owner; this module only adds a
// scoped collaboration section to that sheet and reuses the single V2 repo.
const VERSION='2.1.1';
const state={bound:false,repo:null,unsubscribe:null,lastSnapshot:null,busy:new Set(),draft:null,screen:null,sheet:null};

function text(value){return String(value==null?'':value).trim();}
function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function context(){try{return window.HouseholdContext&&typeof window.HouseholdContext.snapshot==='function'?window.HouseholdContext.snapshot():null;}catch(error){return null;}}
function capture(){try{return window.HouseholdContext&&typeof window.HouseholdContext.capture==='function'?window.HouseholdContext.capture():null;}catch(error){return null;}}
function isCurrent(token){try{return !!(window.HouseholdContext&&typeof window.HouseholdContext.isCurrent==='function'&&window.HouseholdContext.isCurrent(token));}catch(error){return false;}}
function db(){try{return window.fbDb||(window.firebase&&typeof window.firebase.database==='function'&&window.firebase.database())||null;}catch(error){return null;}}
function members(){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[];return (Array.isArray(rows)?rows:[]).filter(function(row){return row&&text(row.uid||row.id)&&text(row.status||'active').toLowerCase()==='active';});}catch(error){return[];}}
function memberUid(row){return text(row&&(row.uid||row.id));}
function memberName(uid){var wanted=text(uid),row=members().find(function(item){return memberUid(item)===wanted;});return row?text(row.displayName||row.name)||'Gezinslid':'Gezinslid';}
function activeUids(){return members().map(memberUid).filter(Boolean);}
function role(){var me=text(context()&&context().uid),row=members().find(function(item){return memberUid(item)===me;}),raw=text(row&&row.role).toLowerCase();return ['owner','admin','manager','beheerder'].includes(raw)?'MANAGER':(['adult','member','gezinslid'].includes(raw)?'MEMBER':(['child','limited','restricted','beperkt'].includes(raw)?'LIMITED':'UNKNOWN'));}
function isManager(){return role()==='MANAGER';}
function toast(message){if(typeof window.showToast==='function')window.showToast(message);else try{console.info('[CleaningCollaborationV21]',message);}catch(error){}}
function safeKey(value){return text(value).replace(/[.#$\[\]\/\u0000-\u001F\u007F]/g,'_');}
function recordOccurrenceIds(row){var ids=[];(Array.isArray(row&&row.cleaningOccurrenceIds)?row.cleaningOccurrenceIds:[]).forEach(function(value){var id=text(value);if(id&&ids.indexOf(id)<0)ids.push(id);});[row&&row.cleaningOccurrenceId,row&&row.sourceId].forEach(function(value){var id=text(value);if(id&&ids.indexOf(id)<0)ids.push(id);});return ids;}
function occurrenceById(id){var data=state.lastSnapshot&&state.lastSnapshot.data,raw=data&&data.occurrences&&data.occurrences[id];return raw?Object.assign({id:id},raw):null;}
function currentAssignee(row){return text(row&&row.assignmentUids&&row.assignmentUids[0]);}
function writeContext(){var ctx=context(),database=db(),token=capture();if(!ctx||ctx.ready!==true||!ctx.uid||!ctx.householdId)throw new Error('ACTIVE_HOUSEHOLD_REQUIRED');if(!database)throw new Error('FIREBASE_DATABASE_UNAVAILABLE');if(!token||!isCurrent(token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED');return{ctx:ctx,db:database,token:token,familyPath:'families/'+ctx.householdId,cleaningPath:'families/'+ctx.householdId+'/cleaning'};}

function projectionTask(occurrenceId){var rows=Array.isArray(window.taskData)?window.taskData:[];return rows.find(function(row){return recordOccurrenceIds(row).indexOf(text(occurrenceId))>=0;})||null;}
function projectionEvent(occurrenceId){var repository=window.CalendarEventHouseholdRepository||window.CalendarEventRepository,rows=[];try{rows=repository&&typeof repository.list==='function'?repository.list():[];}catch(error){rows=[];}return (Array.isArray(rows)?rows:[]).find(function(row){return recordOccurrenceIds(row).indexOf(text(occurrenceId))>=0;})||null;}
function syncAcceptedProjection(occurrence,write){
  if(!occurrence)return Promise.resolve();var assigned=currentAssignee(occurrence),display=memberName(assigned),date=text(occurrence.scheduledDate),time=text(occurrence.scheduledTime),timestamp=Date.now(),updates={},task=projectionTask(occurrence.id),taskKey=task&&text(task._key||task.id);
  if(taskKey){updates['tasks/'+taskKey+'/assignedToUid']=assigned;updates['tasks/'+taskKey+'/assignedToUids']=assigned?{[assigned]:true}:{};updates['tasks/'+taskKey+'/who']=display?[display]:[];if(date){updates['tasks/'+taskKey+'/date']=date;updates['tasks/'+taskKey+'/dueDate']=date;}updates['tasks/'+taskKey+'/time']=time;updates['tasks/'+taskKey+'/updatedAt']=timestamp;updates['tasks/'+taskKey+'/updatedByUid']=write.ctx.uid;}
  var event=projectionEvent(occurrence.id),eventKey=event&&text(event._key||event.id);if(!eventKey&&occurrence.projections&&occurrence.projections.calendarEventId&&event)eventKey='id_'+safeKey(occurrence.projections.calendarEventId);if(eventKey){updates['calendarEvents/'+eventKey+'/assignedToUid']=assigned;updates['calendarEvents/'+eventKey+'/who']=display;if(date)updates['calendarEvents/'+eventKey+'/date']=date;updates['calendarEvents/'+eventKey+'/time']=time;updates['calendarEvents/'+eventKey+'/flexible']=!time;updates['calendarEvents/'+eventKey+'/updatedAt']=timestamp;updates['calendarEvents/'+eventKey+'/updatedByUid']=write.ctx.uid;}
  updates['cleaning/occurrences/'+safeKey(occurrence.id)+'/collaborationProjectionSyncedAt']=timestamp;updates['cleaning/occurrences/'+safeKey(occurrence.id)+'/collaborationProjectionSyncedByUid']=write.ctx.uid;
  return write.db.ref(write.familyPath).update(updates);
}

function applyCommand(occurrenceId,command){
  occurrenceId=text(occurrenceId);if(!occurrenceId)return Promise.reject(new Error('CLEANING_OCCURRENCE_REQUIRED'));if(state.busy.has(occurrenceId))return Promise.resolve({duplicateTap:true});var contract=window.CleaningCollaborationContract;if(!contract||typeof contract.apply!=='function')return Promise.reject(new Error('CLEANING_COLLABORATION_UNAVAILABLE'));
  var write;try{write=writeContext();}catch(error){return Promise.reject(error);}state.busy.add(occurrenceId);render();var outcome=null,idempotent=false,ref=write.db.ref(write.cleaningPath+'/occurrences/'+safeKey(occurrenceId));
  return ref.transaction(function(server){
    if(!server||typeof server!=='object'||!isCurrent(write.token))return;var result=contract.apply(server,command,{actorUid:write.ctx.uid,activeUids:activeUids(),timestamp:Date.now(),isManager:isManager()});outcome=result;if(result.changed===false){idempotent=true;return;}return result.occurrence;
  }).then(function(result){
    if(idempotent)return{changed:false,occurrence:occurrenceById(occurrenceId)};
    if(!result||result.committed!==true||!result.snapshot)throw new Error('CLEANING_COLLABORATION_WRITE_NOT_COMMITTED');var occurrence=Object.assign({id:occurrenceId},result.snapshot.val()),sync=outcome&&outcome.projectionChanged?syncAcceptedProjection(occurrence,write):Promise.resolve();return sync.then(function(){return{changed:true,occurrence:occurrence,retargeted:!!(outcome&&outcome.retargeted)};});
  }).finally(function(){state.busy.delete(occurrenceId);render();try{if(window.ActionInboxStore&&typeof window.ActionInboxStore.refresh==='function')window.ActionInboxStore.refresh();}catch(error){}});
}

function ensureStyle(){if(document.getElementById('cleaning-collaboration-v21-style'))return;var style=document.createElement('style');style.id='cleaning-collaboration-v21-style';style.textContent=''
  +'#cleaning-collaboration-v21{display:none!important}\n'
  +'#cleaning-v2-sheet .cc21-turn{margin:18px 0 4px;padding:14px;border:1px solid var(--c-border);border-radius:16px;background:var(--c-bg,var(--c-bg2))}\n'
  +'#cleaning-v2-sheet .cc21-turn-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:10px}\n'
  +'#cleaning-v2-sheet .cc21-turn-head span{display:block;font-size:10.5px;font-weight:800;letter-spacing:.35px;text-transform:uppercase;color:var(--c-text2);margin-bottom:2px}\n'
  +'#cleaning-v2-sheet .cc21-turn-head strong{display:block;font-size:14px;color:var(--c-text)}\n'
  +'#cleaning-v2-sheet .cc21-status{padding:9px 10px;border-radius:11px;background:rgba(245,158,11,.10);color:#a16207;font-size:11.5px;font-weight:700;line-height:1.35;margin-bottom:9px}\n'
  +'#cleaning-v2-sheet .cc21-actions{display:flex;flex-wrap:wrap;gap:8px}\n'
  +'#cleaning-v2-sheet .cc21-btn{min-height:42px;border-radius:12px;padding:0 12px;border:1px solid var(--c-border);background:var(--c-bg2);color:var(--c-text);font:inherit;font-size:12px;font-weight:800;cursor:pointer}\n'
  +'#cleaning-v2-sheet .cc21-btn.primary{border-color:transparent;background:#7c3aed;color:#fff}\n'
  +'#cleaning-v2-sheet .cc21-btn.danger{color:#b91c1c}\n'
  +'#cleaning-v2-sheet .cc21-btn.link{border-color:transparent;background:transparent;color:var(--c-accent,#7c3aed);padding-left:0;padding-right:0}\n'
  +'#cleaning-v2-sheet .cc21-btn:disabled{opacity:.5;cursor:default}\n'
  +'#cleaning-v2-sheet .cc21-form{margin-top:10px;border-top:1px solid var(--c-border);padding-top:11px;display:grid;gap:9px}\n'
  +'#cleaning-v2-sheet .cc21-form label{display:grid;gap:5px;font-size:11px;font-weight:800;color:var(--c-text2)}\n'
  +'#cleaning-v2-sheet .cc21-form select,#cleaning-v2-sheet .cc21-form input{width:100%;box-sizing:border-box;min-height:44px;border:1px solid var(--c-border);border-radius:11px;background:var(--c-bg2);color:var(--c-text);padding:0 11px;font:inherit}\n'
  +'#cleaning-v2-sheet .cc21-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}\n'
  +'[data-theme*="dark"] #cleaning-v2-sheet .cc21-btn.primary{background:#d8b552;color:#241608}\n'
  +'[data-theme*="dark"] #cleaning-v2-sheet .cc21-status{background:rgba(216,181,82,.13);color:#e0bf69}\n'
  +'@media(max-width:420px){#cleaning-v2-sheet .cc21-grid{grid-template-columns:1fr}}\n';document.head.appendChild(style);}
function optionRows(excludeUid){return members().filter(function(row){return memberUid(row)!==text(excludeUid);}).map(function(row){return'<option value="'+esc(memberUid(row))+'">'+esc(text(row.displayName||row.name)||'Gezinslid')+'</option>';}).join('');}
function formMarkup(row){var draft=state.draft;if(!draft||draft.occurrenceId!==row.id)return'';var assignee=currentAssignee(row),transfer=row.transferRequest||{},counter=transfer.counterProposal||{};
  if(draft.kind==='transfer')return'<form class="cc21-form" data-cc21-form="transfer" data-occurrence-id="'+esc(row.id)+'"><label>Overdragen aan<select name="toUid" required><option value="">Kies gezinslid</option>'+optionRows(assignee)+'</select></label><div class="cc21-actions"><button class="cc21-btn primary" type="submit">Verzoek sturen</button><button class="cc21-btn" type="button" data-cc21-cancel>Annuleren</button></div></form>';
  if(draft.kind==='help')return'<form class="cc21-form" data-cc21-form="help" data-occurrence-id="'+esc(row.id)+'"><label>Hulp vragen aan<select name="toUid" required><option value="">Kies gezinslid</option>'+optionRows(text(context()&&context().uid))+'</select></label><div class="cc21-actions"><button class="cc21-btn primary" type="submit">Hulp vragen</button><button class="cc21-btn" type="button" data-cc21-cancel>Annuleren</button></div></form>';
  if(draft.kind==='counter')return'<form class="cc21-form" data-cc21-form="counter" data-occurrence-id="'+esc(row.id)+'"><label>Wie neemt de beurt?<select name="assigneeUid" required>'+members().map(function(member){var uid=memberUid(member),selected=uid===text(counter.assigneeUid||context()&&context().uid)?' selected':'';return'<option value="'+esc(uid)+'"'+selected+'>'+esc(text(member.displayName||member.name)||'Gezinslid')+'</option>';}).join('')+'</select></label><div class="cc21-grid"><label>Dag<input type="date" name="scheduledDate" value="'+esc(text(row.scheduledDate))+'"></label><label>Tijd<input type="time" name="scheduledTime" value="'+esc(text(row.scheduledTime))+'"></label></div><div class="cc21-actions"><button class="cc21-btn primary" type="submit">Tegenvoorstel sturen</button><button class="cc21-btn" type="button" data-cc21-cancel>Annuleren</button></div></form>';
  return'';
}
function turnOccurrenceId(){var sheet=document.getElementById('cleaning-v2-sheet');if(!sheet||!sheet.classList.contains('is-open'))return'';var anchor=sheet.querySelector('[data-cv2-complete-all]')||sheet.querySelector('[data-cv2-supplies]');return text(anchor&&((anchor.dataset&&anchor.dataset.cv2CompleteAll)||(anchor.dataset&&anchor.dataset.cv2Supplies)));}
function turnMarkup(row){var me=text(context()&&context().uid),assignee=currentAssignee(row),transfer=row.transferRequest||{},counter=transfer.counterProposal||{},help=row.helpRequest||{},transferStatus=text(transfer.status).toUpperCase(),counterStatus=text(counter.status).toUpperCase(),helpStatus=text(help.status).toUpperCase(),busy=state.busy.has(row.id),status='',incoming=false;
  if((transferStatus==='PENDING'||transferStatus==='COUNTER_PROPOSED')&&text(transfer.fromUid)===me)status=transferStatus==='COUNTER_PROPOSED'?'Tegenvoorstel ontvangen — beslis via de Actie-inbox.':'Overdracht naar '+memberName(transfer.toUid)+' wacht op akkoord.';
  else if(transferStatus==='PENDING'&&text(transfer.toUid)===me){status=memberName(transfer.fromUid)+' wil deze beurt aan jou overdragen.';incoming=true;}
  else if(transferStatus==='COUNTER_PROPOSED'&&counterStatus==='PENDING'&&text(transfer.fromUid)===me){status='Er staat een tegenvoorstel klaar in je Actie-inbox.';incoming=true;}
  else if(helpStatus==='PENDING'&&text(help.fromUid)===me)status='Hulp gevraagd aan '+memberName(help.toUid)+' — wacht op reactie.';
  else if(helpStatus==='PENDING'&&text(help.toUid)===me){status=memberName(help.fromUid)+' vraagt jouw hulp bij deze beurt.';incoming=true;}
  else if(helpStatus==='ACCEPTED'&&text(help.fromUid)===me)status=memberName(help.helperUid||help.toUid)+' helpt mee met deze beurt.';
  var canInitiate=assignee===me||isManager(),transferOpen=(transferStatus==='PENDING'||transferStatus==='COUNTER_PROPOSED')&&text(transfer.fromUid)===me,helpOpen=helpStatus==='PENDING'&&text(help.fromUid)===me;
  return'<section class="cc21-turn" data-cc21-turn="'+esc(row.id)+'"><div class="cc21-turn-head"><div><span>Deze beurt</span><strong>Samenwerken</strong></div></div>'+(status?'<div class="cc21-status">'+esc(status)+'</div>':'')+'<div class="cc21-actions">'+(incoming?'<button type="button" class="cc21-btn link" data-cc21-inbox>Open Actie-inbox</button>':'')+(transferOpen?'<button type="button" class="cc21-btn danger" data-cc21-withdraw-transfer="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Overdracht intrekken</button>':(canInitiate?'<button type="button" class="cc21-btn" data-cc21-open-transfer="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Overdragen</button>':''))+(helpOpen?'<button type="button" class="cc21-btn danger" data-cc21-withdraw-help="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Hulpvraag intrekken</button>':(canInitiate?'<button type="button" class="cc21-btn" data-cc21-open-help="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Hulp vragen</button>':''))+'</div>'+formMarkup(row)+'</section>';}
function renderTurnActions(){ensureHooks();var sheet=document.getElementById('cleaning-v2-sheet'),id=turnOccurrenceId();if(!sheet||!id)return;var body=sheet.querySelector('[data-cv2-sheet-body]'),row=occurrenceById(id);if(!body||!row)return;var existing=body.querySelector('[data-cc21-turn]'),markup=turnMarkup(row);if(existing){existing.outerHTML=markup;return;}var actions=body.querySelector('.cv2-sheet-actions'),holder=document.createElement('div');holder.innerHTML=markup;var section=holder.firstElementChild;if(actions)body.insertBefore(section,actions);else body.appendChild(section);}
function render(){var old=document.getElementById('cleaning-collaboration-v21');if(old)old.style.display='none';renderTurnActions();}
function openInbox(){if(window.ActionInboxScreen&&typeof window.ActionInboxScreen.ensure==='function')window.ActionInboxScreen.ensure();if(typeof window.showScreen==='function')window.showScreen('inbox');var title=document.getElementById('hdr-title');if(title)title.textContent='Inbox';}
function onScreenClick(event){var target=event.target&&event.target.closest?event.target.closest('[data-cv2-turn]'):null;if(!target)return;var id=text(target.dataset&&target.dataset.cv2Turn);if(state.draft&&state.draft.occurrenceId!==id)state.draft=null;(window.requestAnimationFrame||function(fn){setTimeout(fn,0);})(renderTurnActions);}
function onSheetClick(event){var target=event.target&&event.target.closest?event.target.closest('button'):null;if(!target)return;if(target.hasAttribute('data-cv2-close')){state.draft=null;return;}if(target.hasAttribute('data-cc21-inbox')){openInbox();return;}if(target.hasAttribute('data-cc21-cancel')){state.draft=null;render();return;}if(target.dataset.cc21OpenTransfer){state.draft={kind:'transfer',occurrenceId:target.dataset.cc21OpenTransfer};render();return;}if(target.dataset.cc21OpenHelp){state.draft={kind:'help',occurrenceId:target.dataset.cc21OpenHelp};render();return;}if(target.dataset.cc21WithdrawTransfer){applyCommand(target.dataset.cc21WithdrawTransfer,{type:'WITHDRAW_TRANSFER'}).then(function(){toast('Overdracht ingetrokken');}).catch(function(error){toast(text(error&&error.message)||'Intrekken mislukt');});return;}if(target.dataset.cc21WithdrawHelp){applyCommand(target.dataset.cc21WithdrawHelp,{type:'WITHDRAW_HELP'}).then(function(){toast('Hulpvraag ingetrokken');}).catch(function(error){toast(text(error&&error.message)||'Intrekken mislukt');});return;}}
function formValues(form){var data=new FormData(form),out={};data.forEach(function(value,key){out[key]=value;});return out;}
function onSheetSubmit(event){var form=event.target;if(!form||!form.dataset||!form.dataset.cc21Form)return;event.preventDefault();var id=text(form.dataset.occurrenceId),values=formValues(form),kind=form.dataset.cc21Form,command=kind==='transfer'?{type:'REQUEST_TRANSFER',toUid:values.toUid}:kind==='help'?{type:'REQUEST_HELP',toUid:values.toUid}:{type:'COUNTER_TRANSFER',assigneeUid:values.assigneeUid,scheduledDate:values.scheduledDate,scheduledTime:values.scheduledTime};Array.from(form.elements||[]).forEach(function(el){el.disabled=true;});applyCommand(id,command).then(function(result){state.draft=null;toast(kind==='transfer'?'Overdracht gevraagd ✓':kind==='help'?'Hulp gevraagd ✓':'Tegenvoorstel verstuurd ✓');if(result&&result.retargeted)toast('Nieuw akkoord gevraagd aan het voorgestelde gezinslid.');render();}).catch(function(error){Array.from(form.elements||[]).forEach(function(el){el.disabled=false;});toast(text(error&&error.message)||'Verzoek kon niet worden opgeslagen.');});}
function ensureHooks(){var screen=document.getElementById('screen-cleaning');if(screen&&state.screen!==screen){if(state.screen)state.screen.removeEventListener('click',onScreenClick);state.screen=screen;screen.addEventListener('click',onScreenClick);}var sheet=document.getElementById('cleaning-v2-sheet');if(sheet&&state.sheet!==sheet){if(state.sheet){state.sheet.removeEventListener('click',onSheetClick);state.sheet.removeEventListener('submit',onSheetSubmit);}state.sheet=sheet;sheet.addEventListener('click',onSheetClick);sheet.addEventListener('submit',onSheetSubmit);}}
function findTurnButton(occurrenceId){return Array.from(document.querySelectorAll('#screen-cleaning [data-cv2-turn]')).find(function(button){return text(button.dataset&&button.dataset.cv2Turn)===text(occurrenceId);})||null;}
function openTurnForCounter(occurrenceId){return new Promise(function(resolve,reject){var attempts=0,switchedPlan=false;function step(){ensureHooks();var current=turnOccurrenceId();if(current===occurrenceId){render();resolve(true);return;}var button=findTurnButton(occurrenceId);if(button){button.click();(window.requestAnimationFrame||function(fn){setTimeout(fn,0);})(step);return;}if(!switchedPlan){var plan=document.querySelector('#screen-cleaning [data-cv2-tab="plan"]');if(plan){switchedPlan=true;plan.click();(window.requestAnimationFrame||function(fn){setTimeout(fn,0);})(step);return;}}attempts++;if(attempts<60){(window.requestAnimationFrame||function(fn){setTimeout(fn,16);})(step);return;}reject(new Error('CLEANING_COLLAB_OCCURRENCE_NOT_VISIBLE'));}step();});}
function openCounter(occurrenceId){occurrenceId=text(occurrenceId);state.draft={kind:'counter',occurrenceId:occurrenceId};if(typeof window.showScreen==='function')window.showScreen('cleaning');return openTurnForCounter(occurrenceId).catch(function(error){state.draft=null;throw error;});}
function handleInboxAction(occurrenceId,actionId){var action=text(actionId).toLowerCase();if(action==='counter')return openCounter(occurrenceId);var map={accept:'ACCEPT_TRANSFER',decline:'DECLINE_TRANSFER','accept-counter':'ACCEPT_COUNTER','decline-counter':'DECLINE_COUNTER','accept-help':'ACCEPT_HELP','decline-help':'DECLINE_HELP'};var command=map[action];if(!command)return Promise.reject(new Error('CLEANING_COLLAB_UNKNOWN_ACTION'));return applyCommand(occurrenceId,{type:command});}
function bindRepository(){var repo=window.CleaningHouseholdRepository;if(!repo||typeof repo.subscribe!=='function'||state.bound)return false;state.repo=repo;state.bound=true;ensureStyle();ensureHooks();state.unsubscribe=repo.subscribe(function(snapshot){state.lastSnapshot=snapshot;render();});render();return true;}
function waitForRepository(attempt){if(bindRepository())return;attempt=Number(attempt)||0;if(attempt>=60)return;(window.requestAnimationFrame||function(fn){Promise.resolve().then(fn);})(function(){waitForRepository(attempt+1);});}

window.CleaningCollaborationV21={version:VERSION,applyCommand:applyCommand,handleInboxAction:handleInboxAction,openCounter:openCounter,render:render};
waitForRepository(0);
export const CLEANING_COLLABORATION_VERSION=VERSION;