'use strict';
// CLEANING V2.3 — contextual controls inside the existing Cleaning turn sheet.
// This module does not create a popup, listener, observer or canonical writer.
(function(){
  var VERSION='2.3.0',bound=false,busy=false;
  function text(v){return String(v==null?'':v).trim();}
  function esc(v){return text(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function repo(){return window.CleaningHouseholdRepository||window.CleaningV2Repository||null;}
  function snap(){var r=repo();try{return r&&r.snapshot?r.snapshot():null;}catch(e){return null;}}
  function occurrence(id){var s=snap(),row=s&&s.data&&s.data.occurrences&&s.data.occurrences[id];return row?Object.assign({id:id},row):null;}
  function members(){try{var b=window.HouseholdIdentityFirebaseBridge,rows=b&&b.getMembers?b.getMembers():[];return(Array.isArray(rows)?rows:[]).filter(function(x){return x&&text(x.uid||x.id)&&text(x.status||'active').toLowerCase()==='active';});}catch(e){return[];}}
  function memberUid(row){return text(row&&(row.uid||row.id));}
  function toast(m){if(window.showToast)window.showToast(m);}
  function turnId(sheet){var anchor=sheet&&sheet.querySelector('[data-cv2-complete-all]');return text(anchor&&anchor.dataset.cv2CompleteAll);}
  function closed(row){var a=text(row&&row.status).toUpperCase(),b=text(row&&row.assignmentStatus).toUpperCase();return a==='COMPLETED'||b==='COMPLETED'||a==='SKIPPED'||b==='SKIPPED'||a==='CANCELLED';}
  function pending(row){var t=text(row&&row.transferRequest&&row.transferRequest.status).toUpperCase(),h=text(row&&row.helpRequest&&row.helpRequest.status).toUpperCase();return t==='PENDING'||t==='COUNTER_PROPOSED'||h==='PENDING';}
  function ensureStyle(){if(document.getElementById('cleaning-v23-controls-style'))return;var s=document.createElement('style');s.id='cleaning-v23-controls-style';s.textContent='#cleaning-v2-sheet .cv23-adjust{margin:18px 0 8px;padding:14px;border:1px solid var(--c-border);border-radius:18px;background:var(--c-bg,var(--c-bg2))}#cleaning-v2-sheet .cv23-adjust-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}#cleaning-v2-sheet .cv23-adjust-head span{display:block;font-size:10.5px;font-weight:800;letter-spacing:.35px;text-transform:uppercase;color:var(--c-text2)}#cleaning-v2-sheet .cv23-adjust-head strong{display:block;font-size:14px;color:var(--c-text);margin-top:2px}#cleaning-v2-sheet .cv23-quick{display:grid;grid-template-columns:1fr 1fr;gap:8px}#cleaning-v2-sheet .cv23-btn{min-height:42px;border-radius:12px;border:1px solid var(--c-border);background:var(--c-bg2);color:var(--c-text);font:inherit;font-size:12px;font-weight:800;padding:0 10px}#cleaning-v2-sheet .cv23-btn.primary{background:#7c3aed;color:white;border-color:transparent}#cleaning-v2-sheet .cv23-btn.warn{color:#a16207}#cleaning-v2-sheet .cv23-form{display:none;margin-top:10px;padding-top:10px;border-top:1px solid var(--c-border);gap:8px}#cleaning-v2-sheet .cv23-form.is-open{display:grid}#cleaning-v2-sheet .cv23-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}#cleaning-v2-sheet .cv23-form label{display:grid;gap:5px;font-size:11px;font-weight:800;color:var(--c-text2)}#cleaning-v2-sheet .cv23-form input,#cleaning-v2-sheet .cv23-form select{box-sizing:border-box;width:100%;min-height:44px;border-radius:11px;border:1px solid var(--c-border);background:var(--c-bg2);color:var(--c-text);padding:0 10px;font:inherit}#cleaning-v2-sheet .cv23-note{font-size:11px;line-height:1.4;color:var(--c-text2);margin:8px 0 0}#cleaning-v2-sheet .cv23-adjust.is-busy{opacity:.65;pointer-events:none}@media(max-width:390px){#cleaning-v2-sheet .cv23-quick,#cleaning-v2-sheet .cv23-grid{grid-template-columns:1fr}}';document.head.appendChild(s);}
  function markup(row){var assigned=text((row.assignmentUids||[])[0]),options=members().map(function(m){var uid=memberUid(m);return'<option value="'+esc(uid)+'"'+(uid===assigned?' selected':'')+'>'+esc(text(m.displayName||m.name)||'Gezinslid')+'</option>';}).join('');if(closed(row))return'';var note=pending(row)?'<p class="cv23-note">Er staat een overdracht- of hulpverzoek open. Rond dat eerst af voordat je deze beurt wijzigt.</p>':'';return'<section class="cv23-adjust" data-cv23-root data-occurrence-id="'+esc(row.id)+'"><div class="cv23-adjust-head"><div><span>Deze schoonmaakbeurt</span><strong>Planning aanpassen</strong></div></div><div class="cv23-quick"><button type="button" class="cv23-btn" data-cv23-later'+(pending(row)?' disabled':'')+'>Later deze week</button><button type="button" class="cv23-btn" data-cv23-edit'+(pending(row)?' disabled':'')+'>Ander moment / persoon</button><button type="button" class="cv23-btn" data-cv23-carry'+(pending(row)?' disabled':'')+'>Doorschuiven</button><button type="button" class="cv23-btn warn" data-cv23-skip'+(pending(row)?' disabled':'')+'>Deze keer overslaan</button></div>'+note+'<form class="cv23-form" data-cv23-form><div class="cv23-grid"><label>Dag<input type="date" name="date" value="'+esc(text(row.scheduledDate))+'" required></label><label>Tijd<input type="time" name="time" value="'+esc(text(row.scheduledTime))+'"></label></div><label>Wie?<select name="assigneeUid" required>'+options+'</select></label><button class="cv23-btn primary" type="submit">Wijziging opslaan</button></form></section>';}
  function render(){var sheet=document.getElementById('cleaning-v2-sheet');if(!sheet||!sheet.classList.contains('is-open'))return;var id=turnId(sheet),existing=sheet.querySelector('[data-cv23-root]');if(!id){if(existing)existing.remove();return;}var row=occurrence(id);if(!row){if(existing)existing.remove();return;}var host=sheet.querySelector('[data-cv2-sheet-body]'),collab=host&&host.querySelector('.cc21-turn'),anchor=host&&host.querySelector('.cv2-sheet-actions');if(!host||!anchor)return;var html=markup(row);if(!html){if(existing)existing.remove();return;}var holder=document.createElement('div');holder.innerHTML=html;var fresh=holder.firstElementChild;if(existing)existing.replaceWith(fresh);else if(collab)host.insertBefore(fresh,collab);else anchor.insertAdjacentElement('afterend',fresh);}
  function run(root,promise,success){if(busy)return;busy=true;root.classList.add('is-busy');Promise.resolve(promise).then(function(){toast(success);setTimeout(render,0);}).catch(function(error){var c=window.CleaningOccurrenceCommandsV23;toast(c&&c.userMessage?c.userMessage(error):text(error&&error.message));}).finally(function(){busy=false;root.classList.remove('is-busy');});}
  function click(event){var button=event.target&&event.target.closest?event.target.closest('[data-cv23-later],[data-cv23-edit],[data-cv23-carry],[data-cv23-skip]'):null;if(!button)return;var root=button.closest('[data-cv23-root]'),id=text(root&&root.dataset.occurrenceId),r=repo();if(!root||!id||!r)return;if(button.hasAttribute('data-cv23-edit')){var form=root.querySelector('[data-cv23-form]');if(form)form.classList.toggle('is-open');return;}if(button.hasAttribute('data-cv23-later')){run(root,r.laterThisWeekV23(id),'Beurt verplaatst ✓');return;}if(button.hasAttribute('data-cv23-carry')){if(!confirm('Niet-afgeronde onderdelen doorschuiven naar de volgende cyclus?'))return;run(root,r.finalizeIncompleteV23(id,'CARRY_FORWARD'),'Resterende onderdelen doorgeschoven ✓');return;}if(button.hasAttribute('data-cv23-skip')){if(!confirm('Deze schoonmaakbeurt deze keer overslaan?'))return;run(root,r.finalizeIncompleteV23(id,'SKIP'),'Beurt overgeslagen');}}
  function submit(event){var form=event.target&&event.target.closest?event.target.closest('[data-cv23-form]'):null;if(!form)return;event.preventDefault();var root=form.closest('[data-cv23-root]'),id=text(root&&root.dataset.occurrenceId),r=repo(),data=new FormData(form);if(!root||!id||!r)return;run(root,r.adjustOccurrenceV23(id,{date:data.get('date'),time:data.get('time'),assigneeUid:data.get('assigneeUid')}),'Beurt bijgewerkt ✓');}
  function bind(){if(bound)return;var sheet=document.getElementById('cleaning-v2-sheet');if(!sheet)return;bound=true;ensureStyle();sheet.addEventListener('click',click);sheet.addEventListener('submit',submit);var original=window.CleaningOccurrenceCommandsV23;if(original&&original.install)original.install();var rerender=function(){setTimeout(render,0);};sheet.addEventListener('click',rerender,true);render();}
  function boot(){bind();if(!bound&&document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});}
  window.CleaningOccurrenceControlsV23=Object.freeze({version:VERSION,render:render,bind:bind});boot();
})();
export const CLEANING_OCCURRENCE_CONTROLS_V23_VERSION='2.3.0';