'use strict';
// ============================================================
// CLEANING PAUSE EXPERIENCE v0.1.0
// Temporary routine/room pauses with explicit resume semantics.
// - planner already excludes routine.paused === true
// - room pause marks only currently-unpaused routines as ROOM-paused
// - resume never creates historical backlog: overdue nextDueAt becomes today
// - expiring pauses auto-resume through the Cleaning repository lifecycle
// ============================================================
(function(){
  if(window.CleaningPauseExperience)return;

  var VERSION='0.1.0';
  var DAY_MS=86400000;
  var state={observer:null,queued:false,sheet:null,busy:false,auto:{},repository:null};

  function clone(value){if(value===undefined)return undefined;try{return JSON.parse(JSON.stringify(value));}catch(error){return value;}}
  function text(value){return String(value==null?'':value).trim();}
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function now(){return Date.now();}
  function startOfDay(value){var d=new Date(Number(value)||now());d.setHours(0,0,0,0);return d.getTime();}
  function repo(){return window.CleaningHouseholdRepository||null;}
  function snapshot(){try{var r=repo();return r&&r.snapshot?r.snapshot():null;}catch(error){return null;}}
  function root(){var snap=state.repository||snapshot();return snap&&snap.data||{};}
  function context(){try{return window.HouseholdContext&&window.HouseholdContext.snapshot?window.HouseholdContext.snapshot():null;}catch(error){return null;}}
  function capture(){try{return window.HouseholdContext&&window.HouseholdContext.capture?window.HouseholdContext.capture():null;}catch(error){return null;}}
  function current(token){try{return !!(window.HouseholdContext&&window.HouseholdContext.isCurrent&&window.HouseholdContext.isCurrent(token));}catch(error){return false;}}
  function database(){try{return window.fbDb||(window.firebase&&window.firebase.database&&window.firebase.database())||null;}catch(error){return null;}}
  function cleaningPath(householdId){var domain=window.CleaningDomain;return householdId&&domain&&domain.basePath?domain.basePath(householdId):null;}
  function toast(message){if(typeof window.showToast==='function')window.showToast(message);}
  function writeContext(){var ctx=context(),db=database(),token=capture(),path=ctx&&cleaningPath(ctx.householdId);if(!ctx||ctx.ready!==true||!ctx.uid||!ctx.householdId)throw new Error('ACTIVE_HOUSEHOLD_REQUIRED');if(!db)throw new Error('FIREBASE_DATABASE_UNAVAILABLE');if(!token||!current(token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED');if(!path)throw new Error('ACTIVE_HOUSEHOLD_REQUIRED');return{ctx:ctx,db:db,token:token,path:path};}
  function activeRoutine(row){return !!(row&&typeof row==='object'&&row.active!==false);}
  function routineById(id){var row=root().routines&&root().routines[id];return activeRoutine(row)?Object.assign({id:id},row):null;}
  function roomById(id){var row=root().rooms&&root().rooms[id];return row&&typeof row==='object'&&row.active!==false?Object.assign({id:id},row):null;}
  function routinesForRoom(roomId){var rows=root().routines||{};return Object.keys(rows).map(function(id){return Object.assign({id:id},rows[id]||{});}).filter(function(row){return activeRoutine(row)&&text(row.roomId)===text(roomId);});}
  function nextDueOnResume(row,resumeAt){var due=Number(row&&row.nextDueAt)||0,day=startOfDay(resumeAt);return due>day?due:day;}
  function pauseUntil(days){return days?startOfDay(now()+Number(days)*DAY_MS):null;}

  function pauseRoutine(id,days){var write;try{write=writeContext();}catch(error){return Promise.reject(error);}var row=routineById(id);if(!row)return Promise.reject(new Error('CLEANING_ROUTINE_NOT_FOUND'));var stamp=now(),until=pauseUntil(days),patch={paused:true,pauseSource:'ROUTINE',pausedAt:stamp,pausedByUid:write.ctx.uid,pauseUntilAt:until,updatedAt:stamp,updatedByUid:write.ctx.uid};return write.db.ref(write.path+'/routines/'+id).update(patch).then(function(){if(!current(write.token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED_AFTER_WRITE');return Object.assign({},row,patch);});}
  function resumeRoutine(id,automatic){var write;try{write=writeContext();}catch(error){return Promise.reject(error);}var row=routineById(id);if(!row)return Promise.reject(new Error('CLEANING_ROUTINE_NOT_FOUND'));var stamp=now(),patch={paused:false,pauseSource:null,pauseUntilAt:null,resumedAt:stamp,resumedByUid:write.ctx.uid,resumeMode:automatic?'AUTO':'MANUAL',nextDueAt:nextDueOnResume(row,stamp),updatedAt:stamp,updatedByUid:write.ctx.uid};return write.db.ref(write.path+'/routines/'+id).update(patch).then(function(){if(!current(write.token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED_AFTER_WRITE');return Object.assign({},row,patch);});}
  function pauseRoom(id,days){
    var write;try{write=writeContext();}catch(error){return Promise.reject(error);}var room=roomById(id);if(!room)return Promise.reject(new Error('CLEANING_ROOM_NOT_FOUND'));var stamp=now(),until=pauseUntil(days),patch={};patch['rooms/'+id+'/paused']=true;patch['rooms/'+id+'/pauseUntilAt']=until;patch['rooms/'+id+'/pausedAt']=stamp;patch['rooms/'+id+'/pausedByUid']=write.ctx.uid;patch['rooms/'+id+'/updatedAt']=stamp;patch['rooms/'+id+'/updatedByUid']=write.ctx.uid;
    routinesForRoom(id).forEach(function(routine){if(routine.paused===true)return;var base='routines/'+routine.id+'/';patch[base+'paused']=true;patch[base+'pauseSource']='ROOM';patch[base+'pauseUntilAt']=until;patch[base+'pausedAt']=stamp;patch[base+'pausedByUid']=write.ctx.uid;patch[base+'updatedAt']=stamp;patch[base+'updatedByUid']=write.ctx.uid;});
    return write.db.ref(write.path).update(patch).then(function(){if(!current(write.token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED_AFTER_WRITE');return{roomId:id,pauseUntilAt:until};});
  }
  function resumeRoom(id,automatic){
    var write;try{write=writeContext();}catch(error){return Promise.reject(error);}var room=roomById(id);if(!room)return Promise.reject(new Error('CLEANING_ROOM_NOT_FOUND'));var stamp=now(),patch={};patch['rooms/'+id+'/paused']=false;patch['rooms/'+id+'/pauseUntilAt']=null;patch['rooms/'+id+'/resumedAt']=stamp;patch['rooms/'+id+'/resumedByUid']=write.ctx.uid;patch['rooms/'+id+'/updatedAt']=stamp;patch['rooms/'+id+'/updatedByUid']=write.ctx.uid;
    routinesForRoom(id).forEach(function(routine){if(routine.paused!==true||text(routine.pauseSource)!=='ROOM')return;var base='routines/'+routine.id+'/';patch[base+'paused']=false;patch[base+'pauseSource']=null;patch[base+'pauseUntilAt']=null;patch[base+'resumedAt']=stamp;patch[base+'resumedByUid']=write.ctx.uid;patch[base+'resumeMode']=automatic?'AUTO':'MANUAL';patch[base+'nextDueAt']=nextDueOnResume(routine,stamp);patch[base+'updatedAt']=stamp;patch[base+'updatedByUid']=write.ctx.uid;});
    return write.db.ref(write.path).update(patch).then(function(){if(!current(write.token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED_AFTER_WRITE');return{roomId:id,resumed:true};});
  }

  function ensureStyle(){if(document.getElementById('cleaning-pause-experience-style'))return;var style=document.createElement('style');style.id='cleaning-pause-experience-style';style.textContent='\n'
    +'#screen-cleaning .cleaning-room-pause-button{min-height:34px;border:1px solid var(--cleaning-border);border-radius:10px;padding:0 10px;background:var(--cleaning-surface);color:var(--cleaning-text);font:inherit;font-size:10px;font-weight:900;cursor:pointer}#screen-cleaning .cleaning-room-pause-button.is-paused{color:var(--cleaning-accent);background:color-mix(in srgb,var(--cleaning-accent) 9%,var(--cleaning-surface))}#screen-cleaning .cleaning-routine-paused-badge{display:inline-flex;margin-top:4px;padding:3px 7px;border-radius:999px;background:color-mix(in srgb,var(--cleaning-accent) 10%,var(--cleaning-surface));color:var(--cleaning-accent);font-size:8.5px;font-weight:900}\n'
    +'.cleaning-pause-overlay{position:fixed;inset:0;z-index:12520;display:grid;align-items:end;background:rgba(8,10,16,.45);padding-top:max(24px,env(safe-area-inset-top))}.cleaning-pause-sheet{width:100%;border-radius:28px 28px 0 0;background:var(--c-surface,#fff);color:var(--c-text,#1e232b);padding:12px 16px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -20px 60px rgba(0,0,0,.18)}.cleaning-pause-handle{width:38px;height:4px;border-radius:999px;background:var(--c-border,#ddd);margin:0 auto 15px}.cleaning-pause-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.cleaning-pause-head p{margin:0 0 4px;font-size:10px;font-weight:900;color:var(--c-primary,#6750a4);text-transform:uppercase;letter-spacing:.08em}.cleaning-pause-head h2{margin:0;font-size:21px}.cleaning-pause-close{width:44px;height:44px;border-radius:13px;border:1px solid var(--c-border,#ddd);background:var(--c-surface,#fff);color:inherit;font:inherit;font-size:18px}.cleaning-pause-copy{font-size:11px;line-height:1.5;color:var(--c-text2,#737784);margin:12px 0}.cleaning-pause-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.cleaning-pause-choice{min-height:48px;border:1px solid var(--c-border,#ddd);border-radius:13px;background:var(--c-surface2,#f7f7f8);color:inherit;font:inherit;font-size:11px;font-weight:900}.cleaning-pause-resume{width:100%;min-height:48px;border:0;border-radius:13px;background:var(--c-primary,#6750a4);color:#fff;font:inherit;font-size:11px;font-weight:900}.cleaning-pause-choice:disabled,.cleaning-pause-resume:disabled{opacity:.5}\n';document.head.appendChild(style);}

  function formatUntil(value){if(!Number(value))return'Tot je zelf hervat';try{return'Pauze tot '+new Date(Number(value)).toLocaleDateString('nl-NL',{day:'numeric',month:'short'});}catch(error){return'Gepauzeerd';}}
  function decorateRoutines(){var edits=document.querySelectorAll('#screen-cleaning [data-cleaning-routine-edit]');for(var i=0;i<edits.length;i++){var edit=edits[i],id=text(edit.getAttribute('data-cleaning-routine-edit')),item=edit.closest('.cleaning-routine-item'),actions=item&&item.querySelector('.cleaning-routine-item-actions'),routine=routineById(id);if(!id||!item||!actions||!routine)continue;var button=actions.querySelector('[data-cleaning-routine-pause="'+id+'"]');if(!button){button=document.createElement('button');button.type='button';button.className='cleaning-routine-pause-button';button.style.display='none';button.setAttribute('data-cleaning-routine-pause',id);actions.appendChild(button);}button.textContent=routine.paused===true?'Hervatten':'Pauzeren';var copy=item.querySelector('.cleaning-routine-copy'),badge=copy&&copy.querySelector('[data-cleaning-routine-paused-badge]');if(routine.paused===true){if(!badge){badge=document.createElement('span');badge.className='cleaning-routine-paused-badge';badge.setAttribute('data-cleaning-routine-paused-badge','1');copy.appendChild(badge);}badge.textContent=formatUntil(routine.pauseUntilAt);}else if(badge)badge.remove();}}
  function decorateRooms(){var cards=document.querySelectorAll('#screen-cleaning .cleaning-room-card[data-cleaning-room-id]');for(var i=0;i<cards.length;i++){var card=cards[i],id=text(card.getAttribute('data-cleaning-room-id')),room=roomById(id),actions=card.querySelector('.cleaning-room-order-actions');if(!id||!room||!actions)continue;var button=actions.querySelector('[data-cleaning-room-pause="'+id+'"]');if(!button){button=document.createElement('button');button.type='button';button.className='cleaning-room-pause-button';button.setAttribute('data-cleaning-room-pause',id);actions.insertBefore(button,actions.firstChild);}button.classList.toggle('is-paused',room.paused===true);button.textContent=room.paused===true?'▶ Hervat':'⏸ Pauzeer';}}
  function decorate(){state.queued=false;ensureStyle();decorateRoutines();decorateRooms();}
  function queue(){if(state.queued)return;state.queued=true;(window.requestAnimationFrame||function(callback){return setTimeout(callback,0);})(decorate);}

  function entity(){if(!state.sheet)return null;return state.sheet.kind==='room'?roomById(state.sheet.id):routineById(state.sheet.id);}
  function sheetHtml(){var row=entity();if(!row)return'';var paused=row.paused===true,title=state.sheet.kind==='room'?(row.name||'Kamer'):(row.title||'Routine');return '<section class="cleaning-pause-sheet"><div class="cleaning-pause-handle"></div><div class="cleaning-pause-head"><div><p>'+(state.sheet.kind==='room'?'Hele kamer':'Routine')+'</p><h2>'+esc(title)+'</h2></div><button type="button" class="cleaning-pause-close" data-cleaning-pause-close aria-label="Sluiten">✕</button></div>'+(paused?'<p class="cleaning-pause-copy">'+esc(formatUntil(row.pauseUntilAt))+'. Bij hervatten wordt gemiste tijd niet als een stapel achterstallige taken teruggezet.</p><button type="button" class="cleaning-pause-resume" data-cleaning-pause-resume'+(state.busy?' disabled':'')+'>'+(state.busy?'Hervatten…':'Nu hervatten')+'</button>':'<p class="cleaning-pause-copy">Tijdens de pauze worden geen nieuwe schoonmaakbeurten voor '+(state.sheet.kind==='room'?'deze kamer':'deze routine')+' gepland. Kies wanneer de planning automatisch weer mag starten.</p><div class="cleaning-pause-grid"><button type="button" class="cleaning-pause-choice" data-cleaning-pause-days="7"'+(state.busy?' disabled':'')+'>1 week</button><button type="button" class="cleaning-pause-choice" data-cleaning-pause-days="14"'+(state.busy?' disabled':'')+'>2 weken</button><button type="button" class="cleaning-pause-choice" data-cleaning-pause-days="30"'+(state.busy?' disabled':'')+'>1 maand</button><button type="button" class="cleaning-pause-choice" data-cleaning-pause-days="0"'+(state.busy?' disabled':'')+'>Tot ik hervat</button></div>')+'</section>';}
  function open(kind,id){state.sheet={kind:kind,id:text(id)};renderSheet();}
  function close(){state.sheet=null;var overlay=document.getElementById('cleaning-pause-overlay');if(overlay)overlay.remove();}
  function renderSheet(){if(!state.sheet)return;var row=entity();if(!row){close();return;}var overlay=document.getElementById('cleaning-pause-overlay');if(!overlay){overlay=document.createElement('div');overlay.id='cleaning-pause-overlay';overlay.className='cleaning-pause-overlay';document.body.appendChild(overlay);}overlay.innerHTML=sheetHtml();}
  function runPause(days){if(!state.sheet||state.busy)return;state.busy=true;renderSheet();var work=state.sheet.kind==='room'?pauseRoom(state.sheet.id,days):pauseRoutine(state.sheet.id,days);Promise.resolve(work).then(function(){state.busy=false;toast('Pauze ingesteld ✓');close();queue();}).catch(function(error){state.busy=false;toast((error&&error.message)||'Pauzeren mislukt');renderSheet();});}
  function runResume(){if(!state.sheet||state.busy)return;state.busy=true;renderSheet();var work=state.sheet.kind==='room'?resumeRoom(state.sheet.id,false):resumeRoutine(state.sheet.id,false);Promise.resolve(work).then(function(){state.busy=false;toast('Schoonmaakplanning hervat ✓');close();queue();}).catch(function(error){state.busy=false;toast((error&&error.message)||'Hervatten mislukt');renderSheet();});}

  function onClick(event){var target=event.target,closest=target&&target.closest?target.closest.bind(target):null;if(!closest)return;var routine=closest('[data-cleaning-routine-pause]');if(routine){event.preventDefault();event.stopPropagation();open('routine',routine.getAttribute('data-cleaning-routine-pause'));return;}var room=closest('[data-cleaning-room-pause]');if(room){event.preventDefault();event.stopPropagation();open('room',room.getAttribute('data-cleaning-room-pause'));return;}var overlay=document.getElementById('cleaning-pause-overlay');if(!overlay)return;if(closest('[data-cleaning-pause-close]')||target===overlay){event.preventDefault();close();return;}var choice=closest('[data-cleaning-pause-days]');if(choice&&!choice.disabled){event.preventDefault();runPause(Number(choice.getAttribute('data-cleaning-pause-days'))||0);return;}if(closest('[data-cleaning-pause-resume]')){event.preventDefault();runResume();}}
  function onKey(event){if(event.key==='Escape'&&state.sheet){event.preventDefault();close();}}

  function autoResume(snapshotValue){
    var snap=snapshotValue&&snapshotValue.data?snapshotValue:null;if(!snap||snap.ready!==true)return;var data=snap.data||{},stamp=now(),rooms=data.rooms||{},routines=data.routines||{};
    Object.keys(rooms).forEach(function(id){var row=rooms[id];if(!row||row.active===false||row.paused!==true||!Number(row.pauseUntilAt)||Number(row.pauseUntilAt)>stamp||state.auto['room:'+id])return;state.auto['room:'+id]=true;resumeRoom(id,true).catch(function(){}).finally(function(){delete state.auto['room:'+id];});});
    Object.keys(routines).forEach(function(id){var row=routines[id];if(!activeRoutine(row)||row.paused!==true||text(row.pauseSource)==='ROOM'||!Number(row.pauseUntilAt)||Number(row.pauseUntilAt)>stamp||state.auto['routine:'+id])return;state.auto['routine:'+id]=true;resumeRoutine(id,true).catch(function(){}).finally(function(){delete state.auto['routine:'+id];});});
  }
  function onRepository(event){state.repository=event&&event.detail||snapshot();autoResume(state.repository);queue();if(state.sheet)renderSheet();}
  function start(){if(window.__cleaningPauseExperienceStarted)return;window.__cleaningPauseExperienceStarted=true;ensureStyle();state.repository=snapshot();autoResume(state.repository);document.addEventListener('click',onClick,true);document.addEventListener('keydown',onKey,true);var target=document.getElementById('screen-cleaning')||document.documentElement;if(typeof MutationObserver!=='undefined'&&target){state.observer=new MutationObserver(queue);state.observer.observe(target,{childList:true,subtree:true});}window.addEventListener('familyapp:cleaning-repository',onRepository);queue();}

  window.CleaningPauseExperience={version:VERSION,start:start,pauseRoutine:pauseRoutine,resumeRoutine:resumeRoutine,pauseRoom:pauseRoom,resumeRoom:resumeRoom,_nextDueOnResume:nextDueOnResume,_pauseUntil:pauseUntil};start();
})();
