'use strict';
// ============================================================
// CLEANING PREMIUM FEEDBACK POLISH v0.1.0
// Presentation-only follow-up for the accepted Cleaning domain.
// - cinematic light/dark hero photography
// - compact room cards with metadata, canonical avatars and two CTAs
// - room photography on Planning cards without owning Planning state
// - presentation-only placement/default-display refinements
// Existing canonical edit/supply handlers remain the only writers.
// ============================================================
(function(){
  if(window.CleaningPremiumFeedback)return;

  var VERSION='0.1.0';
  var state={observer:null,queued:false};
  var ROOM_LABELS={
    'living-room':'Woonkamer',kitchen:'Keuken',bathroom:'Badkamer',bedroom:'Slaapkamer',
    'kids-room':'Kinderkamer',toilet:'Toilet',hall:'Hal',laundry:'Wasruimte',outdoor:'Balkon / tuin',custom:'Eigen ruimte'
  };

  function text(value){return String(value==null?'':value).trim();}
  function canonical(value){return text(value).toLocaleLowerCase('nl-NL').replace(/\s+/g,' ');}
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function unique(values){var seen={},out=[];(Array.isArray(values)?values:[]).forEach(function(value){var key=text(value);if(key&&!seen[key]){seen[key]=true;out.push(key);}});return out;}
  function data(){try{var repo=window.CleaningHouseholdRepository,snap=repo&&repo.snapshot?repo.snapshot():null;return snap&&snap.data||{};}catch(error){return{};}}
  function roomsMap(root){return root&&root.rooms&&typeof root.rooms==='object'?root.rooms:{};}
  function routinesMap(root){return root&&root.routines&&typeof root.routines==='object'?root.routines:{};}
  function occurrencesMap(root){return root&&root.occurrences&&typeof root.occurrences==='object'?root.occurrences:{};}
  function routinesForRoom(root,roomId){var routines=routinesMap(root),rows=[];Object.keys(routines).forEach(function(id){var row=routines[id];if(row&&row.active!==false&&text(row.roomId)===text(roomId))rows.push(Object.assign({id:id},row));});return rows;}
  function occurrenceAnchor(row){if(!row)return Number.MAX_SAFE_INTEGER;if(text(row.scheduledDate)){var parts=text(row.scheduledDate).split('-').map(Number);if(parts.length===3){var local=new Date(parts[0],parts[1]-1,parts[2],0,0,0,0).getTime();if(Number.isFinite(local))return local;}}return Number(row.scheduledStartAt)||Number(row.slotAt)||Number(row.flexibleWindow&&row.flexibleWindow.startAt)||Number(row.earliestDueAt)||Number.MAX_SAFE_INTEGER;}
  function activeOccurrenceForRoom(root,roomId){var rows=occurrencesMap(root),best=null,bestAt=Number.MAX_SAFE_INTEGER;Object.keys(rows).forEach(function(id){var row=rows[id];if(!row||text(row.roomId)!==text(roomId))return;var status=text(row.status).toUpperCase(),assignment=text(row.assignmentStatus).toUpperCase();if(status==='CANCELLED'||status==='SKIPPED'||status==='COMPLETED'||assignment==='COMPLETED'||assignment==='SKIPPED')return;var at=occurrenceAnchor(row);if(at<bestAt){best=Object.assign({id:id},row);bestAt=at;}});return best;}
  function roomMeta(root,roomId){var routines=routinesForRoom(root,roomId),occurrence=activeOccurrenceForRoom(root,roomId),parts=0,minutes=0;if(occurrence){var checklist=Array.isArray(occurrence.checklist)?occurrence.checklist:[];var ids=Array.isArray(occurrence.routineItemIds)?occurrence.routineItemIds:[];parts=checklist.length||ids.length;minutes=Math.max(0,Number(occurrence.estimatedMinutes)||0);}if(!parts){parts=routines.length;minutes=routines.reduce(function(sum,row){return sum+Math.max(0,Number(row&&row.estimatedMinutes)||0);},0);}return{parts:parts,minutes:minutes,occurrence:occurrence,routines:routines};}

  function bridgeMembers(){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[];return Array.isArray(rows)?rows:[];}catch(error){return[];}}
  function canonicalMember(uid){var id=text(uid);try{var identity=window.HouseholdIdentity;if(identity&&typeof identity.getMember==='function'){var row=identity.getMember(id);if(row)return row;}}catch(error){}return bridgeMembers().find(function(row){return text(row&&(row.uid||row.id))===id;})||null;}
  function memberName(member){return text(member&&(member.displayName||member.name||member.firstName))||'Gezinslid';}
  function initialsFor(uid,member){try{var resolver=window.FamilyAvatarIdentity;if(resolver&&typeof resolver.resolveInitials==='function'){var resolved=text(resolver.resolveInitials(text(uid)||member));if(resolved)return resolved;}}catch(error){}var name=memberName(member),parts=name.split(/\s+/).filter(Boolean);return (((parts[0]&&parts[0][0])||'?')+((parts.length>1&&parts[parts.length-1][0])||'')).toUpperCase();}
  function memberPhoto(uid,member){
    try{var resolver=window.FamilyAvatarIdentity;if(resolver&&typeof resolver.resolveAvatar==='function'){var resolved=text(resolver.resolveAvatar(text(uid)||member));if(resolved)return resolved;}}catch(error){}
    try{var identity=window.HouseholdIdentity;if(identity&&typeof identity.resolveAvatar==='function'){var identityResolved=text(identity.resolveAvatar(text(uid)||member));if(identityResolved)return identityResolved;}}catch(error){}
    if(!member)return'';
    var fields=['avatar','avatarUrl','photoURL','photoUrl','avatarURL','profilePhotoUrl','profileImageUrl','imageUrl'];
    for(var i=0;i<fields.length;i++){var value=text(member[fields[i]]);if(value&&(value.indexOf('data:')===0||value.indexOf('blob:')===0||value.indexOf('http')===0||value.indexOf('./')===0||value.indexOf('/')===0))return value;}
    return'';
  }
  function assigneesForRoom(meta){var ids=[],occ=meta&&meta.occurrence;if(occ&&Array.isArray(occ.assignmentUids))ids=ids.concat(occ.assignmentUids);(meta&&meta.routines||[]).forEach(function(row){var status=text(row.assignmentRequestStatus).toUpperCase(),mode=text(row.assignmentMode).toUpperCase(),uid=text(row.preferredAssigneeUid);if(uid&&(status==='ACCEPTED'||mode==='FIXED_PERSON'))ids.push(uid);});return unique(ids);}
  function avatarModels(uids){return unique(uids).map(function(uid){var member=canonicalMember(uid);return{uid:uid,name:memberName(member),photo:memberPhoto(uid,member),initials:initialsFor(uid,member)};});}
  function avatarMarkup(models){var shown=models.slice(0,3),extra=Math.max(0,models.length-shown.length);if(!models.length)return'';var html=shown.map(function(model){return model.photo?'<img class="cleaning-room-avatar" src="'+esc(model.photo)+'" alt="'+esc(model.name)+'" loading="lazy" referrerpolicy="no-referrer" data-avatar-fallback="'+esc(model.initials)+'" title="'+esc(model.name)+'">':'<span class="cleaning-room-avatar is-initial" title="'+esc(model.name)+'">'+esc(model.initials)+'</span>';}).join('');if(extra)html+='<span class="cleaning-room-avatar is-more">+'+extra+'</span>';return html;}
  function bindAvatarFallbacks(stack){if(!stack)return;var images=stack.querySelectorAll('img[data-avatar-fallback]');for(var i=0;i<images.length;i++){(function(img){if(img.__cleaningAvatarFallbackBound)return;img.__cleaningAvatarFallbackBound=true;img.addEventListener('error',function(){var span=document.createElement('span');span.className='cleaning-room-avatar is-initial';span.title=img.title||img.alt||'Gezinslid';span.textContent=text(img.getAttribute('data-avatar-fallback'))||'?';if(img.parentNode)img.parentNode.replaceChild(span,img);},{once:true});})(images[i]);}}

  function roomForVisibleName(root,name){var target=canonical(name),rooms=roomsMap(root),ids=Object.keys(rooms);for(var i=0;i<ids.length;i++){var room=rooms[ids[i]];if(!room||room.active===false)continue;var label=text(room.name)||ROOM_LABELS[text(room.type)]||'';if(canonical(label)===target)return Object.assign({id:ids[i]},room);}return null;}
  function decoratePlanningCards(root){var cards=document.querySelectorAll('#screen-cleaning .cleaning-plan-card');for(var i=0;i<cards.length;i++){var card=cards[i],heading=card.querySelector('.cleaning-plan-room h3'),room=roomForVisibleName(root,heading&&heading.textContent),type=text(room&&room.type);if(type&&type!=='custom')card.setAttribute('data-cleaning-room-visual',type);else card.removeAttribute('data-cleaning-room-visual');}}

  function forceBothPresentation(){var preferences=window.CleaningPreferencesUi;if(!preferences)return;preferences.currentMode=function(){return'BOTH';};preferences.format=function(minutes,count){var minuteText=Math.max(0,Math.round(Number(minutes)||0))+' min';var countValue=Math.max(0,Math.round(Number(count)||0));return minuteText+' · '+countValue+' '+(countValue===1?'taak':'taken');};}
  function moveAvailabilityToBottom(){var screen=document.getElementById('screen-cleaning');if(!screen||!screen.querySelector('[data-cleaning-tab="overview"].is-active'))return;var panel=screen.querySelector('.cleaning-panel'),card=panel&&panel.querySelector('[data-cleaning-availability-card]');if(panel&&card&&panel.lastElementChild!==card)panel.appendChild(card);}

  function ensureStyle(){
    var existing=document.getElementById('cleaning-premium-feedback-style');if(existing)return;
    var style=document.createElement('style');style.id='cleaning-premium-feedback-style';style.textContent='\n'
      +'#screen-cleaning [data-cleaning-preferences-row]{display:none!important}\n'
      +'/* House status hero: warm/light overlay in light mode, moody overlay in dark mode. */\n'
      +'#screen-cleaning .cleaning-overview-hero{background-image:linear-gradient(90deg,rgba(255,253,249,.92) 0%,rgba(255,253,249,.74) 38%,rgba(255,253,249,.32) 61%,rgba(255,253,249,.08) 82%,rgba(255,253,249,0) 100%),linear-gradient(180deg,rgba(255,255,255,.03),rgba(244,238,229,.18)),url("/src/assets/cleaning-heroes/house-light.webp")!important;background-size:100% 100%,100% 100%,cover!important;background-position:center,center,center!important;background-repeat:no-repeat!important;color:#17171c!important;border-color:rgba(90,70,125,.13)!important;box-shadow:0 20px 52px rgba(62,48,82,.14)!important}\n'
      +'#screen-cleaning .cleaning-overview-hero h2{color:#17171c!important;text-shadow:0 1px 14px rgba(255,255,255,.55)}#screen-cleaning .cleaning-overview-hero-copy>p{color:rgba(34,31,39,.76)!important}#screen-cleaning .cleaning-overview-kicker,#screen-cleaning .cleaning-overview-chip{background:rgba(255,255,255,.70)!important;border-color:rgba(70,58,88,.16)!important;box-shadow:0 5px 16px rgba(45,35,63,.07)}#screen-cleaning .cleaning-overview-kicker{color:#27232d!important}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-overview-hero,[data-theme*="dark"] #screen-cleaning .cleaning-overview-hero{background-image:linear-gradient(90deg,rgba(3,8,15,.94) 0%,rgba(3,8,15,.72) 44%,rgba(3,8,15,.25) 76%,rgba(3,8,15,.10) 100%),linear-gradient(180deg,rgba(2,7,13,.02),rgba(2,7,13,.46)),url("/src/assets/cleaning-heroes/house-dark.webp")!important;color:#fff!important;border-color:rgba(126,101,255,.18)!important;box-shadow:0 24px 62px rgba(0,0,0,.42)!important}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-overview-hero h2,[data-theme*="dark"] #screen-cleaning .cleaning-overview-hero h2{color:#fff!important;text-shadow:none}[data-theme="dark"] #screen-cleaning .cleaning-overview-hero-copy>p,[data-theme*="dark"] #screen-cleaning .cleaning-overview-hero-copy>p{color:rgba(255,255,255,.82)!important}[data-theme="dark"] #screen-cleaning .cleaning-overview-kicker,[data-theme="dark"] #screen-cleaning .cleaning-overview-chip,[data-theme*="dark"] #screen-cleaning .cleaning-overview-kicker,[data-theme*="dark"] #screen-cleaning .cleaning-overview-chip{background:rgba(7,13,21,.38)!important;border-color:rgba(255,255,255,.20)!important;box-shadow:none}[data-theme="dark"] #screen-cleaning .cleaning-overview-kicker,[data-theme*="dark"] #screen-cleaning .cleaning-overview-kicker{color:#fff!important}\n'
      +'/* Week plan hero. */\n'
      +'#screen-cleaning .cleaning-plan-hero{position:relative;overflow:hidden;isolation:isolate;background-image:linear-gradient(90deg,rgba(251,249,246,.985) 0%,rgba(251,249,246,.94) 44%,rgba(251,249,246,.62) 67%,rgba(251,249,246,.16) 100%),linear-gradient(180deg,rgba(255,255,255,.02),rgba(241,235,228,.22)),url("/src/assets/cleaning-heroes/plan-light.webp")!important;background-size:100% 100%,100% 100%,cover!important;background-position:center,center,center!important;background-repeat:no-repeat!important;border-color:rgba(91,64,156,.14)!important;box-shadow:0 18px 44px rgba(43,32,74,.10)!important}\n'
      +'#screen-cleaning .cleaning-plan-hero>*{position:relative;z-index:1}#screen-cleaning .cleaning-plan-stats>div{background:rgba(255,255,255,.70)!important;border-color:rgba(88,70,126,.13)!important;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);box-shadow:0 8px 22px rgba(33,25,54,.06)}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-plan-hero,[data-theme*="dark"] #screen-cleaning .cleaning-plan-hero{background-image:linear-gradient(90deg,rgba(5,10,18,.98) 0%,rgba(5,10,18,.90) 43%,rgba(5,10,18,.60) 68%,rgba(5,10,18,.20) 100%),linear-gradient(180deg,rgba(5,10,18,.02),rgba(5,10,18,.38)),url("/src/assets/cleaning-heroes/plan-dark.webp")!important;color:#f8f7fb!important;border-color:rgba(91,203,124,.22)!important;box-shadow:0 22px 56px rgba(0,0,0,.36)!important}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-intro,[data-theme="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-actions>span,[data-theme*="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-intro,[data-theme*="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-actions>span{color:rgba(244,241,250,.70)!important}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-plan-stats>div,[data-theme*="dark"] #screen-cleaning .cleaning-plan-stats>div{background:rgba(7,13,23,.68)!important;border-color:rgba(255,255,255,.12)!important;color:#fff!important;box-shadow:0 10px 26px rgba(0,0,0,.18)}\n'
      +'/* Compact room cards. */\n'
      +'#screen-cleaning .cleaning-room-card{min-height:0!important}#screen-cleaning .cleaning-room-card-main{min-height:92px!important;padding:12px 12px 8px!important;align-items:center!important;gap:10px!important}#screen-cleaning .cleaning-room-card-icon{width:44px!important;height:44px!important;border-radius:14px!important;font-size:20px!important}#screen-cleaning .cleaning-room-card-copy h3{font-size:16px!important}#screen-cleaning .cleaning-room-card-copy p.cleaning-room-card-meta{display:block!important;margin:5px 0 0!important;color:var(--color-muted,var(--cleaning-muted))!important;font-size:10px!important;font-weight:760!important;line-height:1.25!important}\n'
      +'#screen-cleaning .cleaning-room-edit-button,#screen-cleaning .cleaning-room-expand-button,#screen-cleaning .cleaning-room-card-actions>button{display:none!important}#screen-cleaning .cleaning-room-card-actions{min-width:76px!important;align-items:flex-end!important;justify-content:center!important;gap:7px!important}#screen-cleaning .cleaning-room-card-status{min-height:24px!important}\n'
      +'#screen-cleaning .cleaning-room-avatar-stack{display:flex;justify-content:flex-end;align-items:center;padding-right:2px;min-height:32px}#screen-cleaning .cleaning-room-avatar{width:32px;height:32px;display:grid;place-items:center;object-fit:cover;border-radius:50%;border:2px solid rgba(255,255,255,.92);background:linear-gradient(135deg,#7552ee,#9f69ff);color:#fff;font-size:8px;font-weight:900;box-shadow:0 5px 14px rgba(20,24,34,.18);margin-left:-8px;overflow:hidden}#screen-cleaning img.cleaning-room-avatar{display:block}#screen-cleaning .cleaning-room-avatar:first-child{margin-left:0}#screen-cleaning .cleaning-room-avatar.is-more{background:rgba(255,255,255,.86);color:#4a3b72;backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}\n'
      +'#screen-cleaning .cleaning-room-supplies-bar{display:grid!important;grid-template-columns:minmax(0,.86fr) minmax(0,1.34fr)!important;gap:8px!important;padding:0 12px 12px!important}#screen-cleaning .cleaning-room-primary-action,#screen-cleaning .cleaning-room-supplies-button{width:100%!important;min-width:0!important;min-height:46px!important;border-radius:13px!important;padding:7px 9px!important;box-shadow:0 7px 18px rgba(22,25,34,.08)!important;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}#screen-cleaning .cleaning-room-primary-action{border:1px solid color-mix(in srgb,var(--room-accent,var(--color-primary)) 25%,var(--cleaning-border));background:rgba(255,255,255,.84);color:var(--room-accent,var(--color-primary));font:inherit;font-size:10.5px;font-weight:900;cursor:pointer}#screen-cleaning .cleaning-room-supplies-button{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:5px!important;overflow:hidden!important;background:rgba(255,255,255,.86)!important}#screen-cleaning .cleaning-room-supplies-button strong{min-width:0!important;font-size:9.4px!important;line-height:1.1!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}#screen-cleaning .cleaning-room-supplies-button span{min-width:0!important;font-size:8.1px!important;line-height:1.05!important;white-space:nowrap!important;text-align:right!important}\n'
      +'#screen-cleaning .cleaning-room-manage-row{display:none;position:relative;z-index:3;padding:0 12px 10px;justify-content:flex-end}#screen-cleaning .cleaning-room-card.is-expanded .cleaning-room-manage-row{display:flex}#screen-cleaning .cleaning-room-manage-link{min-height:44px;border:0;background:transparent;color:var(--color-muted,var(--cleaning-muted));font:inherit;font-size:10px;font-weight:850;padding:0 4px;cursor:pointer;text-decoration:underline;text-decoration-color:color-mix(in srgb,var(--color-muted,var(--cleaning-muted)) 32%,transparent);text-underline-offset:3px}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-room-avatar,[data-theme*="dark"] #screen-cleaning .cleaning-room-avatar{border-color:rgba(7,13,22,.92);box-shadow:0 5px 16px rgba(0,0,0,.30)}[data-theme="dark"] #screen-cleaning .cleaning-room-avatar.is-more,[data-theme*="dark"] #screen-cleaning .cleaning-room-avatar.is-more{background:rgba(8,14,24,.82);color:#d9caff}[data-theme="dark"] #screen-cleaning .cleaning-room-primary-action,[data-theme="dark"] #screen-cleaning .cleaning-room-supplies-button,[data-theme*="dark"] #screen-cleaning .cleaning-room-primary-action,[data-theme*="dark"] #screen-cleaning .cleaning-room-supplies-button{background:rgba(8,14,24,.78)!important;border-color:rgba(255,255,255,.12)!important;color:#f8f7fb!important;box-shadow:0 8px 20px rgba(0,0,0,.20)!important}\n'
      +'@media(max-width:370px){#screen-cleaning .cleaning-room-card-main{min-height:88px!important;grid-template-columns:auto minmax(0,1fr) auto!important}#screen-cleaning .cleaning-room-avatar{width:29px;height:29px}#screen-cleaning .cleaning-room-card-actions{min-width:64px!important}#screen-cleaning .cleaning-room-supplies-bar{grid-template-columns:minmax(0,.78fr) minmax(0,1.42fr)!important}#screen-cleaning .cleaning-room-primary-action{font-size:9.3px!important;padding:6px!important}#screen-cleaning .cleaning-room-supplies-button{padding:6px 7px!important}#screen-cleaning .cleaning-room-supplies-button strong{font-size:8.6px!important}#screen-cleaning .cleaning-room-supplies-button span{font-size:7.4px!important}}\n'
      +'@media(prefers-reduced-motion:reduce){#screen-cleaning .cleaning-room-primary-action{transition:none!important}}\n';
    document.head.appendChild(style);
  }

  function decorateCard(card,root){
    var roomId=text(card.getAttribute('data-cleaning-room-id'));if(!roomId)return;var room=roomsMap(root)[roomId];if(!room||room.active===false)return;var meta=roomMeta(root,roomId),copy=card.querySelector('.cleaning-room-card-copy'),sub=copy&&copy.querySelector('p');
    if(sub){sub.classList.add('cleaning-room-card-meta');var label=meta.parts+' '+(meta.parts===1?'onderdeel':'onderdelen')+' · ± '+meta.minutes+' min';if(sub.textContent!==label)sub.textContent=label;}
    var actions=card.querySelector('.cleaning-room-card-actions');
    if(actions){var stack=actions.querySelector('[data-cleaning-room-avatars]'),models=avatarModels(assigneesForRoom(meta)),signature=models.map(function(model){return model.uid+'|'+model.photo+'|'+model.initials;}).join('||');if(models.length){if(!stack){stack=document.createElement('div');stack.className='cleaning-room-avatar-stack';stack.setAttribute('data-cleaning-room-avatars','1');actions.appendChild(stack);}if(stack.getAttribute('data-avatar-signature')!==signature){stack.setAttribute('data-avatar-signature',signature);stack.innerHTML=avatarMarkup(models);bindAvatarFallbacks(stack);}}else if(stack)stack.remove();}
    var supplies=card.querySelector('[data-cleaning-room-supplies-bar],.cleaning-room-supplies-bar');if(supplies){var primary=supplies.querySelector('[data-cleaning-room-primary-action]');if(!primary){primary=document.createElement('button');primary.type='button';primary.className='cleaning-room-primary-action';primary.setAttribute('data-cleaning-room-primary-action',roomId);supplies.insertBefore(primary,supplies.firstChild);}var expanded=card.classList.contains('is-expanded'),primaryLabel=expanded?'Sluit details':(meta.occurrence?'Bekijk beurt':'Bekijk kamer');if(primary.textContent!==primaryLabel)primary.textContent=primaryLabel;primary.setAttribute('aria-expanded',expanded?'true':'false');}
    var manage=card.querySelector('[data-cleaning-room-manage-row]');if(!manage){manage=document.createElement('div');manage.className='cleaning-room-manage-row';manage.setAttribute('data-cleaning-room-manage-row','1');manage.innerHTML='<button type="button" class="cleaning-room-manage-link" data-cleaning-room-manage="'+esc(roomId)+'">Kamer beheren</button>';var bar=card.querySelector('[data-cleaning-room-supplies-bar],.cleaning-room-supplies-bar');if(bar&&bar.parentNode)bar.parentNode.insertBefore(manage,bar.nextSibling);else card.appendChild(manage);}
  }

  function decorate(){
    state.queued=false;ensureStyle();forceBothPresentation();var root=data(),cards=document.querySelectorAll('#screen-cleaning .cleaning-room-card[data-cleaning-room-id]');for(var i=0;i<cards.length;i++)decorateCard(cards[i],root);decoratePlanningCards(root);moveAvailabilityToBottom();
  }
  function queue(){if(state.queued)return;state.queued=true;(window.requestAnimationFrame||function(callback){return window.setTimeout(callback,0);})(decorate);}
  function onClick(event){var target=event.target,closest=target&&target.closest?target.closest.bind(target):null;if(!closest)return;var primary=closest('[data-cleaning-room-primary-action]');if(primary){event.preventDefault();event.stopPropagation();var card=primary.closest('.cleaning-room-card');if(card){var expanded=!card.classList.contains('is-expanded');card.classList.toggle('is-expanded',expanded);primary.setAttribute('aria-expanded',expanded?'true':'false');}window.setTimeout(queue,0);return;}var manage=closest('[data-cleaning-room-manage]');if(manage){event.preventDefault();event.stopPropagation();var id=text(manage.getAttribute('data-cleaning-room-manage')),roomCard=manage.closest('.cleaning-room-card'),edit=roomCard&&roomCard.querySelector('[data-cleaning-room-edit="'+id+'"]');if(edit)edit.click();}}
  function start(){if(window.__cleaningPremiumFeedbackStarted)return;window.__cleaningPremiumFeedbackStarted=true;ensureStyle();forceBothPresentation();document.addEventListener('click',onClick,true);var target=document.getElementById('screen-cleaning')||document.documentElement;if(typeof MutationObserver!=='undefined'&&target){state.observer=new MutationObserver(queue);state.observer.observe(target,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});}window.addEventListener('familyapp:cleaning-repository',queue);window.addEventListener('familyapp:household-identity-synced',queue);window.addEventListener('familyapp:household-members-updated',queue);window.addEventListener('familyapp:avatar-updated',queue);queue();}

  window.CleaningPremiumFeedback={version:VERSION,start:start};start();
})();
