import './cleaningTurnRenderGuard.js?v=20260910-1';
'use strict';
// Dedicated Cleaning turn popup. One owner, one overlay, no DOM observers.
(function(){
  if(window.CleaningFreezeTrace)window.CleaningFreezeTrace.noteInit('CleaningTurnExperience');
  if(window.CleaningTurnExperience)return;
  var VERSION='1.0.1';
  var LABELS={'living-room':'Woonkamer',kitchen:'Keuken',bathroom:'Badkamer',bedroom:'Slaapkamer','kids-room':'Kinderkamer',toilet:'Toilet',hall:'Hal',laundry:'Wasruimte',outdoor:'Balkon / tuin',custom:'Kamer'};
  var state={open:false,roomId:'',occurrenceId:'',taskId:'',started:false,bodyOverflow:null,write:null,openingSupplies:false};
  function text(v){return String(v==null?'':v).trim();}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function raf(fn){return (window.requestAnimationFrame||function(cb){return setTimeout(cb,0);})(fn);}
  function data(){try{var r=window.CleaningHouseholdRepository,s=r&&r.snapshot?r.snapshot():null;return s&&s.data||{};}catch(e){return{};}}
  function room(root,id){var row=root&&root.rooms&&root.rooms[id];return row&&row.active!==false?Object.assign({id:id},row):null;}
  function roomName(row){return text(row&&row.name)||LABELS[text(row&&row.type)]||'Kamer';}
  function occurrenceAnchor(row){if(!row)return Number.MAX_SAFE_INTEGER;var d=text(row.scheduledDate);if(d){var p=d.split('-').map(Number);if(p.length===3){var t=new Date(p[0],p[1]-1,p[2]).getTime();if(Number.isFinite(t))return t;}}return Number(row.scheduledStartAt)||Number(row.slotAt)||Number(row.flexibleWindow&&row.flexibleWindow.startAt)||Number(row.earliestDueAt)||Number.MAX_SAFE_INTEGER;}
  function nextOccurrence(root,roomId){var map=root&&root.occurrences||{},best=null,bestAt=Number.MAX_SAFE_INTEGER;Object.keys(map).forEach(function(id){var row=map[id];if(!row||text(row.roomId)!==text(roomId))return;var s=text(row.status).toUpperCase(),a=text(row.assignmentStatus).toUpperCase();if(s==='CANCELLED'||s==='SKIPPED'||s==='COMPLETED'||a==='COMPLETED'||a==='SKIPPED')return;var at=occurrenceAnchor(row);if(at<bestAt){best=Object.assign({id:id},row);bestAt=at;}});return best;}
  function tasks(){return Array.isArray(window.taskData)?window.taskData:[];}
  function findTask(id){var wanted=text(id);return tasks().find(function(row){return row&&text(row.id||row._key)===wanted;})||null;}
  function taskForOccurrence(occ){if(!occ)return null;var id=text(occ.id);return tasks().find(function(t){if(!t)return false;if(text(t.cleaningOccurrenceId)===id||text(t.sourceId)===id)return true;return Array.isArray(t.cleaningOccurrenceIds)&&t.cleaningOccurrenceIds.some(function(v){return text(v)===id;});})||null;}
  function replaceTask(saved){if(!saved)return;var wanted=text(saved.id||saved._key),rows=tasks();for(var i=0;i<rows.length;i++)if(text(rows[i]&&(rows[i].id||rows[i]._key))===wanted){rows[i]=saved;return;}}
  function routines(root,roomId){var map=root&&root.routines||{},out=[];Object.keys(map).forEach(function(id){var row=map[id];if(row&&row.active!==false&&text(row.roomId)===text(roomId))out.push(Object.assign({id:id},row));});return out;}
  function when(occ){if(!occ)return'Geen actieve beurt';var d=text(occ.scheduledDate),tm=text(occ.scheduledTime||occ.time);if(d){var p=d.split('-').map(Number),date=p.length===3?new Date(p[0],p[1]-1,p[2]):null,label=date&&Number.isFinite(date.getTime())?date.toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'}):d;return label+(tm?' · '+tm:'');}var stamp=Number(occ.scheduledStartAt)||Number(occ.slotAt)||0;if(stamp){var d2=new Date(stamp);return d2.toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'})+' · '+d2.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});}return'Gepland';}
  function memberName(uid){var rows=[];try{var b=window.HouseholdIdentityFirebaseBridge;rows=b&&b.getMembers?b.getMembers():[];}catch(e){}var id=text(uid),m=(Array.isArray(rows)?rows:[]).find(function(row){return text(row&&(row.uid||row.id))===id;});return text(m&&(m.displayName||m.name||m.firstName))||'Gezinslid';}
  function assigned(occ){var ids=occ&&Array.isArray(occ.assignmentUids)?occ.assignmentUids.filter(Boolean):[];return ids.length?ids.slice(0,2).map(memberName).join(' & ')+(ids.length>2?' +'+(ids.length-2):''):'Nog niet toegewezen';}
  function model(){var root=data(),r=room(root,state.roomId);if(!r)return null;var occ=state.occurrenceId&&root.occurrences&&root.occurrences[state.occurrenceId]?Object.assign({id:state.occurrenceId},root.occurrences[state.occurrenceId]):nextOccurrence(root,state.roomId);var task=state.taskId?findTask(state.taskId):taskForOccurrence(occ),rs=routines(root,state.roomId),items=task&&Array.isArray(task.subtasks)?task.subtasks.filter(Boolean):[];if(!items.length&&occ&&Array.isArray(occ.checklist))items=occ.checklist.map(function(x){return{title:text(x&&x.title)||'Schoonmaakonderdeel',done:x&&x.completed===true,readonly:true};});if(!items.length)items=rs.map(function(x){return{title:text(x.title)||'Schoonmaakonderdeel',done:false,readonly:true};});return{room:r,occurrence:occ,task:task,routines:rs,items:items};}

  function style(){if(document.getElementById('cleaning-turn-experience-style'))return;var s=document.createElement('style');s.id='cleaning-turn-experience-style';s.textContent='\n'
    +'#cleaning-turn-overlay{position:fixed;inset:0;z-index:9850;display:none;background:rgba(13,16,21,.58);overscroll-behavior:none}#cleaning-turn-overlay.is-open{display:block}'
    +'#cleaning-turn-overlay .ct-shell{--photo:url("/src/assets/cleaning-rooms/room-atlas-light.webp");--x:0%;--y:0%;position:absolute;inset:0;margin:auto;width:100%;max-width:560px;height:100dvh;display:flex;flex-direction:column;background:#f7f6f3;color:#20232a;overflow:hidden;box-shadow:0 20px 70px rgba(0,0,0,.22)}'
    +'#cleaning-turn-overlay[data-room="kitchen"] .ct-shell{--x:50%;--y:0%}#cleaning-turn-overlay[data-room="bathroom"] .ct-shell{--x:100%;--y:0%}#cleaning-turn-overlay[data-room="bedroom"] .ct-shell{--x:0%;--y:50%}#cleaning-turn-overlay[data-room="kids-room"] .ct-shell{--x:50%;--y:50%}#cleaning-turn-overlay[data-room="toilet"] .ct-shell{--x:100%;--y:50%}#cleaning-turn-overlay[data-room="hall"] .ct-shell{--x:0%;--y:100%}#cleaning-turn-overlay[data-room="laundry"] .ct-shell{--x:50%;--y:100%}#cleaning-turn-overlay[data-room="outdoor"] .ct-shell{--x:100%;--y:100%}'
    +'#cleaning-turn-overlay .ct-hero{position:relative;flex:0 0 214px;background-image:linear-gradient(180deg,rgba(0,0,0,.02),rgba(0,0,0,.08) 45%,rgba(0,0,0,.56)),var(--photo);background-size:100% 100%,300% 300%;background-position:center,var(--x) var(--y);background-repeat:no-repeat}#cleaning-turn-overlay .ct-close{position:absolute;z-index:3;top:max(16px,env(safe-area-inset-top));left:16px;width:46px;height:46px;border-radius:50%;border:1px solid rgba(255,255,255,.58);background:rgba(255,255,255,.94);color:#20242a;font-size:20px;box-shadow:0 8px 24px rgba(0,0,0,.15);touch-action:manipulation}#cleaning-turn-overlay .ct-hero-copy{position:absolute;left:20px;right:20px;bottom:18px;color:#fff;text-shadow:0 2px 14px rgba(0,0,0,.35)}#cleaning-turn-overlay .ct-kicker{font-size:10px;font-weight:900;letter-spacing:.09em;text-transform:uppercase;margin-bottom:6px}#cleaning-turn-overlay .ct-title{margin:0;font-size:25px;line-height:1.08;font-weight:900}#cleaning-turn-overlay .ct-when{margin-top:6px;font-size:12px;font-weight:700}'
    +'#cleaning-turn-overlay .ct-scroll{flex:1;min-height:0;overflow-y:auto;-webkit-overflow-scrolling:touch;overscroll-behavior:contain;touch-action:pan-y;padding:16px 16px calc(24px + env(safe-area-inset-bottom));scrollbar-width:none}#cleaning-turn-overlay .ct-scroll::-webkit-scrollbar{display:none}'
    +'#cleaning-turn-overlay .ct-meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:12px}#cleaning-turn-overlay .ct-card,#cleaning-turn-overlay .ct-progress,#cleaning-turn-overlay .ct-list{background:#fff;border:1px solid rgba(35,40,48,.08);box-shadow:0 7px 22px rgba(31,35,42,.045)}#cleaning-turn-overlay .ct-card{min-height:68px;padding:12px;border-radius:17px}#cleaning-turn-overlay .ct-card span{display:block;color:#7b8088;font-size:9px;font-weight:850;text-transform:uppercase}#cleaning-turn-overlay .ct-card strong{display:block;margin-top:5px;font-size:13px}'
    +'#cleaning-turn-overlay .ct-progress{padding:13px;border-radius:17px;margin-bottom:12px}#cleaning-turn-overlay .ct-progress-head{display:flex;justify-content:space-between;gap:10px;font-size:12px;margin-bottom:8px}#cleaning-turn-overlay .ct-progress-head span{color:#777c84;font-weight:800}#cleaning-turn-overlay .ct-track{height:9px;background:#e9ebe8;border-radius:99px;overflow:hidden}#cleaning-turn-overlay .ct-fill{height:100%;background:linear-gradient(90deg,#4bb66b,#32a95a);border-radius:inherit}'
    +'#cleaning-turn-overlay .ct-start{width:100%;min-height:54px;margin-bottom:12px;border:0;border-radius:16px;background:linear-gradient(135deg,#46b665,#2f9954);color:#fff;font-size:14px;font-weight:900;box-shadow:0 11px 27px rgba(48,153,85,.22);touch-action:manipulation}#cleaning-turn-overlay .ct-start.is-started{background:#eaf6ed;color:#2b8050;box-shadow:none;border:1px solid #cfe9d6}'
    +'#cleaning-turn-overlay .ct-status{display:none;margin-bottom:10px;padding:9px 11px;border-radius:12px;font-size:11px;font-weight:750}#cleaning-turn-overlay .ct-status.show{display:block;background:#f2f4f6;color:#66707a}#cleaning-turn-overlay .ct-status.error{background:#fff0f0;color:#a93b3b}'
    +'#cleaning-turn-overlay .ct-head{display:flex;justify-content:space-between;gap:10px;align-items:end;margin:0 2px 8px}#cleaning-turn-overlay .ct-head strong{font-size:15px}#cleaning-turn-overlay .ct-head span{font-size:10px;color:#7c8189;font-weight:750}#cleaning-turn-overlay .ct-list{overflow:hidden;border-radius:18px}#cleaning-turn-overlay .ct-row{display:flex;align-items:center;gap:11px;min-height:58px;padding:10px 13px;border-bottom:1px solid #efefec}#cleaning-turn-overlay .ct-row:last-child{border-bottom:0}#cleaning-turn-overlay .ct-check{appearance:none;-webkit-appearance:none;width:29px;height:29px;min-width:29px;border:2px solid #cbd0d4;border-radius:50%;background:#fff;color:#fff;padding:0;touch-action:manipulation}#cleaning-turn-overlay .ct-check.done{background:#3fac62;border-color:#3fac62}#cleaning-turn-overlay .ct-check.done:after{content:"✓";font-weight:900}#cleaning-turn-overlay .ct-check:disabled{opacity:.5}#cleaning-turn-overlay .ct-copy{min-width:0;flex:1;font-size:13px;font-weight:750}#cleaning-turn-overlay .ct-row.done .ct-copy{text-decoration:line-through;color:#898e94}#cleaning-turn-overlay .ct-empty{padding:16px;border-radius:18px;background:#fff;color:#767b82;font-size:12px}'
    +'#cleaning-turn-overlay .ct-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}#cleaning-turn-overlay .ct-action{min-height:50px;border:1px solid #dddde3;border-radius:15px;background:#fff;color:#4e426d;font-size:12px;font-weight:850;touch-action:manipulation}#cleaning-turn-overlay .ct-action.primary{background:#f0edfb;border-color:#ded6f6;color:#5c49b5}#cleaning-turn-overlay .ct-action.complete{background:#eaf6ed;border-color:#cfe9d6;color:#2b8050}#cleaning-turn-overlay .ct-action:disabled{opacity:.45}'
    +'[data-theme*="dark"] #cleaning-turn-overlay{background:rgba(0,0,0,.72)}[data-theme*="dark"] #cleaning-turn-overlay .ct-shell{--photo:url("/src/assets/cleaning-rooms/room-atlas-dark.webp");background:#070c14;color:#f5f6f8}[data-theme*="dark"] #cleaning-turn-overlay .ct-card,[data-theme*="dark"] #cleaning-turn-overlay .ct-progress,[data-theme*="dark"] #cleaning-turn-overlay .ct-list,[data-theme*="dark"] #cleaning-turn-overlay .ct-empty{background:#0d1420;border-color:rgba(255,255,255,.09);box-shadow:0 8px 28px rgba(0,0,0,.22)}[data-theme*="dark"] #cleaning-turn-overlay .ct-card span,[data-theme*="dark"] #cleaning-turn-overlay .ct-head span,[data-theme*="dark"] #cleaning-turn-overlay .ct-progress-head span{color:#929aa6}[data-theme*="dark"] #cleaning-turn-overlay .ct-row{border-color:rgba(255,255,255,.07)}[data-theme*="dark"] #cleaning-turn-overlay .ct-check{background:#0a111b;border-color:#4a5360}[data-theme*="dark"] #cleaning-turn-overlay .ct-check.done{background:#40b567;border-color:#40b567}[data-theme*="dark"] #cleaning-turn-overlay .ct-track{background:#19222e}[data-theme*="dark"] #cleaning-turn-overlay .ct-start.is-started,[data-theme*="dark"] #cleaning-turn-overlay .ct-action.complete{background:#10261a;border-color:#225d38;color:#8ee8aa}[data-theme*="dark"] #cleaning-turn-overlay .ct-action{background:#0d1420;border-color:rgba(255,255,255,.11);color:#d8ccff}[data-theme*="dark"] #cleaning-turn-overlay .ct-action.primary{background:#17152a;border-color:#352d61;color:#c3b4ff}'
    +'@media(min-width:650px){#cleaning-turn-overlay .ct-shell{height:min(860px,calc(100dvh - 32px));border-radius:26px;inset:16px}.ct-hero{border-radius:26px 26px 0 0}}';document.head.appendChild(s);}
  function overlay(){style();var o=document.getElementById('cleaning-turn-overlay');if(o)return o;o=document.createElement('div');o.id='cleaning-turn-overlay';o.setAttribute('aria-hidden','true');o.innerHTML='<div class="ct-shell" role="dialog" aria-modal="true" aria-label="Schoonmaakbeurt"><div class="ct-hero"><button type="button" class="ct-close" data-ct-close aria-label="Sluiten">×</button><div class="ct-hero-copy"><div class="ct-kicker" data-ct-kicker>Gepland</div><h2 class="ct-title" data-ct-title></h2><div class="ct-when" data-ct-when></div></div></div><div class="ct-scroll"><div data-ct-content></div></div></div>';o.addEventListener('click',onOverlayClick);document.body.appendChild(o);return o;}
  function rowMarkup(item,index,editable){var done=!!(item&&(item.done===true||item.completed===true)),title=text(item&&item.title)||'Schoonmaakonderdeel';return '<div class="ct-row'+(done?' done':'')+'" data-ct-row><button type="button" class="ct-check'+(done?' done':'')+'" data-ct-toggle="'+index+'" aria-pressed="'+(done?'true':'false')+'"'+(!editable||item.readonly?' disabled':'')+'></button><div class="ct-copy">'+esc(title)+'</div></div>';}
  function render(){if(!state.open)return;var m=model(),o=document.getElementById('cleaning-turn-overlay');if(!m||!o){close();return;}o.setAttribute('data-room',text(m.room.type)||'custom');var title=o.querySelector('[data-ct-title]'),date=o.querySelector('[data-ct-when]'),kicker=o.querySelector('[data-ct-kicker]');if(title)title.textContent=roomName(m.room)+' schoonmaken';if(date)date.textContent=when(m.occurrence);if(kicker)kicker.textContent=state.started?'Bezig':'Gepland';var editable=!!(m.task&&state.taskId&&window.TaskSharedData&&typeof window.TaskSharedData.update==='function'),items=m.items||[],done=items.filter(function(x){return x&&(x.done===true||x.completed===true);}).length,total=items.length,pct=total?Math.round(done/total*100):0,min=Math.max(0,Math.round(Number(m.task&&m.task.estimatedMinutes)||Number(m.occurrence&&m.occurrence.estimatedMinutes)||m.routines.reduce(function(sum,r){return sum+Math.max(0,Number(r&&r.estimatedMinutes)||0);},0))),allDone=total>0&&done===total,taskDone=!!(m.task&&m.task.done),content=o.querySelector('[data-ct-content]');content.innerHTML='<div class="ct-meta"><div class="ct-card"><span>Toegewezen aan</span><strong>'+esc(assigned(m.occurrence))+'</strong></div><div class="ct-card"><span>Geschatte tijd</span><strong>± '+min+' min · '+total+' '+(total===1?'onderdeel':'onderdelen')+'</strong></div></div><div class="ct-progress"><div class="ct-progress-head"><strong>Voortgang</strong><span data-ct-progress>'+done+' / '+total+' klaar</span></div><div class="ct-track"><div class="ct-fill" data-ct-fill style="width:'+pct+'%"></div></div></div><button type="button" class="ct-start'+(state.started?' is-started':'')+'" data-ct-start>'+(state.started?'✓ Schoonmaken gestart':'Start schoonmaken')+'</button><div class="ct-status" data-ct-status></div><div class="ct-head"><strong>Onderdelen</strong><span>'+(editable?'Direct opslaan':'Alleen bekijken')+'</span></div>'+(items.length?'<div class="ct-list">'+items.map(function(x,i){return rowMarkup(x,i,editable);}).join('')+'</div>':'<div class="ct-empty">Voor deze kamer staan nog geen schoonmaakonderdelen klaar.</div>')+'<div class="ct-actions"><button type="button" class="ct-action primary" data-ct-supplies>Benodigdheden</button><button type="button" class="ct-action'+(allDone?' complete':'')+'" data-ct-complete'+(!editable||(!allDone&&!taskDone)?' disabled':'')+'>'+(taskDone?'Heropen beurt':(allDone?'Beurt voltooien':'Eerst alles afronden'))+'</button></div>';}
  function status(msg,error){var o=document.getElementById('cleaning-turn-overlay'),n=o&&o.querySelector('[data-ct-status]');if(!n)return;n.textContent=text(msg);n.className='ct-status'+(msg?' show':'')+(error?' error':'');}
  function start(){if(!state.open||state.started)return;state.started=true;var o=document.getElementById('cleaning-turn-overlay'),b=o&&o.querySelector('[data-ct-start]'),k=o&&o.querySelector('[data-ct-kicker]');if(b){b.classList.add('is-started');b.textContent='✓ Schoonmaken gestart';}if(k)k.textContent='Bezig';}
  function visibleProgress(){var o=document.getElementById('cleaning-turn-overlay');if(!o)return;var total=o.querySelectorAll('[data-ct-row]').length,done=o.querySelectorAll('[data-ct-row].done').length,l=o.querySelector('[data-ct-progress]'),f=o.querySelector('[data-ct-fill]'),c=o.querySelector('[data-ct-complete]');if(l)l.textContent=done+' / '+total+' klaar';if(f)f.style.width=(total?Math.round(done/total*100):0)+'%';if(c&&!/Heropen/.test(c.textContent)){var all=total>0&&done===total;c.disabled=!all;c.classList.toggle('complete',all);c.textContent=all?'Beurt voltooien':'Eerst alles afronden';}}
  function runWrite(){var p=state.write;if(!p||p.inFlight)return;var shared=window.TaskSharedData;var trace=window.CleaningFreezeTrace;if(!shared||typeof shared.update!=='function'){state.write=null;status('Opslaan is tijdelijk niet beschikbaar.',true);render();return;}p.inFlight=true;var version=p.version,id=p.taskId,payload=p.subtasks.map(function(x){return Object.assign({},x);}),correlationId=p.correlationId;if(trace)trace.mark('turn-experience-write-begin',{correlationId:correlationId,version:version});status('Wijzigingen opslaan…',false);Promise.resolve(shared.update(id,{subtasks:payload})).then(function(saved){if(trace)trace.mark('turn-experience-write-resolved',{correlationId:correlationId,version:version});replaceTask(saved);var current=state.write;if(!current||current.taskId!==id)return;current.inFlight=false;if(current.version!==version){raf(runWrite);return;}state.write=null;if(trace)trace.endWrite(correlationId);if(state.open)status('',false);}).catch(function(e){if(trace){trace.mark('turn-experience-write-error',{correlationId:correlationId,message:(e&&e.message)||String(e)});trace.endWrite(correlationId);}state.write=null;if(state.open){status((e&&e.message)||'Wijziging kon niet worden opgeslagen.',true);render();}});}
  function toggle(button){if(!state.open)return;var m=model(),task=m&&m.task;if(!task||!state.taskId)return;var index=Number(button.getAttribute('data-ct-toggle'));if(!Number.isInteger(index))return;var trace=window.CleaningFreezeTrace;var pending=state.write&&state.write.taskId===state.taskId?state.write:null,base=pending?pending.subtasks:(Array.isArray(task.subtasks)?task.subtasks:[]);if(!base[index])return;var next=base.map(function(x){return Object.assign({},x);}),nextDone=!(next[index].done===true);next[index].done=nextDone;var row=button.closest('[data-ct-row]');button.classList.toggle('done',nextDone);button.setAttribute('aria-pressed',nextDone?'true':'false');if(row)row.classList.toggle('done',nextDone);visibleProgress();if(!pending){var correlationId=trace?trace.beginWrite():null;if(trace)trace.mark('turn-experience-checkbox-toggle',{correlationId:correlationId,index:index,nextDone:nextDone});pending={taskId:state.taskId,subtasks:next,version:1,inFlight:false,correlationId:correlationId};state.write=pending;}else{if(trace)trace.mark('turn-experience-checkbox-toggle',{correlationId:pending.correlationId,index:index,nextDone:nextDone,batched:true});pending.subtasks=next;pending.version++;}if(!pending.inFlight)raf(runWrite);}
  function complete(button){if(!state.open||button.disabled)return;if(state.write){status('De laatste wijziging wordt nog opgeslagen…',false);return;}var m=model(),task=m&&m.task,shared=window.TaskSharedData;if(!task||!shared||typeof shared.update!=='function')return;button.disabled=true;status(task.done?'Beurt heropenen…':'Beurt afronden…',false);Promise.resolve(shared.update(text(task.id||task._key),{done:!task.done})).then(function(saved){replaceTask(saved);if(saved&&saved.done){close();if(typeof window.showToast==='function')window.showToast('Schoonmaakbeurt afgerond ✓');}else{status('',false);render();}}).catch(function(e){button.disabled=false;status((e&&e.message)||'Beurt kon niet worden bijgewerkt.',true);});}
  function supplies(){if(!state.open||state.openingSupplies)return;var id=state.roomId;state.openingSupplies=true;close();raf(function(){var open=function(){var x=window.CleaningSupplyExperience;if(x&&typeof x.openRoom==='function'){state.openingSupplies=false;x.openRoom(id);return;}state.openingSupplies=false;if(typeof window.showToast==='function')window.showToast('Benodigdheden konden niet worden geopend.');};if(window.CleaningSupplyExperience){open();return;}import('./cleaningSupplyExperience.js?v=2').then(open).catch(function(){state.openingSupplies=false;if(typeof window.showToast==='function')window.showToast('Benodigdheden konden niet worden geopend.');});});}
  function onOverlayClick(e){var t=e.target;if(!t||!t.closest)return;if(t.closest('[data-ct-close]')){e.preventDefault();close();return;}if(t.closest('[data-ct-start]')){e.preventDefault();start();return;}var check=t.closest('[data-ct-toggle]');if(check){e.preventDefault();toggle(check);return;}var done=t.closest('[data-ct-complete]');if(done){e.preventDefault();complete(done);return;}if(t.closest('[data-ct-supplies]')){e.preventDefault();supplies();}}
  function onPrimaryClick(e){var t=e.target;if(!t||!t.closest)return;var b=t.closest('#screen-cleaning [data-cleaning-room-primary-action]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openRoom(b.getAttribute('data-cleaning-room-primary-action'));}
  function openRoom(id){id=text(id);if(!id)return false;var root=data(),r=room(root,id);if(!r)return false;var occ=nextOccurrence(root,id),task=taskForOccurrence(occ),o=overlay();state.open=true;state.roomId=id;state.occurrenceId=occ?text(occ.id):'';state.taskId=task?text(task.id||task._key):'';state.started=false;state.openingSupplies=false;if(state.bodyOverflow===null)state.bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';o.setAttribute('aria-hidden','false');o.classList.add('is-open');if(window.CleaningFreezeTrace)window.CleaningFreezeTrace.mark('turn-experience-open',{roomId:id});render();var sc=o.querySelector('.ct-scroll');if(sc)sc.scrollTop=0;return true;}
  function close(){var o=document.getElementById('cleaning-turn-overlay');state.open=false;state.roomId='';state.occurrenceId='';state.taskId='';state.started=false;if(o){o.classList.remove('is-open');o.setAttribute('aria-hidden','true');}if(state.bodyOverflow!==null){document.body.style.overflow=state.bodyOverflow;state.bodyOverflow=null;}if(window.CleaningFreezeTrace)window.CleaningFreezeTrace.mark('turn-experience-close',{});try{window.dispatchEvent(new CustomEvent('familyapp:cleaning-turn-closed'));}catch(e){}}
  function refresh(){if(state.open&&!state.write)render();}
  document.addEventListener('click',onPrimaryClick,true);document.addEventListener('keydown',function(e){if(state.open&&e.key==='Escape'){e.preventDefault();close();}});window.addEventListener('familyapp:cleaning-repository',refresh);
  window.CleaningTurnExperience={version:VERSION,openRoom:openRoom,close:close,refresh:refresh,isOpen:function(){return state.open;}};
})();