'use strict';
// ============================================================
// CLEANING PREMIUM FEEDBACK POLISH v0.1.0
// Presentation-only follow-up for the accepted Cleaning domain.
// - cinematic light/dark hero photography
// - compact room cards with metadata, assignee avatars and two CTAs
// - preserves canonical room edit/expand/supply handlers through proxies
// No canonical Cleaning state or writer is introduced here.
// ============================================================
(function(){
  if(window.CleaningPremiumFeedback)return;

  var VERSION='0.1.0';
  var state={observer:null,queued:false};

  function text(value){return String(value==null?'':value).trim();}
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function unique(values){var seen={},out=[];(Array.isArray(values)?values:[]).forEach(function(value){var key=text(value);if(key&&!seen[key]){seen[key]=true;out.push(key);}});return out;}
  function data(){try{var repo=window.CleaningHouseholdRepository,snap=repo&&repo.snapshot?repo.snapshot():null;return snap&&snap.data||{};}catch(error){return{};}}
  function roomsMap(root){return root&&root.rooms&&typeof root.rooms==='object'?root.rooms:{};}
  function routinesMap(root){return root&&root.routines&&typeof root.routines==='object'?root.routines:{};}
  function occurrencesMap(root){return root&&root.occurrences&&typeof root.occurrences==='object'?root.occurrences:{};}
  function routinesForRoom(root,roomId){var routines=routinesMap(root),rows=[];Object.keys(routines).forEach(function(id){var row=routines[id];if(row&&row.active!==false&&text(row.roomId)===text(roomId))rows.push(Object.assign({id:id},row));});return rows;}
  function occurrenceAnchor(row){if(!row)return Number.MAX_SAFE_INTEGER;if(text(row.scheduledDate)){var parts=text(row.scheduledDate).split('-').map(Number);if(parts.length===3){var local=new Date(parts[0],parts[1]-1,parts[2],0,0,0,0).getTime();if(Number.isFinite(local))return local;}}return Number(row.scheduledStartAt)||Number(row.slotAt)||Number(row.flexibleWindow&&row.flexibleWindow.startAt)||Number(row.earliestDueAt)||Number.MAX_SAFE_INTEGER;}
  function activeOccurrenceForRoom(root,roomId){var rows=occurrencesMap(root),best=null,bestAt=Number.MAX_SAFE_INTEGER;Object.keys(rows).forEach(function(id){var row=rows[id];if(!row||text(row.roomId)!==text(roomId))return;var status=text(row.status).toUpperCase(),assignment=text(row.assignmentStatus).toUpperCase();if(status==='CANCELLED'||status==='SKIPPED'||status==='COMPLETED'||assignment==='COMPLETED'||assignment==='SKIPPED')return;var at=occurrenceAnchor(row);if(at<bestAt){best=Object.assign({id:id},row);bestAt=at;}});return best;}
  function roomMeta(root,roomId){var routines=routinesForRoom(root,roomId),occurrence=activeOccurrenceForRoom(root,roomId),parts=0,minutes=0;if(occurrence){var checklist=Array.isArray(occurrence.checklist)?occurrence.checklist:[];var ids=Array.isArray(occurrence.routineItemIds)?occurrence.routineItemIds:[];parts=checklist.length||ids.length;minutes=Math.max(0,Number(occurrence.estimatedMinutes)||0);}if(!parts){parts=routines.length;minutes=routines.reduce(function(sum,row){return sum+Math.max(0,Number(row&&row.estimatedMinutes)||0);},0);}return{parts:parts,minutes:minutes,occurrence:occurrence,routines:routines};}

  function members(){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[];return Array.isArray(rows)?rows:[];}catch(error){return[];}}
  function memberByUid(uid){var id=text(uid);return members().find(function(row){return text(row&&(row.uid||row.id))===id;})||null;}
  function memberName(member){return text(member&&(member.displayName||member.name||member.firstName))||'Gezinslid';}
  function memberPhoto(member){if(!member)return'';var fields=['photoURL','photoUrl','avatarUrl','avatarURL','profilePhotoUrl','profileImageUrl','imageUrl','avatar'];for(var i=0;i<fields.length;i++){var value=member[fields[i]];if(typeof value==='string'&&/^https?:\/\//i.test(value))return value;}return'';}
  function initials(member){var name=memberName(member),parts=name.split(/\s+/).filter(Boolean);return((parts[0]&&parts[0][0])||'?')+((parts.length>1&&parts[parts.length-1][0])||'');}
  function assigneesForRoom(meta){var ids=[],occ=meta&&meta.occurrence;if(occ&&Array.isArray(occ.assignmentUids))ids=ids.concat(occ.assignmentUids);(meta&&meta.routines||[]).forEach(function(row){var status=text(row.assignmentRequestStatus).toUpperCase(),mode=text(row.assignmentMode).toUpperCase(),uid=text(row.preferredAssigneeUid);if(uid&&(status==='ACCEPTED'||mode==='FIXED_PERSON'))ids.push(uid);});return unique(ids);}
  function avatarMarkup(uids){var ids=unique(uids),shown=ids.slice(0,3),extra=Math.max(0,ids.length-shown.length);if(!ids.length)return'';var html=shown.map(function(uid){var member=memberByUid(uid),photo=memberPhoto(member),name=memberName(member);return photo?'<img class="cleaning-room-avatar" src="'+esc(photo)+'" alt="'+esc(name)+'" loading="lazy" referrerpolicy="no-referrer">':'<span class="cleaning-room-avatar is-initial" title="'+esc(name)+'">'+esc(initials(member))+'</span>';}).join('');if(extra)html+='<span class="cleaning-room-avatar is-more">+'+extra+'</span>';return html;}

  function ensureStyle(){
    var existing=document.getElementById('cleaning-premium-feedback-style');if(existing)return;
    var style=document.createElement('style');style.id='cleaning-premium-feedback-style';style.textContent='\n'
      +'/* House status hero */\n'
      +'#screen-cleaning .cleaning-overview-hero{background-image:linear-gradient(90deg,rgba(7,13,21,.88) 0%,rgba(7,13,21,.68) 44%,rgba(7,13,21,.22) 76%,rgba(7,13,21,.08) 100%),linear-gradient(180deg,rgba(6,12,19,.04),rgba(6,12,19,.50)),url("/src/assets/cleaning-heroes/house-light.webp")!important;background-size:100% 100%,100% 100%,cover!important;background-position:center,center,center!important;background-repeat:no-repeat!important;color:#fff!important;border-color:rgba(255,255,255,.14)!important;box-shadow:0 20px 52px rgba(34,29,52,.20)!important}\n'
      +'#screen-cleaning .cleaning-overview-hero-copy>p{color:rgba(255,255,255,.82)!important}#screen-cleaning .cleaning-overview-kicker,#screen-cleaning .cleaning-overview-chip{background:rgba(7,13,21,.38)!important;border-color:rgba(255,255,255,.20)!important}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-overview-hero,[data-theme*="dark"] #screen-cleaning .cleaning-overview-hero{background-image:linear-gradient(90deg,rgba(3,8,15,.94) 0%,rgba(3,8,15,.72) 44%,rgba(3,8,15,.25) 76%,rgba(3,8,15,.10) 100%),linear-gradient(180deg,rgba(2,7,13,.02),rgba(2,7,13,.46)),url("/src/assets/cleaning-heroes/house-dark.webp")!important;border-color:rgba(126,101,255,.18)!important;box-shadow:0 24px 62px rgba(0,0,0,.42)!important}\n'
      +'/* Week plan hero */\n'
      +'#screen-cleaning .cleaning-plan-hero{position:relative;overflow:hidden;isolation:isolate;background-image:linear-gradient(90deg,rgba(251,249,246,.985) 0%,rgba(251,249,246,.94) 44%,rgba(251,249,246,.62) 67%,rgba(251,249,246,.16) 100%),linear-gradient(180deg,rgba(255,255,255,.02),rgba(241,235,228,.22)),url("/src/assets/cleaning-heroes/plan-light.webp")!important;background-size:100% 100%,100% 100%,cover!important;background-position:center,center,center!important;background-repeat:no-repeat!important;border-color:rgba(91,64,156,.14)!important;box-shadow:0 18px 44px rgba(43,32,74,.10)!important}\n'
      +'#screen-cleaning .cleaning-plan-hero>*{position:relative;z-index:1}#screen-cleaning .cleaning-plan-stats>div{background:rgba(255,255,255,.70)!important;border-color:rgba(88,70,126,.13)!important;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);box-shadow:0 8px 22px rgba(33,25,54,.06)}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-plan-hero,[data-theme*="dark"] #screen-cleaning .cleaning-plan-hero{background-image:linear-gradient(90deg,rgba(5,10,18,.98) 0%,rgba(5,10,18,.90) 43%,rgba(5,10,18,.60) 68%,rgba(5,10,18,.20) 100%),linear-gradient(180deg,rgba(5,10,18,.02),rgba(5,10,18,.38)),url("/src/assets/cleaning-heroes/plan-dark.webp")!important;color:#f8f7fb!important;border-color:rgba(91,203,124,.22)!important;box-shadow:0 22px 56px rgba(0,0,0,.36)!important}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-intro,[data-theme="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-actions>span,[data-theme*="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-intro,[data-theme*="dark"] #screen-cleaning .cleaning-plan-hero .cleaning-plan-actions>span{color:rgba(244,241,250,.70)!important}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-plan-stats>div,[data-theme*="dark"] #screen-cleaning .cleaning-plan-stats>div{background:rgba(7,13,23,.68)!important;border-color:rgba(255,255,255,.12)!important;color:#fff!important;box-shadow:0 10px 26px rgba(0,0,0,.18)}\n'
      +'/* Compact room cards */\n'
      +'#screen-cleaning .cleaning-room-card{min-height:0!important}#screen-cleaning .cleaning-room-card-main{min-height:92px!important;padding:12px 12px 8px!important;align-items:center!important;gap:10px!important}#screen-cleaning .cleaning-room-card-icon{width:44px!important;height:44px!important;border-radius:14px!important;font-size:20px!important}#screen-cleaning .cleaning-room-card-copy h3{font-size:16px!important}#screen-cleaning .cleaning-room-card-copy p.cleaning-room-card-meta{display:block!important;margin:5px 0 0!important;color:var(--color-muted,var(--cleaning-muted))!important;font-size:10px!important;font-weight:760!important;line-height:1.25!important}\n'
      +'#screen-cleaning .cleaning-room-edit-button,#screen-cleaning .cleaning-room-expand-button{display:none!important}#screen-cleaning .cleaning-room-card-actions{min-width:76px!important;align-items:flex-end!important;justify-content:center!important;gap:7px!important}#screen-cleaning .cleaning-room-card-status{min-height:24px!important}\n'
      +'#screen-cleaning .cleaning-room-avatar-stack{display:flex;justify-content:flex-end;align-items:center;padding-right:2px;min-height:32px}#screen-cleaning .cleaning-room-avatar{width:32px;height:32px;display:grid;place-items:center;object-fit:cover;border-radius:50%;border:2px solid rgba(255,255,255,.88);background:linear-gradient(135deg,#7552ee,#9f69ff);color:#fff;font-size:8px;font-weight:900;box-shadow:0 5px 14px rgba(20,24,34,.18);margin-left:-8px}#screen-cleaning .cleaning-room-avatar:first-child{margin-left:0}#screen-cleaning .cleaning-room-avatar.is-more{background:rgba(255,255,255,.82);color:#4a3b72;backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}\n'
      +'#screen-cleaning .cleaning-room-supplies-bar{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(0,1.1fr)!important;gap:8px!important;padding:0 12px 12px!important}#screen-cleaning .cleaning-room-primary-action,#screen-cleaning .cleaning-room-supplies-button{width:100%!important;min-width:0!important;min-height:46px!important;border-radius:13px!important;padding:7px 9px!important;box-shadow:0 7px 18px rgba(22,25,34,.08)!important;backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}#screen-cleaning .cleaning-room-primary-action{border:1px solid color-mix(in srgb,var(--room-accent,var(--color-primary)) 25%,var(--cleaning-border));background:rgba(255,255,255,.84);color:var(--room-accent,var(--color-primary));font:inherit;font-size:10.5px;font-weight:900;cursor:pointer}#screen-cleaning .cleaning-room-supplies-button{background:rgba(255,255,255,.84)!important}#screen-cleaning .cleaning-room-supplies-button strong{font-size:10px!important;white-space:nowrap}#screen-cleaning .cleaning-room-supplies-button span{font-size:8.5px!important;white-space:nowrap}\n'
      +'#screen-cleaning .cleaning-room-manage-row{display:none;position:relative;z-index:3;padding:0 12px 10px;justify-content:flex-end}#screen-cleaning .cleaning-room-card.is-expanded .cleaning-room-manage-row{display:flex}#screen-cleaning .cleaning-room-manage-link{min-height:44px;border:0;background:transparent;color:var(--color-muted,var(--cleaning-muted));font:inherit;font-size:10px;font-weight:850;padding:0 4px;cursor:pointer;text-decoration:underline;text-decoration-color:color-mix(in srgb,var(--color-muted,var(--cleaning-muted)) 32%,transparent);text-underline-offset:3px}\n'
      +'[data-theme="dark"] #screen-cleaning .cleaning-room-avatar,[data-theme*="dark"] #screen-cleaning .cleaning-room-avatar{border-color:rgba(7,13,22,.92);box-shadow:0 5px 16px rgba(0,0,0,.30)}[data-theme="dark"] #screen-cleaning .cleaning-room-avatar.is-more,[data-theme*="dark"] #screen-cleaning .cleaning-room-avatar.is-more{background:rgba(8,14,24,.82);color:#d9caff}[data-theme="dark"] #screen-cleaning .cleaning-room-primary-action,[data-theme="dark"] #screen-cleaning .cleaning-room-supplies-button,[data-theme*="dark"] #screen-cleaning .cleaning-room-primary-action,[data-theme*="dark"] #screen-cleaning .cleaning-room-supplies-button{background:rgba(8,14,24,.78)!important;border-color:rgba(255,255,255,.12)!important;color:#f8f7fb!important;box-shadow:0 8px 20px rgba(0,0,0,.20)!important}\n'
      +'@media(max-width:370px){#screen-cleaning .cleaning-room-card-main{min-height:88px!important;grid-template-columns:auto minmax(0,1fr) auto!important}#screen-cleaning .cleaning-room-avatar{width:29px;height:29px}#screen-cleaning .cleaning-room-card-actions{min-width:64px!important}#screen-cleaning .cleaning-room-primary-action,#screen-cleaning .cleaning-room-supplies-button{font-size:9.5px!important;padding:6px!important}#screen-cleaning .cleaning-room-supplies-button strong{font-size:9px!important}#screen-cleaning .cleaning-room-supplies-button span{font-size:7.5px!important}}\n'
      +'@media(prefers-reduced-motion:reduce){#screen-cleaning .cleaning-room-primary-action{transition:none!important}}\n';
    document.head.appendChild(style);
  }

  function decorateCard(card,root){
    var roomId=text(card.getAttribute('data-cleaning-room-id'));if(!roomId)return;var room=roomsMap(root)[roomId];if(!room||room.active===false)return;var meta=roomMeta(root,roomId),copy=card.querySelector('.cleaning-room-card-copy'),sub=copy&&copy.querySelector('p');
    if(sub){sub.classList.add('cleaning-room-card-meta');var label=meta.parts+' '+(meta.parts===1?'onderdeel':'onderdelen')+' · ± '+meta.minutes+' min';if(sub.textContent!==label)sub.textContent=label;}
    var actions=card.querySelector('.cleaning-room-card-actions');if(actions){var stack=actions.querySelector('[data-cleaning-room-avatars]'),uids=assigneesForRoom(meta),signature=uids.join('|');if(uids.length){if(!stack){stack=document.createElement('div');stack.className='cleaning-room-avatar-stack';stack.setAttribute('data-cleaning-room-avatars','1');actions.appendChild(stack);}if(stack.getAttribute('data-avatar-signature')!==signature){stack.setAttribute('data-avatar-signature',signature);stack.innerHTML=avatarMarkup(uids);}}else if(stack)stack.remove();}
    var supplies=card.querySelector('[data-cleaning-room-supplies-bar],.cleaning-room-supplies-bar');if(supplies){var primary=supplies.querySelector('[data-cleaning-room-primary-action]');if(!primary){primary=document.createElement('button');primary.type='button';primary.className='cleaning-room-primary-action';primary.setAttribute('data-cleaning-room-primary-action',roomId);supplies.insertBefore(primary,supplies.firstChild);}var expanded=card.classList.contains('is-expanded'),label=expanded?'Sluit details':(meta.occurrence?'Bekijk beurt':'Bekijk kamer');if(primary.textContent!==label)primary.textContent=label;primary.setAttribute('aria-expanded',expanded?'true':'false');}
    var manage=card.querySelector('[data-cleaning-room-manage-row]');if(!manage){manage=document.createElement('div');manage.className='cleaning-room-manage-row';manage.setAttribute('data-cleaning-room-manage-row','1');manage.innerHTML='<button type="button" class="cleaning-room-manage-link" data-cleaning-room-manage="'+esc(roomId)+'">Kamer beheren</button>';var bar=card.querySelector('[data-cleaning-room-supplies-bar],.cleaning-room-supplies-bar');if(bar&&bar.parentNode)bar.parentNode.insertBefore(manage,bar.nextSibling);else card.appendChild(manage);}
  }
  function decorate(){state.queued=false;ensureStyle();var root=data(),cards=document.querySelectorAll('#screen-cleaning .cleaning-room-card[data-cleaning-room-id]');for(var i=0;i<cards.length;i++)decorateCard(cards[i],root);}
  function queue(){if(state.queued)return;state.queued=true;(window.requestAnimationFrame||function(callback){return window.setTimeout(callback,0);})(decorate);}
  function onClick(event){var target=event.target,closest=target&&target.closest?target.closest.bind(target):null;if(!closest)return;var primary=closest('[data-cleaning-room-primary-action]');if(primary){event.preventDefault();event.stopPropagation();var roomId=text(primary.getAttribute('data-cleaning-room-primary-action')),card=primary.closest('.cleaning-room-card'),proxy=card&&card.querySelector('[data-cleaning-room-expand="'+roomId+'"]');if(proxy)proxy.click();else if(card){var main=card.querySelector('.cleaning-room-card-main');if(main)main.click();}window.setTimeout(queue,0);return;}var manage=closest('[data-cleaning-room-manage]');if(manage){event.preventDefault();event.stopPropagation();var id=text(manage.getAttribute('data-cleaning-room-manage')),roomCard=manage.closest('.cleaning-room-card'),edit=roomCard&&roomCard.querySelector('[data-cleaning-room-edit="'+id+'"]');if(edit)edit.click();}}
  function start(){if(window.__cleaningPremiumFeedbackStarted)return;window.__cleaningPremiumFeedbackStarted=true;ensureStyle();document.addEventListener('click',onClick,true);var target=document.getElementById('screen-cleaning')||document.documentElement;if(typeof MutationObserver!=='undefined'&&target){state.observer=new MutationObserver(queue);state.observer.observe(target,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});}window.addEventListener('familyapp:cleaning-repository',queue);window.addEventListener('familyapp:household-identity-synced',queue);queue();}

  window.CleaningPremiumFeedback={version:VERSION,start:start};start();
})();
