'use strict';
// ============================================================
// CLEANING V2.2.1 — CALM PREMIUM DETAIL VISUAL FOUNDATION
// Presentation-only adapter over the accepted Cleaning V2 sheet/repository.
// No Firebase owner, no MutationObserver, no polling and no second popup.
// Existing data-cv2-* execution controls stay owned by cleaningScreen.js.
// ============================================================
(function(){
  if(window.CleaningDetailVisualV221)return;

  var VERSION='2.2.1';
  var state={root:null,sheet:null,sheetBound:false,kind:null,occurrenceId:null,roomId:null,supplyScope:'turn',rows:[],editable:false,addOpen:false,shoppingBusy:false,started:false};

  function text(value){return String(value==null?'':value).trim();}
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function num(value){var n=Number(value);return Number.isFinite(n)?n:0;}
  function repo(){return window.CleaningHouseholdRepository||window.CleaningV2Repository||null;}
  function snap(){var r=repo();try{return r&&typeof r.snapshot==='function'?r.snapshot():null;}catch(error){return null;}}
  function data(){var s=snap();return s&&s.data||{};}
  function defer(fn){if(typeof queueMicrotask==='function')queueMicrotask(fn);else Promise.resolve().then(fn);}
  function toast(message){if(typeof window.showToast==='function')window.showToast(message);else try{console.info('[CleaningDetailVisualV221]',message);}catch(error){}}

  function ensureStyles(){
    if(document.getElementById('cleaning-detail-visual-v221-css'))return;
    var link=document.createElement('link');
    link.id='cleaning-detail-visual-v221-css';
    link.rel='stylesheet';
    link.href='/src/styles/cleaning-detail-v221.css?v=1';
    document.head.appendChild(link);
  }

  function members(){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&typeof bridge.getMembers==='function'?bridge.getMembers():[];return Array.isArray(rows)?rows.filter(Boolean):[];}catch(error){return[];}}
  function member(uid){uid=text(uid);return members().find(function(row){return text(row&&(row.uid||row.id))===uid;})||null;}
  function memberName(uid){var row=member(uid);return text(row&&(row.displayName||row.name))||'Gezinslid';}
  function currentRole(){var s=snap(),row=member(s&&s.uid),raw=text(row&&row.role).toLowerCase();if(['owner','admin','manager','beheerder'].indexOf(raw)>=0)return'MANAGER';if(['adult','member','gezinslid'].indexOf(raw)>=0)return'MEMBER';if(['child','limited','restricted','beperkt'].indexOf(raw)>=0)return'LIMITED';return'UNKNOWN';}
  function canStructure(){var role=currentRole();return role==='MANAGER'||role==='MEMBER';}
  function avatarUrl(row){var raw=text(row&&(row.photoURL||row.photoUrl||row.avatarUrl||row.avatar||row.image));return /^(https?:\/\/|\/|data:image\/)/i.test(raw)?raw:'';}
  function initials(name){var parts=text(name).split(/\s+/).filter(Boolean);return(parts[0]?parts[0].charAt(0):'G')+(parts.length>1?parts[parts.length-1].charAt(0):'');}
  function avatarMarkup(uid){var row=member(uid),name=memberName(uid),url=avatarUrl(row);return url?'<img src="'+esc(url)+'" alt="">':'<span>'+esc(initials(name).toUpperCase())+'</span>';}

  function roomById(id){var row=data().rooms&&data().rooms[id];return row?Object.assign({id:id},row):null;}
  function occurrenceById(id){var row=data().occurrences&&data().occurrences[id];return row?Object.assign({id:id},row):null;}
  function routineById(id){var row=data().routines&&data().routines[id];return row?Object.assign({id:id},row):null;}
  function supplyById(id){var row=data().supplies&&data().supplies[id];return row?Object.assign({id:id},row):null;}
  function inventoryStatus(id){var row=data().inventory&&data().inventory[id],status=text(typeof row==='string'?row:row&&row.status).toUpperCase();return['IN_STOCK','LOW','OUT'].indexOf(status)>=0?status:'IN_STOCK';}

  function roomSupplyRows(roomId){var ids=[];Object.keys(data().routines||{}).forEach(function(id){var routine=data().routines[id];if(!routine||routine.active===false||text(routine.roomId)!==text(roomId))return;(Array.isArray(routine.supplyIds)?routine.supplyIds:[]).forEach(function(supplyId){supplyId=text(supplyId);if(supplyId&&ids.indexOf(supplyId)<0)ids.push(supplyId);});});return supplyRows(ids);}
  function occurrenceSupplyRows(occurrence){var ids=[];(Array.isArray(occurrence&&occurrence.checklist)?occurrence.checklist:[]).forEach(function(item){var routine=routineById(text(item&&(item.routineItemId||item.id)));(Array.isArray(routine&&routine.supplyIds)?routine.supplyIds:[]).forEach(function(supplyId){supplyId=text(supplyId);if(supplyId&&ids.indexOf(supplyId)<0)ids.push(supplyId);});});return supplyRows(ids);}
  function supplyRows(ids){return(ids||[]).map(function(id){var row=supplyById(id);if(!row||row.active===false)return null;return{id:id,name:text(row.name)||'Benodigd item',status:inventoryStatus(id)};}).filter(Boolean).sort(function(a,b){return a.name.localeCompare(b.name,'nl');});}

  function formatDate(value){if(!value)return'Flexibel';try{var date=/^\d{4}-\d{2}-\d{2}$/.test(String(value))?new Date(String(value)+'T12:00:00'):new Date(num(value)||value);return date.toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'});}catch(error){return text(value);}}
  function formatTime(occurrence){var raw=text(occurrence&&occurrence.scheduledTime);if(raw)return raw;var timestamp=num(occurrence&&occurrence.scheduledStartAt);if(timestamp)return new Date(timestamp).toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'});return'Flexibel';}
  function statusLabel(occurrence){var status=text(occurrence&&(occurrence.status||occurrence.assignmentStatus)).toUpperCase();if(status==='COMPLETED')return'AFGEROND';if(status==='SCHEDULED')return'GEPLAND';if(status==='FLEXIBLE'||status==='ACTIVE')return'FLEXIBEL';if(status==='PENDING'||status==='PROPOSED')return'WACHT';return status||'GEPLAND';}
  function statusTone(label){if(label==='AFGEROND')return'success';if(label==='FLEXIBEL')return'violet';if(label==='WACHT')return'attention';return'planned';}

  function supplyKind(name){var n=text(name).toLowerCase();if(/spray|reiniger|allesreiniger|glasreiniger|ontkalker|middel/.test(n))return'spray';if(/doek|microvezel|lap/.test(n))return'cloth';if(/spons/.test(n))return'sponge';if(/handschoen/.test(n))return'glove';if(/borstel|bezem/.test(n))return'brush';if(/emmer/.test(n))return'bucket';if(/zak|vuilnis/.test(n))return'bag';if(/trekker|wisser/.test(n))return'wiper';return'cleaner';}
  function iconSvg(kind){
    var attrs='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"';
    if(kind==='spray')return'<svg '+attrs+'><path d="M9 5h6l1.5 3v11H7.5V8L9 5Z"/><path d="M10 5V3h5"/><path d="M15 3h3"/><path d="M10 11h4"/></svg>';
    if(kind==='cloth')return'<svg '+attrs+'><path d="M5 7.5 12 5l7 2.5-1.5 11h-11L5 7.5Z"/><path d="M8 10c2 1 6 1 8 0"/></svg>';
    if(kind==='sponge')return'<svg '+attrs+'><rect x="4" y="6" width="16" height="12" rx="4"/><path d="M7 10h.01M11 8.5h.01M15 11h.01M17 15h.01M10 15h.01"/></svg>';
    if(kind==='glove')return'<svg '+attrs+'><path d="M8 20c-2-2-3-5-3-8V8a1.5 1.5 0 0 1 3 0v3-6a1.5 1.5 0 0 1 3 0v6-7a1.5 1.5 0 0 1 3 0v7-5a1.5 1.5 0 0 1 3 0v7c0 4-2 7-5 7H8Z"/></svg>';
    if(kind==='brush')return'<svg '+attrs+'><path d="m7 14 8-8"/><path d="M13.5 4.5 17 8"/><path d="M5 15h8l-2 5H6l-1-5Z"/></svg>';
    if(kind==='bucket')return'<svg '+attrs+'><path d="M6 8h12l-1.2 11H7.2L6 8Z"/><path d="M8 8a4 4 0 0 1 8 0"/></svg>';
    if(kind==='bag')return'<svg '+attrs+'><path d="M8 6h8l2 3-1 11H7L6 9l2-3Z"/><path d="M9 6 8 3h8l-1 3"/></svg>';
    if(kind==='wiper')return'<svg '+attrs+'><path d="M5 5h14"/><path d="M7 5l2 5h6l2-5"/><path d="M12 10v10"/></svg>';
    return'<svg '+attrs+'><path d="M9 4h6l2 4v11H7V8l2-4Z"/><path d="M9 12h6"/></svg>';
  }
  function uiIcon(kind){var attrs='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"';if(kind==='calendar')return'<svg '+attrs+'><rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3v4M16 3v4M4 9h16"/></svg>';if(kind==='clock')return'<svg '+attrs+'><circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/></svg>';if(kind==='list')return'<svg '+attrs+'><path d="M9 7h10M9 12h10M9 17h10"/><path d="M5 7h.01M5 12h.01M5 17h.01"/></svg>';if(kind==='timer')return'<svg '+attrs+'><circle cx="12" cy="13" r="7"/><path d="M12 13l3-3M9 3h6M12 3v3"/></svg>';if(kind==='turn')return'<svg '+attrs+'><rect x="5" y="4" width="14" height="16" rx="3"/><path d="M9 9h6M9 13h6"/></svg>';if(kind==='box')return'<svg '+attrs+'><path d="m4 8 8-4 8 4-8 4-8-4Z"/><path d="M4 8v8l8 4 8-4V8M12 12v8"/></svg>';return'';}

  function renderHeader(kicker,title,roomId,occurrenceId){var sheet=state.sheet;if(!sheet)return;var head=sheet.querySelector('.cv2-sheet-head');if(!head)return;var menu='';if(roomId&&canStructure())menu+='<button type="button" data-cv2-room-edit="'+esc(roomId)+'">Kamer bewerken</button>';if(occurrenceId)menu+='<button type="button" data-cv2-supplies="'+esc(occurrenceId)+'">Benodigdheden</button>';head.innerHTML='<button type="button" class="fav-head-button" data-cv2-close aria-label="Terug"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg></button><div class="fav-head-title" data-cv2-sheet-title><span>'+esc(kicker||'Schoonmaken')+'</span><strong>'+esc(title||'')+'</strong></div><button type="button" class="fav-head-button" data-fav-overflow aria-label="Meer opties"><svg viewBox="0 0 24 24" fill="currentColor"><circle cx="5" cy="12" r="1.8"/><circle cx="12" cy="12" r="1.8"/><circle cx="19" cy="12" r="1.8"/></svg></button><div class="fav-overflow-menu" data-fav-overflow-menu hidden>'+menu+'</div>';}

  function leaveDetailMode(preserveCurrentTitle){var sheet=state.sheet;if(!sheet)return;var head=sheet.querySelector('.cv2-sheet-head'),titleNode=head&&head.querySelector('[data-cv2-sheet-title]'),titleHtml=preserveCurrentTitle&&titleNode?titleNode.innerHTML:'';sheet.classList.remove('fav-detail-mode','fav-turn-mode','fav-supplies-mode','fav-executing');delete sheet.dataset.favDetail;if(head)head.innerHTML='<button type="button" data-cv2-close aria-label="Sluiten">×</button><div data-cv2-sheet-title>'+titleHtml+'</div>';state.kind=null;state.occurrenceId=null;state.roomId=null;state.rows=[];state.addOpen=false;state.shoppingBusy=false;}

  function metaItem(icon,label,value){return'<div class="fav-meta-item"><span>'+uiIcon(icon)+'</span><div><small>'+esc(label)+'</small><strong>'+esc(value)+'</strong></div></div>';}

  function renderTurn(occurrenceId){
    bindSheet();var sheet=state.sheet,occurrence=occurrenceById(occurrenceId);if(!sheet||!occurrence)return;var room=roomById(occurrence.roomId),roomName=text(room&&room.name)||'Ruimte',list=Array.isArray(occurrence.checklist)?occurrence.checklist.slice():[],done=list.filter(function(item){return item&&item.completed===true;}).length,total=list.length,pct=total?Math.round(done/total*100):0,assignee=text((occurrence.assignmentUids||[])[0]),label=statusLabel(occurrence),tone=statusTone(label),supplyCount=occurrenceSupplyRows(occurrence).length;
    state.kind='turn';state.occurrenceId=occurrence.id;state.roomId=occurrence.roomId;state.supplyScope='turn';state.rows=[];state.addOpen=false;
    sheet.dataset.favDetail='turn';sheet.classList.add('fav-detail-mode','fav-turn-mode');sheet.classList.remove('fav-supplies-mode');renderHeader('Schoonmaakbeurt',roomName,room&&room.id,occurrence.id);
    var body=sheet.querySelector('[data-cv2-sheet-body]');if(!body)return;
    body.innerHTML='<section class="fav-turn-detail"><div class="fav-turn-hero" data-room-type="'+esc(room&&room.type||'custom')+'"><div class="fav-turn-hero-photo"></div><span class="fav-status-pill is-'+tone+'">'+esc(label)+'</span></div><div class="fav-turn-intro"><h2>'+esc(roomName)+' schoonmaken</h2><div class="fav-meta-grid">'+metaItem('calendar','Dag',formatDate(occurrence.scheduledDate||occurrence.earliestDueAt))+metaItem('clock','Moment',formatTime(occurrence))+metaItem('list','Onderdelen',String(total))+metaItem('timer','Geschat',Math.max(0,Math.round(num(occurrence.estimatedMinutes)))+' min')+'</div></div><div class="fav-person-card"><div class="fav-avatar">'+avatarMarkup(assignee)+'</div><div><small>Toegewezen persoon</small><strong>'+esc(memberName(assignee))+'</strong></div></div><div class="fav-progress-block"><div class="fav-progress-head"><div><small>Voortgang routine</small><strong><b data-cv2-done-count>'+done+'</b> van '+total+' onderdelen</strong></div><span data-fav-progress-percent>'+pct+'%</span></div><i class="fav-progress-track"><b data-cv2-sheet-progress style="width:'+pct+'%"></b></i><p data-fav-progress-copy>'+(pct===100?'Deze schoonmaakbeurt is afgerond.':pct>0?'Lekker bezig — ga verder waar je gebleven was.':'Alles staat klaar om te beginnen.')+'</p></div><div class="fav-section-head"><div><small>Routine</small><h3>Onderdelen</h3></div><span>'+done+'/'+total+'</span></div><div class="cv2-checklist fav-checklist">'+list.map(function(item,index){return'<button type="button" class="cv2-check fav-check '+(item&&item.completed===true?'is-done':'')+'" data-cv2-check="'+index+'"><i>✓</i><span>'+esc(item&&item.title||'Schoonmaakonderdeel')+'</span><small>'+Math.max(0,Math.round(num(item&&item.estimatedMinutes)))+' min</small></button>';}).join('')+'</div><div class="fav-primary-stack"><button type="button" class="cv2-primary fav-primary" data-fav-start-cleaning="'+esc(occurrence.id)+'"'+(pct===100?' disabled':'')+'>'+(pct>0&&pct<100?'Verder schoonmaken':'Start schoonmaken')+'</button>'+(canStructure()?'<button type="button" class="cv2-secondary fav-secondary" data-cv2-room-edit="'+esc(room&&room.id||'')+'">Bewerken</button>':'')+'</div><div class="cv2-sheet-actions fav-utility-pair"><button type="button" class="cv2-secondary fav-utility" data-fav-view-turn>'+uiIcon('turn')+'<span>Bekijk beurt</span></button><button type="button" class="cv2-secondary fav-utility" data-cv2-supplies="'+esc(occurrence.id)+'">'+uiIcon('box')+'<span>Benodigdheden</span>'+(supplyCount?'<b>'+supplyCount+'</b>':'')+'</button></div><div class="cv2-save-state" data-cv2-save-state></div></section>';
    try{if(window.CleaningCollaborationV21&&typeof window.CleaningCollaborationV21.render==='function')window.CleaningCollaborationV21.render();}catch(error){}
  }

  function syncTurnProgressUi(){if(state.kind!=='turn'||!state.sheet)return;var checks=Array.from(state.sheet.querySelectorAll('.fav-check[data-cv2-check]')),total=checks.length,done=checks.filter(function(row){return row.classList.contains('is-done');}).length,pct=total?Math.round(done/total*100):0,percent=state.sheet.querySelector('[data-fav-progress-percent]'),copy=state.sheet.querySelector('[data-fav-progress-copy]'),summary=state.sheet.querySelector('.fav-section-head>span');if(percent)percent.textContent=pct+'%';if(copy)copy.textContent=pct===100?'Deze schoonmaakbeurt is afgerond.':pct>0?'Lekker bezig — ga verder waar je gebleven was.':'Alles staat klaar om te beginnen.';if(summary)summary.textContent=done+'/'+total;}

  function statusInfo(status){if(status==='LOW')return{label:'Bijna op',tone:'low',symbol:'!'};if(status==='OUT')return{label:'Ontbreekt',tone:'out',symbol:'×'};return{label:'Op voorraad',tone:'stock',symbol:'✓'};}
  function supplyRowMarkup(row){var kind=supplyKind(row.name),meta=statusInfo(row.status);return'<div class="fav-supply-row" data-fav-supply-row="'+esc(row.id)+'"><div class="fav-supply-icon is-'+esc(kind)+'">'+iconSvg(kind)+'</div><div class="fav-supply-copy"><strong>'+esc(row.name)+'</strong><small class="is-'+meta.tone+'">'+esc(meta.label)+'</small></div><button type="button" class="fav-supply-state is-'+meta.tone+'" '+(state.editable?'data-fav-supply-cycle="'+esc(row.id)+'"':'disabled')+' aria-label="'+esc(meta.label)+'">'+esc(meta.symbol)+'</button></div>';}
  function readSupplyRows(){var occurrence=state.occurrenceId?occurrenceById(state.occurrenceId):null;return state.supplyScope==='turn'&&occurrence?occurrenceSupplyRows(occurrence):roomSupplyRows(state.roomId);}
  function renderSupplies(options){
    options=options||{};bindSheet();var sheet=state.sheet;if(!sheet)return;var occurrenceId=text(options.occurrenceId||state.occurrenceId),occurrence=occurrenceId?occurrenceById(occurrenceId):null,roomId=text(options.roomId||state.roomId||occurrence&&occurrence.roomId),room=roomById(roomId);if(!room)return;
    if(options.captureEditable){var oldBody=sheet.querySelector('[data-cv2-sheet-body]');state.editable=!!(oldBody&&oldBody.querySelector('select[data-cv2-supply-status], [data-cv2-supply-form]'));}
    state.kind='supplies';state.occurrenceId=occurrenceId||null;state.roomId=roomId;if(!occurrenceId)state.supplyScope='room';else if(options.scope)state.supplyScope=options.scope;if(options.refreshRows!==false||!state.rows.length)state.rows=readSupplyRows();
    sheet.dataset.favDetail='supplies';sheet.classList.add('fav-detail-mode','fav-supplies-mode');sheet.classList.remove('fav-turn-mode','fav-executing');renderHeader('Benodigdheden',text(room.name)||'Kamer',room.id,null);
    var body=sheet.querySelector('[data-cv2-sheet-body]');if(!body)return;var rows=state.rows,attention=rows.filter(function(row){return row.status==='LOW'||row.status==='OUT';}),stock=rows.filter(function(row){return row.status==='IN_STOCK';}).length,low=rows.filter(function(row){return row.status==='LOW';}).length,out=rows.filter(function(row){return row.status==='OUT';}).length,when=occurrence?formatDate(occurrence.scheduledDate||occurrence.earliestDueAt)+(formatTime(occurrence)!=='Flexibel'?' · '+formatTime(occurrence):''):'deze kamer';
    body.innerHTML='<section class="fav-supplies-detail">'+(occurrenceId?'<div class="fav-segmented"><button type="button" data-fav-supply-mode="turn" class="'+(state.supplyScope==='turn'?'is-active':'')+'">Voor deze beurt</button><button type="button" data-fav-supply-mode="room" class="'+(state.supplyScope==='room'?'is-active':'')+'">Alle kameritems</button></div>':'')+'<div class="fav-supply-intro"><small>'+esc(state.supplyScope==='turn'?'Voor deze beurt':'Kamerbenodigdheden')+'</small><h2>'+(state.supplyScope==='turn'?'Wat je nodig hebt':'Alles voor '+esc(text(room.name)||'deze kamer'))+'</h2><p>'+(state.supplyScope==='turn'?'Gepland voor '+esc(when):'Beheer hier wat standaard bij deze kamer hoort.')+'</p></div><div class="fav-supply-list">'+(rows.length?rows.map(supplyRowMarkup).join(''):'<div class="fav-empty-card"><strong>Nog geen benodigdheden</strong><span>Koppel benodigdheden aan de routines van deze kamer.</span></div>')+'</div><div class="fav-missing-card"><div><small>'+(attention.length?'Aandacht nodig':'Boodschappen')+'</small><strong>'+(attention.length?'Ontbreekt iets?':'Alles op voorraad')+'</strong><span>'+(attention.length?'Voeg ontbrekende of bijna lege items direct toe aan boodschappen.':'Je hebt momenteel niets uit deze lijst nodig.')+'</span></div><button type="button" data-fav-shopping-add '+(!attention.length||state.shoppingBusy?'disabled':'')+' aria-label="Toevoegen aan boodschappen">＋</button></div><div class="fav-inventory-summary"><div><small>Kamer voorraadstatus</small><strong>'+stock+' op voorraad</strong></div><p>'+(low?'<span class="is-low">'+low+' bijna op</span>':'')+(low&&out?' · ':'')+(out?'<span class="is-out">'+out+' ontbreekt</span>':'')+(!low&&!out?'<span class="is-stock">Alles compleet</span>':'')+'</p></div>'+(state.editable?'<div class="fav-add-supply"><button type="button" class="fav-add-toggle" data-fav-add-toggle>＋ Kameritem toevoegen</button>'+(state.addOpen?'<form data-fav-supply-form><input name="name" maxlength="80" placeholder="Bijv. Glasreiniger" required><button type="submit">Toevoegen</button></form>':'')+'</div>':'')+'<div class="fav-utility-pair fav-supplies-actions">'+(occurrenceId?'<button type="button" class="fav-utility" data-fav-supply-mode="room">'+uiIcon('list')+'<span>Bekijk alle kameritems</span></button>':'<button type="button" class="fav-utility" disabled>'+uiIcon('list')+'<span>Alle kameritems</span></button>')+'<button type="button" class="fav-utility" data-fav-open-shopping>'+uiIcon('box')+'<span>Boodschappen</span>'+(attention.length?'<b>'+attention.length+'</b>':'')+'</button></div></section>';}

  function cycleStatus(id){var row=state.rows.find(function(item){return item.id===id;});if(!row||!state.editable)return;var before=row.status,next=row.status==='IN_STOCK'?'LOW':row.status==='LOW'?'OUT':'IN_STOCK',r=repo();if(!r||typeof r.setInventoryStatus!=='function')return;row.status=next;renderSupplies({occurrenceId:state.occurrenceId,roomId:state.roomId,scope:state.supplyScope,refreshRows:false});Promise.resolve(r.setInventoryStatus(id,next)).catch(function(error){row.status=before;renderSupplies({occurrenceId:state.occurrenceId,roomId:state.roomId,scope:state.supplyScope,refreshRows:false});toast(text(error&&error.message)||'Voorraadstatus kon niet worden opgeslagen.');});}

  function addRoomSupply(name){var r=repo(),roomId=state.roomId;if(!r||typeof r.addRoomSupply!=='function'||!roomId)return;Promise.resolve(r.addRoomSupply(roomId,name)).then(function(row){if(row&&row.id&&!state.rows.some(function(item){return item.id===row.id;}))state.rows.push({id:row.id,name:text(row.name)||name,status:'IN_STOCK'});state.rows.sort(function(a,b){return a.name.localeCompare(b.name,'nl');});state.addOpen=false;toast('Benodigd item toegevoegd ✓');renderSupplies({occurrenceId:state.occurrenceId,roomId:roomId,scope:state.supplyScope,refreshRows:false});}).catch(function(error){toast(error&&error.message==='CLEANING_SUPPLY_ROUTINE_REQUIRED'?'Voeg eerst een routine toe aan deze kamer.':text(error&&error.message)||'Kon item niet toevoegen.');});}

  function addAttentionToShopping(){if(state.shoppingBusy)return;var rows=state.rows.filter(function(row){return row.status==='LOW'||row.status==='OUT';}),store=window.ShoppingListStore;if(!rows.length)return;if(!store||typeof store.addItems!=='function'){toast('Boodschappen is nog niet beschikbaar.');return;}state.shoppingBusy=true;renderSupplies({occurrenceId:state.occurrenceId,roomId:state.roomId,scope:state.supplyScope,refreshRows:false});var items=rows.map(function(row){return{name:row.name,qty:'1 st',cat:'Schoonmaak',source:'cleaning'};});Promise.resolve(store.addItems(null,items,{dedupe:true})).then(function(result){var added=result&&result.added?result.added.length:0,skipped=result&&result.skipped?result.skipped.length:0;toast(added?added+' '+(added===1?'item toegevoegd':'items toegevoegd')+' aan boodschappen ✓':skipped?'Staat al op boodschappen ✓':'Geen items toegevoegd.');}).catch(function(error){toast(text(error&&error.message)||'Toevoegen aan boodschappen is mislukt.');}).finally(function(){state.shoppingBusy=false;renderSupplies({occurrenceId:state.occurrenceId,roomId:state.roomId,scope:state.supplyScope,refreshRows:false});});}

  function openShopping(){var close=state.sheet&&state.sheet.querySelector('[data-cv2-close]');if(close)close.click();if(typeof window.showScreen==='function')window.showScreen('shop');}
  function viewTurn(){var body=state.sheet&&state.sheet.querySelector('[data-cv2-sheet-body]');if(body)body.scrollTop=0;}
  function startCleaning(button){if(!button||!state.occurrenceId)return;state.sheet&&state.sheet.classList.add('fav-executing');button.removeAttribute('data-fav-start-cleaning');button.setAttribute('data-cv2-complete-all',state.occurrenceId);button.textContent='Alles afronden';toast('Schoonmaak gestart');}

  function bindSheet(){var sheet=document.getElementById('cleaning-v2-sheet');if(!sheet)return false;if(state.sheet===sheet&&state.sheetBound)return true;state.sheet=sheet;if(!state.sheetBound){sheet.addEventListener('click',onSheetClick);sheet.addEventListener('submit',onSheetSubmit);state.sheetBound=true;}return true;}

  function onRootClick(event){var target=event.target&&event.target.closest?event.target.closest('button'):null;if(!target)return;defer(bindSheet);if(target.dataset&&target.dataset.cv2Turn){var id=target.dataset.cv2Turn;defer(function(){renderTurn(id);});return;}if(target.dataset&&target.dataset.cv2Room)defer(function(){leaveDetailMode(true);});}

  function onSheetClick(event){var target=event.target&&event.target.closest?event.target.closest('button'):null;if(!target)return;if(target.hasAttribute('data-cv2-close')){defer(function(){leaveDetailMode(false);});return;}if(target.dataset&&target.dataset.cv2Check!==undefined){defer(syncTurnProgressUi);return;}if(target.dataset&&target.dataset.cv2CompleteAll){defer(syncTurnProgressUi);return;}if(target.dataset&&target.dataset.cv2Supplies){var occurrenceId=target.dataset.cv2Supplies;defer(function(){renderSupplies({occurrenceId:occurrenceId,captureEditable:true,scope:'turn',refreshRows:true});});return;}if(target.dataset&&target.dataset.cv2SuppliesRoom){var roomId=target.dataset.cv2SuppliesRoom;defer(function(){renderSupplies({roomId:roomId,captureEditable:true,scope:'room',refreshRows:true});});return;}if(target.dataset&&target.dataset.favSupplyMode){state.supplyScope=target.dataset.favSupplyMode;renderSupplies({occurrenceId:state.occurrenceId,roomId:state.roomId,scope:state.supplyScope,refreshRows:true});return;}if(target.dataset&&target.dataset.favSupplyCycle){cycleStatus(target.dataset.favSupplyCycle);return;}if(target.hasAttribute('data-fav-add-toggle')){state.addOpen=!state.addOpen;renderSupplies({occurrenceId:state.occurrenceId,roomId:state.roomId,scope:state.supplyScope,refreshRows:false});return;}if(target.hasAttribute('data-fav-shopping-add')){addAttentionToShopping();return;}if(target.hasAttribute('data-fav-open-shopping')){openShopping();return;}if(target.hasAttribute('data-fav-view-turn')){viewTurn();return;}if(target.dataset&&target.dataset.favStartCleaning){startCleaning(target);return;}if(target.hasAttribute('data-fav-overflow')){var menu=state.sheet&&state.sheet.querySelector('[data-fav-overflow-menu]');if(menu)menu.hidden=!menu.hidden;return;}if(target.dataset&&target.dataset.cv2RoomEdit){defer(function(){leaveDetailMode(true);});}}

  function onSheetSubmit(event){var form=event.target;if(!form||!form.matches('[data-fav-supply-form]'))return;event.preventDefault();var input=form.querySelector('input[name="name"]'),name=text(input&&input.value);if(name)addRoomSupply(name);}

  function start(){if(state.started)return true;ensureStyles();var root=document.getElementById('screen-cleaning');if(!root)return false;state.root=root;root.addEventListener('click',onRootClick);state.started=true;bindSheet();return true;}

  window.CleaningDetailVisualV221=Object.freeze({version:VERSION,start:start,renderTurn:renderTurn,renderSupplies:renderSupplies,status:function(){return{version:VERSION,started:state.started,kind:state.kind,occurrenceId:state.occurrenceId,roomId:state.roomId,supplyScope:state.supplyScope};}});
  start();
})();

export const CLEANING_DETAIL_VISUAL_V221_VERSION='2.2.1';