'use strict';
// ============================================================
// CLEANING EXCEPTION TASK UI v0.2.1
// Adds one compact 'Niet alles gelukt?' path to managed Cleaning tasks.
// It owns only its own sheet and never rewrites TaskDetailPopup markup/state.
//
// v0.2.0 adds a fourth option, 'Vraag hulp' (STEP 14 Blok 2.4): the current
// assignee can ask one other active household member to help with THIS
// occurrence. It never auto-accepts; the recipient sees their own
// accept/decline card via CleaningHelpRequestUi.
// v0.2.1 simplifies the incomplete-work copy without changing semantics.
// ============================================================
(function(){
  if(window.CleaningExceptionTaskUi)return;

  var VERSION='0.2.1';
  var state={observer:null,queued:false,sheet:null,busy:false,confirmAction:null};

  function text(value){return String(value==null?'':value).trim();}
  function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
  function pad(value){return value<10?'0'+value:String(value);}
  function localIso(value){var d=new Date(Number(value)||Date.now());return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}
  function guardTaskId(){try{var guard=window.CleaningExecutionUiGuard,status=guard&&guard.status?guard.status():null;return text(status&&status.currentTaskId);}catch(error){return'';}}
  function taskById(id){var rows=[];try{var repo=window.TaskHouseholdRepository||window.TaskRepository;rows=repo&&repo.list?repo.list():(window.taskData||[]);}catch(error){rows=window.taskData||[];}for(var i=0;i<rows.length;i++){var row=rows[i];if(text(row&&(row.id||row._key))===text(id)||text(row&&row._key)===text(id))return row;}return null;}
  function managed(task){var contract=window.CleaningExecutionSync;return !!(contract&&contract._isCleaningProjection&&contract._isCleaningProjection(task));}
  function occurrenceIds(task){var contract=window.CleaningExecutionSync;return contract&&contract._recordOccurrenceIds?contract._recordOccurrenceIds(task):[];}
  function root(){try{var repo=window.CleaningHouseholdRepository,snap=repo&&repo.snapshot?repo.snapshot():null;return snap&&snap.data||{};}catch(error){return{};}}
  function toast(message){if(typeof window.showToast==='function')window.showToast(message);}

  function remaining(task){var rows=Array.isArray(task&&task.subtasks)?task.subtasks:[];return rows.filter(function(item){return !(item&&(item.done===true||item.completed===true));});}
  function planWindow(task){var data=root(),ids=occurrenceIds(task),occurrence=ids.length&&data.occurrences&&data.occurrences[ids[0]],plan=occurrence&&data.plans&&data.plans[occurrence.planId];return plan?{startAt:Number(plan.windowStartAt)||0,endAt:Number(plan.windowEndAt)||0}:null;}
  function rescheduleRange(task){var windowValue=planWindow(task),today=new Date();today.setHours(0,0,0,0);var min=today.getTime(),max=windowValue&&windowValue.endAt?windowValue.endAt-1:min+6*86400000;if(windowValue&&windowValue.startAt)min=Math.max(min,windowValue.startAt);if(max<min)return null;var proposed=Math.min(max,min+86400000);return{min:localIso(min),max:localIso(max),value:localIso(proposed)};}

  function currentUid(){try{return text(window.HouseholdContext&&window.HouseholdContext.snapshot&&window.HouseholdContext.snapshot().uid);}catch(error){return'';}}
  function activeMembers(){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[];return(Array.isArray(rows)?rows:[]).filter(function(row){return row&&text(row.uid)&&text(row.status||'active').toLowerCase()==='active';});}catch(error){return[];}}
  function helpCandidates(task){var uid=currentUid(),ids=occurrenceIds(task),data=root(),occurrence=ids.length&&data.occurrences&&data.occurrences[ids[0]],assigned=occurrence&&Array.isArray(occurrence.assignmentUids)?occurrence.assignmentUids.map(String):[];return activeMembers().filter(function(member){var memberUid=text(member.uid);return memberUid&&memberUid!==uid&&assigned.indexOf(memberUid)<0;});}
  function currentHelpRequest(task){var ids=occurrenceIds(task),data=root(),occurrence=ids.length&&data.occurrences&&data.occurrences[ids[0]];return occurrence&&occurrence.helpRequest&&typeof occurrence.helpRequest==='object'?occurrence.helpRequest:null;}
  function memberDisplayName(uid){var found=activeMembers().find(function(member){return text(member.uid)===text(uid);});return found?text(found.displayName||found.name)||'Gezinslid':'Gezinslid';}

  function ensureStyle(){if(document.getElementById('cleaning-exception-task-ui-style'))return;var style=document.createElement('style');style.id='cleaning-exception-task-ui-style';style.textContent='\n'
    +'#tdp-overlay .cleaning-exception-entry{width:100%;min-height:39px;margin:0 0 9px;border:1px dashed color-mix(in srgb,var(--tdp-purple) 40%,var(--tdp-border-soft));border-radius:12px;background:color-mix(in srgb,var(--tdp-purple) 6%,var(--tdp-surface));color:var(--tdp-purple);font:inherit;font-size:10.5px;font-weight:850;cursor:pointer}\n'
    +'.cleaning-exception-overlay{position:fixed;inset:0;z-index:12500;display:grid;align-items:end;background:rgba(8,10,16,.46);padding-top:max(24px,env(safe-area-inset-top));touch-action:manipulation}.cleaning-exception-sheet{width:100%;max-height:90vh;overflow:auto;-webkit-overflow-scrolling:touch;border-radius:28px 28px 0 0;background:var(--c-surface,#fff);color:var(--c-text,#1e232b);padding:12px 16px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -20px 60px rgba(0,0,0,.18)}\n'
    +'.cleaning-exception-handle{width:38px;height:4px;border-radius:999px;background:var(--c-border,#ddd);margin:0 auto 15px}.cleaning-exception-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.cleaning-exception-head p{margin:0 0 4px;color:var(--c-primary,#6750a4);font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.cleaning-exception-head h2{margin:0;font-size:21px}.cleaning-exception-close{width:44px;height:44px;border-radius:13px;border:1px solid var(--c-border,#ddd);background:var(--c-surface,#fff);color:inherit;font:inherit;font-size:18px}.cleaning-exception-copy{margin:0 0 13px;color:var(--c-text2,#737784);font-size:11px;line-height:1.45}\n'
    +'.cleaning-exception-option{display:grid;gap:8px;padding:13px;margin-bottom:9px;border:1px solid var(--c-border,#ddd);border-radius:16px;background:var(--c-surface2,#f7f7f8)}.cleaning-exception-option strong{font-size:12px}.cleaning-exception-option span{font-size:10px;line-height:1.4;color:var(--c-text2,#737784)}.cleaning-exception-date-row{display:grid;grid-template-columns:1.35fr 1fr;gap:7px}.cleaning-exception-date-row input{min-width:0;border:1px solid var(--c-border,#ddd);border-radius:11px;padding:9px;background:var(--c-surface,#fff);color:inherit;font:inherit;font-size:12px}.cleaning-exception-action{min-height:43px;border:0;border-radius:12px;background:var(--c-primary,#6750a4);color:#fff;font:inherit;font-size:11px;font-weight:900}.cleaning-exception-action.secondary{background:var(--c-surface,#fff);color:var(--c-text,#1e232b);border:1px solid var(--c-border,#ddd)}.cleaning-exception-action.danger{background:#b32636}.cleaning-exception-action:disabled{opacity:.5}\n';document.head.appendChild(style);}

  function decorate(){state.queued=false;ensureStyle();var overlay=document.getElementById('tdp-overlay');if(!overlay||!overlay.classList.contains('open'))return;var task=taskById(guardTaskId());if(!managed(task)||task.done===true)return;var left=remaining(task),footer=overlay.querySelector('.tdp-footer');if(!footer||!left.length)return;var button=overlay.querySelector('[data-cleaning-exception-entry]');if(!button){button=document.createElement('button');button.type='button';button.className='cleaning-exception-entry';button.setAttribute('data-cleaning-exception-entry','1');footer.parentNode.insertBefore(button,footer);}button.textContent='Niet alles gelukt? · '+left.length+' '+(left.length===1?'stap over':'stappen over');}
  function queue(){if(state.queued)return;state.queued=true;(window.requestAnimationFrame||function(callback){return setTimeout(callback,0);})(decorate);}

  function sheetHtml(task){var left=remaining(task),range=rescheduleRange(task),disabled=!range||state.busy;return '<section class="cleaning-exception-sheet"><div class="cleaning-exception-handle"></div><div class="cleaning-exception-head"><div><p>Schoonmaakbeurt</p><h2>Niet alles gelukt?</h2></div><button type="button" class="cleaning-exception-close" data-cleaning-exception-close aria-label="Sluiten">✕</button></div><p class="cleaning-exception-copy">Nog '+left.length+' '+(left.length===1?'stap':'stappen')+' open. Wat wil je doen?</p>'
    +'<article class="cleaning-exception-option"><strong>↻ Later deze week</strong><span>Plan alleen de open stappen opnieuw.</span>'+(range?'<div class="cleaning-exception-date-row"><input type="date" data-cleaning-exception-date min="'+esc(range.min)+'" max="'+esc(range.max)+'" value="'+esc(range.value)+'"><input type="time" data-cleaning-exception-time aria-label="Tijd optioneel"></div><button type="button" class="cleaning-exception-action" data-cleaning-exception-action="RESCHEDULE"'+(disabled?' disabled':'')+'>Later inplannen</button>':'<span>Deze week is geen later moment meer beschikbaar.</span>')+'</article>'
    +'<article class="cleaning-exception-option"><strong>→ Volgende beurt</strong><span>Stop voor nu. De routine gaat verder bij de volgende normale beurt.</span><button type="button" class="cleaning-exception-action secondary" data-cleaning-exception-action="CARRY_FORWARD"'+(state.busy?' disabled':'')+'>'+(state.confirmAction==='CARRY_FORWARD'?'Nogmaals tikken om te bevestigen':'Doorschuiven')+'</button></article>'
    +'<article class="cleaning-exception-option"><strong>⏭ Rest overslaan</strong><span>Sla de open stappen van deze beurt over.</span><button type="button" class="cleaning-exception-action danger" data-cleaning-exception-action="SKIP"'+(state.busy?' disabled':'')+'>'+(state.confirmAction==='SKIP'?'Nogmaals tikken om te bevestigen':'Overslaan')+'</button></article>'
    +helpOptionHtml(task)+'</section>';}
  function helpOptionHtml(task){
    var pending=currentHelpRequest(task);
    if(pending&&text(pending.status)==='PENDING')return '<article class="cleaning-exception-option"><strong>🤝 Hulp gevraagd</strong><span>'+esc(memberDisplayName(pending.toUid))+' heeft je hulpvraag ontvangen. Je krijgt bericht na een reactie.</span></article>';
    var candidates=helpCandidates(task);
    if(!candidates.length)return '';
    var options=candidates.map(function(member){return '<option value="'+esc(member.uid)+'">'+esc(text(member.displayName||member.name)||'Gezinslid')+'</option>';}).join('');
    return '<article class="cleaning-exception-option"><strong>🤝 Vraag hulp</strong><span>Vraag iemand om bij deze beurt mee te helpen.</span>'
      +'<div class="cleaning-exception-date-row"><select data-cleaning-exception-help-target>'+options+'</select><button type="button" class="cleaning-exception-action secondary" data-cleaning-exception-action="REQUEST_HELP"'+(state.busy?' disabled':'')+'>Hulp vragen</button></div></article>';
  }
  function openSheet(){var task=taskById(guardTaskId());if(!managed(task))return;state.sheet={taskId:text(task.id||task._key)};state.confirmAction=null;renderSheet();}
  function closeSheet(){state.sheet=null;state.confirmAction=null;var overlay=document.getElementById('cleaning-exception-overlay');if(overlay)overlay.remove();}
  function renderSheet(){if(!state.sheet)return;ensureStyle();var task=taskById(state.sheet.taskId);if(!managed(task)){closeSheet();return;}var overlay=document.getElementById('cleaning-exception-overlay');if(!overlay){overlay=document.createElement('div');overlay.id='cleaning-exception-overlay';overlay.className='cleaning-exception-overlay';document.body.appendChild(overlay);}overlay.innerHTML=sheetHtml(task);}

  function run(action){var task=taskById(state.sheet&&state.sheet.taskId);if(!task||state.busy)return;if(action==='SKIP'||action==='CARRY_FORWARD'){if(state.confirmAction!==action){state.confirmAction=action;renderSheet();return;}}var runtime=window.CleaningExceptionRuntime;if(!runtime||typeof runtime.apply!=='function'){toast('Deze schoonmaakactie is nog niet beschikbaar');return;}var options={};if(action==='RESCHEDULE'){var overlay=document.getElementById('cleaning-exception-overlay'),date=overlay&&overlay.querySelector('[data-cleaning-exception-date]'),time=overlay&&overlay.querySelector('[data-cleaning-exception-time]');options.date=text(date&&date.value);options.time=text(time&&time.value);}if(action==='REQUEST_HELP'){var helpOverlay=document.getElementById('cleaning-exception-overlay'),target=helpOverlay&&helpOverlay.querySelector('[data-cleaning-exception-help-target]');options.toUid=text(target&&target.value);if(!options.toUid){toast('Kies eerst een gezinslid.');return;}}state.busy=true;state.confirmAction=null;renderSheet();runtime.apply({task:task,action:action,options:options}).then(function(){state.busy=false;if(action==='REQUEST_HELP'){renderSheet();toast('Hulpverzoek verstuurd ✓');return;}closeSheet();if(window.TaskDetailPopup&&TaskDetailPopup.close)TaskDetailPopup.close();toast(action==='RESCHEDULE'?'Schoonmaakbeurt opnieuw ingepland ✓':action==='CARRY_FORWARD'?'Open stappen doorgeschoven naar de volgende beurt ✓':'Schoonmaakbeurt overgeslagen ✓');}).catch(function(error){state.busy=false;toast(runtime.userMessage?runtime.userMessage(error):((error&&error.message)||'Actie mislukt'));renderSheet();});}

  function onClick(event){var target=event.target,closest=target&&target.closest?target.closest.bind(target):null;if(!closest)return;if(closest('[data-cleaning-exception-entry]')){event.preventDefault();event.stopPropagation();openSheet();return;}var sheet=document.getElementById('cleaning-exception-overlay');if(!sheet)return;if(closest('[data-cleaning-exception-close]')||event.target===sheet){event.preventDefault();closeSheet();return;}var action=closest('[data-cleaning-exception-action]');if(action&&!action.disabled){event.preventDefault();run(text(action.getAttribute('data-cleaning-exception-action')));}}
  function onKey(event){if(event.key==='Escape'&&state.sheet){event.preventDefault();closeSheet();}}
  function start(){if(window.__cleaningExceptionTaskUiStarted)return;window.__cleaningExceptionTaskUiStarted=true;ensureStyle();document.addEventListener('click',onClick,true);document.addEventListener('keydown',onKey,true);if(typeof MutationObserver!=='undefined'){state.observer=new MutationObserver(queue);state.observer.observe(document.body,{childList:true,subtree:true});}window.addEventListener('familyapp:cleaning-exception',queue);queue();}

  window.CleaningExceptionTaskUi={version:VERSION,start:start,close:closeSheet,_rescheduleRange:rescheduleRange,_remaining:remaining,_helpCandidates:helpCandidates};start();
})();
