'use strict';
// ============================================================
// CLEANING V2.2 HISTORY CONTRACT
// Pure read-model helpers over canonical Cleaning completionLogs/occurrences.
// No Firebase, DOM, notifications or persistence.
// ============================================================
(function(){
  if(window.CleaningHistoryContract)return;
  var VERSION='2.2.0';
  var DAY_MS=86400000;
  function text(value){return String(value==null?'':value).trim();}
  function num(value){var n=Number(value);return Number.isFinite(n)?n:0;}
  function clone(value){try{return JSON.parse(JSON.stringify(value));}catch(error){return value;}}
  function at(log){return num(log&&(log.completedAt||log.finalizedAt||log.reopenedAt||log.createdAt||log.updatedAt));}
  function localMidnight(value){var d=new Date(num(value)||Date.now());d.setHours(0,0,0,0);return d.getTime();}
  function dateAtLocalMidnight(value){var match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(text(value));if(!match)return 0;var d=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),0,0,0,0);return isNaN(d.getTime())?0:d.getTime();}
  function roomName(data,roomId){var row=data&&data.rooms&&data.rooms[roomId];return text(row&&row.name)||'Verwijderde ruimte';}
  function routineName(data,routineId,fallback){var row=data&&data.routines&&data.routines[routineId];return text(row&&row.title)||text(fallback)||'Schoonmaakroutine';}
  function actorUid(log){return text(log&&(log.completedByUid||log.finalizedByUid||log.createdByUid||log.updatedByUid))||null;}
  function completed(log){var status=text(log&&log.status).toUpperCase(),outcome=text(log&&log.outcome).toUpperCase();if(['REOPENED','SKIPPED','PARTIAL','CARRIED_FORWARD','CARRY_FORWARD'].indexOf(status)>=0)return false;if(['REOPENED','SKIP','SKIPPED','PARTIAL','CARRIED_FORWARD','CARRY_FORWARD'].indexOf(outcome)>=0)return false;return status==='COMPLETED'||outcome==='COMPLETED';}
  function outcomeLabel(log){var status=text(log&&(log.status||log.outcome)).toUpperCase();if(status==='COMPLETED')return'Afgerond';if(status==='REOPENED')return'Heropend';if(status==='PARTIAL')return'Deels gedaan';if(status==='SKIP'||status==='SKIPPED')return'Overgeslagen';if(status==='CARRY_FORWARD'||status==='CARRIED_FORWARD')return'Doorgeschoven';return status||'Bijgewerkt';}
  function logs(data){var source=data&&data.completionLogs&&typeof data.completionLogs==='object'?data.completionLogs:{};return Object.keys(source).map(function(id){return Object.assign({id:id,_at:at(source[id])},clone(source[id])||{});}).filter(function(row){return row._at>0;}).sort(function(a,b){return b._at-a._at;});}
  function routineTouches(data,roomLogs){var map={};(roomLogs||[]).forEach(function(log){var remaining=(Array.isArray(log.remainingRoutineItemIds)?log.remainingRoutineItemIds:[]).map(String);(Array.isArray(log.checklist)?log.checklist:[]).forEach(function(item){var id=text(item&&(item.routineItemId||item.sourceRoutineItemId||item.id));if(!id)return;var status=item&&item.completed===true?'COMPLETED':(remaining.indexOf(id)>=0?'PARTIAL':text(log.status||log.outcome).toUpperCase()||'PARTIAL');var existing=map[id];if(!existing||log._at>existing.lastAt)map[id]={id:id,title:routineName(data,id,item&&item.title),lastAt:log._at,lastStatus:status,lastByUid:actorUid(log),count30:0,totalCount:0};map[id].totalCount++;if(log._at>=Date.now()-30*DAY_MS)map[id].count30++;});});return Object.keys(map).map(function(id){return map[id];}).sort(function(a,b){return b.lastAt-a.lastAt;});}
  function roomRows(data,nowAt){var all=logs(data),byRoom={},cutoff=(num(nowAt)||Date.now())-30*DAY_MS;all.forEach(function(log){var id=text(log.roomId)||'unknown';if(!byRoom[id])byRoom[id]=[];byRoom[id].push(log);});return Object.keys(byRoom).map(function(roomId){var roomLogs=byRoom[roomId],last=roomLogs[0];return{roomId:roomId,name:roomName(data,roomId),lastAt:last&&last._at||0,lastStatus:outcomeLabel(last),lastByUid:actorUid(last),activity30:roomLogs.filter(function(row){return row._at>=cutoff&&completed(row);}).length,totalCompleted:roomLogs.filter(completed).length,routines:routineTouches(data,roomLogs),logs:roomLogs};}).sort(function(a,b){return b.lastAt-a.lastAt;});}
  function weekStart(value){var d=new Date(num(value)||Date.now());d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d.getTime();}
  function summary(data,nowAt){var start=weekStart(nowAt),end=start+7*DAY_MS,rows=logs(data).filter(function(row){return completed(row)&&row._at>=start&&row._at<end;}),minutes=rows.reduce(function(sum,row){return sum+Math.max(0,num(row.actualMinutes||row.estimatedMinutes));},0),people={};rows.forEach(function(row){var uid=actorUid(row);if(uid)people[uid]=true;});return{weekCount:rows.length,weekMinutes:Math.round(minutes),peopleCount:Object.keys(people).length,totalCompleted:logs(data).filter(completed).length};}
  function dueAt(row){if(!row)return 0;var byDate=dateAtLocalMidnight(row.scheduledDate);if(byDate)return byDate;var scheduled=num(row.scheduledStartAt);if(scheduled)return localMidnight(scheduled);var flexible=num(row.flexibleWindow&&row.flexibleWindow.startAt);if(flexible)return localMidnight(flexible);var earliest=num(row.earliestDueAt);if(earliest)return localMidnight(earliest);return 0;}
  function remindable(row,uid){if(!row||!uid)return false;var assigned=Array.isArray(row.assignmentUids)&&row.assignmentUids.map(String).indexOf(String(uid))>=0;if(!assigned)return false;var status=text(row.status).toUpperCase(),assignment=text(row.assignmentStatus).toUpperCase();return ['COMPLETED','CANCELLED','SKIPPED','PROPOSED'].indexOf(status)<0&&['COMPLETED','CANCELLED','SKIPPED','PROPOSED'].indexOf(assignment)<0;}
  function reminders(data,uid,nowAt){var today=localMidnight(nowAt),rows=data&&data.occurrences&&typeof data.occurrences==='object'?data.occurrences:{},todayCount=0,overdueCount=0,todayMinutes=0,overdueMinutes=0;Object.keys(rows).forEach(function(id){var row=rows[id];if(!remindable(row,uid))return;var due=dueAt(row);if(!due)return;var minutes=Math.max(0,num(row.estimatedMinutes));if(due<today){overdueCount++;overdueMinutes+=minutes;}else if(due===today){todayCount++;todayMinutes+=minutes;}});return{todayCount:todayCount,overdueCount:overdueCount,todayMinutes:Math.round(todayMinutes),overdueMinutes:Math.round(overdueMinutes),hasReminder:todayCount>0||overdueCount>0};}
  function activityEvent(data,id,log){if(!completed(log))return null;var room=roomName(data,log&&log.roomId),checklist=Array.isArray(log&&log.checklist)?log.checklist:[],minutes=Math.max(0,Math.round(num(log&&(log.actualMinutes||log.estimatedMinutes)))),detail=[];if(checklist.length)detail.push(checklist.length+' '+(checklist.length===1?'routine':'routines'));if(minutes)detail.push(minutes+' min');return{type:'cleaning.completed',occurrenceKey:'cleaning:completion:'+String(id),occurredAt:at(log)||Date.now(),actorUid:actorUid(log),source:{module:'cleaning',entityType:'cleaningCompletionLog',entityId:String(id)},payload:{title:room+' schoongemaakt',message:'Schoonmaak afgerond in '+room,detail:detail.join(' · ')||null,roomId:text(log&&log.roomId)||null,roomName:room,routineCount:checklist.length,actualMinutes:minutes||null,completionLogId:String(id)}};}
  window.CleaningHistoryContract=Object.freeze({version:VERSION,logs:logs,roomRows:roomRows,routineTouches:routineTouches,summary:summary,reminders:reminders,dueAt:dueAt,remindable:remindable,activityEvent:activityEvent,completed:completed,outcomeLabel:outcomeLabel});
})();
