'use strict';
import './cleaningCollaborationContract.js?v=1';

// CLEANING COLLABORATION EXPERIENCE v2.1.0
// Lazy Cleaning-only companion surface. It reuses CleaningV2Repository's one
// canonical snapshot/listener and owns only collaboration commands + a small
// inline panel. No MutationObserver, document click owner or popup owner.
const VERSION='2.1.0';
const state={bound:false,repo:null,unsubscribe:null,panel:null,draft:null,busy:new Set(),lastSnapshot:null};

function text(value){return String(value==null?'':value).trim();}
function esc(value){return String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function clone(value){if(value===undefined)return undefined;try{return JSON.parse(JSON.stringify(value));}catch(error){return value;}}
function context(){try{return window.HouseholdContext&&typeof window.HouseholdContext.snapshot==='function'?window.HouseholdContext.snapshot():null;}catch(error){return null;}}
function capture(){try{return window.HouseholdContext&&typeof window.HouseholdContext.capture==='function'?window.HouseholdContext.capture():null;}catch(error){return null;}}
function isCurrent(token){try{return !!(window.HouseholdContext&&typeof window.HouseholdContext.isCurrent==='function'&&window.HouseholdContext.isCurrent(token));}catch(error){return false;}}
function db(){try{return window.fbDb||(window.firebase&&typeof window.firebase.database==='function'&&window.firebase.database())||null;}catch(error){return null;}}
function members(){try{var bridge=window.HouseholdIdentityFirebaseBridge,rows=bridge&&bridge.getMembers?bridge.getMembers():[];return (Array.isArray(rows)?rows:[]).filter(function(row){return row&&text(row.uid||row.id)&&text(row.status||'active').toLowerCase()==='active';});}catch(error){return[];}}
function memberUid(row){return text(row&&(row.uid||row.id));}
function memberName(uid){var wanted=text(uid),row=members().find(function(item){return memberUid(item)===wanted;});return row?text(row.displayName||row.name)||'Gezinslid':'Gezinslid';}
function activeUids(){return members().map(memberUid).filter(Boolean);}
function role(){var me=text(context()&&context().uid),row=members().find(function(item){return memberUid(item)===me;}),raw=text(row&&row.role).toLowerCase();return ['owner','admin','manager','beheerder'].includes(raw)?'MANAGER':(['adult','member','gezinslid'].includes(raw)?'MEMBER':(['child','limited','restricted','beperkt'].includes(raw)?'LIMITED':'UNKNOWN'));}
function isManager(){return role()==='MANAGER';}
function toast(message){if(typeof window.showToast==='function')window.showToast(message);else try{console.info('[CleaningCollaborationV21]',message);}catch(error){}}
function safeKey(value){return text(value).replace(/[.#$\[\]\/\u0000-\u001F\u007F]/g,'_');}
function recordOccurrenceIds(row){var ids=[];(Array.isArray(row&&row.cleaningOccurrenceIds)?row.cleaningOccurrenceIds:[]).forEach(function(value){var id=text(value);if(id&&ids.indexOf(id)<0)ids.push(id);});[row&&row.cleaningOccurrenceId,row&&row.sourceId].forEach(function(value){var id=text(value);if(id&&ids.indexOf(id)<0)ids.push(id);});return ids;}
function occurrenceById(id){var data=state.lastSnapshot&&state.lastSnapshot.data,raw=data&&data.occurrences&&data.occurrences[id];return raw?Object.assign({id:id},raw):null;}
function roomName(occurrence){var data=state.lastSnapshot&&state.lastSnapshot.data,room=data&&data.rooms&&data.rooms[text(occurrence&&occurrence.roomId)];return text(room&&room.name)||'Ruimte';}
function formatDate(value){if(!value)return'Flexibel';try{var date=/^\d{4}-\d{2}-\d{2}$/.test(String(value))?new Date(String(value)+'T12:00:00'):new Date(Number(value)||value);return date.toLocaleDateString('nl-NL',{weekday:'short',day:'numeric',month:'short'});}catch(error){return text(value);}}
function openOccurrence(row){var s=text(row&&row.status).toUpperCase(),a=text(row&&row.assignmentStatus).toUpperCase();return !!row&&s!=='CANCELLED'&&s!=='SKIPPED'&&s!=='COMPLETED'&&a!=='SKIPPED'&&a!=='COMPLETED';}
function currentAssignee(row){return text(row&&row.assignmentUids&&row.assignmentUids[0]);}
function writeContext(){var ctx=context(),database=db(),token=capture();if(!ctx||ctx.ready!==true||!ctx.uid||!ctx.householdId)throw new Error('ACTIVE_HOUSEHOLD_REQUIRED');if(!database)throw new Error('FIREBASE_DATABASE_UNAVAILABLE');if(!token||!isCurrent(token))throw new Error('HOUSEHOLD_CONTEXT_CHANGED');return{ctx:ctx,db:database,token:token,familyPath:'families/'+ctx.householdId,cleaningPath:'families/'+ctx.householdId+'/cleaning'};}

function projectionTask(occurrenceId){var rows=Array.isArray(window.taskData)?window.taskData:[];return rows.find(function(row){return recordOccurrenceIds(row).indexOf(text(occurrenceId))>=0;})||null;}
function projectionEvent(occurrenceId){var repository=window.CalendarEventHouseholdRepository||window.CalendarEventRepository,rows=[];try{rows=repository&&typeof repository.list==='function'?repository.list():[];}catch(error){rows=[];}return (Array.isArray(rows)?rows:[]).find(function(row){return recordOccurrenceIds(row).indexOf(text(occurrenceId))>=0;})||null;}
function syncAcceptedProjection(occurrence,write){
  if(!occurrence)return Promise.resolve();var assigned=currentAssignee(occurrence),display=memberName(assigned),date=text(occurrence.scheduledDate),time=text(occurrence.scheduledTime),timestamp=Date.now(),updates={},task=projectionTask(occurrence.id),taskKey=task&&text(task._key||task.id);
  if(taskKey){updates['tasks/'+taskKey+'/assignedToUid']=assigned;updates['tasks/'+taskKey+'/assignedToUids']=assigned?{[assigned]:true}:{};updates['tasks/'+taskKey+'/who']=display?[display]:[];if(date){updates['tasks/'+taskKey+'/date']=date;updates['tasks/'+taskKey+'/dueDate']=date;}updates['tasks/'+taskKey+'/time']=time;updates['tasks/'+taskKey+'/updatedAt']=timestamp;updates['tasks/'+taskKey+'/updatedByUid']=write.ctx.uid;}
  var event=projectionEvent(occurrence.id),eventKey=event&&text(event._key||event.id);if(!eventKey&&occurrence.projections&&occurrence.projections.calendarEventId&&event)eventKey='id_'+safeKey(occurrence.projections.calendarEventId);if(eventKey){updates['calendarEvents/'+eventKey+'/assignedToUid']=assigned;updates['calendarEvents/'+eventKey+'/who']=display;if(date)updates['calendarEvents/'+eventKey+'/date']=date;updates['calendarEvents/'+eventKey+'/time']=time;updates['calendarEvents/'+eventKey+'/flexible']=!time;updates['calendarEvents/'+eventKey+'/updatedAt']=timestamp;updates['calendarEvents/'+eventKey+'/updatedByUid']=write.ctx.uid;}
  updates['cleaning/occurrences/'+safeKey(occurrence.id)+'/collaborationProjectionSyncedAt']=timestamp;updates['cleaning/occurrences/'+safeKey(occurrence.id)+'/collaborationProjectionSyncedByUid']=write.ctx.uid;
  return write.db.ref(write.familyPath).update(updates);
}

function applyCommand(occurrenceId,command){
  occurrenceId=text(occurrenceId);if(!occurrenceId)return Promise.reject(new Error('CLEANING_OCCURRENCE_REQUIRED'));if(state.busy.has(occurrenceId))return Promise.resolve({duplicateTap:true});var contract=window.CleaningCollaborationContract;if(!contract||typeof contract.apply!=='function')return Promise.reject(new Error('CLEANING_COLLABORATION_UNAVAILABLE'));
  var write;try{write=writeContext();}catch(error){return Promise.reject(error);}state.busy.add(occurrenceId);render();var outcome=null,idempotent=false,ref=write.db.ref(write.cleaningPath+'/occurrences/'+safeKey(occurrenceId));
  return ref.transaction(function(server){
    if(!server||typeof server!=='object'||!isCurrent(write.token))return;var result=contract.apply(server,command,{actorUid:write.ctx.uid,activeUids:activeUids(),timestamp:Date.now(),isManager:isManager()});outcome=result;if(result.changed===false){idempotent=true;return;}return result.occurrence;
  }).then(function(result){
    if(idempotent)return{changed:false,occurrence:occurrenceById(occurrenceId)};
    if(!result||result.committed!==true||!result.snapshot)throw new Error('CLEANING_COLLABORATION_WRITE_NOT_COMMITTED');var occurrence=Object.assign({id:occurrenceId},result.snapshot.val()),sync=outcome&&outcome.projectionChanged?syncAcceptedProjection(occurrence,write):Promise.resolve();return sync.then(function(){return{changed:true,occurrence:occurrence,retargeted:!!(outcome&&outcome.retargeted)};});
  }).finally(function(){state.busy.delete(occurrenceId);render();try{if(window.ActionInboxStore&&typeof window.ActionInboxStore.refresh==='function')window.ActionInboxStore.refresh();}catch(error){}});
}

function ensureStyle(){if(document.getElementById('cleaning-collaboration-v21-style'))return;var style=document.createElement('style');style.id='cleaning-collaboration-v21-style';style.textContent=''
  +'#cleaning-collaboration-v21{max-width:760px;margin:0 auto;padding:0 16px 26px}\n'
  +'#cleaning-collaboration-v21 .cc21-shell{border:1px solid var(--c-border);background:var(--c-card-bg,var(--c-bg2));border-radius:18px;padding:15px;box-shadow:0 6px 20px rgba(32,20,50,.05)}\n'
  +'#cleaning-collaboration-v21 .cc21-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}\n'
  +'#cleaning-collaboration-v21 .cc21-head span{display:block;font-size:11px;font-weight:800;letter-spacing:.35px;text-transform:uppercase;color:var(--c-text2);margin-bottom:3px}\n'
  +'#cleaning-collaboration-v21 .cc21-head strong{font-size:16px;color:var(--c-text)}\n'
  +'#cleaning-collaboration-v21 .cc21-inbox{border:0;background:rgba(124,58,237,.11);color:#6d28d9;border-radius:11px;min-height:40px;padding:0 12px;font-weight:800;font-size:12px}\n'
  +'#cleaning-collaboration-v21 .cc21-list{display:grid;gap:9px}\n'
  +'#cleaning-collaboration-v21 .cc21-row{border:1px solid var(--c-border);border-radius:14px;padding:12px;background:var(--c-bg,var(--c-bg2))}\n'
  +'#cleaning-collaboration-v21 .cc21-rowtop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}\n'
  +'#cleaning-collaboration-v21 .cc21-row strong{display:block;color:var(--c-text);font-size:13.5px}\n'
  +'#cleaning-collaboration-v21 .cc21-row small{display:block;color:var(--c-text2);font-size:11.5px;margin-top:2px}\n'
  +'#cleaning-collaboration-v21 .cc21-status{margin-top:8px;padding:8px 10px;border-radius:10px;background:rgba(245,158,11,.10);color:#a16207;font-size:11.5px;font-weight:700}\n'
  +'#cleaning-collaboration-v21 .cc21-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}\n'
  +'#cleaning-collaboration-v21 button{font:inherit;cursor:pointer}\n'
  +'#cleaning-collaboration-v21 .cc21-btn{min-height:40px;border-radius:11px;padding:0 12px;border:1px solid var(--c-border);background:var(--c-bg2);color:var(--c-text);font-size:12px;font-weight:800}\n'
  +'#cleaning-collaboration-v21 .cc21-btn.primary{border-color:transparent;background:#7c3aed;color:#fff}\n'
  +'#cleaning-collaboration-v21 .cc21-btn.danger{color:#b91c1c}\n'
  +'#cleaning-collaboration-v21 button:disabled{opacity:.5;cursor:default}\n'
  +'#cleaning-collaboration-v21 .cc21-form{margin-top:10px;border-top:1px solid var(--c-border);padding-top:11px;display:grid;gap:9px}\n'
  +'#cleaning-collaboration-v21 .cc21-form label{display:grid;gap:5px;font-size:11px;font-weight:800;color:var(--c-text2)}\n'
  +'#cleaning-collaboration-v21 .cc21-form select,#cleaning-collaboration-v21 .cc21-form input{width:100%;box-sizing:border-box;min-height:44px;border:1px solid var(--c-border);border-radius:11px;background:var(--c-bg2);color:var(--c-text);padding:0 11px;font:inherit}\n'
  +'#cleaning-collaboration-v21 .cc21-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}\n'
  +'#cleaning-collaboration-v21 .cc21-empty{color:var(--c-text2);font-size:12px;line-height:1.45;padding:4px 0}\n'
  +'[data-theme*="dark"] #cleaning-collaboration-v21 .cc21-inbox{background:rgba(216,181,82,.13);color:#e0bf69}\n'
  +'[data-theme*="dark"] #cleaning-collaboration-v21 .cc21-btn.primary{background:#d8b552;color:#241608}\n'
  +'@media(max-width:420px){#cleaning-collaboration-v21 .cc21-grid{grid-template-columns:1fr}}\n';document.head.appendChild(style);}
function ensurePanel(){var screen=document.getElementById('screen-cleaning');if(!screen)return null;var panel=document.getElementById('cleaning-collaboration-v21');if(!panel){panel=document.createElement('div');panel.id='cleaning-collaboration-v21';panel.setAttribute('data-cleaning-v21','collaboration');screen.appendChild(panel);panel.addEventListener('click',onClick);panel.addEventListener('submit',onSubmit);}state.panel=panel;return panel;}
function incomingCount(){var me=text(context()&&context().uid),data=state.lastSnapshot&&state.lastSnapshot.data,occurrences=data&&data.occurrences||{};if(!me)return 0;return Object.keys(occurrences).reduce(function(sum,id){var row=occurrences[id]||{},transfer=row.transferRequest||{},counter=transfer.counterProposal||{},help=row.helpRequest||{};if(text(transfer.status).toUpperCase()==='PENDING'&&text(transfer.toUid)===me)return sum+1;if(text(transfer.status).toUpperCase()==='COUNTER_PROPOSED'&&text(counter.status).toUpperCase()==='PENDING'&&text(transfer.fromUid)===me)return sum+1;if(text(help.status).toUpperCase()==='PENDING'&&text(help.toUid)===me)return sum+1;return sum;},0);}
function optionRows(excludeUid){return members().filter(function(row){return memberUid(row)!==text(excludeUid);}).map(function(row){return'<option value="'+esc(memberUid(row))+'">'+esc(text(row.displayName||row.name)||'Gezinslid')+'</option>';}).join('');}
function formMarkup(row){var draft=state.draft;if(!draft||draft.occurrenceId!==row.id)return'';var assignee=currentAssignee(row),transfer=row.transferRequest||{},counter=transfer.counterProposal||{};
  if(draft.kind==='transfer')return'<form class="cc21-form" data-cc21-form="transfer" data-occurrence-id="'+esc(row.id)+'"><label>Overdragen aan<select name="toUid" required><option value="">Kies gezinslid</option>'+optionRows(assignee)+'</select></label><div class="cc21-actions"><button class="cc21-btn primary" type="submit">Verzoek sturen</button><button class="cc21-btn" type="button" data-cc21-cancel>Annuleren</button></div></form>';
  if(draft.kind==='help')return'<form class="cc21-form" data-cc21-form="help" data-occurrence-id="'+esc(row.id)+'"><label>Hulp vragen aan<select name="toUid" required><option value="">Kies gezinslid</option>'+optionRows(text(context()&&context().uid))+'</select></label><div class="cc21-actions"><button class="cc21-btn primary" type="submit">Hulp vragen</button><button class="cc21-btn" type="button" data-cc21-cancel>Annuleren</button></div></form>';
  if(draft.kind==='counter')return'<form class="cc21-form" data-cc21-form="counter" data-occurrence-id="'+esc(row.id)+'"><label>Wie neemt de beurt?<select name="assigneeUid" required>'+members().map(function(member){var uid=memberUid(member),selected=uid===text(counter.assigneeUid||context()&&context().uid)?' selected':'';return'<option value="'+esc(uid)+'"'+selected+'>'+esc(text(member.displayName||member.name)||'Gezinslid')+'</option>';}).join('')+'</select></label><div class="cc21-grid"><label>Dag<input type="date" name="scheduledDate" value="'+esc(text(row.scheduledDate))+'"></label><label>Tijd<input type="time" name="scheduledTime" value="'+esc(text(row.scheduledTime))+'"></label></div><div class="cc21-actions"><button class="cc21-btn primary" type="submit">Tegenvoorstel sturen</button><button class="cc21-btn" type="button" data-cc21-cancel>Annuleren</button></div></form>';
  return'';
}
function rowMarkup(row){var me=text(context()&&context().uid),assignee=currentAssignee(row),transfer=row.transferRequest||{},help=row.helpRequest||{},transferStatus=text(transfer.status).toUpperCase(),helpStatus=text(help.status).toUpperCase(),busy=state.busy.has(row.id),status='';
  if((transferStatus==='PENDING'||transferStatus==='COUNTER_PROPOSED')&&text(transfer.fromUid)===me)status=transferStatus==='COUNTER_PROPOSED'?'Tegenvoorstel ontvangen — beslis via de Actie-inbox.':'Overdracht naar '+memberName(transfer.toUid)+' wacht op akkoord.';
  else if(helpStatus==='PENDING'&&text(help.fromUid)===me)status='Hulp gevraagd aan '+memberName(help.toUid)+' — wacht op reactie.';
  else if(helpStatus==='ACCEPTED'&&text(help.fromUid)===me)status=memberName(help.helperUid||help.toUid)+' helpt mee met deze beurt.';
  var canInitiate=assignee===me||isManager(),transferOpen=(transferStatus==='PENDING'||transferStatus==='COUNTER_PROPOSED')&&text(transfer.fromUid)===me,helpOpen=helpStatus==='PENDING'&&text(help.fromUid)===me;
  return'<article class="cc21-row"><div class="cc21-rowtop"><div><strong>'+esc(roomName(row))+'</strong><small>'+esc(formatDate(row.scheduledDate||row.earliestDueAt))+' · '+esc(memberName(assignee))+'</small></div></div>'+(status?'<div class="cc21-status">'+esc(status)+'</div>':'')+'<div class="cc21-actions">'+(transferOpen?'<button type="button" class="cc21-btn danger" data-cc21-withdraw-transfer="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Overdracht intrekken</button>':(canInitiate?'<button type="button" class="cc21-btn" data-cc21-open-transfer="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Overdragen</button>':''))+(helpOpen?'<button type="button" class="cc21-btn danger" data-cc21-withdraw-help="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Hulpvraag intrekken</button>':(canInitiate?'<button type="button" class="cc21-btn" data-cc21-open-help="'+esc(row.id)+'"'+(busy?' disabled':'')+'>Hulp vragen</button>':''))+'</div>'+formMarkup(row)+'</article>';}
function visibleOccurrences(){var me=text(context()&&context().uid),data=state.lastSnapshot&&state.lastSnapshot.data,map=data&&data.occurrences||{};return Object.keys(map).map(function(id){return Object.assign({id:id},map[id]||{});}).filter(function(row){return openOccurrence(row)&&(currentAssignee(row)===me||isManager()||state.draft&&state.draft.occurrenceId===row.id);}).sort(function(a,b){var da=text(a.scheduledDate),dbb=text(b.scheduledDate);return da.localeCompare(dbb)||text(a.id).localeCompare(text(b.id));}).slice(0,12);}
function render(){var panel=ensurePanel();if(!panel)return;var snapshot=state.lastSnapshot;if(!snapshot||snapshot.ready!==true){panel.innerHTML='';return;}var rows=visibleOccurrences(),count=incomingCount();panel.innerHTML='<section class="cc21-shell"><div class="cc21-head"><div><span>Cleaning V2.1</span><strong>Samenwerken</strong></div>'+(count?'<button type="button" class="cc21-inbox" data-cc21-inbox>'+count+' '+(count===1?'beslissing':'beslissingen')+'</button>':'')+'</div>'+(rows.length?'<div class="cc21-list">'+rows.map(rowMarkup).join('')+'</div>':'<div class="cc21-empty">Geen open beurten waarvoor je nu een overdracht of hulpvraag hoeft te beheren.</div>')+'</section>';}
function openInbox(){if(window.ActionInboxScreen&&typeof window.ActionInboxScreen.ensure==='function')window.ActionInboxScreen.ensure();if(typeof window.showScreen==='function')window.showScreen('inbox');var title=document.getElementById('hdr-title');if(title)title.textContent='Inbox';}
function onClick(event){var target=event.target&&event.target.closest?event.target.closest('button'):null;if(!target)return;if(target.hasAttribute('data-cc21-inbox')){openInbox();return;}if(target.hasAttribute('data-cc21-cancel')){state.draft=null;render();return;}if(target.dataset.cc21OpenTransfer){state.draft={kind:'transfer',occurrenceId:target.dataset.cc21OpenTransfer};render();return;}if(target.dataset.cc21OpenHelp){state.draft={kind:'help',occurrenceId:target.dataset.cc21OpenHelp};render();return;}if(target.dataset.cc21WithdrawTransfer){applyCommand(target.dataset.cc21WithdrawTransfer,{type:'WITHDRAW_TRANSFER'}).then(function(){toast('Overdracht ingetrokken');}).catch(function(error){toast(text(error&&error.message)||'Intrekken mislukt');});return;}if(target.dataset.cc21WithdrawHelp){applyCommand(target.dataset.cc21WithdrawHelp,{type:'WITHDRAW_HELP'}).then(function(){toast('Hulpvraag ingetrokken');}).catch(function(error){toast(text(error&&error.message)||'Intrekken mislukt');});}}
function formValues(form){var data=new FormData(form),out={};data.forEach(function(value,key){out[key]=value;});return out;}
function onSubmit(event){var form=event.target;if(!form||!form.dataset||!form.dataset.cc21Form)return;event.preventDefault();var id=text(form.dataset.occurrenceId),values=formValues(form),kind=form.dataset.cc21Form,command=kind==='transfer'?{type:'REQUEST_TRANSFER',toUid:values.toUid}:kind==='help'?{type:'REQUEST_HELP',toUid:values.toUid}:{type:'COUNTER_TRANSFER',assigneeUid:values.assigneeUid,scheduledDate:values.scheduledDate,scheduledTime:values.scheduledTime};Array.from(form.elements||[]).forEach(function(el){el.disabled=true;});applyCommand(id,command).then(function(result){state.draft=null;toast(kind==='transfer'?'Overdracht gevraagd ✓':kind==='help'?'Hulp gevraagd ✓':'Tegenvoorstel verstuurd ✓');if(result&&result.retargeted)toast('Nieuw akkoord gevraagd aan het voorgestelde gezinslid.');}).catch(function(error){Array.from(form.elements||[]).forEach(function(el){el.disabled=false;});toast(text(error&&error.message)||'Verzoek kon niet worden opgeslagen.');});}
function openCounter(occurrenceId){state.draft={kind:'counter',occurrenceId:text(occurrenceId)};if(typeof window.showScreen==='function')window.showScreen('cleaning');render();return Promise.resolve(true);}
function handleInboxAction(occurrenceId,actionId){var action=text(actionId).toLowerCase();if(action==='counter')return openCounter(occurrenceId);var map={accept:'ACCEPT_TRANSFER',decline:'DECLINE_TRANSFER','accept-counter':'ACCEPT_COUNTER','decline-counter':'DECLINE_COUNTER','accept-help':'ACCEPT_HELP','decline-help':'DECLINE_HELP'};var command=map[action];if(!command)return Promise.reject(new Error('CLEANING_COLLAB_UNKNOWN_ACTION'));return applyCommand(occurrenceId,{type:command});}
function bindRepository(){var repo=window.CleaningHouseholdRepository;if(!repo||typeof repo.subscribe!=='function'||state.bound)return false;state.repo=repo;state.bound=true;ensureStyle();ensurePanel();state.unsubscribe=repo.subscribe(function(snapshot){state.lastSnapshot=snapshot;render();});render();return true;}
function waitForRepository(attempt){if(bindRepository())return;attempt=Number(attempt)||0;if(attempt>=60)return;(window.requestAnimationFrame||function(fn){Promise.resolve().then(fn);})(function(){waitForRepository(attempt+1);});}

window.CleaningCollaborationV21={version:VERSION,applyCommand:applyCommand,handleInboxAction:handleInboxAction,openCounter:openCounter,render:render};
waitForRepository(0);
export const CLEANING_COLLABORATION_VERSION=VERSION;