'use strict';
// ============================================================
// RECIPE SERVERLESS LINK IMPORT v0.503
// One URL import flow -> parsed draft -> review -> RecipeStore.
// Also ensures recipe-detail integration modules are present in the
// actual runtime load graph, because this file is statically loaded by
// index.html before recipes.js.
// ============================================================
(function(){
  var BTN_ID='r-import-link-btn',STYLE_ID='recipe-serverless-link-import-style',loads={};
  var CATS=['Ontbijt','Lunch','Diner','Snack','Dessert','Bakken'];
  var ICONS={Ontbijt:'🥞',Lunch:'🥗',Diner:'🍽️',Snack:'🍿',Dessert:'🍰',Bakken:'🧁'};
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function validUrl(url){try{return /^https?:$/.test(new URL(url).protocol);}catch(e){return false;}}
  function provider(url){try{var h=new URL(url).hostname.toLowerCase();if(h.indexOf('ah.nl')>=0)return'albert-heijn';if(h.indexOf('jumbo.com')>=0||h.indexOf('jumbo.nl')>=0)return'jumbo';return'generic';}catch(e){return'generic';}}
  function titleFromUrl(url){try{var u=new URL(url),p=decodeURIComponent((u.pathname.split('/').filter(Boolean).pop()||u.hostname).replace(/[-_]+/g,' '));return p.replace(/\.[a-z0-9]+$/i,'').trim()||'Geïmporteerd recept';}catch(e){return'Geïmporteerd recept';}}
  function normalize(input,url){input=input||{};var cat=CATS.indexOf(input.cat)>=0?input.cat:'Diner',ings=Array.isArray(input.ingredients)?input.ingredients:[],steps=Array.isArray(input.steps)?input.steps:[];ings=ings.map(function(x){return String(x||'').trim();}).filter(Boolean);steps=steps.map(function(x){return String(x||'').trim();}).filter(Boolean);return{name:String(input.name||'').trim()||titleFromUrl(url),cat:cat,cuisine:String(input.cuisine||'').trim()||'Onbekend',persons:parseInt(input.persons,10)||4,time:parseInt(input.time,10)||30,emoji:input.emoji||ICONS[cat]||'🍴',photo:String(input.photo||'').trim()||null,imageMode:input.photo?'custom':'preset',heroPreset:cat.toLowerCase(),ingredients:ings.length?ings:['Controleer ingrediënten via de bronlink'],steps:steps.length?steps:['Controleer bereidingswijze via de bronlink'],notes:String(input.notes||'').trim(),sourceProvider:provider(url),sourceUrl:url||''};}
  function addStyle(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='.rli-note{font-size:12px;line-height:1.4;color:var(--c-text2,#667085);background:var(--c-surface2,#f3f5f2);border-radius:14px;padding:10px;margin:8px 0 12px}.rli-status{font-size:13px;color:var(--c-text2,#667085);margin-top:10px;min-height:18px}.rli-grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.rli-preview-img{width:100%;height:130px;border-radius:16px;object-fit:cover;background:var(--c-surface2,#f3f5f2);margin:8px 0}.rli-ing-help{font-size:11px;color:var(--c-text2,#777);margin-top:5px}.recipe-import-action{padding:2px 14px 8px!important;display:flex!important;justify-content:flex-start!important}#r-import-link-btn{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:5px!important;width:auto!important;min-height:34px!important;border:1px solid rgba(29,78,216,.14)!important;border-radius:11px!important;padding:6px 10px!important;background:linear-gradient(135deg,#4f8df5,#3567d4)!important;color:#fff!important;font-size:11.5px!important;font-weight:800!important;line-height:1!important;box-shadow:0 3px 8px rgba(29,78,216,.16)!important}';document.head.appendChild(s);}
  function modalOpen(options){if(window.ModalManager&&typeof ModalManager.open==='function')return ModalManager.open(options);if(window.showToast)showToast('Receptvenster kon niet openen');return null;}
  function loadScript(id,src,ready){if(ready&&ready())return Promise.resolve(true);if(loads[id])return loads[id];loads[id]=new Promise(function(resolve){var existing=document.getElementById(id);if(existing){var tries=0,t=setInterval(function(){tries++;if((ready&&ready())||tries>50){clearInterval(t);resolve(!ready||ready());}},50);return;}var s=document.createElement('script');s.id=id;s.src=src;s.async=false;s.onload=function(){resolve(!ready||ready());};s.onerror=function(){resolve(false);};document.body.appendChild(s);});return loads[id];}
  function ensureRecipeIntegrations(){
    return loadScript('recipe-runtime-bottom-sheet','src/core/bottomSheet.js',function(){return !!window.BottomSheet;})
      .then(function(){return loadScript('recipe-runtime-shopping-lists','src/modules/shop/shoppingLists.js',function(){return !!window.ShoppingLists;});})
      .then(function(){return loadScript('recipe-runtime-grocery-parser','src/modules/recipes/recipeGroceryParser.js',function(){return !!window.RecipeGroceryParser;});})
      .then(function(){return loadScript('recipe-runtime-shopping-service','src/modules/shop/shoppingListService.js',function(){return !!window.ShoppingListService;});})
      .then(function(){return loadScript('recipe-runtime-meal-planner','src/modules/meals/mealPlannerBottomSheetBridge.js',function(){return !!window.MealPlannerBottomSheetBridge;});})
      .then(function(){try{if(window.ShoppingLists&&typeof ShoppingLists.boot==='function')ShoppingLists.boot();}catch(e){}try{if(window.MealPlannerBottomSheetBridge&&typeof MealPlannerBottomSheetBridge.boot==='function')MealPlannerBottomSheetBridge.boot();}catch(e){}return true;});
  }
  function importUrl(url,status){if(status)status('Receptdata ophalen...');return fetch('/api/import-recipe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url})}).then(function(r){return r.json().catch(function(){return{};});}).then(function(data){return normalize(data&&data.recipe||{},url);}).catch(function(){return normalize({},url);});}
  function previewHtml(r){var opts=CATS.map(function(c){return '<option '+(r.cat===c?'selected':'')+'>'+c+'</option>';}).join('');return '<div class="rli-note">Controleer alles voordat je opslaat. Elk ingrediënt hieronder wordt één apart afvinkbaar checklist-item.</div>'+(r.photo?'<img class="rli-preview-img" src="'+esc(r.photo)+'" onerror="this.style.display=\'none\'">':'')+'<div class="fam-modal-field"><label>Naam</label><input id="rli-name" value="'+esc(r.name)+'"></div><div class="rli-grid2"><div class="fam-modal-field"><label>Maaltijdtype</label><select id="rli-cat">'+opts+'</select></div><div class="fam-modal-field"><label>Keuken</label><input id="rli-cuisine" value="'+esc(r.cuisine)+'"></div></div><div class="rli-grid2"><div class="fam-modal-field"><label>Personen</label><input id="rli-persons" type="number" value="'+esc(r.persons)+'"></div><div class="fam-modal-field"><label>Tijd min</label><input id="rli-time" type="number" value="'+esc(r.time)+'"></div></div><div class="fam-modal-field"><label>Bronfoto (optioneel)</label><input id="rli-photo" value="'+esc(r.photo||'')+'"><div class="rli-ing-help">Leeg = FamilyApp Hero voor dit maaltijdtype.</div></div><div class="fam-modal-field"><label>Ingrediënten · 1 per regel</label><textarea id="rli-ingredients" rows="7">'+esc((r.ingredients||[]).join('\n'))+'</textarea></div><div class="fam-modal-field"><label>Stappen · 1 per regel</label><textarea id="rli-steps" rows="6">'+esc((r.steps||[]).join('\n'))+'</textarea></div><div class="fam-modal-field"><label>Notities</label><textarea id="rli-notes" rows="2">'+esc(r.notes||'')+'</textarea></div>';}
  function readPreview(m,original){var cat=m.querySelector('#rli-cat').value||'Diner',photo=(m.querySelector('#rli-photo').value||'').trim();return{name:(m.querySelector('#rli-name').value||'').trim(),cat:cat,cuisine:(m.querySelector('#rli-cuisine').value||'').trim(),persons:parseInt(m.querySelector('#rli-persons').value,10)||4,time:parseInt(m.querySelector('#rli-time').value,10)||30,emoji:ICONS[cat]||'🍴',photo:photo||null,imageMode:photo?'custom':'preset',heroPreset:cat.toLowerCase(),ingredients:(m.querySelector('#rli-ingredients').value||'').split('\n').map(function(x){return x.trim();}).filter(Boolean),steps:(m.querySelector('#rli-steps').value||'').split('\n').map(function(x){return x.trim();}).filter(Boolean),notes:m.querySelector('#rli-notes').value||'',sourceProvider:original.sourceProvider||'generic',sourceUrl:original.sourceUrl||''};}
  function openPreview(recipe){return modalOpen({title:'✅ Controleer recept',html:previewHtml(recipe),actions:[{label:'Annuleren'},{label:'Opslaan',primary:true,keepOpen:true,onClick:function(ctx){var draft=readPreview(ctx.modal,recipe);if(!draft.name||!draft.ingredients.length){if(window.showToast)showToast('Naam en ingrediënten zijn verplicht');return false;}if(!window.RecipeStore||typeof RecipeStore.create!=='function'){if(window.showToast)showToast('Receptopslag niet beschikbaar');return false;}var btn=ctx.modal.querySelector('.fam-modal-primary');if(btn)btn.disabled=true;RecipeStore.create(draft).then(function(res){var saved=res.recipe||draft;if(window.awardXP)awardXP(5,'Recept geïmporteerd');if(window.showToast)showToast('Recept geïmporteerd ✓');ctx.close();if(window.renderRecipes)renderRecipes();setTimeout(function(){if(window.openRecipeDetail)openRecipeDetail(saved.id);},80);}).catch(function(err){if(btn)btn.disabled=false;if(window.showToast)showToast(err&&err.message||'Opslaan mislukt');});return false;}}]});}
  function openImportSheet(){addStyle();return modalOpen({title:'🔗 Recept via link',html:'<div class="rli-note">Plak één receptenlink. FamilyApp leest de receptdata, daarna krijg je altijd eerst een controle-preview.</div><div class="fam-modal-field"><label>Receptlink</label><input id="rli-url" placeholder="https://..." inputmode="url"></div><div class="rli-status" id="rli-status"></div>',actions:[{label:'Annuleren'},{label:'Importeren',primary:true,keepOpen:true,onClick:function(ctx){var input=ctx.modal.querySelector('#rli-url'),status=ctx.modal.querySelector('#rli-status'),url=input?input.value.trim():'';if(!validUrl(url)){status.textContent='Plak een geldige http(s) link.';return false;}var btn=ctx.modal.querySelector('.fam-modal-primary');if(btn)btn.disabled=true;importUrl(url,function(v){status.textContent=v;}).then(function(recipe){if(btn)btn.disabled=false;ctx.close();setTimeout(function(){openPreview(recipe);},230);});return false;}}]});}
  function patch(){addStyle();var btn=document.getElementById(BTN_ID);if(!btn)return false;btn.onclick=function(ev){if(ev)ev.preventDefault();openImportSheet();};return true;}
  function boot(){addStyle();ensureRecipeIntegrations();patch();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
  window.RecipeServerlessLinkImport={version:'0.503',boot:boot,open:openImportSheet,ensureIntegrations:ensureRecipeIntegrations};
})();
