'use strict';
// RECIPE MANAGE & IMAGE BRIDGE v1.0 - UI facade only; RecipeStore owns writes.
(function(){
  if(window.RecipeManageAndImageBridge&&window.RecipeManageAndImageBridge.version==='1.0.0')return;
  var VERSION='1.0.0',STYLE_ID='recipe-manage-image-style';
  var PREMIUM_FALLBACKS=[
    'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=1200&q=85',
    'https://images.unsplash.com/photo-1498579397066-22750a3cb424?auto=format&fit=crop&w=1200&q=85',
    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=85',
    'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=85'
  ];
  function store(){return window.RecipeStore||null;}function toast(m){if(typeof window.showToast==='function')window.showToast(m);}function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function recipe(id){var s=store();return s&&s.get?s.get(id):null;}function current(){return recipe(window.currentRecipeId);}function pickFallback(r){var key=String(r&&r.name||'').length+String(r&&r.id||'').length;return PREMIUM_FALLBACKS[Math.abs(key)%PREMIUM_FALLBACKS.length];}
  function ensureStyles(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='.recipe-manage-row{display:flex;gap:9px;padding:0 16px 14px}.recipe-manage-btn{border:0;border-radius:999px;padding:10px 13px;font-size:12px;font-weight:950;background:var(--c-surface2,#f4f7f2);color:var(--c-text,#111827)}.recipe-manage-btn.primary{background:var(--c-primary,#3f7f2f);color:#fff}.recipe-manage-btn.danger{background:#fff1f1;color:#c23333}.recipe-photo-preview{width:100%;height:155px;border-radius:20px;background-size:cover;background-position:center;background-color:var(--c-surface2,#f4f7f2);border:1px solid var(--c-border,#edf0ec);margin-bottom:12px}';document.head.appendChild(s);}
  function render(){if(typeof window.renderRecipes==='function')window.renderRecipes();setTimeout(installDetailActions,80);}
  function openEditSheet(id){var r=recipe(id);if(!r)return;if(window.RecipeEditorPopup&&typeof RecipeEditorPopup.open==='function')return RecipeEditorPopup.open(r.id);if(typeof window.openRecipeEditor==='function')return window.openRecipeEditor(r.id);toast('Recept-editor is niet beschikbaar');}
  function openPhotoSheet(id){var r=recipe(id),s=store();if(!r||!s||!window.BottomSheet)return;var currentPhoto=r.photo||pickFallback(r);BottomSheet.open({title:'🖼️ Receptfoto',html:'<div id="recipe-photo-preview-manage" class="recipe-photo-preview" style="background-image:url(\''+esc(currentPhoto)+'\')"></div><div class="fam-modal-field"><label>Foto URL</label><input id="recipe-photo-manage-url" value="'+esc(currentPhoto)+'"></div>',actions:[{label:'Annuleren'},{label:'Opslaan',primary:true,keepOpen:true,onClick:function(ctx){var url=((ctx.modal.querySelector('#recipe-photo-manage-url')||{}).value||'').trim()||pickFallback(r);s.upsert(Object.assign({},r,{photo:url,imageMode:'custom'})).then(function(saved){ctx.close();toast('Foto opgeslagen ✓');render();if(typeof window.openRecipeDetail==='function')setTimeout(function(){window.openRecipeDetail(saved.recipe.id);},100);}).catch(function(e){toast(e&&e.code==='RECIPE_CONTEXT_CHANGED'?'Receptcontext gewijzigd':(e.message||'Foto opslaan mislukt'));});return false;}}]});}
  function deleteRecipe(id){var r=recipe(id),s=store();if(!r||!s)return Promise.resolve(false);if(!confirm('Recept "'+r.name+'" verwijderen?'))return Promise.resolve(false);return s.remove(r.id).then(function(result){if(result&&result.removed){toast('Recept verwijderd');if(typeof window.showRecipeListView==='function')window.showRecipeListView();render();return true;}return false;}).catch(function(e){toast(e&&e.code==='RECIPE_CONTEXT_CHANGED'?'Receptcontext gewijzigd':(e.message||'Verwijderen mislukt'));return false;});}
  function applyFallbacks(){var s=store();if(!s||!s.list)return Promise.resolve(0);var rows=s.list(),jobs=[];rows.forEach(function(r){if(!r.photo)jobs.push(s.upsert(Object.assign({},r,{photo:pickFallback(r),photoFallback:true,photoFallbackVersion:VERSION,imageMode:'preset'})));});return Promise.all(jobs).then(function(){return jobs.length;});}
  function installDetailActions(){ensureStyles();var r=current(),content=document.getElementById('recipe-detail-content');if(!r||!content||document.getElementById('recipe-manage-row'))return;var title=content.querySelector('.recipe-title-area')||content.firstElementChild,row=document.createElement('div');row.id='recipe-manage-row';row.className='recipe-manage-row';row.innerHTML='<button class="recipe-manage-btn primary" id="recipe-manage-edit">✏️ Bewerken</button><button class="recipe-manage-btn" id="recipe-manage-photo">🖼️ Foto</button><button class="recipe-manage-btn danger" id="recipe-manage-delete">🗑️ Verwijderen</button>';if(title&&title.parentNode)title.parentNode.insertBefore(row,title.nextSibling);else content.insertBefore(row,content.firstChild);document.getElementById('recipe-manage-edit').onclick=function(){openEditSheet(r.id);};document.getElementById('recipe-manage-photo').onclick=function(){openPhotoSheet(r.id);};document.getElementById('recipe-manage-delete').onclick=function(){deleteRecipe(r.id);};}
  function wrapDetail(){if(typeof window.openRecipeDetail!=='function'||window.openRecipeDetail.__manageImageWrapped)return;var original=window.openRecipeDetail;window.openRecipeDetail=function(id){var result=original.apply(this,arguments);window.currentRecipeId=id;setTimeout(installDetailActions,80);return result;};window.openRecipeDetail.__manageImageWrapped=true;}
  function boot(){ensureStyles();wrapDetail();installDetailActions();setTimeout(function(){wrapDetail();installDetailActions();},500);}
  window.RecipeManageAndImageBridge={version:VERSION,boot:boot,openEditSheet:openEditSheet,openPhotoSheet:openPhotoSheet,deleteRecipe:deleteRecipe,applyFallbacks:applyFallbacks,fallbackImages:PREMIUM_FALLBACKS};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
