'use strict';
// ============================================================
// RECIPE SERVERLESS LINK IMPORT v0.500
// One URL import flow -> parsed draft -> review -> RecipeStore.
// ============================================================
(function(){
  var BTN_ID='r-import-link-btn',STYLE_ID='recipe-serverless-link-import-style';
  var CATS=['Ontbijt','Lunch','Diner','Snack','Dessert','Bakken'];
  var ICONS={Ontbijt:'🥞',Lunch:'🥗',Diner:'🍽️',Snack:'🍿',Dessert:'🍰',Bakken:'🧁'};
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function validUrl(url){try{return /^https?:$/.test(new URL(url).protocol);}catch(e){return false;}}
  function provider(url){try{var h=new URL(url).hostname.toLowerCase();if(h.indexOf('ah.nl')>=0)return'albert-heijn';if(h.indexOf('jumbo.com')>=0||h.indexOf('jumbo.nl')>=0)return'jumbo';return'generic';}catch(e){return'generic';}}
  function titleFromUrl(url){try{var u=new URL(url),p=decodeURIComponent((u.pathname.split('/').filter(Boolean).pop()||u.hostname).replace(/[-_]+/g,' '));return p.replace(/\.[a-z0-9]+$/i,'').trim()||'Geïmporteerd recept';}catch(e){return'Geïmporteerd recept';}}
  function normalize(input,url){input=input||{};var cat=CATS.indexOf(input.cat)>=0?input.cat:'Diner',ings=Array.isArray(input.ingredients)?input.ingredients:[],steps=Array.isArray(input.steps)?input.steps:[];ings=ings.map(function(x){return String(x||'').trim();}).filter(Boolean);steps=steps.map(function(x){return String(x||'').trim();}).filter(Boolean);return{name:String(input.name||'').trim()||titleFromUrl(url),cat:cat,cuisine:String(input.cuisine||'').trim()||'Onbekend',persons:parseInt(input.persons,10)||4,time:parseInt(input.time,10)||30,emoji:input.emoji||ICONS[cat]||'🍴',photo:String(input.photo||'').trim()||null,imageMode:input.photo?'custom':'preset',heroPreset:cat.toLowerCase(),ingredients:ings.length?ings:['Controleer ingrediënten via de bronlink'],steps:steps.length?steps:['Controleer bereidingswijze via de bronlink'],notes:String(input.notes||'').trim(),sourceProvider:provider(url),sourceUrl:url||''};}
  function addStyle(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='.rli-note{font-size:12px;line-height:1.4;color:var(--c-text2,#667085);background:var(--c-surface2,#f3f5f2);border-radius:14px;padding:10px;margin:8px 0 12px}.rli-status{font-size:13px;color:var(--c-text2,#667085);margin-top:10px;min-height:18px}.rli-grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.rli-preview-img{width:100%;height:130px;border-radius:16px;object-fit:cover;background:var(--c-surface2,#f3f5f2);margin:8px 0}.rli-ing-help{font-size:11px;color:var(--c-text2,#777);margin-top:5px}';document.head.appendChild(s);}
  function importUrl(url,status){if(status)status('Receptdata ophalen...');return fetch('/api/import-recipe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url})}).then(function(r){return r.json().catch(function(){return{};});}).then(function(data){return normalize(data&&data.recipe||{},url);}).catch(function(){return normalize({},url);});}
  function previewHtml(r){var opts=CATS.map(function(c){return '<option '+(r.cat===c?'selected':'')+'>'+c+'</option>';}).join('');return '<div class="rli-note">Controleer alles voordat je opslaat. Elk ingrediënt hieronder wordt één apart afvinkbaar checklist-item.</div>'+(r.photo?'<img class="rli-preview-img" src="'+esc(r.photo)+'" onerror="this.style.display=\'none\'">':'')+'<div class="fam-modal-field"><label>Naam</label><input id="rli-name" value="'+esc(r.name)+'"></div><div class="rli-grid2"><div class="fam-modal-field"><label>Maaltijdtype</label><select id="rli-cat">'+opts+'</select></div><div class="fam-modal-field"><label>Keuken</label><input id="rli-cuisine" value="'+esc(r.cuisine)+'"></div></div><div class="rli-grid2"><div class="fam-modal-field"><label>Personen</label><input id="rli-persons" type="number" value="'+esc(r.persons)+'"></div><div class="fam-modal-field"><label>Tijd min</label><input id="rli-time" type="number" value="'+esc(r.time)+'"></div></div><div class="fam-modal-field"><label>Bronfoto (optioneel)</label><input id="rli-photo" value="'+esc(r.photo||'')+'"><div class="rli-ing-help">Leeg = FamilyApp Hero voor dit maaltijdtype.</div></div><div class="fam-modal-field"><label>Ingrediënten · 1 per regel</label><textarea id="rli-ingredients" rows="7">'+esc((r.ingredients||[]).join('\n'))+'</textarea></div><div class="fam-modal-field"><label>Stappen · 1 per regel</label><textarea id="rli-steps" rows="6">'+esc((r.steps||[]).join('\n'))+'</textarea></div><div class="fam-modal-field"><label>Notities</label><textarea id="rli-notes" rows="2">'+esc(r.notes||'')+'</textarea></div>';}
  function readPreview(m,original){var cat=m.querySelector('#rli-cat').value||'Diner',photo=(m.querySelector('#rli-photo').value||'').trim();return{name:(m.querySelector('#rli-name').value||'').trim(),cat:cat,cuisine:(m.querySelector('#rli-cuisine').value||'').trim(),persons:parseInt(m.querySelector('#rli-persons').value,10)||4,time:parseInt(m.querySelector('#rli-time').value,10)||30,emoji:ICONS[cat]||'🍴',photo:photo||null,imageMode:photo?'custom':'preset',heroPreset:cat.toLowerCase(),ingredients:(m.querySelector('#rli-ingredients').value||'').split('\n').map(function(x){return x.trim();}).filter(Boolean),steps:(m.querySelector('#rli-steps').value||'').split('\n').map(function(x){return x.trim();}).filter(Boolean),notes:m.querySelector('#rli-notes').value||'',sourceProvider:original.sourceProvider||'generic',sourceUrl:original.sourceUrl||''};}
  function openPreview(recipe){if(!window.BottomSheet)return;BottomSheet.open({title:'✅ Controleer recept',html:previewHtml(recipe),actions:[{label:'Annuleren'},{label:'Opslaan',primary:true,onClick:function(ctx){var draft=readPreview(ctx.modal,recipe);if(!draft.name||!draft.ingredients.length){if(window.showToast)showToast('Naam en ingrediënten zijn verplicht');return false;}if(!window.RecipeStore||typeof RecipeStore.create!=='function'){if(window.showToast)showToast('Receptopslag niet beschikbaar');return false;}RecipeStore.create(draft).then(function(res){var saved=res.recipe||draft;if(window.awardXP)awardXP(5,'Recept geïmporteerd');if(window.showToast)showToast('Recept geïmporteerd ✓');if(window.renderRecipes)renderRecipes();setTimeout(function(){if(window.openRecipeDetail)openRecipeDetail(saved.id);},80);}).catch(function(){if(window.showToast)showToast('Opslaan mislukt');});return true;}}]});}
  function openImportSheet(){addStyle();if(!window.BottomSheet)return;BottomSheet.open({title:'🔗 Recept via link',html:'<div class="rli-note">Plak één receptenlink. FamilyApp leest de receptdata, daarna krijg je altijd eerst een controle-preview.</div><div class="fam-modal-field"><label>Receptlink</label><input id="rli-url" placeholder="https://..." inputmode="url"></div><div class="rli-status" id="rli-status"></div>',actions:[{label:'Annuleren'},{label:'Importeren',primary:true,keepOpen:true,onClick:function(ctx){var input=ctx.modal.querySelector('#rli-url'),status=ctx.modal.querySelector('#rli-status'),url=input?input.value.trim():'';if(!validUrl(url)){status.textContent='Plak een geldige http(s) link.';return false;}importUrl(url,function(v){status.textContent=v;}).then(function(recipe){ctx.close();setTimeout(function(){openPreview(recipe);},220);});return false;}}]});}
  function patch(){addStyle();var btn=document.getElementById(BTN_ID);if(!btn)return false;btn.onclick=openImportSheet;btn.textContent='🔗 Importeren';btn.title='Recept importeren via link';return true;}
  function boot(){patch();var screen=document.getElementById('screen-recipes');if(screen&&!screen.__serverlessRecipeImport){screen.__serverlessRecipeImport=true;new MutationObserver(patch).observe(screen,{childList:true,subtree:true});}}
  var n=0,t=setInterval(function(){n++;boot();if(patch()||n>40)clearInterval(t);},150);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();window.RecipeServerlessLinkImport={version:'0.500',boot:boot,open:openImportSheet};
})();
