'use strict';
(function(){
  var BTN_ID='r-import-link-btn', STYLE_ID='recipe-link-import-style';
  var CATS=['Ontbijt','Lunch','Diner','Snack','Dessert','Bakken'];
  var ICONS={Ontbijt:'🥞',Lunch:'🥗',Diner:'🍽️',Snack:'🍿',Dessert:'🍰',Bakken:'🧁'};
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function validUrl(url){try{var u=new URL(url);return /^https?:$/.test(u.protocol);}catch(e){return false;}}
  function provider(url){try{var h=new URL(url).hostname.toLowerCase();if(h.indexOf('ah.nl')>=0)return'albert-heijn';if(h.indexOf('jumbo.com')>=0)return'jumbo';return'generic';}catch(e){return'generic';}}
  function titleFromUrl(url){try{var u=new URL(url),p=decodeURIComponent((u.pathname.split('/').filter(Boolean).pop()||u.hostname).replace(/[-_]+/g,' '));return p.replace(/\.[a-z0-9]+$/i,'').trim()||'Geïmporteerd recept';}catch(e){return'Geïmporteerd recept';}}
  function cleanJsonText(text){text=String(text||'').replace(/```json|```/gi,'').trim();var a=text.indexOf('{'),b=text.lastIndexOf('}');return a>=0&&b>a?text.slice(a,b+1):text;}
  function normalize(input,url){input=input||{};var cat=CATS.indexOf(input.cat)>=0?input.cat:'Diner';return{name:String(input.name||titleFromUrl(url)).trim(),cat:cat,cuisine:String(input.cuisine||'').trim()||'Onbekend',persons:parseInt(input.persons,10)||4,time:parseInt(input.time,10)||30,emoji:input.emoji||ICONS[cat]||'🍴',photo:String(input.photo||'').trim()||null,imageMode:input.photo?'source':'preset',heroPreset:cat.toLowerCase(),ingredients:(Array.isArray(input.ingredients)?input.ingredients:[]).map(function(x){return String(x||'').trim();}).filter(Boolean),steps:(Array.isArray(input.steps)?input.steps:[]).map(function(x){return String(x||'').trim();}).filter(Boolean),notes:String(input.notes||'').trim(),sourceProvider:provider(url),sourceUrl:url};}
  function fallback(url){return normalize({name:titleFromUrl(url),cat:'Diner',ingredients:['Controleer ingrediënten via de bronlink'],steps:['Controleer de bereidingswijze via de bronlink'],notes:'Import kon niet volledig worden verwerkt; controleer dit recept handmatig.'},url);}
  function prompt(url){return['Maak van deze receptenlink een gestructureerd Nederlands recept voor FamilyApp.','URL: '+url,'Geef alleen geldige JSON terug met: name, cat, cuisine, persons, time, photo, ingredients, steps, notes.','cat is één van: Ontbijt, Lunch, Diner, Snack, Dessert, Bakken.','Elke ingrediëntregel moet één afzonderlijk ingrediënt bevatten inclusief hoeveelheid en eenheid waar beschikbaar.','Splits nooit meerdere ingrediënten samen op één regel.'].join('\n');}
  function importRecipe(url,status){if(typeof window.callGemini!=='function')return Promise.resolve(fallback(url));if(status)status('Link wordt geanalyseerd...');return window.callGemini(prompt(url),null,1800).then(function(text){return normalize(JSON.parse(cleanJsonText(text)),url);}).catch(function(){return fallback(url);});}
  function style(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='#'+BTN_ID+'{background:linear-gradient(135deg,#262c56,#5b5ce2);color:#fff;border:0;border-radius:99px;padding:9px 14px;font-size:13px;font-weight:900;cursor:pointer;margin-left:8px}.rli-note{font-size:12px;line-height:1.45;color:var(--c-text2,#667085);background:var(--c-surface2,#f3f5f2);border-radius:14px;padding:10px;margin:8px 0 12px}.rli-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.rli-preview{width:100%;height:130px;object-fit:cover;border-radius:16px;background:var(--c-surface2,#f3f5f2)}';document.head.appendChild(s);}
  function previewHtml(r){var opts=CATS.map(function(c){return'<option '+(r.cat===c?'selected':'')+'>'+c+'</option>';}).join('');return'<div class="rli-note">Controleer alles vóór opslaan. Elke regel onder Ingrediënten wordt een apart afvinkbaar checklist-item.</div>'+(r.photo?'<img class="rli-preview" src="'+esc(r.photo)+'" onerror="this.style.display=\'none\'">':'')+'<div class="fam-modal-field"><label>Naam</label><input id="rli-name" value="'+esc(r.name)+'"></div><div class="rli-grid"><div class="fam-modal-field"><label>Maaltijdtype</label><select id="rli-cat">'+opts+'</select></div><div class="fam-modal-field"><label>Keuken</label><input id="rli-cuisine" value="'+esc(r.cuisine)+'"></div></div><div class="rli-grid"><div class="fam-modal-field"><label>Personen</label><input id="rli-persons" type="number" value="'+esc(r.persons)+'"></div><div class="fam-modal-field"><label>Tijd (min)</label><input id="rli-time" type="number" value="'+esc(r.time)+'"></div></div><div class="fam-modal-field"><label>Ingrediënten — één per regel</label><textarea id="rli-ingredients" rows="7">'+esc((r.ingredients||[]).join('\n'))+'</textarea></div><div class="fam-modal-field"><label>Bereidingsstappen — één per regel</label><textarea id="rli-steps" rows="6">'+esc((r.steps||[]).join('\n'))+'</textarea></div><div class="fam-modal-field"><label>Notities</label><textarea id="rli-notes" rows="2">'+esc(r.notes||'')+'</textarea></div>';
  }
  function read(modal,original){var cat=modal.querySelector('#rli-cat').value||'Diner';return normalize({name:modal.querySelector('#rli-name').value,cat:cat,cuisine:modal.querySelector('#rli-cuisine').value,persons:modal.querySelector('#rli-persons').value,time:modal.querySelector('#rli-time').value,photo:original.photo,ingredients:modal.querySelector('#rli-ingredients').value.split('\n'),steps:modal.querySelector('#rli-steps').value.split('\n'),notes:modal.querySelector('#rli-notes').value,emoji:ICONS[cat]},original.sourceUrl);}
  function save(recipe){if(!window.RecipeStore||typeof window.RecipeStore.create!=='function')return Promise.reject(new Error('RecipeStore is nog niet gereed'));return window.RecipeStore.create(recipe).then(function(result){try{if(typeof window.awardXP==='function')window.awardXP(5,'Recept geïmporteerd');}catch(e){}if(typeof window.showToast==='function')window.showToast('Recept geïmporteerd ✓');return result.recipe;});}
  function openPreview(recipe){if(!window.BottomSheet)return;window.BottomSheet.open({title:'Controleer recept',html:previewHtml(recipe),actions:[{label:'Annuleren'},{label:'Opslaan',primary:true,keepOpen:true,onClick:function(ctx){var r=read(ctx.modal,recipe);if(!r.name||!r.ingredients.length){if(window.showToast)window.showToast('Naam en ingrediënten zijn verplicht');return false;}save(r).then(function(saved){ctx.close();setTimeout(function(){if(typeof window.renderRecipes==='function')window.renderRecipes();if(typeof window.openRecipeDetail==='function')window.openRecipeDetail(saved.id);},80);}).catch(function(err){if(window.showToast)window.showToast(err.message||'Opslaan mislukt');});return false;}}]});}
  function open(){if(!window.BottomSheet)return;window.BottomSheet.open({title:'🔗 Recept importeren',html:'<div class="rli-note">Plak één receptenlink. Je ziet altijd eerst een controle-preview voordat iets wordt opgeslagen.</div><div class="fam-modal-field"><label>Receptlink</label><input id="rli-url" placeholder="https://..." inputmode="url"></div><div id="rli-status" class="rli-note" style="display:none"></div>',actions:[{label:'Annuleren'},{label:'Importeren',primary:true,keepOpen:true,onClick:function(ctx){var input=ctx.modal.querySelector('#rli-url'),box=ctx.modal.querySelector('#rli-status'),url=input?input.value.trim():'';if(!validUrl(url)){box.style.display='block';box.textContent='Plak een geldige http(s)-link.';return false;}box.style.display='block';box.textContent='Bezig met analyseren...';importRecipe(url,function(m){box.textContent=m;}).then(function(r){ctx.close();setTimeout(function(){openPreview(r);},220);}).catch(function(e){box.textContent=e.message||'Importeren mislukt';});return false;}}]});}
  function inject(){style();var add=document.getElementById('r-addbtn');if(!add||document.getElementById(BTN_ID))return;var b=document.createElement('button');b.id=BTN_ID;b.type='button';b.textContent='🔗 Importeren';b.onclick=open;add.insertAdjacentElement('afterend',b);}
  function boot(){inject();var screen=document.getElementById('screen-recipes');if(screen&&!screen.__recipeLinkImportObserver){screen.__recipeLinkImportObserver=true;new MutationObserver(inject).observe(screen,{childList:true,subtree:true});}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
  window.RecipeLinkImport={boot:boot,open:open};
})();
