'use strict';
const fs=require('fs');const assert=require('assert');
const activity=fs.readFileSync('src/platform/activity/householdActivity.js','utf8');
const producers=fs.readFileSync('src/platform/activity/activityDomainProducers.js','utf8');
const feed=fs.readFileSync('src/modules/feed/feedActivityPresentation.js','utf8');
const loader=fs.readFileSync('api/app.js','utf8');
assert(activity.includes("COLLECTION='activity'"),'ActivityService must use canonical shared/activity collection');
assert(activity.includes('HouseholdContext'),'ActivityService must use HouseholdContext');
assert(activity.includes('ACTIVITY_CONTEXT_CHANGED'),'ActivityService must reject stale context');
assert(activity.includes('idempotencyKey'),'ActivityService must require deterministic idempotency');
assert(activity.includes('entityType')&&activity.includes('entityId'),'Activity events need canonical entity references');
assert(!activity.includes('window.fbFamilyId'),'ActivityService must not resolve household from fbFamilyId');
assert(!activity.includes('window.fbUser'),'ActivityService must not resolve actor from fbUser');
assert(producers.includes("type:'task.created'")&&producers.includes("type:'task.completed'"),'Tasks must produce activity events');
assert(producers.includes("type:'meal.planned'"),'Meals must produce activity events');
assert(producers.includes("type:'grocery.receipt_uploaded'"),'Shopping receipt must produce activity event');
assert(!producers.includes('amount:'),'Receipt activity producer must not publish amount');
assert(!producers.includes('total:'),'Receipt activity producer must not publish total');
assert(feed.includes('HouseholdActivity')||feed.includes('ActivityService'),'Feed must consume activity service rather than produce events');
assert(!feed.includes('.publish('),'Feed presentation must not publish activity events');
const serviceIndex=loader.indexOf('src/platform/activity/householdActivity.js');
const producerIndex=loader.indexOf('src/platform/activity/activityDomainProducers.js');
const feedIndex=loader.indexOf('src/modules/feed/feedActivityPresentation.js');
assert(serviceIndex>=0&&producerIndex>serviceIndex&&feedIndex>producerIndex,'Loader order must be ActivityService -> producers -> Feed presentation');
console.log('activity-context-adoption: ok');
