'use strict';
const fs=require('fs'),assert=require('assert');
const store=fs.readFileSync('src/modules/feed/feedSharedData.js','utf8');
const presentation=fs.readFileSync('src/modules/feed/feedActivityPresentation.js','utf8');
assert.ok(store.includes("COLLECTION='feed'"),'feed must use canonical shared/feed collection');
assert.ok(store.includes('HouseholdContext'),'feed must use HouseholdContext');
assert.ok(store.includes('FEED_CONTEXT_CHANGED'),'feed must expose stale-context error');
assert.ok(store.includes("familyapp:household-context-changed"),'feed must rebind on household context changes');
assert.ok(store.includes("familyapp:session:cleared"),'feed must stop on session clear');
assert.ok(store.includes('stop:stop')&&store.includes('rebind:rebind'),'feed API must expose stop/rebind');
assert.ok(!store.includes('window.fbFamilyId'),'feed store must not use fbFamilyId as identity authority');
assert.ok(!store.includes('window.fbUser'),'feed store must not use fbUser as identity authority');
assert.ok(store.includes("LEGACY_RECORD_COLLECTION='feedPosts'"),'feedPosts may only remain as migration source');
assert.ok(store.includes('authorUid:token.uid'),'new posts must be UID-authored');
assert.ok(store.includes("'likes',token.uid"),'likes must be keyed by UID');
assert.ok(store.includes('authorUid:token.uid'),'comments must retain actor UID');
assert.ok(presentation.includes('HouseholdActivity.getEvents')||presentation.includes('ActivityService'),'Feed presentation must consume central activity events');
assert.ok(!presentation.includes('writeSharedRecord'),'Feed activity presentation must not write domain events');
console.log('feed context adoption OK');
