'use strict';
const fs=require('fs');const assert=require('assert');
const avatarBridge=fs.readFileSync('src/core/avatarIdentityBridge.js','utf8');
const avatarStore=fs.readFileSync('src/modules/profile/avatarStore.js','utf8');
const profileBridge=fs.readFileSync('src/modules/profile/profileRuntimeContextBridge.js','utf8');
const loader=fs.readFileSync('api/app.js','utf8');
const retirement=fs.readFileSync('src/core/legacyAuthorityRetirement.js','utf8');
assert(!/\bShane\b|\bEsra\b/.test(avatarBridge),'avatar bridge must not encode named identities');
assert(!/localStorage/.test(avatarBridge),'avatar bridge must not use localStorage identity authority');
assert(!/firebase\.database|fbFamilyId|fbUser/.test(avatarBridge),'avatar bridge must not read/write Firebase identity directly');
assert(avatarStore.includes('ProfileContextService.updateAvatar'),'avatar writes must use ProfileContextService');
assert(avatarStore.includes('familyapp-profile-v2:'),'avatar preference key must be UID scoped');
assert(!/\bShane\b|\bEsra\b/.test(avatarStore),'avatar store must not hardcode household names');
assert(profileBridge.includes('stopImmediatePropagation'),'profile save must block legacy localStorage handler');
assert(profileBridge.includes('ProfileContextService')||profileBridge.includes('window.ProfileContextService'),'profile save must use canonical service');
assert(retirement.includes('__legacyAuthorityRetired'),'retirement guard must mark legacy roots disabled');
assert(loader.includes('legacyAuthorityRetirement.js?v=1'),'retirement guard must load in runtime');
assert(!loader.includes('legacyXpOverwriteGuard.js'),'obsolete XP overwrite guard must not load');
assert(!fs.existsSync('src/core/legacyXpOverwriteGuard.js'),'obsolete XP overwrite guard source must be removed');
console.log('legacy cleanup adoption: ok');
