const fs=require('fs'),assert=require('assert');
const store=fs.readFileSync('src/core/notificationStore.js','utf8');
const events=fs.readFileSync('src/core/notificationEvents.js','utf8');
const actions=fs.readFileSync('src/core/notificationActions.js','utf8');
assert(store.includes("version:'2.0.0'")||store.includes("VERSION='2.0.0'"));
assert(store.includes('HouseholdContext'));
assert(store.includes('NOTIFICATION_CONTEXT_CHANGED'));
assert(store.includes("'partyQuest.invitation.sent':true"));
assert(store.includes("householdId:t.householdId"));
assert(store.includes("familyapp:household-context-changed"));
assert(store.includes("familyapp:session:cleared"));
assert(!store.includes('window.fbFamilyId'));
assert(!store.includes('window.fbUser'));
assert(events.includes('HouseholdContext'));
assert(!events.includes('window.fbUser'));
assert(actions.includes('NOTIFICATION_CONTEXT_CHANGED'));
assert(actions.includes('event.householdId'));
assert(actions.includes('HouseholdContext.isCurrent'));
console.log('notification context adoption ok');
