const fs=require('fs');const vm=require('vm');const assert=require('assert');
const source=fs.readFileSync('src/core/progressionEngine.js','utf8');
let ctx={uid:'alpha-user',householdId:'alpha-household'};const listeners={};let subscriptions=[];
const db={
 'alpha-user':{current:{schemaVersion:2,uid:'alpha-user',totalXp:0,level:1,skills:{vacuum:{xp:0,log:[]}},stats:{},streak:{current:0,best:0,lastActiveDate:null},achievements:{},events:{}}},
 'beta-user':{current:{schemaVersion:2,uid:'beta-user',totalXp:0,level:1,skills:{vacuum:{xp:0,log:[]}},stats:{},streak:{current:0,best:0,lastActiveDate:null},achievements:{},events:{}}}
};
const hc={requireUser:()=>ctx.uid,requireHousehold:()=>ctx.householdId,assertContext:t=>{if(!t||t.uid!==ctx.uid||t.householdId!==ctx.householdId){const e=new Error('changed');e.code='PROGRESSION_CONTEXT_CHANGED';throw e;}},isCurrent:t=>!!t&&t.uid===ctx.uid&&t.householdId===ctx.householdId,current:()=>Object.assign({},ctx)};
const fds={readPrivate:()=>Promise.resolve(JSON.parse(JSON.stringify(db[ctx.uid]||{}))),writePrivateRecord:(c,id,v)=>{db[ctx.uid]=db[ctx.uid]||{};db[ctx.uid][id]=JSON.parse(JSON.stringify(v));return Promise.resolve({value:v});},subscribePrivate:(c,cb)=>{const token=ctx.uid;const row={token,cb};subscriptions.push(row);Promise.resolve().then(()=>cb(JSON.parse(JSON.stringify(db[token]||{})),{source:'test'}));return()=>{subscriptions=subscriptions.filter(x=>x!==row);};}};
const sandbox={console,setTimeout,clearTimeout,Promise,Date,Math,CustomEvent:function(n,o){this.type=n;this.detail=o&&o.detail;},document:{readyState:'complete',addEventListener:()=>{}},window:{SKILL_DEFS:[{id:'vacuum',xpPerDo:12}],skillLevelFromXp:xp=>1,HouseholdContext:hc,FamilyDataStore:fds,addEventListener:(n,f)=>{(listeners[n]||(listeners[n]=[])).push(f);},dispatchEvent:()=>{}}};sandbox.window.window=sandbox.window;sandbox.window.document=sandbox.document;sandbox.window.CustomEvent=sandbox.CustomEvent;
vm.createContext(sandbox);vm.runInContext(source,sandbox);const e=sandbox.window.FamilyProgression;
(async()=>{await e.load();assert.strictEqual(e.status().context.uid,'alpha-user');let r=e.awardXp(10,{eventId:'task:1',type:'task',source:'test'});assert.strictEqual(r.totalXp,10);r=e.awardXp(10,{eventId:'task:1',type:'task',source:'test'});assert.ok(r.duplicate,'duplicate XP event should be ignored');let s=e.awardSkill('vacuum',12,{eventId:'task:1:skill',source:'test'});assert.strictEqual(s.xp,12);s=e.awardSkill('vacuum',12,{eventId:'task:1:skill',source:'test'});assert.ok(s.duplicate,'duplicate skill event should be ignored');await e.persist();assert.strictEqual(db['alpha-user'].current.totalXp,10);assert.strictEqual(db['alpha-user'].current.skills.vacuum.xp,12);const old=subscriptions.find(x=>x.token==='alpha-user');ctx={uid:'beta-user',householdId:'beta-household'};(listeners['familyapp:household-context-changed']||[]).forEach(f=>f());await new Promise(r=>setTimeout(r,0));assert.strictEqual(e.status().context.uid,'beta-user');assert.strictEqual(e.getState().totalXp,0);old.cb({current:{schemaVersion:2,uid:'alpha-user',totalXp:999,skills:{vacuum:{xp:999,log:[]}},stats:{},streak:{},achievements:{},events:{}}},{source:'late-alpha'});assert.strictEqual(e.getState().totalXp,0,'late Alpha callback must not replace Beta progression');console.log('progression context rebind OK');})().catch(err=>{console.error(err);process.exit(1);});
