'use strict';
const fs=require('fs');const vm=require('vm');const assert=require('assert');
const code=fs.readFileSync('src/core/searchContextService.js','utf8');
let current={uid:'u-alpha',householdId:'h-alpha'};
let taskRows=[{id:'ta',title:'Alpha taak'}],recipeRows=[{id:'ra',name:'Alpha pasta',cat:'Diner',ingredients:['Alpha saus']}],calRows=[{id:'ca',title:'Alpha afspraak',date:'2026-08-16'}],shopRows=[{scope:'shared',list:{id:'la',name:'Alpha lijst',items:{ia:{id:'ia',name:'Alpha melk',qty:'1 liter'}}}}],members=[{uid:'u-alpha',displayName:'Alpha User'}];
function ctx(){return{requireUser:()=>current.uid,requireHousehold:()=>current.householdId,assertContext:(t)=>{if(t.uid!==current.uid||t.householdId!==current.householdId){let e=new Error('changed');e.code='HOUSEHOLD_CONTEXT_CHANGED';throw e;}},isCurrent:(t)=>!!t&&t.uid===current.uid&&t.householdId===current.householdId};}
const sandbox={console,Date,JSON,Math,window:{},CustomEvent:function(){}};sandbox.window.window=sandbox.window;
function setGlobal(name,value){sandbox.window[name]=value;sandbox[name]=value;}
function install(){setGlobal('HouseholdContext',ctx());setGlobal('TaskSharedData',{status:()=>({uid:current.uid,householdId:current.householdId,sharedSnapshot:true})});setGlobal('taskData',taskRows);setGlobal('RecipeStore',{status:()=>({ready:true,context:{...current}}),list:()=>recipeRows});setGlobal('ShoppingLists',{status:()=>({bound:true,context:{...current}}),all:()=>shopRows});setGlobal('CalendarSharedLive',{status:()=>({attached:true,context:{...current}})});setGlobal('calData',calRows);setGlobal('ProfileContextService',{status:()=>({context:{...current}}),getMembers:()=>members});}
install();vm.createContext(sandbox);vm.runInContext(code,sandbox);const svc=sandbox.window.SearchContextService;
assert(svc.search('Alpha').length>=4,'alpha sources should be searchable');let ai=svc.buildAiContext({include:['tasks','recipes','calendar','shopping','members','notes','finance']});assert.equal(ai.scope.householdId,'h-alpha');assert(ai.sources.tasks.length===1);assert(ai.sources.members.length===1);assert(!Object.prototype.hasOwnProperty.call(ai.sources,'notes'));assert(!Object.prototype.hasOwnProperty.call(ai.sources,'finance'));
// Switch context before source services rebind: stale source statuses/data must disappear.
const alphaStatus={uid:'u-alpha',householdId:'h-alpha'};current={uid:'u-beta',householdId:'h-beta'};setGlobal('HouseholdContext',ctx());setGlobal('TaskSharedData',{status:()=>({uid:alphaStatus.uid,householdId:alphaStatus.householdId,sharedSnapshot:true})});setGlobal('RecipeStore',{status:()=>({ready:true,context:alphaStatus}),list:()=>recipeRows});setGlobal('ShoppingLists',{status:()=>({bound:true,context:alphaStatus}),all:()=>shopRows});setGlobal('CalendarSharedLive',{status:()=>({attached:true,context:alphaStatus})});setGlobal('ProfileContextService',{status:()=>({context:alphaStatus}),getMembers:()=>members});assert.equal(svc.search('Alpha').length,0,'stale household sources must be rejected after context switch');ai=svc.buildAiContext({include:['tasks','recipes','calendar','shopping','members']});assert.equal(ai.sources.tasks.length,0);assert.equal(ai.sources.members.length,0);
// Rebind sources to beta and ensure alpha does not leak.
taskRows=[{id:'tb',title:'Beta taak'}];recipeRows=[{id:'rb',name:'Beta curry',cat:'Diner',ingredients:['Beta kruiden']}];calRows=[{id:'cb',title:'Beta afspraak',date:'2026-08-17'}];shopRows=[{scope:'private',list:{id:'lb',name:'Beta prive',items:{ib:{id:'ib',name:'Beta koffie',qty:'1 pak'}}}}];members=[{uid:'u-beta',displayName:'Beta User'}];install();assert.equal(svc.search('Alpha').length,0);assert(svc.search('Beta').length>=4);const sug=svc.shoppingSuggestions('Beta',[]);assert.equal(sug[0].n,'Beta koffie');const ing=svc.ingredientSuggestions('Beta',[]);assert.equal(ing[0],'Beta kruiden');ai=svc.buildAiContext({include:['shopping','members']});assert.equal(ai.scope.uid,'u-beta');assert.equal(ai.sources.shopping[0].scope,'private');assert.equal(ai.sources.members[0].uid,'u-beta');console.log('search context rebind: ok');
