'use strict';
(function(){
  if(window.FeedTagging&&window.FeedTagging.version==='1.1.0')return;
  var pending=[],picker=null,inlinePicker=null,originalCreate=null,originalRenderPost=null,patchedCreate=false,patchedRender=false;
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function safe(v){return esc(v).replace(/`/g,'&#096;');}
  function refs(value){return Array.isArray(value)?value.filter(function(r){return r&&((r.type==='member'&&r.uid)||(r.type==='recipe'&&r.recipeId));}).map(clone):[];}
  function key(r){return r.type==='member'?'member:'+String(r.uid):'recipe:'+String(r.recipeId);}
  function members(){try{if(window.FeedSharedData&&FeedSharedData.members)return FeedSharedData.members()||[];}catch(e){}try{if(window.HouseholdIdentityFirebaseBridge&&HouseholdIdentityFirebaseBridge.getMembers)return HouseholdIdentityFirebaseBridge.getMembers()||[];}catch(e){}return[];}
  function recipes(){try{if(window.RecipeStore&&RecipeStore.list)return RecipeStore.list()||[];}catch(e){}return Array.isArray(window.recipesData)?window.recipesData:[];}
  function memberRef(m){return{type:'member',uid:String(m.uid||m.id),displayName:String(m.displayName||m.name||'Gezinslid')};}
  function recipeRef(r){return{type:'recipe',recipeId:String(r.id),title:String(r.name||r.title||'Recept')};}
  function has(r){var k=key(r);return pending.some(function(x){return key(x)===k;});}
  function add(r){if(!r||has(r))return;pending.push(clone(r));renderPending();closeAllPickers();}
  function remove(k){pending=pending.filter(function(r){return key(r)!==String(k);});renderPending();}
  function clear(){pending=[];renderPending();}
  function pendingRefs(){return pending.map(clone);}

  function chip(r,removable){var label=r.type==='member'?'@'+(r.displayName||'Gezinslid'):(r.title||'Recept');var action=r.type==='member'?"openFeedReference('member','"+safe(r.uid)+"')":"openFeedReference('recipe','"+safe(r.recipeId)+"')";return '<span class="fs-tag-wrap"><button type="button" class="fs-tag-chip fs-tag-'+esc(r.type)+'" onclick="event.stopPropagation();'+action+'"><b>'+esc(label)+'</b></button>'+(removable?'<button type="button" class="fs-tag-remove" aria-label="Tag verwijderen" onclick="event.stopPropagation();removeFeedTag(\''+safe(key(r))+'\')">×</button>':'')+'</span>';}
  function chipsHtml(list){list=refs(list);return list.length?'<div class="fs-post-tags">'+list.map(function(r){return chip(r,false);}).join('')+'</div>':'';}
  function renderPending(){var host=document.getElementById('feed-tag-pending');if(host)host.innerHTML=pending.length?'<div class="fs-compose-tags">'+pending.map(function(r){return chip(r,true);}).join('')+'</div>':'';}

  function filteredRows(type,q){q=String(q||'').trim().toLowerCase();if(type==='member')return members().filter(function(m){return !q||String(m.displayName||m.name||'').toLowerCase().indexOf(q)>-1;}).map(memberRef);return recipes().filter(function(r){return !q||String(r.name||r.title||'').toLowerCase().indexOf(q)>-1;}).map(recipeRef);}
  function rowHtml(r,compact){var isMember=r.type==='member',label=isMember?r.displayName:r.title,sub=isMember?'Gezinslid':'Recept';return '<button type="button" class="'+(compact?'fs-tag-inline-row':'fs-tag-choice')+'" onclick="selectFeedTag(\''+r.type+'\',\''+safe(isMember?r.uid:r.recipeId)+'\')"><span class="fs-tag-avatar">'+(isMember?'@':'🍽')+'</span><span><b>'+esc(label)+'</b><small>'+sub+'</small></span><i>+</i></button>';}

  function closePicker(){if(picker&&picker.parentNode)picker.remove();picker=null;}
  function closeInline(){if(inlinePicker&&inlinePicker.parentNode)inlinePicker.remove();inlinePicker=null;}
  function closeAllPickers(){closePicker();closeInline();}
  function openPicker(type){closeAllPickers();var root=document.createElement('div');root.className='fs-tag-picker';root.innerHTML='<div class="fs-tag-backdrop" onclick="closeFeedTagPicker()"></div><section class="fs-tag-sheet"><div class="fs-tag-sheet-head"><div><small>TAG TOEVOEGEN</small><h3>'+(type==='member'?'Persoon':'Recept')+'</h3></div><button type="button" onclick="closeFeedTagPicker()">×</button></div><div class="fs-tag-choices">'+filteredRows(type,'').map(function(r){return rowHtml(r,false);}).join('')+'</div></section>';document.body.appendChild(root);picker=root;}
  function openInline(type,query){closeInline();var ca=document.getElementById('compose-area');if(!ca)return;var rows=filteredRows(type,query).slice(0,6);var root=document.createElement('div');root.className='fs-tag-inline';root.innerHTML='<div class="fs-tag-inline-head"><b>'+(type==='member'?'Persoon taggen':'Recept taggen')+'</b><small>'+(query?esc(query):'Kies een optie')+'</small></div><div class="fs-tag-inline-list">'+(rows.length?rows.map(function(r){return rowHtml(r,true);}).join(''):'<div class="fs-tag-empty">Geen resultaten</div>')+'</div>';document.body.appendChild(root);inlinePicker=root;positionInline(root,ca);}
  function positionInline(root,ca){var r=ca.getBoundingClientRect(),vv=window.visualViewport;var viewportTop=vv?vv.offsetTop:0,viewportH=vv?vv.height:window.innerHeight;var bottom=Math.max(12,window.innerHeight-(viewportTop+viewportH)+12);root.style.left=Math.max(12,r.left)+'px';root.style.width=Math.min(r.width,window.innerWidth-24)+'px';root.style.bottom=bottom+'px';}
  function select(type,id){if(type==='member'){var m=members().find(function(x){return String(x.uid||x.id)===String(id);});if(m)add(memberRef(m));return;}var r=recipes().find(function(x){return String(x.id)===String(id);});if(r)add(recipeRef(r));}

  function openRef(type,id){closeAllPickers();if(type==='recipe'){try{if(window.showScreenMore)showScreenMore('recipes');else if(window.showScreen)showScreen('recipes');}catch(e){}setTimeout(function(){try{if(window.openRecipeDetail)openRecipeDetail(id);}catch(e){}},120);return;}window.__familyFeedMemberFocusUid=String(id);try{if(window.showScreen)showScreen('tasks');}catch(e){}setTimeout(function(){try{var personTab=document.querySelector('#screen-tasks [data-tab="person"],#screen-tasks [data-task-tab="person"],#screen-tasks .ttab-person,#screen-tasks .task-tab-person');if(personTab&&personTab.click)personTab.click();setTimeout(function(){var btn=document.querySelector('[data-pt2-member="'+CSS.escape(String(id))+'"]');if(btn)btn.click();},80);}catch(e){}},80);}

  function decorateComposer(){var card=document.getElementById('feed-compose-card')||document.querySelector('#screen-feed .feed-compose-card');if(!card)return;if(!document.getElementById('feed-tag-tools')){var tools=document.createElement('div');tools.id='feed-tag-tools';tools.className='fs-tag-tools';tools.innerHTML='<button type="button" class="fs-tag-tool" aria-label="Persoon taggen" title="Persoon taggen" onclick="openFeedTagPicker(\'member\')">@</button><button type="button" class="fs-tag-tool fs-tag-tool-recipe" aria-label="Recept taggen" title="Recept taggen" onclick="openFeedTagPicker(\'recipe\')">⌑</button>';var actions=card.querySelector('.compose-actions,.feed-compose-actions');if(actions)actions.insertBefore(tools,actions.lastElementChild||null);else card.appendChild(tools);var pendingHost=document.createElement('div');pendingHost.id='feed-tag-pending';var input=card.querySelector('#compose-area,.compose-input');if(input&&input.parentNode)input.parentNode.insertBefore(pendingHost,input.nextSibling);else card.appendChild(pendingHost);renderPending();}
    var ca=document.getElementById('compose-area');if(ca&&ca.dataset.feedTagWired!=='1'){ca.dataset.feedTagWired='1';ca.addEventListener('input',function(){var text=String(ca.innerText||ca.textContent||'');var match=text.match(/(?:^|\s)([@#])([^\s@#]{0,30})$/);if(match){openInline(match[1]==='@'?'member':'recipe',match[2]||'');}else closeInline();});ca.addEventListener('blur',function(){setTimeout(function(){if(!document.activeElement||!document.activeElement.closest||!document.activeElement.closest('.fs-tag-inline'))closeInline();},120);});}}

  function patchCreate(){if(patchedCreate||!window.FeedSharedData||!FeedSharedData.createPost)return false;originalCreate=FeedSharedData.createPost;FeedSharedData.createPost=function(data){data=Object.assign({},data||{});var supplied=refs(data.references),current=pendingRefs();data.references=supplied.concat(current.filter(function(r){return !supplied.some(function(x){return key(x)===key(r);});}));return Promise.resolve(originalCreate.call(FeedSharedData,data)).then(function(row){clear();return row;});};patchedCreate=true;return true;}
  function patchRender(){if(patchedRender||!window.renderPostHTML)return false;originalRenderPost=window.renderPostHTML;window.renderPostHTML=function(p){var html=originalRenderPost(p);if(!p||p.type!=='post')return html;var tags=chipsHtml(p.references);if(!tags)return html;var re=/(<div class="fs-post-text">[\s\S]*?<\/div>)/;return re.test(html)?html.replace(re,'$1'+tags):html.replace('</article>',tags+'</article>');};patchedRender=true;return true;}

  function css(){if(document.getElementById('feed-tagging-css-v2'))return;var s=document.createElement('style');s.id='feed-tagging-css-v2';s.textContent=''
    +'.fs-tag-tools{display:inline-flex;gap:6px;align-items:center;margin-left:2px}.fs-tag-tool{width:30px;height:30px;min-width:30px;border:1px solid var(--c-border,#e3e7eb);border-radius:10px;background:transparent;color:var(--c-text2,#667085);font-size:17px;font-weight:900;display:grid;place-items:center;padding:0}.fs-tag-tool-recipe{font-size:16px}.fs-compose-tags,.fs-post-tags{display:flex;gap:5px;flex-wrap:wrap}.fs-compose-tags{margin:7px 0 0}.fs-post-tags{margin:0 0 10px}.fs-tag-wrap{display:inline-flex;align-items:center}.fs-tag-chip{height:25px;display:inline-flex;align-items:center;border:0;border-radius:9px;padding:0 8px;background:#eef6ee;color:#47714b;font-size:11.5px;max-width:190px}.fs-tag-chip.fs-tag-recipe{background:#f3effb;color:#735d9b}.fs-tag-chip b{font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.fs-tag-remove{margin-left:2px;width:20px;height:20px;border:0;border-radius:7px;background:transparent;color:#98a0ab;font-size:15px;padding:0;display:grid;place-items:center}'
    +'.fs-tag-inline{position:fixed;z-index:100030;background:var(--c-surface,#fff);border:1px solid var(--c-border,#e5e7eb);border-radius:16px;box-shadow:0 16px 40px rgba(17,24,39,.16);padding:8px;max-height:240px;overflow:auto}.fs-tag-inline-head{display:flex;align-items:center;justify-content:space-between;padding:3px 6px 7px}.fs-tag-inline-head b{font-size:12px;color:var(--c-text,#111827)}.fs-tag-inline-head small{font-size:10px;color:var(--c-text3,#9aa3b2)}.fs-tag-inline-list{display:flex;flex-direction:column;gap:2px}.fs-tag-inline-row{width:100%;display:grid;grid-template-columns:32px 1fr 20px;gap:8px;align-items:center;text-align:left;border:0;background:transparent;border-radius:11px;padding:6px;color:var(--c-text,#111827)}.fs-tag-inline-row:active{background:var(--c-surface2,#f3f5f4)}.fs-tag-inline-row b{display:block;font-size:12.5px}.fs-tag-inline-row small{display:block;font-size:10px;color:var(--c-text2,#7c8592)}.fs-tag-inline-row i{font-style:normal;color:var(--c-primary,#3f7f2f);font-weight:900}.fs-tag-avatar{width:32px;height:32px;border-radius:10px;background:var(--c-surface2,#f3f4f6);display:grid;place-items:center;font-size:13px;font-weight:900;color:var(--c-text2,#667085)}'
    +'.fs-tag-picker{position:fixed;inset:0;z-index:100020;display:flex;align-items:flex-end;justify-content:center}.fs-tag-backdrop{position:absolute;inset:0;background:rgba(14,18,25,.28);backdrop-filter:blur(4px)}.fs-tag-sheet{position:relative;width:min(100%,520px);max-height:58vh;background:var(--c-surface,#fff);border-radius:22px 22px 0 0;padding:14px 14px calc(18px + env(safe-area-inset-bottom));box-shadow:0 -16px 50px rgba(0,0,0,.18)}.fs-tag-sheet-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.fs-tag-sheet-head small{font-size:9px;letter-spacing:.1em;color:var(--c-text3,#9aa3b2);font-weight:900}.fs-tag-sheet-head h3{margin:1px 0 0;font-size:18px}.fs-tag-sheet-head>button{width:30px;height:30px;border:0;border-radius:10px;background:var(--c-surface2,#f1f3f2);font-size:21px}.fs-tag-choices{display:flex;flex-direction:column;gap:3px;overflow:auto;max-height:calc(58vh - 64px)}.fs-tag-choice{width:100%;display:grid;grid-template-columns:36px 1fr 22px;gap:9px;align-items:center;text-align:left;border:0;border-bottom:1px solid var(--c-border,#eef0f2);background:transparent;padding:8px 4px;color:var(--c-text,#111827)}.fs-tag-choice b{display:block;font-size:13px}.fs-tag-choice small{display:block;font-size:10px;color:var(--c-text2,#7c8592)}.fs-tag-choice i{font-style:normal;color:var(--c-primary,#3f7f2f);font-weight:900}.fs-tag-empty{text-align:center;padding:24px;color:var(--c-text2,#7c8592);font-size:12px}'
    +'[data-theme="dark"] .fs-tag-chip,.dark .fs-tag-chip,body.dark-mode .fs-tag-chip{background:#243128;color:#a9d0ad}[data-theme="dark"] .fs-tag-chip.fs-tag-recipe,.dark .fs-tag-chip.fs-tag-recipe,body.dark-mode .fs-tag-chip.fs-tag-recipe{background:#312a3f;color:#c8b7e4}';document.head.appendChild(s);}
  function boot(){css();patchCreate();patchRender();decorateComposer();var obs=new MutationObserver(function(){patchCreate();patchRender();decorateComposer();});obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('familyapp:feed-updated',function(){setTimeout(decorateComposer,0);});if(window.visualViewport)visualViewport.addEventListener('resize',function(){if(inlinePicker){var ca=document.getElementById('compose-area');if(ca)positionInline(inlinePicker,ca);}});}
  window.FeedTagging={version:'1.1.0',pending:pendingRefs,clear:clear,add:add,remove:remove,openPicker:openPicker,closePicker:closeAllPickers,select:select,openReference:openRef,decorateComposer:decorateComposer};window.openFeedTagPicker=openPicker;window.closeFeedTagPicker=closeAllPickers;window.selectFeedTag=select;window.removeFeedTag=remove;window.openFeedReference=openRef;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
