'use strict';
// ============================================================
// FEED SHARED DATA v2.0
// Canonical household social posts under shared/feed.
// Activity events live separately under shared/activity.
// ============================================================
(function(){
  if(window.FeedSharedData&&window.FeedSharedData.version==='2.0.0')return;
  var VERSION='2.0.0',COLLECTION='feed',LEGACY_RECORD_COLLECTION='feedPosts';
  var state={token:null,unsubscribe:null,hasSnapshot:false,posts:{},migrated:{},lastError:null};
  function fds(){return window.FamilyDataStore||null;}function hc(){return window.HouseholdContext||null;}function now(){return Date.now();}
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function captureReady(){var c=hc();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function same(t){return!!(t&&hc()&&hc().isCurrent(t));}function assertToken(t){if(!same(t)){var e=new Error('FEED_CONTEXT_CHANGED');e.code='FEED_CONTEXT_CHANGED';throw e;}return t;}
  function members(){try{if(window.HouseholdIdentityFirebaseBridge&&typeof HouseholdIdentityFirebaseBridge.getMembers==='function')return HouseholdIdentityFirebaseBridge.getMembers()||[];if(window.TaskSharedData&&typeof TaskSharedData.members==='function')return TaskSharedData.members()||[];}catch(e){}return[];}
  function memberByUid(id){return members().find(function(m){return String(m.uid||m.id)===String(id);})||null;}
  function displayNameFor(id){var m=memberByUid(id)||{};return m.displayName||m.name||'Gezinslid';}
  function initialsFor(name){return String(name||'G').trim().split(/\s+/).map(function(p){return p.charAt(0);}).join('').slice(0,2).toUpperCase()||'G';}
  function makeId(prefix){var s=fds();return s&&s.makeId?s.makeId(prefix||'post'):(prefix||'post')+'_'+now().toString(36)+'_'+Math.random().toString(36).slice(2,8);}
  function likesArray(row){var l=row&&row.likes;if(!l)return[];if(Array.isArray(l))return l.filter(Boolean);return Object.keys(l).filter(function(k){return l[k];});}
  function commentsArray(row){var c=row&&row.comments;if(!c)return[];var list=Array.isArray(c)?c.filter(Boolean).map(function(x,i){return Object.assign({},x,{_key:x._key||String(i)});}):Object.keys(c).map(function(k){var v=c[k];return v?Object.assign({},v,{_key:k}):null;}).filter(Boolean);return list.sort(function(a,b){return Number(a.createdAt||0)-Number(b.createdAt||0);});}
  function rows(value){if(!value)return[];return Object.keys(value).map(function(key){var raw=value[key];if(!raw||typeof raw!=='object')return null;var row=clone(raw)||{};row._key=key;if(row.id==null)row.id=key;row.likes=likesArray(row);row.comments=commentsArray(row);row.authorDisplayName=row.authorDisplayName||displayNameFor(row.authorUid);row.author=row.authorDisplayName;row.initials=row.initials||initialsFor(row.authorDisplayName);return row;}).filter(Boolean).sort(function(a,b){return Number(b.createdAt||0)-Number(a.createdAt||0);});}
  function publishProjection(value,token){if(token&&!same(token))return;state.posts=value&&typeof value==='object'?value:{};window.feedData=rows(state.posts);state.hasSnapshot=true;try{window.dispatchEvent(new CustomEvent('familyapp:feed-updated',{detail:{householdId:token&&token.householdId||null,count:window.feedData.length}}));}catch(e){}try{var screen=document.getElementById('screen-feed');if(screen&&screen.classList.contains('active')&&typeof window.renderFeed==='function')window.renderFeed();}catch(e){}}
  function findLocal(idOrKey){var target=String(idOrKey||'');return(window.feedData||[]).find(function(p){return String(p.id)===target||String(p._key||'')===target;})||null;}function keyFor(post){return post&&(post._key||String(post.id));}
  function migrateLegacy(token){var k=token.uid+':'+token.householdId;if(state.migrated[k])return Promise.resolve(false);state.migrated[k]=true;var s=fds();return s.readShared(COLLECTION,{}).then(function(current){assertToken(token);if(current&&Object.keys(current).length)return false;return s.readShared(LEGACY_RECORD_COLLECTION,{}).then(function(old){assertToken(token);if(!old||typeof old!=='object'||!Object.keys(old).length)return false;var jobs=Object.keys(old).map(function(key){var raw=old[key];if(!raw||typeof raw!=='object')return Promise.resolve();var row=clone(raw);row.id=row.id||key;row.householdId=token.householdId;row.authorUid=row.authorUid||null;return s.writeSharedRecord(COLLECTION,key,row);});return Promise.all(jobs).then(function(){assertToken(token);return true;});});});}
  function stop(){if(state.unsubscribe)try{state.unsubscribe();}catch(e){}state.unsubscribe=null;state.token=null;state.posts={};state.hasSnapshot=false;window.feedData=[];try{window.dispatchEvent(new CustomEvent('familyapp:feed-updated',{detail:{count:0}}));}catch(e){}}
  function start(){var token;try{token=captureReady();}catch(e){stop();return Promise.resolve(status());}if(state.token&&same(state.token)&&state.unsubscribe)return Promise.resolve(status());stop();state.token=token;return migrateLegacy(token).catch(function(e){if(e&&e.code!=='FEED_CONTEXT_CHANGED')console.warn('[FeedSharedData] legacy migration failed',e);}).then(function(){assertToken(token);state.unsubscribe=fds().subscribeShared(COLLECTION,function(value){if(!same(token))return;publishProjection(value,token);},{});return status();}).catch(function(e){if(e&&e.code!=='FEED_CONTEXT_CHANGED')state.lastError=e.message||String(e);return status();});}
  function rebind(){stop();return start();}
  function createPost(data){var token=captureReady(),key=makeId('post'),ts=now(),name=displayNameFor(token.uid);var row={id:key,type:'post',householdId:token.householdId,authorUid:token.uid,authorDisplayName:name,author:name,initials:initialsFor(name),text:String(data&&data.text||''),media:data&&data.media||null,mediaType:data&&data.mediaType||null,linkedEntity:data&&data.linkedEntity||null,createdAt:ts,updatedAt:ts,likes:{},comments:{}};assertToken(token);return fds().writeSharedRecord(COLLECTION,key,row).then(function(result){assertToken(token);return row;});}
  function canDelete(post){var token;try{token=captureReady();}catch(e){return false;}return!!(post&&post.authorUid&&String(post.authorUid)===String(token.uid));}
  function deletePost(idOrKey){var token=captureReady(),post=findLocal(idOrKey);if(!post)return Promise.reject(new Error('Post niet gevonden'));if(!canDelete(post))return Promise.reject(new Error('Je kunt alleen je eigen posts verwijderen'));assertToken(token);return fds().writeSharedRecord(COLLECTION,keyFor(post),null).then(function(r){assertToken(token);return r;});}
  function toggleReaction(idOrKey){var token=captureReady(),post=findLocal(idOrKey);if(!post)return Promise.reject(new Error('Post niet gevonden'));var liked=(post.likes||[]).indexOf(token.uid)>-1;assertToken(token);return fds().writeSharedPath(COLLECTION,[keyFor(post),'likes',token.uid],liked?null:true).then(function(){assertToken(token);return{liked:!liked};});}
  function addComment(idOrKey,data){var token=captureReady(),post=findLocal(idOrKey);if(!post)return Promise.reject(new Error('Post niet gevonden'));var name=displayNameFor(token.uid),commentKey=makeId('cmt'),comment={authorUid:token.uid,authorDisplayName:name,author:name,initials:initialsFor(name),text:String(data&&data.text||''),gifUrl:data&&data.gifUrl||null,createdAt:now()};assertToken(token);return fds().writeSharedPath(COLLECTION,[keyFor(post),'comments',commentKey],comment).then(function(){assertToken(token);return comment;});}
  function getPosts(){return(window.feedData||[]).slice();}
  function status(){return{version:VERSION,ready:!!(state.token&&same(state.token)&&state.unsubscribe),hasSnapshot:state.hasSnapshot,context:state.token?clone(state.token):null,count:(window.feedData||[]).length,lastError:state.lastError,collection:COLLECTION};}
  window.FeedSharedData={version:VERSION,start:start,stop:stop,rebind:rebind,createPost:createPost,deletePost:deletePost,toggleReaction:toggleReaction,addComment:addComment,getPosts:getPosts,canDelete:canDelete,members:members,status:status};
  window.addEventListener('familyapp:household-context-changed',rebind);window.addEventListener('familyapp:session:cleared',stop);window.addEventListener('online',start);window.addEventListener('focus',start);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
