'use strict';
// ============================================================
// FEED ACTIVITY PRESENTATION v1.2.1 — STEP 13.3
// Social posts keep their existing card style. Immutable household activity
// events are merged only for presentation and receive a stable semantic pastel
// family with explicit dark-mode counterparts. Copy is contextual/cozy rather
// than repeating the same event label in eyebrow, title and body.
// ============================================================
(function(){
  if(window.FeedActivityPresentation&&window.FeedActivityPresentation.version==='1.2.1')return;

  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function actorMember(event){try{return window.HouseholdActivity&&HouseholdActivity.resolveMember?HouseholdActivity.resolveMember(event.actorUid):null;}catch(e){return null;}}
  function actorName(event){var m=actorMember(event)||{};try{if(m.displayName||m.name)return m.displayName||m.name;if(window.HouseholdActivity&&HouseholdActivity.actorName)return HouseholdActivity.actorName(event.actorUid);}catch(e){}return 'Gezinslid';}
  function actorAvatar(event){var m=actorMember(event)||{},name=m.displayName||m.name||actorName(event),url=m.avatar||m.avatarUrl||m.photoURL||m.photoUrl||'';if(url)return '<img class="fs-author-avatar" src="'+esc(url)+'" alt="'+esc(name)+'" style="object-fit:cover">';try{if(typeof window.avatarHTML==='function')return window.avatarHTML(name,m.initials||'','', 'fs-author-avatar');}catch(e){}return '<div class="fs-author-avatar"></div>';}
  function postTime(p){return Number(p&&p.createdAt||0);}
  function eventTime(e){return Number(e&&e.occurredAt||e&&e.createdAt||0);}
  function events(){try{return window.HouseholdActivity&&HouseholdActivity.getEvents?HouseholdActivity.getEvents().filter(function(e){return HouseholdActivity.shouldPublishToFeed(e);}):[];}catch(e){return[];}}
  function pick(event,values){var seed=String(event&&event.id||event&&event.occurrenceKey||event&&event.type||'family');var hash=0;for(var i=0;i<seed.length;i++)hash=((hash<<5)-hash+seed.charCodeAt(i))|0;return values[Math.abs(hash)%values.length];}
  function taskDoneTitle(e){return pick(e,['Weer eentje van de lijst ✓','Dat is geregeld ✨','Lekker afgevinkt','Een taak minder aan je hoofd','Klaar is klaar 🙌']);}
  function taskCreatedTitle(e){return pick(e,['Er staat iets nieuws klaar','Nieuwe missie voor thuis','Iets om straks af te vinken','Op de planning ✨']);}
  function shoppingTitle(e){return pick(e,['De voorraad is weer aangevuld','De buit is binnen 🛒','Koelkastmodus: aangevuld','We kunnen weer vooruit','Boodschappen binnen ✓']);}
  function mealTitle(e){return pick(e,['Iets lekkers om naar uit te kijken','Het menu krijgt vorm 🍽️','Eten staat op de planning','Dat wordt lekker']);}
  function partyTitle(e){return pick(e,['Samen gefixt 🏆','Teamwork betaald zich uit','Quest geklaard ✨','Als team weer eentje binnen']);}

  var PRESENTATIONS={
    'task.created':function(e){var p=e.payload||{},name=p.taskTitle||'Nieuwe taak';return{eyebrow:'NIEUWE TAAK',title:taskCreatedTitle(e),body:actorName(e)+' zette “'+name+'” op de planning',detail:p.xpEarned?'Klaar voor '+p.xpEarned+' XP':'Klaar om opgepakt te worden',meta:null,icon:'✓',tone:'tone-task'};},
    'task.completed':function(e){var p=e.payload||{},name=p.taskTitle||'Taak';return{eyebrow:'TAAK AFGEROND',title:taskDoneTitle(e),body:actorName(e)+' rondde “'+name+'” af',detail:p.xpEarned?'Mooi meegenomen':'Het huis is weer een taak lichter',meta:p.xpEarned?('+'+p.xpEarned+' XP'):null,icon:'✓',tone:'tone-task'};},
    'meal.planned':function(e){var p=e.payload||{},meal=p.mealName||'Maaltijd';return{eyebrow:'MAALTIJD GEPLAND',title:mealTitle(e),body:meal+' is ingepland door '+actorName(e),detail:p.plannedDate||null,meta:p.slot==='lunch'?'Lunch':(p.slot==='breakfast'?'Ontbijt':(p.slot==='dinner'?'Diner':null)),icon:'🍽️',tone:'tone-meal'};},
    'shopping.completed':function(e){var p=e.payload||{};return{eyebrow:'BOODSCHAPPEN',title:shoppingTitle(e),body:actorName(e)+' heeft de boodschappen gedaan',detail:p.shoppingListName||'Gezinsboodschappen',meta:p.itemCount?String(p.itemCount)+' items':null,icon:'🛒',tone:'tone-shopping'};},
    'grocery.receipt_uploaded':function(e){var p=e.payload||{};return{eyebrow:'BOODSCHAPPEN',title:shoppingTitle(e),body:actorName(e)+' heeft de boodschappen gedaan',detail:p.shoppingListName||'Gezinsboodschappen',meta:p.itemCount?String(p.itemCount)+' items':null,icon:'🛒',tone:'tone-shopping'};},
    'partyQuest.completed':function(e){var p=e.payload||{};return{eyebrow:'PARTY QUEST',title:partyTitle(e),body:'“'+(p.questTitle||'Party Quest')+'” is samen afgerond',detail:'Goed teamwork',meta:p.xpPerParticipant?('+'+p.xpPerParticipant+' XP p.p.'):null,icon:'🏆',tone:'tone-progression'};},
    'agenda.created':function(e){var p=e.payload||{};return{eyebrow:'AFSPRAAK',title:'Iets om naar uit te kijken',body:(p.title||'Nieuwe afspraak')+' staat in de agenda',detail:p.date||null,meta:p.time||null,icon:'📅',tone:'tone-agenda'};}
  };

  function genericPresentation(e){var p=e.payload||{};return{eyebrow:'GEZINSUPDATE',title:p.title||'Er is iets nieuws thuis',body:p.message||actorName(e)+' heeft iets bijgewerkt',detail:p.detail||null,meta:null,icon:'⌂',tone:'tone-generic'};}
  function presentation(event){return (PRESENTATIONS[event.type]||genericPresentation)(event);}
  function card(event){var vm=presentation(event);return '<article class="fs-card fs-activity '+esc(vm.tone)+'" data-activity-id="'+esc(event.id)+'" onclick="openHouseholdActivitySource(\''+esc(event.id)+'\')">'
      +'<div class="fs-activity-head">'+actorAvatar(event)
      +'<div class="fs-activity-heading"><span class="fs-activity-eyebrow">'+esc(vm.eyebrow)+'</span><strong>'+esc(vm.title)+'</strong><small>'+esc(vm.body)+'</small></div>'
      +'<div class="fs-activity-icon">'+esc(vm.icon)+'</div></div>'
      +(vm.detail?'<div class="fs-activity-detail"><b>'+esc(vm.detail)+'</b>'+(vm.meta?'<span>'+esc(vm.meta)+'</span>':'')+'</div>':'')
      +'</article>';}

  function merged(){var social=(window.feedData||[]).map(function(p){return{kind:'post',at:postTime(p),value:p};});var activity=events().map(function(e){return{kind:'activity',at:eventTime(e),value:e};});return social.concat(activity).sort(function(a,b){return b.at-a.at;});}
  function matchesFilter(item){if(window.feedFilter==='tasks')return (item.kind==='activity'&&/^task\./.test(item.value.type))||(item.kind==='post'&&item.value.type==='task');if(window.feedFilter==='agenda')return (item.kind==='activity'&&/^agenda\./.test(item.value.type))||(item.kind==='post'&&item.value.type==='agenda');return true;}
  function feedBody(){var st=null;try{st=window.FeedSharedData&&FeedSharedData.status?FeedSharedData.status():null;}catch(e){}if(!st||!st.hasSnapshot)return '<div class="fs-feed-loading" style="text-align:center;padding:48px 20px;color:var(--c-text2,#6b7280)"><div style="font-size:28px;margin-bottom:8px">⏳</div><div style="font-size:14px;font-weight:600">Feed wordt verbonden...</div></div>';var items=merged().filter(matchesFilter);if(!items.length)return '<div class="fs-feed-empty" style="text-align:center;padding:48px 20px;color:var(--c-text2,#6b7280)"><div style="font-size:28px;margin-bottom:8px">💬</div><div style="font-size:14px;font-weight:600">Nog geen berichten</div><div style="font-size:12px;margin-top:4px">Deel iets met het gezin hierboven</div></div>';return items.map(function(item){if(item.kind==='activity')return card(item.value);return typeof window.renderPostHTML==='function'?window.renderPostHTML(item.value):'';}).join('');}

  function stats(){var es=events(),social=window.feedData||[];return{tasks:es.filter(function(e){return e.type==='task.completed';}).length,agenda:es.filter(function(e){return /^agenda\./.test(e.type);}).length+social.filter(function(p){return p.type==='agenda';}).length,shopping:es.filter(function(e){return e.type==='shopping.completed'||e.type==='grocery.receipt_uploaded';}).length,updates:es.length+social.length};}
  function statLabel(type,value){if(type==='task')return value+' afgerond';if(type==='agenda')return value+' gepland';if(type==='shop')return value+' afgerond';return value+' totaal';}
  function decorateStats(){var root=document.querySelector('#screen-feed .fs-stats');if(!root)return;var s=stats(),map={task:s.tasks,agenda:s.agenda,shop:s.shopping,updates:s.updates};Object.keys(map).forEach(function(type){var node=root.querySelector('.fs-stat.'+type+' .fs-stat-copy span');if(node)node.textContent=statLabel(type,map[type]);});}

  function openSource(eventId){var event=events().find(function(e){return String(e.id)===String(eventId);});if(!event||!event.source)return;var module=event.source.module;try{if(module==='tasks'||module==='partyQuests'){if(typeof window.showScreen==='function')window.showScreen('tasks');return;}if(module==='meals'){if(typeof window.showScreenMore==='function')window.showScreenMore('meals');else if(typeof window.showScreen==='function')window.showScreen('meals');return;}if(module==='shop'){if(typeof window.showScreenMore==='function')window.showScreenMore('shop');else if(typeof window.showScreen==='function')window.showScreen('shop');return;}if(module==='agenda'&&typeof window.showScreenMore==='function')window.showScreenMore('cal');}catch(e){}}

  function css(){if(document.getElementById('feed-activity-presentation-v3'))return;var s=document.createElement('style');s.id='feed-activity-presentation-v3';s.textContent=''
    +'.fs-activity{--event-bg:#f7f5f0;--event-border:#e8e3d9;--event-accent:#756d61;--event-chip:#eee9df;position:relative;overflow:hidden;cursor:pointer;background:var(--event-bg)!important;border-color:var(--event-border)!important;transition:transform .14s ease,box-shadow .14s ease}.fs-activity:active{transform:scale(.992)}.fs-activity:before{content:"";position:absolute;inset:0 auto 0 0;width:4px;background:var(--event-accent)}'
    +'.fs-activity.tone-task{--event-bg:#edf8f0;--event-border:#d6eadb;--event-accent:#5c8f6a;--event-chip:#dff1e4}.fs-activity.tone-meal{--event-bg:#fff2e9;--event-border:#f3ddcf;--event-accent:#bd7656;--event-chip:#f9e4d7}.fs-activity.tone-shopping{--event-bg:#fff9df;--event-border:#eee4b7;--event-accent:#a98b36;--event-chip:#f6edc4}.fs-activity.tone-agenda{--event-bg:#edf5ff;--event-border:#d7e5f5;--event-accent:#6284a9;--event-chip:#dfebf8}.fs-activity.tone-progression{--event-bg:#f4effc;--event-border:#e4d9f3;--event-accent:#8067a3;--event-chip:#e9def6}'
    +'.fs-activity-head{display:grid;grid-template-columns:48px 1fr 42px;gap:12px;align-items:center}.fs-activity-heading{min-width:0}.fs-activity-eyebrow{display:block;font-size:10px;font-weight:950;letter-spacing:.11em;color:var(--event-accent);margin-bottom:3px}.fs-activity-heading strong{display:block;font-size:16px;color:var(--c-text,#111827);line-height:1.22}.fs-activity-heading small{display:block;font-size:12px;color:var(--c-text2,#707887);margin-top:3px;line-height:1.3}.fs-activity-icon{width:40px;height:40px;border-radius:14px;background:var(--event-chip);display:grid;place-items:center;font-size:18px}.fs-activity-detail{margin:14px 0 0 60px;padding:11px 12px;border:1px solid var(--event-border);border-radius:15px;background:color-mix(in srgb,var(--event-bg) 65%,var(--c-surface,#fff) 35%);font-size:14px;color:var(--c-text,#172033);display:flex;align-items:center;justify-content:space-between;gap:10px}.fs-activity-detail b{font-weight:850}.fs-activity-detail span{font-size:12px;color:var(--c-text2,#748094);font-weight:850;white-space:nowrap}'
    +'[data-theme="dark"] .fs-activity,.dark .fs-activity,body.dark-mode .fs-activity{--event-bg:#242421;--event-border:#393833;--event-accent:#c7c0b4;--event-chip:#32312c}.dark .fs-activity.tone-task,body.dark-mode .fs-activity.tone-task,[data-theme="dark"] .fs-activity.tone-task{--event-bg:#1d2c23;--event-border:#2d4736;--event-accent:#8fc69e;--event-chip:#263c2e}.dark .fs-activity.tone-meal,body.dark-mode .fs-activity.tone-meal,[data-theme="dark"] .fs-activity.tone-meal{--event-bg:#33241f;--event-border:#50372d;--event-accent:#e1a183;--event-chip:#432e27}.dark .fs-activity.tone-shopping,body.dark-mode .fs-activity.tone-shopping,[data-theme="dark"] .fs-activity.tone-shopping{--event-bg:#302c1d;--event-border:#4a4328;--event-accent:#d7bd65;--event-chip:#403a24}.dark .fs-activity.tone-agenda,body.dark-mode .fs-activity.tone-agenda,[data-theme="dark"] .fs-activity.tone-agenda{--event-bg:#1e2934;--event-border:#304253;--event-accent:#8fb4d9;--event-chip:#293847}.dark .fs-activity.tone-progression,body.dark-mode .fs-activity.tone-progression,[data-theme="dark"] .fs-activity.tone-progression{--event-bg:#292335;--event-border:#403651;--event-accent:#bba3db;--event-chip:#362e45}';document.head.appendChild(s);}

  var previousRender=window.renderFeed;
  if(typeof previousRender==='function'&&!previousRender.__activityStatsWrapped){var wrapped=function(){var out=previousRender.apply(this,arguments);setTimeout(decorateStats,0);return out;};wrapped.__activityStatsWrapped=true;window.renderFeed=wrapped;}
  window.feedListBodyHTML=function(){css();return feedBody();};window.openHouseholdActivitySource=openSource;
  window.addEventListener('familyapp:activity-updated',function(){try{var screen=document.getElementById('screen-feed');if(screen&&screen.classList.contains('active')&&typeof window.renderFeed==='function')window.renderFeed();}catch(e){}});
  window.FeedActivityPresentation={version:'1.2.1',presentations:PRESENTATIONS,presentation:presentation,merged:merged,stats:stats,renderCard:card,openSource:openSource};
})();
