const avatarUrl = 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80';
const familyPhotoOne = 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=180&q=80';
const familyPhotoTwo = 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=180&q=80';
const familyPhotoThree = 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=180&q=80';

export function renderFeedScreen(container) {
  container.innerHTML = [
    '<section class="target-feed">',
    '  <section class="target-feed-summary">',
    '    <h2>Goedemiddag Shane 👋</h2>',
    '    <p>Dit is er vandaag in het gezin</p>',
    '    <div class="target-stat-grid">',
    '      <div class="target-stat"><span class="target-stat-icon green">✓</span><strong>4</strong><small>Taken afgerond</small></div>',
    '      <div class="target-stat"><span class="target-stat-icon purple">▣</span><strong>2</strong><small>Afspraken</small></div>',
    '      <div class="target-stat"><span class="target-stat-icon orange">▣</span><strong>3</strong><small>Boodschappen</small></div>',
    '      <div class="target-stat"><span class="target-stat-icon blue">●●</span><strong>5</strong><small>Nieuwe updates</small></div>',
    '    </div>',
    '  </section>',
    '',
    '  <section class="target-composer">',
    '    <div class="target-avatar solid">SK</div>',
    '    <div class="target-input">Deel iets met het gezin...</div>',
    '    <div class="target-composer-actions">',
    '      <button>▧</button><button>☺</button><button>⌖</button><button>☷</button>',
    '      <button class="target-post">Posten</button>',
    '    </div>',
    '  </section>',
    '',
    '  <nav class="target-tabs">',
    '    <button class="active">⌂ Alle updates</button>',
    '    <button>☑ Taken</button>',
    '    <button>▣ Agenda</button>',
    "    <button>▧ Foto's</button>",
    '    <button>▱ Notities</button>',
    '  </nav>',
    '',
    '  <section class="target-feed-list">',
    '    <article class="target-card task-card">',
    '      <div class="target-type-icon task">✓</div>',
    '      <img class="target-user-photo" src="' + avatarUrl + '" alt="">',
    '      <div class="target-card-body">',
    '        <div class="target-card-top"><p><strong>Shane</strong> heeft een taak afgerond</p><span>1u ···</span></div>',
    '        <h3>Vuilnis buiten zetten</h3>',
    '        <div class="target-card-footer"><b>+10 punten</b><div class="target-mini-avatars"><span></span><span></span><span></span><em>+2</em></div></div>',
    '      </div>',
    '    </article>',
    '',
    '    <article class="target-card agenda-card">',
    '      <div class="target-type-icon agenda">▣</div>',
    '      <img class="target-user-photo" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80" alt="">',
    '      <div class="target-card-body">',
    '        <div class="target-card-top"><p><strong>Esra</strong> heeft een afspraak toegevoegd</p><span>2u ···</span></div>',
    '        <div class="target-agenda-pill"><strong>▣ Tandarts - Emma</strong><small>Morgen om 14:30</small></div>',
    '      </div>',
    '    </article>',
    '',
    '    <article class="target-card photo-card">',
    '      <div class="target-type-icon photo">▧</div>',
    '      <img class="target-user-photo" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80" alt="">',
    '      <div class="target-card-body">',
    '        <div class="target-card-top"><p><strong>Esra</strong> heeft 3 foto’s toegevoegd</p><span>3u ···</span></div>',
    '        <div class="target-photo-row"><img src="' + familyPhotoOne + '" alt=""><img src="' + familyPhotoTwo + '" alt=""><img src="' + familyPhotoThree + '" alt=""></div>',
    '        <div class="target-reactions"><span>♥ 8</span><span>○ 2</span></div>',
    '      </div>',
    '    </article>',
    '',
    '    <article class="target-card grocery-card">',
    '      <div class="target-type-icon grocery">▰</div>',
    '      <img class="target-user-photo" src="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=120&q=80" alt="">',
    '      <div class="target-card-body">',
    '        <div class="target-card-top"><p><strong>Boodschappenlijst</strong> is bijgewerkt</p><span>5u ···</span></div>',
    '        <div class="target-grocery-pill">🥛 Melk &nbsp; 🍌 Bananen &nbsp; 🍞 Brood &nbsp; +2 meer</div>',
    '      </div>',
    '    </article>',
    '',
    '    <article class="target-card birthday-card">',
    '      <div class="target-type-icon birthday">♛</div>',
    '      <img class="target-user-photo" src="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=120&q=80" alt="">',
    '      <div class="target-card-body">',
    '        <div class="target-card-top"><p><strong>Verjaardag</strong> morgen</p><span>1d ···</span></div>',
    '        <div class="target-birthday-pill"><img src="https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=80&q=80" alt=""><div><strong>Emma</strong><small>8 jaar! 🎉</small></div></div>',
    '      </div>',
    '    </article>',
    '  </section>',
    '</section>'
  ].join('');
}
