'use strict';
// SHOPPING LISTS v0.423 - Firebase household/private lists are authoritative.
(function(){
  if(window.ShoppingLists)return;
  var VERSION='0.423',COLLECTION='shoppingLists',PREF_KEY='familyapp_active_shopping_list_v1',sharedLists={},privateLists={},activeKey=null,booted=false;
  function store(){return window.FamilyDataStore;}function status(){return store()&&store().status?store().status():{};}function uid(){return status().userId||null;}function ready(){var s=status();return!!(s.userId&&s.familyId);}function now(){return Date.now();}function itemMap(v){return store()&&store().itemMap?store().itemMap(v):{};}function itemArray(v){var m=itemMap(v);return Object.keys(m).map(function(k){return Object.assign({},m[k],{_key:k});}).sort(function(a,b){return Number(b.createdAt||0)-Number(a.createdAt||0);});}function normalizeList(x){if(!x)return x;var y=Object.assign({},x);y.items=itemMap(y.items);return y;}
  function all(){var out=[];Object.keys(sharedLists||{}).forEach(function(id){if(sharedLists[id])out.push({scope:'shared',list:normalizeList(sharedLists[id]),key:'shared:'+id});});Object.keys(privateLists||{}).forEach(function(id){if(privateLists[id])out.push({scope:'private',list:normalizeList(privateLists[id]),key:'private:'+id});});return out.sort(function(a,b){return Number(b.list.updatedAt||0)-Number(a.list.updatedAt||0);});}
  function active(){var rows=all(),f=rows.find(function(x){return x.key===activeKey;})||rows.find(function(x){return x.scope==='shared';})||rows[0]||null;if(f&&f.key!==activeKey){activeKey=f.key;try{localStorage.setItem(PREF_KEY,activeKey);}catch(e){}}return f;}
  function setActive(key,rerender){activeKey=key;try{localStorage.setItem(PREF_KEY,key);}catch(e){}applyActive(rerender!==false);}
  function applyActive(rerender){var row=active();if(!row)return;window.shopData=itemArray(row.list.items);window.shopNextId=Math.max.apply(null,window.shopData.map(function(i){return Number(i.id)||0;}).concat([0]))+1;renderSwitcher();if(rerender&&typeof window.renderShop==='function')window.renderShop();}
  function scopeFn(row,sn,pn){return row.scope==='shared'?store()[sn]:store()[pn];}function pathMutation(row,path,value){var fn=scopeFn(row,'writeSharedPath','writePrivatePath');return fn.call(store(),COLLECTION,[row.list.id].concat(path),value);}function touch(row){return Promise.all([pathMutation(row,['updatedAt'],now()),pathMutation(row,['updatedBy'],uid())]);}function findKey(row,id){var items=itemMap(row.list.items),keys=Object.keys(items);for(var i=0;i<keys.length;i++){if(String(keys[i])===String(id)||String(items[keys[i]].id)===String(id))return keys[i];}return null;}
  function addItem(item){var row=active();if(!row||!store())return Promise.resolve(false);var key=item._key||store().makeId('item'),record=Object.assign({},item,{_key:key,createdAt:item.createdAt||now(),updatedAt:now(),updatedBy:uid()});return pathMutation(row,['items',key],record).then(function(){return touch(row);}).then(function(){return record;});}
  function toggleItem(id){var row=active();if(!row)return Promise.resolve(false);var key=findKey(row,id);if(!key)return Promise.resolve(false);var fn=scopeFn(row,'transactSharedPath','transactPrivatePath');return fn.call(store(),COLLECTION,[row.list.id,'items',key],function(item){if(!item)return item;item.done=!item.done;item.updatedAt=now();item.updatedBy=uid();return item;},null).then(function(r){touch(row);return r;});}
  function deleteItem(id){var row=active();if(!row)return Promise.resolve(false);var key=findKey(row,id);return key?pathMutation(row,['items',key],null).then(function(){return touch(row);}):Promise.resolve(false);}function clearDone(){var row=active();if(!row)return Promise.resolve(false);var items=itemMap(row.list.items),jobs=[];Object.keys(items).forEach(function(k){if(items[k]&&items[k].done)jobs.push(pathMutation(row,['items',k],null));});return Promise.all(jobs).then(function(){return touch(row);});}
  function esc(s){var d=document.createElement('div');d.textContent=String(s||'');return d.innerHTML;}function ensureStyles(){if(document.getElementById('shopping-lists-v1-style'))return;var st=document.createElement('style');st.id='shopping-lists-v1-style';st.textContent='.shopping-listbar{margin:0 16px 12px;display:flex;gap:9px;align-items:center}.shopping-listpick{min-width:0;flex:1;border:1px solid var(--c-border);background:var(--c-surface);border-radius:16px;padding:10px 12px;display:flex;align-items:center;gap:9px}.shopping-listpick .sl-copy{min-width:0;flex:1;text-align:left}.shopping-listpick b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.shopping-list-add{width:43px;height:43px;border:0;border-radius:15px;background:var(--c-primary);color:#fff;font-size:23px}.shopping-list-option{width:100%;border:1px solid var(--c-border);background:var(--c-surface);border-radius:16px;padding:11px 12px;margin:7px 0;display:flex;align-items:center;gap:10px;text-align:left}.shopping-list-option.active{border-color:var(--c-primary)}';document.head.appendChild(st);}function ensureBar(){var screen=document.getElementById('screen-shop'),header=screen&&screen.querySelector('.list-header');if(!header)return null;var bar=document.getElementById('shopping-listbar');if(!bar){bar=document.createElement('div');bar.id='shopping-listbar';bar.className='shopping-listbar';header.insertAdjacentElement('afterend',bar);}return bar;}
  function renderSwitcher(){ensureStyles();var bar=ensureBar(),row=active();if(!bar||!row)return;var count=itemArray(row.list.items).filter(function(i){return!i.done;}).length;bar.innerHTML='<button class="shopping-listpick" id="shopping-list-pick"><span>'+(row.list.icon||'🛒')+'</span><span class="sl-copy"><b>'+esc(row.list.name||'Winkellijst')+'</b><small>'+(row.scope==='private'?'🔒 Privé':'👨‍👩‍👧 Gezin · live')+' · '+count+' te kopen</small></span><span>⌄</span></button><button class="shopping-list-add" id="shopping-list-add">+</button>';document.getElementById('shopping-list-pick').onclick=openPicker;document.getElementById('shopping-list-add').onclick=openCreate;}
  function openPicker(){if(!window.BottomSheet)return;var html=all().map(function(r){return'<button class="shopping-list-option '+(r.key===activeKey?'active':'')+'" data-list-key="'+r.key+'"><span>'+esc(r.list.icon||'🛒')+'</span><span style="flex:1"><b>'+esc(r.list.name)+'</b><small>'+(r.scope==='private'?'🔒 Alleen ik':'👨‍👩‍👧 Gezin · live')+'</small></span></button>';}).join('');BottomSheet.open({title:'Winkellijst kiezen',html:html,onOpen:function(ctx){ctx.modal.querySelectorAll('[data-list-key]').forEach(function(b){b.onclick=function(){setActive(b.getAttribute('data-list-key'),true);ctx.close();};});},actions:[{label:'Sluiten'}]});}
  function createList(o){var scope=o.visibility==='private'?'private':'shared',id=store().makeId('list'),list={id:id,name:o.name,icon:o.icon||'🛒',visibility:scope==='private'?'private':'household',ownerUid:uid(),createdBy:uid(),createdAt:now(),updatedAt:now(),items:{}},fn=scope==='shared'?store().writeSharedRecord:store().writePrivateRecord;return fn.call(store(),COLLECTION,id,list).then(function(){setActive(scope+':'+id,true);return list;});}
  function openCreate(){if(!window.BottomSheet)return;var html='<div class="fam-modal-field"><label>Naam</label><input id="sl-name" placeholder="bijv. IKEA of Weekboodschappen"></div><div class="fam-modal-field"><label>Zichtbaarheid</label><select id="sl-privacy"><option value="household">Gezin</option><option value="private">Alleen ik</option></select></div>';BottomSheet.open({title:'Nieuwe winkellijst',html:html,actions:[{label:'Annuleren'},{label:'Lijst maken',primary:true,onClick:function(ctx){var n=ctx.modal.querySelector('#sl-name').value.trim();if(!n)return false;createList({name:n,visibility:ctx.modal.querySelector('#sl-privacy').value});}}]});}
  function onData(scope,value){if(scope==='shared')sharedLists=value||{};else privateLists=value||{};applyActive(window._currentScreen==='shop');}
  function ensureDefault(){return store().migrateLegacyShopping().then(function(){return Promise.all([store().readShared(COLLECTION,{}),store().readPrivate(COLLECTION,{})]);}).then(function(v){sharedLists=v[0]||{};privateLists=v[1]||{};if(!Object.keys(sharedLists).length&&!Object.keys(privateLists).length){var list=store().defaultShoppingList(Array.isArray(window.shopData)?window.shopData:[]);sharedLists[list.id]=list;return store().writeSharedRecord(COLLECTION,list.id,list);}});}
  function boot(){if(booted||!store()||!ready())return false;booted=true;try{activeKey=localStorage.getItem(PREF_KEY)||null;}catch(e){}ensureDefault().then(function(){store().subscribeShared(COLLECTION,function(v){onData('shared',v);},{});store().subscribePrivate(COLLECTION,function(v){onData('private',v);},{});applyActive(true);});return true;}
  function bootWhenReady(){if(boot())return;var tries=0,t=setInterval(function(){tries++;if(boot()||tries>300)clearInterval(t);},100);}
  window.ShoppingLists={version:VERSION,boot:boot,all:all,active:active,setActive:setActive,create:createList,addItem:addItem,toggleItem:toggleItem,deleteItem:deleteItem,clearDone:clearDone,openPicker:openPicker,openCreate:openCreate,refresh:function(){applyActive(true);}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootWhenReady);else bootWhenReady();
})();
