'use strict';
// SHOPPING LISTS v0.500 - context-authoritative UID/household scoped realtime lists.
(function(){
  if(window.ShoppingLists)return;
  var VERSION='0.500',COLLECTION='shoppingLists',PREF_PREFIX='familyapp_active_shopping_list_v2:',sharedLists={},privateLists={},activeKey=null,booted=false,boundToken=null,sharedUnsub=null,privateUnsub=null,originalRender=null,originalToggle=null,originalDelete=null,originalReset=null;
  function store(){return window.FamilyDataStore||null;}function ctx(){return window.HouseholdContext||null;}function now(){return Date.now();}
  function captureReady(){var c=ctx();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function uid(){try{return captureReady().uid;}catch(e){return null;}}function ready(){try{return !!captureReady();}catch(e){return false;}}function same(token){return !!(token&&ctx()&&ctx().isCurrent(token));}
  function prefKey(token){return PREF_PREFIX+token.uid+':'+token.householdId;}function itemMap(v){return store()&&store().itemMap?store().itemMap(v):{};}function itemArray(v){var m=itemMap(v);return Object.keys(m).map(function(k){return Object.assign({},m[k],{_key:k});}).sort(function(a,b){return Number(b.createdAt||0)-Number(a.createdAt||0);});}function normalizeList(x){if(!x)return x;var y=Object.assign({},x);y.items=itemMap(y.items);return y;}
  function all(){var out=[];Object.keys(sharedLists||{}).forEach(function(id){if(sharedLists[id])out.push({scope:'shared',list:normalizeList(sharedLists[id]),key:'shared:'+id});});Object.keys(privateLists||{}).forEach(function(id){if(privateLists[id])out.push({scope:'private',list:normalizeList(privateLists[id]),key:'private:'+id});});return out.sort(function(a,b){return Number(b.list.updatedAt||0)-Number(a.list.updatedAt||0);});}
  function active(){var rows=all(),f=rows.find(function(x){return x.key===activeKey;})||rows.find(function(x){return x.scope==='shared';})||rows[0]||null;if(f&&f.key!==activeKey){activeKey=f.key;try{if(boundToken)localStorage.setItem(prefKey(boundToken),activeKey);}catch(e){}}return f;}
  function setActive(key,rerender){activeKey=key;try{if(boundToken)localStorage.setItem(prefKey(boundToken),key);}catch(e){}applyActive(rerender!==false);}
  function clearProjection(){sharedLists={};privateLists={};activeKey=null;window.shopData=[];window.shopNextId=1;try{if(typeof originalRender==='function'&&window._currentScreen==='shop')originalRender();}catch(e){}}
  function applyActive(rerender){var row=active();if(!row){window.shopData=[];window.shopNextId=1;if(rerender&&typeof originalRender==='function')originalRender();return;}window.shopData=itemArray(row.list.items);window.shopNextId=Math.max.apply(null,window.shopData.map(function(i){return Number(i.id)||0;}).concat([0]))+1;renderSwitcher();if(rerender&&typeof originalRender==='function')originalRender();}
  function assertToken(token){if(!same(token)){var e=new Error('SHOPPING_CONTEXT_CHANGED');e.code='SHOPPING_CONTEXT_CHANGED';throw e;}return token;}
  function scopeFn(row,sn,pn){return row.scope==='shared'?store()[sn]:store()[pn];}function pathMutation(row,path,value,token){assertToken(token);var fn=scopeFn(row,'writeSharedPath','writePrivatePath');return fn.call(store(),COLLECTION,[row.list.id].concat(path),value).then(function(r){assertToken(token);return r;});}function touch(row,token){return Promise.all([pathMutation(row,['updatedAt'],now(),token),pathMutation(row,['updatedBy'],token.uid,token)]);}
  function findKey(row,id){var items=itemMap(row.list.items),candidate=String(id==null?'':id);if(candidate&&items[candidate])return candidate;var matches=Object.keys(items).filter(function(k){return items[k]&&String(items[k].id)===candidate;});return matches.length===1?matches[0]:null;}
  function addItem(item){var token=captureReady(),row=active();if(!row||!store())return Promise.resolve(false);var key=item._key||store().makeId('item'),record=Object.assign({},item,{_key:key,createdAt:item.createdAt||now(),createdBy:item.createdBy||token.uid,updatedAt:now(),updatedBy:token.uid});return pathMutation(row,['items',key],record,token).then(function(){return touch(row,token);}).then(function(){assertToken(token);return record;});}
  function toggleItem(id){var token=captureReady(),row=active();if(!row)return Promise.resolve(false);var key=findKey(row,id);if(!key)return Promise.resolve(false);var fn=scopeFn(row,'transactSharedPath','transactPrivatePath');assertToken(token);return fn.call(store(),COLLECTION,[row.list.id,'items',key],function(item){assertToken(token);if(!item)return item;item.done=!item.done;item.updatedAt=now();item.updatedBy=token.uid;return item;},null).then(function(r){assertToken(token);return touch(row,token).then(function(){return r;});});}
  function deleteItem(id){var token=captureReady(),row=active();if(!row)return Promise.resolve(false);var key=findKey(row,id);return key?pathMutation(row,['items',key],null,token).then(function(){return touch(row,token);}):Promise.resolve(false);}function clearDone(){var token=captureReady(),row=active();if(!row)return Promise.resolve(false);var items=itemMap(row.list.items),jobs=[];Object.keys(items).forEach(function(k){if(items[k]&&items[k].done)jobs.push(pathMutation(row,['items',k],null,token));});return Promise.all(jobs).then(function(){return touch(row,token);});}
  function esc(s){var d=document.createElement('div');d.textContent=String(s||'');return d.innerHTML;}function listScopeIcon(scope){return scope==='private'?'🔒':'👨‍👩‍👧';}
  function ensureStyles(){if(document.getElementById('shopping-lists-v1-style'))return;var st=document.createElement('style');st.id='shopping-lists-v1-style';st.textContent='.shopping-listbar{margin:0 16px 12px;display:flex;align-items:center}.shopping-listpick{min-width:0;flex:1;border:1px solid var(--c-border);background:var(--c-surface);border-radius:16px;padding:10px 12px;display:flex;align-items:center;gap:9px}.shopping-listpick .sl-icon{width:34px;height:34px;border-radius:11px;background:var(--c-surface2);display:grid;place-items:center;flex:0 0 auto}.shopping-listpick .sl-copy{min-width:0;flex:1;text-align:left}.shopping-listpick b,.shopping-listpick small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.shopping-list-option{width:100%;border:1px solid var(--c-border);background:var(--c-surface);border-radius:16px;padding:11px 12px;margin:7px 0;display:flex;align-items:center;gap:10px;text-align:left}.shopping-list-option.active{border-color:var(--c-primary)}.shopping-list-create{width:100%;border:0;background:transparent;color:var(--c-primary);font-weight:700;padding:13px 10px;margin-top:4px;text-align:center}';document.head.appendChild(st);}
  function ensureBar(){var screen=document.getElementById('screen-shop'),header=screen&&screen.querySelector('.list-header');if(!header)return null;var bar=document.getElementById('shopping-listbar');if(!bar){bar=document.createElement('div');bar.id='shopping-listbar';bar.className='shopping-listbar';header.insertAdjacentElement('afterend',bar);}return bar;}
  function renderSwitcher(){ensureStyles();var bar=ensureBar(),row=active();if(!bar)return;if(!row){bar.innerHTML='';return;}var count=itemArray(row.list.items).filter(function(i){return!i.done;}).length;bar.innerHTML='<button class="shopping-listpick" id="shopping-list-pick" aria-label="Winkellijst kiezen"><span class="sl-icon">'+listScopeIcon(row.scope)+'</span><span class="sl-copy"><b>'+esc(row.list.name||'Winkellijst')+'</b><small>'+(row.scope==='private'?'Privé':'Gezin · live')+' · '+count+' te kopen</small></span><span>⌄</span></button>';var pick=document.getElementById('shopping-list-pick');if(pick)pick.onclick=openPicker;}
  function openPicker(){if(!window.BottomSheet)return;var html=all().map(function(r){return'<button class="shopping-list-option '+(r.key===activeKey?'active':'')+'" data-list-key="'+r.key+'"><span>'+esc(r.list.icon||'🛒')+'</span><span style="flex:1"><b>'+esc(r.list.name)+'</b><small>'+(r.scope==='private'?'🔒 Alleen ik':'👨‍👩‍👧 Gezin · live')+'</small></span></button>';}).join('')+'<button class="shopping-list-create" id="shopping-list-create">＋ Nieuwe lijst</button>';BottomSheet.open({title:'Winkellijst kiezen',html:html,onOpen:function(c){c.modal.querySelectorAll('[data-list-key]').forEach(function(b){b.onclick=function(){setActive(b.getAttribute('data-list-key'),true);c.close();};});var create=c.modal.querySelector('#shopping-list-create');if(create)create.onclick=function(){c.close();setTimeout(openCreate,180);};},actions:[{label:'Sluiten'}]});}
  function createList(o){var token=captureReady(),scope=o.visibility==='private'?'private':'shared',id=store().makeId('list'),list={id:id,name:o.name,icon:o.icon||'🛒',visibility:scope==='private'?'private':'household',ownerUid:token.uid,createdBy:token.uid,createdAt:now(),updatedAt:now(),updatedBy:token.uid,items:{}},fn=scope==='shared'?store().writeSharedRecord:store().writePrivateRecord;assertToken(token);return fn.call(store(),COLLECTION,id,list).then(function(){assertToken(token);setActive(scope+':'+id,true);return list;});}
  function openCreate(){if(!window.BottomSheet)return;var html='<div class="fam-modal-field"><label>Naam</label><input id="sl-name" placeholder="bijv. IKEA of Weekboodschappen"></div><div class="fam-modal-field"><label>Zichtbaarheid</label><select id="sl-privacy"><option value="household">Gezin</option><option value="private">Alleen ik</option></select></div>';BottomSheet.open({title:'Nieuwe winkellijst',html:html,actions:[{label:'Annuleren'},{label:'Lijst maken',primary:true,onClick:function(c){var n=c.modal.querySelector('#sl-name').value.trim();if(!n)return false;createList({name:n,visibility:c.modal.querySelector('#sl-privacy').value});}}]});}
  function installLegacyBridges(){if(!originalRender&&typeof window.renderShop==='function')originalRender=window.renderShop;if(!originalToggle&&typeof window.toggleShop==='function')originalToggle=window.toggleShop;if(!originalDelete&&typeof window.deleteShop==='function')originalDelete=window.deleteShop;if(!originalReset&&typeof window.resetShop==='function')originalReset=window.resetShop;if(originalRender)window.renderShop=function(){applyActive(false);var r=originalRender.apply(this,arguments);renderSwitcher();return r;};if(originalToggle)window.toggleShop=function(id){toggleItem(id).catch(function(e){console.warn('[ShoppingLists] toggle failed',e);});return false;};if(originalDelete)window.deleteShop=function(id){deleteItem(id).catch(function(e){console.warn('[ShoppingLists] delete failed',e);});return false;};if(originalReset)window.resetShop=function(){clearDone().catch(function(e){console.warn('[ShoppingLists] clear failed',e);});return false;};}
  function onData(scope,value,token){if(!same(token))return;if(scope==='shared')sharedLists=value||{};else privateLists=value||{};applyActive(window._currentScreen==='shop');}
  function ensureDefault(token){return store().migrateLegacyShopping().then(function(){assertToken(token);return Promise.all([store().readShared(COLLECTION,{}),store().readPrivate(COLLECTION,{})]);}).then(function(v){assertToken(token);sharedLists=v[0]||{};privateLists=v[1]||{};if(!Object.keys(sharedLists).length&&!Object.keys(privateLists).length){var list=store().defaultShoppingList(Array.isArray(window.shopData)?window.shopData:[]);sharedLists[list.id]=list;return store().writeSharedRecord(COLLECTION,list.id,list);}});}
  function stop(){if(sharedUnsub)try{sharedUnsub();}catch(e){}if(privateUnsub)try{privateUnsub();}catch(e){}sharedUnsub=null;privateUnsub=null;boundToken=null;booted=false;clearProjection();}
  function boot(){var token;try{token=captureReady();}catch(e){return false;}if(booted&&boundToken&&same(boundToken))return true;stop();booted=true;boundToken=token;installLegacyBridges();try{activeKey=localStorage.getItem(prefKey(token))||null;}catch(e){}ensureDefault(token).then(function(){assertToken(token);sharedUnsub=store().subscribeShared(COLLECTION,function(v){onData('shared',v,token);},{});privateUnsub=store().subscribePrivate(COLLECTION,function(v){onData('private',v,token);},{});applyActive(true);}).catch(function(e){if(e&&e.code==='SHOPPING_CONTEXT_CHANGED')return;console.warn('[ShoppingLists] boot failed',e);});return true;}
  function rebind(){stop();boot();}
  function bootWhenReady(){if(boot())return;var tries=0,t=setInterval(function(){tries++;if(boot()||tries>300)clearInterval(t);},100);}
  window.ShoppingLists={version:VERSION,boot:boot,stop:stop,rebind:rebind,all:all,active:active,setActive:setActive,create:createList,addItem:addItem,toggleItem:toggleItem,deleteItem:deleteItem,clearDone:clearDone,openPicker:openPicker,openCreate:openCreate,status:function(){return{version:VERSION,bound:booted,context:boundToken?Object.assign({},boundToken):null,shared:Object.keys(sharedLists).length,private:Object.keys(privateLists).length,activeKey:activeKey};}};
  window.addEventListener('familyapp:household-context-changed',rebind);window.addEventListener('familyapp:session:cleared',stop);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootWhenReady);else bootWhenReady();
})();
