'use strict';
// SHOPPING LISTS v0.425 - UID/household scoped realtime lists.
(function(){
  if(window.ShoppingLists)return;
  var VERSION='0.425',COLLECTION='shoppingLists',PREF_KEY='familyapp_active_shopping_list_v1',sharedLists={},privateLists={},activeKey=null,booted=false,originalRender=null,originalToggle=null,originalDelete=null,originalReset=null;
  function store(){return window.FamilyDataStore;}function status(){return store()&&store().status?store().status():{};}function uid(){return status().userId||null;}function ready(){var s=status();return !!(s.userId&&s.familyId);}function now(){return Date.now();}function itemMap(v){return store()&&store().itemMap?store().itemMap(v):{};}function itemArray(v){var m=itemMap(v);return Object.keys(m).map(function(k){return Object.assign({},m[k],{_key:k});}).sort(function(a,b){return Number(b.createdAt||0)-Number(a.createdAt||0);});}function normalizeList(x){if(!x)return x;var y=Object.assign({},x);y.items=itemMap(y.items);return y;}
  function all(){var out=[];Object.keys(sharedLists||{}).forEach(function(id){if(sharedLists[id])out.push({scope:'shared',list:normalizeList(sharedLists[id]),key:'shared:'+id});});Object.keys(privateLists||{}).forEach(function(id){if(privateLists[id])out.push({scope:'private',list:normalizeList(privateLists[id]),key:'private:'+id});});return out.sort(function(a,b){return Number(b.list.updatedAt||0)-Number(a.list.updatedAt||0);});}
  function active(){var rows=all(),f=rows.find(function(x){return x.key===activeKey;})||rows.find(function(x){return x.scope==='shared';})||rows[0]||null;if(f&&f.key!==activeKey){activeKey=f.key;try{localStorage.setItem(PREF_KEY,activeKey);}catch(e){}}return f;}
  function setActive(key,rerender){activeKey=key;try{localStorage.setItem(PREF_KEY,key);}catch(e){}applyActive(rerender!==false);}
  function applyActive(rerender){var row=active();if(!row)return;window.shopData=itemArray(row.list.items);window.shopNextId=Math.max.apply(null,window.shopData.map(function(i){return Number(i.id)||0;}).concat([0]))+1;renderSwitcher();if(rerender&&typeof originalRender==='function')originalRender();}
  function scopeFn(row,sn,pn){return row.scope==='shared'?store()[sn]:store()[pn];}function pathMutation(row,path,value){var fn=scopeFn(row,'writeSharedPath','writePrivatePath');return fn.call(store(),COLLECTION,[row.list.id].concat(path),value);}function touch(row){return Promise.all([pathMutation(row,['updatedAt'],now()),pathMutation(row,['updatedBy'],uid())]);}
  function findKey(row,id){
    var items=itemMap(row.list.items),candidate=String(id==null?'':id);
    if(candidate&&items[candidate])return candidate;
    var matches=Object.keys(items).filter(function(k){return items[k]&&String(items[k].id)===candidate;});
    return matches.length===1?matches[0]:null;
  }
  function addItem(item){var row=active();if(!row||!store())return Promise.resolve(false);var key=item._key||store().makeId('item'),record=Object.assign({},item,{_key:key,createdAt:item.createdAt||now(),updatedAt:now(),updatedBy:uid()});return pathMutation(row,['items',key],record).then(function(){return touch(row);}).then(function(){return record;});}
  function toggleItem(id){var row=active();if(!row)return Promise.resolve(false);var key=findKey(row,id);if(!key)return Promise.resolve(false);var fn=scopeFn(row,'transactSharedPath','transactPrivatePath');return fn.call(store(),COLLECTION,[row.list.id,'items',key],function(item){if(!item)return item;item.done=!item.done;item.updatedAt=now();item.updatedBy=uid();return item;},null).then(function(r){touch(row);return r;});}
  function deleteItem(id){var row=active();if(!row)return Promise.resolve(false);var key=findKey(row,id);return key?pathMutation(row,['items',key],null).then(function(){return touch(row);}):Promise.resolve(false);}function clearDone(){var row=active();if(!row)return Promise.resolve(false);var items=itemMap(row.list.items),jobs=[];Object.keys(items).forEach(function(k){if(items[k]&&items[k].done)jobs.push(pathMutation(row,['items',k],null));});return Promise.all(jobs).then(function(){return touch(row);});}
  function esc(s){var d=document.createElement('div');d.textContent=String(s||'');return d.innerHTML;}
  function listScopeIcon(scope){return scope==='private'?'<svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="5" y="10.5" width="14" height="9" rx="2"></rect><path d="M8 10.5V7a4 4 0 0 1 8 0v3.5"></path></svg>':'<svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M17 20v-1a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v1"></path><circle cx="12" cy="7" r="3.2"></circle><path d="M21 20v-1a3.5 3.5 0 0 0-2.5-3.36"></path><path d="M15.5 3.13a3.2 3.2 0 0 1 0 6.2"></path></svg>';}
  function ensureStyles(){if(document.getElementById('shopping-lists-v1-style'))return;var st=document.createElement('style');st.id='shopping-lists-v1-style';st.textContent='.shopping-listbar{margin:0 16px 12px;display:flex;align-items:center}.shopping-listpick{min-width:0;flex:1;border:1px solid var(--c-border);background:var(--c-surface);border-radius:16px;padding:10px 12px;display:flex;align-items:center;gap:9px}.shopping-listpick .sl-icon{width:34px;height:34px;border-radius:11px;background:var(--c-surface2);display:grid;place-items:center;flex:0 0 auto}.shopping-listpick .sl-copy{min-width:0;flex:1;text-align:left}.shopping-listpick b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.shopping-listpick small{display:block;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.shopping-listpick .sl-chevron{font-size:17px;line-height:1;color:var(--c-muted);padding-left:4px}.shopping-list-option{width:100%;border:1px solid var(--c-border);background:var(--c-surface);border-radius:16px;padding:11px 12px;margin:7px 0;display:flex;align-items:center;gap:10px;text-align:left}.shopping-list-option.active{border-color:var(--c-primary)}.shopping-list-create{width:100%;border:0;background:transparent;color:var(--c-primary);font-weight:700;padding:13px 10px;margin-top:4px;text-align:center}@media(max-width:600px){.shopping-listbar{margin:0 16px 8px}.shopping-listpick{min-height:54px;border-radius:16px;padding:6px 10px;gap:8px}.shopping-listpick .sl-icon{width:32px;height:32px}.shopping-listpick b{font-size:15px}.shopping-listpick small{font-size:12px;color:var(--c-muted)}#screen-shop .shop-col+.shop-col{border-top-color:rgba(75,132,56,.06)}#screen-shop .shop-col:last-child .shop-col-head{background:rgba(75,132,56,.055)}#screen-shop .shop-del{color:rgba(86,96,112,.42)}#screen-shop .check-circle{transform:scale(.92)}}';document.head.appendChild(st);}
  function ensureBar(){var screen=document.getElementById('screen-shop'),header=screen&&screen.querySelector('.list-header');if(!header)return null;var bar=document.getElementById('shopping-listbar');if(!bar){bar=document.createElement('div');bar.id='shopping-listbar';bar.className='shopping-listbar';header.insertAdjacentElement('afterend',bar);}return bar;}
  function renderSwitcher(){ensureStyles();var bar=ensureBar(),row=active();if(!bar||!row)return;var count=itemArray(row.list.items).filter(function(i){return!i.done;}).length;bar.innerHTML='<button class="shopping-listpick" id="shopping-list-pick" aria-label="Winkellijst kiezen"><span class="sl-icon">'+listScopeIcon(row.scope)+'</span><span class="sl-copy"><b>'+esc(row.list.name||'Winkellijst')+'</b><small>'+(row.scope==='private'?'🔒 Privé':'👨‍👩‍👧 Gezin · live')+' · '+count+' te kopen</small></span><span class="sl-chevron">⌄</span></button>';document.getElementById('shopping-list-pick').onclick=openPicker;}
  function openPicker(){if(!window.BottomSheet)return;var html=all().map(function(r){return'<button class="shopping-list-option '+(r.key===activeKey?'active':'')+'" data-list-key="'+r.key+'"><span>'+esc(r.list.icon||'🛒')+'</span><span style="flex:1"><b>'+esc(r.list.name)+'</b><small>'+(r.scope==='private'?'🔒 Alleen ik':'👨‍👩‍👧 Gezin · live')+'</small></span></button>';}).join('')+'<button class="shopping-list-create" id="shopping-list-create">＋ Nieuwe lijst</button>';BottomSheet.open({title:'Winkellijst kiezen',html:html,onOpen:function(ctx){ctx.modal.querySelectorAll('[data-list-key]').forEach(function(b){b.onclick=function(){setActive(b.getAttribute('data-list-key'),true);ctx.close();};});var create=ctx.modal.querySelector('#shopping-list-create');if(create)create.onclick=function(){ctx.close();setTimeout(openCreate,180);};},actions:[{label:'Sluiten'}]});}
  function createList(o){var scope=o.visibility==='private'?'private':'shared',id=store().makeId('list'),list={id:id,name:o.name,icon:o.icon||'🛒',visibility:scope==='private'?'private':'household',ownerUid:uid(),createdBy:uid(),createdAt:now(),updatedAt:now(),items:{}},fn=scope==='shared'?store().writeSharedRecord:store().writePrivateRecord;return fn.call(store(),COLLECTION,id,list).then(function(){setActive(scope+':'+id,true);return list;});}
  function openCreate(){if(!window.BottomSheet)return;var html='<div class="fam-modal-field"><label>Naam</label><input id="sl-name" placeholder="bijv. IKEA of Weekboodschappen"></div><div class="fam-modal-field"><label>Zichtbaarheid</label><select id="sl-privacy"><option value="household">Gezin</option><option value="private">Alleen ik</option></select></div>';BottomSheet.open({title:'Nieuwe winkellijst',html:html,actions:[{label:'Annuleren'},{label:'Lijst maken',primary:true,onClick:function(ctx){var n=ctx.modal.querySelector('#sl-name').value.trim();if(!n)return false;createList({name:n,visibility:ctx.modal.querySelector('#sl-privacy').value});}}]});}
  function installLegacyBridges(){if(!originalRender&&typeof window.renderShop==='function')originalRender=window.renderShop;if(!originalToggle&&typeof window.toggleShop==='function')originalToggle=window.toggleShop;if(!originalDelete&&typeof window.deleteShop==='function')originalDelete=window.deleteShop;if(!originalReset&&typeof window.resetShop==='function')originalReset=window.resetShop;if(originalRender)window.renderShop=function(){applyActive(false);var r=originalRender.apply(this,arguments);renderSwitcher();return r;};if(originalToggle)window.toggleShop=function(id){toggleItem(id);return false;};if(originalDelete)window.deleteShop=function(id){deleteItem(id);return false;};if(originalReset)window.resetShop=function(){clearDone();return false;};}
  function onData(scope,value){if(scope==='shared')sharedLists=value||{};else privateLists=value||{};applyActive(window._currentScreen==='shop');}
  function ensureDefault(){return store().migrateLegacyShopping().then(function(){return Promise.all([store().readShared(COLLECTION,{}),store().readPrivate(COLLECTION,{})]);}).then(function(v){sharedLists=v[0]||{};privateLists=v[1]||{};if(!Object.keys(sharedLists).length&&!Object.keys(privateLists).length){var list=store().defaultShoppingList(Array.isArray(window.shopData)?window.shopData:[]);sharedLists[list.id]=list;return store().writeSharedRecord(COLLECTION,list.id,list);}});}
  function boot(){if(booted||!store()||!ready())return false;booted=true;installLegacyBridges();try{activeKey=localStorage.getItem(PREF_KEY)||null;}catch(e){}ensureDefault().then(function(){store().subscribeShared(COLLECTION,function(v){onData('shared',v);},{});store().subscribePrivate(COLLECTION,function(v){onData('private',v);},{});applyActive(true);});return true;}
  function bootWhenReady(){if(boot())return;var tries=0,t=setInterval(function(){tries++;if(boot()||tries>300)clearInterval(t);},100);}
  window.ShoppingLists={version:VERSION,boot:boot,all:all,active:active,setActive:setActive,create:createList,addItem:addItem,toggleItem:toggleItem,deleteItem:deleteItem,clearDone:clearDone,openPicker:openPicker,openCreate:openCreate};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootWhenReady);else bootWhenReady();
})();