'use strict';
// ============================================================
// MEAL PLAN STORE v2.0
// HouseholdContext-authoritative shared meal planning.
// Firebase is authoritative; window.mealPlanData is compatibility projection.
// ============================================================
(function(){
  if(window.MealPlanStore&&window.MealPlanStore.version==='2.0.0')return;
  var VERSION='2.0.0',COLLECTION='mealPlans',LEGACY_KEY='familyapp_food_meal_plan_v001';
  var records={},listeners=[],unsub=null,migratedToken=null,boundToken=null,booting=null;
  function store(){return window.FamilyDataStore||null;}function hc(){return window.HouseholdContext||null;}function now(){return Date.now();}
  function captureReady(){var c=hc();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function same(t){return!!(t&&hc()&&hc().isCurrent(t));}function assertToken(t){if(!same(t)){var e=new Error('MEAL_PLAN_CONTEXT_CHANGED');e.code='MEAL_PLAN_CONTEXT_CHANGED';throw e;}return t;}
  function parse(v,f){try{return v?JSON.parse(v):f;}catch(e){return f;}}
  function normalize(x,id,token){x=x||{};token=token||boundToken||captureReady();var mealType=String(x.mealType||x.slot||'dinner').toLowerCase();if(mealType!=='breakfast'&&mealType!=='lunch'&&mealType!=='dinner')mealType='dinner';return{id:String(x.id||id||''),date:String(x.date||''),mealType:mealType,recipeId:x.recipeId==null?null:String(x.recipeId),title:String(x.title||'Maaltijd'),persons:parseInt(x.persons,10)||4,notes:String(x.notes||''),emoji:String(x.emoji||'🍽️'),householdId:token.householdId,createdBy:x.createdBy||x.who||token.uid,createdAt:Number(x.createdAt)||now(),updatedBy:x.updatedBy||x.createdBy||token.uid,updatedAt:Number(x.updatedAt)||Number(x.createdAt)||now()};}
  function list(){var token=boundToken||captureReady();return Object.keys(records).map(function(k){return normalize(records[k],k,token);}).filter(function(x){return x.date;}).sort(function(a,b){var d=String(a.date).localeCompare(String(b.date));return d||String(a.mealType).localeCompare(String(b.mealType));});}
  function mirror(){window.mealPlanData=boundToken&&same(boundToken)?list():[];window.mealPlanNextId=window.mealPlanData.length+1;return window.mealPlanData;}
  function emit(token){if(token&&!same(token))return;var rows=mirror();listeners.slice().forEach(function(fn){try{fn(rows.slice());}catch(e){}});try{window.dispatchEvent(new CustomEvent('familyapp:meals:changed',{detail:{source:'MealPlanStore',userId:token&&token.uid||null,householdId:token&&token.householdId||null,rows:rows.slice()}}));}catch(e){}}
  function get(id){var token=boundToken||captureReady();return records[String(id)]?normalize(records[String(id)],String(id),token):null;}
  function subscribe(fn){if(typeof fn!=='function')return function(){};listeners.push(fn);Promise.resolve().then(function(){try{fn(boundToken&&same(boundToken)?list():[]);}catch(e){}});return function(){listeners=listeners.filter(function(x){return x!==fn;});};}
  function stop(){if(unsub)try{unsub();}catch(e){}unsub=null;boundToken=null;booting=null;records={};window.mealPlanData=[];window.mealPlanNextId=1;emit(null);}
  function create(input){var s=store(),token=captureReady();if(!s)return Promise.reject(new Error('Maaltijdopslag niet beschikbaar'));var id=s.makeId('meal'),t=now(),record=normalize(Object.assign({},input,{id:id,createdBy:token.uid,createdAt:t,updatedBy:token.uid,updatedAt:t}),id,token);assertToken(token);return s.writeSharedRecord(COLLECTION,id,record).then(function(result){assertToken(token);records[id]=record;emit(token);return{record:record,result:result};});}
  function upsert(input){var s=store(),token=captureReady(),id=String(input&&input.id||'');if(!s||!id)return Promise.reject(new Error('Maaltijd ontbreekt'));var prev=records[id]?normalize(records[id],id,token):{},record=normalize(Object.assign({},prev,input,{id:id,createdBy:prev.createdBy||token.uid,createdAt:prev.createdAt||now(),updatedBy:token.uid,updatedAt:now()}),id,token);assertToken(token);return s.writeSharedRecord(COLLECTION,id,record).then(function(result){assertToken(token);records[id]=record;emit(token);return{record:record,result:result};});}
  function remove(id){var s=store(),token=captureReady(),key=String(id||'');if(!s||!key)return Promise.reject(new Error('Maaltijd ontbreekt'));assertToken(token);return s.writeSharedRecord(COLLECTION,key,null).then(function(result){assertToken(token);delete records[key];emit(token);return result;});}
  function removeSlot(date,mealType){var row=list().find(function(x){return x.date===date&&x.mealType===mealType;});return row?remove(row.id):Promise.resolve(false);}
  function replaceSlot(input){var date=String(input&&input.date||''),mealType=String(input&&input.mealType||'dinner'),existing=list().find(function(x){return x.date===date&&x.mealType===mealType;});return existing?upsert(Object.assign({},input,{id:existing.id})):create(input);}
  function migrateLegacy(token){var key=token.uid+':'+token.householdId;if(migratedToken===key||!store())return Promise.resolve(false);migratedToken=key;return store().readShared(COLLECTION,{}).then(function(existing){assertToken(token);if(existing&&Object.keys(existing).length)return false;var legacy=parse(localStorage.getItem(LEGACY_KEY),[]);if(!Array.isArray(legacy)||!legacy.length)return false;var jobs=legacy.filter(function(x){return x&&x.date;}).map(function(x){var id=store().makeId('meal'),record=normalize(Object.assign({},x,{id:id,createdBy:x.createdBy||token.uid,updatedBy:token.uid}),id,token);return store().writeSharedRecord(COLLECTION,id,record);});return Promise.all(jobs).then(function(){assertToken(token);return jobs.length>0;});});}
  function boot(){var token;try{token=captureReady();}catch(e){return Promise.resolve(status());}if(boundToken&&same(boundToken)&&unsub)return Promise.resolve(status());if(booting&&boundToken&&same(boundToken))return booting;stop();boundToken=token;booting=migrateLegacy(token).then(function(){assertToken(token);unsub=store().subscribeShared(COLLECTION,function(value){if(!same(token))return;records=value&&typeof value==='object'?value:{};emit(token);},{});return status();}).catch(function(err){if(!(err&&err.code==='MEAL_PLAN_CONTEXT_CHANGED'))console.error('[MealPlanStore] boot failed',err);return status();}).then(function(v){if(boundToken===token)booting=null;return v;});return booting;}
  function rebind(){stop();return boot();}
  function status(){return{version:VERSION,ready:!!(boundToken&&same(boundToken)&&unsub),count:boundToken&&same(boundToken)?Object.keys(records).length:0,context:boundToken?Object.assign({},boundToken):null};}
  window.MealPlanStore={version:VERSION,boot:boot,stop:stop,rebind:rebind,list:list,get:get,subscribe:subscribe,create:create,upsert:upsert,remove:remove,removeSlot:removeSlot,replaceSlot:replaceSlot,status:status};
  function start(){var tries=0,t=setInterval(function(){tries++;boot().then(function(){if(status().ready)clearInterval(t);});if(tries>300)clearInterval(t);},100);boot();}
  window.addEventListener('online',boot);window.addEventListener('focus',boot);window.addEventListener('familyapp:household-context-changed',rebind);window.addEventListener('familyapp:session:cleared',stop);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
