'use strict';
(function(){
  if(window.PersonHeroBackgroundPicker)return;
  var VERSION='1.0.0',root=null,activeUid=null,currentPresetId=null,busy=false;
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function ensureRoot(){if(root&&document.body.contains(root))return root;root=document.createElement('div');root.className='phbp-overlay';root.setAttribute('aria-hidden','true');root.innerHTML='<div class="phbp-sheet" role="dialog" aria-modal="true" aria-label="Hero-achtergrond kiezen"><div class="phbp-handle"></div><div class="phbp-head"><div><h2>Achtergrond kiezen</h2><p>Kies een sfeer die bij jou past.</p></div><button type="button" class="phbp-close" data-phbp-close aria-label="Sluiten">×</button></div><div class="phbp-grid" data-phbp-grid></div><div class="phbp-actions"><button type="button" class="phbp-reset" data-phbp-reset>Standaard herstellen</button></div><div class="phbp-note">Alleen jij kunt jouw hero-achtergrond aanpassen.</div></div>';document.body.appendChild(root);bind();return root;}
  function catalog(){return window.HeroBackdropCatalog&&HeroBackdropCatalog.listPresets?HeroBackdropCatalog.listPresets():[];}
  function render(){var r=ensureRoot(),grid=r.querySelector('[data-phbp-grid]');if(!grid)return;grid.innerHTML=catalog().map(function(p){var active=String(p.id)===String(currentPresetId||window.HeroBackdropCatalog&&HeroBackdropCatalog.defaultId||'');return'<button type="button" class="phbp-card'+(active?' is-active':'')+'" data-phbp-preset="'+esc(p.id)+'"><span class="phbp-thumb"><img src="'+esc(p.thumbnailUrl||p.imageUrl)+'" alt=""><i>'+(active?'✓':'')+'</i></span><strong>'+esc(p.label||p.id)+'</strong></button>';}).join('');}
  function setBusy(v){busy=!!v;if(root)root.classList.toggle('is-busy',busy);}
  function close(){if(!root)return;root.classList.remove('is-open');root.setAttribute('aria-hidden','true');activeUid=null;currentPresetId=null;}
  function savePreset(id){if(busy||!activeUid)return;var repo=window.MemberHeroBackgroundRepository;if(!repo||typeof repo.setPreset!=='function')return;setBusy(true);repo.setPreset(activeUid,id).then(function(){currentPresetId=id;render();setTimeout(close,120);}).catch(function(err){console.warn('[HeroBackgroundPicker]',err);alert(err&&err.message||'Achtergrond opslaan is niet gelukt.');}).finally(function(){setBusy(false);});}
  function reset(){if(busy||!activeUid)return;var repo=window.MemberHeroBackgroundRepository;if(!repo||typeof repo.reset!=='function')return;setBusy(true);repo.reset(activeUid).then(function(){currentPresetId=window.HeroBackdropCatalog&&HeroBackdropCatalog.defaultId||null;render();setTimeout(close,120);}).catch(function(err){console.warn('[HeroBackgroundPicker]',err);alert(err&&err.message||'Achtergrond herstellen is niet gelukt.');}).finally(function(){setBusy(false);});}
  function bind(){root.addEventListener('click',function(e){if(e.target===root||e.target.closest('[data-phbp-close]')){close();return;}var preset=e.target.closest('[data-phbp-preset]');if(preset){savePreset(preset.getAttribute('data-phbp-preset'));return;}if(e.target.closest('[data-phbp-reset]'))reset();});}
  function open(uid,config){var repo=window.MemberHeroBackgroundRepository;if(!repo||!repo.canEdit||!repo.canEdit(uid))return false;activeUid=String(uid);currentPresetId=config&&config.type==='preset'&&config.presetId?config.presetId:(window.HeroBackdropCatalog&&HeroBackdropCatalog.defaultId||null);render();var r=ensureRoot();r.classList.add('is-open');r.setAttribute('aria-hidden','false');return true;}
  window.PersonHeroBackgroundPicker={version:VERSION,open:open,close:close};
})();
