'use strict';
// ============================================================
// FAMILYAPP TASKS V3 — DETAIL / CREATE / EDIT
// New DOM and presentation. Canonical TaskSharedData owns persistence.
// Completion still delegates to window.toggleTask to preserve rewards/bridges.
// ============================================================
(function(){
  if(window.TaskDetailV3)return;

  var state={mode:null,taskId:null,draft:null,helpPicker:false,iconPicker:null,scrollOverflow:null};
  var SUB_ICONS=['','⭐','✅','📌','✨','🧹','🧽','🧴','🧼','🪣','🚿','🛒','🥦','🍎','🛏️','🚪','🪑','📦','📅','🌱','🐾','💻','🚗'];

  function M(){return window.TaskPresentationModelV3;}
  function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
  function svg(path,size){return '<svg viewBox="0 0 24 24" width="'+(size||16)+'" height="'+(size||16)+'" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+path+'</svg>';}
  var ICON={
    close:svg('<path d="M6 6l12 12M18 6 6 18"/>',16),
    calendar:svg('<rect x="4" y="5.5" width="16" height="14.5" rx="2.2"/><path d="M4 10h16M8 3.5v4M16 3.5v4"/>',13),
    repeat:svg('<path d="M17 2l4 4-4 4"/><path d="M3 11V9a3 3 0 0 1 3-3h15M7 22l-4-4 4-4"/><path d="M21 13v2a3 3 0 0 1-3 3H3"/>',13),
    priority:svg('<path d="M5 20V10m7 10V4m7 16v-7"/>',13),
    check:svg('<path d="m5 12 4 4L19 6"/>',14),
    edit:svg('<path d="M4 20h4l11-11-4-4L4 16v4Z"/><path d="m13 7 4 4"/>',14),
    clock:svg('<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/>',14),
    people:svg('<circle cx="9" cy="8" r="3"/><circle cx="16.5" cy="9" r="2.2"/><path d="M3.5 20a5.5 5.5 0 0 1 11 0M13 20a4 4 0 0 1 7.5-1.8"/>',16),
    trash:svg('<path d="M5 7h14M10 7V5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2M7 7l1 12a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2l1-12"/>',14)
  };

  function overlay(){var el=document.getElementById('tasks-v3-detail');if(!el){el=document.createElement('div');el.id='tasks-v3-detail';el.className='tv3d-overlay';document.body.appendChild(el);}return el;}
  function lock(){if(state.scrollOverflow===null)state.scrollOverflow=document.body.style.overflow||'';document.body.style.overflow='hidden';}
  function unlock(){document.body.style.overflow=state.scrollOverflow===null?'':state.scrollOverflow;state.scrollOverflow=null;}
  function close(){var el=document.getElementById('tasks-v3-detail');if(el){el.classList.remove('open');setTimeout(function(){if(el.parentNode)el.parentNode.removeChild(el);},180);}state.mode=null;state.taskId=null;state.draft=null;state.helpPicker=false;state.iconPicker=null;unlock();}
  function toast(msg){if(typeof window.showToast==='function')window.showToast(msg);}
  function task(){return M()&&M().getTask(state.taskId);}
  function ready(){return !!(window.TaskSharedData&&TaskSharedData.update);}
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function persistLocal(row){try{var index=(window.taskData||[]).findIndex(function(t){return String(t.id||t._key)===String(row.id||row._key);});if(index>-1)window.taskData[index]=row;if(window.AppState&&AppState.save)AppState.save();}catch(e){}}
  function patch(id,changes,cb){var current=M().getTask(id);if(ready()){TaskSharedData.update(current.id,changes).then(function(saved){if(saved)persistLocal(saved);if(cb)cb(saved||Object.assign({},current,changes));}).catch(function(err){toast((err&&err.message)||'Kon niet opslaan');});return;}if(!current)return;Object.keys(changes).forEach(function(k){current[k]=changes[k];});current.updatedAt=Date.now();persistLocal(current);if(cb)cb(current);}
  function removeTask(row){if(typeof window.deleteTask==='function'){window.deleteTask(row.id);close();return;}if(window.TaskSharedData&&TaskSharedData.remove)TaskSharedData.remove(row.id).then(close).catch(function(err){toast((err&&err.message)||'Verwijderen mislukt');});}

  function avatarHtml(person,cls){var c=cls||'tv3d-person-avatar';if(!person)return'<span class="'+c+'">?</span>';return person.avatar?'<img class="'+c+'" src="'+esc(person.avatar)+'" alt="'+esc(person.name)+'">':'<span class="'+c+'">'+esc(M().initials(person.name))+'</span>';}
  function chip(icon,label){return '<span class="tv3d-chip">'+icon+'<span>'+esc(label)+'</span></span>';}
  function managedCleaning(row){try{return !!(window.CleaningTaskSupplyUi&&CleaningTaskSupplyUi._isManaged&&CleaningTaskSupplyUi._isManaged(row));}catch(e){return false;}}
  function completeAllowed(vm){return !vm.subtasks.length||vm.subtasks.every(function(s){return s&&s.done;});}

  function collaboration(row){
    var me=M().currentUid(),assigned=M().assignees(row),helpers=Array.isArray(row.helpers)?row.helpers:[],owner=window.TaskSharedData&&TaskSharedData.isTaskOwner&&TaskSharedData.isTaskOwner(row,me),helper=helpers.some(function(h){return String(h&&(h.uid||h.memberId||h.id))===String(me);});
    if(helper)return{role:'helper',title:'Samen aan deze taak',subtitle:'Je helpt mee met deze taak.',button:'Stop helpen'};
    if(owner&&row.helpRequested)return{role:'owner-pending',title:'Hulp gevraagd',subtitle:row.helpAudience==='household'?'De hulpvraag staat open voor het gezin.':'De uitnodiging staat nog open.',button:'Intrekken'};
    if(owner)return{role:'owner',title:'Hulp nodig?',subtitle:'Vraag iemand uit je gezin om mee te helpen.',button:'Hulp vragen'};
    if(row.helpRequested&&(row.helpAudience==='household'||String(row.helpRequestedForUid||'')===String(me)))return{role:'invitee',title:'Hulp gevraagd',subtitle:'Je kunt aansluiten bij deze taak.',button:'Meehelpen'};
    return{role:'viewer',title:'Samen',subtitle:assigned.length?'Deze taak is toegewezen aan '+assigned.map(function(p){return p.name;}).join(', ')+'.':'Deze taak is nog niet toegewezen.',button:null};
  }
  function helpPicker(row){if(!state.helpPicker)return'';var me=M().currentUid(),people=M().members().filter(function(member){var id=member.uid||member.id;return id&&String(id)!==String(me)&&!(row.assignedToUids&&row.assignedToUids[id]);});return '<div class="tv3d-help-picker">'+people.map(function(member){var id=member.uid||member.id;return '<button data-tv3-help-pick="'+esc(id)+'">'+esc(member.displayName||member.name||'Gezinslid')+'</button>';}).join('')+(people.length?'':'<span class="tv3d-supply-empty">Geen extra gezinsleden beschikbaar.</span>')+'</div>';}
  function helpHtml(row){var c=collaboration(row);return '<section class="tv3d-help"><span class="tv3d-help-icon">'+ICON.people+'</span><span class="tv3d-help-copy"><strong>'+esc(c.title)+'</strong><small>'+esc(c.subtitle)+'</small></span>'+(c.button?'<button class="tv3d-help-btn" data-tv3-help="'+c.role+'">'+esc(c.button)+'</button>':'')+helpPicker(row)+'</section>';}

  function subtaskHtml(vm){if(!vm.subtasks.length)return '<div class="tv3d-supply-empty">Nog geen subtaken.</div><button class="tv3d-sub-add" data-tv3-sub-add="1">+ Subtaak toevoegen</button>';return '<div class="tv3d-sublist">'+vm.subtasks.map(function(sub){return '<div class="tv3d-sub'+(sub.done?' is-done':'')+'"><button class="tv3d-sub-check" data-tv3-sub-toggle="'+esc(sub.id)+'">'+(sub.done?ICON.check:'')+'</button><span class="tv3d-sub-title">'+(sub.icon?'<span aria-hidden="true">'+esc(sub.icon)+'</span> ':'')+esc(sub.title||'Subtaak')+'</span><button class="tv3d-sub-more" data-tv3-sub-edit="'+esc(sub.id)+'" aria-label="Subtaak bewerken">⋮</button></div>';}).join('')+'</div><button class="tv3d-sub-add" data-tv3-sub-add="1">+ Subtaak toevoegen</button>';}
  function suppliesHtml(vm){
    var list=vm.supplies||[];var managed=managedCleaning(vm.raw);
    return '<section class="tv3d-section"><div class="tv3d-section-head"><strong>Benodigdheden</strong>'+(list.length?'<small>'+list.length+' items</small>':'')+'</div>'+(list.length?'<div class="tv3d-supplies">'+list.map(function(item){return '<span class="tv3d-supply" data-status="'+esc(item.status||'IN_STOCK')+'"><i></i>'+esc(item.name)+'</span>';}).join('')+'</div>':'<div class="tv3d-supply-empty">Geen benodigdheden gekoppeld.</div>')+(managed?'<button class="tv3d-cleaning-manage" data-tv3-cleaning-manage="1">Beheer in Schoonmaken</button>':'')+'</section>';
  }
  function detailHtml(row){
    var vm=M().view(row),person=vm.primaryPerson,allowed=completeAllowed(vm),done=!!row.done;
    return '<article class="tv3d-card" role="dialog" aria-modal="true" aria-label="'+esc(vm.title)+'"><div class="tv3d-hero" style="background-image:url(\''+esc(vm.photo)+'\')"><button class="tv3d-close" data-tv3-close="1">'+ICON.close+'</button></div><div class="tv3d-sheet"><h2 class="tv3d-title">'+esc(vm.title)+'</h2>'
      +'<div class="tv3d-person">'+avatarHtml(person)+'<span><strong>'+esc(person?person.name:'Niet toegewezen')+'</strong><small>Toegewezen aan</small></span></div>'
      +'<div class="tv3d-chips">'+chip(ICON.calendar,vm.dateLabel)+chip(ICON.repeat,vm.recurrenceLabel)+chip(ICON.priority,vm.priorityLabel)+'</div>'
      +(vm.description?'<p class="tv3d-description">'+esc(vm.description)+'</p>':'')+'<div class="tv3d-divider"></div>'
      +'<section class="tv3d-section"><div class="tv3d-section-head"><strong>Subtaken</strong><small>'+vm.subDone+' van '+vm.subtasks.length+' voltooid</small></div>'+subtaskHtml(vm)+'</section>'
      +suppliesHtml(vm)+helpHtml(row)
      +'<button class="tv3d-complete'+(done?' is-done':'')+'" data-tv3-complete="1" '+(!allowed&&!done?'disabled':'')+'>'+ICON.check+'<span>'+(done?'Heropenen':allowed?'Markeer als klaar':'Voltooi eerst alle stappen')+'</span></button>'
      +'<div class="tv3d-secondary"><button data-tv3-edit="1">'+ICON.edit+'<span>Bewerken</span></button><button data-tv3-postpone="1">'+ICON.clock+'<span>Uitstellen</span></button></div></div></article>';
  }

  function open(id){var row=M()&&M().getTask(id);if(!row)return;state.mode='detail';state.taskId=String(row.id||row._key);state.draft=null;state.helpPicker=false;state.iconPicker=null;lock();render();}
  function render(){var row=task();if(!row){close();return;}var el=overlay();if(state.mode==='edit'){renderEditor(row,false);return;}el.innerHTML=detailHtml(row);requestAnimationFrame(function(){el.classList.add('open');});bindDetail(el,row);}

  function bindDetail(el,row){
    el.onclick=function(e){if(e.target===el)close();};var closeBtn=el.querySelector('[data-tv3-close]');if(closeBtn)closeBtn.onclick=close;
    el.querySelectorAll('[data-tv3-sub-toggle]').forEach(function(btn){btn.onclick=function(){var id=btn.getAttribute('data-tv3-sub-toggle'),next=(Array.isArray(row.subtasks)?row.subtasks:[]).map(function(s){return String(s.id)===String(id)?Object.assign({},s,{done:!s.done}):s;});patch(row.id,{subtasks:next},render);};});
    el.querySelectorAll('[data-tv3-sub-edit]').forEach(function(btn){btn.onclick=function(){var id=btn.getAttribute('data-tv3-sub-edit'),sub=(row.subtasks||[]).find(function(s){return String(s.id)===String(id);});if(!sub)return;var title=(prompt('Naam van de subtaak',sub.title||'')||'').trim();if(!title)return;var next=(row.subtasks||[]).map(function(s){return String(s.id)===String(id)?Object.assign({},s,{title:title}):s;});patch(row.id,{subtasks:next},render);};});
    var add=el.querySelector('[data-tv3-sub-add]');if(add)add.onclick=function(){var title=(prompt('Naam van de subtaak?')||'').trim();if(!title)return;var next=(Array.isArray(row.subtasks)?row.subtasks.slice():[]);next.push({id:'sub_'+Date.now().toString(36),title:title,done:false});patch(row.id,{subtasks:next},render);};
    var complete=el.querySelector('[data-tv3-complete]');if(complete)complete.onclick=function(){var current=M().getTask(row.id);if(!current)return;var vm=M().view(current);if(!current.done&&!completeAllowed(vm)){toast('Voltooi eerst alle stappen');return;}if(typeof window.toggleTask==='function'){window.toggleTask(current.id);setTimeout(render,80);}else patch(current.id,{done:!current.done},render);};
    var edit=el.querySelector('[data-tv3-edit]');if(edit)edit.onclick=function(){state.mode='edit';state.draft=clone(row);renderEditor(row,false);};
    var postpone=el.querySelector('[data-tv3-postpone]');if(postpone)postpone.onclick=function(){var base=row.date?new Date(row.date+'T00:00:00'):new Date();base.setDate(base.getDate()+1);var iso=base.getFullYear()+'-'+String(base.getMonth()+1).padStart(2,'0')+'-'+String(base.getDate()).padStart(2,'0');patch(row.id,{date:iso},function(){toast('Taak één dag uitgesteld');render();});};
    var help=el.querySelector('[data-tv3-help]');if(help)help.onclick=function(){var role=help.getAttribute('data-tv3-help');if(!window.TaskSharedData)return;if(role==='owner'){state.helpPicker=!state.helpPicker;render();return;}var p=role==='owner-pending'?TaskSharedData.retractHelp(row.id):role==='invitee'?TaskSharedData.joinHelp(row.id):role==='helper'?TaskSharedData.leaveHelp(row.id):Promise.resolve();Promise.resolve(p).then(function(){state.helpPicker=false;render();}).catch(function(err){toast((err&&err.message)||'Actie mislukt');});};
    el.querySelectorAll('[data-tv3-help-pick]').forEach(function(btn){btn.onclick=function(){TaskSharedData.requestHelp(row.id,btn.getAttribute('data-tv3-help-pick')).then(function(){state.helpPicker=false;render();}).catch(function(err){toast((err&&err.message)||'Hulp vragen mislukt');});};});
    var manage=el.querySelector('[data-tv3-cleaning-manage]');if(manage)manage.onclick=function(){openCleaning(row);};
  }

  function openCleaning(row){var roomId=String(row.cleaningRoomId||'');close();if(typeof window.showScreen==='function')window.showScreen('cleaning');if(!roomId)return;var tries=0,timer=setInterval(function(){tries++;if(window.CleaningSupplyExperience&&CleaningSupplyExperience.openRoom){clearInterval(timer);CleaningSupplyExperience.openRoom(roomId);setTimeout(function(){var all=document.querySelector('[data-cleaning-supply-mode="all"]');if(all&&all.click)all.click();},60);}else if(tries>80)clearInterval(timer);},50);}

  function todayIso(){var d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10);}
  function newDraft(){var assigned={},me=M().currentUid();if(me)assigned[me]=true;return{title:'',desc:'',description:'',category:null,date:todayIso(),time:'',prio:'normaal',recurrence:'once',assignedToUids:assigned,subtasks:[],supplies:[],done:false};}
  function normalizeSupplyNames(value){return String(value||'').split(',').map(function(x){return x.trim();}).filter(Boolean).map(function(name,i){return{id:'supply_'+i+'_'+Date.now().toString(36),name:name,status:'IN_STOCK'};});}
  function editMembers(draft){return M().members().map(function(member){var id=member.uid||member.id,name=member.displayName||member.name||'Gezinslid',selected=!!(draft.assignedToUids&&draft.assignedToUids[id]),person={name:name,avatar:M().avatar(member)};return '<button type="button" class="tv3e-member'+(selected?' active':'')+'" data-v3e-member="'+esc(id)+'">'+avatarHtml(person,'tv3e-member-avatar')+'<span>'+esc(name)+'</span></button>';}).join('');}
  function editorSubs(draft){return '<div class="tv3e-sublist">'+(draft.subtasks||[]).map(function(sub){return '<div class="tv3e-subrow"><input data-v3e-sub-title="'+esc(sub.id)+'" value="'+esc(sub.title||'')+'" placeholder="Subtaak"><button type="button" data-v3e-sub-remove="'+esc(sub.id)+'">'+ICON.trash+'</button></div>'+(state.iconPicker===String(sub.id)?'<div class="tv3e-iconpicker">'+SUB_ICONS.map(function(icon){return '<button type="button" data-v3e-icon="'+esc(sub.id)+'" data-v3e-icon-value="'+esc(icon)+'">'+(icon||'Geen')+'</button>';}).join('')+'</div>':'')+'<button type="button" class="tv3e-icon-open" data-v3e-icon-open="'+esc(sub.id)+'">'+(sub.icon?esc(sub.icon)+' ':'')+'Icoon</button>';}).join('')+'</div><button type="button" class="tv3e-add" data-v3e-sub-add="1">+ Subtaak toevoegen</button>';}
  function notesHtml(row){var notes=Array.isArray(row&&row.notes)?row.notes.slice().reverse():[];return '<div class="tv3e-notes">'+(notes.length?notes.map(function(note){var date='';try{date=new Date(note.createdAt).toLocaleString('nl-NL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});}catch(e){}return '<div class="tv3e-note"><strong>'+esc((M().member(note.createdByUid)||{}).displayName||(M().member(note.createdByUid)||{}).name||'Gezinslid')+'</strong><small>'+esc(date)+'</small><p>'+esc(note.text||'')+'</p></div>';}).join(''):'<div class="tv3d-supply-empty">Nog geen opmerkingen.</div>')+'</div><div class="tv3e-note-form"><input data-v3e-note-input placeholder="Laat een opmerking achter…"><button type="button" data-v3e-note-send="1">Plaats</button></div>';}
  function editorHtml(row,isCreate){var d=state.draft,managed=!isCreate&&managedCleaning(row),supplies=Array.isArray(d.supplies)?d.supplies.map(function(x){return typeof x==='string'?x:(x&&x.name)||'';}).filter(Boolean).join(', '):'';return '<article class="tv3d-card tv3e-card" role="dialog" aria-modal="true"><div class="tv3d-sheet tv3e-sheet"><div class="tv3e-head"><h2>'+(isCreate?'Nieuwe taak':'Taak bewerken')+'</h2><button data-tv3-close="1">'+ICON.close+'</button></div><div class="tv3e-field"><label>Taaknaam</label><input class="tv3e-input" data-v3e-title value="'+esc(d.title||'')+'" placeholder="Bijv. badkamer schoonmaken"></div><div class="tv3e-field"><label>Beschrijving</label><textarea class="tv3e-textarea" data-v3e-desc placeholder="Wat moet er gebeuren?">'+esc(d.desc||d.description||'')+'</textarea></div><div class="tv3e-grid"><div class="tv3e-field"><label>Datum</label><input class="tv3e-input" type="date" data-v3e-date value="'+esc(d.date||'')+'"></div><div class="tv3e-field"><label>Tijd</label><input class="tv3e-input" type="time" data-v3e-time value="'+esc(d.time||'')+'"></div></div><div class="tv3e-grid"><div class="tv3e-field"><label>Herhaling</label><select class="tv3e-select" data-v3e-recurrence>'+['once','daily','weekly','monthly'].map(function(v){return '<option value="'+v+'"'+(String(d.recurrence||'once')===v?' selected':'')+'>'+({once:'Eenmalig',daily:'Dagelijks',weekly:'Wekelijks',monthly:'Maandelijks'}[v])+'</option>';}).join('')+'</select></div><div class="tv3e-field"><label>Prioriteit</label><select class="tv3e-select" data-v3e-prio>'+['laag','normaal','hoog'].map(function(v){return '<option value="'+v+'"'+(String(d.prio||d.priority||'normaal')===v?' selected':'')+'>'+({laag:'Laag',normaal:'Normaal',hoog:'Hoog'}[v])+'</option>';}).join('')+'</select></div></div><div class="tv3e-field"><label>Toegewezen aan</label><div class="tv3e-members">'+editMembers(d)+'</div></div><div class="tv3e-field"><label>Subtaken</label>'+editorSubs(d)+'</div>'+(managed?'<div class="tv3e-field"><label>Benodigdheden</label><button type="button" class="tv3e-add" data-v3e-cleaning="1">Beheer benodigdheden in Schoonmaken</button></div>':'<div class="tv3e-field"><label>Benodigdheden · gescheiden met komma&apos;s</label><input class="tv3e-input" data-v3e-supplies value="'+esc(supplies)+'" placeholder="Allesreiniger, spons, doek"></div>')+(!isCreate?'<div class="tv3e-field"><label>Opmerkingen</label>'+notesHtml(row)+'</div>':'')+'<button type="button" class="tv3e-save" data-v3e-save="1">'+(isCreate?'Taak aanmaken':'Wijzigingen opslaan')+'</button>'+(!isCreate?'<button type="button" class="tv3e-delete" data-v3e-delete="1">Taak verwijderen</button>':'')+'</div></article>';}

  function syncDraft(el){var d=state.draft;if(!d)return;var q=function(sel){return el.querySelector(sel);};d.title=(q('[data-v3e-title]')||{}).value||'';d.desc=(q('[data-v3e-desc]')||{}).value||'';d.description=d.desc;d.date=(q('[data-v3e-date]')||{}).value||'';d.time=(q('[data-v3e-time]')||{}).value||'';d.recurrence=(q('[data-v3e-recurrence]')||{}).value||'once';d.prio=(q('[data-v3e-prio]')||{}).value||'normaal';var supplies=q('[data-v3e-supplies]');if(supplies)d.supplies=normalizeSupplyNames(supplies.value);el.querySelectorAll('[data-v3e-sub-title]').forEach(function(input){var id=input.getAttribute('data-v3e-sub-title');d.subtasks=(d.subtasks||[]).map(function(s){return String(s.id)===String(id)?Object.assign({},s,{title:input.value}):s;});});}
  function renderEditor(row,isCreate){var el=overlay();el.innerHTML=editorHtml(row,isCreate);requestAnimationFrame(function(){el.classList.add('open');});bindEditor(el,row,isCreate);}
  function bindEditor(el,row,isCreate){el.onclick=function(e){if(e.target===el)close();};var x=el.querySelector('[data-tv3-close]');if(x)x.onclick=function(){if(isCreate)close();else{state.mode='detail';state.draft=null;render();}};el.querySelectorAll('[data-v3e-member]').forEach(function(btn){btn.onclick=function(){syncDraft(el);var id=btn.getAttribute('data-v3e-member');state.draft.assignedToUids=state.draft.assignedToUids||{};if(state.draft.assignedToUids[id])delete state.draft.assignedToUids[id];else state.draft.assignedToUids[id]=true;renderEditor(row,isCreate);};});el.querySelectorAll('[data-v3e-sub-remove]').forEach(function(btn){btn.onclick=function(){syncDraft(el);var id=btn.getAttribute('data-v3e-sub-remove');state.draft.subtasks=(state.draft.subtasks||[]).filter(function(s){return String(s.id)!==String(id);});renderEditor(row,isCreate);};});var add=el.querySelector('[data-v3e-sub-add]');if(add)add.onclick=function(){syncDraft(el);state.draft.subtasks=state.draft.subtasks||[];state.draft.subtasks.push({id:'sub_'+Date.now().toString(36),title:'Nieuwe subtaak',done:false});renderEditor(row,isCreate);};el.querySelectorAll('[data-v3e-icon-open]').forEach(function(btn){btn.onclick=function(){syncDraft(el);var id=btn.getAttribute('data-v3e-icon-open');state.iconPicker=state.iconPicker===id?null:id;renderEditor(row,isCreate);};});el.querySelectorAll('[data-v3e-icon]').forEach(function(btn){btn.onclick=function(){syncDraft(el);var id=btn.getAttribute('data-v3e-icon'),val=btn.getAttribute('data-v3e-icon-value')||null;state.draft.subtasks=(state.draft.subtasks||[]).map(function(s){return String(s.id)===String(id)?Object.assign({},s,{icon:val}):s;});state.iconPicker=null;renderEditor(row,isCreate);};});var manage=el.querySelector('[data-v3e-cleaning]');if(manage)manage.onclick=function(){openCleaning(row);};var noteSend=el.querySelector('[data-v3e-note-send]');if(noteSend)noteSend.onclick=function(){var input=el.querySelector('[data-v3e-note-input]'),value=(input&&input.value||'').trim();if(!value)return;var notes=(Array.isArray(row.notes)?row.notes.slice():[]);notes.push({id:'note_'+Date.now().toString(36),text:value,createdByUid:M().currentUid(),createdAt:Date.now()});patch(row.id,{notes:notes},function(saved){state.draft=clone(saved||row);renderEditor(saved||row,false);});};var save=el.querySelector('[data-v3e-save]');if(save)save.onclick=function(){syncDraft(el);saveDraft(row,isCreate,save);};var del=el.querySelector('[data-v3e-delete]');if(del)del.onclick=function(){if(confirm('Deze taak verwijderen?'))removeTask(row);};}

  function saveDraft(row,isCreate,btn){var d=state.draft,title=String(d.title||'').trim();if(!title){toast('Geef de taak een naam');return;}if(!Object.keys(d.assignedToUids||{}).length){var me=M().currentUid();if(me)d.assignedToUids[me]=true;}var names=[];M().members().forEach(function(m){var id=m.uid||m.id;if(id&&d.assignedToUids[id])names.push(m.displayName||m.name||'Gezinslid');});var payload={title:title,desc:d.desc||'',description:d.desc||'',category:d.category||null,who:names,assignedToUids:d.assignedToUids,date:d.date||'',time:d.time||'',prio:d.prio||'normaal',recurrence:d.recurrence||'once',subtasks:d.subtasks||[],supplies:d.supplies||[]};btn.disabled=true;if(isCreate){payload.createdByUid=M().currentUid();payload.done=false;if(!window.TaskSharedData||!TaskSharedData.create){btn.disabled=false;toast('Taak kon niet worden opgeslagen');return;}TaskSharedData.create(payload).then(function(saved){toast('Taak aangemaakt');if(saved&&saved.id){state.mode='detail';state.taskId=String(saved.id);state.draft=null;render();}else close();}).catch(function(err){btn.disabled=false;toast((err&&err.message)||'Taak kon niet worden opgeslagen');});}else patch(row.id,payload,function(saved){toast('Wijzigingen opgeslagen');state.mode='detail';state.draft=null;state.taskId=String((saved&&saved.id)||row.id);render();});}

  function openCreate(){state.mode='create';state.taskId=null;state.draft=newDraft();state.helpPicker=false;state.iconPicker=null;lock();renderEditor(null,true);}

  var legacy=window.TaskDetailPopup;
  var api={version:'3.0.0',open:open,close:close,openCreate:openCreate,isOpen:function(){return !!state.mode;},legacy:legacy};
  window.TaskDetailV3=api;
  window.TaskDetailPopup=api;

  window.addEventListener('familyapp:tasks-updated',function(){if(state.mode==='detail'&&state.taskId&&document.getElementById('tasks-v3-detail'))render();});
})();
