'use strict';
// ============================================================
// FAMILY DATA STORE v1.2
// Shared/private/offline persistence boundary with record + child-path mutations.
// ============================================================
(function(){
  var VERSION='1.2.0',CACHE_PREFIX='familyapp_data_v1_',listeners={},subscriptions={};
  var SHARED={shoppingLists:'shoppingLists',recipes:'recipes',notes:'notes',notifications:'notifications'};
  var PRIVATE={shoppingLists:'shoppingLists',notes:'notes',progression:'progression',preferences:'preferences'};
  function now(){return Date.now();}
  function parse(v,f){try{return v?JSON.parse(v):f;}catch(e){return f;}}
  function user(){try{return window.fbUser||(window.firebase&&firebase.auth&&firebase.auth().currentUser)||null;}catch(e){return null;}}
  function uid(){var u=user();return u&&u.uid||null;}
  function familyId(){if(window.fbFamilyId)return window.fbFamilyId;try{var m=window.HouseholdRepository&&HouseholdRepository.getMeta?HouseholdRepository.getMeta():null;if(m&&m.householdId&&m.householdId!=='household-local')return m.householdId;}catch(e){}return null;}
  function db(){try{return window.fbDb||(window.firebase&&firebase.database&&firebase.database())||null;}catch(e){return null;}}
  function onlineReady(){return !!(db()&&uid()&&familyId()&&!window.offlineMode);}
  function cacheKey(scope,c){return CACHE_PREFIX+scope+'_'+(scope==='shared'?(familyId()||'local-household'):(uid()||'local-user'))+'_'+c;}
  function readCache(scope,c,f){try{return parse(localStorage.getItem(cacheKey(scope,c)),f);}catch(e){return f;}}
  function writeCache(scope,c,v){try{localStorage.setItem(cacheKey(scope,c),JSON.stringify(v));}catch(e){}return v;}
  function emit(scope,c,v,source){var k=scope+':'+c,p={scope:scope,collection:c,value:v,source:source||'local',at:now()};(listeners[k]||[]).slice().forEach(function(fn){try{fn(p);}catch(e){}});try{window.dispatchEvent(new CustomEvent('familyapp:data:'+k,{detail:p}));}catch(e){}}
  function on(scope,c,cb){var k=scope+':'+c;if(!listeners[k])listeners[k]=[];listeners[k].push(cb);return function(){listeners[k]=(listeners[k]||[]).filter(function(fn){return fn!==cb;});};}
  function rootRef(scope,c){var d=db();if(!d)return null;if(scope==='shared'){var f=familyId();return f?d.ref('families/'+f+'/shared/'+c):null;}var u=uid();return u?d.ref('users/'+u+'/private/'+c):null;}
  function deepClone(v){if(v===undefined)return undefined;return JSON.parse(JSON.stringify(v));}
  function getPath(obj,path,fallback){var cur=obj;for(var i=0;i<path.length;i++){if(cur==null||cur[path[i]]===undefined)return fallback;cur=cur[path[i]];}return cur;}
  function setPath(obj,path,value){var out=(obj&&typeof obj==='object')?deepClone(obj):{};var cur=out;for(var i=0;i<path.length-1;i++){if(!cur[path[i]]||typeof cur[path[i]]!=='object')cur[path[i]]={};cur=cur[path[i]];}if(value===null||value===undefined)delete cur[path[path.length-1]];else cur[path[path.length-1]]=value;return out;}
  function pendingKey(){return CACHE_PREFIX+'pending_writes';}
  function pending(){try{return parse(localStorage.getItem(pendingKey()),[]);}catch(e){return[];}}
  function markPending(scope,c,value,path){var key=[scope,c,(path||[]).join('/')||'*'].join(':');var list=pending().filter(function(x){return [x.scope,x.collection,(x.path||[]).join('/')||'*'].join(':')!==key;});list.push({scope:scope,collection:c,path:path||[],value:value,at:now()});try{localStorage.setItem(pendingKey(),JSON.stringify(list));}catch(e){}}
  function read(scope,c,f){var cached=readCache(scope,c,f),ref=rootRef(scope,c);if(!ref||!onlineReady())return Promise.resolve(cached);return ref.once('value').then(function(s){var v=s.val();if(v==null)return cached;writeCache(scope,c,v);emit(scope,c,v,'firebase');return v;}).catch(function(){return cached;});}
  function write(scope,c,v,o){o=o||{};writeCache(scope,c,v);emit(scope,c,v,'local');var ref=rootRef(scope,c);if(!ref||!onlineReady()||o.localOnly)return Promise.resolve({mode:'local',value:v});return ref.set(v).then(function(){return{mode:'firebase',value:v};}).catch(function(e){markPending(scope,c,v,[]);return{mode:'local-pending',value:v,error:e};});}
  function writePath(scope,c,path,v,o){o=o||{};path=Array.isArray(path)?path:[path];var current=readCache(scope,c,{})||{},next=setPath(current,path,v);writeCache(scope,c,next);emit(scope,c,next,'local-path');var ref=rootRef(scope,c);if(ref)path.forEach(function(seg){ref=ref.child(String(seg));});if(!ref||!onlineReady()||o.localOnly)return Promise.resolve({mode:'local',value:v});return ref.set(v==null?null:v).then(function(){return{mode:'firebase',value:v};}).catch(function(e){markPending(scope,c,v,path);return{mode:'local-pending',value:v,error:e};});}
  function transactPath(scope,c,path,updater,fallback){path=Array.isArray(path)?path:[path];var current=readCache(scope,c,{})||{},local=getPath(current,path,fallback),localNext=updater(deepClone(local));writePath(scope,c,path,localNext,{localOnly:true});var ref=rootRef(scope,c);if(ref)path.forEach(function(seg){ref=ref.child(String(seg));});if(!ref||!onlineReady()){markPending(scope,c,localNext,path);return Promise.resolve({mode:'local-pending',value:localNext});}return new Promise(function(resolve){ref.transaction(function(server){return updater(deepClone(server==null?fallback:server));},function(err,committed,snap){if(err||!committed){markPending(scope,c,localNext,path);resolve({mode:'local-pending',value:localNext,error:err});return;}var v=snap.val(),latest=readCache(scope,c,{})||{},next=setPath(latest,path,v);writeCache(scope,c,next);emit(scope,c,next,'firebase-transaction');resolve({mode:'firebase',value:v});},false);});}
  function subscribe(scope,c,cb,f){var k=scope+':'+c;if(subscriptions[k])subscriptions[k]();var offLocal=on(scope,c,function(p){cb(p.value,p);}),ref=rootRef(scope,c);if(!ref||!onlineReady()){Promise.resolve().then(function(){cb(readCache(scope,c,f),{scope:scope,collection:c,source:'cache'});});subscriptions[k]=offLocal;return offLocal;}var handler=function(s){var v=s.val();if(v==null)v=f;writeCache(scope,c,v);cb(v,{scope:scope,collection:c,source:'firebase',at:now()});};ref.on('value',handler);var off=function(){offLocal();try{ref.off('value',handler);}catch(e){}delete subscriptions[k];};subscriptions[k]=off;return off;}
  function flushPending(){if(!onlineReady())return Promise.resolve({flushed:0,remaining:pending().length});var list=pending(),remain=[],flushed=0,chain=Promise.resolve();list.forEach(function(item){chain=chain.then(function(){var ref=rootRef(item.scope,item.collection);if(ref)(item.path||[]).forEach(function(seg){ref=ref.child(String(seg));});if(!ref){remain.push(item);return;}return ref.set(item.value==null?null:item.value).then(function(){flushed++;}).catch(function(){remain.push(item);});});});return chain.then(function(){try{localStorage.setItem(pendingKey(),JSON.stringify(remain));}catch(e){}return{flushed:flushed,remaining:remain.length};});}
  function makeId(prefix){return(prefix||'item')+'_'+now().toString(36)+'_'+Math.random().toString(36).slice(2,8);}
  function itemMap(items){var out={};if(Array.isArray(items)){items.forEach(function(i,n){if(!i)return;var k=i._key||('item_'+String(i.id!=null?i.id:n));out[k]=Object.assign({},i,{_key:k});});}else if(items&&typeof items==='object'){Object.keys(items).forEach(function(k){if(items[k])out[k]=Object.assign({},items[k],{_key:items[k]._key||k});});}return out;}
  function defaultShoppingList(items){return{id:'household_default',name:'Gezinslijst',icon:'🛒',category:'groceries',visibility:'household',ownerUid:uid(),createdBy:uid(),createdAt:now(),updatedAt:now(),items:itemMap(items)};}
  function migrateLegacyShopping(){var legacy=Array.isArray(window.shopData)?window.shopData.slice():[];return read('shared',SHARED.shoppingLists,{}).then(function(existing){if(existing&&Object.keys(existing).length)return{migrated:false,reason:'already-exists'};if(!legacy.length)return{migrated:false,reason:'no-legacy-items'};var list=defaultShoppingList(legacy);return writePath('shared',SHARED.shoppingLists,[list.id],list).then(function(result){try{localStorage.setItem('familyapp_migration_shopping_lists_v1','done');}catch(e){}return{migrated:true,list:list,result:result};});});}
  function status(){return{version:VERSION,onlineReady:onlineReady(),userId:uid(),familyId:familyId(),pendingWrites:pending().length};}
  window.FamilyDataStore={version:VERSION,sharedCollections:SHARED,privateCollections:PRIVATE,status:status,makeId:makeId,itemMap:itemMap,defaultShoppingList:defaultShoppingList,migrateLegacyShopping:migrateLegacyShopping,flushPending:flushPending,
    readShared:function(c,f){return read('shared',c,f);},readPrivate:function(c,f){return read('private',c,f);},writeShared:function(c,v,o){return write('shared',c,v,o);},writePrivate:function(c,v,o){return write('private',c,v,o);},subscribeShared:function(c,cb,f){return subscribe('shared',c,cb,f);},subscribePrivate:function(c,cb,f){return subscribe('private',c,cb,f);},
    writeSharedRecord:function(c,id,v,o){return writePath('shared',c,[id],v,o);},writePrivateRecord:function(c,id,v,o){return writePath('private',c,[id],v,o);},mutateSharedRecord:function(c,id,u,f){return transactPath('shared',c,[id],u,f);},mutatePrivateRecord:function(c,id,u,f){return transactPath('private',c,[id],u,f);},
    writeSharedPath:function(c,path,v,o){return writePath('shared',c,path,v,o);},writePrivatePath:function(c,path,v,o){return writePath('private',c,path,v,o);},transactSharedPath:function(c,path,u,f){return transactPath('shared',c,path,u,f);},transactPrivatePath:function(c,path,u,f){return transactPath('private',c,path,u,f);}
  };
  window.addEventListener('online',function(){setTimeout(flushPending,250);});
})();
