'use strict';
// ============================================================
// GROCERY QUICK ADD v0.421 — active list + item-level realtime add
// ============================================================
(function(){
  var VERSION='0.421',STORAGE_KEY='familyapp_food_shop_v001',STYLE_ID='grocery-bottom-sheet-style';
  var FALLBACK_ITEMS=[{n:'Melk',e:'🥛',c:'Zuivel',q:'1 liter'},{n:'Kaas',e:'🧀',c:'Zuivel',q:'200g'},{n:'Eieren',e:'🥚',c:'Zuivel',q:'6 stuks'},{n:'Brood',e:'🍞',c:'Brood',q:'1 brood'},{n:'Bananen',e:'🍌',c:'Fruit',q:'6 stuks'},{n:'Appels',e:'🍎',c:'Fruit',q:'1 zak'},{n:'Tomaten',e:'🍅',c:'Groente',q:'500g'},{n:'Kipfilet',e:'🍗',c:'Vlees',q:'500g'},{n:'Pasta',e:'🍝',c:'Overig',q:'500g'},{n:'Water',e:'💧',c:'Dranken',q:'6 flessen'}];
  function safeParse(raw,f){try{return raw?JSON.parse(raw):f;}catch(e){return f;}}
  function ensureState(){if(!Array.isArray(window.shopData))window.shopData=safeParse(localStorage.getItem(STORAGE_KEY),[]);window.shopNextId=Math.max.apply(null,(window.shopData||[]).map(function(i){return Number(i.id)||0;}).concat([0]))+1;}
  function allSuggestions(){ensureState();var prev=(window.shopData||[]).map(function(i){return{n:i.name,e:i.photo||'🛒',c:i.cat||'Overig',q:i.qty||'1x'};}),all=(window.AC_SHOP||FALLBACK_ITEMS).concat(prev),seen={};return all.filter(function(i){var k=i&&i.n&&String(i.n).toLowerCase();if(!k||seen[k])return false;seen[k]=true;return true;});}
  function getSuggestions(query){var q=String(query||'').trim().toLowerCase();return q?allSuggestions().filter(function(i){return String(i.n).toLowerCase().indexOf(q)>-1;}).slice(0,8):[];}
  function guess(query){var f=getSuggestions(query)[0];if(f)return f;var q=String(query||'').toLowerCase();if(/melk|yoghurt|kwark/.test(q))return{e:'🥛',c:'Zuivel',q:'1x'};if(/kaas/.test(q))return{e:'🧀',c:'Zuivel',q:'200g'};if(/brood/.test(q))return{e:'🍞',c:'Brood',q:'1 brood'};if(/appel/.test(q))return{e:'🍎',c:'Fruit',q:'1 zak'};if(/banaan/.test(q))return{e:'🍌',c:'Fruit',q:'6 stuks'};if(/tomaat/.test(q))return{e:'🍅',c:'Groente',q:'500g'};if(/kip/.test(q))return{e:'🍗',c:'Vlees',q:'500g'};if(/pasta|spaghetti/.test(q))return{e:'🍝',c:'Overig',q:'500g'};if(/water/.test(q))return{e:'💧',c:'Dranken',q:'6 flessen'};return{e:'📦',c:'Overig',q:'1x'};}
  function ensureStyles(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='.grocery-sheet-grid{display:grid;grid-template-columns:1fr 86px;gap:10px}.grocery-suggestions{display:none;margin-top:8px;border:1px solid var(--c-border);border-radius:16px;overflow:hidden;background:var(--c-surface);box-shadow:0 12px 30px rgba(17,24,39,.13)}.grocery-suggestion{width:100%;border:0;background:var(--c-surface);padding:10px 12px;display:flex;align-items:center;gap:10px;text-align:left}.grocery-suggestion-emoji{font-size:23px}.grocery-suggestion-title{display:block;font-size:14px;color:var(--c-text);font-weight:900}.grocery-suggestion-meta{font-size:11px;color:var(--c-text2)}';document.head.appendChild(s);}
  function activeListLabel(){var r=window.ShoppingLists&&ShoppingLists.active?ShoppingLists.active():null;return r&&r.list?r.list.name:'Gezinslijst';}
  function sheetHtml(){return '<div style="font-size:11px;font-weight:800;color:var(--c-primary);margin:-4px 0 10px">Toevoegen aan · '+activeListLabel()+'</div><div class="fam-modal-field"><label>Product</label><input id="grocery-name" autocomplete="off" placeholder="bijv. Melk"><div class="grocery-suggestions" id="grocery-suggestions"></div></div><div class="grocery-sheet-grid"><div class="fam-modal-field"><label>Hoeveelheid</label><input id="grocery-qty" placeholder="1x"></div><div class="fam-modal-field"><label>Icoon</label><input id="grocery-emoji" value="📦"></div></div><div class="fam-modal-field"><label>Categorie</label><select id="grocery-cat"><option>Groente</option><option>Fruit</option><option>Zuivel</option><option>Brood</option><option>Vlees</option><option>Dranken</option><option>Overig</option></select></div>';}
  function attachAutocomplete(m){var n=m.querySelector('#grocery-name'),q=m.querySelector('#grocery-qty'),e=m.querySelector('#grocery-emoji'),c=m.querySelector('#grocery-cat'),box=m.querySelector('#grocery-suggestions');function input(){var g=guess(n.value),r=getSuggestions(n.value);if(n.value){e.value=g.e;c.value=g.c;if(!q.value)q.value=g.q;}box.innerHTML=r.map(function(i,x){return'<button class="grocery-suggestion" data-i="'+x+'"><span class="grocery-suggestion-emoji">'+i.e+'</span><span><b class="grocery-suggestion-title">'+i.n+'</b><small class="grocery-suggestion-meta">'+i.q+' · '+i.c+'</small></span></button>';}).join('');box.style.display=r.length?'block':'none';box.querySelectorAll('[data-i]').forEach(function(b){b.onclick=function(){var i=r[+b.getAttribute('data-i')];n.value=i.n;q.value=i.q;e.value=i.e;c.value=i.c;box.style.display='none';q.focus();};});}n.oninput=input;setTimeout(function(){n.focus();},80);}
  function values(m){var n=m.querySelector('#grocery-name'),q=m.querySelector('#grocery-qty'),e=m.querySelector('#grocery-emoji'),c=m.querySelector('#grocery-cat'),name=n.value.trim(),g=guess(name);return{name:name,qty:q.value||g.q,emoji:e.value||g.e,cat:c.value||g.c};}
  function saveFromModal(m){ensureState();var v=values(m);if(!v.name)return false;var item={id:window.shopNextId++,name:v.name,qty:v.qty,cat:v.cat,who:window.myName||'Gezin',done:false,photo:v.emoji,createdAt:Date.now()};if(window.ShoppingLists&&typeof ShoppingLists.addItem==='function'){ShoppingLists.addItem(item).then(function(saved){if(saved){if(typeof window.showToast==='function')showToast('Toegevoegd aan '+activeListLabel()+' ✓');}});}else{window.shopData.unshift(item);localStorage.setItem(STORAGE_KEY,JSON.stringify(window.shopData));if(typeof window.renderShop==='function')renderShop();}if(typeof window.addActivity==='function')addActivity('🛒','#fff3dc',(window.myName||'Gezin')+' voegde "'+v.name+'" toe');return true;}
  function open(){ensureState();ensureStyles();if(!window.BottomSheet)return window.openAdd&&window.openAdd('shop');BottomSheet.open({title:'🛒 Item toevoegen',html:sheetHtml(),onOpen:function(ctx){attachAutocomplete(ctx.modal);},actions:[{label:'Annuleren'},{label:'Toevoegen',primary:true,onClick:function(ctx){return saveFromModal(ctx.modal);}}]});}
  function installButton(){var screen=document.getElementById('screen-shop'),header=screen&&screen.querySelector('.list-header');if(!header)return;var btn=header.querySelector('.add-btn');if(!btn){btn=document.createElement('button');btn.className='add-btn';header.appendChild(btn);}btn.onclick=function(e){if(e)e.preventDefault();open();return false;};btn.textContent='+ Toevoegen';}
  function boot(){ensureStyles();installButton();[100,300,800,1500].forEach(function(d){setTimeout(installButton,d);});}
  window.GroceryQuickAddModal={version:VERSION,open:open,installButton:installButton,guess:guess,getSuggestions:getSuggestions};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
