'use strict';
// ============================================================
// GROCERY QUICK ADD v0.420
// Active-list aware quick add. Rapid-entry behaviour is added in the next UX step.
// ============================================================
(function(){
  var VERSION='0.420',STORAGE_KEY='familyapp_food_shop_v001',STYLE_ID='grocery-bottom-sheet-style';
  var FALLBACK_ITEMS=[{n:'Melk',e:'🥛',c:'Zuivel',q:'1 liter'},{n:'Kaas',e:'🧀',c:'Zuivel',q:'200g'},{n:'Eieren',e:'🥚',c:'Zuivel',q:'6 stuks'},{n:'Brood',e:'🍞',c:'Brood',q:'1 brood'},{n:'Bananen',e:'🍌',c:'Fruit',q:'6 stuks'},{n:'Appels',e:'🍎',c:'Fruit',q:'1 zak'},{n:'Tomaten',e:'🍅',c:'Groente',q:'500g'},{n:'Paprika',e:'🫑',c:'Groente',q:'2 stuks'},{n:'Komkommer',e:'🥒',c:'Groente',q:'1 stuk'},{n:'Aardappelen',e:'🥔',c:'Groente',q:'1 kg'},{n:'Kipfilet',e:'🍗',c:'Vlees',q:'500g'},{n:'Gehakt',e:'🥩',c:'Vlees',q:'500g'},{n:'Pasta',e:'🍝',c:'Overig',q:'500g'},{n:'Rijst',e:'🍚',c:'Overig',q:'1 kg'},{n:'Olijfolie',e:'🫙',c:'Overig',q:'1 fles'},{n:'Cola',e:'🥤',c:'Dranken',q:'1.5 liter'},{n:'Water',e:'💧',c:'Dranken',q:'6 flessen'},{n:'Toiletpapier',e:'🧻',c:'Overig',q:'1 pak'},{n:'Wasmiddel',e:'🧺',c:'Overig',q:'1 fles'}];
  function safeParse(raw,f){try{return raw?JSON.parse(raw):f;}catch(e){return f;}}
  function ensureState(){if(!Array.isArray(window.shopData))window.shopData=safeParse(localStorage.getItem(STORAGE_KEY),[]);window.shopNextId=Math.max.apply(null,(window.shopData||[]).map(function(i){return Number(i.id)||0;}).concat([0]))+1;}
  function persist(){ensureState();localStorage.setItem(STORAGE_KEY,JSON.stringify(window.shopData||[]));if(window.ShoppingLists&&typeof window.ShoppingLists.saveActiveItems==='function')window.ShoppingLists.saveActiveItems(window.shopData||[]);else if(window.HouseholdRepository&&typeof window.HouseholdRepository.write==='function')window.HouseholdRepository.write('groceries',window.shopData||[],{source:'groceryQuickAddModal',operation:'saveGroceries',version:VERSION});try{window.dispatchEvent(new CustomEvent('familyapp:food:grocery-updated',{detail:{items:window.shopData||[]}}));}catch(e){}}
  function allSuggestions(){ensureState();var prev=(window.shopData||[]).map(function(i){return{n:i.name,e:(i.photo&&!String(i.photo).startsWith('http'))?i.photo:'🛒',c:i.cat||'Overig',q:i.qty||'1x'};});var all=(window.AC_SHOP||FALLBACK_ITEMS).concat(prev),seen={};return all.filter(function(i){if(!i||!i.n)return false;var k=String(i.n).toLowerCase();if(seen[k])return false;seen[k]=true;return true;});}
  function getSuggestions(query){var q=String(query||'').trim().toLowerCase();if(!q)return[];return allSuggestions().filter(function(i){return String(i.n).toLowerCase().indexOf(q)>-1;}).slice(0,8);}
  function guess(query){var f=getSuggestions(query)[0];if(f)return f;var q=String(query||'').toLowerCase();if(q.indexOf('melk')>-1||q.indexOf('yoghurt')>-1||q.indexOf('kwark')>-1)return{e:'🥛',c:'Zuivel',q:'1x'};if(q.indexOf('kaas')>-1)return{e:'🧀',c:'Zuivel',q:'200g'};if(q.indexOf('ei')>-1)return{e:'🥚',c:'Zuivel',q:'6 stuks'};if(q.indexOf('brood')>-1)return{e:'🍞',c:'Brood',q:'1 brood'};if(q.indexOf('appel')>-1)return{e:'🍎',c:'Fruit',q:'1 zak'};if(q.indexOf('banaan')>-1)return{e:'🍌',c:'Fruit',q:'6 stuks'};if(q.indexOf('tomaat')>-1)return{e:'🍅',c:'Groente',q:'500g'};if(q.indexOf('komkommer')>-1)return{e:'🥒',c:'Groente',q:'1 stuk'};if(q.indexOf('aardappel')>-1)return{e:'🥔',c:'Groente',q:'1 kg'};if(q.indexOf('kip')>-1)return{e:'🍗',c:'Vlees',q:'500g'};if(q.indexOf('gehakt')>-1||q.indexOf('rund')>-1)return{e:'🥩',c:'Vlees',q:'500g'};if(q.indexOf('pasta')>-1||q.indexOf('spaghetti')>-1)return{e:'🍝',c:'Overig',q:'500g'};if(q.indexOf('rijst')>-1)return{e:'🍚',c:'Overig',q:'1 kg'};if(q.indexOf('cola')>-1)return{e:'🥤',c:'Dranken',q:'1.5 liter'};if(q.indexOf('water')>-1)return{e:'💧',c:'Dranken',q:'6 flessen'};return{e:'📦',c:'Overig',q:'1x'};}
  function ensureStyles(){if(document.getElementById(STYLE_ID))return;var s=document.createElement('style');s.id=STYLE_ID;s.textContent='.grocery-sheet-grid{display:grid;grid-template-columns:1fr 86px;gap:10px}.grocery-suggestions{display:none;margin-top:8px;border:1px solid var(--c-border,#edf0ec);border-radius:16px;overflow:hidden;background:#fff;box-shadow:0 12px 30px rgba(17,24,39,.13)}.grocery-suggestion{width:100%;border:0;background:#fff;padding:10px 12px;display:flex;align-items:center;gap:10px;text-align:left}.grocery-suggestion-emoji{font-size:23px;width:28px;text-align:center}.grocery-suggestion-title{display:block;font-size:14px;color:var(--c-text,#1f2933);font-weight:900}.grocery-suggestion-meta{font-size:11px;color:var(--c-text2,#697386)}';document.head.appendChild(s);}
  function activeListLabel(){var r=window.ShoppingLists&&window.ShoppingLists.active?window.ShoppingLists.active():null;return r&&r.list?r.list.name:'Gezinslijst';}
  function sheetHtml(){return '<div style="font-size:11px;font-weight:800;color:var(--c-primary);margin:-4px 0 10px">Toevoegen aan · '+activeListLabel()+'</div><div class="fam-modal-field"><label>Product</label><input id="grocery-name" autocomplete="off" placeholder="bijv. Melk"><div class="grocery-suggestions" id="grocery-suggestions"></div></div><div class="grocery-sheet-grid"><div class="fam-modal-field"><label>Hoeveelheid</label><input id="grocery-qty" placeholder="1x"></div><div class="fam-modal-field"><label>Icoon</label><input id="grocery-emoji" value="📦"></div></div><div class="fam-modal-field"><label>Categorie</label><select id="grocery-cat"><option>Groente</option><option>Fruit</option><option>Zuivel</option><option>Brood</option><option>Vlees</option><option>Dranken</option><option>Overig</option></select></div>';}
  function attachAutocomplete(modal){var name=modal.querySelector('#grocery-name'),qty=modal.querySelector('#grocery-qty'),emoji=modal.querySelector('#grocery-emoji'),cat=modal.querySelector('#grocery-cat'),box=modal.querySelector('#grocery-suggestions');if(!name||!box)return;function apply(i){name.value=i.n||name.value;if(qty)qty.value=i.q||'1x';if(emoji)emoji.value=i.e||'📦';if(cat)cat.value=i.c||'Overig';box.style.display='none';if(qty)qty.focus();}function input(){var value=name.value.trim(),g=guess(value);if(value){if(emoji)emoji.value=g.e||'📦';if(cat)cat.value=g.c||'Overig';if(qty&&!qty.value)qty.value=g.q||'1x';}var r=getSuggestions(value);if(!r.length){box.style.display='none';box.innerHTML='';return;}box.style.display='block';box.innerHTML=r.map(function(i,x){return '<button class="grocery-suggestion" data-i="'+x+'" type="button"><span class="grocery-suggestion-emoji">'+i.e+'</span><span style="flex:1"><b class="grocery-suggestion-title">'+i.n+'</b><small class="grocery-suggestion-meta">'+i.q+' · '+i.c+'</small></span></button>';}).join('');box.querySelectorAll('[data-i]').forEach(function(b){b.onclick=function(){apply(r[parseInt(b.getAttribute('data-i'),10)]);};});}name.oninput=input;name.onfocus=function(){if(name.value.trim())input();};setTimeout(function(){name.focus();},80);}
  function valuesFrom(m){var n=m.querySelector('#grocery-name'),q=m.querySelector('#grocery-qty'),e=m.querySelector('#grocery-emoji'),c=m.querySelector('#grocery-cat'),v=n?n.value.trim():'',g=guess(v);return{name:v,qty:q&&q.value?q.value:g.q||'1x',emoji:e&&e.value?e.value:g.e||'📦',cat:c&&c.value?c.value:g.c||'Overig'};}
  function saveFromModal(m){ensureState();var v=valuesFrom(m);if(!v.name)return false;var id=window.shopNextId++;window.shopData.unshift({id:id,name:v.name,qty:v.qty,cat:v.cat,who:window.myName||'Gezin',done:false,photo:v.emoji,createdAt:Date.now()});persist();if(typeof window.renderShop==='function')window.renderShop();if(typeof window.updateStats==='function')window.updateStats();if(typeof window.addActivity==='function')window.addActivity('🛒','#fff3dc',(window.myName||'Gezin')+' voegde "'+v.name+'" toe');if(typeof window.showToast==='function')window.showToast('Toegevoegd aan '+activeListLabel()+' ✓');if(typeof window.highlightShopItem==='function')requestAnimationFrame(function(){window.highlightShopItem(id);});return true;}
  function open(){ensureState();ensureStyles();if(!window.ModalManager||!window.BottomSheet){if(typeof window.openAdd==='function')return window.openAdd('shop');return;}window.BottomSheet.open({title:'🛒 Item toevoegen',html:sheetHtml(),onOpen:function(ctx){attachAutocomplete(ctx.modal);},actions:[{label:'Annuleren'},{label:'Toevoegen',primary:true,onClick:function(ctx){return saveFromModal(ctx.modal);}}]});}
  function installButton(){var screen=document.getElementById('screen-shop');if(!screen)return;var header=screen.querySelector('.list-header');if(!header)return;var btn=header.querySelector('.add-btn');if(!btn){btn=document.createElement('button');btn.className='add-btn';header.appendChild(btn);}btn.setAttribute('onclick','return GroceryQuickAddModal.open()');btn.onclick=function(e){if(e)e.preventDefault();open();return false;};btn.textContent='+ Toevoegen';btn.style.pointerEvents='auto';}
  function boot(){ensureStyles();installButton();[100,300,800,1500,2500].forEach(function(d){setTimeout(installButton,d);});}
  window.GroceryQuickAddModal={version:VERSION,open:open,installButton:installButton,guess:guess,getSuggestions:getSuggestions};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
