'use strict';
(function(){
  if(window.NotificationActions&&window.NotificationActions.version==='3.0.0')return;
  var VERSION='3.0.0';
  function token(){var c=window.HouseholdContext;if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function assertToken(t){if(!window.HouseholdContext||!HouseholdContext.isCurrent(t)){var e=new Error('NOTIFICATION_CONTEXT_CHANGED');e.code='NOTIFICATION_CONTEXT_CHANGED';throw e;}return t;}
  function currentUid(){try{return token().uid;}catch(e){return null;}}
  function taskByEvent(event){var id=event&&event.data&&(event.data.taskId||event.data.taskKey)||(event&&event.entity&&event.entity.id)||'';return(window.taskData||[]).find(function(t){return String(t.id||t._key)===String(id);})||null;}
  function markRead(event,t){if(!window.NotificationStore||!event||!event.id)return Promise.resolve();assertToken(t);return NotificationStore.markRead(event.id).then(function(r){assertToken(t);return r;});}
  function isActionable(event){return!!(event&&(event.type==='task.help.requested'||event.type==='partyQuest.invitation.sent'||event.type==='partyQuest.created'));}
  function actionLabel(event){if(!event)return'';if(event.type==='task.help.requested')return'Hulp bieden';if(event.type==='partyQuest.invitation.sent')return'Uitnodiging intrekken';return'Openen';}
  function acceptTaskHelp(event){var t=token(),task=taskByEvent(event);if(!task)return Promise.reject(new Error('Taak niet gevonden'));if(!window.TaskSharedData||typeof TaskSharedData.joinHelp!=='function')return Promise.reject(new Error('Taakdata is nog niet klaar'));var existed=Array.isArray(task.helpers)&&task.helpers.some(function(h){return String(h&&(h.uid||h.memberId||h.id)||'')===String(t.uid);});assertToken(t);return TaskSharedData.joinHelp(task.id||task._key).then(function(saved){assertToken(t);var requester=task.helpRequestedByUid||task.createdByUid||null;if(!existed&&window.NotificationEvents&&NotificationEvents.taskHelpJoined)NotificationEvents.taskHelpJoined(saved||task,requester).catch(function(){});return markRead(event,t).then(function(){if(typeof window.showToast==='function')window.showToast(existed?'Je helpt al mee ✓':'Je bent aan de quest toegevoegd 🤝');return saved;});});}
  function revokePartyInvitation(event){var t=token(),questId=event&&event.data&&event.data.questId,inviteeUid=event&&event.data&&event.data.inviteeUid;if(!questId||!inviteeUid)return Promise.reject(new Error('Uitnodigingsgegevens ontbreken'));if(!window.PartyQuestInvites||typeof PartyQuestInvites.revokeInvite!=='function')return Promise.reject(new Error('Party Quest service is nog niet klaar'));assertToken(t);return PartyQuestInvites.revokeInvite(questId,inviteeUid).then(function(){assertToken(t);return markRead(event,t);});}
  function respondPartyQuestInvite(event,status){var t=token(),questId=event&&event.data&&event.data.questId;if(!questId)return Promise.reject(new Error('Uitnodigingsgegevens ontbreken'));if(!window.PartyQuestInvites||typeof PartyQuestInvites.getById!=='function'||typeof PartyQuestInvites.respond!=='function')return Promise.reject(new Error('Party Quest service is nog niet klaar'));var quest=PartyQuestInvites.getById(questId);if(!quest)return Promise.reject(new Error('Uitnodiging is niet meer actief'));assertToken(t);return PartyQuestInvites.respond(quest,status).then(function(){assertToken(t);return markRead(event,t);});}
  function run(event,action){if(!event)return Promise.resolve(false);var t=token();if(event.householdId&&String(event.householdId)!==String(t.householdId))return Promise.reject(new Error('Deze melding hoort bij een ander gezin'));if(event.type==='task.help.requested')return acceptTaskHelp(event).then(function(){return true;});if(event.type==='partyQuest.invitation.sent')return revokePartyInvitation(event).then(function(){return true;});if(event.type==='partyQuest.created')return respondPartyQuestInvite(event,action==='decline'?'declined':'active').then(function(){return true;});return markRead(event,t).then(function(){return false;});}
  function byId(id){if(!window.NotificationStore)return null;return NotificationStore.list().find(function(n){return String(n.id)===String(id);})||null;}
  function describeStatus(event){if(!event)return{statusLabel:'',detail:'',actions:[]};if(event.householdId){var c=null;try{c=window.HouseholdContext&&HouseholdContext.current?HouseholdContext.current():null;}catch(e){}if(c&&String(event.householdId)!==String(c.householdId))return{statusLabel:'Niet beschikbaar',detail:'Deze melding hoort bij een ander gezin.',actions:[]};}
    if(event.type==='task.help.requested'){var task=taskByEvent(event),me=currentUid();if(!task)return{statusLabel:'Taak niet gevonden',detail:'Deze taak bestaat niet meer.',actions:[]};var already=Array.isArray(task.helpers)&&task.helpers.some(function(h){return String(h&&(h.uid||h.memberId||h.id)||'')===String(me);});if(already)return{statusLabel:'Je helpt al mee',detail:'Je bent al toegevoegd aan “'+String(task.title||task.name||'deze taak')+'”.',actions:[]};var stillOpen=!!task.helpRequested&&String(task.helpRequestedForUid||'')===String(me);if(stillOpen)return{statusLabel:'Open — wacht op jouw reactie',detail:event.body||'Er is hulp gevraagd.',actions:[{label:'Hulp geven',action:'run',cls:''}]};return{statusLabel:'Niet meer actief',detail:'Deze hulpvraag is ingetrokken, of is al door iemand anders opgepakt.',actions:[]};}
    if(event.type==='partyQuest.created'){var qid=event.data&&event.data.questId,me2=currentUid(),q=window.PartyQuestInvites&&PartyQuestInvites.getById?PartyQuestInvites.getById(qid):null,inv=q&&q.invitees&&q.invitees[me2];if(!q||!inv)return{statusLabel:'Niet meer beschikbaar',detail:'Deze uitnodiging bestaat niet meer.',actions:[]};if(inv.status==='pending')return{statusLabel:'Open — wacht op jouw reactie',detail:event.body||'Je bent uitgenodigd voor een Party Quest.',actions:[{label:'Accepteren',action:'accept',cls:''},{label:'Weigeren',action:'decline',cls:'is-danger'}]};if(inv.status==='active')return{statusLabel:'Geaccepteerd ✓',detail:'Je doet mee aan deze Party Quest.',actions:[]};if(inv.status==='declined')return{statusLabel:'Geweigerd',detail:'Je hebt deze uitnodiging geweigerd.',actions:[]};if(inv.status==='revoked')return{statusLabel:'Ingetrokken',detail:'De maker heeft deze uitnodiging ingetrokken.',actions:[]};}
    if(event.type==='partyQuest.invitation.sent'){var qid2=event.data&&event.data.questId,target=event.data&&event.data.inviteeUid,q2=window.PartyQuestInvites&&PartyQuestInvites.getById?PartyQuestInvites.getById(qid2):null,inv2=q2&&q2.invitees&&target&&q2.invitees[target];if(!q2||!inv2)return{statusLabel:'Niet meer beschikbaar',detail:'Deze uitnodiging bestaat niet meer.',actions:[]};if(inv2.status==='pending')return{statusLabel:'Wacht op reactie',detail:event.body||'',actions:[{label:'Uitnodiging intrekken',action:'run',cls:'is-danger'}]};if(inv2.status==='active')return{statusLabel:'Geaccepteerd ✓',detail:'',actions:[]};if(inv2.status==='declined')return{statusLabel:'Geweigerd',detail:'',actions:[]};if(inv2.status==='revoked')return{statusLabel:'Al ingetrokken',detail:'',actions:[]};}
    return{statusLabel:'',detail:event.body||'',actions:[]};}
  window.NotificationActions={version:VERSION,isActionable:isActionable,actionLabel:actionLabel,run:run,acceptTaskHelp:acceptTaskHelp,revokePartyInvitation:revokePartyInvitation,respondPartyQuestInvite:respondPartyQuestInvite,describeStatus:describeStatus,byId:byId};
})();
