'use strict';
(function(){
  if(window.NotificationEvents&&window.NotificationEvents.version==='2.0.0')return;
  var VERSION='2.0.0';
  function currentUid(){try{return window.HouseholdContext&&HouseholdContext.requireUser?HouseholdContext.requireUser():null;}catch(e){return null;}}
  function members(){try{if(window.HouseholdIdentityFirebaseBridge&&typeof HouseholdIdentityFirebaseBridge.getMembers==='function'){var live=HouseholdIdentityFirebaseBridge.getMembers()||[];if(live.length)return live;}if(window.TaskSharedData&&typeof TaskSharedData.members==='function')return TaskSharedData.members()||[];}catch(e){}return[];}
  function memberUid(m){return m&&(m.uid||m.id)||null;}function memberName(uid){var m=members().find(function(x){return String(memberUid(x))===String(uid);});return m&&(m.displayName||m.name)||'Gezinslid';}function currentName(){return memberName(currentUid());}
  function activeMembers(){return members().filter(function(m){return memberUid(m)&&m.status!=='inactive'&&m.status!=='removed';});}function otherMemberUids(){var me=currentUid();return activeMembers().map(memberUid).filter(function(id){return id&&String(id)!==String(me);});}
  function taskAssigneeUids(task){var out=[];if(task&&task.assignedToUids&&typeof task.assignedToUids==='object')Object.keys(task.assignedToUids).forEach(function(id){if(task.assignedToUids[id])out.push(id);});if(task&&task.assignedToUid)out.push(task.assignedToUid);return Array.from(new Set(out.filter(Boolean).map(String)));}
  function entity(type,id){return{type:type,id:String(id==null?'':id)};}function store(){if(!window.NotificationStore)throw new Error('NotificationStore niet beschikbaar');return NotificationStore;}function publishTo(type,uids,payload){uids=Array.from(new Set((uids||[]).filter(Boolean).map(String)));if(!uids.length)return Promise.resolve(null);return store().publishToUids(type,uids,payload);}function publishHousehold(type,payload){return store().publishHousehold(type,payload);}function questLabel(q){return String(q&&(q.questTitle||q.title||q.name)||'Party Quest');}
  function taskHelpRequested(task,targetUid){var recipients=(targetUid?[String(targetUid)]:otherMemberUids()).filter(function(id){return id!==currentUid();});return publishTo('task.help.requested',recipients,{icon:'help',bg:'#dbeafe',tone:'action',title:'Hulp gevraagd',body:currentName()+' vraagt hulp bij “'+String(task&&(task.title||task.name)||'taak')+'”.',entity:entity('task',task&&(task.id||task._key)),data:{taskId:String(task&&task.id||''),taskKey:String(task&&task._key||''),targetUid:targetUid?String(targetUid):'',action:'help'}});}
  function taskHelpJoined(task,requesterUid){var recipients=requesterUid?[String(requesterUid)]:taskAssigneeUids(task).filter(function(id){return id!==currentUid();});return publishTo('task.help.joined',recipients,{icon:'party',bg:'#dcfce7',tone:'success',title:'Hulp onderweg',body:currentName()+' helpt mee met “'+String(task&&(task.title||task.name)||'taak')+'”.',entity:entity('task',task&&(task.id||task._key)),data:{taskId:String(task&&task.id||''),taskKey:String(task&&task._key||''),requesterUid:String(requesterUid||''),action:'helpJoined'}});}
  function taskSwapRequested(task,targetUid){if(!targetUid)return Promise.reject(new Error('Ontvanger ontbreekt'));return publishTo('task.swap.requested',[targetUid],{icon:'undo',bg:'#ede9fe',tone:'action',title:'Ruilverzoek',body:currentName()+' wil “'+String(task&&(task.title||task.name)||'taak')+'” met je ruilen.',entity:entity('task',task&&(task.id||task._key)),data:{taskId:String(task&&task.id||''),taskKey:String(task&&task._key||''),action:'swapRequested',targetUid:String(targetUid)}});}
  function taskSwapResolved(task,requesterUid,accepted){if(!requesterUid)return Promise.resolve(null);return publishTo(accepted?'task.swap.accepted':'task.swap.declined',[requesterUid],{icon:accepted?'tasks':'undo',bg:accepted?'#dcfce7':'#f1f5f9',tone:accepted?'success':'neutral',title:accepted?'Ruil geaccepteerd':'Ruil afgewezen',body:currentName()+(accepted?' accepteerde ':' wees ')+'het ruilverzoek voor “'+String(task&&(task.title||task.name)||'taak')+'”'+(accepted?' toe.':' af.'),entity:entity('task',task&&(task.id||task._key)),data:{taskId:String(task&&task.id||''),taskKey:String(task&&task._key||''),action:accepted?'swapAccepted':'swapDeclined'}});}
  function partyQuestCreated(q,targetUids){var recipients=(Array.isArray(targetUids)&&targetUids.length?targetUids:otherMemberUids()).filter(function(id){return String(id)!==String(currentUid());});return publishTo('partyQuest.created',recipients,{icon:'party',bg:'#ede9fe',tone:'action',title:'Nieuwe Party Quest',body:currentName()+' nodigt je uit voor “'+questLabel(q)+'”.',entity:entity('partyQuest',q&&(q.id||q._key)),data:{questId:String(q&&q.id||''),questTaskId:String(q&&q.questId||''),action:'created'}});}
  function partyQuestInvitationSent(q,targetUid){var owner=String(q&&q.inviterUid||currentUid()||'');if(!owner||!targetUid)return Promise.resolve(null);return publishTo('partyQuest.invitation.sent',[owner],{icon:'party',bg:'#fef3c7',tone:'action',title:'Uitnodiging verstuurd',body:memberName(targetUid)+' is uitgenodigd voor “'+questLabel(q)+'”.',entity:entity('partyQuest',q&&(q.id||q._key)),data:{questId:String(q&&q.id||''),questTaskId:String(q&&q.questId||''),inviteeUid:String(targetUid),action:'revokeInvitation'}});}
  function partyQuestJoined(q,ownerUid){return publishTo('partyQuest.joined',ownerUid?[ownerUid]:[],{icon:'party',bg:'#dbeafe',tone:'success',title:'Party-lid aangesloten',body:currentName()+' doet mee met “'+questLabel(q)+'”.',entity:entity('partyQuest',q&&(q.id||q._key)),data:{questId:String(q&&q.id||''),questTaskId:String(q&&q.questId||''),action:'joined'}});}
  function partyQuestCompleted(q){return publishHousehold('partyQuest.completed',{icon:'party',bg:'#fef3c7',tone:'celebration',title:'Party Quest voltooid!',body:'“'+questLabel(q)+'” is samen voltooid.',entity:entity('partyQuest',q&&(q.id||q._key)),data:{questId:String(q&&q.id||''),questTaskId:String(q&&q.questId||''),action:'completed'}});}
  function financeSavingsUpdated(goal,tx){tx=tx||{};var type=tx.type==='withdrawal'?'withdrawal':'deposit',amount=Math.abs(Number(tx.amount)||0),who=tx.who||currentName();return publishTo('finance.savings.updated',otherMemberUids(),{icon:'tasks',bg:'#dbeafe',tone:'finance',title:String(goal&&goal.icon||'🎯')+' '+String(goal&&goal.name||'Spaardoel'),body:String(who)+' '+(type==='deposit'?'zette € ':'nam € ')+amount.toFixed(0)+(type==='deposit'?' opzij':' op'),entity:entity('savingsGoal',goal&&goal.id),data:{goalId:String(goal&&goal.id||''),transactionType:type,amount:amount,who:String(who),date:String(tx.date||''),note:String(tx.note||'')}});}
  window.NotificationEvents={version:VERSION,members:activeMembers,otherMemberUids:otherMemberUids,taskAssigneeUids:taskAssigneeUids,taskHelpRequested:taskHelpRequested,taskHelpJoined:taskHelpJoined,taskSwapRequested:taskSwapRequested,taskSwapResolved:taskSwapResolved,partyQuestCreated:partyQuestCreated,partyQuestInvitationSent:partyQuestInvitationSent,partyQuestJoined:partyQuestJoined,partyQuestCompleted:partyQuestCompleted,financeSavingsUpdated:financeSavingsUpdated};
})();
