'use strict';
// ============================================================
// FAMILYAPP PROGRESSION ENGINE v2.0.1
// UID-private progression authority at users/{uid}/private/progression/current.
// ============================================================
(function(){
  if(window.FamilyProgression&&window.FamilyProgression.version==='2.0.1')return;
  var VERSION='2.0.1',COLLECTION='progression',STATE_KEY='current',state=null,ready=false,saveTimer=null,unsubscribe=null,boundToken=null;
  function now(){return Date.now();}function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}function fds(){return window.FamilyDataStore||null;}function hc(){return window.HouseholdContext||null;}
  function skillDefs(){return Array.isArray(window.SKILL_DEFS)?window.SKILL_DEFS:[];}function skillLevel(xp){return typeof window.skillLevelFromXp==='function'?window.skillLevelFromXp(xp):1;}
  function capture(){var c=hc();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function same(t){return!!(t&&hc()&&hc().isCurrent(t));}function assertToken(t){if(!same(t)){var e=new Error('PROGRESSION_CONTEXT_CHANGED');e.code='PROGRESSION_CONTEXT_CHANGED';throw e;}return t;}
  function levelXp(lv){return Math.floor(70+(lv*55)+Math.pow(lv,1.7)*4);}function totalForLevel(lv){var t=0;for(var i=1;i<lv;i++)t+=levelXp(i);return t;}function levelFromXp(xp){var lv=1,x=Math.max(0,Number(xp)||0);while(x>=totalForLevel(lv+1)&&lv<100)lv++;return lv;}
  function blankSkill(){return{xp:0,log:[],updatedAt:0};}
  function defaultState(t){var skills={};skillDefs().forEach(function(d){skills[d.id]=blankSkill();});return{schemaVersion:2,uid:t&&t.uid||null,totalXp:0,level:1,skills:skills,stats:{tasksCompleted:0,skillActions:0},streak:{current:0,best:0,lastActiveDate:null},achievements:{},events:{},createdAt:now(),updatedAt:now(),updatedBy:t&&t.uid||null};}
  function normalize(raw,t){var out=Object.assign(defaultState(t),raw||{});out.schemaVersion=2;out.uid=t&&t.uid||out.uid||null;out.totalXp=Math.max(0,Number(out.totalXp)||0);out.level=levelFromXp(out.totalXp);out.skills=out.skills||{};skillDefs().forEach(function(d){var sk=out.skills[d.id]||blankSkill();sk.xp=Math.max(0,Number(sk.xp)||0);sk.log=Array.isArray(sk.log)?sk.log:[];out.skills[d.id]=sk;});out.stats=Object.assign({tasksCompleted:0,skillActions:0},out.stats||{});out.streak=Object.assign({current:0,best:0,lastActiveDate:null},out.streak||{});out.achievements=out.achievements||{};out.events=out.events||{};return out;}
  function emit(type,detail){try{window.dispatchEvent(new CustomEvent('familyapp:progression:'+type,{detail:detail||{}}));}catch(e){}try{window.dispatchEvent(new CustomEvent('familyapp:progression-updated',{detail:Object.assign({uid:boundToken&&boundToken.uid||null,householdId:boundToken&&boundToken.householdId||null},detail||{})}));}catch(e){}}
  function stop(){if(saveTimer)clearTimeout(saveTimer);saveTimer=null;if(unsubscribe)try{unsubscribe();}catch(e){}unsubscribe=null;boundToken=null;state=null;ready=false;}
  function persist(token){token=token||boundToken;if(!state||!token)return Promise.resolve(false);assertToken(token);state.updatedAt=now();state.updatedBy=token.uid;var payload=clone(state);return fds().writePrivateRecord(COLLECTION,STATE_KEY,payload).then(function(r){assertToken(token);return r;});}
  function persistSoon(){var token=boundToken;if(!token)return;if(saveTimer)clearTimeout(saveTimer);saveTimer=setTimeout(function(){saveTimer=null;if(!same(token))return;persist(token).catch(function(e){if(e&&e.code!=='PROGRESSION_CONTEXT_CHANGED')console.warn('[FamilyProgression] persist failed',e);});},120);}
  function eventSeen(id){return!!(id&&state&&state.events&&state.events[id]);}
  function markEvent(id,payload){if(!id)return;state.events[id]=Object.assign({at:now()},payload||{});var ids=Object.keys(state.events);if(ids.length>500){ids.sort(function(a,b){return(state.events[a].at||0)-(state.events[b].at||0);});ids.slice(0,ids.length-400).forEach(function(k){delete state.events[k];});}}
  function awardXp(amount,meta){var token=boundToken;assertToken(token);if(!ready||!state)return null;amount=Math.max(0,Math.round(Number(amount)||0));meta=meta||{};if(!amount||meta.eventId&&eventSeen(meta.eventId))return meta.eventId?{duplicate:true,state:clone(state)}:null;var before=state.level;state.totalXp+=amount;state.level=levelFromXp(state.totalXp);if(meta.type==='task')state.stats.tasksCompleted++;markEvent(meta.eventId,{type:meta.type||'xp',amount:amount,source:meta.source||''});persistSoon();emit('xp',{amount:amount,beforeLevel:before,level:state.level,totalXp:state.totalXp,meta:meta});if(state.level>before)emit('levelup',{from:before,to:state.level,totalXp:state.totalXp});return{amount:amount,level:state.level,totalXp:state.totalXp};}
  function awardSkill(skillId,amount,meta){var token=boundToken;assertToken(token);if(!ready||!state)return null;meta=meta||{};if(meta.eventId&&eventSeen(meta.eventId))return{duplicate:true,state:clone(state)};var def=skillDefs().find(function(d){return d.id===skillId;});if(!def)return null;amount=Math.max(0,Math.round(Number(amount!=null?amount:def.xpPerDo)||0));if(!amount)return null;var sk=state.skills[skillId]||blankSkill(),oldLevel=skillLevel(sk.xp);sk.xp+=amount;sk.updatedAt=now();sk.log.push({date:new Date().toISOString(),xp:amount,source:meta.source||'app',uid:token.uid});if(sk.log.length>100)sk.log=sk.log.slice(-100);state.skills[skillId]=sk;state.stats.skillActions++;var newLevel=skillLevel(sk.xp);markEvent(meta.eventId,{type:'skill',skillId:skillId,amount:amount});persistSoon();emit('skill',{skillId:skillId,amount:amount,xp:sk.xp,beforeLevel:oldLevel,level:newLevel,meta:meta});return{skillId:skillId,xp:sk.xp,level:newLevel};}
  function unlockAchievement(id,data){var token=boundToken;assertToken(token);if(!ready||!state||!id)return null;if(state.achievements[id]&&state.achievements[id].unlocked!==false)return{duplicate:true,achievement:clone(state.achievements[id])};var row=Object.assign({id:String(id),unlocked:true,unlockedAt:now(),unlockedBy:token.uid},clone(data||{}));state.achievements[id]=row;markEvent('achievement:'+id,{type:'achievement',achievementId:id});persistSoon();emit('achievement',{achievement:clone(row)});return clone(row);}
  function setStreak(current,lastActiveDate){var token=boundToken;assertToken(token);var n=Math.max(0,Math.round(Number(current)||0));state.streak={current:n,best:Math.max(n,Number(state.streak&&state.streak.best)||0),lastActiveDate:lastActiveDate||state.streak&&state.streak.lastActiveDate||null,updatedAt:now(),updatedBy:token.uid};persistSoon();emit('streak',{streak:clone(state.streak)});return clone(state.streak);}
  function incrementCounter(name,delta){var token=boundToken;assertToken(token);delta=Number(delta)||1;state.stats[name]=Math.max(0,Number(state.stats[name])||0)+delta;persistSoon();return state.stats[name];}
  function stableTaskKey(task){if(!task)return null;if(task.id!=null)return String(task.id);var raw=[task.title||'',task.date||'',task.createdAt||''].join('|'),h=0;for(var i=0;i<raw.length;i++)h=((h<<5)-h)+raw.charCodeAt(i)|0;return'legacy_'+Math.abs(h);}
  function detectSkill(title){var lower=String(title||'').toLowerCase(),map=window.TASK_SKILL_MAP||{},matched=null;(lower.match(/#\w+/g)||[]).forEach(function(tag){if(!matched&&map[tag])matched=map[tag];});if(!matched)Object.keys(map).forEach(function(k){if(!matched&&lower.indexOf(k)>-1)matched=map[k];});return matched;}
  function awardTaskCompletion(task,o){o=o||{};if(!ready||!state||!task)return null;var key=stableTaskKey(task),base='task:'+key+':completion:v1',xp=Math.max(0,Math.round(Number(o.xp!=null?o.xp:4)||4)),account=awardXp(xp,{eventId:base+':xp',type:'task',source:o.source||'task-complete',taskId:task.id}),skillId=o.skillId||detectSkill(task.title),skill=null;if(skillId){var def=skillDefs().find(function(d){return d.id===skillId;});skill=awardSkill(skillId,def?def.xpPerDo:undefined,{eventId:base+':skill:'+skillId,source:o.source||'task-complete'});}emit('taskreward',{taskId:task.id,key:key,account:account,skill:skill,skillId:skillId});return{account:account,skill:skill,skillId:skillId};}
  function applyCollection(collection,token){if(!same(token))return;state=normalize(collection&&collection[STATE_KEY]||{},token);ready=true;window.myXP=state.totalXp;window.unlockedBadges=window.unlockedBadges||{};Object.keys(state.achievements).forEach(function(id){if(state.achievements[id]&&state.achievements[id].unlocked!==false)window.unlockedBadges[id]=true;});emit('ready',{state:clone(state)});}
  function load(){var token;try{token=capture();}catch(e){stop();return Promise.resolve(null);}stop();boundToken=token;return fds().readPrivate(COLLECTION,{}).then(function(collection){assertToken(token);applyCollection(collection,token);unsubscribe=fds().subscribePrivate(COLLECTION,function(value){if(!same(token))return;applyCollection(value,token);},{});return clone(state);}).catch(function(e){if(e&&e.code!=='PROGRESSION_CONTEXT_CHANGED')console.warn('[FamilyProgression] load failed',e);return null;});}
  function boot(){return load();}
  window.FamilyProgression={version:VERSION,boot:boot,load:load,rebind:load,stop:stop,persist:function(){return persist(boundToken);},getState:function(){return state?clone(state):null;},isReady:function(){return!!(ready&&boundToken&&same(boundToken));},status:function(){return{version:VERSION,ready:ready,context:boundToken?clone(boundToken):null};},levelFromXp:levelFromXp,xpForLevel:levelXp,totalXpForLevel:totalForLevel,awardXp:awardXp,awardSkill:awardSkill,unlockAchievement:unlockAchievement,setStreak:setStreak,incrementCounter:incrementCounter,awardTaskCompletion:awardTaskCompletion,eventSeen:eventSeen};
  window.addEventListener('familyapp:household-context-changed',load);window.addEventListener('familyapp:session:cleared',stop);window.addEventListener('online',function(){if(!ready)load();});window.addEventListener('focus',function(){if(!ready)load();});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
