'use strict';
// FAMILYAPP PROGRESSION UNLOCKS v1.1 - account-bound unlock ledger.
(function(){
  if(window.FamilyProgressionUnlocks)return;
  var VERSION='1.1.0',COLLECTION='progressionUnlocks',STATE_KEY='current',ledger={schemaVersion:1,unlocks:{},updatedAt:0},ready=false,saveTimer=null,wrapped=false;
  var MILESTONES={5:{icon:'🧦',title:'Level 5 bereikt'},10:{icon:'⚡',title:'Level 10 bereikt'},15:{icon:'🏅',title:'Level 15 bereikt'},20:{icon:'👑',title:'Level 20 bereikt'},25:{icon:'💎',title:'Level 25 bereikt'},30:{icon:'🌌',title:'Level 30 bereikt'},35:{icon:'🌀',title:'Level 35 bereikt'}};
  function now(){return Date.now();}function clone(v){return JSON.parse(JSON.stringify(v));}function has(id){return !!(id&&ledger.unlocks&&ledger.unlocks[id]);}function mark(id,data){if(!id||has(id))return false;ledger.unlocks[id]=Object.assign({id:id,unlockedAt:now()},data||{});ledger.updatedAt=now();persistSoon();return true;}function persistSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,180);}function persist(){return window.FamilyDataStore&&FamilyDataStore.writePrivateRecord?FamilyDataStore.writePrivateRecord(COLLECTION,STATE_KEY,ledger):Promise.resolve({mode:'unavailable'});}function load(){if(!window.FamilyDataStore)return Promise.resolve(null);return FamilyDataStore.readPrivate(COLLECTION,{}).then(function(c){ledger=Object.assign({schemaVersion:1,unlocks:{},updatedAt:0},c&&c[STATE_KEY]||{});ledger.unlocks=ledger.unlocks||{};ready=true;return clone(ledger);});}
  function show(p){if(typeof window.queueUnlock==='function')return window.queueUnlock(p);if(typeof window.showToast==='function')showToast((p.icon||'🏆')+' '+(p.title||'Unlock!'));}function onLevelUp(ev){if(!ready)return;var d=ev&&ev.detail||{},from=Number(d.from)||0,to=Number(d.to)||0;for(var lv=from+1;lv<=to;lv++){var id='level:'+lv,m=MILESTONES[lv];if(!has(id)){mark(id,{kind:'level',level:lv});if(m)show({icon:m.icon,type:'✨ Nieuwe rang',title:m.title,desc:'Account progression milestone',confetti:lv%10===0});}}}function onSkill(ev){if(!ready)return;var d=ev&&ev.detail||{},before=Number(d.beforeLevel)||0,to=Number(d.level)||0;for(var lv=before+1;lv<=to;lv++){var id='skill:'+d.skillId+':'+lv;if(!has(id))mark(id,{kind:'skill',skillId:d.skillId,level:lv});}}
  function stableId(p){p=p||{};var raw=[p.type||'',p.title||'',p.icon||''].join('|').toLowerCase(),h=0;for(var i=0;i<raw.length;i++)h=((h<<5)-h)+raw.charCodeAt(i)|0;return'legacy_'+Math.abs(h);}function wrapLegacy(){if(wrapped||typeof window.queueUnlock!=='function')return false;var original=window.queueUnlock;window.queueUnlock=function(p){p=p||{};var id=p.unlockId||p.id?('legacy:'+(p.unlockId||p.id)):stableId(p);if(ready&&has(id))return false;if(ready)mark(id,{kind:'legacy',title:p.title||'',type:p.type||'',icon:p.icon||''});return original.apply(this,arguments);};wrapped=true;return true;}
  function boot(){var tries=0,t=setInterval(function(){tries++;if(window.FamilyDataStore&&window.FamilyProgression&&FamilyProgression.isReady&&FamilyProgression.isReady()){clearInterval(t);load().then(wrapLegacy);}else if(tries>300)clearInterval(t);},100);window.addEventListener('familyapp:progression:levelup',onLevelUp);window.addEventListener('familyapp:progression:skill',onSkill);}
  window.FamilyProgressionUnlocks={version:VERSION,load:load,persist:persist,has:has,mark:mark,getLedger:function(){return clone(ledger);}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
