'use strict';
// FAMILYAPP PROGRESSION ENGINE v1.2 - Firebase UID private progression.
(function(){
  if(window.FamilyProgression)return;
  var VERSION='1.2.0',COLLECTION='progression',STATE_KEY='current',state=null,ready=false,saveTimer=null;
  function now(){return Date.now();}function clone(v){return JSON.parse(JSON.stringify(v));}
  function user(){try{return window.fbUser||(window.firebase&&firebase.auth&&firebase.auth().currentUser)||null;}catch(e){return null;}}
  function levelXp(lv){return Math.floor(70+(lv*55)+Math.pow(lv,1.7)*4);}function totalForLevel(lv){var t=0;for(var i=1;i<lv;i++)t+=levelXp(i);return t;}function levelFromXp(xp){var lv=1,x=Math.max(0,Number(xp)||0);while(x>=totalForLevel(lv+1)&&lv<100)lv++;return lv;}
  function blankSkill(){return{xp:0,log:[],updatedAt:0};}
  function defaultState(){var skills={};if(Array.isArray(window.SKILL_DEFS))SKILL_DEFS.forEach(function(d){skills[d.id]=blankSkill();});return{schemaVersion:1,totalXp:0,level:1,skills:skills,stats:{tasksCompleted:0,skillActions:0},events:{},createdAt:now(),updatedAt:now()};}
  function normalize(raw){var out=Object.assign(defaultState(),raw||{});out.totalXp=Math.max(0,Number(out.totalXp)||0);out.level=levelFromXp(out.totalXp);out.skills=out.skills||{};if(Array.isArray(window.SKILL_DEFS))SKILL_DEFS.forEach(function(d){var sk=out.skills[d.id]||blankSkill();sk.xp=Math.max(0,Number(sk.xp)||0);sk.log=Array.isArray(sk.log)?sk.log:[];out.skills[d.id]=sk;});out.stats=Object.assign({tasksCompleted:0,skillActions:0},out.stats||{});out.events=out.events||{};return out;}
  function emit(type,detail){try{window.dispatchEvent(new CustomEvent('familyapp:progression:'+type,{detail:detail||{}}));}catch(e){}}
  function persistSoon(){if(saveTimer)clearTimeout(saveTimer);saveTimer=setTimeout(function(){saveTimer=null;persist();},180);}
  function persist(){if(!state)return Promise.resolve();state.updatedAt=now();return window.FamilyDataStore&&FamilyDataStore.writePrivateRecord?FamilyDataStore.writePrivateRecord(COLLECTION,STATE_KEY,state):Promise.resolve({mode:'unavailable'});}
  function eventSeen(id){return !!(id&&state&&state.events&&state.events[id]);}
  function markEvent(id,payload){if(!id)return;state.events[id]=Object.assign({at:now()},payload||{});var ids=Object.keys(state.events);if(ids.length>500){ids.sort(function(a,b){return(state.events[a].at||0)-(state.events[b].at||0);});ids.slice(0,ids.length-400).forEach(function(k){delete state.events[k];});}}
  function awardXp(amount,meta){if(!ready||!state)return null;amount=Math.max(0,Math.round(Number(amount)||0));meta=meta||{};if(!amount||meta.eventId&&eventSeen(meta.eventId))return meta.eventId?{duplicate:true,state:clone(state)}:null;var before=state.level;state.totalXp+=amount;state.level=levelFromXp(state.totalXp);if(meta.type==='task')state.stats.tasksCompleted++;markEvent(meta.eventId,{type:meta.type||'xp',amount:amount,source:meta.source||''});persistSoon();emit('xp',{amount:amount,beforeLevel:before,level:state.level,totalXp:state.totalXp,meta:meta});if(state.level>before)emit('levelup',{from:before,to:state.level,totalXp:state.totalXp});return{amount:amount,level:state.level,totalXp:state.totalXp};}
  function awardSkill(skillId,amount,meta){if(!ready||!state)return null;meta=meta||{};if(meta.eventId&&eventSeen(meta.eventId))return{duplicate:true,state:clone(state)};var def=Array.isArray(window.SKILL_DEFS)&&SKILL_DEFS.find(function(d){return d.id===skillId;});if(!def)return null;amount=Math.max(0,Math.round(Number(amount!=null?amount:def.xpPerDo)||0));if(!amount)return null;var sk=state.skills[skillId]||blankSkill(),oldLevel=typeof window.skillLevelFromXp==='function'?skillLevelFromXp(sk.xp):1;sk.xp+=amount;sk.updatedAt=now();sk.log.push({date:new Date().toISOString(),xp:amount,source:meta.source||'app'});if(sk.log.length>100)sk.log=sk.log.slice(-100);state.skills[skillId]=sk;state.stats.skillActions++;var newLevel=typeof window.skillLevelFromXp==='function'?skillLevelFromXp(sk.xp):oldLevel;markEvent(meta.eventId,{type:'skill',skillId:skillId,amount:amount});persistSoon();emit('skill',{skillId:skillId,amount:amount,xp:sk.xp,beforeLevel:oldLevel,level:newLevel,meta:meta});return{skillId:skillId,xp:sk.xp,level:newLevel};}
  function stableTaskKey(task){if(!task)return null;if(task.id!=null)return String(task.id);var raw=[task.title||'',task.date||'',task.createdAt||''].join('|'),h=0;for(var i=0;i<raw.length;i++)h=((h<<5)-h)+raw.charCodeAt(i)|0;return'legacy_'+Math.abs(h);}
  function detectSkill(title){var lower=String(title||'').toLowerCase(),map=window.TASK_SKILL_MAP||{},matched=null;(lower.match(/#\w+/g)||[]).forEach(function(tag){if(!matched&&map[tag])matched=map[tag];});if(!matched)Object.keys(map).forEach(function(k){if(!matched&&lower.indexOf(k)>-1)matched=map[k];});return matched;}
  function awardTaskCompletion(task,o){o=o||{};if(!ready||!state||!task)return null;var key=stableTaskKey(task),base='task:'+key+':completion:v1',xp=Math.max(0,Math.round(Number(o.xp!=null?o.xp:4)||4)),account=awardXp(xp,{eventId:base+':xp',type:'task',source:o.source||'task-complete',taskId:task.id}),skillId=o.skillId||detectSkill(task.title),skill=null;if(skillId){var def=Array.isArray(window.SKILL_DEFS)&&SKILL_DEFS.find(function(d){return d.id===skillId;});skill=awardSkill(skillId,def?def.xpPerDo:undefined,{eventId:base+':skill:'+skillId,source:o.source||'task-complete'});}emit('taskreward',{taskId:task.id,key:key,account:account,skill:skill,skillId:skillId});return{account:account,skill:skill,skillId:skillId};}
  function load(){if(!user()||!window.FamilyDataStore)return Promise.resolve(null);return FamilyDataStore.readPrivate(COLLECTION,{}).then(function(collection){state=normalize(collection&&collection[STATE_KEY]||{});ready=true;emit('ready',{state:clone(state)});return clone(state);});}
  function boot(){var tries=0,t=setInterval(function(){tries++;if(user()&&window.FamilyDataStore){clearInterval(t);load();}else if(tries>300)clearInterval(t);},100);}
  window.FamilyProgression={version:VERSION,boot:boot,load:load,persist:persist,getState:function(){return state?clone(state):null;},isReady:function(){return ready;},levelFromXp:levelFromXp,xpForLevel:levelXp,totalXpForLevel:totalForLevel,awardXp:awardXp,awardSkill:awardSkill,awardTaskCompletion:awardTaskCompletion,eventSeen:eventSeen};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
