'use strict';
// ============================================================
// PROGRESSION STORE v1.0.0
// UID-private source of truth for XP, achievements, streaks and skills.
// Household-facing activity is projection only, never progression authority.
// ============================================================
(function(){
  if(window.ProgressionStore&&window.ProgressionStore.version==='1.0.0')return;
  var VERSION='1.0.0',COLLECTION='progression';
  var state=null,unsubscribe=null,boundToken=null,readyPromise=null;
  function fds(){return window.FamilyDataStore||null;}function hc(){return window.HouseholdContext||null;}function now(){return Date.now();}
  function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
  function capture(){var c=hc();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function same(t){return!!(t&&hc()&&hc().isCurrent(t));}
  function assertToken(t){if(!same(t)){var e=new Error('PROGRESSION_CONTEXT_CHANGED');e.code='PROGRESSION_CONTEXT_CHANGED';throw e;}return t;}
  function blank(t){return{schemaVersion:1,uid:t&&t.uid||null,xp:0,achievements:{},streak:{current:0,best:0,lastActiveDate:null},skills:{},counters:{},meta:{createdAt:now(),updatedAt:now(),updatedBy:t&&t.uid||null}};}
  function normalize(v,t){v=v&&typeof v==='object'?clone(v):blank(t);v.schemaVersion=1;v.uid=t&&t.uid||v.uid||null;v.xp=Math.max(0,Math.round(Number(v.xp)||0));v.achievements=v.achievements&&typeof v.achievements==='object'?v.achievements:{};v.streak=v.streak&&typeof v.streak==='object'?v.streak:{current:0,best:0,lastActiveDate:null};v.streak.current=Math.max(0,Number(v.streak.current)||0);v.streak.best=Math.max(v.streak.current,Number(v.streak.best)||0);v.skills=v.skills&&typeof v.skills==='object'?v.skills:{};v.counters=v.counters&&typeof v.counters==='object'?v.counters:{};v.meta=v.meta||{};return v;}
  function displayName(uid){try{var list=window.HouseholdIdentityFirebaseBridge&&HouseholdIdentityFirebaseBridge.getMembers?HouseholdIdentityFirebaseBridge.getMembers():[];var m=(list||[]).find(function(x){return String(x.uid||x.id)===String(uid);});return m&&(m.displayName||m.name)||'Gezinslid';}catch(e){return'Gezinslid';}}
  function legacySeed(t){var out=blank(t),xp=Number(window.myXP);if(isFinite(xp)&&xp>0)out.xp=Math.round(xp);var badges=window.unlockedBadges||{};Object.keys(badges).forEach(function(id){if(badges[id])out.achievements[id]={unlocked:true,unlockedAt:now(),migrated:true};});try{var raw=localStorage.getItem('fam_skills_v1');if(raw){var parsed=JSON.parse(raw),name=displayName(t.uid),source=parsed[name]||null;if(source&&typeof source==='object')out.skills=clone(source);}}catch(e){}out.meta.migratedLegacyAt=now();return out;}
  function project(){var s=normalize(state||blank(boundToken),boundToken);window.myXP=s.xp;window.unlockedBadges=window.unlockedBadges||{};Object.keys(s.achievements).forEach(function(id){if(s.achievements[id]&&s.achievements[id].unlocked!==false)window.unlockedBadges[id]=true;});try{localStorage.setItem('fam_myxp_v1',String(s.xp));}catch(e){}try{window.dispatchEvent(new CustomEvent('familyapp:progression-updated',{detail:{uid:boundToken&&boundToken.uid||null,householdId:boundToken&&boundToken.householdId||null,xp:s.xp,streak:clone(s.streak)}}));}catch(e){}try{if(typeof window.renderAch==='function')window.renderAch();if(typeof window.renderSkills==='function')window.renderSkills();}catch(e){}}
  function stop(){if(unsubscribe)try{unsubscribe();}catch(e){}unsubscribe=null;boundToken=null;readyPromise=null;state=null;}
  function subscribe(t){if(unsubscribe)try{unsubscribe();}catch(e){}unsubscribe=fds().subscribePrivate(COLLECTION,function(v){if(!same(t))return;state=normalize(v,t);project();},blank(t));}
  function initialize(t){return fds().readPrivate(COLLECTION,null).then(function(existing){assertToken(t);if(existing&&existing.schemaVersion){state=normalize(existing,t);return state;}var seed=legacySeed(t);return fds().writePrivate(COLLECTION,seed).then(function(){assertToken(t);state=seed;return seed;});}).then(function(v){assertToken(t);project();subscribe(t);return true;});}
  function ready(){if(boundToken&&same(boundToken)&&unsubscribe)return Promise.resolve(true);if(readyPromise)return readyPromise;var t;try{t=capture();}catch(e){return Promise.resolve(false);}boundToken=t;readyPromise=initialize(t).catch(function(e){if(e&&e.code!=='PROGRESSION_CONTEXT_CHANGED')console.warn('[ProgressionStore]',e);return false;}).then(function(v){readyPromise=null;return v;});return readyPromise;}
  function rebind(){stop();return ready();}
  function mutate(path,fn,fallback){var t=capture();return ready().then(function(){assertToken(t);return fds().transactPrivatePath(COLLECTION,path,fn,fallback);}).then(function(r){assertToken(t);return r&&r.value;});}
  function awardXP(amount,reason,meta){var t=capture(),delta=Math.max(0,Math.round(Number(amount)||0));if(!delta)return Promise.resolve(get());return mutate(['xp'],function(v){return Math.max(0,Math.round(Number(v)||0))+delta;},0).then(function(xp){assertToken(t);return mutate(['meta'],function(m){return Object.assign({},m||{},{updatedAt:now(),updatedBy:t.uid,lastXpReason:String(reason||''),lastXpMeta:clone(meta||{})});},{}).then(function(){return{xp:xp,delta:delta};});});}
  function unlockAchievement(id,data){var t=capture(),payload=Object.assign({unlocked:true,unlockedAt:now()},clone(data||{}));return mutate(['achievements',String(id)],function(existing){return existing&&existing.unlocked!==false?existing:Object.assign({},payload,{unlockedBy:t.uid});},null).then(function(row){assertToken(t);if(window.ActivityService&&typeof ActivityService.publish==='function'&&row&&row.unlocked){ActivityService.publish({type:'achievement.unlocked',module:'progression',entityType:'achievement',entityId:String(id),idempotencyKey:'achievement:'+t.uid+':'+id,payload:{achievementId:String(id),name:String(row.name||''),icon:String(row.icon||''),xp:Number(row.xp||0)||0}}).catch(function(){});}return clone(row);});}
  function logSkill(skillId,xp,meta){var t=capture(),id=String(skillId),delta=Math.max(0,Math.round(Number(xp)||0)),entry={id:(fds().makeId?fds().makeId('skilllog'):'skill_'+now()),xp:delta,at:now(),createdBy:t.uid,meta:clone(meta||{})};return mutate(['skills',id],function(cur){cur=cur&&typeof cur==='object'?clone(cur):{xp:0,log:[]};cur.xp=Math.max(0,Number(cur.xp)||0)+delta;cur.log=Array.isArray(cur.log)?cur.log:[];cur.log.push(entry);cur.updatedAt=entry.at;return cur;},{xp:0,log:[]});}
  function setStreak(current,lastActiveDate){var t=capture(),n=Math.max(0,Math.round(Number(current)||0));return mutate(['streak'],function(s){s=s||{};return{current:n,best:Math.max(n,Number(s.best)||0),lastActiveDate:lastActiveDate||s.lastActiveDate||null,updatedAt:now(),updatedBy:t.uid};},{current:0,best:0,lastActiveDate:null});}
  function incrementCounter(name,delta){delta=Number(delta)||1;return mutate(['counters',String(name)],function(v){return Math.max(0,Number(v)||0)+delta;},0);}
  function get(){return normalize(state||blank(boundToken),boundToken);}function skill(id){var s=get().skills[String(id)]||{xp:0,log:[]};return clone(s);}
  window.ProgressionStore={version:VERSION,ready:ready,start:ready,stop:stop,rebind:rebind,get:get,awardXP:awardXP,unlockAchievement:unlockAchievement,logSkill:logSkill,setStreak:setStreak,incrementCounter:incrementCounter,skill:skill,status:function(){return{version:VERSION,context:boundToken?clone(boundToken):null,ready:!!(boundToken&&same(boundToken)&&unsubscribe),xp:get().xp};}};
  window.addEventListener('familyapp:household-context-changed',rebind);window.addEventListener('familyapp:session:cleared',stop);window.addEventListener('online',ready);window.addEventListener('focus',ready);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
