'use strict';
// REACTIVE HOUSEHOLD STATE v0.308 - compatibility event state backed by Firebase household identity.
(function(){
  var VERSION='0.308',subscribers={},state={version:VERSION,ready:false,updatedAt:new Date().toISOString(),household:null,activeMember:null,members:[],groupQuests:[],presence:{}};
  function nowIso(){return new Date().toISOString();}function safeCall(fn,payload){try{fn(payload);}catch(e){console.warn('[ReactiveHouseholdState] subscriber failed',e);}}function emit(channel,payload){(subscribers[channel]||[]).forEach(function(fn){safeCall(fn,payload);});(subscribers['*']||[]).forEach(function(fn){safeCall(fn,{channel:channel,payload:payload});});try{window.dispatchEvent(new CustomEvent('familyapp:state:'+channel,{detail:payload}));}catch(e){}}
  function subscribe(channel,callback){if(!subscribers[channel])subscribers[channel]=[];subscribers[channel].push(callback);return function(){subscribers[channel]=(subscribers[channel]||[]).filter(function(fn){return fn!==callback;});};}function snapshot(){return JSON.parse(JSON.stringify(state));}
  function getMembers(){if(window.HouseholdIdentityFirebaseBridge&&typeof HouseholdIdentityFirebaseBridge.getMembers==='function'){var members=HouseholdIdentityFirebaseBridge.getMembers();if(members&&members.length)return members;}if(window.HouseholdIdentity&&typeof HouseholdIdentity.getMembers==='function')return HouseholdIdentity.getMembers();return[];}
  function getActiveMember(){var uid=null;try{var u=window.fbUser||(window.firebase&&firebase.auth&&firebase.auth().currentUser);uid=u&&u.uid;}catch(e){}var members=getMembers();if(uid){var mine=members.find(function(m){return m&&(m.uid===uid||m.id===uid);});if(mine)return mine;}if(window.HouseholdIdentity&&typeof HouseholdIdentity.getActiveMember==='function')return HouseholdIdentity.getActiveMember();return null;}
  function getHousehold(){var hid=window.fbFamilyId||null;if(!hid)return null;return{id:hid,source:'firebase'};}
  function getGroupQuests(){if(typeof window.loadGroupQuests==='function')return window.loadGroupQuests();return[];}
  function refresh(reason){state.household=getHousehold();state.members=getMembers();state.activeMember=getActiveMember();state.groupQuests=getGroupQuests();state.presence={};state.members.forEach(function(m){if(m&&m.id)state.presence[m.id]={online:m.online===true,onlineStatus:m.onlineStatus||'offline',lastSeen:m.lastSeen||null,area:m.area||''};});state.ready=true;state.updatedAt=nowIso();state.reason=reason||'refresh';emit('updated',snapshot());if(reason)emit(reason,snapshot());return snapshot();}
  function setPresence(memberId,patch){if(!memberId)return snapshot();state.presence[memberId]=Object.assign({},state.presence[memberId]||{},patch||{},{updatedAt:nowIso()});emit('presence',{memberId:memberId,presence:state.presence[memberId],state:snapshot()});return snapshot();}
  function setActiveMember(memberId){if(window.HouseholdIdentity&&typeof HouseholdIdentity.setActiveMember==='function')HouseholdIdentity.setActiveMember(memberId);return refresh('active-member');}
  function updateMembers(updater){if(!window.HouseholdIdentity||typeof HouseholdIdentity.saveMembers!=='function')return refresh('members');var current=getMembers(),next=updater?updater(current.slice()):current;HouseholdIdentity.saveMembers(next);return refresh('members');}
  function updateGroupQuests(updater){if(typeof window.loadGroupQuests!=='function'||typeof window.saveGroupQuests!=='function')return refresh('group-quests');var current=window.loadGroupQuests(),next=updater?updater(current.slice()):current;window.saveGroupQuests(next);emit('group-quests',{groupQuests:next,state:refresh('group-quests')});return snapshot();}
  function announceQuestEvent(type,quest,extra){var payload=Object.assign({type:type,quest:quest||null,at:nowIso(),state:snapshot()},extra||{});emit('quest-event',payload);return payload;}
  function installBridgeListeners(){window.addEventListener('familyapp:household-members-updated',function(){refresh('members');});window.addEventListener('familyapp:household-identity-synced',function(){refresh('firebase-identity');});window.addEventListener('familyapp:active-member-updated',function(){refresh('active-member');});window.addEventListener('familyapp:group-quests-updated',function(){refresh('group-quests');});}
  function boot(){installBridgeListeners();refresh('boot');}
  window.ReactiveHouseholdState={version:VERSION,subscribe:subscribe,on:subscribe,emit:emit,refresh:refresh,snapshot:snapshot,setPresence:setPresence,setActiveMember:setActiveMember,updateMembers:updateMembers,updateGroupQuests:updateGroupQuests,announceQuestEvent:announceQuestEvent};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
