'use strict';
// ============================================================
// SEARCH CONTEXT SERVICE v1.0.0
// Read-only search/autocomplete/AI-context boundary.
// Never queries Firebase directly. It only consumes canonical services that
// are already bound to the current UID + household context.
// ============================================================
(function(){
  if(window.SearchContextService&&window.SearchContextService.version==='1.0.0')return;
  var VERSION='1.0.0';
  function hc(){return window.HouseholdContext||null;}
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function capture(){var c=hc();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function same(t){return!!(t&&hc()&&hc().isCurrent(t));}
  function assertToken(t){if(!same(t)){var e=new Error('SEARCH_CONTEXT_CHANGED');e.code='SEARCH_CONTEXT_CHANGED';throw e;}return t;}
  function norm(v){return String(v==null?'':v).toLowerCase().trim();}
  function statusContext(status){if(!status)return null;var c=status.context||status.boundToken||null;if(c&&c.uid&&c.householdId)return{uid:String(c.uid),householdId:String(c.householdId)};if(status.uid&&status.householdId)return{uid:String(status.uid),householdId:String(status.householdId)};return null;}
  function sourceCurrent(status,token){var c=statusContext(status);return!!(c&&String(c.uid)===String(token.uid)&&String(c.householdId)===String(token.householdId));}
  function safeTasks(token){try{var s=window.TaskSharedData&&TaskSharedData.status?TaskSharedData.status():null;if(!sourceCurrent(s,token)||!s.sharedSnapshot)return[];return Array.isArray(window.taskData)?window.taskData.slice():[];}catch(e){return[];}}
  function safeRecipes(token){try{var s=window.RecipeStore&&RecipeStore.status?RecipeStore.status():null;if(!sourceCurrent(s,token)||!s.ready)return[];return RecipeStore.list?RecipeStore.list():[];}catch(e){return[];}}
  function safeShoppingRows(token){try{var s=window.ShoppingLists&&ShoppingLists.status?ShoppingLists.status():null;if(!sourceCurrent(s,token)||!s.bound)return[];var rows=ShoppingLists.all?ShoppingLists.all():[];var out=[];(rows||[]).forEach(function(row){if(!row||!row.list)return;var items=row.list.items||{};Object.keys(items).forEach(function(k){var item=items[k];if(item)out.push(Object.assign({_key:k,listId:row.list.id,listName:row.list.name,scope:row.scope},clone(item)));});});return out;}catch(e){return[];}}
  function safeCalendar(token){try{var s=window.CalendarSharedLive&&CalendarSharedLive.status?CalendarSharedLive.status():null;if(!sourceCurrent(s,token)||!s.attached)return[];return Array.isArray(window.calData)?window.calData.slice():[];}catch(e){return[];}}
  function formatDate(v){try{return typeof window.formatDate==='function'?window.formatDate(v):String(v||'');}catch(e){return String(v||'');}}
  function search(query,options){var token=capture(),q=norm(query),opts=options||{},limit=Math.max(1,Math.min(100,Number(opts.limit)||40));if(q.length<2)return[];var out=[];
    safeTasks(token).forEach(function(t){var hay=norm([t.title,t.description,t.type,t.category].join(' '));if(hay.indexOf(q)>-1)out.push({kind:'task',type:'Taak',icon:'✅',id:String(t.id||t._key||''),label:String(t.title||'Taak'),sub:(t.done||t.status==='completed')?'Gedaan':'Open',screen:'tasks',householdId:token.householdId});});
    safeRecipes(token).forEach(function(r){var ingredients=(r.ingredients||[]).map(function(x){return typeof x==='string'?x:(x.rawText||x.name||'');}).join(' '),hay=norm([r.name,r.cat,r.cuisine,ingredients].join(' '));if(hay.indexOf(q)>-1)out.push({kind:'recipe',type:'Recept',icon:'🍳',id:String(r.id||''),label:String(r.name||'Recept'),sub:String(r.cat||''),screen:'recipes',householdId:token.householdId});});
    safeShoppingRows(token).forEach(function(i){var hay=norm([i.name,i.cat,i.category,i.qty,i.quantity,i.listName].join(' '));if(hay.indexOf(q)>-1)out.push({kind:'shopping',type:'Boodschap',icon:'🛒',id:String(i.id||i._key||''),label:String(i.name||'Boodschap'),sub:String(i.qty||i.quantity||i.cat||i.category||i.listName||''),screen:'shop',householdId:token.householdId});});
    safeCalendar(token).forEach(function(e){var hay=norm([e.title,e.description,e.date,e.time].join(' '));if(hay.indexOf(q)>-1)out.push({kind:'calendar',type:'Agenda',icon:'📅',id:String(e.id||''),label:String(e.title||'Afspraak'),sub:formatDate(e.date),screen:'cal',householdId:token.householdId});});
    assertToken(token);return out.slice(0,limit);
  }
  function shoppingSuggestions(query,staticRows){var token=capture(),q=norm(query);if(!q)return[];var history=safeShoppingRows(token).map(function(i){return{n:String(i.name||''),e:(i.photo&&String(i.photo).indexOf('http')!==0)?i.photo:(i.emoji||i.icon||'🛒'),c:String(i.cat||i.category||'Overig'),q:String(i.qty||i.quantity||'1 stuk')};}).filter(function(i){return i.n;});var all=(Array.isArray(staticRows)?staticRows:[]).concat(history),seen={};all=all.filter(function(i){var k=norm(i&&i.n);if(!k||seen[k])return false;seen[k]=true;return true;});assertToken(token);return all.filter(function(i){return norm(i.n).indexOf(q)>-1;}).slice(0,7);}
  function ingredientSuggestions(query,staticRows){var token=capture(),q=norm(query);if(q.length<2)return[];var existing=[];safeRecipes(token).forEach(function(r){(r.ingredients||[]).forEach(function(ing){var text=typeof ing==='string'?ing:String(ing&& (ing.rawText||ing.text||ing.name)||'');if(text)existing.push(text);});});var all=(Array.isArray(staticRows)?staticRows:[]).concat(existing),seen={};all=all.filter(function(v){var k=norm(v);if(!k||seen[k])return false;seen[k]=true;return true;});assertToken(token);return all.filter(function(v){var n=norm(v);return n.indexOf(q)>-1&&n!==q;}).slice(0,6);}
  function buildAiContext(options){var token=capture(),opts=options||{},requested=Array.isArray(opts.include)?opts.include:['tasks','recipes','calendar','shopping'],allowed={tasks:true,recipes:true,calendar:true,shopping:true,members:true},max=Math.max(1,Math.min(50,Number(opts.maxItems)||20)),payload={schemaVersion:1,scope:{uid:token.uid,householdId:token.householdId},generatedAt:Date.now(),sources:{}};
    requested.forEach(function(key){if(!allowed[key])return;if(key==='tasks')payload.sources.tasks=safeTasks(token).slice(0,max).map(function(t){return{id:String(t.id||t._key||''),title:String(t.title||''),status:(t.done||t.status==='completed')?'completed':'open',dueDate:t.date||t.dueDate||null,assignedToUids:clone(t.assignedToUids||{})};});if(key==='recipes')payload.sources.recipes=safeRecipes(token).slice(0,max).map(function(r){return{id:String(r.id||''),name:String(r.name||''),category:String(r.cat||''),ingredients:(r.ingredients||[]).slice(0,30).map(function(x){return typeof x==='string'?x:String(x.rawText||x.name||'');})};});if(key==='calendar')payload.sources.calendar=safeCalendar(token).slice(0,max).map(function(e){return{id:String(e.id||''),title:String(e.title||''),date:e.date||null,time:e.time||null};});if(key==='shopping')payload.sources.shopping=safeShoppingRows(token).filter(function(i){return!i.done;}).slice(0,max).map(function(i){return{id:String(i.id||i._key||''),name:String(i.name||''),quantity:String(i.qty||i.quantity||''),category:String(i.cat||i.category||''),scope:i.scope};});if(key==='members'){try{payload.sources.members=(window.ProfileContextService&&ProfileContextService.getMembers?ProfileContextService.getMembers():[]).slice(0,max).map(function(m){return{uid:String(m.uid||m.id||''),displayName:String(m.displayName||m.name||''),role:String(m.role||'member')};});}catch(e){payload.sources.members=[];}}});
    // Deliberately excluded: finance, notes, notification contents, private progression,
    // drafts and arbitrary Firebase paths. Future AI callers must opt into allowlisted sources.
    assertToken(token);return payload;
  }
  function status(){var token=null;try{token=capture();}catch(e){}return{version:VERSION,ready:!!token,context:token,sources:{tasks:!!window.TaskSharedData,recipes:!!window.RecipeStore,shopping:!!window.ShoppingLists,calendar:!!window.CalendarSharedLive},notesIncluded:false,aiAllowlist:['tasks','recipes','calendar','shopping','members']};}
  window.SearchContextService={version:VERSION,capture:capture,isCurrent:same,search:search,shoppingSuggestions:shoppingSuggestions,ingredientSuggestions:ingredientSuggestions,buildAiContext:buildAiContext,status:status};
})();
