'use strict';
// ============================================================
// SWIPE TO DELETE
// ============================================================
function attachSwipeDelete(el, onDelete) {
  var startX=0,startY=0,dx=0,moving=false,threshold=80;
  var content=el.querySelector('.swipe-content')||el;
  el.addEventListener('touchstart',function(e){startX=e.touches[0].clientX;startY=e.touches[0].clientY;dx=0;moving=false;},{passive:true});
  el.addEventListener('touchmove',function(e){
    dx=e.touches[0].clientX-startX;var dy=e.touches[0].clientY-startY;
    if(!moving&&Math.abs(dy)>Math.abs(dx))return;
    moving=true;if(dx<0)content.style.transform='translateX('+Math.max(dx,-120)+'px)';
  },{passive:true});
  el.addEventListener('touchend',function(){
    if(dx<-threshold){content.style.transform='translateX(-100%)';content.style.transition='transform .2s';setTimeout(onDelete,200);}
    else{content.style.transform='';content.style.transition='transform .15s';setTimeout(function(){content.style.transition='';},160);}
    dx=0;moving=false;
  },{passive:true});
}

(function installUiPolishV0263(){
  if(window.__uiPolishV0263) return;
  window.__uiPolishV0263=true;
  var link=document.createElement('link');link.rel='stylesheet';link.href='src/styles/ui-polish-v0263.css';link.setAttribute('data-ui-polish-v0263','');document.head.appendChild(link);
  var paths={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/>',tasks:'<rect x="4" y="4" width="16" height="16" rx="4"/><path d="m8 12 2.5 2.5L16.5 9"/>',notes:'<path d="M6 3.5h9l3 3V20H6z"/><path d="M14.5 3.5V7H18"/><path d="M9 11h6M9 15h6"/>',shop:'<path d="M3 5h2l2 10h9.5l2-7H6"/><circle cx="9" cy="19" r="1.2"/><circle cx="16" cy="19" r="1.2"/>',cal:'<rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3v4M16 3v4M4 9h16"/>',finance:'<path d="M4 7.5h15v11H5.5A2.5 2.5 0 0 1 3 16V7a2 2 0 0 1 2-2h11"/><path d="M15 11h5v4h-5a2 2 0 0 1 0-4Z"/>',achievements:'<path d="M8 4h8v4a4 4 0 0 1-8 0Z"/><path d="M8 6H5v2a4 4 0 0 0 4 4M16 6h3v2a4 4 0 0 1-4 4M12 12v4M8.5 20h7M10 16h4"/>',notif:'<path d="M6 16h12l-1.5-2V9a4.5 4.5 0 0 0-9 0v5Z"/><path d="M10 19a2.2 2.2 0 0 0 4 0"/>',profile:'<circle cx="12" cy="8" r="3.5"/><path d="M5 20a7 7 0 0 1 14 0"/>',recipes:'<path d="M8 10a3 3 0 1 1 1-5.8A3.8 3.8 0 0 1 16 5a3 3 0 1 1 0 5H8Z"/><path d="M8 10v8h8v-8M9 14h6"/>',skills:'<path d="m13 2-7 11h6l-1 9 7-12h-6Z"/>',meals:'<path d="M7 3v7M4.5 3v4a2.5 2.5 0 0 0 5 0V3M7 10v11M16 3v18M16 3c3 2 3 7 0 9"/>',templates:'<rect x="5" y="4.5" width="14" height="16" rx="3"/><path d="M9 4.5V3h6v1.5M9 10h6M9 14h6"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.6a6 6 0 0 0-.8-1.9l1-1.8-2.1-2.1-1.8 1A6 6 0 0 0 11.5 4L11 2H8l-.6 2a6 6 0 0 0-1.9.8l-1.8-1-2.1 2.1 1 1.8A6 6 0 0 0 2 10v3l2 .6a6 6 0 0 0 .8 1.9l-1 1.8 2.1 2.1 1.8-1a6 6 0 0 0 1.9.8l.6 2h3l.6-2a6 6 0 0 0 1.9-.8l1.8 1 2.1-2.1-1-1.8a6 6 0 0 0 .4-2Z"/>'};
  function svg(name){return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(paths[name]||paths.more)+'</svg>';}
  function polishNav(){var nav=document.getElementById('bottom-nav');if(nav){nav.querySelectorAll('[data-goto]').forEach(function(btn){var icon=btn.querySelector('.nav-icon');if(icon)icon.innerHTML=svg(btn.dataset.goto);});var more=document.getElementById('nav-more-btn');if(more){var mi=more.querySelector('.nav-icon');if(mi)mi.innerHTML=svg('more');}}var grid=document.getElementById('more-grid');if(grid){grid.querySelectorAll('[data-goto-more]').forEach(function(btn){var first=btn.querySelector('span');if(first){first.className='more-icon';first.innerHTML=svg(btn.dataset.gotoMore);}});var cfg=document.getElementById('nav-config-btn');if(cfg){var ci=cfg.querySelector('span');if(ci){ci.className='more-icon';ci.innerHTML=svg('settings');}cfg.classList.add('is-config');}}}
  if(typeof renderNav==='function'){var originalRenderNav=renderNav;renderNav=function(){var result=originalRenderNav.apply(this,arguments);polishNav();return result;};}
  document.addEventListener('DOMContentLoaded',polishNav);setTimeout(polishNav,0);
})();

(function installMoreMenuDelegation(){if(window.__familyMoreMenuDelegation)return;window.__familyMoreMenuDelegation=true;document.addEventListener('click',function(e){var item=e.target.closest&&e.target.closest('[data-goto-more]');if(!item)return;e.preventDefault();e.stopPropagation();var target=item.getAttribute('data-goto-more');if(target&&typeof showScreenMore==='function')showScreenMore(target);else if(target&&typeof showScreen==='function')showScreen(target);},true);})();
(function installMobileZoomLock(){if(window.__familyMobileZoomLock)return;window.__familyMobileZoomLock=true;var viewport=document.querySelector('meta[name="viewport"]');if(!viewport){viewport=document.createElement('meta');viewport.name='viewport';document.head.appendChild(viewport);}viewport.setAttribute('content','width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, viewport-fit=cover');['gesturestart','gesturechange','gestureend'].forEach(function(type){document.addEventListener(type,function(e){e.preventDefault();},{passive:false});});document.addEventListener('touchmove',function(e){if(e.touches&&e.touches.length>1)e.preventDefault();},{passive:false});var lastTouchEnd=0;document.addEventListener('touchend',function(e){var now=Date.now();if(now-lastTouchEnd<=300)e.preventDefault();lastTouchEnd=now;},{passive:false});})();
(function installNavBusyRecovery(){if(window.__familyNavBusyRecovery)return;window.__familyNavBusyRecovery=true;window.addEventListener('error',function(){if(typeof _navBusy!=='undefined'&&_navBusy)_navBusy=false;});window.addEventListener('unhandledrejection',function(){if(typeof _navBusy!=='undefined'&&_navBusy)_navBusy=false;});})();
(function loadMobileUxFixes(){if(window.__familyMobileUxFixLoader)return;window.__familyMobileUxFixLoader=true;var script=document.createElement('script');script.src='src/core/mobileUxFixes.js?v=1';script.defer=true;document.head.appendChild(script);})();
(function loadGoogleAuthMobileFix(){if(window.__familyGoogleAuthMobileFixLoader)return;window.__familyGoogleAuthMobileFixLoader=true;var script=document.createElement('script');script.src='src/core/googleAuthMobileFix.js?v=1';script.defer=true;document.head.appendChild(script);})();
(function loadHouseholdPlatform(){if(window.__familyHouseholdPlatformLoader)return;window.__familyHouseholdPlatformLoader=true;var script=document.createElement('script');script.src='src/core/householdPlatform.js?v=4';script.async=false;script.defer=true;document.head.appendChild(script);})();
(function loadHouseholdManagerUi(){if(window.__familyHouseholdManagerUiLoader)return;window.__familyHouseholdManagerUiLoader=true;var script=document.createElement('script');script.src='src/core/householdManagerUi.js?v=1';script.async=false;script.defer=true;document.head.appendChild(script);})();

// Ordered notification runtime: persistence -> event API -> actions -> presentation -> projectors.
(function loadFamilyDataStore(){if(window.__familyDataStoreLoader)return;window.__familyDataStoreLoader=true;var script=document.createElement('script');script.src='src/core/familyDataStore.js?v=1';script.async=false;script.defer=true;script.onload=function(){loadNotificationStore();};document.head.appendChild(script);})();
function loadNotificationStore(){if(window.__familyNotificationStoreLoader)return;window.__familyNotificationStoreLoader=true;var script=document.createElement('script');script.src='src/core/notificationStore.js?v=4';script.async=false;script.defer=true;script.onload=function(){loadNotificationEvents();};document.head.appendChild(script);}
function loadNotificationEvents(){if(window.__familyNotificationEventsLoader)return;window.__familyNotificationEventsLoader=true;var script=document.createElement('script');script.src='src/core/notificationEvents.js?v=4';script.async=false;script.defer=true;script.onload=function(){loadNotificationActions();loadTaskNotificationProjector();loadTaskSwapNotificationProjector();loadPartyQuestNotificationProjector();};document.head.appendChild(script);}
function loadNotificationActions(){if(window.__familyNotificationActionsLoader)return;window.__familyNotificationActionsLoader=true;var script=document.createElement('script');script.src='src/core/notificationActions.js?v=2';script.async=false;script.defer=true;script.onload=function(){loadNotificationCenter();loadNotificationDelivery();};document.head.appendChild(script);}
function loadNotificationCenter(){if(window.__familyNotificationCenterLoader)return;window.__familyNotificationCenterLoader=true;var script=document.createElement('script');script.src='src/core/notificationCenter.js?v=1';script.async=false;script.defer=true;document.head.appendChild(script);}
function loadNotificationDelivery(){if(window.__familyNotificationDeliveryLoader)return;window.__familyNotificationDeliveryLoader=true;var script=document.createElement('script');script.src='src/core/notificationDelivery.js?v=3';script.async=false;script.defer=true;document.head.appendChild(script);}
function loadTaskNotificationProjector(){if(window.__familyTaskNotificationProjectorLoader)return;window.__familyTaskNotificationProjectorLoader=true;var script=document.createElement('script');script.src='src/modules/tasks/taskNotificationProjector.js?v=1';script.async=false;script.defer=true;document.head.appendChild(script);}
function loadTaskSwapNotificationProjector(){if(window.__familyTaskSwapNotificationProjectorLoader)return;window.__familyTaskSwapNotificationProjectorLoader=true;var script=document.createElement('script');script.src='src/modules/tasks/taskSwapNotificationProjector.js?v=1';script.async=false;script.defer=true;document.head.appendChild(script);}
function loadPartyQuestNotificationProjector(){if(window.__familyPartyQuestNotificationProjectorLoader)return;window.__familyPartyQuestNotificationProjectorLoader=true;var script=document.createElement('script');script.src='src/modules/tasks/partyQuestNotificationProjector.js?v=2';script.async=false;script.defer=true;document.head.appendChild(script);}

(function loadShoppingLists(){if(window.__familyShoppingListsLoader)return;window.__familyShoppingListsLoader=true;var script=document.createElement('script');script.src='src/modules/shop/shoppingLists.js?v=1';script.async=false;script.defer=true;document.head.appendChild(script);})();
(function loadShoppingSyncDiagnostics(){if(window.__familyShoppingSyncDiagnosticsLoader)return;window.__familyShoppingSyncDiagnosticsLoader=true;var script=document.createElement('script');script.src='src/core/shoppingSyncDiagnostics.js?v=1';script.async=false;script.defer=true;document.head.appendChild(script);})();
