'use strict';
// ============================================================
// ACTIVITY DOMAIN PRODUCERS v1.0
// Transitional domain adapters: successful module mutations -> ActivityService.
// No Feed knowledge belongs here. Activity failures never roll back domain writes.
// ============================================================
(function(){
  if(window.ActivityDomainProducers)return;
  var VERSION='1.0.0',timer=null,tries=0,MAX_TRIES=240;
  function svc(){return window.ActivityService||null;}function now(){return Date.now();}
  function publish(input,label){var s=svc();if(!s||typeof s.publish!=='function')return Promise.resolve(null);return s.publish(input).catch(function(e){console.warn('[ActivityDomainProducers] '+label,e);return null;});}
  function taskTitle(task){return task&&(task.title||task.name)||'Taak';}
  function taskXp(task){var raw=task&&(task.xp||task.rewardXp||task.reward);if(typeof raw==='number')return raw;var m=String(raw||'').match(/\d+/);return m?Number(m[0]):null;}
  function taskRow(result,fallback){return result&&result.value&&typeof result.value==='object'?result.value:(result&&typeof result==='object'&&!result.mode?result:fallback||null);}
  function installTasks(){if(!window.TaskSharedData||TaskSharedData.__activityProducerV1)return false;var rawCreate=TaskSharedData.create,rawUpdate=TaskSharedData.update;if(typeof rawCreate==='function')TaskSharedData.create=function(task){return Promise.resolve(rawCreate.apply(this,arguments)).then(function(result){var row=taskRow(result,task)||task,key=row&&(row._key||row.id);if(key)publish({type:'task.created',module:'tasks',entityType:'task',entityId:String(key),idempotencyKey:'task:'+key+':created',occurredAt:row.createdAt||now(),payload:{taskTitle:taskTitle(row),xpEarned:taskXp(row),difficulty:row&&row.priority||null}},'task.created');return result;});};if(typeof rawUpdate==='function')TaskSharedData.update=function(id,patch){patch=patch||{};return Promise.resolve(rawUpdate.apply(this,arguments)).then(function(result){var row=taskRow(result,null),local=(window.taskData||[]).find(function(t){return String(t.id)===String(id);});row=row||local;if(patch.done===true&&row&&row.done){var key=row._key||row.id||id,completionId=row.completedAt||patch.completedAt||row.updatedAt||now();publish({type:'task.completed',module:'tasks',entityType:'task',entityId:String(key),idempotencyKey:'task:'+key+':completion:'+completionId,occurredAt:completionId,payload:{taskTitle:taskTitle(row),xpEarned:taskXp(row),difficulty:row.priority||null}},'task.completed');}return result;});};TaskSharedData.__activityProducerV1=true;return true;}
  function installMeals(){if(!window.MealPlanStore||MealPlanStore.__activityProducerV1||typeof MealPlanStore.replaceSlot!=='function')return false;var raw=MealPlanStore.replaceSlot;MealPlanStore.replaceSlot=function(input){return Promise.resolve(raw.apply(this,arguments)).then(function(result){var r=result&&result.record?result.record:(input||{}),id=r.id||((r.date||input.date)+':'+(r.mealType||input.mealType||'dinner')),stamp=r.updatedAt||r.createdAt||now();publish({type:'meal.planned',module:'meals',entityType:'mealPlan',entityId:String(id),idempotencyKey:'meal:'+id+':planned:'+stamp,occurredAt:stamp,payload:{mealName:r.title||'Maaltijd',plannedDate:r.date||input.date,slot:r.mealType||input.mealType||'dinner',recipeId:r.recipeId||input.recipeId||null}},'meal.planned');return result;});};MealPlanStore.__activityProducerV1=true;return true;}
  function installReceipt(){if(!window.FinanceStore||FinanceStore.__activityProducerV1||typeof FinanceStore.upsertSourceTransaction!=='function')return false;var raw=FinanceStore.upsertSourceTransaction;FinanceStore.upsertSourceTransaction=function(config){return Promise.resolve(raw.apply(this,arguments)).then(function(record){if(config&&config.sourceType==='shoppingReceipt'){var tx=config.transaction||{},sourceId=config.sourceId||record&&record.sourceId||record&&record.id;if(sourceId)publish({type:'grocery.receipt_uploaded',module:'shop',entityType:'shoppingReceipt',entityId:String(sourceId),idempotencyKey:'receipt:'+sourceId+':uploaded',occurredAt:record&&record.updatedAt||record&&record.createdAt||now(),payload:{shoppingListName:tx.shoppingListName||'Boodschappen',itemCount:Array.isArray(tx.shoppingItemNames)?tx.shoppingItemNames.length:null}},'grocery.receipt_uploaded');}return record;});};FinanceStore.__activityProducerV1=true;return true;}
  function ensure(){installTasks();installMeals();installReceipt();return!!(window.TaskSharedData&&TaskSharedData.__activityProducerV1&&window.MealPlanStore&&MealPlanStore.__activityProducerV1&&window.FinanceStore&&FinanceStore.__activityProducerV1);}
  function stopPolling(){if(timer){clearInterval(timer);timer=null;}}
  function wake(){if(ensure()){stopPolling();return true;}if(timer)return false;tries=0;timer=setInterval(function(){tries++;if(ensure()||tries>=MAX_TRIES)stopPolling();},250);return false;}
  ['familyapp:modules:ready','familyapp:household-context-changed','familyapp:auth-ready','familyapp:meals:changed'].forEach(function(n){window.addEventListener(n,wake);});window.addEventListener('focus',wake);window.addEventListener('online',wake);window.addEventListener('load',wake,{once:true});Promise.resolve().then(wake);
  window.ActivityDomainProducers={version:VERSION,ensure:ensure,status:function(){return{tasks:!!(window.TaskSharedData&&TaskSharedData.__activityProducerV1),meals:!!(window.MealPlanStore&&MealPlanStore.__activityProducerV1),receipt:!!(window.FinanceStore&&FinanceStore.__activityProducerV1),polling:!!timer};}};
})();
