'use strict';
// STEP 13.1 compatibility facade. Canonical persistence/lifecycle authority is
// ActivityHouseholdRepository. Existing domain producer wrappers are retained
// temporarily and will be moved/audited explicitly in STEP 13.2.
(function(){
  if(window.HouseholdActivity)return;

  var TYPES=Object.freeze({TASK_CREATED:'task.created',TASK_COMPLETED:'task.completed',MEAL_PLANNED:'meal.planned',GROCERY_RECEIPT_UPLOADED:'grocery.receipt_uploaded'});
  var VISIBLE={};Object.keys(TYPES).forEach(function(k){VISIBLE[TYPES[k]]=true;});
  var state={events:[],unsubscribe:null,lastError:null,timer:null,tries:0};
  var MAX_BOOT_TRIES=240;

  function repo(){return window.ActivityHouseholdRepository||null;}
  function now(){return Date.now();}
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function members(){try{if(window.HouseholdIdentityFirebaseBridge&&typeof HouseholdIdentityFirebaseBridge.getMembers==='function')return HouseholdIdentityFirebaseBridge.getMembers()||[];if(window.TaskSharedData&&typeof TaskSharedData.members==='function')return TaskSharedData.members()||[];}catch(e){}return[];}
  function member(userId){return members().find(function(m){return String(m.uid||m.id)===String(userId);})||null;}
  function actorName(userId){var m=member(userId)||{};return m.displayName||m.name||'Gezinslid';}
  function stripReceiptAmounts(payload){var out=clone(payload||{})||{};['amount','total','totalAmount','price','cost','receiptTotal','value','currencyAmount'].forEach(function(k){delete out[k];});return out;}
  function shouldPublishToFeed(event){return !!(event&&VISIBLE[event.type]);}
  function normalize(input){input=clone(input||{})||{};var type=String(input.type||'');if(!VISIBLE[type])throw new Error('Onbekend activity type: '+type);var occurrenceKey=String(input.occurrenceKey||input.dedupeKey||'').trim();if(!occurrenceKey)throw new Error('Activity occurrenceKey ontbreekt');input.occurrenceKey=occurrenceKey;delete input.dedupeKey;if(type===TYPES.GROCERY_RECEIPT_UPLOADED)input.payload=stripReceiptAmounts(input.payload);input.presentation=Object.assign({variant:type.replace(/\./g,'-')},input.presentation||{});return input;}
  function publish(input){var r=repo();if(!r||typeof r.appendOnce!=='function')return Promise.reject(new Error('Activity repository is nog niet gereed'));var event;try{event=normalize(input);}catch(e){return Promise.reject(e);}return r.appendOnce(event).then(function(result){state.lastError=null;return result.event;}).catch(function(error){state.lastError=error&&error.message||String(error);throw error;});}
  function attach(){var r=repo();if(!r||typeof r.subscribe!=='function')return false;if(state.unsubscribe)return true;state.unsubscribe=r.subscribe(function(events){state.events=(events||[]).filter(shouldPublishToFeed);try{window.dispatchEvent(new CustomEvent('familyapp:activity-updated',{detail:{count:state.events.length}}));}catch(e){}});return true;}

  function taskTitle(task){return task&&(task.title||task.name)||'Taak';}
  function taskXp(task){var raw=task&&(task.xp||task.rewardXp||task.reward);if(typeof raw==='number')return raw;var m=String(raw||'').match(/\d+/);return m?Number(m[0]):null;}
  function taskRow(result,fallback){return result&&result.value&&typeof result.value==='object'?result.value:(result&&typeof result==='object'&&!result.mode?result:fallback||null);}
  function wrapTasks(){if(!window.TaskSharedData||TaskSharedData.__activityWrapped)return false;var rawCreate=TaskSharedData.create,rawUpdate=TaskSharedData.update;
    if(typeof rawCreate==='function')TaskSharedData.create=function(task){return Promise.resolve(rawCreate.apply(this,arguments)).then(function(result){var row=taskRow(result,task)||task,key=row&&row._key||row&&row.id;if(key)publish({type:TYPES.TASK_CREATED,occurrenceKey:'task:'+key+':created',source:{module:'tasks',entityType:'task',entityId:String(key)},payload:{taskTitle:taskTitle(row),xpEarned:taskXp(row),difficulty:row&&row.priority||null}}).catch(function(e){console.warn('[HouseholdActivity] task.created',e);});return result;});};
    if(typeof rawUpdate==='function')TaskSharedData.update=function(id,patch){patch=patch||{};return Promise.resolve(rawUpdate.apply(this,arguments)).then(function(result){var local=(window.taskData||[]).find(function(t){return String(t.id)===String(id);}),row=taskRow(result,local);if(patch.done===true&&row&&row.done){var key=row._key||row.id||id,completionId=patch.completedAt||row.completedAt||row.updatedAt||now();publish({type:TYPES.TASK_COMPLETED,occurrenceKey:'task:'+key+':completion:'+completionId,occurredAt:row.completedAt||completionId,source:{module:'tasks',entityType:'task',entityId:String(key)},payload:{taskTitle:taskTitle(row),xpEarned:taskXp(row),difficulty:row.priority||null}}).catch(function(e){console.warn('[HouseholdActivity] task.completed',e);});}return result;});};TaskSharedData.__activityWrapped=true;return true;}
  function wrapMeals(){if(!window.MealPlanStore||MealPlanStore.__activityWrapped||typeof MealPlanStore.replaceSlot!=='function')return false;var raw=MealPlanStore.replaceSlot;MealPlanStore.replaceSlot=function(input){return Promise.resolve(raw.apply(this,arguments)).then(function(result){var record=result&&result.record?result.record:(input||{}),id=record.id||((record.date||input.date)+':'+(record.mealType||input.mealType||'dinner'));publish({type:TYPES.MEAL_PLANNED,occurrenceKey:'meal:'+id+':planned:'+String(record.updatedAt||record.createdAt||now()),occurredAt:record.updatedAt||record.createdAt||now(),source:{module:'meals',entityType:'mealPlan',entityId:String(id)},payload:{mealName:record.title||'Maaltijd',plannedDate:record.date||input.date,slot:record.mealType||input.mealType||'dinner',recipeId:record.recipeId||input.recipeId||null}}).catch(function(e){console.warn('[HouseholdActivity] meal.planned',e);});return result;});};MealPlanStore.__activityWrapped=true;return true;}
  function wrapReceiptFinance(){if(!window.FinanceStore||FinanceStore.__activityWrapped||typeof FinanceStore.upsertSourceTransaction!=='function')return false;var raw=FinanceStore.upsertSourceTransaction;FinanceStore.upsertSourceTransaction=function(config){return Promise.resolve(raw.apply(this,arguments)).then(function(record){if(config&&config.sourceType==='shoppingReceipt'){var tx=config.transaction||{},sourceId=config.sourceId||record&&record.sourceId||record&&record.id;if(sourceId)publish({type:TYPES.GROCERY_RECEIPT_UPLOADED,occurrenceKey:'receipt:'+sourceId+':uploaded',source:{module:'shop',entityType:'shoppingReceipt',entityId:String(sourceId)},payload:{shoppingListName:tx.shoppingListName||'Boodschappen',itemCount:Array.isArray(tx.shoppingItemNames)?tx.shoppingItemNames.length:null}}).catch(function(e){console.warn('[HouseholdActivity] grocery.receipt_uploaded',e);});}return record;});};FinanceStore.__activityWrapped=true;return true;}
  function ensure(){attach();wrapTasks();wrapMeals();wrapReceiptFinance();return !!(state.unsubscribe&&window.TaskSharedData&&TaskSharedData.__activityWrapped&&window.MealPlanStore&&MealPlanStore.__activityWrapped&&window.FinanceStore&&FinanceStore.__activityWrapped);}
  function wake(){if(ensure()){if(state.timer){clearInterval(state.timer);state.timer=null;}return;}if(state.timer)return;state.tries=0;state.timer=setInterval(function(){state.tries++;if(ensure()||state.tries>=MAX_BOOT_TRIES){clearInterval(state.timer);state.timer=null;}},250);}
  ['familyapp:household-context','familyapp:household-identity-synced','familyapp:modules:ready'].forEach(function(name){window.addEventListener(name,wake);});window.addEventListener('load',wake,{once:true});Promise.resolve().then(wake);

  window.HouseholdActivity={version:'1.3.0',TYPES:TYPES,start:function(){wake();return true;},publish:publish,getEvents:function(){return state.events.slice();},shouldPublishToFeed:shouldPublishToFeed,resolveMember:member,actorName:actorName,status:function(){var r=repo();var s=r&&r.status?r.status():{};return{ready:!!s.ready,householdId:s.householdId||null,uid:s.uid||null,count:state.events.length,lastError:state.lastError,canonicalPath:s.canonicalPath||null,repositoryVersion:r&&r.version||null};}};
})();
