'use strict';
// ============================================================
// ACTIVITY SERVICE v2.1
// Canonical immutable household event layer.
// Modules publish domain events; Feed/Notifications consume them.
// ============================================================
(function(){
  if(window.ActivityService&&window.ActivityService.version==='2.1.0')return;
  var VERSION='2.1.0',COLLECTION='activity',LEGACY_COLLECTION='activityEvents';
  var TYPES=Object.freeze({TASK_CREATED:'task.created',TASK_COMPLETED:'task.completed',MEAL_PLANNED:'meal.planned',GROCERY_RECEIPT_UPLOADED:'grocery.receipt_uploaded',ACHIEVEMENT_UNLOCKED:'achievement.unlocked'});
  var ALLOWED={};Object.keys(TYPES).forEach(function(k){ALLOWED[TYPES[k]]=true;});
  var state={token:null,unsubscribe:null,events:[],ready:false,migrated:{},lastError:null};
  function fds(){return window.FamilyDataStore||null;}function hc(){return window.HouseholdContext||null;}function now(){return Date.now();}
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function captureReady(){var c=hc();if(!c)throw new Error('HOUSEHOLD_CONTEXT_UNAVAILABLE');var uid=c.requireUser(),householdId=c.requireHousehold();c.assertContext({uid:uid,householdId:householdId,requireReady:true});return{uid:uid,householdId:householdId};}
  function same(t){return!!(t&&hc()&&hc().isCurrent(t));}function assertToken(t){if(!same(t)){var e=new Error('ACTIVITY_CONTEXT_CHANGED');e.code='ACTIVITY_CONTEXT_CHANGED';throw e;}return t;}
  function safe(v){return String(v||'event').replace(/[.#$\[\]\/]/g,'_').replace(/[^a-zA-Z0-9:_-]/g,'_').slice(0,220);}
  function idFor(key){return'evt_'+safe(key);}function stripReceiptAmounts(payload){var out=clone(payload||{})||{};['amount','total','totalAmount','price','cost','receiptTotal','value','currencyAmount'].forEach(function(k){delete out[k];});return out;}
  function members(){try{if(window.HouseholdIdentityFirebaseBridge&&typeof HouseholdIdentityFirebaseBridge.getMembers==='function')return HouseholdIdentityFirebaseBridge.getMembers()||[];if(window.TaskSharedData&&typeof TaskSharedData.members==='function')return TaskSharedData.members()||[];}catch(e){}return[];}
  function resolveMember(uid){return members().find(function(m){return String(m.uid||m.id)===String(uid);})||null;}
  function actorName(uid){var m=resolveMember(uid)||{};return m.displayName||m.name||'Gezinslid';}
  function normalize(input,token){input=input||{};token=token||captureReady();var type=String(input.type||''),entityType=String(input.entityType||input.source&&input.source.entityType||'').trim(),entityId=String(input.entityId||input.source&&input.source.entityId||'').trim(),dedupeKey=String(input.idempotencyKey||input.dedupeKey||'').trim();if(!ALLOWED[type])throw new Error('Onbekend activity type: '+type);if(!entityType)throw new Error('Activity entityType ontbreekt');if(!entityId)throw new Error('Activity entityId ontbreekt');if(!dedupeKey)dedupeKey=type+':'+entityType+':'+entityId;var ts=Number(input.occurredAt)||now(),payload=type===TYPES.GROCERY_RECEIPT_UPLOADED?stripReceiptAmounts(input.payload):clone(input.payload||{});return{id:idFor(dedupeKey),schemaVersion:2,type:type,householdId:token.householdId,actorUid:token.uid,entityType:entityType,entityId:entityId,occurredAt:ts,createdAt:ts,visibility:'household',idempotencyKey:dedupeKey,dedupeKey:dedupeKey,source:{module:String(input.module||input.source&&input.source.module||''),entityType:entityType,entityId:entityId},payload:payload,presentation:{variant:String(input.presentation&&input.presentation.variant||type.replace(/\./g,'-'))}};}
  function rows(v){if(!v)return[];return Object.keys(v).map(function(k){var x=v[k];if(!x||typeof x!=='object')return null;var e=clone(x);if(!e.id)e.id=k;return e;}).filter(Boolean).sort(function(a,b){return Number(b.occurredAt||0)-Number(a.occurredAt||0);}).slice(0,100);}
  function publish(input){var token=captureReady(),s=fds();if(!s)return Promise.reject(new Error('ActivityService opslag niet beschikbaar'));var event;try{event=normalize(input,token);}catch(e){return Promise.reject(e);}assertToken(token);return s.mutateSharedRecord(COLLECTION,event.id,function(existing){return existing||event;},null).then(function(result){assertToken(token);state.lastError=result&&result.error?(result.error.message||String(result.error)):null;return result&&result.value?result.value:event;});}
  function migrateLegacy(token){var key=token.uid+':'+token.householdId;if(state.migrated[key])return Promise.resolve(false);state.migrated[key]=true;return fds().readShared(COLLECTION,{}).then(function(current){assertToken(token);if(current&&Object.keys(current).length)return false;return fds().readShared(LEGACY_COLLECTION,{}).then(function(old){assertToken(token);var legacy=rows(old);if(!legacy.length)return false;return Promise.all(legacy.map(function(e){var id=e.id||idFor(e.dedupeKey||e.idempotencyKey||('legacy:'+e.type+':'+(e.source&&e.source.entityId||now())));var migrated=Object.assign({},e,{id:id,schemaVersion:2,householdId:token.householdId,actorUid:e.actorUid||token.uid,entityType:e.entityType||e.source&&e.source.entityType||'legacy',entityId:e.entityId||e.source&&e.source.entityId||id,idempotencyKey:e.idempotencyKey||e.dedupeKey||id});return fds().writeSharedRecord(COLLECTION,id,migrated);})).then(function(){assertToken(token);return true;});});});}
  function stop(){if(state.unsubscribe)try{state.unsubscribe();}catch(e){}state.unsubscribe=null;state.token=null;state.events=[];state.ready=false;try{window.dispatchEvent(new CustomEvent('familyapp:activity-updated',{detail:{count:0}}));}catch(e){}}
  function start(){var token;try{token=captureReady();}catch(e){stop();return Promise.resolve(status());}if(state.token&&same(state.token)&&state.unsubscribe)return Promise.resolve(status());stop();state.token=token;return migrateLegacy(token).catch(function(e){if(e&&e.code!=='ACTIVITY_CONTEXT_CHANGED')console.warn('[ActivityService] legacy migration failed',e);}).then(function(){assertToken(token);state.unsubscribe=fds().subscribeShared(COLLECTION,function(value){if(!same(token))return;state.events=rows(value);state.ready=true;try{window.dispatchEvent(new CustomEvent('familyapp:activity-updated',{detail:{count:state.events.length,householdId:token.householdId}}));}catch(e){}},{});return status();}).catch(function(e){if(e&&e.code!=='ACTIVITY_CONTEXT_CHANGED')state.lastError=e.message||String(e);return status();});}
  function rebind(){stop();return start();}function shouldPublishToFeed(e){return!!(e&&ALLOWED[e.type]);}
  function status(){return{version:VERSION,ready:state.ready,context:state.token?clone(state.token):null,count:state.events.length,lastError:state.lastError,collection:COLLECTION};}
  window.ActivityService={version:VERSION,TYPES:TYPES,publish:publish,start:start,stop:stop,rebind:rebind,getEvents:function(){return state.events.slice();},shouldPublishToFeed:shouldPublishToFeed,resolveMember:resolveMember,actorName:actorName,status:status};
  window.HouseholdActivity=window.ActivityService;
  window.addEventListener('familyapp:household-context-changed',rebind);window.addEventListener('familyapp:session:cleared',stop);window.addEventListener('online',start);window.addEventListener('focus',start);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
