module.exports = async function handler(req, res) {
  const upstreamUrl = 'https://raw.githubusercontent.com/cverhoog-tech/VerhoogFamily/main/index.html';
  const upstream = await fetch(upstreamUrl, { headers: { 'User-Agent': 'FamilieApp-v042-quest-ui' } });
  let html = await upstream.text();

  const inject = `
<style>
.quest-overview-v42{padding:14px 16px 110px;background:#fbfcfb}.quest-stats-v42{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:18px}.quest-stat-v42{background:#fff;border-radius:18px;padding:12px;box-shadow:0 10px 28px rgba(17,24,39,.05)}.quest-stat-v42 b{font-size:24px;display:block}.quest-card-v42{display:flex;gap:12px;background:#fff;border-radius:22px;padding:10px;margin-bottom:10px;box-shadow:0 10px 28px rgba(17,24,39,.06)}.quest-thumb-v42{width:100px;min-width:100px;height:100px;border-radius:16px;background-size:cover;background-position:center}.quest-body-v42{flex:1}.quest-type-v42{font-size:10px;font-weight:900;color:#3f7f2f}.quest-title-v42{font-size:17px;font-weight:900;margin:5px 0}.quest-desc-v42{font-size:12px;color:#697386;line-height:1.3;margin-bottom:8px}.quest-meta-v42{display:flex;gap:6px;flex-wrap:wrap}.quest-meta-v42 span{font-size:11px;padding:4px 8px;border-radius:999px;background:#f4f4f5}.xp-v42{background:#edf8e9!important;color:#2f7f2e}.raid-card-v42{background:#17202b;color:#fff}.raid-card-v42 .quest-title-v42{color:#fff}.raid-card-v42 .quest-desc-v42{color:#cbd5e1}.quest-btn-v42{margin-top:10px;border:0;border-radius:14px;background:#6d4aff;color:#fff;padding:10px 12px;font-weight:900}
</style>
<script>
(function(){if(window.__v42)return;window.__v42=true;function q(s,r){return Array.from((r||document).querySelectorAll(s));}function txt(e){return(e&&e.textContent||'').toLowerCase();}function render(){var h=q('.header-title')[0];if(!h||txt(h).indexOf('taken')===-1)return;var tab=q('.ttab.active')[0];if(tab&&txt(tab).indexOf('overzicht')===-1)return;var root=document.getElementById('task-content')||q('.task-content')[0];if(!root||root.dataset.v42)return;root.dataset.v42='1';root.innerHTML='<div class="quest-overview-v42"><div class="quest-stats-v42"><div class="quest-stat-v42">Vandaag<b>4/8</b><small>quests voltooid</small></div><div class="quest-stat-v42">Level<b>12</b><small>450 / 800 XP</small></div><div class="quest-stat-v42">Streak<b>7</b><small>dagen op rij</small></div></div><div class="quest-card-v42"><div class="quest-thumb-v42" style="background-image:url(https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=700&q=90&fm=webp)"></div><div class="quest-body-v42"><div class="quest-type-v42">SIDE QUEST</div><div class="quest-title-v42">Stofzuigen woonkamer</div><div class="quest-desc-v42">Maak de woonkamer weer fris.</div><div class="quest-meta-v42"><span>4 mei</span><span>Esra</span><span class="xp-v42">+20 XP</span></div></div></div><div class="quest-card-v42"><div class="quest-thumb-v42" style="background-image:url(https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&w=700&q=90&fm=webp)"></div><div class="quest-body-v42"><div class="quest-type-v42">SIDE QUEST</div><div class="quest-title-v42">Planten water geven</div><div class="quest-desc-v42">Zorg dat alle planten genoeg hebben.</div><div class="quest-meta-v42"><span>5 mei</span><span>Esra</span><span class="xp-v42">+10 XP</span></div></div></div><div class="quest-card-v42"><div class="quest-thumb-v42" style="background-image:url(https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=700&q=90&fm=webp)"></div><div class="quest-body-v42"><div class="quest-type-v42">SIDE QUEST</div><div class="quest-title-v42">Auto wassen</div><div class="quest-desc-v42">Maak de auto van buiten en binnen schoon.</div><div class="quest-meta-v42"><span>6 mei</span><span>Shane</span><span class="xp-v42">+40 XP</span></div></div></div><div class="quest-card-v42 raid-card-v42"><div class="quest-thumb-v42" style="background-image:url(https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=700&q=90&fm=webp)"></div><div class="quest-body-v42"><div class="quest-type-v42" style="color:#a78bfa">RAID</div><div class="quest-title-v42">Kinderkamer chaos raid</div><div class="quest-desc-v42">Tijd om de chaos te verslaan. Samen sta je sterker.</div><div class="quest-meta-v42"><span>10 mei</span><span>2-4 spelers</span><span class="xp-v42">+120 XP</span></div><button class="quest-btn-v42">Start raid</button></div></div></div>';}
setInterval(render,1000);window.addEventListener('load',render);document.addEventListener('DOMContentLoaded',render);})();
</script>`;

  html = html.replace('</body>', inject + '</body>');

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.status(200).send(html);
};