'use strict';
// SKILLS PROGRESSION BRIDGE v3 - current Firebase UID only.
(function(){
  if(window.SkillsProgressionBridge)return;
  var VERSION='3.0.0',wrapped=false,renderTimer=null;
  function user(){try{return window.fbUser||(window.firebase&&firebase.auth&&firebase.auth().currentUser)||null;}catch(e){return null;}}function member(){var u=user();if(!u)return null;var members=window.FamilyHousehold&&FamilyHousehold.getMembers?FamilyHousehold.getMembers():[];return members.find(function(m){return m&&m.uid===u.uid;})||null;}function name(){var m=member(),u=user();return m&&m.name||u&&u.displayName||'Gebruiker';}function avatar(){var m=member(),u=user();return m&&m.avatar||u&&u.photoURL||'';}function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function sync(){if(!window.FamilyProgression||!FamilyProgression.isReady||!FamilyProgression.isReady())return false;var st=FamilyProgression.getState();if(!st)return false;var key=name();window.skillsData=window.skillsData||{};skillsData[key]={};Object.keys(st.skills||{}).forEach(function(id){skillsData[key][id]=JSON.parse(JSON.stringify(st.skills[id]));});window.skillsViewPerson=key;try{skillsViewPerson=key;}catch(e){}return true;}
  function injectCss(){if(document.getElementById('skills-progression-v3-css'))return;var s=document.createElement('style');s.id='skills-progression-v3-css';s.textContent='#skills-content .skills-person-tabs{display:none!important}.skills-v3-identity{display:flex;align-items:center;gap:12px;margin-bottom:12px}.skills-v3-avatar{width:50px;height:50px;border-radius:18px;overflow:hidden;display:grid;place-items:center;background:rgba(255,255,255,.2);font-weight:900}.skills-v3-avatar img{width:100%;height:100%;object-fit:cover}.skills-v3-uid{font-size:10px;opacity:.68;margin-top:3px}';document.head.appendChild(s);}
  function repair(){injectCss();var el=document.getElementById('skills-content');if(!el)return;el.querySelectorAll('.skills-person-tabs').forEach(function(n){n.remove();});var hero=el.firstElementChild,u=user();if(!hero||!u)return;var a=avatar(),n=name(),identity=hero.querySelector('.skills-v3-identity');if(!identity){identity=document.createElement('div');identity.className='skills-v3-identity';hero.insertBefore(identity,hero.firstChild);}identity.innerHTML='<div class="skills-v3-avatar">'+(a?'<img src="'+esc(a)+'" alt="">':esc(n.substring(0,2).toUpperCase()))+'</div><div><div style="font-size:20px;font-weight:900">'+esc(n)+' Skills</div><div class="skills-v3-uid">Persoonlijke progression · Firebase account</div></div>';}
  function schedule(){clearTimeout(renderTimer);renderTimer=setTimeout(function(){if(sync()&&typeof window.renderSkills==='function')window.renderSkills();repair();},60);}
  function wrap(){if(wrapped||typeof window.renderSkills!=='function')return false;var original=window.renderSkills;window.renderSkills=function(){sync();var r=original.apply(this,arguments);repair();return r;};wrapped=true;return true;}
  function boot(){injectCss();var tries=0,t=setInterval(function(){tries++;wrap();if(window.FamilyProgression&&FamilyProgression.isReady&&FamilyProgression.isReady()){schedule();if(wrapped)clearInterval(t);}if(tries>300)clearInterval(t);},100);['ready','xp','skill','levelup'].forEach(function(type){window.addEventListener('familyapp:progression:'+type,schedule);});window.addEventListener('familyapp:household-members-updated',schedule);window.addEventListener('familyapp:avatar-updated',schedule);}
  window.SkillsProgressionBridge={version:VERSION,boot:boot,sync:sync,repair:repair};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
